### PR TITLE
Fix #9270 by adding dependency in dev.txt

### LINKED ISSUE #9270: Error setting up environment with docker
## Observed behavior
When building the base docker image and installing python base requirements, some python dependency throws an error pointing out that the minimum version of python required is 3.5.

## Errors and logs

```
Downloading https://files.pythonhosted.org/packages/b7/81/c04fb9be62657d4dce8aa2d99fde258a3af1cd77ec72af525593e9560127/ruamel.yaml.clib-0.2.4.tar.gz (180kB)
    Complete output from command python setup.py egg_info:
    minimum python version(s): [(3, 5)]
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-CyxhF5/ruamel.yaml.clib/
The command '/bin/sh -c cd /kolibri     && pip install -r requirements/dev.txt     && pip install -r requirements/build.txt     && pip install -r requirements/test.txt     && yarn install --network-timeout 100000' returned a non-zero code: 1
make: *** [Makefile:260: docker-build-base] Error 1
```

## Expected behavior
Docker installs the system without errors in an simple way.

## Steps to reproduce
Run `make docker-build-base` as indicated in https://kolibri-dev.readthedocs.io/en/latest/getting_started.html#id2

## Context
* kolibri version: latest
* Operating system: Ubuntu 20.04 LTS
* Kernel: Linux 5.11.0-27-generic

### PR DESCRIPTION
**Pull request by Wck-iipi**
## Summary

"make docker-build-base" now runs without any error due to the inclusion of 0.2.2 version of ruamel.yaml.clib, which supports python 2.7. 

## References

Fixes #9270.

## Reviewer guidance

You can run "make docker-build-base" and see it works without any errors.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by MisRob** [comment]
Thank you for your contributions @Wck-iipi. Looking at the diff, it seems that this pull request contains changes from your other PR #10374 too. Could you please clean this PR so that it only contains work relevant to #9270?

**Comment by Wck-iipi** [comment]
@MisRob Sorry I forgot I didn't create a new branch for this. Now it only has one change.

**Comment by MisRob** [comment]
@Wck-iipi No worries, thanks

**Review by AlexVelezLl — APPROVED** [review]
Hi! I confirm this solves the issue. Docker build base now works as expected. Thanks @Wck-iipi!! 🚀

**Comment by jredrejo** [comment]
@Wck-iipi @AlexVelezLl the introduced version of  `ruamel.yaml.clib==0.2.2`   does not work with Python 3.10. It seems that's a bug for that library they[ solved in version 0.2.4](https://sourceforge.net/p/ruamel-yaml-clib/tickets/5/). 
Can you check if 0.2.4 works fine to solve #9270 ?
If it does not, we'll have to create a different requirements.txt to be used in Docker environments.

**Comment by Wck-iipi** [comment]
@jredrejo The problem with 0.2.4 is that it [doesn't work](https://pypi.org/project/ruamel.yaml.clib/0.2.4/) with Python2.7. In the docker-base file, python2.7 is used. I include 0.2.2 of ruamel.yaml.clib because it is the last version that supports python2.7. I can create a different requirements.txt for the Docker environment if you want, as I think this may be the only solution for future versions of python. We can also just add `RUN pip install ruamel.yaml.clib==0.2.2` in docker-base, and just remove it when the version of python gets update.

**Comment by jredrejo** [comment]
@Wck-iipi  in that case we'll have to revert this PR and create a dev.txt exclusively for Docker (in Docker environments using python <3.10) because currently the dev is unusable with python >=3.10

**Comment by Wck-iipi** [comment]
@jredrejo Created a [pull request](https://github.com/learningequality/kolibri/pull/10413) doing this. Tell me if it has any issues.

**Pull request merged**
