### PR TITLE
Use markdown-it to render content descriptions

### PR DESCRIPTION
**Pull request by divad12**
## Summary

Some of the descriptions we scrape have newlines that we'd like to preserve. For example, in Touchable Earth, each video an "Info" and "Transcript" field. We scrape both fields and concatenate them together with a `\n\n` separator to render for the description in Kolibri. By rendering with Markdown, these newlines can be preserved, while ensuring we don't inject raw source HTML into the page (the Markdown parser sanitizes the input and doesn't output any input HTML).

For now we're only using the Markdown parser to render line breaks, because we don't want to introduce too many new features at once and this is all we need at the moment, while at the same time we have the flexibility to expand the scope of the formatting we support.

## Test plan

- hardcode the following text inside of `md.render();` in `computed.description()`: `Hello, here is some text.\n\nThis text on a new line.\n\n**This should not be bolded.** <b>Nor should this! And this text should be surrounded by HTML tags!</b>`
- open a content node in Kolibri
- ensure that we see the following output:
> Hello, here is some text.
>
>This text on a new line.
>
>\*\*This should not be bolded.\*\* \<b>Nor should this! And this text should be surrounded by HTML tags!\</b>

## Reviewer guidance

Note that I have only tested with the Touchable Earth channel. I don't have other channels imported into my local Kolibri server; I'd be happy to test on more channels if you'd deem that helpful. Just let me know how I can import more channels to test on, or if you could help me with the testing, that'd be great too. :)

Also, on Slack @jamalex mentioned that we might like to get this into the 0.5.x patch. Would that mean merging this PR into `release-v0.5.x`, or is there another process for doing that?

## Issues addressed

Addresses #1782

### Before

image

### After
image

("TRANSCRIPT:" is on its own line.)

### CODE REVIEW

**Comment by divad12** [comment]
Review please, @jamalex or @rtibbles ?

**Comment by indirectlylit** [comment]
Thanks, @divad12!

FYI, during the dev meeting on monday we had discussed limiting the handling to just end-lines, and _not_ allowing bolded text (or other markdown syntax) in descriptions: https://docs.google.com/document/d/1A1WMhU8bcU7c_hvnevWszSrpDkEU3AXYdCnlml5uioQ/edit#heading=h.hz5lkwba4vm6

**Comment by divad12** [comment]
Thanks for mentioning that @indirectlylit . Wondering what the rationale was for that? Happy to switch to implementing just handling newlines if that would be preferred over the current Markdown implementation.

**Comment by indirectlylit** [comment]
IIRC, we mainly wanted to introduce new features like that slowly:

* design-wise, unclear what formatting is appropriate in descriptions and all the places they might end up being used
* don't want people relying on something we might not want to support - in this case a very small subset of markdown
* risk of adding dom elements (headers, link, etc) inside description blocks

I don't think it's off the table entirely, but my understanding is that the critical update here is handling of newlines.

I believe @ivanistheone may have been tackling part of this from the Ricecooker side?

**Comment by rtibbles** [comment]
Another option would be to use the underlying `markdown-it` library that `vue-markdown` uses (the component is an exceedingly thin wrapper) - which allows rules to be turned on or off, this would give us the flexibility going forward to expand the ruleset if desired, without having to reinvent the wheel in a fit of NBH.

**Comment by jamalex** [comment]
It would be great if vue-markdown had a whitelist/blacklist of allowed markup types, so we can be selective but still leverage it, but it doesn't look as if it does. But if markdown-it does, then that sounds great.

If there are any issues with doing that, a simple alternative would be to do the `\n` -> `<br >` replacement, after safely escaping the text, and then inserting it as HTML. But there would be value down the road in having a reusable Vue component (that allows whitelisting of rules), for content formats like "articles" or our own exercise renderer, so perhaps it's worth starting one?

**Comment by rtibbles** [comment]
`vue-markdown` does not have that capability, but `markdown-it` does, and `vue-markdown` is a very thin wrapper, so it would not be a huge job of work to use it directly.

**Comment by divad12** [comment]
Thanks for the discussion all. I've updated this to use `markdown-it` as suggested by @rtibbles and only enabling line breaks. Tested that source HTML gets escaped and only source `\n\n` gets formatted while source markdown formatting (e.g. `**bold**`) doesn't.

**Comment by rtibbles** [comment]
This looks good - two things, you will need to run the linter on `content-page.vue` in order to have the Travis build pass.

Easiest way to do this is to install the pre-commit hooks in the repo using `pre-commit install` (should be in the Python dev dependencies).

Also, could you rebase this onto `release-v0.5.x` branch and retarget the PR there - Touchable Earth content (with their markdown descriptions) will be wanted by partners using that release.

**Comment by divad12** [comment]
@rtibbles ran linter and rebased + retargetted onto `release-v0.5.x` branch. Take a look again when you get the chance?

**Comment by divad12** [comment]
Thanks @rtibbles . And if or when would this PR be merged into `develop`?

**Pull request merged**
