### PR TITLE
Show content metadata

### PR DESCRIPTION
**Pull request by christianmemije**
### Summary

Show content metadata

### Reviewer guidance

Double check.

----

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Review by DXCanas — APPROVED** [review]
Fetching this kind of info from state isn't ideal IMO, but this works!

**Comment by DXCanas** [comment]
Wait - is this the right branch @indirectlylit?

**Review by indirectlylit — APPROVED** [review]

**Comment by indirectlylit** [comment]
if it's broken in 0.9 we should put it there and back-port it

**Comment by indirectlylit** [comment]
fixes https://github.com/learningequality/kolibri/issues/3839

**Pull request merged**
