### PR TITLE
Added download content functionality.

### PR DESCRIPTION
**Pull request by christianmemije**
## Summary

Added download content functionality.

## TODO

- [ ] Test on mobile devices.
- [ ] Styling.

## Reviewer guidance

* Opinions on this method of downloading files? I made use of [download.js](https://github.com/rndme/download). 
* In terms of sanitizing filenames, pretty basic but gets the job done. The 20 char limit is just a magic number.

## Screenshot

screenshot from 2016-07-29 14-56-40

### CODE REVIEW

**Comment by indirectlylit** [comment]
I would recommend moving both these files into a sub-directory. So then you would have:

```
kolibri/core/assets/src/content-renderer/index.vue
kolibri/core/assets/src/content-renderer/download.js
```

This makes it clearer that download.js is only used by the content-renderer.

**Comment by indirectlylit** [comment]
Doesn't seem to work in IE9. We need to have that eventually but it's not a requirement for MVP

**Comment by christianmemije** [comment]
Leave content_renderer_module.js outside, or also put into the directory. I'll check that out.

**Comment by indirectlylit** [comment]
looks like `content_renderer_module` is referenced by other plugins and has special webpack resolution logic, so that should be left where it is

**Comment by christianmemije** [comment]
I will continue to work on this so do not merge yet.

**Pull request merged**
