### PR TITLE
Catch signal handler attachment error.

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
Reinstate behaviour that was omitted.

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by kollivier — APPROVED** [review]
If at first you don't succeed, just pass. LGTM!

**Comment by indirectlylit** [comment]
tested mac installer. It does seem to get further in the process than it did in #6125 

still not loading completely but this seems to be an improvement

image

**Comment by radinamatic** [comment]
Tested in Mojave 10.14, app seems to get blocked at the same step as for @indirectlylit, loading in the browser was also unsuccessful, plus there's this weird alert to install git:

**Comment by radinamatic** [comment]
...and no change in Windows:

**Comment by indirectlylit** [comment]
> Tested in Mojave 10.14, app seems to get blocked at the same step as for @indirectlylit 

https://github.com/learningequality/kolibri-installer-mac/issues/15

> loading in the browser was also unsuccessful, plus there's this weird alert to install git

@radinamatic if this is reproducible, would you mind opening an issue for it in https://github.com/learningequality/kolibri-installer-mac/

> ...and no change in Windows:

we have a bunch of changes landing for Windows soon. Will re-test after

**Comment by radinamatic** [comment]
Updated the issue on the macApp repo, Windows side has been resolved in the meantime!

**Pull request merged**
