### PR TITLE
Calculate ContentNode file sizes in one aggregation query

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

Calculates the Content Node Filesizes using one aggregation query instead of two. 

### Reviewer guidance

1. Check to see if the changes make sense and are consistent with original implementation
1. Maybe do some profiling to see if this improves the performance for this endpoint?

### Contributor Checklist

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] Contributor has fully tested the PR manually
- [ ] Screenshots of any front-end changes are in the PR description
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by rtibbles** [comment]
Could you do tests with Django Debug Panel to see how this affects the query performance? http://kolibri-dev.readthedocs.io/en/develop/references/manual_testing.html#performance-testing-with-django-debug-panel

**Comment by lyw07** [comment]
Testing with Django Debug Panel now, I will post the result here after.

**Comment by lyw07** [comment]
I just tested this with Django Debug Panel and compared the result with the previous implementation. The results of both implementations are the same.

Here is the result of this PR:
screen shot 2018-01-10 at 6 45 37 pm

Here is the result of previous implementation:
screen shot 2018-01-10 at 6 42 51 pm

I tested this by creating a channel (`3cadf81863d9411fa93aa35732b30613`) with two files uploaded and importing only one topic that contains one file. 
I guess it may be because ".aggreate(total= , on_device=)" is still doing two aggregation queries?

**Comment by rtibbles** [comment]
I think you're right, @lyw07. If we want to optimize this query, would be good to take a look at what those 22 SQL queries are (should be able to get that breakdown on the Debug Panel). It may be that some judicious prefetching might reduce the number of queries here.

Would also be good to look at how the number of queries scales with a larger channel (if prefetching is helpful, it may be that the number of queries is scaling geometrically).

**Comment by indirectlylit** [comment]
Since the performance stays the same, but complexity slightly increases, should we close this PR?

**Comment by indirectlylit** [comment]
but maybe keep the comment :)

**Comment by jonboiser** [comment]
It looks like the `.aggregate()` with two kwargs is just sugar...

Is there something like "partition" in SQL? For example in JS I might do something like this:

```
const [availableFiles, notAvailableFiles] = partition(files, file => file.available)
// code to sum over the file sizes
```

**Comment by rtibbles** [comment]
You can do GROUP BY - which might allow this to happen with a single SQL statement, but given that this query is executing 22 SQL queries already, I think inspecting those to see where the low hanging fruit for optimization is would be the best way forward.

**Pull request closed without merging**
