### PR TITLE
Triggered android builds

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

Replacing android build script with a triggered build in the Android repo. Using some fancy YAML to add to an anchor. 

### Reviewer guidance

Check the build to ensure that the Android build was triggered and blocked by default.

### References

#6411 should be deprecated in favor of this

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by lyw07** [comment]
I can confirm that the android build was triggered and blocked by default. but the build is considered failed due to the failed android build. I will re-open my PR so that we can have the builds pass temporarily in case you don't have time to work on this before the release. Thank you! :)

**Comment by kollivier** [comment]
@DXCanas I merged @lyw07 's PR to temporarily disable the Android build (#6411), as even if we can get Android to build, it will not start the server due to 0.13 changes in terms of the CLI API. I don't think this is a good time to keep fighting with the Android build.

**Comment by indirectlylit** [comment]
ref: https://github.com/learningequality/kolibri/issues/6420

**Comment by lyw07** [comment]
moving this PR to 0.13.1 milestone as we are not going to release apk for 0.13.0. Please let me know if there are any problems with changing the milestone. Thank you!

**Comment by DXCanas** [comment]
This has become pretty stale. Think I'm going to try and bring it in with MacOS down the line instead ✌️

**Comment by indirectlylit** [comment]
okay thanks

**Pull request closed without merging**
