### PR TITLE
fix handleConfirmDelete issues in SectionEditor

### LINKED ISSUE #12532: EQM - Add new section/Edit Section - The 'Section settings' modal remains open after clicking 'Delete section'
## Observed behavior

When adding a new section or editing it if I click the 'Delete section' button, then the 'Section settings' remains open and cannot be closed by the user so that the user is forced to reload the page resulting in loss of any unsaved changes.

Video:

https://github.com/user-attachments/assets/0da1924f-3698-4744-8a67-8ac069c76663

## Expected behavior

The 'Section settings' modal should disappear.

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/releases/tag/v0.17.0-rc2
2. Create a new quiz.
3. Click the 'Add section' button and then click the 'Delete section' button.
4. Alternatively after having already added a section click the 'Options' button, select 'Edit section' and click 'Delete section'.

## Usage Details
Ubuntu 22  - Chrome
Windows 11 - Edge

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Summary

Cherry-picks the commit that fixes a regression in section deletion.

An error remained for me re: 'avoiding redundant navigation' but saw no UX issues due to this.

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
Code changes make sense, I will let manual QA have the final word here!

**Comment by radinamatic** [comment]
All possible quiz sections changes (renaming, reordering, moving questions around, adding more, etc.) combined with the section deletion, were performed and completed without UI errors. 

`Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location` error did appear in the console, but with no apparent user-facing consequences.

**Review by radinamatic — APPROVED** [review]
LGTM! 👏🏽 💯 :shipit:

**Comment by rtibbles** [comment]
Had a quick conversation with @nucleogenesis about the possible provenance of the problematic navigation, and it seems like it's not hiding anything further.

**Pull request merged**
