### PR TITLE
changed all kds imports and removed kds logic from apiSpec.js

### LINKED ISSUE #11561: Use consistent KDS imports across the whole Kolibri
There are currently two ways we import KDS (Kolibri Design System) logic (e.g. a component, a mixin, a composable) to Kolibri:

**(1) Via `kolibri.coreVue`**

First, a piece of KDS logic, in this example `UiIconButton`, is imported from `kolibri-design-system` and registered in [apiSpec.js
](https://github.com/learningequality/kolibri/blob/4de6c2fbd8924b1ec82f9c8555ed9aedb772bb61/kolibri/core/assets/src/core-app/apiSpec.js)

https://github.com/learningequality/kolibri/blob/4de6c2fbd8924b1ec82f9c8555ed9aedb772bb61/kolibri/core/assets/src/core-app/apiSpec.js#L22

https://github.com/learningequality/kolibri/blob/4de6c2fbd8924b1ec82f9c8555ed9aedb772bb61/kolibri/core/assets/src/core-app/apiSpec.js#L192

This makes it available in the whole Kolibri for import from `kolibri.coreVue`:

https://github.com/learningequality/kolibri/blob/4de6c2fbd8924b1ec82f9c8555ed9aedb772bb61/kolibri/plugins/learn/assets/src/views/QuizRenderer/index.vue#L160

**(2) Directly**

The other approach imports a piece of KDS logic, in this example `UiAlert`, to a Kolibri component directly from the `kolibri-design-system` package:

https://github.com/learningequality/kolibri/blob/4de6c2fbd8924b1ec82f9c8555ed9aedb772bb61/kolibri/plugins/learn/assets/src/views/QuizRenderer/index.vue#L159

## Goal

The goal of this issue is to use approach (2) everywhere. Using direct imports from KDS will ensure consistency and make it clear where code is being imported from.

## Acceptance criteria

- [ ] All JavaScript `coreVue` imports for KDS are replaced by direct imports in all Kolibri files
- [ ] All related KDS logic is removed from `apiSpec.js`

## Out of scope

Note that we also use direct KDS styles imports, for example `@import '~kolibri-design-system/lib/styles/definitions';`. Dealing with these Sass imports is not in the scope of this issue and they can stay as are.

## Guidance

1. Search the codebase for [api spec `kolibri.coreVue` imports](https://github.com/search?q=repo%3Alearningequality%2Fkolibri+from+%27kolibri.coreVue&type=code)
2. If an imported piece of KDS logic is registered in `apiSpec.js`, remove it.
3. Replace the `coreVue` import with the direct import

### PR DESCRIPTION
**Pull request by Abhinav1148**
## Summary
changed all KDS imports and removed KDS logic from apiSpec.js

## References
fixes: #11561

## Reviewer guidance

…

----

## Testing checklist

- [X ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by nucleogenesis — APPROVED** [review]
I checked out the branch and did some grep searches to search for possible misses among the many files that needed changed and it looks like this has made the changes needed throughout.

Thank you @Abhinav1148 for this!

**Comment by Abhinav1148** [comment]
> I checked out the branch and did some grep searches to search for possible misses among the many files that needed changed and it looks like this has made the changes needed throughout.
> 
> Thank you @Abhinav1148 for this!

You're welcome @nucleogenesis !! And please let me know if any changes are needed in this PR, I am open for suggestions.
And I would like to work more with this organization so please guide me for solving more issues

**Comment by MisRob** [comment]
I'm sorry but as posted to the issue this is already resolved by a person who was assigned to an issue https://github.com/learningequality/kolibri/pull/11742

**Comment by MisRob** [comment]
https://github.com/learningequality/kolibri/pull/11742 was waiting for merge only because of unrelated docs check failure. @Abhinav1148 please check out my comment in the issue I left for you so next time we can prevent from this situation. I am really really sorry for extra work.

**Comment by MisRob** [comment]
@Abhinav1148

>  And please let me know if any changes are needed in this PR, I am open for suggestions.
And I would like to work more with this organization so please guide me for solving more issues

We enjoy and appreciate collaboration with volunteers. You can find guidance in the [contributing guidelines](https://github.com/learningequality/kolibri/blob/develop/CONTRIBUTING.md), including the steps to get assigned to an issue that I mentioned to you in https://github.com/learningequality/kolibri/pull/11742. It's unfortunate this is your first experience here. Let us know if you find a good issue to work on if you're still interested. You will find links to them in the guidelines. ff you'd like to start with something simpler, focus on "good first issue"s. If there's not a suitable and free first issue, you can post to GitHub Discussions https://github.com/learningequality/kolibri/discussions/categories/community and we will see if we can open a new one.

**Comment by MisRob** [comment]
@nucleogenesis in any case, thanks for pro-active review, I appreciate that too.

**Pull request closed without merging**
