### PR TITLE
frontend architecture docs correction re: default sass import

### PR DESCRIPTION
**Pull request by nucleogenesis**
This is a super simple update. I came across this error while grepping for the proper path for some other use and saw the docs were wrong.

### CODE REVIEW

**Comment by nucleogenesis** [comment]
@radinamatic I've not done much with docs lately - have you seen failures like this from simple changes before? (cc @rtibbles)

**Comment by radinamatic** [comment]
I see nothing in your edits that would warrant this error, but during the release last month there must have been some rushed merge of the changes in the `CHANGELOG.md`, that introduced non-kosher formatting that is provoking this error. I suggest you delete the [repeated `###` in line 26](https://github.com/learningequality/kolibri/blob/release-v0.15.x/CHANGELOG.md?plain=1#L26), and properly format the lists of PRs below, to see if that resolves the error.

This also causes those PR titles to appear in the docs TOC:

Selection_002

**Review by rtibbles — APPROVED** [review]

**Comment by rtibbles** [comment]
Docs failure is now fixed on release-v0.15.x merging this.

**Comment by radinamatic** [comment]
The proper format of the lists of PRs in the 0.15 section is still pending, and therefore PR titles continue to appear in the ToC (built the project 2 times on RTD to be sure it's not cached).

I'll fix that in a separate PR.

**Comment by rtibbles** [comment]
Is the bulleting here not sufficient to fix that? https://github.com/learningequality/kolibri/blob/release-v0.15.x/CHANGELOG.md#fixed

**Comment by radinamatic** [comment]
You're correct, it should have been...
At this point the only difference I see from the 0.14 section is the indentation 🤔

**Comment by radinamatic** [comment]
Or rather it most probably would be sufficient, if it was on the `develop` branch, from where the dev docs are built on RTD... 😅 

Selection_130

**Pull request merged**
