### PR TITLE
Hide the table when data is loading

### PR DESCRIPTION
**Pull request by muditchoudhary**
## Summary

Hides the table when `this.dataLoading` is true in `coreTable.vue`

kolibri

## References

#10993 

## Reviewer guidance

Visit the Group section under plan under Coach in Kolibri. Throttle the network to slow 3g.

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by MisRob** [comment]
Thanks @muditchoudhary!

@pcenov Could you please preview several random tables in Kolibri and see if you can spot any regressions of loading states and displaying of table data afterwards?

**Review by MisRob — APPROVED** [review]
Code is looking good to me. Let's wait for QA results before merging.

**Comment by pcenov** [comment]
Hi @MisRob this is implemented as specified and I didn't observe any regressions. Just a clarifying question - is this change supposed to be made for other tables as well such as the Groups table under Coach > Reports because now the tables are hidden while loading only at Coach > Plan?

**Comment by MisRob** [comment]
@pcenov This particular change addresses just some edge cases - it ensures that data are not displayed simultaneously with a loader and it will affect all tables in Kolibri.

**Comment by MisRob** [comment]
> Just a clarifying question - is this change supposed to be made for other tables as well such as the Groups table under Coach > Reports because now the tables are hidden while loading only at Coach > Plan?

@pcenov This sounds like one of the existing inconsistencies in loading states in Coach. I assume it's present before this PR?

**Comment by pcenov** [comment]
@MisRob that's precisely what I mean - the table issues at Coach > Reports are preexisting so I was wondering whether they will be fixed with a separate PR.

**Comment by MisRob** [comment]
@pcenov I think so, but if you could upload a recording, that'd be helpful so I know exactly what problems you mean. We can then transfer it to a new issue if needed.

**Comment by pcenov** [comment]
Yeah, sure - here's the video comparing what I see while I am at Coach > Plan vs Coach > Reports:

https://github.com/learningequality/kolibri/assets/79847249/83ebdb1c-28a7-4243-a264-7ce73addce11

**Comment by MisRob** [comment]
Ah yes, thank you. I think that's one of the consequences of https://github.com/learningequality/kolibri/issues/11219 and not directly to work in this PR.

**Comment by MisRob** [comment]
I am linking it to #11219

**Review by pcenov — APPROVED** [review]
Thank you @MisRob, in that case I am going to approve this one and we can track the other changes separately.

**Pull request merged**
