### PR TITLE
enables sync button in sync modal

### LINKED ISSUE #10758: Update Sync All Facilities Modal to allow unregistered facilities to sync
## Observed behavior

When pressing `Sync All` to open `Sync all facility data ` modal, the `sync` submission is disabled with the tooltip message 'There are no registered facilities on this device'. Because facilities could already be registered and may not know until they are synced, the `sync` button should not be disabled and the tooltip message should be removed.. 

The message 'You must be connected to the internet' is also incorrectly displayed.

Screenshot 2023-05-30 at 11 58 07 AM

## Expected behavior

When `Sync All` button is pressed, the `sync` button should not be disabled on the opened modal. If user is connected to the internet, the message 'You must be connected to the internet' should not be displayed.

## User-facing consequences

Users are unable to sync unregistered facilities when clicking `Sync all`.

## Steps to reproduce

1. Navigate to Device > Facilities
2. Select `Sync all`
3. If facility is unregistered, the `sync` button is disabled and on hover, the message 'There are no registered facilities on this device' is displayed

### PR DESCRIPTION
**Pull request by akolson**
## Summary

This pr enables the previously disabled `Sync` button in the facility syncing modal. It also corrects the display of the `You must be connected to the internet` message to only show when an internet connection is not available. The sync button is additionally disabled when there is no internet connection available. Finally, the tooltip has been removed.

**Before:**
image

**After:**
Screenshot 2023-06-01 at 12 53 22

Screenshot 2023-06-01 at 12 54 10

## References

Fixes https://github.com/learningequality/kolibri/issues/10758

## Reviewer guidance

- Navigate to `Device > Facilities`
- Select `Sync all`
- A syncing modal will open. Proceed to click the Sync button to start the syncing process
- `You must be connected to the internet` message is displayed when you set your connection to offline
----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by akolson** [comment]
Tagging @jtamiace @tomiwaoLE  to advise on
image
IMO, it probably doesn't make sense to to display the `You must be connected to the internet` message and disable the  since we already have a global snackbar handling connectivity announcements that also prevents interaction with any interfaces underneath.

**Comment by bjester** [comment]
> IMO, it probably doesn't make sense to to display the You must be connected to the internet message and disable the since we already have a global snackbar handling connectivity announcements that also prevents interaction with any interfaces underneath.

@akolson The client browser's connectivity isn't the same as Kolibri's connectivity. You of course could run Kolibri locally, be connected to Kolibri, but have no internet connection. That said, the string could/should be reworded along those lines for clarification.

**Review by pcenov — CHANGES_REQUESTED** [review]
Hi @akolson, my understanding is that the message `You must be connected to the internet.` should be displayed not when the server is in a disconnected state but when the server is running while the person's device is with no internet access and therefore cannot sync with KDP.
See the following video:

https://github.com/learningequality/kolibri/assets/79847249/9388afa4-1982-4ef4-840a-1b5e8b90aeaa

**Review by nucleogenesis — APPROVED** [review]
Code LGTM!

**Comment by akolson** [comment]
@bjester @jredrejo do we have an implementation that checks for the availability of KDP? There's a ToDo comment regarding this in the modal, just wondering if anything was ever implemented

**Comment by jredrejo** [comment]
> @bjester @jredrejo do we have an implementation that checks for the availability of KDP? There's a ToDo comment regarding this in the modal, just wondering if anything was ever implemented

No, we don't, as far as i'm aware

**Comment by bjester** [comment]
> do we have an implementation that checks for the availability of KDP?

We don't currently but with the new [`is_local`](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/discovery/models.py#L87) field and when https://github.com/learningequality/kolibri/issues/10431 is completed, we can optimize this and use the existing network location API

**Comment by akolson** [comment]
Changes have been made following @pcenov 's feedback:

https://github.com/learningequality/kolibri/assets/5203639/0a97c5a0-5788-473d-904f-e600d3080f90

As a follow up to fully resolve this issue, there is need to check for;

1. Device's internet connectivity(implemented with this pr)
2. KDP's availability, a task that will follow once [this comment](https://github.com/learningequality/kolibri/pull/10765#issuecomment-1572486054) has been addressed

**Review by pcenov — APPROVED** [review]
Excellent @akolson, this is implemented as specified now.

**Pull request merged**
