### PR TITLE
apply 'Black' formatter

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

* apply formatting
* add pre-commit hook
* updates to docs

### Reviewer guidance

* should we do this?
* is this the right time to do this?

### References

https://github.com/ambv/black

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by jredrejo** [comment]
I like Black and use it when developing my code, but I don't think applying it massively to the whole code base is a good idea as we are losing a good part of the git history with it, together with the utility of `git blame`.
I would prefer to have it applied for new changes instead.

Also, as far as I know it only works with Python 3.x, so having it as a mandatory or pre-commit hook will force everybody to use python 3.x for development. That might not be a bad thing, but it's good to remark it.

**Comment by indirectlylit** [comment]
thanks @jredrejo - very good feedback

> I would prefer to have it applied for new changes instead.

Yeah, I had a similar thought and this is definitely a possibility. It may be that applying it globally doesn't have a huge benefit.

The main reason I like doing it all at once is to avoid this scenario:

* I open up a file that hasn't been edited in a while
* I make one small change
* Black makes a dozen other changes and screws up my little diff

We did a similar 'big bang' reformat with Prettier in the front-end (#1726) and it hasn't caused more issues in practice than any other refactor might. The previous commit is always a click away at least in github: 

image

> Also, as far as I know it only works with Python 3.x, so having it as a mandatory or pre-commit hook will force everybody to use python 3.x for development. That might not be a bad thing, but it's good to remark it

Kind of, but not quite. Py2 and Py3 need to both be available on the path, but you can still develop in Py2.

Turns out that pre-commit runs its hooks in separate virtual environments, so the dev environment can be Py2 and still use Black: https://github.com/learningequality/kolibri/pull/5286/files#diff-82c3b36709926de3a1b27bea0d8258ccR2

Made a note of this here: https://github.com/learningequality/kolibri/pull/5286/files#diff-9bc8bf6e8d9db020cefce1fbc0426795R77

**Comment by rtibbles** [comment]
I am fine with the big bang reformat, for much the reasons you outline @indirectlylit.

I think now would be a good time to bring our pre-commit hooks and our pylinting test build into line as well. At the moment, our pre-commit hooks are more rigorous than our pylint test step, could you also update our pylinting travis steps to apply all of the pre-commit hooks as well, so that we enforce as well as facilitate the linting?

**Comment by aronasorman** [comment]
> Turns out that pre-commit runs its hooks in separate virtual environments, so the dev environment can be Py2 and still use Black: https://github.com/learningequality/kolibri/pull/5286/files#diff-82c3b36709926de3a1b27bea0d8258ccR2

TIL! That makes it significantly more palatable on Studio too.

**Comment by indirectlylit** [comment]
> could you also update our pylinting travis steps

I'll take a look at that. I also wanted to update our devserver to format in real-time, similar to prettier, when developing in py3

**Comment by rtibbles** [comment]
> I also wanted to update our devserver to format in real-time, similar to prettier, when developing in py3

Could we use the virtualenv trick from the precommit hook to run the formatter in real time regardless of which virtualenv you were currently in?

**Comment by indirectlylit** [comment]
maybe if we can find where `pre-commit` stores its venv and then hack into those site-packages, but it feels a bit wrong to mess with those internals...

**Comment by indirectlylit** [comment]
suppose we could try to mimic what pre-commit does. sounds like a lot of effort :)

**Comment by indirectlylit** [comment]
Updated PR to resolve conflicts and apply formatting.

Haven't yet added Travis or devserver live update support, but perhaps should do these in a second PR?

**Comment by rtibbles** [comment]
Can also do each in a separate PR, fine by me.

**Review by rtibbles — APPROVED** [review]

**Pull request merged**
