### PR TITLE
0.15 into develop

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
Cascade merge.

Conflicts:
```
#	AUTHORS.md
#	kolibri/__init__.py
#	kolibri/core/content/api.py
#	kolibri/core/logger/api.py
#	kolibri/core/logger/test/test_api.py
#	kolibri/core/tasks/storage.py
#	kolibri/plugins/coach/assets/src/modules/exerciseDetail/handlers.js
#	kolibri/plugins/facility/assets/src/views/UserTable.vue
#	requirements/base.txt
#	yarn.lock
```

### CODE REVIEW

**Review by marcellamaki — COMMENTED** [review]
I did a code review focusing just on front-end files and I do not see any major problems there. I also ran locally and smoke tested, without issue. The only problem I noticed was this error in the console (which did not seem to prevent compilation?) which is for a dependency that was removed in  the `yarn.lock` changes. I would appreciate if someone else can retest and see if this is consistently an issue, or if it might just be me.

Also, code review of the python heavy changes would be helpful 😄 

> [hashi-dev] ERROR in ./src/iframe.js
[hashi-dev] Module build failed (from ../../node_modules/babel-loader/lib/index.js):
[hashi-dev] Error: [BABEL]: Cannot find module '@babel/helper-get-function-arity'
[hashi-dev] Require stack:
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/traverse/node_modules/@babel/helper-function-name/lib/index.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/traverse/lib/path/conversion.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/traverse/lib/path/index.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/traverse/lib/context.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/traverse/lib/traverse-node.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/traverse/lib/index.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/helper-replace-supers/lib/index.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/helper-create-class-features-plugin/lib/fields.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/helper-create-class-features-plugin/lib/index.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/plugin-proposal-class-properties/lib/index.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/preset-env/lib/available-plugins.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/preset-env/lib/filter-items.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/preset-env/lib/index.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/core/lib/config/files/module-types.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/core/lib/config/files/configuration.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/core/lib/config/files/index.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/core/lib/index.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/babel-loader/lib/index.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/loader-runner/lib/loadLoader.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/loader-runner/lib/LoaderRunner.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/webpack/lib/NormalModuleFactory.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/webpack/lib/Compiler.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/webpack/lib/webpack.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/webpack/lib/index.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/webpack-cli/lib/webpack-cli.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/webpack-cli/lib/bootstrap.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/webpack-cli/bin/cli.js
[hashi-dev] - /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/webpack/bin/webpack.js (While processing: /Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/preset-env/lib/index.js)
[hashi-dev]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[hashi-dev]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[hashi-dev]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[hashi-dev]     at require (node:internal/modules/cjs/helpers:102:18)
[hashi-dev]     at Object.<anonymous> (/Users/marcellamaki/Documents/learning-equality/kolibri/node_modules/@babel/traverse/node_modules/@babel/helper-function-name/lib/index.js:8:54)
[hashi-dev]     at Module._compile (node:internal/modules/cjs/loader:1101:14)
[hashi-dev]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
[hashi-dev]     at Module.load (node:internal/modules/cjs/loader:981:32)
[hashi-dev]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[hashi-dev]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[hashi-dev] 
[hashi-dev] webpack 5.74.0 compiled with 1 error in 844 ms

**Comment by rtibbles** [comment]
I have definitely seen this error before `@babel/helper-get-function-arity` - I think during one of the dependency upgrades in develop.

**Comment by rtibbles** [comment]
This should now be fixed @marcellamaki.

**Review by jredrejo — APPROVED** [review]
LGTM, also tested without any issue.

**Pull request merged**
