### PR TITLE
Fetch groups

### LINKED ISSUE #1270: group disappears from list after creation
steps to repro:

* create new group. the new group is visible
* switch tabs, e.g. to exams
* switch back to groups. the new group is not visible
* refresh. the new group is visible again

### PR DESCRIPTION
**Pull request by christianmemije**
## Summary

Fixes #1270

### CODE REVIEW

**Comment by rtibbles** [comment]
Note: we should probably think about all the cases where this 'adding a model' behaviour means that we want to fetch with a force and think about how to solve it systematically - I think there are multiple instances where this occurs.

**Comment by indirectlylit** [comment]
maybe it would be something like:

_any delete/update/save of model invalidates the cache of any collections of that model type_

**Comment by rtibbles** [comment]
Well, currently if any model is unsynced, the collection it is in is also marked as unsynced. The issue comes when we create new models that *should* be part of the collection.

Another way to do it would be for Collections to have model get/create methods, which would proxy to the Resource get/create methods, but also add the model to the Collection itself on the way.

**Comment by indirectlylit** [comment]
That's a good idea. Assumes that new models always get adding to the collection on the server side .. but maybe that's a safe assumption? Simply unsyncing a collection on model creation might be more robust to weird edge cases at the cost of less efficient cache usage.

**Comment by rtibbles** [comment]
Yeah, there are some possible edge cases to it - could slightly reduce those by automatically applying any filters in the collection to model fields on the created model, but it's still not foolproof.

**Pull request merged**
