### PR TITLE
Merging old and new styles, cleaning up HTML elements.

### PR DESCRIPTION
**Pull request by DXCanas**
## Summary

Work still needs to be done, but wanted to get this into master for others to work off of.

### CODE REVIEW

**Comment by rtibbles** [comment]
Thanks, @DXCanas this is some much needed cleanup. Testing locally then merging.

**Comment by rtibbles** [comment]
I am a little concerned at the size of the folder icons here:
image

The icons are helpful, but being able to read the title in total more so.

**Comment by rtibbles** [comment]
The description seems to be getting clipped on the topic pages too:

image

**Comment by DXCanas** [comment]
Yeah I clipped them, and change the icon sizes too. Both are 1 css value fixes. 

Clipping was for uniformity, but it doesn't seem possible to do more than 1 line without some backend or js work

**Comment by rtibbles** [comment]
We can probably create a 'line wrap' filter for Vue without too much difficulty.

Just specify a max line length and then wrap based on that.

**Comment by DXCanas** [comment]
Cool. I'll change the folders when I get in, we can unclip the titles too.

**Comment by indirectlylit** [comment]
@DXCanas @rtibbles @66eli77 @whitzhu - let's all chat tomorrow about card styling. Eli, Whitney and I talked a bit today about the need to better-handle long titles, and we're thinking a good option might be to make the cards have a wider aspect ratio (meaning fewer columns). There are also a bunch of general card styling issues to clean up, and I want to get a quick sense for who's working on what so we don't step on each others' toes...

a couple relevant trello cards:
* https://trello.com/c/DdmIMjXC/212-fix-up-content-card-and-topic-card-styling
* https://trello.com/c/xYWa3waC/217-widen-cards

**Pull request merged**
