### PR TITLE
Do full schema check for job storage tables

### LINKED ISSUE #11047: Migrate from 0.16 alpha to beta does not work
## Observed behavior
In a system where 0.16a19 was running, after installing 016b0 kolibri does not start.
There's a problem in the jobs table, the `func` column is missing.
A workaround is deleting the ` job_storage.sqlite3 `file

The same problem has been found in two different servers (laptop & raspberry pi)

## Errors and logs
Instalation was done with the deb package:
```
sudo dpkg -i kolibri_0.16.0b0-0ubuntu1_all.deb 
(Leyendo la base de datos ... 63592 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar kolibri_0.16.0b0-0ubuntu1_all.deb ...
Desempaquetando kolibri (0.16.0b0-0ubuntu1) sobre (0.16.0a19-0ubuntu1) 
```
Then, after executing `kolibri start --foreground `this error appears and kolibri does not start:

```
INFO     2023-08-02 13:18:00,880 Processing new content removal requests
Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3/dist-packages/kolibri/dist/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: jobs.func

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/utils/cli.py", line 193, in invoke
    initialize(**get_initialize_params())
  File "/usr/lib/python3/dist-packages/kolibri/utils/main.py", line 300, in initialize
    update(version, kolibri.__version__)
  File "/usr/lib/python3/dist-packages/kolibri/utils/main.py", line 366, in update
    run_upgrades(old_version, new_version)
  File "/usr/lib/python3/dist-packages/kolibri/core/upgrade.py", line 156, in run_upgrades
    version_upgrade()
  File "/usr/lib/python3/dist-packages/kolibri/core/upgrade.py", line 51, in __call__
    return self.upgrade()
  File "/usr/lib/python3/dist-packages/kolibri/core/content/upgrade.py", line 344, in synchronize_content_requests_upgrade
    automatic_resource_import.enqueue_if_not()
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/registry.py", line 309, in enqueue_if_not
    return job_storage.enqueue_job_if_not_enqueued(
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/storage.py", line 200, in enqueue_job_if_not_enqueued
    queued_jobs = self.filter_jobs(func=job.func, queue=queue, state=State.QUEUED)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/storage.py", line 308, in filter_jobs
    orm_jobs = conn.execute(q)
  File "/usr/lib/python3/dist-packages/kolibri/dist/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/usr/lib/python3/dist-packages/kolibri/dist/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/lib/python3/dist-packages/kolibri/dist/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/python3/dist-packages/kolibri/dist/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3/dist-packages/kolibri/dist/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3/dist-packages/kolibri/dist/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/usr/lib/python3/dist-packages/kolibri/dist/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3/dist-packages/kolibri/dist/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: jobs.func
[SQL: SELECT jobs.id, jobs.state, jobs.func, jobs.priority, jobs.queue, jobs.saved_job, jobs.time_created, jobs.time_updated, jobs.interval, jobs.retry_interval, jobs.repeat, jobs.scheduled_time 
FROM jobs 
WHERE jobs.queue = ? AND jobs.state = ? AND jobs.func = ?]
[parameters: ('content', 'QUEUED', 'kolibri.core.content.tasks.automatic_resource_import')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

## Expected behavior

After upgrading kolibri from alpha to beta, previous installations should keep working

## User-facing consequences
No easy upgrade

## Steps to reproduce
Run kolibri 0.16 alpha, and then upgrade to beta using the same database

## Context
* Ubuntu 22.04

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Move sqlalchemy schema checking code to general purpose utils.
* Use in confirming that the job storage database is readable.
* Delete upgrade functionality in favour of sanity checking.

## References
Fixes #11047

## Reviewer guidance
Run version < 0.16.0b0, then run this. Confirm it doesn't error.

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [x] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by jredrejo — CHANGES_REQUESTED** [review]
It does not work yet, same problem with this code.
In case it helps, I'm attaching here a sqlite db to test it
[job_storage_alpha19.zip](https://github.com/learningequality/kolibri/files/12243538/job_storage_alpha19.zip)

**Comment by rtibbles** [comment]
I just reran Kolibri with this database and it worked - the appropriate warning showed:

```
WARNING  2023-08-02 11:37:56,504 Database table for job storage was not accessible, recreating.
```

and then Kolibri ran normally.

**Comment by jredrejo** [comment]
> I just reran Kolibri with this database and it worked - the appropriate warning showed:
> 
> ```
> WARNING  2023-08-02 11:37:56,504 Database table for job storage was not accessible, recreating.
> ```
> 
> and then Kolibri ran normally.

I've tried it again in this PR branch with two different db from 2 servers and I can't get it working yet, could it be there's some missing file not added in the PR commits?
I've tried it both with
`yarn python-devserver`
and `kolibri start `(after doing `pip install -e .`)


```
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Installed 2 object(s) from 1 fixture(s)
INFO     2023-08-02 21:12:12,380 Processing new content assignment requests
INFO     2023-08-02 21:12:13,180 Processing new content removal requests
INFO     2023-08-02 21:12:13,870 Processing new content assignment requests
INFO     2023-08-02 21:12:14,159 Processing new content removal requests
Error: Traceback (most recent call last):
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: jobs.func

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/datos/le/mio/kolibri/kolibri/utils/cli.py", line 193, in invoke
    initialize(**get_initialize_params())
  File "/datos/le/mio/kolibri/kolibri/utils/main.py", line 300, in initialize
    update(version, kolibri.__version__)
  File "/datos/le/mio/kolibri/kolibri/utils/main.py", line 366, in update
    run_upgrades(old_version, new_version)
  File "/datos/le/mio/kolibri/kolibri/core/upgrade.py", line 156, in run_upgrades
    version_upgrade()
  File "/datos/le/mio/kolibri/kolibri/core/upgrade.py", line 51, in __call__
    return self.upgrade()
  File "/datos/le/mio/kolibri/kolibri/core/content/upgrade.py", line 344, in synchronize_content_requests_upgrade
    automatic_resource_import.enqueue_if_not()
  File "/datos/le/mio/kolibri/kolibri/core/tasks/registry.py", line 309, in enqueue_if_not
    return job_storage.enqueue_job_if_not_enqueued(
  File "/datos/le/mio/kolibri/kolibri/core/tasks/storage.py", line 201, in enqueue_job_if_not_enqueued
    queued_jobs = self.filter_jobs(func=job.func, queue=queue, state=State.QUEUED)
  File "/datos/le/mio/kolibri/kolibri/core/tasks/storage.py", line 309, in filter_jobs
    orm_jobs = conn.execute(q)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: jobs.func
[SQL: SELECT jobs.id, jobs.state, jobs.func, jobs.priority, jobs.queue, jobs.saved_job, jobs.time_created, jobs.time_updated, jobs.interval, jobs.retry_interval, jobs.repeat, jobs.scheduled_time 
FROM jobs 
WHERE jobs.queue = ? AND jobs.state = ? AND jobs.func = ?]
[parameters: ('content', 'QUEUED', 'kolibri.core.content.tasks.automatic_resource_import')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by rtibbles** [comment]
Replicated - was an issue with the sanity check not happening prior to upgrade routines being run.

**Review by jredrejo — APPROVED** [review]
Works perfectly with the latest changes:
`WARNING  2023-08-03 11:41:11,114 Database table for job storage was not accessible, recreating.`

A rebase from `develop` or from https://github.com/learningequality/kolibri/pull/11054 will be needed to fix current linting issues

**Comment by rtibbles** [comment]
Linting issues resolved on release 0.16.x, so merging as is.

**Pull request merged**
