### PR TITLE
Upgrade to iceqube 0.0.5

### PR DESCRIPTION
**Pull request by aronasorman**
Has support for multiprocessing

### CODE REVIEW

**Review by indirectlylit — CHANGES_REQUESTED** [review]
Remember that we're trying to include links to diffs for internal upgrades. Looks like 0.0.5 may have been released off the develop branch?

iceqube has no tags and the master branch was last updated on Oct 3, 2017

Let's get the branch situation cleaned up and add tagged releases for `v0.0.4` and `v0.0.5` so we know exactly what code is being run.

----

Refs:

* https://github.com/learningequality/iceqube/pull/2
* https://github.com/learningequality/iceqube/issues/23

**Comment by indirectlylit** [comment]
@aronasorman let me know what you want to do with this. (were you interested in handing off the iceqube repo for maintenance?)

**Comment by aronasorman** [comment]
Sorry wasn't able to reply early! I'll create a tag for 0.0.5 and then link it here.

**Comment by benjaoming** [comment]
@aronasorman would be great if you could ease my introduction a bit by adding tags for what has been released, so I won't have to do too much research :)

At least maybe 0.0.4 and 0.0.5

**Comment by benjaoming** [comment]
Fixed and verified by the build in #4134

**Comment by benjaoming** [comment]
S

**Pull request closed without merging**
