### PR TITLE
Added manual testing/ QA doc

### PR DESCRIPTION
**Pull request by whitzhu**
Added a new `manual testing/QA` doc to kolibri doc

## Summary

*Short description*

## TODO

- [ ] Have tests been written for the new code?
- [ ] Has documentation been written/updated?
- [ ] New dependencies (if any) added to requirements file
- [ ] Add an entry to CHANGELOG.rst
- [ ] Add yourself it AUTHORS.rst if you don't appear there

## Reviewer guidance

*If you PR has a significant size, give the reviewer some helpful remarks*

## Issues addressed

List the issues solved or partly solved by the PR

## Documentation

If the PR has documentation, link the file here (either .rst in your repo or if built on Read The Docs)

## Screenshots (if appropriate)

They're nice. :)

### CODE REVIEW

**Comment by indirectlylit** [comment]
thanks for adding this! Does it have a link from the main index page?

Would also be great to mention Browserstack and the A11Y checking tools that @radinamatic uses

**Comment by benjaoming** [comment]
> Does it have a link from the main index page?

Should be added to `docs/dev/index.rst`, maybe we should consider a new `Test` section, too.

**Comment by radinamatic** [comment]
I will add the section about A11y testing once this is merged!

**Comment by radinamatic** [comment]
Did we decide not to include this? 
@whitzhu @indirectlylit

**Comment by whitzhu** [comment]
@radinamatic I was cleaning my github repo and I just closed all inactive branches. It seems like it was inactive for a while so it got closed it. 

@indirectlylit Do we still want to include this?

**Comment by indirectlylit** [comment]
still looks like good content to me. I think the main thing it needed was a link from the TOC

**Comment by radinamatic** [comment]
I agree, if you can merge it @indirectlylit, I'll add the link from TOC myself together with the a11y testing section.

**Comment by indirectlylit** [comment]
@whitzhu mind re-opening this from your end?

**Comment by radinamatic** [comment]
@whitzhu Will you have time to re-open this? 
It's a pity to have valuable content wasted... :wink:

**Pull request closed without merging**
