### PR TITLE
Kolibri Server Timezone Issue

### LINKED ISSUE #2476: Starting up Kolibri Development Server
### Observed behavior

Trying to run the Kolobri Development Server from Ubuntu Bash on Windows, but it raises a ValueError for incorrect timezone (local).

### Expected behavior

Should start up the Kolibri server on local machine.

### Errors and logs

Relevant errors and tracebacks from:

*virtual environment command line:
```
Traceback (most recent call last):
  File "/home/alan/.venvs/kolibri/bin/kolibri", line 11, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "/home/alan/Kolibri1/kolibri/kolibri/utils/cli.py", line 607, in main
    initialize(debug=debug)
  File "/home/alan/Kolibri1/kolibri/kolibri/utils/cli.py", line 176, in initialize
    django.setup()
  File "/home/alan/.venvs/kolibri/local/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/alan/.venvs/kolibri/local/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/home/alan/.venvs/kolibri/local/lib/python2.7/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/alan/.venvs/kolibri/local/lib/python2.7/site-packages/django/conf/__init__.py", line 138, in __init__
    raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)
ValueError: Incorrect timezone setting: local

```

### Steps to reproduce

Run command to start up Kolibri Development server. 

kolibri --debug manage devserver --webpack

### Context

* Kolibri version: Develop Branch
* Operating system: Ubuntu Bash for Windows

### PR DESCRIPTION
**Pull request by alanchenz**
# Checklist

- [ ] PR has the correct target milestone when it's merged
- [ ] Automated test coverage is satisfactory
- [ ] PR has been fully tested manually
- [x] You've added yourself to AUTHORS.rst if you're not there

# Details

### Summary

Fixed timezone issue that returns local. Now, it returns UTC as a default timezone.

### Reviewer guidance

Run Kolibri server on Ubuntu Bash

### References

Fixes #2476

### CODE REVIEW

**Comment by benjaoming** [comment]
Am fixing it upstream as well: https://github.com/regebro/tzlocal/pull/48

**Comment by benjaoming** [comment]
Hi @alanchenz I had a look around and landed on this solution, inspired by djangocms-installer: https://github.com/nephila/djangocms-installer/commit/f7995036ed36b6e494b4ea84cc8856e85fb565df

**Comment by regebro** [comment]
It failed to detect the local time zone name, and instead just returns the time zone configuration. The time zone object returned is still valid.

If you need a time zone name, then you need to configure your system so that it is possible to detect the name of the timezone. 

Making it fall back to UTC is not robust, it's wrong.

**Comment by rtibbles** [comment]
For our purposes, having a valid timezone name, as opposed to `local` which is not the valid name of a timezone, is more important than having the right timezone. Not having a valid timezone name makes Django fail to start, whereas defaulting to UTC means that we get slightly less accurate information about the particular timezone in which an interaction occurred, due to the particular system that it was setup in not exposing more useful timezone information.

Because we have very little control over the distributed server devices that run Kolibri, letting it run, but with a less informative default of UTC is our best fall back here.

There are some cases where we have more control over the environment, such as in the Android installer, where we can use a system specific API to ensure that this is set correctly before runtime, but in this particular edge case of an Ubuntu bash shell running on a Windows machine, we do not have that control.

**Comment by rtibbles** [comment]
For the more general `tzlocal` this is probably not the case, for sure - would be nice if it was easier to infer the timezone name from the timezone from file method that you are using in this particular instance, but if it's not possible, it's not possible!

**Comment by benjaoming** [comment]
@regebro Thanks for responding - We are aware that UTC is wrong - but do you mean that the returned tz info contains timezone data that can be used to generate an adequate timezone name?

**Comment by regebro** [comment]
No, your system configuration doesn't specify a time zone name, just the information about that time zone. So tzlocal returns a TZInfo object with that information, but the name "local". This is because dateutil used that name in that case, it seemed reasonable to me.

If you want to get the name of the timezone from your systems time zone configuration, the system needs to be configured in such a way that the configuration actually contains the name of the timezone.

tzlocal will first check the TZ environment variable, then it will look in /etc/timezone and /var/db/zoneinfo, after that it will look in /etc/sysconfig/clock, /etc/conf.d/clock for a ZONE= or TIMEZONE=.
If that fails it will do further silly magic, but just putting the timezone name into /etc/timezone works and should be easily doable.

**Comment by rtibbles** [comment]
Well, if we knew the timezone name to put into the folder in the first place, we would avoid all this muss and fuss to start with, and just set the timezone directly.

We don't have control over the machines our software is deployed on, and can't go about arbitrarily writing to /etc/timezone whenever we feel like it, so this is our catch for this rare edgecase when it is unspecified. Thanks for following up!

**Comment by benjaoming** [comment]
It's interesting, what @regebro says is that we can detect the timezone as the offset from UTC but not the name -- which the Django settings need.

So in case this becomes a more important issue, we could start researching how we can reverse lookup the timezone name from the UTC offset.

**Comment by regebro** [comment]
*Someone* reasonably must know which timezone the server is in. That someone needs to configure his/her server environment properly.

You can't look up timezone names from UTC offset, they aren't unique. You could make a binary comparison with all time zone files on the machine and see if one fits, and pick that.

But it's a fairly silly solution compared with configuring it correctly.

**Comment by benjaoming** [comment]
Yes, but you also don't know the typical user in question here ;)

Thanks for the response, I think we can consider picking an arbitrary timezone name with the offset detected. And put a warning in the log. The important part is that we don't make the application crash or completely mess up the time and dates.

**Comment by regebro** [comment]
On most systems zones like "Etc/GMT+3" will be available, so you can pick those. You won't get DST but printing a big warning about not finding the timezone and that this will be a problem when you have daylight savings should be enough.

**Comment by benjaoming** [comment]
Thanks for the guidance @regebro - FYI the lower common denominator would be a child running an Android smart phone where the timezone isn't detected, and we would therefore be unable to advice much -- and possibly the case for having a correct timezone is a bit low priority in that case, it would just be about not crashing :)

**Pull request merged**
