### PR TITLE
SECURE_CONTENT_TYPE_NOSNIFF setted to True

### LINKED ISSUE #9033: Set SECURE_CONTENT_TYPE_NOSNIFF setting to True
## Observed behavior
Currently clients can MIME sniff content rather than deferring to the declared MIME type.

## Expected behavior
Clients should not be able to MIME sniff content, can set this response header with this setting: https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-SECURE_CONTENT_TYPE_NOSNIFF

### PR DESCRIPTION
**Pull request by sakshampathak1508**
Fixes issue number #9033 
updated base.py and updated SECURE_CONTENT_TYPE_NOSNIFF to True

## Summary

…

## References

…

## Reviewer guidance

…

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [x] Critical user journeys are covered by Gherkin stories
- [x] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [x] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
Thanks, this looks like the right fix!

Could you please add a reference to the issue that this is fixing?

Can say `Fixes #<github issue number>` in the pull request description.

**Comment by sakshampathak1508** [comment]
Hello added the issue number for the fix in the PR description

**Review by rtibbles — COMMENTED** [review]
Changes look good - we'll do some manual QA to confirm that this does what we expect!

**Comment by sakshampathak1508** [comment]
cool thanks for guiding me. on to more issues

**Review by rtibbles — APPROVED** [review]
Manual QA confirms!

**Pull request merged**
