### PR TITLE
Faster development server

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Disables babel transpilation when doing development builds (roughly a 50% speed up)
* Removes `pathinfo` from the output in development mode (recommended in https://webpack.js.org/guides/build-performance/#output-without-path-info - gave some speed up but measurements were a little unstable)
* Removes live watching of all code for frontend linting - with pre-commit seemingly fully functional, this seems OK to do.
* Swaps out `yarn-run-all` in favour of `concurrency` to allow passing arguments to specific commands
* Uses the ability to pass arguments to let plugin filters be passed in as comma separated values to only watch specific plugins for development
* All other plugins are built if not already built, but otherwise left alone
* Updates the getting started documentation to add a tip for using this ^

## Reviewer guidance
Try out the new work flow. Some things to try:
* Run `yarn run build` then run `yarn run devserver-hot learn` observe that only `learn` gets built and watched
* Run `yarn run clean` then run `yarn run devserver-hot learn` observe that everything gets built, but only `learn` gets watched

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by MisRob** [comment]
Someone had a birthday :)? Thank you @rtibbles. I will rebase some of my active work branches on top of this PR and will use the updated bundling for a couple of days.

**Comment by MisRob** [comment]
New commands as described in the "Reviewer guidance" are awesome, by the way

**Review by MisRob — APPROVED** [review]
Thanks again, @rtibbles. I've been working on a project that I rebased on top of this branch so I spent some time using the new dev server actively. I haven't noticed any problems and can confirm around 50% faster builds, that's awesome.

Regarding code, I would need a whole course in our current `kolibri-tools` to be able to fathom updates with some confidence. So for now I can only say - I read it :)  Something's telling me that we'd notice problems with builds pretty easily, but If someone else could have a look, that'd be good.

**Review by marcellamaki — APPROVED** [review]
Did a co-review code walk through with @rtibbles and it was very thorough and helpful. Feel good about approving!

**Pull request merged**
