### PR TITLE
Add the latest i18n files from Crowdin (new language  - Italian)

### PR DESCRIPTION
**Pull request by radinamatic**
### Summary
After Italian strings were finalized and proofread, pulled the latest from Crowdin to include in 0.13.2 release.

### Reviewer guidance
…

### References
…

----

### Contributor Checklist

PR process:

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
Any luck here? We can try to get Italian in for 0.13.2 (cc @jonboiser)

**Comment by radinamatic** [comment]
All good code-wise, had it running on my local dev env

Selection_392

We are doing a proofreading round with the volunteer who translated, but not sure if it will be ready this week. I'll update when the translations have been all ready and proofread!

**Comment by indirectlylit** [comment]
it appears that the Persues files were removed in this PR:

`kolibri_exercise_perseus_plugin.exercise_perseus_render_module-messages.json`

It's important to follow the instructions and watch for warnings related to Perseus when running `crowdin.py`

**Comment by indirectlylit** [comment]
other than that, looks great! I was able to enable Italian

**Comment by jonboiser** [comment]
Are the perseus messages supposed to be in the Kolibri codebase, since they are supposed to be stored on the Perseus code base? The perseus files in their entirety were added in this commit https://github.com/learningequality/kolibri/commit/414da3b93c2515393204e1fe2249630c85ff298d

maybe the `makemessage` command cleaned them up or something.

**Comment by indirectlylit** [comment]
Ah of course! the perseus files need to be committed separately to that repo:

https://github.com/learningequality/kolibri-exercise-perseus-plugin/tree/develop/kolibri_exercise_perseus_plugin/locale

Looks like I may have made a mistake and accidentally committed them to this repo. 

Sorry for the confusion!

**Review by indirectlylit — APPROVED** [review]
hooray!

**Comment by indirectlylit** [comment]
made a follow-up tracker issue here: https://github.com/learningequality/kolibri/issues/6772

**Pull request merged**
