### PR TITLE
support non-adjacent keywords search

### PR DESCRIPTION
**Pull request by 66eli77**

### CODE REVIEW

**Comment by rtibbles** [comment]
Could you benchmark the difference between current master and this for API
performance?

**Comment by 66eli77** [comment]
it will perform the same as previous approach if there's exact match, but will be able to return results the previous approach cannot if the keywords exist non-adjacent to each other.

**Comment by 66eli77** [comment]
screen shot 2016-07-15 at 6 20 22 pm
force to use previous approach ^


screen shot 2016-07-15 at 6 20 53 pm
force to use non-adjacent search^

**Comment by rtibbles** [comment]
Righto, seems fairly straight forward for a fallback method then.

**Pull request merged**
