### PR TITLE
[fix] responsive onboarding setup wizard

### LINKED ISSUE #7997: Responsive behaviors on setup wizard language switcher list no longer work as originally designed
## Observed behavior

The number of visible languages is changing based on screen size breakpoints even though the available space is not changing.

This may have been an unintentional consequence of some unrelated layout changing, e.g. making the max-width of the setup wizard smaller.

## Expected behavior

UI layout should be responsive to actual available screen real estate.

## User-facing consequences

Layout and text wrapping behavior on the very first screen users see behaves poorly.

## Steps to reproduce

resize setup wizard window

## Context

0.14.7 rc2
0.16.0b10

### PR DESCRIPTION
**Pull request by FidalMathew**
## Summary

Made the setup wizard responsive for screen size by eliminating max-width. 

https://github.com/learningequality/kolibri/assets/84982038/358427b6-ed51-4e06-bfb7-43ac55f9823d

…

## References

fixes #7997 
…

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by AlexVelezLl — CHANGES_REQUESTED** [review]
Hi @FidalMathew! Unfortunately, this doesn't seem like the right change. The issue referred to the fact that the number of items in the language list changed even though the width of the card container did not change, but instead changed depending on the width of the window.
Look at these two cases:

image

image

In both of them, the width of the card is the same, 700px, but in the second one there is one less item than in the first one, and that is because the window is narrower, but it shouldn't be like that.

It is an issue with [the way we calculate the number of visible languages](https://github.com/learningequality/kolibri/blob/c372cd05ddd105a7688db9e3698dc21b842ac3e5/kolibri/core/assets/src/views/language-switcher/LanguageSwitcherList.vue#L77).

**Comment by FidalMathew** [comment]
@AlexVelezLl Thanks for the clarification. I am considering fetching the width of the `OnboardingStepBase` component and passing its `width` as props to `LanguageSwitcherList`. Using width, we can set the breakpoints for `numVisibleLanguageBtns`. Is this a good approach to solving the issue?

**Comment by AlexVelezLl** [comment]
Oh @FidalMathew I think you can add a ref to the div container and obtain its width

**Comment by FidalMathew** [comment]
> Oh @FidalMathew I think you can add a ref to the div container and obtain its width
 
Got it! Thanks @AlexVelezLl

**Comment by FidalMathew** [comment]
@AlexVelezLl Could you take a look at the PR?

**Comment by pcenov** [comment]
Hi @FidalMathew and @AlexVelezLl - can we do something for the position of the 'More languages' label - currently when I select a language different than English there are some cases where it goes on the second line which should be avoided if possible:

https://github.com/learningequality/kolibri/assets/79847249/a5ddb5f3-0564-4a4d-81b8-1d586b4f228a

**Comment by FidalMathew** [comment]
> Hi @FidalMathew and @AlexVelezLl - can we do something for the position of the 'More languages' label - currently when I select a language different than English there are some cases where it goes on the second line which should be avoided if possible:
> 
>  2024-02-15_14-18-41.mp4

Thanks @pcenov, I'll look into this issue.

**Comment by FidalMathew** [comment]
@pcenov do you have any suggestions on how to approach this issue?

**Comment by AlexVelezLl** [comment]
Hi @FidalMathew, we are devleoping a new KDS component that I think would fit good for doing this. But could take some more time.

@pcenov, Can we accept this as a solution for the original issue regarding the items hiding regardless of whether there is still space in the container?, and make a follow up issue about it only taking a single line? Since for this there are some other dependencies that we should develop first.

**Comment by FidalMathew** [comment]
> Hi @FidalMathew, we are devleoping a new KDS component that I think would fit good for doing this. But could take some more time.
> 
> @pcenov, Can we accept this as a solution for the original issue regarding the items hiding regardless of whether there is still space in the container?, and make a follow up issue about it only taking a single line? Since for this there are some other dependencies that we should develop first.

Thanks for letting me know! 😄

**Review by pcenov — APPROVED** [review]
Hi @AlexVelezLl - yes, certainly!

**Review by AlexVelezLl — APPROVED** [review]
Thank you all! LGTM :). We will follow it up in #11923.

**Pull request merged**
