### PR TITLE
Search Box Vertical Green line fixed

### PR DESCRIPTION
**Pull request by muhammadalics**
## Summary
To fix the issue line 296 was added to SearchBox.vue. See screenshot below:
image

**Before:** Unwanted green line visible in search box.

vertical_greenline_searchbox

**After:** Green line is no longer visible.

vertical_nogreenline_searchbox

## References
Issue: #7990

## Reviewer guidance

The only change occurs in the search box under Learn section where unwanted green line has been removed.

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by muhammadalics** [comment]
@indirectlylit Would you please review my PR?

**Comment by jonboiser** [comment]
@muhammadalics , could you squash your 5 commits into 1 first?

**Comment by indirectlylit** [comment]
> @indirectlylit Would you please review my PR?

Sorry I'll need to leave this to another team member

**Comment by jonboiser** [comment]
This will fix the issue in one place, but is basically a temporary hack until the bigger issue of #7974 is fixed. I think it makes more sense for us to wait until that issue is fixed.

**Pull request closed without merging**
