### PR TITLE
Adding :focus styling  to icon-button

### PR DESCRIPTION
**Pull request by whitzhu**
**Chrome**
screen shot 2016-08-08 at 1 00 26 pm

**Firefox**
screen shot 2016-08-08 at 1 00 41 pm

## Summary

*Short description*

## TODO

- [ ] Have tests been written for the new code?
- [ ] Has documentation been written/updated?
- [ ] New dependencies (if any) added to requirements file
- [ ] Add an entry to CHANGELOG.rst
- [ ] Add yourself it AUTHORS.rst if you don't appear there

## Reviewer guidance

*If you PR has a significant size, give the reviewer some helpful remarks*

## Issues addressed

List the issues solved or partly solved by the PR

## Documentation

If the PR has documentation, link the file here (either .rst in your repo or if built on Read The Docs)

## Screenshots (if appropriate)

They're nice. :)

### CODE REVIEW

**Comment by whitzhu** [comment]
@radinamatic @indirectlylit To keep things consistent with the nav and card :focus style, I added the same style to icon_buttons

**Comment by radinamatic** [comment]
Do icon_buttons ever get TAB focus on their own, or just as part of the `a` element?
If not, it may not be strictly necessary...

**Comment by indirectlylit** [comment]
This was updated in this commit: 2214adadeed9fc25f535840879096ae725b32c66

**Comment by indirectlylit** [comment]
> Do icon_buttons ever get TAB focus on their own, or just as part of the a element?
If not, it may not be strictly necessary...

Icon buttons refer to things that look like this:

image

**Comment by radinamatic** [comment]
OK, button_with_icon, then, cool... I was thinking of a content_icon... :smiley:

Yep, this one does need focus styling, but with the same caveat about background color change @whitzhu - make sure that the contrast between color of the button content (`Download media`) and the color of the background is enough when it in focus.

**Pull request closed without merging**
