### PR TITLE
Pytest upgrade 3.7.1 -> 6.2.5

### LINKED ISSUE #11728: Update pytest to 6.2.5
Our version of pytest was pinned to a very old version for back compatibility with Python 2.7.

Now that we have dropped support for 2.7, we can upgrade pytest to versions that support Python 3.6 and above.

While technically, 7.0.1 may work, there have been issues reported with Python 3.10 (cc @jredrejo), so it seems safer to upgrade to 6.2.5, as we would not be able to upgrade to newer versions of the 7 series, as they drop support for Python 3.6, which we still support.

We would also need to update any pytest plugins, and remove the existing [patching of pytest for Python 3.10 compatibility](https://github.com/learningequality/kolibri/blob/release-v0.16.x/test/patch_pytest.py).

```[tasklist]
### Acceptance Criteria
- [x] Update pytest and pytest plugins
- [x] Remove patching for pytest for Python 3.10 compatibility
```

### PR DESCRIPTION
**Pull request by thesujai**
## Summary

When i run test on files individually all are passing, but while running them at once it fails

## References

Fixes #11728 
…

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
This work should be targeted to develop and targeted there, as this version of pytest is not compatible with Python 2.7, which has been dropped in develop.

**Comment by thesujai** [comment]
@rtibbles  okay i will change the target in final pr, but i am facing this issue
In develop branch only, after changing versions in requirements
**Check that test_utils is failing when i ran all at once**
Screenshot from 2024-01-20 22-11-01
**But it passes when i run this individually**
Screenshot from 2024-01-20 22-11-17

**Comment by rtibbles** [comment]
Interesting - there must be something else at play here. One possibility is a change in pytest that is causing state to be persisted between tests.

Seeing the traceback from the failed tests would help diagnose further!

Also it may be worth seeing if any of the other pytest plugins could be upgraded.

**Comment by thesujai** [comment]
@rtibbles 
After some debugging, what i can observe is if exclude all test from `test_dbrestore.py` (for testing only)then all my tests are passing, except for one:
Screenshot from 2024-01-22 19-36-17
This test was passing fine when running standalone.

Further more, i just configured the pytest.ini to run only `test_content_sync_hook.py` and `utils/test_content_request.py`, and it failed giving the exact above error. So I think this `test_content_sync_hook.py` is causing some state to be persisted here.

let me know what can be done further

**Comment by rtibbles** [comment]
That's some good debugging - I notice that the test_content_sync_hook test case inherits from the test_content_request testcase: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/content/test/test_content_sync_hook.py#L12

So it may be that this is the cause of the interaction? Looking more closely at the IncompleteDownloadRequest test case may shed some more light here.


What errors are you seeing from the test_dbrestore test suite?

**Comment by thesujai** [comment]
While running test_dbrestore standalone I am getting this:
Screenshot from 2024-02-01 11-02-51

Also one more behaviour that test are getting collected with pytest6.2.5 and pytest-django 3.6.0
With pytest3.7.1 and pytest-django3.3.3:(running deviceadmin):
Screenshot from 2024-02-01 11-07-07

With pytest6.2.5 and pytest-django3.6.0:(running deviceadmin):
Screenshot from 2024-02-01 11-10-40
Errors are:
Screenshot from 2024-02-01 11-10-54





As much as i know test are failing because of pytest-django upgrade to 3.6.0 as the  pytest.config is changed to request.config and high version of pytest uses that

**Comment by rtibbles** [comment]
Sorry @thesujai I missed the follow up comments here as I was out of the office. It looks like the dbrestore tests might be fixable by tweaking the configuration for pytest-django?

For the other test where the bare assertion is failing, can you look at where the assertion is failing and see what it is meant to be asserting?

**Comment by rtibbles** [comment]
Once we have merged [this PR](https://github.com/learningequality/kolibri/pull/11974) (which upgrades Django to 3.2), it would be good to rebase this PR onto develop, as that may help with some of the errors.

**Comment by rtibbles** [comment]
I have rebased this PR onto latest develop and pushed, let's see how the tests shake out now!

**Comment by thesujai** [comment]
I'm not sure if it helped still getting 657 failing tests with 530 errors. 
I cannot even get what is causing the tests to fail because running most of them individually is okay but running them together is not so okay. As the log file I generated(by pytest) is 212873 lines long, so not able to read it either. 

One idea I can think of is having a global teardown code that will reset all the states after each test, making tests stateless. Ref: https://stackoverflow.com/questions/22627659/run-code-before-and-after-each-test-in-py-test

**Comment by rtibbles** [comment]
No - it doesn't seem to have helped. Although, you had mentioned above that there was some configuration change needed for the upgraded pytest-django plugin?

**Comment by thesujai** [comment]
Sorry for missing your previous comment on this, I missed it. I was not talking about configuration change needed for the upgraded pytest-django plugin


I was referring to this changelog https://pytest-django.readthedocs.io/en/latest/changelog.html#id35 and https://docs.pytest.org/en/8.2.x/changelog.html#removals

I trying to say that changelog is the only reason for upgrading `pytest-django` as the older version of pytest-django is not compatible with the new version pytest(due to that changelog only)

**Comment by akolson** [comment]
In Hiatus until @rtibbles has the bandwidth to pick it up!

**Comment by jredrejo** [comment]
@rtibbles  I think we should move this from the hiatus status, after 2.7 support has been finished, and specially if new versions of django are been used (as a reference, KDP has been using 6.2.1 since September 2022)

**Comment by rtibbles** [comment]
Yes, I have the overall issue for upgrading to support Python 3.12, which this is a prerequisite for.

**Review by rtibbles — APPROVED** [review]
The changes here only affect test files and related github actions/configuration. I have asked @marcellamaki to confirm as I have done a significant chunk of the work here too.

**Pull request merged**
