### PR TITLE
Added UNIT test for context processor.

### PR DESCRIPTION
**Pull request by ralphiee22**
## Summary

Title.
## TODO
- [x] Have tests been written for the new code?

### CODE REVIEW

**Comment by ralphiee22** [comment]
@rtibbles Let me know if this fits as a unit test. It's kinda hard to do it simply because a lot of the behind the scenes thing django does in setting request attributes and storing user sessions.

**Comment by rtibbles** [comment]
I think this could be even simpler. You can just run the context processor function we have defined on the dummy request object you create in the tests, and check that it is setting the right values.

We could even do mock/patching on the SessionViewSet etc. to set the values that should be applied.

We should then have independent tests that test the SessionViewSet (although, as you wrote it, I am sure those already exist).

**Comment by rtibbles** [comment]
More inspiration for how simple this can be here: http://blog.namis.me/2012/05/13/writing-unit-tests-for-django-middleware/

**Comment by ralphiee22** [comment]
I understand how this can be done with anonymous users, but still confused with the user case. Particularly this line https://github.com/learningequality/kolibri/blob/master/kolibri/auth/api.py#L152 is the blocker because it does all the request and session checks. This is what allows it to go past and return the user info successfully. Unless the mocking the SessionViewSet allows me to get past this, but not sure how I would do that.

**Comment by rtibbles** [comment]
Yes, so we should mock the `get_session` method, for the context processor tests.

Then we can create other tests that test the `get_session` method, which in turn should mock the `get_user` function, to set the correct kind of users, and test the behaviour of that method.

**Comment by ralphiee22** [comment]
@rtibbles I have to thank you for showing me `mock`. It's actually a wonderful tool.

**Comment by rtibbles** [comment]
It really is - it is very helpful for limiting the scope of unit tests to a single unit, rather than ending up testing a whole load of other code (and often other people's code) as well.

**Pull request merged**
