### PR TITLE
rename coach_tools plugin to coach

### PR DESCRIPTION
**Pull request by 66eli77**

### CODE REVIEW

**Comment by indirectlylit** [comment]
this sort of refactor is very likely to cause merge conflicts, so we should get it into `develop` ASAP. ongoing work on learner groups can/should happen in a separate branch, but these changes in particular should be merged quickly

**Comment by 66eli77** [comment]
you want me to merge it now?

**Comment by indirectlylit** [comment]
if you make a PR, I'll test and merge

**Comment by 66eli77** [comment]
can you test on this branch and merge it into develop?

**Comment by indirectlylit** [comment]
yes .. okay I'll make the PR :)

**Comment by 66eli77** [comment]
Oh, I see what you mean, do a merge on develop and open a PR. I can do that if you haven't started yet

**Pull request merged**
