### PR TITLE
Upgrade morango.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Upgrades morango to fix a regression caused by the Django 3.2 upgrade
* Upgrades to a morango version that supports Python 3.12

## References

…

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by marcellamaki — APPROVED** [review]
This is the latest morango release, which contains the upgrade to python 3.12 PR. but let's wait for manual QA before merge

**Comment by radinamatic** [comment]
No issues observed after installing the assets on Windows 10 and Ubuntu 18.04, major features (imported resources, user & classes created, lesson & quiz assigned) all a-Ok! 💯 

Ubuntu 18.04 | Windows 10
-- | --
morango-Ubuntu18 04 | morango-windows

**Review by radinamatic — APPROVED** [review]
Manual QA passes, good to go! 💯 👍🏽 :shipit:

**Comment by rtibbles** [comment]
The full morango integration tests have not quite run just yet, so I am going to rebase and force push to try to trigger them here.

**Comment by rtibbles** [comment]
Integration tests are all passing. Only test failure is a known flaky test on MacOS that has nothing to do with these changes.

**Pull request merged**
