### PR TITLE
prototyping notification links and stubs - round 4

### PR DESCRIPTION
**Pull request by indirectlylit**
### 0.12.x string stubs

* Round 1: #4632
* Round 2: #4642
* Round 3: #4651
* Round 4 final: #4662 (this one)

### Summary

Next step after #4651

Prototyping link behaviors for the activity notifications. Some factors:

* We've gotten feedback that the link destinations can be confusing - particularly for the "Someone and N other" type events. Users wanted to see the full list of users implied by that phrase, but instead lost context in an unexpected list of content items.
* We've removed the 'Channels' tab, which means that some links no longer have a destination.
* We've gotten feedback that people don't understand the distinction between Check icons and Star icons, both of which are used to mean "Completed"
* We don't currently have specs for hover state, click areas, tab focus, etc on the notification cards.

### Reviewer guidance

| screenshot | notes |
|--|--|
| image | Added a 'show' button because (a) the styling is already defined and (b) certain items don't have any link to go to |
| image | Added a new 'Learners' tab to the 'Lesson' report page, as a more natural link destination from these notifications than the list of lesson items |
| image | standardized on yellow stars to mean 'completed' |
 
feedback is welcome

### References

* [Actionable coach notification specs](https://docs.google.com/document/d/1f-Z1lbDGYXybI4R7k-MKZ3NUX8w4L_gkoEv-BiYXwhg/edit)
* [Figma mockup](https://www.figma.com/file/D5wXhmWNGyt60SpGBgFucwZU/Coach-reports-0.12?node-id=0%3A1)

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

----

cc @jonboiser @jtamiace @khangmach

### CODE REVIEW

**Comment by khangmach** [comment]
In the second screenshot, where does each learner link in the list go?

**Comment by indirectlylit** [comment]
> In the second screenshot, where does each learner link in the list go?

It's a "single learner lesson report". A list of content items in the lesson with the learner's progress and time spent on each one.

There's a similar report which can be accessed by:

```
Reports -> Learners -> Some Learner -> Some Lesson
```

From there, resources are unlinked but exercises have an exercise detail report for the user. Something like this:

image

**Comment by khangmach** [comment]
the "show" link feature looks good to me.

**Comment by indirectlylit** [comment]
Self-merging to simplify the upcoming PR review process.

This PR is essentially an extension of the past 3 string stub PRs, and from a code perspective isn't worth reviewing in isolation.

The notification designs can be iterated on as necessary.

**Comment by indirectlylit** [comment]
To do a full review of all the changes, see:

* Round 1: #4632
* Round 2: #4642
* Round 3: #4651
* Round 4 final: #4662 (this one)

**Comment by indirectlylit** [comment]
cc @jonboiser

**Pull request merged**
