### PR TITLE
Worker migrations

### LINKED ISSUE #574: 500 Internal Server Error on Content page (new dev repo)
## Summary

This is a fresh development repo setup on Ubuntu 16.04.1 LTS 64-bit.
No content channels installed, Learn & Explore pages show `Download content channels from the Content Management page`, where the 500 error occurs:

virtualbox_gnomeubuntu_14_10_2016_11_09_55
## System information
- Version: dev repo
- Operating system: Ubuntu 16.04.1 LTS 64-bit
- Browser: Firefox
## Traceback or relevant snippet from server.log or browser console

Terminal is full of:

```
10:12:50 [Q] INFO Process-1:1:3 stopped pushing tasks
10:12:50 [Q] ERROR reincarnated pusher Process-1:1:3 after sudden death
10:12:50 [Q] INFO Process-1:1:4 pushing tasks at 3900
10:12:50 [Q] ERROR no such table: django_q_ormq
```

### PR DESCRIPTION
**Pull request by aronasorman**
Fixes #574. It's because we don't run migrate when we start the dev server (unlike the prod server).

### CODE REVIEW

**Comment by indirectlylit** [comment]
remember not to target PRs to master!

It should either be the current release branch (https://github.com/learningequality/kolibri/tree/release-0.1.x__MVP) or the develop branch (https://github.com/learningequality/kolibri/tree/develop)

**Comment by aronasorman** [comment]
Oh I forgot to change it :/

And wow retargeting on Github is now so much easier! It used to be a pain, having to close the PR and make another with the new target.

**Comment by indirectlylit** [comment]
(note - current "MVP" release branch is what we should be building installers for Unicef from now)

**Comment by indirectlylit** [comment]
(so this one might actually belong in the release branch?)

**Comment by radinamatic** [comment]
Error gone, fix confirmed, ready to be merged! :+1:

**Comment by aronasorman** [comment]
Retargeted! I'm assuming that we'll be rebasing the release branch to develop soon. Merging.

**Pull request merged**
