### PR TITLE
Upgrade windows installer

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

bump window installer version to v1.2.1

### Reviewer guidance

* Is this how it's done in the new Docker world @benjaoming?
* Is the installer correct @radinamatic?

### References

fixes https://github.com/learningequality/kolibri-installer-windows/issues/88

----

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by indirectlylit** [comment]
hm windows build is failing with 


```
$ ./.buildkite/build_windows_installer.sh
--
  | 2018-10-17 09:48:06 INFO   Searching for artifacts: "dist/*.whl"
  | 2018-10-17 09:48:07 INFO   Found 1 artifacts. Starting to download to: /var/lib/buildkite-agent/builds/vader-1/learningequality/kolibri/dist
  | 2018-10-17 09:48:17 INFO   Successfully downloaded "dist/kolibri-0.11.0b1.dev0+git.65.gd5f45e75-py2.py3-none-any.whl" 81058252 bytes
  | python -c "import kolibri; print(kolibri.__version__)" > kolibri/VERSION
  | WARNING:root:No C Extensions available for this platform.
  |  
  |  
  | Current version is now 0.11.0b2.dev0+git.1.gd5f45e75
  |  
  | !! This assumes you have run 'make dockerenvdist' or 'make dist' !!
  |  
  | docker image build -t "learningequality/kolibri-windows" -f docker/build_windows.dockerfile .
  | Sending build context to Docker daemon  89.57MB
  | Step 1/7 : FROM ubuntu:bionic
  | ---> cd6d8154f1e1
  | Step 2/7 : RUN dpkg --add-architecture i386
  | ---> Using cache
  | ---> 9e6bc40f1d02
  | Step 3/7 : RUN apt-get update -y &&     DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends       ca-certificates       git       sudo       software-properties-common
  | ---> Using cache
  | ---> 35e571e6d91b
  | Step 4/7 : RUN echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true \| debconf-set-selections
  | ---> Using cache
  | ---> 6decca7037f9
  | Step 5/7 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y       ttf-mscorefonts-installer       wine-stable
  | ---> Using cache
  | ---> b671d8530a2e
  | Step 6/7 : VOLUME /kolibridist/
  | ---> Using cache
  | ---> 136b4f21f604
  | Step 7/7 : CMD git clone https://github.com/learningequality/kolibri-installer-windows.git &&     cd kolibri-installer-windows/windows &&     git checkout $KOLIBRI_WINDOWS_INSTALLER_VERSION &&     cp /kolibridist/kolibri-$KOLIBRI_VERSION*.whl . &&     export KOLIBRI_BUILD_VERSION=$KOLIBRI_VERSION &&     wine inno-compiler/ISCC.exe installer-source/KolibriSetupScript.iss &&     cp *.exe /kolibridist/
  | ---> Using cache
  | ---> d3aa96dbd246
  | Successfully built d3aa96dbd246
  | Successfully tagged learningequality/kolibri-windows:latest
  | export KOLIBRI_VERSION=$(cat kolibri/VERSION) && \
  | docker run --env-file ./docker/env.list -v $PWD/dist:/kolibridist "learningequality/kolibri-windows"
  | Cloning into 'kolibri-installer-windows'...
  | Note: checking out 'v1.2.1'.
  |  
  | You are in 'detached HEAD' state. You can look around, make experimental
  | changes and commit them, and you can discard any commits you make in this
  | state without impacting any branches by performing another checkout.
  |  
  | If you want to create a new branch to retain commits you create, you may
  | do so (now or later) by using -b with the checkout command again. Example:
  |  
  | git checkout -b <new-branch-name>
  |  
  | HEAD is now at 6341241 Merge pull request #90 from learningequality/develop
  | cp: cannot stat '/kolibridist/kolibri-0.11.0b2.dev0+git.1.gd5f45e75*.whl': No such file or directory
  | make: *** [docker-windows] Error 1
  | 🚨 Error: The command exited with status 2
```

**Comment by radinamatic** [comment]
Could have been a fluke? I've restarted the build on Buildkite, and it passed that step... 
Will test Windows asset now!

**Comment by benjaoming** [comment]
> Is this how it's done in the new Docker world @benjaoming?

The built assets will give the final answer to that :)

**Review by radinamatic — APPROVED** [review]
Looking good, even in an upgrade from 0.8 scenario! 👍 

All the Windows improvements are in (no shortcut creation step, no unnecessary Python alerts - cc @laurenlichtman, and providing the `option.ini` file with a new port runs Kolibri from there without a glitch).

Merge away!

**Comment by indirectlylit** [comment]
thanks for testing @radinamatic!

**Pull request merged**
