### PR TITLE
Fix import duplicate usernames

### PR DESCRIPTION
**Pull request by nick2432**
## Summary
This pull request introduces a modification to the get_username method, enabling case-insensitive checking for duplicate usernames.

## Changes made
Updated the get_username method to convert usernames to lowercase before checking for duplicates.
Ensured that usernames with different letter cases are treated as the same to prevent case-related duplicates.

## Issue Resolved
Fixes https://github.com/learningequality/kolibri/issues/11890

##Screenshots

https://github.com/learningequality/kolibri/assets/77477551/b5e3ac85-8a92-4d7c-a6d7-878fcddc42b9

### CODE REVIEW

**Comment by radinamatic** [comment]
@nick2432 We'll proceed with the manual QA, please try to fix the linting errors in the meantime.

**Review by pcenov — CHANGES_REQUESTED** [review]
Hi @nick2432, there's one more case to handle here - if the username is already existing in the facility and I attempt to import several duplicated usernames or just the same username as the one which is already in the facility, you are now checking that they are duplicated but you are still allowing one of the usernames to be imported:

https://github.com/learningequality/kolibri/assets/79847249/1667a706-8dd9-4604-a257-0e1fb83b9a08

It shouldn't be possible to import a duplicated username which is without a UUID.

**Review by akolson — CHANGES_REQUESTED** [review]
Hi @nick2432, the current changes makes make sense to me. I will however hold off the approval until the feedback from @pcenov has been added. Thanks. Also, noting that your most recent commit seems to have brought in a really huge number of changes. Is this intended?

**Comment by nick2432** [comment]
> Hi @nick2432, the current changes makes make sense to me. I will however hold off the approval until the feedback from @pcenov has been added. Thanks. Also, noting that your most recent commit seems to have brought in a really huge number of changes. Is this intended?

no

**Comment by akolson** [comment]
Please be sure to let us know how we can help in case you encounter any challenges while reverting the changes. Thanks

**Comment by rtibbles** [comment]
Retargeting this to release-v0.16.x as the issue is for Planned Patch 1.

**Comment by rtibbles** [comment]
Hi @nick2432 - sorry, after you sorted out your previous rebase woes, the retarget is going to give you more issues.

Could you please rebase this onto release-v0.16.x? See here for instructions: https://github.com/learningequality/kolibri/blob/develop/docs/howtos/rebasing_a_pull_request.md

**Comment by nick2432** [comment]
Hey @pcenov  , could you please check my new changes?

**Review by pcenov — APPROVED** [review]
Thanks @nick2432 - I confirm that now it's not possible to import duplicate usernames.

**Review by akolson — CHANGES_REQUESTED** [review]
Hi @nick2432. This looks correct to me. It would however be nice to add  some tests to https://github.com/learningequality/kolibri/blob/7fba0d2a8edd9e2edda5df9ae196865a8c624172/kolibri/core/auth/test/test_bulk_import.py as as well covering the scenarios that @pcenov raised. Thanks again

**Comment by nick2432** [comment]
> Hi @nick2432. This looks correct to me. It would however be nice to add some tests to https://github.com/learningequality/kolibri/blob/7fba0d2a8edd9e2edda5df9ae196865a8c624172/kolibri/core/auth/test/test_bulk_import.py as as well covering the scenarios that @pcenov raised. Thanks again

I will add the tests and have resolved the scenarios raised by @pcenov.

**Comment by akolson** [comment]
Thanks @nick2432.

**Comment by rtibbles** [comment]
Also worth noting that there is a test failure now of an existing test, might be worth checking if something has broken, or if an assumption of the test is now being violated:

```
kolibri.core.auth.test.test_bulk_import.ImportTestCase testMethod=test_asterisk_in_password
```

**Comment by nick2432** [comment]
@akolson  @rtibbles , I have added the tests and resolved the test failure.

**Review by akolson — APPROVED** [review]
LGTM. Thanks for seeing this through @nick2432.

**Comment by akolson** [comment]
Assigning this to Marcella for merge purposes.

**Pull request merged**
