### PR TITLE
Performance fixes

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
Bug fixes resulting for issues resulting from the recent performance updates

### Reviewer guidance
Should fix these issues:
* 500 on the learnerclassroom endpoint
* JS error when viewing Facility > Class page when coaches are assigned to classroom
* Cannot read property 'member_ids' of undefined on Coach dashboard landing page
* Coach can't enroll users to group
* Added FacilityCoach to class, try to go to Facility > Class Details - get errors
* Creating lesson assigned to group, doesn't assign group
* Class page won't load on existing database
* Users are not visible when coach goes to enroll them in a group
* Likely related to not being able to make Groups, but when copying a lesson and selecting a group to assign to, it does not assign to that group

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jonboiser** [comment]
Another bug was from removing Role ID when Serializing Roles on FacilityUser objects. Currently, you can't switch from a facility coach to class coach. You can either add the id back to the Role serializer or make this change to `userManagement/utils.js` to fix this specific bug.

```diff
  // Changing from one Facility-Level Role to another. Any Classroom-Level Roles
  // are left untouched
  if (FACILITY_ROLES.includes(newRoleKind)) {
-    return createFacilityRole().then(() =>
-      RoleResource.deleteModel({ id: currentFacilityRole.id }) // <- is a Role object, so doesn't have ID rightnow
-    );
+    return RoleResource.deleteCollection({ collection: facility }).then(() => {
+      return createFacilityRole();
+    });
  }
}

```

**Comment by rtibbles** [comment]
OK, will update, thanks!

**Review by indirectlylit — APPROVED** [review]
in the interest of keeping things as current as possible, I'll go ahead and merge this in. @rtibbles would you mind submitting the change that @jonboiser in a new PR?

**Comment by bjester** [comment]
I'm still getting a 500 error as a learner trying to view my assigned classes
```
ERROR    Internal Server Error: /learn/api/learnerclassroom/
Traceback (most recent call last):
  File "/home/bjester/.local/share/virtualenvs/kolibri-J0Tqdocd/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/bjester/.local/share/virtualenvs/kolibri-J0Tqdocd/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bjester/.local/share/virtualenvs/kolibri-J0Tqdocd/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bjester/.local/share/virtualenvs/kolibri-J0Tqdocd/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/bjester/.local/share/virtualenvs/kolibri-J0Tqdocd/lib/python3.6/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/bjester/.local/share/virtualenvs/kolibri-J0Tqdocd/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/bjester/.local/share/virtualenvs/kolibri-J0Tqdocd/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/bjester/.local/share/virtualenvs/kolibri-J0Tqdocd/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/bjester/Projects/learningequality/kolibri/kolibri/core/api.py", line 109, in list
    return Response(self.serialize(queryset))
  File "/home/bjester/Projects/learningequality/kolibri/kolibri/core/api.py", line 99, in serialize
    list(map(self._map_fields, self._serialize_queryset(queryset) or []))
  File "/home/bjester/Projects/learningequality/kolibri/kolibri/plugins/learn/viewsets.py", line 73, in consolidate
    for resource in lesson["resources"]
  File "/home/bjester/Projects/learningequality/kolibri/kolibri/plugins/learn/viewsets.py", line 73, in <genexpr>
    for resource in lesson["resources"]
KeyError: '57cab9422c62524a820d24405da6f432'
ERROR    "GET /learn/api/learnerclassroom/?1574887027929=1574887027929 HTTP/1.1" 500 34889
```

**Comment by bjester** [comment]
The following seems to fix the error, but not sure if it's appropriate:
```
diff --git a/kolibri/plugins/learn/viewsets.py b/kolibri/plugins/learn/viewsets.py
index 4e9327925..d6674f403 100644
--- a/kolibri/plugins/learn/viewsets.py
+++ b/kolibri/plugins/learn/viewsets.py
@@ -71,6 +71,7 @@ class LearnerClassroomViewset(ValuesViewset):
                     (
                         progress_map[resource["content_id"]]
                         for resource in lesson["resources"]
+                        if resource["content_id"] in progress_map
                     )
                 ),
                 "total_resources": len(lesson["resources"]),
```

**Comment by indirectlylit** [comment]
That change looks logically correct to me, since I don't see any guarantee that there should be a `progress_map` entry for every resource. I'm not sure what would have caused this change in behavior, though.

Would you mind opening a PR and I'll merge?

**Comment by bjester** [comment]
@indirectlylit Added https://github.com/learningequality/kolibri/pull/6159

**Pull request merged**
