### PR TITLE
adding scroll behavior to individual table cells when the contents are too large

### LINKED ISSUE #5106: Tooltips in CoreTable headers can get cut off at box boundary
### Observed behavior

CSS rules for CoreBase th/tds have an overflow hidden rule that cuts horizontal overflows off

screen shot 2019-02-19 at 5 49 59 pm

screen shot 2019-02-19 at 5 51 49 pm

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

### LINKED ISSUE #5118: Very long full names (or other strings) not truncated in fixed-width columns
### Observed behavior

For example, in Facility > Classes > Edit Class, the full name cell for a 100+character name actually just extends into the other columns (see the blue highlight in the screenshot), but is hidden behind those columns. I'm sure other tables probably have this issue

screen shot 2019-02-20 at 11 38 06 am

Other places this happens:

* Name and title columns in various coach reports

### Expected behavior

Table cells display long unbroken strings (and long broken strings) in a consistent, aesthetic, and accessible way. 💯 	

### Context
0.12 latest

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

This PR adds nested scrollbars to tables in order to address some outstanding issues around text truncation.

scroll

It also works to further standardize the tables by making wider use of the new core button class, which should help with button-row alignment especially in Facility tables:

| before | after |
|--|--|
|image|image|

### Reviewer guidance

As much as I hate nested scrollbars, this is the simplest strategy I can think of to handle these edge cases without coding something much more complex in JS.

Previously we were truncating the strings, but this (a) hid potentially important information, and (b) caused issues with nested tooltips

### References

* fixes #5118
* fixes #5106

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by khangmach** [comment]
Have we tried overflowing the cell data to a new line, similar to how the class name column is handled?

**Comment by indirectlylit** [comment]
> Have we tried overflowing the cell data to a new line, similar to how the class name column is handled?

yeah good point. in fact it already does that when there are spaces between words - this only kicks in when there's a single word longer than 300px

**Comment by indirectlylit** [comment]
(super edge case)

**Comment by khangmach** [comment]
interesting, thanks for clarifying!

**Review by khangmach — APPROVED** [review]

**Comment by rtibbles** [comment]
Linting error.

**Review by jonboiser — APPROVED** [review]

**Review by jtamiace — APPROVED** [review]

**Comment by rtibbles** [comment]
Seems to set scroll bars always on for Ubuntu 16.04, Chrome 72.

**Comment by radinamatic** [comment]
Chrome-only issue (Ubuntu 18.04)

ledev1901 start running - oracle vm virtualbox_430

**Comment by radinamatic** [comment]
Is this related? If yes, then it might not be Chrome-only...

ledev1901 start running - oracle vm virtualbox_432

**Comment by indirectlylit** [comment]
> Is this related? 

that would be an independent issue

**Pull request merged**
