### PR TITLE
String wrapping

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Wraps all the client side strings for core and learn.

Also adds a 'reverse text' thing to show up unwrapped strings.

Further, adds method for translating HTML strings properly.

## TODO

- [x] Wrap strings for setup wizard.

## Screenshots (if appropriate)

image

### CODE REVIEW

**Comment by indirectlylit** [comment]
irbiloK, my friend

**Comment by rtibbles** [comment]
Leaving string wrapping for user management as an exercise for the reader (i.e. when the interface has settled down somewhat!)

**Comment by rtibbles** [comment]
Updated to latest master.

**Comment by indirectlylit** [comment]
nice!

**Pull request merged**
