### PR TITLE
Wrap radio buttons inside KRadioButtonGroup component

### PR DESCRIPTION
**Pull request by muditchoudhary**
## Summary

Wrap radio buttons of Device's setting page and Change language model inside KRadioButtonGroup. This PR is made to test this component.
…

## References

…

## Reviewer guidance

1. Visit Device's settings page in firefox.
2. Visit Change language model and test.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by muditchoudhary** [comment]
@MisRob here is the PR.

**Comment by MisRob** [comment]
Thanks @muditchoudhary - one last request, in this PR, could you please also install KDS package into Kolibri via your KDS PR commit? Basically you would

- update _kolibri/core/package.json_
- update _packages/kolibri-core-for-export/package.json_
- run yarn install
- commit (including updated _yarn.lock_ file)

See example here https://github.com/learningequality/kolibri/pull/12209/files

This is to make sure that this PR will work for people who don't have KDS repository linked locally. QA team will then use build assets on the PR to test it.

**Comment by MisRob** [comment]
@muditchoudhary I think this is the commit to install https://github.com/muditchoudhary/kolibri-design-system#fddf31ef432a830b8e569bd7dc63fc6f03956d9b

**Comment by muditchoudhary** [comment]
@MisRob did it. See, if it is good to go.

**Comment by MisRob** [comment]
Thanks a lot @muditchoudhary

**Comment by MisRob** [comment]
@radinamatic @pcenov Could you please try out that this issue gets fixed in Firefox and that there are no regressions in Chrome? https://github.com/learningequality/kolibri/issues/10491

**Comment by pcenov** [comment]
Hi @radinamatic I didn't observe any regressions in Chrome and the custom implementation for Firefox looks good to me (using the Tab button instead of going straight to the Cancel button you first go to the next column with radio buttons):

https://github.com/learningequality/kolibri/assets/79847249/85533f72-ef14-4a75-a3ac-9d824967f936

**Comment by radinamatic** [comment]
@pcenov This is the [original issue](https://github.com/learningequality/kolibri/issues/10491) that the KDS change is supposed to fix, so the main question is if the user can move between radio button options with the arrow keys (for some reason that is not visible in the recording above), and jump out of the radio button group with the `Tab` key, once they have made their selection.

**Comment by pcenov** [comment]
@radinamatic - yes, I am aware of https://github.com/learningequality/kolibri/issues/10491 but apparently was overly optimistic that the recording will show clearly that now in Firefox you can indeed navigate through the radio buttons using only the arrow keys but only in the first column of languages, then you need to hit the TAB button again in order to move to the second column. So that's what's still different from the behavior in Chrome.

**Comment by MisRob** [comment]
Thank you @pcenov and @radinamatic

> then you need to hit the TAB button again in order to move to the second column

@muditchoudhary looking at code, I assume this is caused by using an instance `KRadioButtonGroup`s for each language column. I believe it could be resolved by making sure that a group of related radio buttons is a member of exactly one `KRadioButtonGroup`.

**Comment by radinamatic** [comment]
Thank you for confirming @pcenov , and yes, as @MisRob says it would be ideal if the whole list of language radio button choices could be traversed **just** with arrow keys, and not having to jump to and back columns by interjecting the Tab key navigation. 👍🏽

**Comment by muditchoudhary** [comment]
Thank you! pcenov and radinamatic.

> I believe it could be resolved by making sure that a group of related radio buttons is a member of exactly one `KRadioButtonGroup`

Okay, I will try to have some logic for this.

**Comment by MisRob** [comment]
Thanks @muditchoudhary - after this last piece, it will be great improvement for user experience

**Comment by MisRob** [comment]
@muditchoudhary I am going to be away for two weeks, back on July 8. Take all the time you need, and when I'm back if there are some updates, I will re-review. Also feel free to ping @radinamatic and @pcenov to ask for another round of QA meanwhile if you feel it's ready. Thanks and see you!

**Comment by muditchoudhary** [comment]
@MisRob Thanks for letting me know.

**Comment by muditchoudhary** [comment]
Hi @radinamatic @pcenov @MisRob I have fixed that tab issue on the change language form. But I have accidentally messed with rebasing or merge in this branch. So I will push the changes for review in a new draft branch, not in this branch. 
We may close this draft PR.

**Comment by MisRob** [comment]
Hi @muditchoudhary, thanks a lot - it seems that something unexpected happened, perhaps during the rebase? There's many unrelated files in the diff.

**Comment by MisRob** [comment]
@radinamatic after this ^ gets resolved and you do testing, would you also preview tab index behavior? I think @muditchoudhary utilizes setting it - I haven't seen the latest updates yet, however, if I recall right what we discussed in the first prototype, it should behave very similarly to how I implemented tabs navigation to ensure a11y.

**Comment by muditchoudhary** [comment]
> it seems that something unexpected happened, perhaps during the rebase?

Yes during rebase. I don't know what happened. I did the same as I usually do. I must have missed something. 

> I haven't seen the latest updates yet

I will send the draft PR today.

> if I recall right what we discussed in the first prototype, it should behave very similarly to how I implemented tabs navigation to ensure a11y.

Yes, I have used the same approach as we discussed the roving tab index one.

**Comment by MisRob** [comment]
Closing in favor of https://github.com/learningequality/kolibri/pull/12325

**Pull request closed without merging**
