### PR TITLE
Bugfix- birth year selction on profile edit page

### LINKED ISSUE #11292: Profile edit page shows incorrect label for birth year
## Observed behavior
When we try to edit birth year on our edit profile page the value and label gets mismatched due to which birth year value shows incorrect on our profile page

Screenshot from 2023-09-23 01-03-16(1)

…

## Expected behavior
The birth year we select from drop-down, exact value should show, but it shows value with 1 incremented to it

…

## Steps to reproduce
1. On localhost, go to profile section
2. Click on edit
3. Select birth year from age dropdown
4. Check the value if it is correct

...

### PR DESCRIPTION
**Pull request by haldaranup**
## Summary

After selecting birth year the value gets mismatched because of incorrect label. This is because of timezone, when localized in any timezone that is less than UTC, ex- `new Date('2023') `the date will be shown 2022 instead of 2023

Screenshot from 2023-09-23 01-03-16(1)

So, instead of passing year directly to `$fomatDate`('2023'), setting full year to it so there is no effect of timezone

Screenshot from 2023-09-29 13-15-44

…

## References
Fixes #11292 

…

## Reviewer guidance
- Go to profile edit page
- Try to change the birth year
- After saving check if the year is showing correctly

…

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
Hi @haldaranup - thanks, this definitely looks like the right fix!

I think we would like to include this in our upcoming release, so if I could ask you to rebase this PR onto release-v0.16.x that would be great.

To do this, I would suggest the following workflow:
* Make sure you have local versions of the Learning Equality develop branch and the Learning Equality release-v0.16.x branch and that they are both up to date - for the sake of the following, I will assume they are called `develop` and `release-v0.16.x` respectively.
* Locally, checkout your feature branch
* Run this rebase command: `git rebase --onto release-v0.16.x develop` this will rebase your current branch (your feature branch) onto `release-v0.16.x`, removing any commits that are already present in `develop` - so, if everything works as expected, it should keep your commit [bugfix- birth year selction](https://github.com/learningequality/kolibri/pull/11337/commits/15ce825f871d5361cfd5e4b2a79a7c8feec4879c)
* Once you have done that, you will need to force push to update your remote branch `git push --force` - if the remote branch is not set, then git should give you hints about how to push to the correct remote branch.

**Comment by haldaranup** [comment]
> Hi @haldaranup - thanks, this definitely looks like the right fix!
> 
> I think we would like to include this in our upcoming release, so if I could ask you to rebase this PR onto release-v0.16.x that would be great.
> 
> To do this, I would suggest the following workflow:
> 
> * Make sure you have local versions of the Learning Equality develop branch and the Learning Equality release-v0.16.x branch and that they are both up to date - for the sake of the following, I will assume they are called `develop` and `release-v0.16.x` respectively.
> * Locally, checkout your feature branch
> * Run this rebase command: `git rebase --onto release-v0.16.x develop` this will rebase your current branch (your feature branch) onto `release-v0.16.x`, removing any commits that are already present in `develop` - so, if everything works as expected, it should keep your commit [bugfix- birth year selction](https://github.com/learningequality/kolibri/pull/11337/commits/15ce825f871d5361cfd5e4b2a79a7c8feec4879c)
> * Once you have done that, you will need to force push to update your remote branch `git push --force` - if the remote branch is not set, then git should give you hints about how to push to the correct remote branch.

Thanks @rtibbles, I have done the steps mentioned above. Please let me know if any other changes are required or if anything is done incorrectly

**Comment by rtibbles** [comment]
Looks right to me, thank you! We will do a full review on Monday.

**Review by rtibbles — APPROVED** [review]
Code looks good and manual testing checks out - the value of the component and the label match! Could you fix the line length for your comments, so we can merge?

**Comment by pcenov** [comment]
LGTM as well, no issues observed while manually testing.

**Comment by rtibbles** [comment]
Thank you for your contribution @haldaranup!

**Pull request merged**
