### PR TITLE
Update docs: Simplified structure and fixed som introspection issues

### PR DESCRIPTION
**Pull request by benjaoming**
## Summary

Nicing up the docs a bit and consolidating final bits of hooks and plugins following the big merge.

@indirectlylit I removed the TODO.rst file in this PR!

## TODO

- [x] Remove TODO
- [x] Restructure first-level topics in docs
- [x] Add a section about testing
- [x] Automatically add `help_text` and `verbose_name` to the documentation of model fields.
- [ ] Consolidate hooks and plugins docs and examples
- [ ] New dependencies (if any) added to requirements file
- [ ] Add an entry to CHANGELOG.rst

## Reviewer guidance

View the docs here: http://kolibri.readthedocs.io/en/hooks-docs/

Once WIP status is removed, Read docs, comment if the make sense.

## Issues addressed

#93

### CODE REVIEW

**Comment by benjaoming** [comment]
Rebased so it's merge-able... instead of leaving this around, I suggest we just merge it asap to avoid further conflicts.

**Comment by benjaoming** [comment]
"conditional comparison" sounds pretty stupid... but the comparison occurred in the conditional testing script :)

**Comment by benjaoming** [comment]
@indirectlylit rebased and ready to merge

**Comment by indirectlylit** [comment]
Hey - my main comment here is around embedding the readme file in the docs. Previously I had intentionally decoupled the two: https://github.com/learningequality/kolibri/pull/136/commits/98d856db90f127db8bc3d06e236c59d1bc57c403

Curious what your thoughts are. I think many of the points are still true:

1. separating the readme from the docs allows more flexibility to target the content towards expected readers in each scenario
2. it’s not immediately obvious to a developer editing the readme that changes will also appear embedded in read-the-docs, potentially introducing weird edits that don’t make sense in the embedded context
3. the travis/codecov/rtd badges render poorly in readthedocs in a mobile view or any smaller browser window
4. the badges aren’t appropriate in that context anyway. (e.g. rtd links to itself)

an example of (3):

image

**Comment by benjaoming** [comment]
@indirectlylit -- for now, I think we should keep things tightly integrated, simple and DRY. README.rst contains information that we'd end up duplicating if we didn't put it on the cover of our docs.

I agree that the badges are a problem, but it's a bit complicated to solve. They are also online and will pose a problem once we pack and distribute the docs offline.

README.rst will probably have to fork.. but I added it back to the docs to have a more friendly landing page, since I hardly see having to separate README-ish landing pages can be made a priority atm.

> it’s not immediately obvious to a developer editing the readme that changes will also appear embedded in read-the-docs

I wouldn't worry about that, it's the same case for CONTRIBUTING and CHANGELOG. Maintaining similar information in two different locations is a bigger problem.

Btw. I've renamed the previous `setup.rst` to `dev/getting_started.rst`, I think the `dev/*` pages now have a better chronology. But we should work with these, it's our most important pages for onboarding people.

**Comment by indirectlylit** [comment]
I'll merge in, but I disagree that it's more DRY this way because all our online URLs should serve a specific, unique purpose. If anything, I think it would be simpler to take "friendly intros" out of both README and the RTD index and prominently link to learningequality.org/kolibri instead.

I'd imagine the breakdown as:

* https://learningequality.org/kolibri - friendly intro and overview page
* https://github.com/learningequality/kolibri - code, branches, testing, coverage reports, etc
* https://kolibri.readthedocs.io/en/latest/ - developer documentation
* https://kolibri.readthedocs.io/en/latest/ - end-user documentation, though eventually I believe we should separate it from dev docs to be less scary to end-users

Right now, the home page of the docs links to itself, twice. And if the user is on github and clicks over to the docs, they see the same content again...

When I first was editing README, CONTRIBUTING, and CHANGELOG I definitely did not realize they were also imported into docs, so my worry about other devs was from that experience. However for CONTRIBUTING and CHANGELOG, I think the case for DRY and importing is much stronger because they are ancillary content, not landing pages.

> Btw. I've renamed the previous setup.rst to dev/getting_started.rst, I think the dev/* pages now have a better chronology. But we should work more with these, it's our most important pages for onboarding people.. I think the dev/ docs should be our main focus for now, and we should consider ourselves as much as possible with the "outsider, that pops up and wants to commit a flyby contribution" -- not because we'd expect that to happen necessarily, but because it's a great test of how dev-friendly our efforts have turned.

that sounds great to me

thank you!

**Comment by radinamatic** [comment]
Just mentioning myself here so I can find the issue easier in future searches, as this conversation contains some interesting arguments regarding approaches for integrating docs into projects that my documentarian friends from WriteTheDocs gangs might find interesting! :wink: 

@radinamatic

**Comment by benjaoming** [comment]
@indirectlylit there are files which you always find in the root of source distributions that will have an overlap with your full, online docs. The inclusion of said CHANGELOG, README and CONTRIBUTING is an attempt to have more DRY in that regard.

The approach is from [cookiecutter](http://cookiecutter-python-library.readthedocs.org/).

**Comment by benjaoming** [comment]
...but I do share your concerns about making all our online pages as little overlapping as possible, and I hope with time we'll get there :)

**Pull request merged**
