### PR TITLE
Update facility settings link display for Learn Only Device users

### LINKED ISSUE #11877: I see the “You can also configure Facility settings” link in Device settings - but on a LOD I can’t access facility
Spotted by @nucleogenesis in the 0.16 syncing session Feb 14 2024
## Observed behavior
I see the “You can also configure Facility settings” link in Device settings - but on a LOD I can’t access facility

### PR DESCRIPTION
**Pull request by LianaHarris360**
## Summary

Previously admin users on a learn-only device could see "You can also configure Facility settings” link in Device settings, but users on a LOD cannot access the facility settings page. This pull request modifies the Device Settings page to display the link if the user is not on a Learn Only Device.

- Updates vuex `mapGetters` with `isLearnerOnlyImport` on the `DeviceSettingsPage` and modifies the conditional to display the `KExternalLink` that leads to `FacilityConfigPage`.

View of a super admin on a full device:

devicesettingspage

Updated view for admins on a learn only device:

Screenshot 2024-05-01 at 9 57 26 AM

## References

Closes #11877 

## Reviewer guidance

1. Follow the group learning setup and select Learn-Only device -> import or create a user account with an existing facility -> go to the Device settings page -> Verify that the message `The changes you make here will affect this device only.` is displayed.
2. Follow the On My Own setup -> go to Device settings page -> Verify that the message and link `The changes you make here will affect this device only. You can also configure device settings` are displayed.

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by AllanOXDi — APPROVED** [review]
Thanks for the changes @LianaHarris360 ,  Looks good!

**Review by rtibbles — APPROVED** [review]

**Comment by rtibbles** [comment]
@radinamatic can you confirm the fix manually here, and then we can merge?

**Comment by rtibbles** [comment]
Oh one thought here - as this doesn't involve any string updates, I think we could instead target this issue to the next 0.16 patch?

**Comment by pcenov** [comment]
Thanks @LianaHarris360 - I confirm that this is implemented as specified above, no issues observed while manually testing.

**Review by radinamatic — APPROVED** [review]
Manual QA passes, good to go! 👏🏽 💯 :shipit:

**Pull request merged**
