### PR TITLE
File sizes

### LINKED ISSUE #9848: Automatic Syncing Updates: Resource size is displayed for content in Reports and Plan tabs
## Overview 

This issue is a full-stack issue that updates the Coach Plugin's Reports and Plan tabs to include information about resource size, both within the resource and in the main table. 

### Figma 

Please see [complete figma spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=960%3A16822&t=yKUs0H8sJ8FrRN6r-0) for all relevant screens and details. Below is just one example
Screen Shot 2022-11-21 at 10 50 33 AM

## Acceptance Criteria
- [ ]  Frontend is updated with resources sizes on both Lesson and Quiz tables, with a total, and by-resource in each row
- [ ] Each resource has a total size available when you navigate into the resource

### Out of Scope
➡️ Accessibility notes: 
* Accessibility remediations for the reports page will be handled in . However, please do not make anything worse 😄 

## References 
- [Notion project page](https://www.notion.so/learningequality/Remote-Content-Syncing-Automatic-syncing-d0a28f150b324d4da019790228117068)
- [Figma spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=194%3A2922&t=yKUs0H8sJ8FrRN6r-0)
- [Gherkin scenarios](https://www.notion.so/learningequality/Gherkin-scenarios-02096ac9925844f8902c818cab607d4b#45dcdae16db8450b98023b559724277f)

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary
Finalized file sizes issues that were partially merged for string freeze

## References
Fixes #9848 #9850 #10158

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
Code read through makes sense - just needs manual verification of the behaviour.

**Comment by marcellamaki** [comment]
Hi @pcenov and @radinamatic - here are some more details about what is ready to be tested within the scope of this PR. 

The automated syncing work is still in progress, so the resources being "sent" to a LOD is _not_ yet ready for testing. My apologies that I really did not make this clear when opening this PR. 

This PR is just regarding the coach experience, even though I did also update some of the Gherkin scenarios to cover the _entire_ workflow.

So, things to test: 
1. **File size** in bytes should be appearing on the REPORTS tab for:
- Single lesson 
- Multiple lessons 
- Within a single lesson page
- Single quiz 
- Multiple quizzes 
- Within a single quiz page

2. **File size** in bytes should be appearing on the PLAN tab for:
- Single lesson 
- Multiple lessons 
- Within a single lesson page (dynamically updating as resources are added and removed, i.e. adding/removing a 10 MB resource, the file size in the sidebar should increase - or decrease - accordingly) 
- Single quiz 
- Multiple quizzes 
- Within a single quiz page (this is not quite as dynamic as adding and removing lesson resources, but it can still vary if the quiz is edited) 

3. When there are learn only devices in the class: 
- when the visibility of the lesson or quiz changes, the coach should see a pop up modal, informing them of the file size
- On "CONTINUE" the lesson or quiz should be "assigned" (although due to the syncing feature still being built, the resource will not actually appear on the LOD if the learner does not already have these resources just yet.). The status of being "visible to learners" should change, and the snackbar should appear. 
- If the coach selects "don't show this again" for either LESSON or QUIZ, this modal should not appear. (Please note that it is a separate "don't show this again" for lessons and quizzes, so selecting one does not change the modal behavior of the other)

4. When there are no learn only devices for learners in the class the modal about file sizes should not appear

Please do let me know if you have more questions or need clarification, and apologies again for the confusion about the LOD file syncing.

**Comment by pcenov** [comment]
Thanks for the additional details on this @marcellamaki - it summarizes nicely my expectations for the scope of this task, the only confusing bit was about whether the automatic syncing is fully functional or not.

I have reported separately the following issues: https://github.com/learningequality/kolibri/issues/10500 and https://github.com/learningequality/kolibri/issues/10501 plus there is this one https://github.com/learningequality/kolibri/issues/10483 which is fixed.

So we will need to do another QA pass on this once we have fixes for these 3 issues and the fully implemented automatic syncing.

**Comment by marcellamaki** [comment]
Thanks @pcenov!

**Review by radinamatic — APPROVED** [review]
Manual QA by @pcenov completed. Two follow-up issues will be worked on separately! 👍🏽 :shipit: 

cc @marcellamaki: https://github.com/learningequality/kolibri/issues/10500 & https://github.com/learningequality/kolibri/issues/10501

**Pull request merged**
