### PR TITLE
Update KDS package to the latest version on develop

### PR DESCRIPTION
**Pull request by MisRob**
## Summary

This prepares Kolibri for this KCheckbox update https://github.com/learningequality/kolibri-design-system/pull/351 by updating checkbox used on user's permission page to not provide its own `<label>` (which wasn't working anyways since it didn't have `for`) since it's now KCheckbox that provides it.

~~It also serves for testing by referencing my fork (commit will be reverted after the corresponding KDS PR gets merged)~~ Reverted. The PR now points to the latest KDS develop commit.

## References

https://github.com/learningequality/kolibri-design-system/pull/351

## Reviewer guidance

- Preview _Make super admin_ checkbox on the user's permissions page in the _Device Permissions_ tab as a super admin (checkbox label should be formatted as disabled) and as a learner (checkbox label should be formatted as enabled)
- Preview a couple of other places in Kolibri where we use checkboxes, for example on the _Facility settings_ page
- Check labels markup
- There should be no visual changes or regressions in checkboxes behavior

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by akolson — APPROVED** [review]
PR looks good! Thanks @MisRob

**Comment by pcenov** [comment]
LGTM @radinamatic tested in all supported browsers and couldn't find any issues with the checkboxes.

**Comment by radinamatic** [comment]
Oh, such beauty!!! 😍 

Ubuntu18 (start)  Running  - Oracle VM VirtualBox_013

**Review by radinamatic — APPROVED** [review]
Thank you so much, great improvement to have checkboxes consistently labeled! 💯 👏🏽

**Comment by MisRob** [comment]
I reverted the commit that pointed KDS to my fork for testing and pushed a commit that upgrades KDS version from https://github.com/learningequality/kolibri-design-system/commit/37dcf4f8db24d0afc5a72586bb35771dd29c8b1d to https://github.com/learningequality/kolibri-design-system/commit/269b294bf562dd7d0e3a616aaace97bf0d3433c3 so this should be ready to merge.

**Review by marcellamaki — APPROVED** [review]
Code update to the kds reference looks fine, and manual QA works

**Pull request merged**
