### PR TITLE
Frontend tasks API updates

### LINKED ISSUE #9394: Updates required on the front end for the new Tasks backend
## Description 

https://github.com/learningequality/kolibri/pull/8269 shifted all tasks of `core/tasks/api.py` to their core django apps -- the place where they actually belong. The tasks on `core/tasks/api.py` were not removed because removing them will break kolibri. We need updates on the frontend before we remove tasks from the `core/tasks/api.py`. 

So, here are the updates required for tasks:

- [ ] All tasks will be enqueued via single `POST /api/tasks/tasks/` endpoint. 
- [ ] Include the dotted task function path on every task payload like 
`{ "task": "kolibri.core.content.tasks.startcontentimport", ... }`. `track_progress` and `cancellable` parameters should be removed. Rest all parameters will remain as is. 
- [ ] `startdataportalbulksync` will be repalced with `startdataportalsync`. Our frontend will first fetch all the registered facilities and then it'll use our new task create api to enqeue `startdataportal` in bulk which will mimic `startdataportalbulksync`.
- [ ] Similarly, `startbulkdelete` will be replaced with bulk version of `startdeletechannel`.
- [ ] And `startdiskbulkexport` will be replaced with the bulk version of `startdiskexport`.

Supporting documentation: https://kolibri-dev.readthedocs.io/en/develop/backend_architecture/tasks.html.

If this needs any clatification, more details or any help then please DM me on Slack and I'll be happy to help!

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Updates all frontend task handling to use the new tasks API
* Fixes issues in backend tasks that became apparent while manually testing the frontend

## References
Fixes #9394 

## Reviewer guidance
Ideally this needs manual testing of:
All content import, export, and deletion work flows.
All syncing, import, and deletion workflows for the Facility tab in device.
All setup wizard import workflows (currently inaccessible in the UI).
All CSV export and import workflows in the Facility -> Data tab.

This PR does not currently fix an issue where an import of a complete channel shows the progress bar going to 100%. This is a regression introduced by the previous backend refactors, but I didn't fix it here because it would require a bigger diff to break out the channel import management command into more composable functions.

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [x] Critical user journeys are covered by Gherkin stories
- [x] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
Here are the findings using the Debian package:

1. Content import, export, and deletion - It is possible to import a channel or resources through all 3 options but there are several issues. Export and delete are not functioning.

| Issue| Screenshot |
:-------------------------:|:-------------------------:
| Import from Kolibri studio - Error after clicking "Select resources. The error is observed each time I click "Select resources" for the first time and after that I'm able to see the resources |  |
:-------------------------:|:-------------------------:
| Import from Kolibri studio - When I attempt to import all or some of the resources I see a "Task could not be started message and it seems that nothing is happening while in reality the channel resources are being downloaded in the background |  |
:-------------------------:|:-------------------------:
| Delete or Export - Both Delete and Export are not functioning at all  |  |
:-------------------------:|:-------------------------:
| Task manager - No tasks are displayed in the Task manager |  |

2. Syncing, import, and deletion workflows for the Facility tab in device - Import is working with some errors in the console, syncing is broken, deletion is functional

| Issue| Screenshot |
:-------------------------:|:-------------------------:
| Import a Facility - Some errors in the console after a successful import | |
:-------------------------:|:-------------------------:
| Sync a facility - Not able to sync a facility, getting a Bad request error after clicking "Continue" and both buttons get disabled | |

3. Setup wizard import workflows (currently inaccessible in the UI). - Not tested
4. CSV export and import workflows in the Facility -> Data tab - Both export and import are functioning correctly

Logs: [logs.zip](https://github.com/learningequality/kolibri/files/8772677/logs.zip)

**Comment by rtibbles** [comment]
Seems like I missed some things in my manual testing :)

One thing to flag:

> Import a Facility - Some errors in the console after a successful import

These errors are independent of my PR and are coming from Kolibri Design System - I have an open PR there that addresses it, but it has yet to be merged.

**Comment by rtibbles** [comment]
@radinamatic @pcenov I think I've resolved all reported issues now.

**Review by jredrejo — CHANGES_REQUESTED** [review]
Importing/exporting csv of data works fine. 
However I still see problems when trying to import content from channels:
1. When importing a channel I see:
image
However, clicking on the task manager:
image
it seems tasks polling is cleared there. I can see how the command loading the content is working in the background though

2. Same thing happens when trying to upgrade a channel after seeing 
image
Clicking on view changes takes you to a page where not polling on the tasks is done, so the button to update the channel is never enabled:
image

I see correct all the backend/frontend code excepting the monitoring of the tasks status in these places.

**Comment by pcenov** [comment]
Retested on Windows, Ubuntu and Android using the latest build. The issues reported by me are now fixed. Note that I'm not able to replicate @jredrejo's findings in the latest build.

1. Content import, export, and deletion - All 3 functioning with some exceptions:

| Issue| Screenshot |
:-------------------------:|:-------------------------:
| Delete or Export an entire channel - Getting a 400 bad request error  |  |
:-------------------------:|:-------------------------:
| Import an entire channel from a device on the local network - The import fails and I see an error in the logs | |
:-------------------------:|:-------------------------:
| Import an entire channel from attached drive - The import fails and I see an error in the logs | |

2. Syncing, import, and deletion workflows for the Facility tab in device - Import, syncing and deletion are functional. Found an issue with not being able to sync a learn only device which might or might not be caused by these changes:

| Issue| Screenshot |
:-------------------------:|:-------------------------:
| Learn only device syncing - None of the information for the completed resources is synced back to the server |[AndroidLogsDB.zip](https://github.com/learningequality/kolibri/files/8779325/AndroidLogsDB.zip) |

3. Setup wizard import workflows (currently inaccessible in the UI). - Not tested
4. CSV export and import workflows in the Facility -> Data tab - Both export and import are functioning correctly

**Comment by rtibbles** [comment]
@jredrejo I think the issues you reported were possibly prior to my latest pushes? There was definitely an issue with the content management task polling (I had moved it out of the device index page, but had only put it in one, not all of the base pages for content tasks).

**Comment by rtibbles** [comment]
This seems to be the relevant traceback for the peer syncing issues:
```
ERROR 2022-05-26 11:21:38,763 kolibri.core.tasks.job Job 5da456c51ea016bbafd4ad0f7a491bc6 raised an exception: Traceback (most recent call last):
  File "/home/kivy/build/android/kolibri/core/auth/tasks.py", line 437, in peerusersync
  File "/home/kivy/build/android/kolibri/dist/django/core/management/__init__.py", line 131, in call_command
  File "/home/kivy/build/android/kolibri/dist/django/core/management/base.py", line 330, in execute
  File "/home/kivy/build/android/kolibri/core/tasks/management/commands/base.py", line 119, in handle
  File "/home/kivy/build/android/kolibri/core/auth/management/commands/sync.py", line 167, in handle_async
  File "/home/kivy/build/android/kolibri/core/auth/management/utils.py", line 265, in get_client_and_server_certs
django.core.management.base.CommandError: Server username and/or password not specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kivy/build/android/kolibri/core/auth/tasks.py", line 451, in peerusersync
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kivy/build/android/kolibri/core/tasks/job.py", line 110, in execute_job
  File "/home/kivy/build/android/kolibri/core/tasks/registry.py", line 191, in __call__
  File "/home/kivy/build/android/kolibri/core/auth/tasks.py", line 463, in peerusersync
KeyError: 'user'
```

Will fix.

**Comment by rtibbles** [comment]
Looks like I need to do more testing on the bulk workflows!

**Comment by jredrejo** [comment]
> @jredrejo I think the issues you reported were possibly prior to my latest pushes? There was definitely an issue with the content management task polling (I had moved it out of the device index page, but had only put it in one, not all of the base pages for content tasks).

should I test it in a previous commit?

**Comment by jredrejo** [comment]
> 

mmm, I've tested this week peerusersync using the api_explorer and worked perfectly, so it's probably some problem with the frontend not sending all the data
```
{
    "type": "kolibri.plugins.auth.tasks.peerusersync",
    "baseurl": "http://192.168.0.201:80/",
    "facility": "41d0e8bb1600347f17ab3d9172fff87a",
    "username": "uno",
    "password": "pass"
}
```
should work. With the mess of the parameters we're using maybe you're using user instead of username

**Comment by rtibbles** [comment]
@pcenov - I have replicated and resolved all the issues that you reported, with the exception of the bulk import from peers. Looking at the error in the terminal, this appears to be because you had insufficient storage on the device to complete the import. I don't think this is a regression from my work.

@jredrejo I have double checked and all the pages that you were reporting issues on do have the task polling composable embedded in them, so I think your prior test must have happened before I had pushed commit. Tasks should be being properly polled everywhere.

**Review by nucleogenesis — APPROVED** [review]
Frontend looks good to me. The Task resource is much simpler now. I appreciate the change for the Tasks constants to refer to Python paths rather than dummy values - I think it'll be helpful for any debugging between front-end and back-end to know exactly where to look when something goes sideways :). Whenever tests and others' comments are addressed this should be good to go.

**Review by jredrejo — APPROVED** [review]
Latest tests are fine and code is good for me.

**Comment by pcenov** [comment]
Retested today using the latest Linux, Windows and Android builds - all reported issues are now fixed.
Syncing a learn-only Android device to the server is still not fully functional - I was able to complete a lesson and sync the results but after creating an additional lesson and a quiz these are never displayed on the learn-only device regardless of the number of times I restarted both the server and the app. Logs and DB for that:
[AndroidLogsAndDB.zip](https://github.com/learningequality/kolibri/files/8804546/AndroidLogsAndDB.zip)
[UbuntuLogsAndDB.zip](https://github.com/learningequality/kolibri/files/8804642/UbuntuLogsAndDB.zip)

**Comment by rtibbles** [comment]
I think I have fixed the final scenario - there was still a code error when the sync was resuming.

**Comment by pcenov** [comment]
@rtibbles it seems that the app-server syncing is still not fully functional as once I complete a lesson or a quiz in the app I have to manually restart both the app and the server for the sync to occur.
I see the following error in the app's logs:
`ERROR 2022-06-01 07:56:46,158 kolibri.core.tasks.job Job 11cb296579734b9c88599dc59918fafb raised an exception: Traceback (most recent call last):
  File "/home/kivy/build/android/kolibri/core/tasks/job.py", line 110, in execute_job
  File "/home/kivy/build/android/kolibri/core/tasks/registry.py", line 191, in __call__
TypeError: request_soud_sync() got an unexpected keyword argument 'job_id'`
[LogsDB.zip](https://github.com/learningequality/kolibri/files/8814550/LogsDB.zip)

**Comment by rtibbles** [comment]
Thanks @pcenov - that definitely seems like an error. Will fix!

**Comment by rtibbles** [comment]
Have updated.

**Comment by pcenov** [comment]
The 'job id' error is now fixed in the latest build and there are no other issues that I am aware of. Note that we haven't tested the setup wizard import workflows as these are still inaccessible in the UI.

**Pull request merged**
