### PR TITLE
Fix appearance of long label (in certain locales) and remove disabling for "select resources" buttons. 

### LINKED ISSUE #6528: Cannot import a second channel from Studio in IE11
### Observed behavior
Noticed while testing the 0.13.1b1.

When using IE11 it seems to be possible to import resources only from one public channel on Studio, as when you make a second attempt and press the `Select resources` button for any other  channel, nothing happens (user would expect to see the channel topic tree loading at this point).

- It is still possible to import unlisted channels using the token.
- If user stops and restarts Kolibri, they are now able to import, but only once.
- It is possible to import resources correctly from more than one channel in FF & Chrome. 

### Expected behavior
User needs to be able to import from more than one channel.

### User-facing consequences
Impossibility to import content on IE11.

### Errors and logs
Nothing visible in the console or network tab

### Steps to reproduce
1. Open Kolibri in IE11 on Windows 7.
2. Import a resource from one channel from Studio
3. When the task is finished, try importing from another channel.

### Context
 * Kolibri version: 0.13.1b1
 * Operating system: Windows 7
 * Browser: IE11

I'll install on Windows 10 and see if I can replicate on Edge.

cc @jonboiser @indirectlylit @lyw07

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

1. Implements a locale-independent fix for #6443 by making all three major columns in the relevant card component direct siblings of each other
. This ensures the "select resources" button isn't pushed off to the right.

Screenshot in Portuguese
Screen Shot 2020-02-11 at 12 59 58 PM

2. Removes logic that would disable the "Selected resource" button if any "active" tasks where in the task queue, which should fix #6528 , where in this button was functionally disabled, but was not styled at such.

3. Deletes some dead CSS, and the now-dead code for the activeTaskList getter
### Reviewer guidance

1. In IE11 and other browsers, check to see the "Selected resource" button is not cut off on the right edge for different locales.
1. In IE11 specifically, check to see that the importing resources workflow is not blocked at the Channel list when there are active tasks in the queue.

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
Looking good when I checkout your branch in my dev env, even when I try with the longer string `Sélectionnez les ressources` (we may change that in 0.14). 

Selection_321

I'll install the `exe` asset on Windows VM next to confirm and approve.

**Comment by radinamatic** [comment]
Hm, it does not seem to be working well in IE11/W7  :confused: 

Peek 2020-02-12 02-09

Import works OK though, even when there are completed but not cleared tasks in the queue :+1: 


Width in Firefox looks OK:

ff

**Comment by jonboiser** [comment]
@radinamatic Does the layout change to a columnar mobile layout if you keep narrowing the window on either IE or firefox?

**Comment by radinamatic** [comment]
Eventually it does, but not really smooth transitions... That's IE for you, I guess :unamused: 

IE

**Comment by jonboiser** [comment]
Yeah, the cards don't look great even on Chrome at that in-between width. I think the responsive layout should probably kick in at the "medium" screen breakpoint to address the general lack of responsiveness at between-medium-and-small range.

At least the label doesn't get cut at the larger window width.

**Comment by indirectlylit** [comment]
let's open a subsequent issue to improve the responsiveness of this screen

**Review by radinamatic — APPROVED** [review]
Button is functional, let's deal with the width on IE and window responsiveness in subsequent PRs.

**Pull request merged**
