### PR TITLE
Add a plugin to generate launchers for Linux desktops

### PR DESCRIPTION
**Pull request by dylanmccall**
### Summary

This adds an optional 'app_desktop_xdg' plugin which generates desktop
launchers for Kolibri channels. These launchers and icons are created in
in '$KOLIBRI_HOME/content/xdg/share'. A user can then add that path to
their XDG_DATA_DIRS environment variable.

Launcher files are updated automatically whenever there is a change to
channel metadata.

### Reviewer guidance

To test these changes you have to add KOLIBRI_HOME/content/share to XDG_DATA_DIRS. This can be achieved by, for example, in a modern systemd based system, by creating the following executable file in /usr/lib/systemd/user-environment-generators/61-kolibri:

```
#!/bin/bash

# This will work for Flatpak Kolibri, change it if required
XDG_DATA_DIRS="$HOME/.var/app/org.learningequality.Kolibri/data/kolibri/content/xdg/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
echo "XDG_DATA_DIRS=$XDG_DATA_DIRS"
```

Then reboot the computer and add/delete channels to see the launchers.

### References

This pull request is a replacement for #7720.

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by dylanmccall** [comment]
This needs a little more work (note the big TODO around icon generation), but I'm happy with how it looks at the moment so very interested in any feedback people might have :)

**Comment by dylanmccall** [comment]
Okay, this is ready for review now :) I ended up adding a dependency on Pillow to cover our needs for smushing channel thumbnails into a shape that resembles an app icon. I suspect this might not _really_ belong upstream here as a result, but I figure I should make a PR at least to see what you all think. (And there's no problem shipping the plugin separately if indeed the added dependency is trouble).

**Comment by rtibbles** [comment]
Yeah, unfortunately Pillow is mostly C libraries so is not something that we can readily add to upstream. I can give this a review tomorrow though for the interface elements.

**Comment by dylanmccall** [comment]
Okay, that makes sense. Thanks for checking :) I went ahead and split this into a separate repo: https://github.com/endlessm/kolibri-app-desktop-xdg-plugin/.

And then there's a pull request to conditionally enable it in the GNOME desktop app:

https://github.com/learningequality/kolibri-installer-gnome/pull/27

**Pull request closed without merging**
