### PR TITLE
remove instructions that made corruption worse not better

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

In the case of DB corruption, the current instructions advise users to:

```bash
sqlite3 {path} .dump | sqlite3 fixed.db
cp fixed.db {path}
```

User who run these commands will add another layer of corruption on top of the first.

From the docs in [1.4. Mispairing database files and hot journals](https://www.sqlite.org/howtocorrupt.html), the following actions are all likely to lead to corruption:

* Swapping journal files between two different databases.
* Overwritting a journal file with a different journal file.
* Moving a journal file from one database to another.
* Copying a database file without also copying its journal.
* Overwriting a database file with another without also deleting any hot journal associated with the original database. 

Furthermore by having the user overwrite the old DB without backing it up, it made it impossible for us to get a copy of the original corrupted DB.

### Reviewer guidance

Do the new instructions make sense?

### References

* Hopeful fix for DB corruption in #5201
* Refs #3825

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by indirectlylit** [comment]
also updated to re-raise exception rather than sys.exit - is this preferable to get the stack trace?

**Review by rtibbles — APPROVED** [review]

**Comment by benjaoming** [comment]
Would this mean that the current `dbrestore` command suffers from the same issue? I.e. would it be safe to delete/backup journals upon restoring?

Also, are journals needed when running `dbbackup` or is it better/safer to ignore them, as long as the `dbrestore` command doesn't mix mis-matching databases and journals?

**Comment by jredrejo** [comment]
when doing `dbbackup` journals are not included in the backup, but you can't delete current db journals because there would be data corruption. Actually, if the db is closed when doing the backup there should not be any journal. This is something that should be fixed if there are any.

On the other hand, I am not sure about `dbrestore`. If it relies on internal sqlite restore mechanisms it should take care of the journals, if it's a manual restore, journals should be removed before doing the restore process.

**Comment by benjaoming** [comment]
> This is something that should be fixed if there are any.

Yes :) And that's the question, I don't know the internals of SQLite. We do use SQLite execute statements for the restore itself, but we wipe the db file firstly, not any journal files. See from the line `# Wipe current database file`...

```
    dst_file = settings.DATABASES["default"]["NAME"]

    # Close connections
    db.connections.close_all()

    # Wipe current database file
    if not db.connections["default"].is_in_memory_db():
        with open(dst_file, "w") as f:
            f.truncate()
    else:
        logger.info("In memory database, not truncating: {}".format(dst_file))

    # Setting encoding=utf-8: io.open() is Python 2 compatible
    # See: https://github.com/learningequality/kolibri/issues/2875
    with open(from_file, **KWARGS_IO_READ) as f:
        db.connections["default"].connect()
        db.connections["default"].connection.executescript(f.read())

    # Finally, it's okay to import models and open database connections.
    # We need this to avoid generating records with identical 'Instance ID'
    # and conflicting counters, in case the database we're overwriting had
    # already been synced with other devices.:
    from morango.models import DatabaseIDModel

    DatabaseIDModel.objects.create()

```

**Pull request merged**
