### PR TITLE
Video player header display and zoom problem resolved

### LINKED ISSUE #9501: Microsoft Edge browser - Video player is displayed with hidden header
## Observed behavior
When I open a video resource using Microsoft Edge browser the video player is displayed so that the header is hidden (if I scroll up I can see the header but I have to do that every time) and everything looks zoomed in.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-python-package/builds/5658 from https://github.com/learningequality/kolibri/pull/9222
2. Go to the Library and click on a video resource

## Usage Details
Windows 10 - Microsoft Edge

### PR DESCRIPTION
**Pull request by GarvitSinghal47**
Fixes #9501 

## Summary

Before:

[Folders - Touchable Earth (en).webm](https://github.com/learningequality/kolibri/assets/82756460/fed39f7f-4f2d-4205-b6b3-8281b40bdc4d)

After:

[Folders - Touchable Earth (en) (1).webm](https://github.com/learningequality/kolibri/assets/82756460/7c50ebc0-49e6-42ce-bf5e-4cc5277b7513)

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by akolson — COMMENTED** [review]
@GarvitSinghal47 Thanks! This change looks correct to me. Also, no regressions have been experience while doing manual QA. I will probably hold off my approval until @pcenov does a more comprehensive check on the fix

**Review by pcenov — CHANGES_REQUESTED** [review]
@GarvitSinghal47 for some reason now the videos are displayed in weird aspect ratio (very small height of the player) so that if I shrink the page to mobile view the dimensions of the video player would become 393 x151 pixels which is unwatchable. @MisRob could you take a look and advice what should be the proper aspect ratio of the video player?

https://github.com/learningequality/kolibri/assets/79847249/277ea3dc-5d5d-402f-bc3c-cabd17c6334a

**Comment by MisRob** [comment]
Thank you, @pcenov.

@GarvitSinghal47 I can see that aspect ratio settings was changed from 16/9 to 2.6 for when the video is not fullscreen.

Could you please elaborate on your approach of solving the bug reported here https://github.com/learningequality/kolibri/issues/9501? The issue seems to be related specifically to some problems on Microsoft Edge but code changes in this PR will cause all videos aspect ratio to change. I can't understand how it relates to header and zoom problems.

**Comment by MisRob** [comment]
Closing due to no activity. If you wished to continue on this @GarvitSinghal47, please let us know and we can re-open.

**Pull request closed without merging**
