### PR TITLE
Added superuser gherkin scenarios

### PR DESCRIPTION
**Pull request by radinamatic**
### Summary

Superuser pickles and assorted other edits...

Ready for review & merge!

### CODE REVIEW

**Comment by radinamatic** [comment]
@mrpau-richard This should be ready for review & merge as soon as all the checks pass!

There are 3 more drafts for coach scenarios that @mrpau-julius can finish:
- `coach-remove-lesson-resources.feature`
- `coach-rename-lesson.feature`
- `coach-reorder-lesson-resources.feature`

**Comment by mrpau-julius** [comment]
@radinamatic Ok will added that .feature in this week task, thanks 😃

**Comment by radinamatic** [comment]
You can jump on that as soon as @mrpau-richard merges this! 😉

**Review by mrpau-richard — APPROVED** [review]

**Comment by mrpau-richard** [comment]
Thank @radinamatic, merging this.

**Pull request merged**
