### PR TITLE
Fixes hidden search elements in search panel on scroll

### LINKED ISSUE #10775: Library - Search bar - Cannot scroll all the way to the bottom
## Observed behavior
On devices with smaller screen size there is a scrollbar being displayed for the search bar and in some cases it's not possible to view the lowest positioned filter such as the Channels drop-down.

## Expected behavior
All filters should be fully visible when I scroll down.

## Steps to reproduce the issue
1. Install the the latest 0.16.0a14 build
2.  Import the QA channel and navigate to Learn > Library
3. Observe the the filter section of the page

## Video
https://github.com/learningequality/kolibri/assets/79847249/25f6d278-52eb-4b8b-9d27-46c23b8c1b97

## Usage Details
Windows 10, Ubuntu 22  - Chrome, Firefox

### PR DESCRIPTION
**Pull request by akolson**
## Summary

This pr fixes hidden search elements in the search panel on scroll.
**Before:**

https://github.com/learningequality/kolibri/assets/79847249/25f6d278-52eb-4b8b-9d27-46c23b8c1b97

**After:**
_Show resources as last filter_
image
Accessibility as last filter
image
_Activities as last filter_
image

## References

Fixes https://github.com/learningequality/kolibri/issues/10775

## Reviewer guidance

1. Import the QA channel and navigate to Learn > Library
2. Observe the the filter section of the page while resizing the browser window to allow the search panel scroll.

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by nucleogenesis — COMMENTED** [review]
Code changes look good! I'll leave the final approval to @pcenov 's QA

**Review by pcenov — CHANGES_REQUESTED** [review]
Hi @akolson unfortunately this is not working in IE11 and mobile browsers such as Chrome and Firefox for Android as I am not able to see the 'Channel' dropdown in these browser when I scroll down. Here's a video for Internet Explorer 11:

https://github.com/learningequality/kolibri/assets/79847249/151665a5-1f1e-46e4-905f-88ee7993f380

Note that you have to check this in an actual mobile phone device as if you are using Chrome's device emulator everything is looking just fine.

**Comment by akolson** [comment]
It turns out there is a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1417667) associated with `overflow-y: scroll;` that doesn't seem to take the bottom padding into consideration in some browsers. There is a [workaround](https://stackoverflow.com/questions/48687129/padding-bottom-not-working-in-firefox-ie11), 🤞 it works

**Comment by akolson** [comment]
Hi @pcenov! Issue has been resolved on IE11 and, on chrome and firefox mobile browsers;
**IE11**
image

**Chrome Mac**
image

**Firefox Windows**
image

**Chrome Android**
image

**Firefox Android**
image

**Review by pcenov — APPROVED** [review]
Awesome @akolson - I confirm that this is fixed now in IE11 and mobile browsers.

**Pull request merged**
