### PR TITLE
Fix sync progress tracking overflow

### LINKED ISSUE #10077: peerfacilityimport task progress update bug
## Observed behavior

The `progress` and `total_progress` values for the `peerfacilityimport` job are being set and reset inconsistently resulting in the progress percentage coming back as over 1.0 (translating into > 100% values being returned from the api).

`JobProgressMixin.start_progress` is being called from `kolibri.core.auth.management.utils._queueing_tracker_adapter` and thats where I decided I should just write an issue and discuss w/ @rtibbles and/or @bjester 

Logging the values of `self.progress` and `self.total_progress` in `kolibri.core.tasks.job.percentage_progress`, I get the following entries (I believe they're called about 2s apart):

|progress|total progress|
|-|-|
|0|0|
|0|0|
|0|0|
|1|2|
|1|2|
|0|2|
|0|2|
|1|2|
|2|2|
|3|2|
|N|2|

So it starts with 0 on both, then goes straight to 50%, then just counts up infinitely without stopping.

**ALSO** - There isn't a message so the task just says "Unknown" as its status on the loader.

## Expected behavior

- `progress_percent` cannot return anything less than 1.0
- the progress of the job should be updated accurately and reflected accurately via the api

## User-facing consequences

Unclear status of tasks.

## Steps to reproduce

Try to import a facility from another device using the branch at #9896 

## Context

#9896

### PR DESCRIPTION
**Pull request by bjester**
## Summary

~This made sense when I first made the changes. Then looking back through, it doesn't seem that it actually does anything differently than before. It does seem to work though~:

Screenshot from 2023-04-25 13-02-39

@rtibbles has now updated this. This seems to make more sense, as it seemed to be an issue with `start_progress` being called outside the context of the signal handlers, so the progress total was being rapidly set to 2, then 100, then 2 - and then never being reset.

## References

Fixes https://github.com/learningequality/kolibri/issues/10077

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by pcenov — APPROVED** [review]
I can confirm that now the progress bar never runs over 100%. At the same time in all my tests it goes from 0 to 50% and then it finishes without showing any other percentage values, such as 75% for example:

https://github.com/learningequality/kolibri/assets/79847249/8648cc50-8734-4c8f-a2ac-0b087fb2e3aa

**Comment by rtibbles** [comment]
Hrm, not a roaring success then! I'll see if I can get 100% all the way!

**Comment by rtibbles** [comment]
This should now be correctly reaching 100%:

[Screencast from 08-22-2023 01:00:30 PM.webm](https://github.com/learningequality/kolibri/assets/1680573/011f9090-c52e-4df4-825e-816524c9a955)

**Comment by pcenov** [comment]
@rtibbles I confirm, this is working correctly now, never going over 100% as well:

https://github.com/learningequality/kolibri/assets/79847249/2760896e-e6ff-40f5-ab01-7a9a18880b0b

**Pull request merged**
