### PR TITLE
Language updates

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

* manual fixes for strings lost in the great TM fire 🔥 
* update all i18n data to latest from crowdin
* update source noto fonts, and improve tooling for doing that

### Reviewer guidance

check that languages and fonts load as expected

### References

follow up from #4461

----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by indirectlylit** [comment]
also finally fixes #3648

**Comment by radinamatic** [comment]
@indirectlylit From the  cursory look everything seems to display correctly (Windows 7). :+1: 

Anything specific that might fail, and needs a deeper dig?

win7 start running - oracle vm virtualbox_121

**Comment by radinamatic** [comment]
Although Bulgarian Cyrillic does not look that sleek on this Windows, as on the latest screenshots that I remember... :thinking: 

win7 start running - oracle vm virtualbox_123

**Comment by indirectlylit** [comment]
@radinamatic thanks - mind filing a follow-up issue for bulgarian?

**Comment by indirectlylit** [comment]
also one for these scroll-bars?

image

**Comment by indirectlylit** [comment]
hahha looking at those screenshots I see half a dozen issues to file...

**Comment by radinamatic** [comment]
Bengali has problems on Firefox and IE, and Bulgarian looks bad on Firefox:

win7 start running - oracle vm virtualbox_125

**Comment by radinamatic** [comment]
Yoruba not showing correctly on Ubuntu 16.04:

ubuntu 16 04 3 upgraded to 0 11b2 running - oracle vm virtualbox_126

**Comment by indirectlylit** [comment]
I think the git LFS is messing with builds

**Comment by indirectlylit** [comment]
this should be working now. Would someone mind giving it a final review so I can merge in and tag beta3?

**Comment by indirectlylit** [comment]
hmm may have spoken too soon .. local builds work fine but remote still not

**Comment by radinamatic** [comment]
@indirectlylit Are the assets good to download & test?

**Comment by radinamatic** [comment]
Seem to be installing fine :)

**Comment by indirectlylit** [comment]
yeah the fonts still don't load for me though

**Comment by radinamatic** [comment]
Bengali is still not correct, but Bulgarian fonts actually display well when the interface is _in Bulgarian_, and not when I switch to another language:

win7 start running - oracle vm virtualbox_147

**Comment by benjaoming** [comment]
> but Bulgarian fonts actually display well when the interface is in Bulgarian, and not when I switch to another language:

This seems like a separate issue: Choosing the right font subset is based on the active UI language? @indirectlylit this could be a separate issue that isn't a blocker for 0.11.

**Comment by radinamatic** [comment]
@indirectlylit 

Not sure if it helps, but I dug deeper into the issue with Bulgarian Cyrillic. It displays correctly when UI language is in _Latin based alphabets_ (`en`, `es`, `fr`, `pt`, and even `vi`, `ny`, `sw`, `yo`, plus Bulgarian itself), but fails on non-Latin locales like `ar`, `bn`, `hi`, `mr`, `fa`, `te`, `ur`. The error is consistent in Firefox 58-63 on both Windows 7 (screenshot above), and Windows 10:

win10 start running - oracle vm virtualbox_153

Firefox & IE/Edge also display Hindi, Marathi & Bengali differently than Chrome:

*Bengali*
win10 start running - oracle vm virtualbox_155


*Hindi*
win10 start running - oracle vm virtualbox_156


*Marathi*
win10 start running - oracle vm virtualbox_157


IE 11 on Windows 7, and  MS Edge on Windows 10 are displaying Cyrillic correctly independently of the UI locale, but have the same _ghost_ chars on Hindi, Marathi & Bengali:

win7 start running - oracle vm virtualbox_152


win10 start running - oracle vm virtualbox_154

**Comment by radinamatic** [comment]
And I see you've just committed more stuff, so the above might be obsolete... :woman_facepalming:

**Comment by radinamatic** [comment]
Yey, awesome job @indirectlylit !!! :100: 

win7 start running - oracle vm virtualbox_158

**Comment by indirectlylit** [comment]
the top-right one still looks broken?

**Comment by indirectlylit** [comment]
I'm going to merge this in to unblock others - let's open new issues for outstanding problems

**Comment by radinamatic** [comment]
Good eye! 
Marathi does not load correctly, but it seems to try to load Arabic font...? :thinking: 

win7 start running - oracle vm virtualbox_163

**Comment by indirectlylit** [comment]
> Marathi does not load correctly, but it seems to try to load Arabic font...? 🤔

Great eye yourself! that's exactly right, thank you

**Pull request merged**
