### PR TITLE
Overrides prop default flipping behaviour

### PR DESCRIPTION
**Pull request by kafukoM**
## Summary
This pull request extends the enhancements introduced in the recent KDS component update addressing this issue (https://github.com/learningequality/kolibri-design-system/issues/432). It adjusts the constrainToScrollParent prop of the KDropdownMenu component within Kolibri. Previously, we updated the KDropdownMenu in the KDS repo to support a new prop allowing for more flexible dropdown positioning. This PR leverages that enhancement in Kolibri by setting constrainToScrollParent to false for a specific instance (Facility Settings template) of KDropdownMenu, ensuring that the dropdown always displays downwards, improving UX under specific layout conditions.

…

## References
Issue in KDS - https://github.com/learningequality/kolibri-design-system/issues/432
PR in KDS - https://github.com/learningequality/kolibri-design-system/pull/586

…

## Reviewer guidance
Steps to test

    Go to Facility
    Click Settings
    Scroll down and create PIN if non-existent
    Click Options button

…

----

## Testing checklist

- [X] Contributor has fully tested the PR manually
- [X] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional

### CODE REVIEW

**Comment by kafukoM** [comment]
@akolson @MisRob  Kindly requesting for a review

**Review by akolson — CHANGES_REQUESTED** [review]
This change looks correct to me. Thanks @kafukoM.
I'll however add a blocker as this should only be merged after https://github.com/learningequality/kolibri-design-system/pull/586 is merged and a new kds npm package published. Also, the [KDS](https://github.com/learningequality/kolibri/blob/3490eaca1c19441c19bf83c589d7af64950484ca/kolibri/core/package.json#L24) version in your pr should be updated accordingly before the merge.

@MisRob please be sure to let me know whenever the npm release from [this fix](https://github.com/learningequality/kolibri-design-system/pull/586) is ready so this can be updated and merged as well. Thanks

**Comment by MisRob** [comment]
@akolson I will release it by the beginning of next week

**Comment by akolson** [comment]
Thanks @MisRob!

**Comment by akolson** [comment]
Hi @kafukoM, could you please update the KDS version of this pr to 3.1.1 so we can have manual QA on it?

https://github.com/learningequality/kolibri/blob/3490eaca1c19441c19bf83c589d7af64950484ca/kolibri/core/package.json#L24

**Comment by akolson** [comment]
Please remember to run `yarn install` and test it. Let me know when ready so I can tag manual QA. Feel free to add images, videos so QA is able to better understand what was fixed. Thanks

**Comment by kafukoM** [comment]
Hello @akolson. I have made the requested changes to the package.json file.

**Review by akolson — APPROVED** [review]
This looks correct me. Tagging QA to have a look before the merge. Thanks @kafukoM!

**Review by pcenov — APPROVED** [review]
Thanks @kafukoM - I confirm that this is implemented as specified and there are no issues observed while manually testing the drop-down.

**Comment by akolson** [comment]
Thanks @pcenov @kafukoM.

**Pull request merged**
