### PR TITLE
Break words on cards

### PR DESCRIPTION
**Pull request by christianmemije**
### Summary
Before

localhost_8000_learn_

After

localhost_8000_learn_ 1

### Reviewer guidance

…

### References

#4419

----

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by benjaoming** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/word-break#Browser_compatibility

**Review by jonboiser — APPROVED** [review]
Looks gooooooooooooo
ooooooooo
oooooooooood!

**Comment by christianmemije** [comment]
@benjaoming Great catch! Added a fallback
ie

**Comment by benjaoming** [comment]
Thanks @christianmemije :)

**Comment by benjaoming** [comment]
Btw. if you're feeling "at it", there are these related issues/PRs :)

https://github.com/learningequality/kolibri/pull/3278
https://github.com/learningequality/kolibri/issues/3723

**Pull request merged**
