### PR TITLE
fix toolbar 1px black line flicking issue on Chrome

### PR DESCRIPTION
**Pull request by 66eli77**
can merge in case others also encounter this issue, currently I only observed on my machine

### CODE REVIEW

**Comment by 66eli77** [comment]
here's the explanation for this issue
http://stackoverflow.com/questions/9983520/webkit-animation-is-leaving-junk-pixels-behind-on-the-screen

**Comment by indirectlylit** [comment]
@66eli77 can you add a comment to the code indicating why that line was added? Otherwise someone may come along and delete it as cleanup.

**Comment by indirectlylit** [comment]
also, were the two deleted lines intentionally part of this PR?

```
 -    position: fixed
 -    left: -20px
```

**Comment by 66eli77** [comment]
good call! comment added.
refer to your later comment, these are just clean up redundant css rules

**Comment by indirectlylit** [comment]
thanks

**Pull request merged**
