### PR TITLE
Progress fetching url limiting

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
* We always fetched content node progress by content node ids
* This sometimes led to fetches having very long URIs
* This broke on some setups, due to limits on URI length
* Fixes this by:
   * Fetching content node progress for topic children by their parent id
   * Fetching content node progress for lesson resource by the lesson id
   * Only fetching content node progress for displayed content nodes in the recommended page
   * Batching requests for content node progress for recommended subpage to fetch 50 ids at a time

### Reviewer guidance

Check that progress loads in a lesson, in a topic, and on the main recommended page and on recommended subpages.

### References

I thought there was an issue for this, but I can't find it for the life of me.
----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jonboiser** [comment]
I think we've talked informally about this happening, but there's no specific issue about adding these filters. 

Maybe this issue is relevant? https://github.com/learningequality/kolibri/issues/5041

**Comment by rtibbles** [comment]
Yeah - that seems related. Not sure it will fix the vue dev tools part or not.

**Comment by indirectlylit** [comment]
Also possibly related - https://github.com/learningequality/kolibri/issues/6466#issuecomment-664593273

> I'm able to reproduce this issue by going to the Recommended tab on our main kolibri demo server. My guess is that the the request URL for `contentnodeprogress` endpoint is too long with the number of node ids.

**Comment by jonboiser** [comment]
I'm not seeing the progress bar on the Recommended Subpages cards, but the progress is coming over the wire

image

**Comment by jonboiser** [comment]
Devtools output for the "5+6" card on the main Recommended Page (with Progress = 1)

image

Output on the subpage (Progress = 0)
image

The Vuex mutation for setting progress is going through, but it must not be setting the Card props correctly at the end.

**Comment by rtibbles** [comment]
Hrm - curious, will look into this!

**Comment by jonboiser** [comment]
So, it seems that the state for the "Most popular" subpage is actually this `subpage` sub-module. And it's getting all the card info + progresses from `state.recommended.subpage.recommendations`, whereas the `created` hook is only updating the `state.recommended.popular` stuff. I think maybe we should just get rid of this `recommended/subpage` submodule and read directly from the main `recommended` module

image

**Comment by rtibbles** [comment]
Thanks - I'll make that alteration, seems like a decent cleanup.

**Comment by rtibbles** [comment]
Updated!

**Comment by jonboiser** [comment]
Looks good. I think these lines are now dead code if you can clean it up

https://github.com/rtibbles/kolibri/blob/58d41d5760ac4eb4f14716cccb990b2b2903f51d/kolibri/plugins/learn/assets/src/constants.js#L45-L48

**Comment by rtibbles** [comment]
Done!

**Review by jonboiser — APPROVED** [review]
Looks good!

**Pull request merged**
