### PR TITLE
Updates to the generateuserdata management command.

### PR DESCRIPTION
**Pull request by cpauya**
### Summary

**WIP!  Please don't merge!**

Some updates for the `generateuserdata` management command useful for integration testing.
* ARG: `device-name` - prepend this to the name of facilities, classes, groups, learners when created.  This is useful when testing P2P syncing of data.
* ARG: `max-channels` - limit to number of channels to create learner activity, instead of all which will take time
* ARG: `num-groups` - total groups to create for each class
* Example: 
    * `kolibri manage generateuserdata --no-onboarding --facilities 2 --device-name VM1`
    * See steps to test below.

List of arguments (only the last 3 are new): 
* `users`, default=20, Users per facility
* `classes`, default=2, Classes per facilities
* `facilities`, default=2, Number of facilities
* `no-onboarding`, Automatically create superusers and skip onboarding
* `num-content-items`, Number of content interactions per user, if not specified - will base on age of learner, the older the more interactions
* `num-lessons`, default=5, Number of lessons to be created per class
* `num-exams`, default=2, Number of exams to be created per class
* `max-channels`, default=2, Maximum number of channels to add activities to. NEW!
* `max-groups`, default=2, Number of groups to be created per class. NEW!
* `device-name`, Device name to use for this instance. If specified - this will be prefixed to the facilities, classes, and users to be created. NEW!

Example: `kolibri manage generateuserdata --no-onboarding --facilities 1 --classes 4 --users 20 --max-channels 1 --device-name VM1`

### ToDos:

- [x] Add help message when `kolibri manage generateuserdata --help` is used to show all arguments.
- [ ] Generate classes, groups, lessons, and learners without importing a channel first.
- [ ] Fix `num-groups` argument
- [ ] For generating learner activities, use channel token/s instead of just limiting the number of channels with `max-channels`
- [ ] Other notes at the [Notion Page for this task](https://www.notion.so/learningequality/Look-at-generateuserdata-if-can-be-modified-to-be-useful-for-integration-testing-0d5de37ed3d942b89f04e2f044608597)
    - [ ] Quizzes
    - [ ] Lessons
    - [ ] etc

### Reviewer guidance

To test, do the following:

#### Part 1 - Run `generateuserdata` command and test it's arguments and data generated:

1. Checkout this branch and follow the [instructions how to setup Kolibri for development](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#setting-up-kolibri-for-development).  Stop after installing Yarn, just before running Kolibri.
1. Optional: Delete the Sqlite3 database, make a backup if you still need it!  Run in terminal:
    * `rm ~/.kolibri/db.sqlite3`
    * repeat this step during devt and testing for a clean database
1. Test the command:
    * `kolibri manage generateuserdata --no-onboarding --facilities 2 --device-name VM1`
    * this will auto-run migrations if needed
    * variations, experiment with the arguments:
        *    `kolibri manage generateuserdata --facilities 1 users 40`
        *    `kolibri manage generateuserdata --facilities 1 --classes 4 users 20 --device-name VM1`
        *    `kolibri manage generateuserdata`

1. Run Kolibri
    * `yarn devserver`
1. Open http://0.0.0.0:8000/ in web browser
    * login as superuser/password
    * this super user account is auto-generated with the `--no-onboarding` argument
1. Navigate to the Facility, Coach, and Learners pages

#### Part 2 - Import a Channel and generate learner activities on the channel
The following imports content then re-runs the command to auto-create learner activities on the imported channel:
1. Import channel content using this token: `nakav-mafak` = Radina's Testing Channel
1. After importing channel content, stop Kolibri then run in Terminal: 
    * `kolibri manage generateuserdata --no-onboarding --facilities 2 --device-name VM1`
    * this will add activity data for the learners
1. You can import more channels to test the `max-channels` argument.  Then stop Kolibri and run in Terminal: 
    * `kolibri manage generateuserdata --no-onboarding --facilities 2 --device-name VM1 --max-channels 2`
        * this will add activity data for the learners up to 2 channels only
        * WARNING: This will take a long time, depends on how large the channel and the number of users. 
1. Start Kolibri again, run in Terminal: `yarn devserver`
1. Open http://0.0.0.0:8000/ in web browser and navigate to the Facility, Coach, Quizzes, Learners, Reports, and Activity pages.

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [x] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [x] Critical user journeys are covered by Gherkin stories
- [x] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by mrpau-richard** [comment]
i tested this on Windows 7. and it is working as expected. 
here's the sample screenshots:
Screen Shot 2020-06-05 at 12 35 41 AM
Screen Shot 2020-06-05 at 12 36 05 AM
Screen Shot 2020-06-05 at 12 51 56 AM


I think this errors is the caused why travis failed? 
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python34\lib\logging\__init__.py", line 980, in emit
    stream.write(msg)
  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 120-127:
 character maps to <undefined>
Call stack:
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\kolibri.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "C:\Python34\lib\site-packages\kolibri\dist\click\core.py", line 764, in
__call__
    return self.main(*args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\click\core.py", line 717, in
main
    rv = self.invoke(ctx)
  File "C:\Python34\lib\site-packages\kolibri\dist\click\core.py", line 1137, in
 invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python34\lib\site-packages\kolibri\utils\cli.py", line 244, in invoke

    return super(KolibriDjangoCommand, self).invoke(ctx)
  File "C:\Python34\lib\site-packages\kolibri\dist\click\core.py", line 956, in
invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python34\lib\site-packages\kolibri\dist\click\core.py", line 555, in
invoke
    return callback(*args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\click\decorators.py", line 17
, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\utils\cli.py", line 655, in manage

    execute_from_command_line(["kolibri manage"] + ctx.args)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\management\__init
__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\management\__init
__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\management\base.p
y", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\management\base.p
y", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Python34\lib\site-packages\kolibri\core\logger\management\commands\ge
nerateuserdata.py", line 188, in handle
    channel=channel, learner=user)
Message: '      ==> Adding Radina Testing Channel channel activity for learner "
VM3 \u042f\u0440\u043e\u0441\u043b\u0430\u0432\u0430 \u041a"@"VM3 Test Facility
2"...'
Arguments: ()
?[37mINFO         Learner "VM3 M Sigurd"@"VM3 Test Facility 2"...?[0m
?[37mINFO           ==> Adding Radina Testing Channel channel activity for learn
er "VM3 M Sigurd"@"VM3 Test Facility 2"...?[0m
?[37mINFO     Done.?[0m
```

**Comment by cpauya** [comment]
Good catch @mrpau-richard - I will check that out. Thanks for reviewing.

**Comment by cpauya** [comment]
@mrpau-richard May I know your testing setup?  I cannot reproduce this using these setup:

* Python v3.7.7
* 1 channel, Radina's Testing Channel
* Ran the following but no error:
    * `kolibri manage generateuserdata`
    * `kolibri manage generateuserdata --facilities 1 --classes 1 --users 40`

**Comment by cpauya** [comment]
Hi @jonboiser - I added you here just in case you have time to check it out for your P2P stuff. 😺

**Comment by radinamatic** [comment]
@cpauya Great start!

1. This should point out to `develop`, not `release-v0.13.x` branch

2. It was confusing to me seeing 2 classes in **Facility > Classes** and 4 in the **Coach**. Am I seeing 2 classes from both facilities? That can't be right...
    
    generate-classes

3. There are 2 classes in the **Coach** view that have the same name ``VM1 Classroom 2D``, but a different set of users.

4. Would it be possible to include the name of the facility in the name of the generated class? That might help in recognizing the origin of classes after importing the facility on another device, and ease the debugging process.

5. While we are at it, let's simplify and shorten the naming:
    * facility: ``FacilityXX`` (instead of ``Test Facility XX``)
    * class: `ClassXX` (instead of ``Classroom XX``)

**Comment by radinamatic** [comment]
I can replicate the issue of 2 classes in Facilities and 4 in Coach when I install on Windows 7:

generate-classes

I also see some errors in the Command prompt, and guessing Windows can't cope with properly encoding chars...? 🙄 

[W7-output-generateuserdata.txt](https://github.com/learningequality/kolibri/files/4749835/W7-output-generateuserdata.txt)

**Comment by cpauya** [comment]
Thanks for testing @radinamatic

Good catch re target to `develop` branch!  I tried to edit this PR but it's giving me a warning dialog, I don't wanna risk it.  I have to create another PR to point to `develop` branch.  I don't want to mess-around with merge conflicts. 😸 

Regarding the error, I think that's caused by the use of Python v3.4 for the Windows installer. It's a similar error on Buildkite as @mrpau-richard pointed-out above.  I've been using the Python v3.7 on my pipenv and didn't encounter it.  I will probably handle that exception or just remove that line if it's not important.

The 4 Classes you saw are the 2 classes for each of the 2 facilities, which the current user can coach.  So yes, we can prepend the facility name when we create the classes for easy identification - good idea! Thanks! 😸 

Will close this and resume work on the new PR targeting `develop` branch.

**Comment by radinamatic** [comment]
Gotcha, I can totally understand the strategy of opening a new PR to escape merge conflicts!
It's comforting to know even more seasoned developers resort to that strategy, I don't feel so alone :blush: 

> The 4 Classes you saw are the 2 classes for each of the 2 facilities, which the current user can coach. 

But does it makes sense to see ALL the classes someone can coach in the same view, which is supposed to be limited to ONE facility? At least that's what I understood: when a user signs in one facility, they should be able to view only the information (like classes they can coach) for that particular facility...?
cc @indirectlylit @jtamiace @khangmach

**Comment by cpauya** [comment]
I agree that it's a bug, we should see only 2 classes in the logged-in facility.  But I will let the others chime-in.  And I think it merits another issue of it's own. 😸

**Comment by cpauya** [comment]
Just an FYI @radinamatic that the "list of classes" bug applies to the `release-v0.13.x` branch only.  It's filtered by facility on the `develop` branch.  I hope to create a PR for this soon.

2020-06-09-tue--facility-classes-on-develop-branch

**Comment by cpauya** [comment]
Wrong target branch, closing this in favor of https://github.com/learningequality/kolibri/pull/7013

**Pull request closed without merging**
