### PR TITLE
Use separate engine and client for iceqube.

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
This is dependent on changes in iceqube, here: https://github.com/learningequality/iceqube/pull/39

It separates the aspects of iceqube that run the workers, and the client for scheduling jobs, and carries that distinction into Kolibri.

### Reviewer guidance
Does it fix the uwsgi errors?

### References
Fixes...

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by indirectlylit** [comment]
switching base to `develop`

**Comment by rtibbles** [comment]
This has now been updated based on latest changes in https://github.com/learningequality/iceqube/pull/39, but still needs the release of a new iceqube.

**Review by jredrejo — CHANGES_REQUESTED** [review]
I have been testing this changes, trying to add & delete channels.
* adding worked perfectly
* delete raised often this error
```WARNING 2019-05-02 10:01:56,105 utils Got an exception running <bound method Worker.check_jobs of <iceqube.worker.Worker object at 0x7fba3ecca7f0>>: No module named 'iceqube.common' ```
but it worked. I haven't been able to find any reference to iceqube.common, but after doing `make clean` and removing all the *.pyc files it still happened with channels that had been added before the new iceqube version was installed. I can't think of a reason for that, but it did disappear when deleting channels that had been added with the new iceqube version.

* cancel does not work, it always raises this error:
```
ERROR 2019-05-02 12:51:05,967 exception Internal Server Error: /api/tasks/tasks/canceltask/
Traceback (most recent call last):
  File "/datos/le/mio/kolibri/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/datos/le/mio/kolibri/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/datos/le/mio/kolibri/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/datos/le/mio/kolibri/kolibri/dist/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/datos/le/mio/kolibri/kolibri/dist/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/datos/le/mio/kolibri/kolibri/dist/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/datos/le/mio/kolibri/kolibri/dist/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/datos/le/mio/kolibri/kolibri/dist/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/datos/le/mio/kolibri/kolibri/core/tasks/api.py", line 300, in canceltask
    get_queue().cancel(request.data["task_id"])
  File "/datos/le/mio/kolibri/kolibri/dist/iceqube/queue.py", line 75, in cancel
    self.storage.mark_job_as_canceling(job_id)
  File "/datos/le/mio/kolibri/kolibri/dist/iceqube/storage.py", line 133, in mark_job_as_canceling
    self._update_job(job_id, State.CANCELING)
  File "/datos/le/mio/kolibri/kolibri/dist/iceqube/storage.py", line 222, in _update_job
    job, orm_job = self._get_job_and_orm_job(job_id, session)
  File "/datos/le/mio/kolibri/kolibri/dist/iceqube/storage.py", line 244, in _get_job_and_orm_job
    raise JobNotFound()
iceqube.exceptions.JobNotFound
```
The frontend request was fine, as the task id was in the database:
task

captura2

**Comment by rtibbles** [comment]
Yeah, having real difficulty understanding how `iceqube.common` references would persist in channel data between iceqube upgrades. The only thing that could hold a reference to that might be the iceqube DB storage, if it had some sort of pickled reference, but the DB representations of those jobs should have been deleted already.

**Comment by rtibbles** [comment]
Following up on the cancellation error you are seeing here.

**Comment by rtibbles** [comment]
OK, replicated the JobNotFound error, but only in cases where the job managed to finish itself before the cancellation request got processed (relatively simple to do on the devserver, where the single threading makes the task endpoints very slow to respond).

I was also able to cancel jobs that were longer running, and hence did not complete before the canceltask request occurred.

**Review by jredrejo — APPROVED** [review]

**Comment by jredrejo** [comment]
> I was also able to cancel jobs that were longer running, and hence did not complete before the canceltask request occurred.

This was the case that was not working for me. After you last commits it works fine now. Now I can cancel loading content from a channel.

**Comment by rtibbles** [comment]
Great, will release a new version of iceqube, update this, PR, and we'll be ready to go!

**Pull request merged**
