### PR TITLE
Fix upgrade startup errors

### LINKED ISSUE #8781: Cannot start Kolibri after upgrading Kolibri 0.14.7 to Kolibri 0.15.0 beta2
## Observed behavior
I'm getting a database error when I attempt to start Kolibri after an upgrade from the 0.14.7 version to 0.15.0 beta2

## Expected behavior
It should be possible to upgrade the 0.14 version of Kolibri to the 0.15 version

## Steps to reproduce the issue
1. Install the a 0.14.7 version of Kolibri from [here](https://learningequality.org/r/kolibri-windows-setup-latest).
2. Setup a facility, create classes, users, lesson etc and perform some user interactions such as completing a lesson or a quiz.
3. Upgrade to the 0.15 version by Installing the following [build.](https://github.com/learningequality/kolibri/releases/tag/v0.15.0-beta2).
4. Attempt to start the Kolibri server.

## Additional information

Console info when I execute the `kolibri start --foreground` command in Ubuntu:

```
le@osboxes:~$ kolibri start --foreground
INFO     Option DEBUG in section [Server] being overridden by environment variable KOLIBRI_DEBUG
INFO     Option DEBUG_LOG_DATABASE in section [Server] being overridden by environment variable KOLIBRI_DEBUG_LOG_DATABASE
/usr/lib/python3/dist-packages/kolibri/dist/rest_framework/utils/serializer_helpers.py:107: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if value is None or value is '':
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO     Backed up database to: /home/le/.kolibri/backups/db-v0.14.7_2021-11-25_16-17-29.dump
INFO     Version was 0.14.7, new version: 0.15.0b2
INFO     Running update routines for new version...
Operations to perform:
  Apply all migrations: admin, analytics, auth, bookmarks, content, contenttypes, device, discovery, exams, kolibriauth, lessons, logger, morango, notifications, sessions
Running migrations:
  No migrations to apply.
Operations to perform:
  Apply all migrations: admin, analytics, auth, bookmarks, content, contenttypes, device, discovery, exams, kolibriauth, lessons, logger, morango, notifications, sessions
Running migrations:
  No migrations to apply.
Operations to perform:
  Apply all migrations: admin, analytics, auth, bookmarks, content, contenttypes, device, discovery, exams, kolibriauth, lessons, logger, morango, notifications, sessions
Running migrations:
  No migrations to apply.
Operations to perform:
  Apply all migrations: admin, analytics, auth, bookmarks, content, contenttypes, device, discovery, exams, kolibriauth, lessons, logger, morango, notifications, sessions
Running migrations:
  No migrations to apply.
Installed 2 object(s) from 1 fixture(s)
Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/utils/cli.py", line 193, in invoke
    initialize(**get_initialize_params())
  File "/usr/lib/python3/dist-packages/kolibri/utils/main.py", line 268, in initialize
    update(version, kolibri.__version__)
  File "/usr/lib/python3/dist-packages/kolibri/utils/main.py", line 326, in update
    run_upgrades(old_version, new_version)
  File "/usr/lib/python3/dist-packages/kolibri/core/upgrade.py", line 156, in run_upgrades
    version_upgrade()
  File "/usr/lib/python3/dist-packages/kolibri/core/upgrade.py", line 51, in __call__
    return self.upgrade()
  File "/usr/lib/python3/dist-packages/kolibri/core/content/upgrade.py", line 306, in metadata_annotation_update
    get_all_contentnode_label_metadata()
  File "/usr/lib/python3/dist-packages/kolibri/core/content/utils/search.py", line 122, in get_all_contentnode_label_metadata
    return get_available_metadata_labels(
  File "/usr/lib/python3/dist-packages/kolibri/core/content/utils/search.py", line 86, in get_available_metadata_labels
    content_cache_key = ContentCacheKey.get_cache_key()
  File "/usr/lib/python3/dist-packages/kolibri/core/device/models.py", line 159, in get_cache_key
    cache.set(CONTENT_CACHE_KEY_CACHE_KEY, key, 5000)
  File "/usr/lib/python3/dist-packages/kolibri/dist/diskcache/djangocache.py", line 147, in set
    return self._cache.set(key, value, timeout, read, tag, retry)
  File "/usr/lib/python3/dist-packages/kolibri/dist/diskcache/fanout.py", line 97, in set
    return shard.set(key, value, expire, read, tag, retry)
  File "/usr/lib/python3/dist-packages/kolibri/dist/diskcache/core.py", line 836, in set
    self._row_update(rowid, now, columns)
  File "/usr/lib/python3/dist-packages/kolibri/dist/diskcache/core.py", line 860, in _row_update
    sql('UPDATE Cache SET'
sqlite3.DatabaseError: database disk image is malformed
```

Complete Windows 10 and Ubuntu folders with DBs and logs: https://drive.google.com/drive/folders/1ZWYLxZ24lghoBfYbyCU1b71YaMw5eJub?usp=sharing

## Usage Details
 - OS: Windows 10, Ubuntu 20
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Moves disk cache integrity check to before any upgrades are run, ensures that it catches all fanout shards by using full Django cache
* Adds scheduler storage table recreation to upgrade task

## References
Fixes #8781 - fixes both errors reported therein, which are reproducible with the zip file.

## Reviewer guidance
Does running with the kolibri home dir in the issue upgrade without any issues?

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
Hi @rtibbles I tested the upgrade scenario from Kolibri 0.14.7 to 0.15 on both Windows (real device) and Ubuntu (VM) and I am able to upgrade without any of the previously observed issues.
On both Windows and Ubuntu I have a fully setup facility with users who have completed lessons/quizzes.
I noticed that if I as a Coach go to the reports immediately after the upgrade and attempt to go through the completed lessons or quizzes I'm not able to see the actual questions, instead I see: No attempts made on this question:



This gets fixed for the quiz report if I restart Kolibri but it remains broken for the lesson reports.

Here are the logs and DB files: 
[UbuntuDBlogs.zip](https://github.com/learningequality/kolibri/files/7669547/UbuntuDBlogs.zip)
[WindowsDBLogs.zip](https://github.com/learningequality/kolibri/files/7669548/WindowsDBLogs.zip)

Sharing this info here for context - I can open a follow-up issue?

**Comment by rtibbles** [comment]
Yes, please open a follow up issue!

**Review by radinamatic — APPROVED** [review]
Upgrade looks much better, one follow-up issue to be opened. 👍🏽

**Review by jredrejo — APPROVED** [review]
From a code point of view I can't see any problem, it looks good.
From an user point of view: testing it, this is the cleanest upgrade I've seen since we began to test 0.15.x !

**Pull request merged**
