### PR TITLE
Nishant

### PR DESCRIPTION
**Pull request by shrinishant**
## Summary

I removed the min-height css property of mobile-card in HybridLearningContentCardListView.vue so that the extra void space could be removed between resource description and bookmarked status.

I manually verified the results in the inspection mode for upto 320 px width screens and also for iPhone SE device. I also ran yarn run test to test for the frontend before creating this PR.

Before :

Screenshot from 2023-03-04 11-37-55

After : 

Screenshot from 2023-03-05 23-39-07

## References

#9058 

## Reviewer guidance

…

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by MisRob** [comment]
Hello @shrinishant, thank you for your contribution. Before I proceed to the review, I'd like to ask you to have your PR branch based on the latest `develop` branch so that your PR will only contain your change (it's a huge diff right now with many unrelated files and commits).

**Comment by shrinishant** [comment]
> Hello @shrinishant, thank you for your contribution. Before I proceed to the review, I'd like to ask you to have your PR branch based on the latest `develop` branch so that your PR will only contain your change (it's a huge diff right now with many unrelated files and commits).

Sir, I was going through the develop branch and found that it's way too different from the release-v0.15.x branch. I mean the components are different in the branches. I figured them out and would soon have the required PR. 

Need your guidance, could u please answer this?

1. Should i close the PR based on v0.15.x branch and create a fresh new PR based on develop branch, or commit in the previous branch?

2. And which branch should i continue to work and explore upon for further development? because the getting started docs, it has been mentioned to start with v0.15.x branch

**Comment by MisRob** [comment]
Hello @shrinishant, please target the `develop` branch. For that, I think it'd be easiest to create a fresh PR, yes.

Regarding documentation, I think we only advise checking out the `release-v0.15.x` branch temporarily only to do facility setup on it because the setup flow is broken on `develop`. After you have your facility setup done, please checkout back to the `develop` branch and start working from there. I know it's a bit confusing, and am sorry to hear that it caused you trouble. We're working on a new release that will allow us to remove the need to checkout to v15 to do the setup.

**Comment by shrinishant** [comment]
@MisRob created a new #10217 (PR) regarding this issue. Please review this

**Comment by MisRob** [comment]
Thanks @shrinishant, I'm closing this one then

**Pull request closed without merging**
