### PR TITLE
Update to nodejs 18.

### LINKED ISSUE #10636: Update node.js requirement to NodeJS 18
## Observed behavior
NodeJS 16 EOL is 2023-09-11 (see https://github.com/nodejs/release#release-schedule).

We should upgrade to NodeJS 18 well before that happens, so that we can spin it out to all projects dependent on kolibri-tools.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Does the minimal upgrade for NodeJS 18

## References
Fixes #10636

## Reviewer guidance
Does CI all pass? Are there any extant references to Node 16?

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jredrejo** [comment]
This is an important change for the 0.16 release. If aproved it will allow upgrading several libraries in KDP, but testing it will require time, so the sooner we decide it , the better

**Comment by rtibbles** [comment]
Noting that the main reason I targeted this for 0.16.x is because last time that we did a NodeJS upgrade in develop (but not in the main release branch, 0.15.x at the time) it caused a massive pain for all concerned with having to switch between multiple node versions.

**Comment by radinamatic** [comment]
> This is an important change for the 0.16 release. If aproved it will allow upgrading several libraries in KDP, but testing it will require time, so the sooner we decide it , the better

Does this testing refer to manual QA on Kolibri or KDP? Any pointers what to look for in case of the former? Thank you!

**Comment by rtibbles** [comment]
No - this would only be testing the integration of the NodeJS upgrade to ensure it doesn't break building on KDP.

**Review by marcellamaki — APPROVED** [review]
- [x] Searched for references to node 16, none found
- [x] smoke tested devserver in new node18 virtual env 
- [x] smoke tested PR pex

All checks out, and CI passes

**Pull request merged**
