### PR TITLE
Faster null import

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Uses values call to get all files to download instead of instantiating as models 3-4 x speed up (which should also improve performance for all imports)
* Gives a much earlier and simpler trapdoor for content import when remote content storage is being used
* Should give approximately 4-5x speedup overall for remote storage content import

## Reviewer guidance
Does content import and upgrade still work as expected?
Is it faster for remote storage import?

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
I tested the asset from 2 commits in this build on Windows 10, and I see no issues with importing, but I'm not really noticing  speed improvements either. It takes 5 minutes to download 1GB of content from KA Spanish channel on Studio. Throttling to 4G is just slightly slower, so not sure if the FF is just not too precise with those figures.

Or maybe the speed increase is noticeable just for higher volume imports...? 🤔

**Comment by rtibbles** [comment]
> Or maybe the speed increase is noticeable just for higher volume imports...? thinking

This may not have a noticeable increase in import speed when you are actually downloading content - but it should reduce the time that a task spends at 0% before file downloads even begin.

Probably only really noticeable on a very big channel like KA - where the download task will probably churn on 0% for quite some time.

When running it on a hosted Kolibri instance where we are not actually downloading the content, it should be a significant speed improvement.

**Comment by radinamatic** [comment]
When I select the full KA EN US channel (54GB), it has been sitting for 6 minutes now like this, not even showing 0%... 😕 

Win10 (start)  Running  - Oracle VM VirtualBox_027

**Comment by rtibbles** [comment]
Is that better or worse than before?

**Comment by aronasorman** [comment]
@rtibbles I can test on a BCK instance either tomorrow or Monday!

**Comment by radinamatic** [comment]
I honestly don't remember how long it took before on the full KA EN channel 😞

**Comment by radinamatic** [comment]
It took about 8 minutes for 0% to appear and see something in the progress bar.
Process was also heavy on the VM resources (and it was not particularly _constrained_: 2 cores and 8MB RAM) - although that might be normal.

I cancelled the import task at 2% progress of downloaded resources, but the channel is not appearing neither in Device > Channels, nor in Learn > Channels.

1 | 2 | 3
--- | --- | ---
Workspace 1_002 | Win10 (start)  Running  - Oracle VM VirtualBox_030 | Win10 (start)  Running  - Oracle VM VirtualBox_031

[logs.zip](https://github.com/learningequality/kolibri/files/7139558/logs.zip)

**Comment by rtibbles** [comment]
Yep, cancellation cancels the import process, it doesn't leave it part way done.

**Comment by radinamatic** [comment]
Not even if there are 2 GB of resources locally? 😳

**Comment by rtibbles** [comment]
Oh, I appear to be wrong - it should be annotating after cancellation.

**Review by bjester — APPROVED** [review]
Testers did not uncover regressions, looks good

**Pull request merged**
