### PR TITLE
Don't pass notifications in summarizedNotifications

### PR DESCRIPTION
**Pull request by nucleogenesis**
### Summary

Addresses a regression from https://github.com/learningequality/kolibri/pull/5595 that caused "QuizAnswered" events to show in the Coach ActivityBlock. There is no need to show those notifications - a class of students taking a quiz would flood the summarized notifications for the coach to review.

This is also noted in https://github.com/learningequality/kolibri/issues/5921 - which is an unrelated issue, but the issue was originally noted there in this comment: https://github.com/learningequality/kolibri/issues/5921#issuecomment-528895111

### Reviewer guidance

- Create a quiz for a class of students as a coach and assign it to the class, enable it, etc.
- View the Coach > Reports > Quiz Report for that quiz
- In a Private Browsing / Incognito window, sign in as one of the learners assigned to the quiz
- Answer a few questions. As a coach, note that that learner's status for the quiz goes to `x of y answered`
- After answering a few of them - go to the Class overview page. See that you see none of what is shown in this image: https://github.com/learningequality/kolibri/issues/5921#issuecomment-528895111
- Complete the quiz then you ought to see the proper "Learner completed quiz" notification. You should also see the "Learner started quiz" and other normal notifications.

### References

https://github.com/learningequality/kolibri/issues/5921#issuecomment-528895111
https://github.com/learningequality/kolibri/pull/5595

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [x] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by radinamatic — APPROVED** [review]
Found no superfluous notifications in class activity, LGTM! 👍

**Comment by jonboiser** [comment]
@radinamatic 	If you still have access to this branch, could you check if the notifications appear in the full activity feed (click "View all" next to "Class activity")? I have a feeling they might still be there.

If so, we'll need to filter them out in ActivityList.vue as well.

**Comment by radinamatic** [comment]
And @jonboiser scores again: slew of notifications on `home/activity`, and a lot of `Vue warns` in the console.

**Comment by jonboiser** [comment]
:oh-no:! We'll need to put a similar skip-exam-answered notifications thing in this component.

**Pull request merged**
