### PR TITLE
Linting: As you like it

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
* Empower developers to make their own choices in how they lint their code!
* Adds linting configs to the base of the repo for all the linting tools we use.
* Adds `devserver-warn` and `devserver-hot-warn` to allow the devserver commands to be run with a linter in warn only mode.
* Updates getting started docs to emphasise that the goal is to commit code linted to our standards, and providing different options and tools to achieve that goal.

### Reviewer guidance
Try out your preferred work flow, does it blend?

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by kollivier — APPROVED** [review]
In the immortal words of @micahscopes: wooooooooo! :) Thanks for this!

**Comment by indirectlylit** [comment]
wasn't quite ready for merge - will need a bit more follow-up to clean up some pre-commit references:

* https://github.com/learningequality/kolibri/blob/develop/.pre-commit-config.yaml
* https://github.com/learningequality/kolibri/blob/develop/docs/frontend_architecture/conventions.rst
* https://github.com/learningequality/kolibri/blob/develop/docs/getting_started.rst
* https://github.com/learningequality/kolibri/blob/develop/docs/stack.rst
* https://github.com/learningequality/kolibri/blob/develop/requirements/dev.txt

**Comment by indirectlylit** [comment]
If folks on this thread could test locally and leave feedback that'd be great. We can address any outstanding issues in a follow-up PR

**Comment by bjester** [comment]
I'll give the updates a shot, and I can update the docs too unless someone is working on that.

**Pull request merged**
