### PR TITLE
fix: os_user unnecessary password field

### LINKED ISSUE #11777: On os_user sign-in, unnecessary password field can temporarily appear
## Observed behavior
There are two possible sign in flows - one is the regular username and password flow, and one is where the operating system user is used to create a Kolibri account within setup. 

If multiple accounts are created on the same device and kolibri installation, with different setup options, there is a scenario where a user signing in using the operating system user can briefly see a password field which is not required for them to sign in. This is a frontend state management/loading state issue (~1 second of intermediate state), and the sign in works as expected following https://github.com/learningequality/kolibri/pull/11754

## Errors and logs

https://github.com/learningequality/kolibri/assets/17235236/dfd36144-974f-48a3-a9b3-65ed220f6b56

## Expected behavior
For an optimal user experience, this would be properly managed in the front end, and the `os_user` workflow would not see the password field.

## User-facing consequences
Users may think they need to enter a password, or try to enter one, which could result in confusion or further errors. 

## Steps to reproduce
1. Running Kolibri locally *[*not** in app_mode](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#running-in-app-mode), create a user with a password (let's call this "pw_user")
2. Stop your Kolibri server, but maintain the same `KOLIBRI_HOME` folder
3. Run Kolibri locally using (https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#running-in-app-mode). (let's call this "os_user")
4. Sign out. You should now see both "pw_user" and "os_user" available to select in the sign in page
7. Select "pw_user". You should be directed to the next step, where you enter your password. Do not sign in. Go back via "Change User"
8. Select "os_user". You should briefly see the password field appear (the same as before) but then be properly logged in and redirected into Kolibri after ~1 second, without needing to enter a password.

## Context
0.16.x
Mac ventura 13

### PR DESCRIPTION
**Pull request by ThEditor**
## Summary

Resets `usernameSubmittedWithoutPassword` back to `false` on `clearUser` (executed when user goes back using "Change User")

## References

Closes #11777 

## Reviewer guidance

1. Running Kolibri locally [not in app_mode], create a user with a password (let's call this "pw_user")
2. Stop your Kolibri server, but maintain the same KOLIBRI_HOME folder
    Run Kolibri locally using (https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#running-in-app-mode). (let's call this "os_user")
2. Sign out. You should now see both "pw_user" and "os_user" available to select in the sign in page
    Select "pw_user". You should be directed to the next step, where you enter your password. Do not sign in. Go back via "Change User"
3. Select "os_user". **You should not see any password field show up and sign-in should happen automatically.**
----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by ThEditor** [comment]
@marcellamaki any updates on it?

**Comment by MisRob** [comment]
Hi @ThEditor, thanks for the contribution! We have a queue of pull requests. Generally, a review may take up to two weeks.

**Review by marcellamaki — APPROVED** [review]
Hi @ThEditor - I apologize for the delay in following up on this PR. The code changes look good and I've done manual QA to confirm. Thank you for your contribution here!

**Comment by ThEditor** [comment]
Its fine, no worries. Thanks for approving the PR. :D

**Comment by marcellamaki** [comment]
I'm just rerunning the Python checks, and if it sorts itself out, this will be good to merge, and I'll do that later today :)

**Review by rtibbles — DISMISSED** [review]
No need to change the code here, but flagging that the issue this is fixing is targeted for Planned Patch 1 - this means that this PR should be targeted at the release-v0.16.x branch, not develop!

For details on how to do a rebase from one to another, please see here: https://kolibri-dev.readthedocs.io/en/develop/howtos/rebasing_a_pull_request.html

Note, I have retarged the pull request already, so you just need to do the rebase and force push to update the PR branch.

**Comment by ThEditor** [comment]
I've rebased the PR, does it look correct?

**Comment by radinamatic** [comment]
From the manual QA point of view we're struggling to find the real-world scenario this PR is supposed to fix... Is it only replicable in the dev environment, or there is some angle we're missing when using built assets?

**Comment by pcenov** [comment]
Thanks @ThEditor - I confirm that the issue described in https://github.com/learningequality/kolibri/issues/11777 is now fixed. cc @marcellamaki

**Review by radinamatic — APPROVED** [review]
Manual QA passed, good to go! 💯 🚀 :shipit:

**Review by marcellamaki — APPROVED** [review]
Thank you for retargeting this PR @ThEditor and for your patience!

**Pull request merged**
