### PR TITLE
Merge 0.12.x into develop

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
Conflicts all arose from branding updates - just resolved them in favour of develop as that seemed correct.

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
merging in favor of https://github.com/learningequality/kolibri/pull/6045

**Review by indirectlylit — DISMISSED** [review]

**Review by indirectlylit — CHANGES_REQUESTED** [review]
actually I think there were some changes necessary - see my resolution here: https://github.com/learningequality/kolibri/pull/6045/files

**Comment by indirectlylit** [comment]
should prob have @ralphiee22 take a look

**Comment by ralphiee22** [comment]
right, there are those missing changes from learningequality/kolibri/pull/6045/files which should be in this PR. I see them in the commits but not in the files changed.

**Comment by indirectlylit** [comment]
closing in favor of #6045 :)

**Comment by indirectlylit** [comment]
@ralphiee22 would you mind reviewing that one

**Pull request closed without merging**
