### PR TITLE
Makes core modal more responsive

### PR DESCRIPTION
**Pull request by christianmemije**
# Details

### Summary
Makes `core-modal` more responsive.
Before

localhost_8000_user_ 7

After

localhost_8000_user_ 6

### Reviewer guidance

Open a modal in a small viewport.

### References

N/A

# Contributor Checklist

- [x] PR has the correct target milestone
- [x] PR has the appropriate labels
- [x] Changes in the PR do not introduce accessibility regressions ([confimed by testing with one of the recommended tools](http://kolibri.readthedocs.io/en/develop/dev/manual_testing.html#accessibility-a11y-testing)) 
- [x] If PR is ready for review, it has been assigned or requests review from someone
- [x] ~Documentation is updated as necessary~ Not necessary 
- [x] ~External dependency files are updated (`yarn` and `pip`)~ N/A
- [x] ~If internal dependency is updated, link to diff is included~ N/A
- [x] Screenshots of any front-end changes are in the PR description
- [x] ~CHANGELOG.rst is updated for high-level changes~ Not necessary  
- [x] ~You've added yourself to AUTHORS.rst if you're not there~ Not necessary

# Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] PR has been fully tested manually

### CODE REVIEW

**Comment by DXCanas** [comment]
This supposed to go to `0.6`? Or `develop`?

**Comment by indirectlylit** [comment]
0.6 is correct for responsive issues because that's for VF

**Comment by indirectlylit** [comment]
any benefit to making this change for all modals - mobile or otherwise?

image

**Comment by DXCanas** [comment]
^ Squat displays? Is this preferable
localhost_8000_management_facility
?

**Comment by indirectlylit** [comment]
looks marginally better in my opinion. (pun intended)

**Comment by christianmemije** [comment]
I can just make the max-width & max-height for `.modal` a certain value, like 90%. And just keep `width: 85%` for `.modal.mobile` Although I am not too sure of the value of having a set width on mobile.

**Comment by christianmemije** [comment]
localhost_8000_coach_
localhost_8000_coach_ ipad pro

**Comment by indirectlylit** [comment]
LGTM

**Comment by khangmach** [comment]
looks like a marginal improvement. Previous iteration looked a bit broken. +1 to doing this for all modals

**Pull request merged**
