### PR TITLE
Bug/soud cannot edit profile

### LINKED ISSUE #8849: User on SouD should not be able to edit their user profile
From @jamalex in bug bash: 
The FacilityUser object is read-only for single-user certificates, so these changes will not be synced back. We had a spec doc that laid out "what should be allowed on a SoUD", I think this was documented in there — we should do an audit to make sure other cases are covered as well.

https://www.notion.so/learningequality/CRITICAL-FEATURE-BUG-Users-on-SoUD-should-not-be-allowed-to-edit-their-user-profile-e5765979e7ed4fcaa694cfe7932ac4df

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Summary

Users shouldn't be able to edit their profile on SoUD this ensures:
- The "Edit" button is not present on the Profile page when on SoUD
- The Profile Edit page altogether is inaccessible by direct URL to be extra safe

Per @jamalex 's suggestion - if I can get my hands on the SoUD specs doc I'll do an audit to be sure things that aren't allowed aren't allowed.

## References

Fixes #8849  

## Reviewer guidance

Go into your database and in the `device_devicesettings` table make your `subset_of_users_device` setting is true.

Log in - try to edit your profile. Go to the profile and add "edit" to the URL and you should be redirected to your user's "home" - a super admin goes to device and a learner goes to learn, for example. A coach... probably to coach? In any case - this would only happen in the exact case you're testing (going directly to the URL) so it's an edge case altogether. 

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
> if I can get my hands on the SoUD specs doc I'll do an audit to be sure things that aren't allowed aren't allowed.


See the table here:

https://www.notion.so/learningequality/Support-for-individual-user-syncing-and-S2S-RCT-73b84ed2d3df4899b5d0441126b96850#ae1a93e1daac440a9bd9d645e8a6e780

Reproduced below:

image

**Comment by radinamatic** [comment]
Looking good! 👍🏽 

* No `Edit` button on the Profile page in the Android app, while it's still there when the same learner signs in from the browser
* Direct `/profile/#/edit` URL redirects to Learn page (although I could do it in the Chrome dev tools while debugging via USB, no idea how would a user do that on the device itself)

Selection_025

**Review by radinamatic — APPROVED** [review]
LGTM! 👍🏽

**Review by rtibbles — APPROVED** [review]

**Comment by rtibbles** [comment]
Can do any audit fixes in follow up!

**Pull request merged**
