### PR TITLE
Kill the "download" button on error page

### LINKED ISSUE #4315: line endings in downloaded errors are not windows-compatible
### Observed behavior

reported in https://github.com/learningequality/kolibri/pull/4232#issuecomment-422985685

> when user downloads the text file and opens it in Notepad on Windows, it seems to be missing the hard end-of-the-line, which makes the items difficult to distinguish. Opening in Notepad++ or pasting from clipboard does not have this issue.

### Expected behavior

We should either make its so that line endings work on all operating systems, or if that's too hard,  remove the 'download' option

### User-facing consequences

users on Windows will have trouble using this feature

### Context

0.11

### PR DESCRIPTION
**Pull request by DXCanas**
Resolves #4315

### Summary

Trying to use Blob constructor features to make sure the text file uses the proper line endings. 

If this doesn't work, it's going to have to be regex.

### Reviewer guidance

1. Be on windows
1. Cause error
1. Open error report modal
2. download file
3. Open in notepad

### References

- #4315
----

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by DXCanas** [comment]
On Windows 10.0.14393:

Blob download from Firefox:
error file in notepad

However, didn't work from Edge or IE:
edge screenshot

@indirectlylit Gonna try out regex for now. Will post updates here.

**Comment by indirectlylit** [comment]
Okay. I don't think the download function is critical, so if this looks like a rabbit hole feel free to just remove it

**Comment by DXCanas** [comment]
@indirectlylit Killed the download button. It seemed like, even if I manually went in and tried to replace `\n` with `\r\n`, files would be downloaded with regular newlines. 

@radinamatic Do you think removing the button is a bad move?

**Comment by DXCanas** [comment]
Alternatively, I could just do a userAgent check and hide it if using IE/Edge? The `native` option worked fine on Firefox and Chrome! @indirectlylit

**Comment by indirectlylit** [comment]
In my opinion, the 'download' functionality is 'nice to have' and not required. I don't think it's worth spending more time on

@jtamiace @khangmach feel free to weigh in

**Comment by khangmach** [comment]
Yeah the download option is purely a formatting convenience. Ok to remove if this is bogging you down.

**Review by indirectlylit — APPROVED** [review]
killed it dead

**Pull request merged**
