### PR TITLE
focus and hover updates

### LINKED ISSUE #5884: Focused buttons, links, etc. do not have an outline
### Observed behavior

In keyboard modality, focused buttons, links, and form elements, do not have an outline (light green in default theme)

### Expected behavior
In keyboard modality, focused buttons, links, and form elements, have an outline (light green in default theme)

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

Kolibri develop

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

Mainly, fixes #5884, which was a regression in #5847

Also, makes some changes to the side nav styling and code:

* remove unused `divider` and `disabled` attributes
* remove unused `/deep/` styling
* remove use of `display: flex`
* remove unused `hover` reference
* simplify computed styles
* add hover state for active tabs
* add keyboard focus outlines
* add background color transition

| before | after |
|--|--|
| before|after |

### Reviewer guidance

Deleted a fair amount of code so make sure I didn't break anything.

### References

#5884

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by nucleogenesis** [comment]
Here is a couple of things that I found while walking the site with the keyboard.

- `BlockItem` components (eg, Coach > Class Home > Quizzes and Lessons lists) don't have any keyboard outline style. 

- The keyboard focus indicator skips "Change language" in the user profile menu.

**Review by nucleogenesis — APPROVED** [review]
Looks great to me. Not sure why Travis / tox is talking about reformatting py files but everything here looks much cleaner and works well. 

I noted a couple of items in a  comment above - but they may not be related to this PR.

**Review by khangmach — APPROVED** [review]

**Comment by jonboiser** [comment]
tox.ini's config for 'pythonblack' is installing the latest version of `black`, which seems to differ from the version we're used to using in the `black-fmt` package. Should probably either upgrade whatever is in `black-fmt` or update tox.ini.

**Comment by indirectlylit** [comment]
thanks all 

@nucleogenesis opened a new issue for the items you mentioned. They were unrelated to this PR

**Comment by bjester** [comment]
> thanks all
> 
> @nucleogenesis opened a new issue for the items you mentioned. They were unrelated to this PR

Ah just saw this... I created a new PR on top of this. Feel free to ignore then

**Pull request merged**
