### PR TITLE
Bump ifcfg, adds ip detection support for MacOS, restores for Ubuntu 17.10+

### PR DESCRIPTION
**Pull request by benjaoming**
### Summary

Bump ifcfg, adds ip detection support for MacOS, restores for Ubuntu 17.10+

Old result:

image

New result:

image

### Reviewer guidance

We're bumping ifcfg twice here.

https://github.com/ftao/python-ifcfg/compare/releases/0.15...releases/0.17

### References

n/a never opened an issue about this

----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If there are any front-end changes, before/after screenshots are included
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by benjaoming** [comment]
Trying again because of CI fail in #3994

**Comment by indirectlylit** [comment]
Don't think that was the issue - the [output](https://buildkite.com/learningequality/kolibri/builds/7153#f5ae6023-ce3a-473f-bf34-50f88d5426df) is:

```
make[1]: Entering directory '/kolibri'
# This expression checks that everything in kolibri/dist has an __init__.py
# To prevent namespaced packages from suddenly showing up
# https://github.com/learningequality/kolibri/pull/2972
! find kolibri/dist -mindepth 1 -maxdepth 1 -type d -not -name __pycache__ -not -name cext -not -name py2only -exec ls {}/__init__.py \; 2>&1 | grep  "No such file"
ls: cannot access 'kolibri/dist/jaraco/__init__.py': No such file or directory
make[1]: *** [test-namespaced-packages] Error 1
Makefile:119: recipe for target 'test-namespaced-packages' failed
make[1]: Leaving directory '/kolibri'
Makefile:125: recipe for target 'staticdeps' failed
make: *** [staticdeps] Error 2
make: *** [dockerenvdist] Error 2
```

**Comment by indirectlylit** [comment]
needed to merge in your own fix @benjaoming :)

https://github.com/learningequality/kolibri/commit/6e416e015119f6f102ca4993fe3dccce885dac94#diff-7fe11226cff646f5d9f35faa76217059R15

**Review by indirectlylit — APPROVED** [review]

**Comment by benjaoming** [comment]
:face_with_head_bandage:

**Pull request merged**
