### PR TITLE
Final performance tweaks for 0.4.x

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Prevents trying to load throbber.gif from the wrong path.
Prevents SPA url endpoints from catching all urls.
Increase heartbeat interval to reduce server load.

### CODE REVIEW

**Comment by rtibbles** [comment]
Note: these have been field tested and helped to produce :much-success:!

**Comment by indirectlylit** [comment]
if possible, could you include a link to the `kolibri_exercise_perseus_plugin` changes?

**Comment by indirectlylit** [comment]
this works for me. in particular:
* URLs return 404s
* exercises still seem to work

**Comment by rtibbles** [comment]
@indirectlylit https://github.com/learningequality/kolibri-exercise-perseus-plugin/commit/db495288734ded9ce7372925c62e9e0ed25a5e9a#diff-a52871c0cf601e47fc36bb0e1116e027L20 one character change!

**Pull request merged**
