### PR TITLE
switch core require syntax from ‘/’ to ‘.’

### PR DESCRIPTION
**Pull request by indirectlylit**
Based on feedback from @DXCanas - using slashes is confusing because it makes it look like a directory structure. Dot notation is more appropriate based on the way apiSpec.js is defined.

### CODE REVIEW

**Comment by indirectlylit** [comment]
see also - https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/5

**Comment by DXCanas** [comment]
So this was as simple as substituting dots for slashes? What's the motivation for the `/` notation? Looks like it was implemented here: `frontend_build/src/apiSpecExportTools.js`?

**Comment by 66eli77** [comment]
@DXCanas @indirectlylit  looks good to me, willing to merge if no objections

**Comment by indirectlylit** [comment]
that would be great, thanks. Note that I made a corresponding PR to the perseus plugin: 67fbdf31efa94b4d8bd1a3abd2993197

**Pull request merged**
