### PR TITLE
Remove db_lock from non-django ops

### PR DESCRIPTION
**Pull request by bjester**
## Summary

Removes the `db_lock` for import operations that use the SQLAlchemy connection instead of Django's

## References

https://github.com/learningequality/kolibri/issues/8012

## Reviewer guidance

Manual testing:

* Import a channel from studio
* Delete content
* Sync

Code review:

In the code, look for any database functions that use the SQLAlchemy bridge (can tell because `sqlalchemy.Bridge` will be somewhere in the call stack. These functions should not be with a lock.

----

## Testing checklist

- [X] Contributor has fully tested the PR manually

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jonboiser** [comment]
Importing content is fine, but deleting it causes the server to hang indefinitely. The last message I see before it hangs is this

```
INFO     Removing availability of non-topic ContentNode objects in 0 batches of 10000
```

which seems like there is something wrong with the batching

**Comment by radinamatic** [comment]
I tested this branch locally and now it seems that both importing and deleting (single resources and whole channels) tasks complete successfully. I do see occasional errors in the console, but nothing user-facing.

LEDev2104 (start)  Running  - Oracle VM VirtualBox_071
LEDev2104 (start)  Running  - Oracle VM VirtualBox_069

**Review by apurva-modi — APPROVED** [review]
`db_lock()` has been removed for the non-Django operations and added to for-Django one and as per understanding everything looks clear to me, as no major code changes have been made  for this PR.

**Comment by pcenov** [comment]
@bjester today I fully regression tested https://github.com/learningequality/kolibri/releases/tag/v0.14.7-rc7 on Win 10, Ubuntu and Mac and didn't stumble upon any db_lock related issues. All looks good.

**Pull request merged**
