### PR TITLE
Create message JSON files for 'en'

### LINKED ISSUE #8908: Generate JSON file with strings in English
## Observed behavior
Long overdue reminder, I'm so sorry!!! 😞 

We need those EN strings as fallback, let's get them in.

## Errors and logs
…

## Expected behavior
…

## User-facing consequences
…

## Steps to reproduce
…

## Context
…

cc @rtibbles

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Due to a change in our webpack build process message files for the 'en' language code no longer get generated at build time
* This updates our message file generation code to create message files for english from the default messages
* Updates our .gitignore to no longer ignore en message files
* Commit the latest en message files

## References
Fixes #8908

## Reviewer guidance
Do you get any missing translation warnings in English? (most likely culprit is when using a perseus exercise)

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by nucleogenesis — COMMENTED** [review]
Just spun it up and seeing this - not sure if it's related directly to this PR

image

**Comment by rtibbles** [comment]
I think that's this issue? https://github.com/learningequality/kolibri/issues/8829

**Comment by radinamatic** [comment]
I did about 8 different Perseus exercises and a cursory walk-through other main pages, no missing EN strings! 💯

**Review by radinamatic — APPROVED** [review]
LGTM, :shipit:!

**Pull request merged**
