### PR TITLE
Add fixed header to FullScreenSidePanel

### LINKED ISSUE #8551: Implement fixed header for side panel to contain learning activities chip and close button
## Observed behavior
Slightly odd look for the close button as it scrolls down with the side panel to maintain the good user experience of quickly closing it out.

Screenshot from 2021-10-28 13-42-35

## Expected behavior
Add a fixed header that remains in place containing the learning activity chips and the close button
screen_shot_2021-10-28_at_1 57 33_pm

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Summary

Add's a slot `#header` to FullScreenSidePanel where the content at the top, aligned with the (optional) close icon, will live without scrolling. The header overlays the content of the sidepanel as it scrolls up underneath.

https://user-images.githubusercontent.com/6356129/146099414-2331ba28-f974-4718-85a2-2ebd428ddbd5.mp4

Video:

- Side panel while in library. Note that scroll section extends as Show more / License data expands
- Side panel while viewing content for the content being viewed
- "Also in this" folder for that same content
- (The H5P part) - Side panel while viewing content "Also in this" which has a "next folder" link in it
- Side panel while viewing "Also in this" lesson

Additionally:
 
- Focus is started on the header once the panel is open

Known issues:

- The scroll bar visually goes underneath the "Next folder" section which is odd but I couldn't get it lined up correctly. There is padding ensuring that all content is visible and nothing gets hidden behind it (you should double check that if you're testing though).

## References

Fixes #8551 

## Reviewer guidance

- Test a11y, keyboard navigation if you can please
- Test on mobile where possible
- Check the search filters in the library which use this component, but not the thing that I added in this PR

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
All looking 💯 ✔️  in the browser mobile/responsive view on Linux, but in the non-mobile view I'm getting this while opening the **View information** from a card in the library **Recent** section - it does not happen when user is browsing a channel and opens the sidebar, just from the main library _homepage_:

Ubuntu18 04 (start)  Running  - Oracle VM VirtualBox_021

Going to try Android next! 👍🏽

**Comment by radinamatic** [comment]
(fullscreen) Sidebar header is nice and fixed also when the asset from this PR is installed on mobile phone! ✔️ 

I could not replicate the issue from above since there is no **View information" ❕ button on cards in mobile view, is that upcoming in some other PR...? 🤔 


✔️  | ⁉️ 
--- | ---
mobile2 | mobile

**Comment by nucleogenesis** [comment]
> I could not replicate the issue from above since there is no **View information" grey_exclamation button on cards in mobile view, is that upcoming in some other PR...? 

I assumed it was part of the designs to not include it on the mobile screen. I tested the mobile by opening it on a bigger browser then shrinking it to be sure it worked as expected anyway.

Great catch on the Recent section - got that working and tests passing.

**Review by rtibbles — COMMENTED** [review]
No concerns on the code, so good to merge once @radinamatic gives the QA thumbs up.

**Comment by radinamatic** [comment]
Opening from cards in **Recent** fixed! 🎉 

Ubuntu18 04 (start)  Running  - Oracle VM VirtualBox_023

**Review by radinamatic — APPROVED** [review]
:shipit: 💯 👍🏽

**Pull request merged**
