### PR TITLE
Gherkin features

### PR DESCRIPTION
**Pull request by indirectlylit**
Gherkin features -> Develop

@radinamatic @mrpau-dev is there a reason not to merge in?

### CODE REVIEW

**Comment by radinamatic** [comment]
No specific reason, @indirectlylit, there were a couple of guest & learner scenarios still pending (see the *Integration testing* main spreadsheet, but we can merge now and add them later!

**Comment by indirectlylit** [comment]
merged! let's work off of develop from now on

**Comment by radinamatic** [comment]
Yey, pickles are released into the wild!!! 💚 💚 💚

**Comment by indirectlylit** [comment]
:pickle:

**Pull request merged**
