### PR TITLE
Pass progress explicitly from parent components

### PR DESCRIPTION
**Pull request by ralphiee22**
### Summary

Moving up calculation of the progress to the parent components, and then passing it as a prop down the component tree. This should address showing the correct progress icon within topic and content level views. 
There is a caveat. This lacks some reactivity in updating higher level topics progress icon (until refresh), because we grab progress once and it is cached for subsequent requests. Can we force fetch the progress data?

### Reviewer guidance

From a learner account, open an exercise and attempt a question. Try to complete content items under a topic.

### References

Fixes https://github.com/learningequality/kolibri/issues/5132, https://github.com/learningequality/kolibri/issues/5105, https://github.com/learningequality/kolibri/issues/5078.

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
Code makes sense to me - will merge on confirmation of bug fixes.

**Comment by radinamatic** [comment]
Ref. #5078, an exercise gets the `Started` flag in the topic list only after the second question is answered, and page refreshed.

ledev1901 start running - oracle vm virtualbox_427

**Comment by ralphiee22** [comment]
Thanks for testing @radinamatic. Right now it will not show progress in the topic list until they get an answer correct (We rely on content progress when showing in the topic list, regardless of type of content). Also, I mentioned that there lacks some auto updating of the progress icons, and that it would only be available on refresh.

**Comment by radinamatic** [comment]
Not complaining @ralphiee22 , just stating the testing results :wink: :+1:

**Comment by rtibbles** [comment]
This seems good enough to merge at the very least - any objections?

**Comment by radinamatic** [comment]
#5105 seems fixed too, topics correctly flagged according to the state of subtopics:

ledev1901 start running - oracle vm virtualbox_429

**Review by radinamatic — APPROVED** [review]
LGTM, merge away! :+1:

**Pull request merged**
