### PR TITLE
Fix dbrestore command and add a new selection option

### PR DESCRIPTION
**Pull request by jredrejo**
### Summary
In https://kolibri.readthedocs.io/en/latest/manage.html#troubleshoot-database-issues the recomendation is using the sqlite3 to try to fix the database creating a dump and restoring it.
This requires the user to install sqlite3. Also, it is a bit complex and does not work if the db is very damaged.

There was already a `dbrestore` command that could be used to restore the backups Kolibri does automatically after every migration/upgrading.

This PR does two things:
1. fix the dbrestore command, that wasn't working properly (in some cases it was comparing strings with a None object)
2. Adds a new option to the command, --select, that will show to the  user the available backups, sorted by date. Then he can select the backup to be restored

### Reviewer guidance
**Beware**: these tests will **replace** the existing kolibri database. Do a copy of it if you want to keep it.

For 1: If the latest backup is not a full version (i.e. it contains suffixes denoting git, alpha, beta, post, dev etc.)
`kolibri manage dbrestore --last`  
should restore the latest backup . This was not working in develop nor in the latest release of Kolibri.

For 2: Executing
`kolibri manage dbrestore --select` should show a list of the latest 10 backups, and will restore the one the user selects.

### References
https://github.com/learningequality/kolibri-docs/pull/75

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
Code changes make sense to me.

**Comment by radinamatic** [comment]
Having the worst of luck trying to test this one... :confused: 

Context: Ubuntu 16.04

After several attempts to intentionally "malform" the database, I settled to at least achieve a few dump files to choose from. 

Therefore, I installed v0.10, 0.11.1 and 0.12.0 one on top of the other, with some small interactions and user changes in between.

However, after that sequence, installing this asset proved to be an issue:

```
osboxes@osboxes:~/Desktop$ sudo dpkg -i kolibri-buildkite-build-5344-10503-kolibri_0.12.3a0.dev0+git.168.g358b4b08-0ubuntu1_all.deb [sudo] password for osboxes: 
(Reading database ... 315685 files and directories currently installed.)
Preparing to unpack kolibri-buildkite-build-5344-10503-kolibri_0.12.3a0.dev0+git.168.g358b4b08-0ubuntu1_all.deb ...
Unpacking kolibri (0.12.3a0.dev0+git.168.g358b4b08-0ubuntu1) over (0.12.0-0ubuntu1) ...
Setting up kolibri (0.12.3a0.dev0+git.168.g358b4b08-0ubuntu1) ...
Synchronizing state of kolibri.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable kolibri
Job for kolibri.service failed because the control process exited with error code. See "systemctl status kolibri.service" and "journalctl -xe" for details.
Processing triggers for systemd (229-4ubuntu21.21) ...
Processing triggers for ureadahead (0.100.0-19) ...
osboxes@osboxes:~/Desktop$ sudo systemctl stop kolibri
osboxes@osboxes:~/Desktop$ sudo systemctl start kolibri
Job for kolibri.service failed because the control process exited with error code. See "systemctl status kolibri.service" and "journalctl -xe" for details.
osboxes@osboxes:~/Desktop$ systemctl status kolibri.service
● kolibri.service - LSB: kolibri daemon, an offline education platform
   Loaded: loaded (/etc/init.d/kolibri; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-04-26 01:33:09 BST; 20s ago
  Process: 2889 ExecStart=/etc/init.d/kolibri start (code=exited, status=1/FAILURE)

Apr 26 01:33:09 osboxes kolibri[2889]:     app_config.ready()
Apr 26 01:33:09 osboxes kolibri[2889]:   File "/usr/lib/python3/dist-packages/kolibri/dist/morango/apps.py", line 23, in ready
Apr 26 01:33:09 osboxes kolibri[2889]:     max_parameter_substitution()
Apr 26 01:33:09 osboxes kolibri[2889]:   File "/usr/lib/python3/dist-packages/kolibri/dist/morango/util.py", line 93, in max_parameter_substitution
Apr 26 01:33:09 osboxes kolibri[2889]:     with open(SQLITE_VARIABLE_FILE_CACHE, 'w') as file:
Apr 26 01:33:09 osboxes kolibri[2889]: PermissionError: [Errno 13] Permission denied: 'SQLITE_MAX_VARIABLE_NUMBER.cache'
Apr 26 01:33:09 osboxes systemd[1]: kolibri.service: Control process exited, code=exited status=1
Apr 26 01:33:09 osboxes systemd[1]: Failed to start LSB: kolibri daemon, an offline education platform.
Apr 26 01:33:09 osboxes systemd[1]: kolibri.service: Unit entered failed state.
Apr 26 01:33:09 osboxes systemd[1]: kolibri.service: Failed with result 'exit-code'.
osboxes@osboxes:~/Desktop$ 
```


[kolibri.log](https://github.com/learningequality/kolibri/files/3119321/kolibri.log)
[server.log](https://github.com/learningequality/kolibri/files/3119322/server.log)




I also tried to install the asset from scratch on a clean VM snapshot, and got the similar error code:

```
osboxes@osboxes:~$ cd Desktop/
osboxes@osboxes:~/Desktop$ sudo dpkg -i kolibri-buildkite-build-5344-10503-kolibri_0.12.3a0.dev0+git.168.g358b4b08-0ubuntu1_all.deb 
[sudo] password for osboxes: 
Selecting previously unselected package kolibri.
(Reading database ... 302828 files and directories currently installed.)
Preparing to unpack kolibri-buildkite-build-5344-10503-kolibri_0.12.3a0.dev0+git.168.g358b4b08-0ubuntu1_all.deb ...
Unpacking kolibri (0.12.3a0.dev0+git.168.g358b4b08-0ubuntu1) ...
Setting up kolibri (0.12.3a0.dev0+git.168.g358b4b08-0ubuntu1) ...
Synchronizing state of kolibri.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable kolibri
Job for kolibri.service failed because the control process exited with error code. See "systemctl status kolibri.service" and "journalctl -xe" for details.
Processing triggers for systemd (229-4ubuntu21.21) ...
Processing triggers for ureadahead (0.100.0-19) ...
osboxes@osboxes:~/Desktop$ sudo service kolibri status
● kolibri.service - LSB: kolibri daemon, an offline education platform
   Loaded: loaded (/etc/init.d/kolibri; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-04-26 01:51:08 BST; 20s ago

Apr 26 01:51:08 osboxes kolibri[2937]:     app_config.ready()
Apr 26 01:51:08 osboxes kolibri[2937]:   File "/usr/lib/python3/dist-packages/kolibri/dist/morango/apps.py", line 23, in ready
Apr 26 01:51:08 osboxes kolibri[2937]:     max_parameter_substitution()
Apr 26 01:51:08 osboxes kolibri[2937]:   File "/usr/lib/python3/dist-packages/kolibri/dist/morango/util.py", line 93, in max_parameter_substitution
Apr 26 01:51:08 osboxes kolibri[2937]:     with open(SQLITE_VARIABLE_FILE_CACHE, 'w') as file:
Apr 26 01:51:08 osboxes kolibri[2937]: PermissionError: [Errno 13] Permission denied: 'SQLITE_MAX_VARIABLE_NUMBER.cache'
Apr 26 01:51:08 osboxes systemd[1]: kolibri.service: Control process exited, code=exited status=1
Apr 26 01:51:08 osboxes systemd[1]: Failed to start LSB: kolibri daemon, an offline education platform.
Apr 26 01:51:08 osboxes systemd[1]: kolibri.service: Unit entered failed state.
Apr 26 01:51:08 osboxes systemd[1]: kolibri.service: Failed with result 'exit-code'.
osboxes@osboxes:~/Desktop$ 
```

**Comment by jredrejo** [comment]
@radinamatic  if I understand your message correctly you did a Debian package from this ticket branch (based on develop) and tried to install it to test this PR.
The errors I see are unrelated to this PR. You seem to have discovered a bug in Morango in develop. @ralphiee22 can you take a look to the traceback?

**Comment by radinamatic** [comment]
@jredrejo Yes, I used the `deb` asset from this PR to perform the test.

The error is replicable on Ubuntu 18.04, and I'll file a separate issue, so @ralphiee22 can take a look.

Ubuntu 18 04 upg (start)  Running  - Oracle VM VirtualBox_555

On Windows 7, however, the error above does not appear, and I was able to replicate the upgrade sequence _v0.10 to 0.11.1 to 0.12.1_ to obtain two `dump` files.

`kolibri manage dbrestore --latest` (not `--last` :wink:) threw an error, but I suppose that is because the latest `dump` was because a _full_ 0.12.1 version was installed on top of 0.11.1.

```C:\Python34\Scripts>kolibri manage dbrestore --latest
←[32mINFO     Option RUN_MODE in section [Deployment] being overridden by enviro
nment variable KOLIBRI_RUN_MODE←[0m
←[37mINFO     Running Kolibri with the following settings: kolibri.deployment.de
fault.settings.base←[0m
Cannot restore while Kolibri is running, please run:

    kolibri stop

C:\Python34\Scripts>kolibri stop
←[32mINFO     Option RUN_MODE in section [Deployment] being overridden by enviro
nment variable KOLIBRI_RUN_MODE←[0m
←[37mINFO     Running Kolibri with the following settings: kolibri.deployment.de
fault.settings.base←[0m
←[37mINFO     Kolibri server has successfully been stopped.←[0m

C:\Python34\Scripts>kolibri manage dbrestore --latest
←[32mINFO     Option RUN_MODE in section [Deployment] being overridden by enviro
nment variable KOLIBRI_RUN_MODE←[0m
←[37mINFO     Running Kolibri with the following settings: kolibri.deployment.de
fault.settings.base←[0m
←[37mINFO     Beginning database restore←[0m
←[37mINFO     Searching latest backup in C:\Users\IEUser\.kolibri\backups...←[0m

Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\kolibri.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\kolibri\utils\cli.py", line 648, in main
    manage(command, args=django_args)
  File "C:\Python34\lib\site-packages\kolibri\utils\cli.py", line 459, in manage

    execute_from_command_line(argv=argv)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\management\__init
__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\management\__init
__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\management\base.p
y", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\management\base.p
y", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Python34\lib\site-packages\kolibri\core\deviceadmin\management\comman
ds\dbrestore.py", line 117, in handle
    use_backup = self.fetch_latest(search_root)
  File "C:\Python34\lib\site-packages\kolibri\core\deviceadmin\management\comman
ds\dbrestore.py", line 69, in fetch_latest
    raise RuntimeError("Could not find a database backup for version: {}".format
(fallback_version))
RuntimeError: Could not find a database backup for version: 0.12

C:\Python34\Scripts>
```

`kolibri manage dbrestore --select` successfully restored DB from both `dump` files:

Win7 (5344)  Running  - Oracle VM VirtualBox_557


@rtibbles Command works on Windows, do we want to wait for the corresponding fix to test in Ubuntu too, before the merge?

**Comment by rtibbles** [comment]
I think the windows test is sufficient.

**Comment by radinamatic** [comment]
In that case, approved!

**Review by rtibbles — APPROVED** [review]

**Review by radinamatic — APPROVED** [review]
Works on Windows, will retest on Ubuntu when #5432 is fixed!

**Pull request merged**
