### PR TITLE
WOFF pointer issues in git

### PR DESCRIPTION
**Pull request by nucleogenesis**
### Summary

I checked out 0.14 to do something really quickly and saw this:

```
Previous HEAD position was e404c44740 Merge pull request #7082 from learningequality/release-v0.12.x
HEAD is now at 6979d0610c Merge pull request #7085 from DXCanas/dockerize-integration-worksheet
Encountered 54 file(s) that should have been pointers, but weren't:
	kolibri/core/static/assets/fonts/noto-full.NotoSans.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSans.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansArabic.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansArabic.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansArmenian.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansArmenian.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansBengali.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansBengali.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansCanadianAboriginal.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansCanadianAboriginal.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansCham.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansCham.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansCherokee.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansCherokee.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansDevanagari.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansDevanagari.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansEthiopic.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansEthiopic.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansGeorgian.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansGeorgian.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansGujarati.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansGujarati.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansGurmukhi.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansGurmukhi.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansHebrew.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansHebrew.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansJavanese.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansJavanese.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansKannada.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansKannada.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansKhmer.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansKhmer.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansLao.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansLao.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansMalayalam.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansMalayalam.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansMyanmar.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansMyanmar.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansOriya.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansOriya.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansSinhala.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansSinhala.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansSymbols.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansSymbols.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansTamil.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansTamil.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansTelugu.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansTelugu.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansThaana.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansThaana.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansThai.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansThai.700.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansTibetan.400.woff
	kolibri/core/static/assets/fonts/noto-full.NotoSansTibetan.700.woff
```

No hard or soft `git reset` or any kind of `git stash` got rid of it. 

Do we need to just commit them?

### CODE REVIEW

**Review by indirectlylit — APPROVED** [review]
thank you

**Comment by indirectlylit** [comment]
it looks like these were added in https://github.com/learningequality/kolibri/pull/7084

@lyw07 @radinamatic it's very important that we use git LFS to store font files and not commit the binaries directly

**Comment by lyw07** [comment]
thank you both! sorry I think they were added yesterday by me through the latest translations strings PR. I will make sure these are not committed next time

**Comment by indirectlylit** [comment]
no problem. I've opened #7099 to prevent this in the future because it's happened before

**Pull request merged**
