### PR TITLE
Remove unneeded vacuums and close correctly the connection when needed

### PR DESCRIPTION
**Pull request by jredrejo**
### Summary
When kolibri sqlite database is big (>2 Gb) it takes a long time to start and breaks the `kolibri-server`  [booting checks.](https://github.com/learningequality/kolibri-server/issues/20#issuecomment-523139707)
Also, in 0.12.x branch, the `update_channel_metadata` function leaves the db locked.
This PR:

- removes the `update_channel_metadata` call that was executed everytime kolibri starts, leaving it only when it has to update the db
- removes an unneeded vacuum made in cli.py that was causing duplication of the vacuum process in the cases kolibri was started using the cli.
- Solves a couple of cases where the db was not properly closed and left the db open, thus vacuum does not work correctly and the wal file was kept forever, without a proper clean shutdown of kolibri.

### Reviewer guidance
- Check tests pass

The PR has very few lines, but good to take a look to ensure there are not any typos or stupid  mistakes.

### References
Closes: #5891  
IMPORTANT: The changes this PR adds in the ping.py and core/apps.py file should be ported to develop.

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — APPROVED** [review]

**Review by rtibbles — APPROVED** [review]

**Comment by indirectlylit** [comment]
@jredrejo would you please open a follow up issue for this note, and put it in the 0.13.0 milestone as P0?

> IMPORTANT: The changes this PR adds in the ping.py and core/apps.py file should be ported to develop.

**Comment by jredrejo** [comment]
> @jredrejo would you please open a follow up issue for this note, and put it in the 0.13.0 milestone as P0?
> 
> > IMPORTANT: The changes this PR adds in the ping.py and core/apps.py file should be ported to develop.

@indirectlylit  I have created #5991 to have these changes ported in develop.

**Comment by indirectlylit** [comment]
One test is failing:

```
=================================== FAILURES ===================================
____________________ PingCommandTestCase.test_ping_succeeds ____________________
self = <django.db.backends.postgresql.base.DatabaseWrapper object at 0x7f32d34f4f60>
name = None
    def _cursor(self, name=None):
        self.ensure_connection()
        with self.wrap_database_errors:
>           return self._prepare_cursor(self.create_cursor(name))
.tox/postgres/lib/python3.5/site-packages/django/db/backends/base/base.py:231: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <django.db.backends.postgresql.base.DatabaseWrapper object at 0x7f32d34f4f60>
name = None
    def create_cursor(self, name=None):
        if name:
            # In autocommit mode, the cursor will be used outside of a
            # transaction, hence use a holdable cursor.
            cursor = self.connection.cursor(name, scrollable=False, withhold=self.connection.autocommit)
        else:
>           cursor = self.connection.cursor()
E           psycopg2.InterfaceError: connection already closed
.tox/postgres/lib/python3.5/site-packages/django/db/backends/postgresql/base.py:220: InterfaceError
The above exception was the direct cause of the following exception:
kolibri/core/analytics/test/test_utils.py:50: in setUp
    content_id=uuid.uuid4().hex,
.tox/postgres/lib/python3.5/site-packages/django/db/models/manager.py:85: in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
.tox/postgres/lib/python3.5/site-packages/django/db/models/query.py:394: in create
    obj.save(force_insert=True, using=self.db)
.tox/postgres/lib/python3.5/site-packages/mptt/models.py:1007: in save
    self.insert_at(parent, position='last-child', allow_existing_pk=True)
.tox/postgres/lib/python3.5/site-packages/mptt/models.py:730: in insert_at
    refresh_target=refresh_target)
.tox/postgres/lib/python3.5/site-packages/mptt/managers.py:72: in wrapped
    return method(self, *args, **kwargs)
.tox/postgres/lib/python3.5/site-packages/mptt/managers.py:525: in insert_node
    tree_id = self._get_next_tree_id()
.tox/postgres/lib/python3.5/site-packages/mptt/managers.py:777: in _get_next_tree_id
    max_tree_id = list(self.aggregate(Max(self.tree_id_attr)).values())[0]
.tox/postgres/lib/python3.5/site-packages/django/db/models/manager.py:85: in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
.tox/postgres/lib/python3.5/site-packages/django/db/models/query.py:351: in aggregate
    return query.get_aggregation(self.db, kwargs.keys())
.tox/postgres/lib/python3.5/site-packages/django/db/models/sql/query.py:480: in get_aggregation
    result = compiler.execute_sql(SINGLE)
.tox/postgres/lib/python3.5/site-packages/django/db/models/sql/compiler.py:887: in execute_sql
    cursor = self.connection.cursor()
.tox/postgres/lib/python3.5/site-packages/django/db/backends/base/base.py:254: in cursor
    return self._cursor()
.tox/postgres/lib/python3.5/site-packages/django/db/backends/base/base.py:231: in _cursor
    return self._prepare_cursor(self.create_cursor(name))
.tox/postgres/lib/python3.5/site-packages/django/db/utils.py:94: in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
.tox/postgres/lib/python3.5/site-packages/django/utils/six.py:685: in reraise
    raise value.with_traceback(tb)
.tox/postgres/lib/python3.5/site-packages/django/db/backends/base/base.py:231: in _cursor
    return self._prepare_cursor(self.create_cursor(name))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <django.db.backends.postgresql.base.DatabaseWrapper object at 0x7f32d34f4f60>
name = None
    def create_cursor(self, name=None):
        if name:
            # In autocommit mode, the cursor will be used outside of a
            # transaction, hence use a holdable cursor.
            cursor = self.connection.cursor(name, scrollable=False, withhold=self.connection.autocommit)
        else:
>           cursor = self.connection.cursor()
E           django.db.utils.InterfaceError: connection already closed
.tox/postgres/lib/python3.5/site-packages/django/db/backends/postgresql/base.py:220: InterfaceError
```

**Comment by indirectlylit** [comment]
In the description it says "Closes: #5984"

I think this is meant to be "Closes: #5891", correct?

**Comment by jredrejo** [comment]
> In the description it says "Closes: #5984"
> 
> I think this is meant to be "Closes: #5891", correct?

Fixed, thanks!

**Comment by jredrejo** [comment]
> One test is failing:

@indirectlylit  I know, I did a commit to force the test running inside a transaction so the connection keeps open in Postgresql but it seems it was not enough. I would not like to revert the fix I did in the ping command because I noticed the db was kept open when there were db errors, but it seems tests are not able to be open a connection in the setup when Postgresql is used... if you have a better idea, I am all ears

**Comment by jredrejo** [comment]
> @indirectlylit I know, I did a commit to force the test running inside a transaction so the connection keeps open in Postgresql but it seems it was not enough. I would not like to revert the fix I did in the ping command because I noticed the db was kept open when there were db errors, but it seems tests are not able to be open a connection in the setup when Postgresql is used... if you have a better idea, I am all ears

I managed to fix it, merged!

**Comment by benjaoming** [comment]
Nominating this for the changelog, motivated by @intelliant01 's thorough and encouraging feedback :100:

**Comment by indirectlylit** [comment]
Yup, definitely!

Note that the issue it fixed (#5891) already had the _changelog_ label so we don't need to label the PR also

**Pull request merged**
