### PR TITLE
Fixes truncated text and missing header section in mobile view

### LINKED ISSUE #9624: Mobile view - Not truncated texts and missing header section
## Observed behavior
See the attached screenshots. Tested in real devices as well as using Chrome's dev tools emulator.

## Steps to reproduce the issue
1. Install the latest develop (0.16) build
2. Go to the Library > Browse channel

## Screenshots
Longer resource titles are not truncated:

Missing channel header and channel/folder title not being truncated:

## Usage Details
Windows 10 and Ubuntu 20 - Chrome, Firefox

### PR DESCRIPTION
**Pull request by Kej-r03**
## Summary

Fixed truncated title and header issue in mobile view.
Kolibri

## References

Fixes #9624 

## Reviewer guidance

Go to Learn>Library
Select any channel and turn into mobile view to see the changes.

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by Kej-r03** [comment]
@pcenov @radinamatic please take a look at the above changes

**Comment by radinamatic** [comment]
Haven't tested yet although screnshots look Ok to me. 
Thoughts @marcellamaki @jtamiace?

**Comment by marcellamaki** [comment]
Thanks for flagging, @radinamatic - I will review this today!

**Comment by jtamiace** [comment]
I haven't tested the missing headers locally, but based on the screenshot, the app bar title is line wrapping to a second line. It should be changed to one-line truncation according to the issue?

**Comment by rtibbles** [comment]
No updates in 3 weeks, closing. Please reopen if you make further updates here.

**Pull request closed without merging**
