### PR TITLE
Hashi updates

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
H5P Updates:
* Updates hashi to detach the `<body>` from the document while the `<head>` is being parsed
* As a consequence, hashi is moved from the end of `<body>` to the end of `<head>` otherwise it would be recursively reinserted and hence executed.
* Also, Hashi preparation code is now executed after the `DOMContentLoaded` event has been triggered, as the `<body>` has to finish rendering before it can properly execute
* This has the added benefit of giving more certainty when events fire
* Updates standalone H5P code in order to accommodate H5P confirmation dialogues
* Makes all backend processing for H5P as parallel as possible to non-H5P file processing
* Creates a separate H5P renderer
* Skips hashi modifications on any HTML files that might be stored inside an H5P zip, as it is only needed on the generated bootstrap HTML

Non-H5P Updates:
* Adds processing of a `SKIP_HASHI` get param to allow HTML files from the backend to be returned in a non-modified way
* Monkey patches `XMLHttpRequest` and `fetch` appropriately inside the hashi environment to add this get param to all requests, to ensure that dynamically loaded HTML is not modified

…

### Reviewer guidance
To test the H5P related updates import channel `effbdfe850dd56d4a595037a090e9225` from `develop.studio.learningequality.org` and confirm that the H5P files render appropriately.

To test non-H5P related updates, import channel `8e32a10adb4e449db5a4ee2166958a0e` from mainline Studio and test the HTML5 content item in there.

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
when running this locally, I get:

image

**Comment by ivanistheone** [comment]
Deduping works, here is the before and after:

Screen Shot 2019-12-14 at 8 02 10 AM

**Comment by rtibbles** [comment]
The screenshot from @indirectlylit seems to point to another possible issue, so I'll dig into that also before we merge this.

**Review by indirectlylit — APPROVED** [review]
no longer reproducing the issue i was seeing

**Pull request merged**
