### PR TITLE
Release v0.4.x into 0.5.x

### PR DESCRIPTION
**Pull request by rtibbles**

### CODE REVIEW

**Comment by indirectlylit** [comment]
some conflicts here. Also - title is into 0.5 but current target is develop:

image

**Comment by rtibbles** [comment]
Bah, could have sworn I had fixed that.

I opened this for tracking while we fixed up the 0.4.6 issues.

**Comment by rtibbles** [comment]
Will resolve and merge when #2370 and #2373 have been merged.

**Comment by rtibbles** [comment]
Superseded by #2387

**Pull request closed without merging**
