### PR TITLE
Basic Bootstrapping of Profile Page

### PR DESCRIPTION
**Pull request by DXCanas**
## Summary

This is the page users would go to edit their information. Really basic scaffolding here.

[Working off of this mockup](https://projects.invisionapp.com/share/6GA6TZXKZ#/screens/216117475)
[Based off of these permissions](https://docs.google.com/document/d/1ZRpd8AhCzCSLD327_szr2AuWSlXQqJ1Zq7PCVRk4gvE/edit)

Was told not to worry about styling, since the stuff's going to get overhauled with Keen soon.

## Reviewer guidance

Let me know if you've got problems with the way the object is set in the core store. I thought it'd be a simple way to check. I also decided to go with a method for the privilege check; a computed property didn't quite feel right because the property it's checking for isn't dynamic

### Here it is with all settings visible (except the submit button)
all users visible

### Here it is with privileges applied
with privileges

### CODE REVIEW

**Comment by DXCanas** [comment]
I've removed the `Lockdown Account` option since I wasn't even sure if that was meant to be included here

**Comment by DXCanas** [comment]
Also, @indirectlylit when is the WIP flag appropriate?

**Comment by indirectlylit** [comment]
usually WIP and needs review are mutually exclusive. sometimes we'll have a WIP and informally ask for initial feedback. needs review implies ready to merge if no changes are requested.

**Comment by indirectlylit** [comment]
> I've also removed the Lockdown Account option since I wasn't even sure if that was meant to be included here

that's right - not implementing that yet

**Pull request merged**
