### PR TITLE
Learner and guest Gherkin scenarios reviewed

### PR DESCRIPTION
**Pull request by radinamatic**
### Summary
Very few changes needed for these roles.
…

### Reviewer guidance
Review and merge as soon as test pass, so we can generate the spreadsheet.

### References
…

----

### Contributor Checklist

PR process:

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by cpauya** [comment]
Hi @radinamatic - sorry but I have to concede reviewing these coz of the [issue with my local macOS setup](https://github.com/learningequality/kolibri/pull/7050#issuecomment-644056268) - no way for me to test them via in a Kolibri instance.  I looked at the changes in the 4 files and they looked good to me so I will approve it based on that. 😺

@mrpau-richard or @mrpau-julius are in the process of testing if they can reproduce my above error/s on their macOS and if not, they can review these.

**Comment by radinamatic** [comment]
@cpauya Thank you!
I think we can safely ignore this Travis fail, nothing to do with the files in this PR.
Please approve & merge so we can continue with the integration testing.

**Review by cpauya — COMMENTED** [review]
All good!  

Though I noticed inconsistent indentations, some are using 2-space or 4-space indentations.

Maybe we can use 2-spaces to be consistent with the other files?

**Review by cpauya — APPROVED** [review]
Sorry, meant to Approve it earlier.  Doing that now. 😸

**Pull request merged**
