### PR TITLE
fix css venders not get applied and other styling issues

### PR DESCRIPTION
**Pull request by 66eli77**
1. apply css vender in vue file
2. center the search
3. make nav item have the same width in portrait mode

### CODE REVIEW

**Comment by indirectlylit** [comment]
can you please post before/after screenshots so we know what to look for?

**Comment by 66eli77** [comment]
screen shot 2017-01-06 at 12 20 40 pm
before

**Comment by indirectlylit** [comment]
good catch on the `postcss` stuff - probably fixes lots of bugs in one line

**Comment by 66eli77** [comment]
screen shot 2017-01-06 at 12 20 16 pm
after

**Pull request merged**
