### PR TITLE
ES6 & linting

### PR DESCRIPTION
**Pull request by indirectlylit**
Further work getting some of the existing JS files to pass the linter.

Unfortunately this broke a test. @rtibbles I could use some help deciphering what happened. My guess is that it could be related to converting `arguments` to `...args` rest parameters, but it's not clear to me how to debug backwards from the test failure.

The relevant error is

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) Mediator registerKolibriModuleAsync method async callbacks with error on script load "before each" hook for "should call logging.error twice" FAILED
	Strict mode forbids implicit creation of global property 'asset_loader'
	eval code
	eval@[native code]
	__set__@/Users/d/Projects/learning_equality/repos/kolibri/kolibri/core/assets/test/core_app_mediator.js:12161:10 <- webpack:/kolibri/core/assets/src/core_app_mediator.js (rewired):333:0
	/Users/d/Projects/learning_equality/repos/kolibri/kolibri/core/assets/test/core_app_mediator.js:488:34 <- webpack:///kolibri/core/assets/test/core_app_mediator.js:437:33
```

which refers to

```javascript
        describe('async callbacks with error on script load', function() {
            beforeEach(function() {
                var self = this;
                this.args = ['this', 'that'];
                Mediator.__set__('asset_loader', function(files, callback) {
                    callback('error!', self.kolibriModuleUrls);
                });
                this.spy = sinon.spy();
                Mediator.__set__('logging', {error: this.spy});
                this.mediator._asyncCallbackRegistry[this.kolibriModuleName][0].callback(this.args);
            });
            it('should call logging.error twice', function() {
                assert(this.spy.calledTwice);
            });
            it('should call logging.error with each of the args', function() {
                assert(this.spy.calledWith(this.kolibriModuleUrls[0] + ' failed to load'));
                assert(this.spy.calledWith(this.kolibriModuleUrls[1] + ' failed to load'));
            });
        });
```

### CODE REVIEW

**Comment by rtibbles** [comment]
You have to change:
```
Mediator.__set__('asset_loader', function(files, callback) {
                    callback('error!', self.kolibriModuleUrls);
                });
```
to
```
Mediator.__set__('assetLoader', function(files, callback) {
                    callback('error!', self.kolibriModuleUrls);
                });
```

The `__set__` method is the way that the `rewire` module injects dependencies (i.e. so we can test without using the real `assetLoader` module. Because you changed its name to camelCase, you have to change the reference to it too!

**Comment by indirectlylit** [comment]
Oh thanks! I did a search and replace but somehow missed that instance.

**Comment by indirectlylit** [comment]
mind merging if it looks good to you?

**Comment by rtibbles** [comment]
Will do... when our testing overlords doth decree it!

**Pull request merged**
