### PR TITLE
Removing HTML page generation

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

Clearing out the HTML page and associated logic, as we're updating statuses via buildkite & public pipelines now. This approach is subject to change at a later date, but I figured we should simplify maintenance on the pipeline wherever possible.

Going to have a helluva time with the commits from here to 0.13, but wanted to make sure this was all cleaned up in one go.

Looking for advice for testing this code - it's meant to only appear if a build tag is present. And I don't want to tag this commit. 

### Reviewer guidance

Please look over the code, as I'm still fairly green when it comes to writing python. 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by lyw07** [comment]
it looks like the build got separated into jobs, and all the jobs were uploaded as github checks? ~~I'm wondering if we could have one check for just the entire build.~~ Sorry I was trying to ask if the separation of jobs for the github checks is intended. Thank you!

Also the build has finished but somehow the github check thinks it is still pending.

**Comment by DXCanas** [comment]
@lyw07 it is inteded behaviour, but I'm beginning to wonder if it's necessary. Will bring that up.

The hanging `kolibri` pipeline, however, is annoying. It's becoming more of a problem.

**Comment by lyw07** [comment]
thank you for the clarification! I think the separation of the jobs should be okay, as it may just take time for people to get used to the new checks. but might be good to bring it up as you mentioned, in kolibri-dev channel or tactical meeting. Thank you!

**Comment by DXCanas** [comment]
@lyw07 I recall mentioning this in slack around 2 weeks ago, but it might not have been clear - Will reconsider. Thanks!!

**Review by lyw07 — APPROVED** [review]
LGTM!

**Pull request merged**
