### PR TITLE
Download speed remediation

### LINKED ISSUE #10836: Premature locking of chunked file during download
## Observed behavior
In the course of tests for #10825 it became clear that random access to the RemoteFile object could result in chunks of the ChunkedFile object being locked and then not released, but the file also not being downloaded and saved. This has the effect of introducing a delay as long as the lock expiry when trying to access the same chunk.

## Errors and logs
This can be reproduced by running the random access tests, e.g. https://github.com/learningequality/kolibri/blob/develop/kolibri/utils/tests/test_file_transfer.py#L462

It will be clear that there is a 10 second delay during the test while it waits for the prematurely gained lock to expire.

## Expected behavior
The lock should be released once the read operation has been completed by the RemoteFile object

## User-facing consequences
Potential slowdown during synchronous reads that need to fetch remote data.

## Steps to reproduce
See the test referenced above.

### LINKED ISSUE #10848: Content download speed regression in 0.16
## Observed behavior

Downloading content objects has become much slower with 0.16.0a14. I wrote a [script](https://gist.github.com/dbnicholson/c9ffc907546d8b866ad6210f6442a2e1) comparing 0.15.12 to 0.16.0a14 with the extremely small Passionfruit Island Series channel (`f393c30f95fb4bec87f873b2013ec9e3`). In 0.15.12 this took 7 seconds on my laptop in the best case. In 0.16.0a14 this took 60 seconds on my laptop in the best case.

## Errors and logs

No errors, although running 0.16.0a14 with `--debug` shows many more HTTP requests with 206 statuses.

## Expected behavior

No content download speed regression from 0.15.12.

## User-facing consequences

You have to wait a lot longer to use the content.

## Steps to reproduce

```
kolibri manage importchannel network f393c30f95fb4bec87f873b2013ec9e3
time kolibri manage importcontent network f393c30f95fb4bec87f873b2013ec9e3
```

## Context

Kolibri 0.16.0a14
Linux

### LINKED ISSUE #10862: Other libraries - Errors when attempting to view resources
## Observed behavior
Spotted by @marcellamaki. There's a regression on the Library page resulting in various errors when attempting to view resources from the devices in the Zerotier network.

## Expected behavior
It should be possible to freely explore any available libraries and see the resources.

## Steps to reproduce the issue
1. Install the latest develop build
2. Navigate to Learn > Library and attempt to view resources form the devices in the Other libraries section

## Video

https://github.com/learningequality/kolibri/assets/79847249/1a952c25-fea9-49e0-9ab3-99c1f0dbb1ec

## Usage Details
Kolibri 0.16alfa15
Windows 10, Ubuntu - Chrome

### LINKED ISSUE #10905: Channel export onto external drive failing
## Observed behavior
The channel was exporting for a while and then eventually showed that it had failed
…

## Errors and logs
[kolibri.txt](https://github.com/learningequality/kolibri/files/11858264/kolibri.txt)

Please wrap errors in triple backticks for clean formatting like this:
```
Kolibri Modules: kolibri.plugins.device.app registered
actions.js:210 [INFO: kolibri/core/assets/src/state/modules/core/actions.js] Notifications set.
:8080/en/device/#/content:1 Autofocus processing was blocked because a document already has a focused element.
:8080/device/api/device_channel/4489f959ec9a40c0b6c571bdd2f398df/?include_fields=total_resources%2Ctotal_file_size%2Con_device_resources%2Con_device_file_size%2Cnew_resource_count%2Cnew_resource_total_size:1     Failed to load resource: the server responded with a status of 404 (Not Found)
api-resource.js:1034 Request error: Not Found, 404 for GET to /device/api/device_channel/4489f959ec9a40c0b6c571bdd2f398df/ - open for more info
handlers.js:171 ^^^ 404 (Not Found) error returned while requesting "/device/api/device_channel/4489f959ec9a40c0b6c571bdd2f398df/..." is an expected response.
:8080/device/api/device_channel/624e09bb5eeb4d20aa8de62e7b4778a0/?include_fields=total_resources%2Ctotal_file_size%2Con_device_resources%2Con_device_file_size%2Cnew_resource_count%2Cnew_resource_total_size:1     Failed to load resource: the server responded with a status of 404 (Not Found)
api-resource.js:1034 Request error: Not Found, 404 for GET to /device/api/device_channel/624e09bb5eeb4d20aa8de62e7b4778a0/ - open for more info
handlers.js:171 ^^^ 404 (Not Found) error returned while requesting "/device/api/device_channel/624e09bb5eeb4d20aa8de62e7b4778a0/..." is an expected response.
:8080/device/api/device_channel/ec29f4cc20a8437d844a60297c2ffd07/?include_fields=total_resources%2Ctotal_file_size%2Con_device_resources%2Con_device_file_size%2Cnew_resource_count%2Cnew_resource_total_size:1     Failed to load resource: the server responded with a status of 404 (Not Found)
api-resource.js:1034 Request error: Not Found, 404 for GET to /device/api/device_channel/ec29f4cc20a8437d844a60297c2ffd07/ - open for more info
handlers.js:171 ^^^ 404 (Not Found) error returned while requesting "/device/api/device_channel/ec29f4cc20a8437d844a60297c2ffd07/..." is an expected response.
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://lggdbpblkekjjbobadliahffoaobaknh/content.72a61e7a.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
2DevTools failed to load source map: Could not load content for chrome-extension://ppbfhhgcdehhbjigifndnfmcihegokbb/globals/custom-elements.min.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
```
-->

…

image

…

## Context

Tell us about your environment, including:
 * Kolibri version 0.16.0a15
 * Operating system Mac OS
 * Browser Chrome

…

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Removes iteration API for Transfer objects
* Uses the disckcache for storing file size data and header information to allow efficient repeated requests to the same host
* Restore full file range requests to allow non-parallelized downloads to not make chunked requests with small byte ranges to prevent download speed regression
* Prevent unnecessary downloads when chunked files are complete but not finalized
* Separate the chunked file chunk size and transfer block size to allow them to be independently tweaked.
* Add locking of chunked file chunks for all downloads to help reduce parallel redundant data transfer
* Check whether chunks still need to be downloaded after a lock has been acquired when we are able to do byte range downloads

## References
Fixes [#10848](https://github.com/learningequality/kolibri/issues/10848)
Fixes #10836
Fixes [#10862](https://github.com/learningequality/kolibri/issues/10862)
I believe this also fixes #10905 - although noting that one underyling cause there is a fundamental bug in MacOS Catalina, which we are not able to fix.

## Reviewer guidance
Ensure that channel import and resource import function as intended.

Ensure that all files can be remotely browsed from other Kolibris.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
Hi @rtibbles I confirm that channel and resource import function as intended.

When browsing content remotely from other Kolibris both video and audio files are still not working - getting multiple console errors:



https://github.com/learningequality/kolibri/assets/79847249/8597d18b-7fba-4425-926a-c5eb4598029c

**Comment by rtibbles** [comment]
Thanks @pcenov - clearly something still not quite right here, I'll look again!

**Comment by rtibbles** [comment]
> When browsing content remotely from other Kolibris both video and audio files are still not working - getting multiple console errors:

This should now be resolved.

For other reviewers, the test failure I got here is not replicable locally, so I've not quite worked out what is happening here yet.

**Comment by pcenov** [comment]
> > When browsing content remotely from other Kolibris both video and audio files are still not working - getting multiple console errors:
> 
> This should now be resolved.

I confirm - viewing video and audio resources is working correctly now and I didn't observe any regressions.

**Review by radinamatic — APPROVED** [review]
Manual QA passes, good to go! 💯 :shipit:

**Review by jredrejo — CHANGES_REQUESTED** [review]
Code looks good, but there's a race condition that is making tests fail randomly.
This code is not being executed in time  
https://github.com/learningequality/kolibri/blob/de293846230e1fe93bdc377f34bfb6a67a0505f5/kolibri/utils/file_transfer.py#L378 in this test https://github.com/learningequality/kolibri/blob/de293846230e1fe93bdc377f34bfb6a67a0505f5/kolibri/core/content/test/test_import_export.py#L1017 . The mock returns a `test/test` value that requires a `test/test.chunks` directory to be created and it's not done in time in a slow disk (as it seems GH has, in my laptop SSD disk the problem does not raise)

**Comment by rtibbles** [comment]
> The mock returns a test/test value that requires a test/test.chunks directory to be created and it's not done in time in a slow disk (as it seems GH has, in my laptop SSD disk the problem does not raise)

I looked into this a bit more, and I think the issue was to do with how the test was using temporary files. In the course of this cleanup, I have hardened the chunked file and remote file implementations against rug pulling, and also simplified the resource import logic and tests.

**Comment by pcenov** [comment]
Hi @rtibbles, the only issue I was able to identify while regression testing is that the export to flash drive is failing. Tested on both Windows 11 and Ubuntu. Here are the logs, no error observed in the browser console.
[logs.zip](https://github.com/learningequality/kolibri/files/11896290/logs.zip)

**Comment by rtibbles** [comment]
I had fixed one issue with export, and then @pcenov had reported another, which I have hopefully now fixed as well!

**Comment by pcenov** [comment]
Hi @rtibbles I confirm that the export is functioning correctly now. Here are what I believe the last remaining issues here after I carefully fully regression tested all import/export workflows and remotely accessing content:

Importing an entire channel or several channels simultaneously from USB is not working:

https://github.com/learningequality/kolibri/assets/79847249/39ca648c-6132-4ec3-999d-cd62e037ed6d

If I am importing a channel from a device on my network and I select the option to import entire channels, but the channel on the device consists of only a few of all of the original resources in that channel, then it incorrectly attempts to download the entire channel from studio and the import fails since the channel is too large:

https://github.com/learningequality/kolibri/assets/79847249/a4f3d26e-5297-4248-ae31-fe68baf2a08a

Logs: [logs.zip](https://github.com/learningequality/kolibri/files/11916828/logs.zip)

**Review by jredrejo — APPROVED** [review]
This PR has so many changes that's pretty hard to review, I have tested it as deep as I've been able and looked at the code without seeing any issue anymore.
As soon as latest tests from Peter end, it's fine to be merged.

**Comment by rtibbles** [comment]
Both the issues that @pcenov noted here should now be resolved - they were both pre-existing regressions in develop from previous task refactoring (and incorrect merge conflict resolution).

**Comment by pcenov** [comment]
@rtibbles the issue about importing channels from my network is resolved now, however the one about USB channel import is still extant. I have reported it separately here: https://github.com/learningequality/kolibri/issues/10934 as you have mentioned that it's not caused by changes in this PR.
I have also regression tested channel import/export and remote browsing and have not found any other issues so this PR can be merged.

**Comment by radinamatic** [comment]
Follow-up issue is reported, this should be ready to merge! 👍🏽

**Pull request merged**
