### PR TITLE
Move exam models out of content to avoid having syncable models in Content models

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

In order to give easier integration in the CC server, move any syncable models out of the content app.

### CODE REVIEW

**Comment by aronasorman** [comment]
Looks mostly like reshuffling. I'll test out the buildkite build to see if the morango dependency is gone now.

**Comment by aronasorman** [comment]
It's working on the cc server!!! Wooo!!!

**Comment by aronasorman** [comment]
Will merge once the tests pass.

**Comment by rtibbles** [comment]
They shall not pass.

**Comment by rtibbles** [comment]
(there is an issue with installing morango inside the pythonlint tox env right now - we don't know why)

**Pull request merged**
