### PR TITLE
Update v0.13.x Morango dependency to latest version

### PR DESCRIPTION
**Pull request by bjester**
## Summary

- Updates Morango dependency to latest version `0.6.5`

## References

https://learningequality.slack.com/archives/CAKK24483/p1631897590033100

## Reviewer guidance

- `EcosystemTestCase.test_chaos_sync` seems to fail regardless with an error about:
```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://127.0.0.1:40223/api/auth/classroom/
```

----

## Testing checklist

- [X] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jamalex** [comment]
>requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://127.0.0.1:40223/api/auth/classroom/

Hmm, strange, I can't seem to find where that test would be making that request. Is there a fuller traceback?

**Comment by bjester** [comment]
@jamalex The request comes from [this line](https://github.com/learningequality/kolibri/blob/release-v0.13.x/kolibri/core/auth/test/test_morango_integration.py#L82) initiated from [this line in the test](https://github.com/learningequality/kolibri/blob/release-v0.13.x/kolibri/core/auth/test/test_morango_integration.py#L392)

**Comment by jamalex** [comment]
Ah, OK, I was looking at [a newer version of the test](https://github.com/learningequality/kolibri/blob/2d0cf3d166b491114ec35397c66537370b47d049/kolibri/core/auth/test/test_morango_integration.py#L132) that used `create_model` instead of the API endpoints. We could probably just ignore that, unless we want to backport that part of the tests.

**Comment by bjester** [comment]
@jamalex Yeah I know there have been some recent improvement that you and @rtibbles have made to those tests, so after spending a moment to figure out if I could fix it, I decided to let it be.

**Review by jamalex — APPROVED** [review]
Sounds as if it's working, and the proof's in the pudding! Thanks!

**Pull request merged**
