### PR TITLE
Tidies up root dir by putting all JS build and testing config files into subdirs.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

See title.

## Reviewer guidance

This is a tiny refactor, if tests pass, then all is good!

Have manually tested by locally running build and test scripts for JS.

### CODE REVIEW

**Comment by indirectlylit** [comment]
Would it make sense to maybe consolidate the `/assets` dir into `/webpack_config`?

**Comment by rtibbles** [comment]
While the majority of the code in there is used for creating our own webpack config, I would prefer to keep it separate, as they are not explicitly just webpack configuration files.

**Comment by indirectlylit** [comment]
fair enough. could also combine them both into `client-assets` or something, if they're generally "coupled" and working together... your call

**Comment by rtibbles** [comment]
`client-assets` might be a little misleading, given that they are only used by the node build process. I'll just merge as is.

**Pull request merged**
