### PR TITLE
More explicitly pinning watchdog dependency

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

There is a build breakage for Kolibri due to a sloppy dependency set by one out our dependencies. The more recent builds haven't experienced it because of docker caching, I suspect.

Some package depends on watchdog, and wathdog's latest release (`1.0.0`) doesn't seem to support python2, which we use in building to support python2 installers.

This will be a waterfall commit. Please bear with me.

### Reviewer guidance

See if buildkite builds the image!

### References

This seems to be a requirement for building 0.14.5 installers for @lauradanforth @jredrejo @radinamatic 

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jonboiser** [comment]
@DXCanas We actually removed `sphinx-autobuild` recently. You could probably do the same here on this branch just to save some trouble.

**Comment by DXCanas** [comment]
> @DXCanas We actually removed `sphinx-autobuild` recently. You could probably do the same here on this branch just to save some trouble.

Music to my ears. Thanks for the heads up.

**Comment by DXCanas** [comment]
@rtibbles @jonboiser Is travis perpetually broken? Should I ignore and merge?

**Comment by rtibbles** [comment]
Yes, Travis will never work for us again.

**Pull request merged**
