### PR TITLE
Add integrity checking for sqlite3 databases

### LINKED ISSUE #7907: Implement integrity check of job_storage database at startup and clear if broken
### Observed behavior
If something like an unclean shutdown has caused the job_storage sqlite file to be in a bad state, then any subsequent queries to the Tasks database may result in errors.

### Expected behavior
We should attempt to read any extant jobs in the tasks database at startup, and if it results in an error and is using SQLite, clear the file.

### User-facing consequences
Unclean shutdowns that leave the job storage database in an unclean state could prevent the usual 'clear at startup' that we do, and then leave 500s coming from queries to the Task API.

### PR DESCRIPTION
**Pull request by vkWeb**
## Summary
Added integrity checking for sqlite3 databases. It has been implemented on `job_storage.sqlite3` to detect database corruption and regenerate. 

## References

Closes https://github.com/learningequality/kolibri/issues/7907

## Reviewer guidance

Edit `job_storage.sqlite3` via text editor to break integrity then run server to see if the database is detected as corrupt or not.  

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by vkWeb** [comment]
cc @rtibbles for review.

**Review by rtibbles — APPROVED** [review]
Works as intended.

**Comment by vkWeb** [comment]
@rtibbles yeah! 

Btw, the issue https://github.com/learningequality/kolibri/issues/7907 looks open? Doesn't this fix it?

**Comment by rtibbles** [comment]
Yeah, I was not at my computer when it got reopened, no idea how.

**Comment by vkWeb** [comment]
Ohhh, no problem sir!

**Pull request merged**
