### PR TITLE
Disables caching for the kolibri studio status check

### LINKED ISSUE #11437: Library - No clear indication of a lost internet connection
## Observed behavior

There's no clear indication that I've lost my connection - the Kolibri Library appears available but clicking on a resource just brings me back to the Library page.

## Expected behavior
To be further discussed.

## Steps to reproduce the issue
1. Install the latest build from https://github.com/learningequality/kolibri/pull/11419 and setup a full facility.
2. Go to the Library page.
3. Turn off your wi-fi.
4. Keep attempting to explore the 'Kolibri Library' section under 'Other libraries'

## More information

https://github.com/learningequality/kolibri/assets/79847249/94a34eb1-1d7d-4e32-9a2a-435560d2a183

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome, Firefox

### PR DESCRIPTION
**Pull request by akolson**
## Summary

This pr fixes the **Disconnected** indicator that is displayed when there is no internet connection on the host device by disabling caching on the `kolibri_studio_status` view, the root cause of the reported issue.

https://github.com/learningequality/kolibri/assets/5203639/2141dc64-8b4d-4d33-bd1c-07f06ee93241

https://github.com/learningequality/kolibri/assets/5203639/df2fca02-35db-4450-9236-2be05166c7d7

## References

Fixes https://github.com/learningequality/kolibri/issues/11437

## Reviewer guidance

1. Go to the Library page.
2. Turn off your wi-fi.
3. Keep attempting to explore the 'Kolibri Library' section under 'Other libraries'

**Note:** Some strange behavior was picked up around caching of failed requests and is being or will be addressed with [this separately filed issue](https://github.com/learningequality/kolibri/issues/11457)

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
Confirmed the code changes and some behaviour changes by inspecting the returned cache headers. If you can confirm the overall issue fix, @pcenov we're good to go here!

**Comment by radinamatic** [comment]
Confirmed that the '_Disconnected_' notification appears as soon as the device looses the connection, and disappears once the connection is reestablished. Kolibri Library disappears from the Other libraries section and there is the _No other libraries around you right now_ notification. I must admit that I would have preferred if the _Disconnected_ notification was also visible on the Library main page, and not only in the top bar for folders and resources.


https://github.com/learningequality/kolibri/assets/1457929/73550cb4-fe39-4695-8e35-dc0b20933dd7

**Comment by rtibbles** [comment]
>  I must admit that I would have preferred if the Disconnected notification was also visible on the Library main page, and not only in the top bar for folders and resources.

That does seem like possibly an oversight either in design or implementation. @akolson I am not sure if we are currently checking device status on the library page when `deviceId` is defined, so it seems maybe we should be doing that here, and displaying the Disconnected notification accordingly. Can either do in this PR or file as a follow up.

**Comment by akolson** [comment]
@rtibbles It is actually added to the Library page. From what I see, it has been conditionalized to display only when the `deviceId` is not null thus why its not showing. We should probably remove this check.

**Comment by rtibbles** [comment]
Sorry - it looks like I misinterpreted @radinamatic's query - she was suggesting to do this when the network connection is lost as a whole, but we don't have a way of detecting this currently in Kolibri, so I don't think we can implement this now. We can carry on!

**Review by radinamatic — APPROVED** [review]
Manual QA passes, good to go! 💯 🎉 :shipit:

**Pull request merged**
