### PR TITLE
Translations for content license descriptions and names

### LINKED ISSUE #2371: Allow internationalization of known content licenses
## Summary

Currently all content licenses are hard coded into the database. It would be good to be able to translate known content licenses into the interface language.

### LINKED ISSUE #5569: creative commons licenses are written from perspective of content creator
### Observed behavior

Noticed by @jamalex, our CC licenses are currently displayed to learners and coaches but written from the perspective of the content creator, e.g.:

> **Attribution-NonCommercial-ShareAlike**
> 
> This license lets others remix, tweak, and build upon your work non-commercially, as long as they credit you and license their new creations under the identical terms.

This should also be taken into account when we address #2371

### Expected behavior

perhaps something like:

> **Attribution-NonCommercial-ShareAlike**
> 
> This license lets you remix, tweak, and build upon this work non-commercially, as long as you credit the copyright holder and license your new creations under identical terms.

### User-facing consequences

The terms of the license don't really make sense in this context as currently written

### Steps to reproduce

View any KA content

### Context

0.12.4

### LINKED ISSUE #6003: Add warnings to catch invocations of translation functions before polyfill loading occurs
### Observed behavior
On two occasions now we have fixed Kolibri due to invocation of translation machinery in module scope breaking on Intl-polyfilled browsers. (#5254, #6002)

### Expected behavior
The linter should catch these invocations in module scope and error.

Alternatively, we can add a flag like `i18nReady = false` that gets set to `true` after `setupi18n` has been invoked. Then the translation machinery should complain if run too early

### User-facing consequences
Total breakage in old browsers.

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

* Adds license names and descriptions as actual translated strings
* Removes all references to user-facing strings in LE-utils. License names are only used as IDs now
* Raise error if translation machinery is run before ready

We now have four sets of strings:

* Short license names
* Long license names (sometimes the same as short)
* License descriptions, from the perspective of a content consumer
* License descriptions, from the perspective of a content creator (unused)

### Reviewer guidance

See any issues?

### References

* fixes https://github.com/learningequality/kolibri/issues/2371
* fixes https://github.com/learningequality/kolibri/issues/5569
* fixes #6003
* refs https://github.com/learningequality/kolibri/pull/5205

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
Code looks good to me. Any chance of replicating your previous work of bringing in the license descriptions from CC to avoid our translators having to duplicate that work?

**Comment by indirectlylit** [comment]
yes, and in fact I created [a next-action to do that](https://www.notion.so/learningequality/Add-previously-written-license-strings-to-crowdin-9eed5c4d60fa4e0ab30da77868f460aa).

However, since then I've actually edited the descriptions a fair amount to bring them more in line with the terminology we use in the rest of the app, for example replacing "work" with "resource": https://github.com/learningequality/kolibri/pull/6042/commits/498d3a6099f67e53f0829bb5bd4e9ee4db880bea

see also notes in: https://github.com/learningequality/le-utils/issues/70 and https://github.com/learningequality/kolibri/issues/5569

feedback would be appreciated

**Comment by radinamatic** [comment]
Not able to test the translated licenses, even after overcoming the issue of *Change language* not working [with the help](https://learningequality.slack.com/archives/CB37UM23A/p1573602410469200) of @nucleogenesis. Are the translations in at all? Not sure what to test otherwise... :thinking: 

LEDev1911n (start)  Running  - Oracle VM VirtualBox_189

**Comment by indirectlylit** [comment]
>  Are the translations in at all?

No, these are all new strings (see my response to @rtibbles above)

> Not sure what to test otherwise...

Mainly I wanted feedback on the actual text: https://github.com/learningequality/kolibri/pull/6042/files#diff-9f7ce4e3d27b9bd48244300dc36466fcR5-R208

**Comment by indirectlylit** [comment]
Self-merging for string freeze. Please open follow-up issues if necessary

**Pull request merged**
