### PR TITLE
Use server state for learner management

### PR DESCRIPTION
**Pull request by MCGallaspy**
## Summary

Still a work in progress. This space reserved for future comments.

## TODO

- [X] Have tests been written for the new code?
- [ ] Has documentation been written/updated?
- [X] New dependencies (if any) added to requirements file
- [X] Add an entry to CHANGELOG.rst

## Reviewer guidance

* Run the server and take a peek at `http://localhost:8000/management/`: `kolibri --debug manage -- --webpack` (@radinamatic you can do this to check out the resulting html!)
* Start with `test/management.js` to understand the intended functionality of the management app.
* Move on to `main.vue` and `src/management.js` to see changes in the application logic. Basically I make the classroom and group selectors functional.
* Changes to `getters.js`, `store.js`, and `fixture1.js` are pretty minimal. The currently selected group is now a state variable, similar to the currently selected classroom. It has two special values -- one corresponding to all groups within the currently selected classroom, and one corresponding to *no* groups selected, which is the state it should be in when the classroom selector takes the special value `ALL_CLASSROOMS_ID`.
* In `actions.js` a new action is defined which fetches classroom and learner group data from the server. It attaches a `learnerGroups` property to classrooms and a `learners` property to groups since the `main.vue` expects this.
* The remaining python files deal with the `kolibri.auth` module http API -- I add filtering functionality and polish up the fields exposed by the model serializers, as well as writing some new test cases.

### CODE REVIEW

**Comment by MCGallaspy** [comment]
Part of the drop in coverage is due to the untested `fetch` action. However it's not enough to mock the xhr -- we also have this same problem that `kolibriGlobal.urls` is undefined, since the test webpack pipeline does not build it as the regular one does. We could exclude this action from the tests, maybe? Open to recommendations.

**Comment by rtibbles** [comment]
Might be worth embellishing the urls object a bit, so that instead of just setting it directly in the template, we register it with kolibriGlobal, and then it is exposed through a thin wrapper.

This wrapper could be of the form `(url_name, ...args) => {return urlsObject[url_name](...args);}` or somesuch.

**Comment by MCGallaspy** [comment]
I made the urls into parameters of the action, so I could just stub them. See last commit.

**Comment by MCGallaspy** [comment]
I seem to have beaten some reviews here in both adding some additional functionality and refactoring for readability. Closing this PR to open a new one -- it's a bit longer, but hopefully it will be easier to review as well!

**Pull request closed without merging**
