### PR TITLE
update notification styling

### LINKED ISSUE #7149: padding needed above 'new version' banner
### Observed behavior

insufficient padding

image

### Expected behavior

padding consistent with other pages - some multiple of 8px

### Context

0.14.0 beta 3

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

| before | after |
|--|--|
| image| image |

### Reviewer guidance

make sense?

any regressions? 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by jonboiser — APPROVED** [review]

**Comment by radinamatic** [comment]
I actually liked the old version of the notification, it was impossible to miss.

This new one is better styled, true, but so easy to overlook :confused:

**Comment by jonboiser** [comment]
This test needs to be fixed here: https://travis-ci.org/github/learningequality/kolibri/jobs/711165802#L8356

It might simply just involve flipping the indices of the paragraphs to get the right text.

**Comment by indirectlylit** [comment]
this better?

image

**Comment by radinamatic** [comment]
Yes, this does look more **prominent** :+1: 

We could discuss adding a different background color for that block (like for old notifications), to make it pop out even more, but this looks OK for now.

**Comment by indirectlylit** [comment]
fixed linting, force-merging

**Pull request merged**
