### PR TITLE
integrate PF functionality into develop

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

* resolves conflicts merging the `pf-mvp` branch into `develop`
  * KIcon.vue
  * FacilityIndex.vue
  * DataPage/index.vue
  * facility/assets/src/routes.js
  * deployment/default/settings/base.py
  * tasks/api.py
  * cli.py
* remove pf-specific functionality

### Reviewer guidance

everyone on the reviewer list has changes that were affected. Please check parts of the code relating to your work

### References

https://github.com/learningequality/kolibri/pull/6667

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by jredrejo — COMMENTED** [review]
I have added a couple of commits to fix problems with the bulk import/export and now everything looks good to me for that part

**Comment by indirectlylit** [comment]
@rtibbles @jonboiser mind taking a look? I resolved another conflict in cli.py and merged another round of commits

**Comment by rtibbles** [comment]
I don't see anything in any of the merge conflicted files that looks concerning to me.

**Comment by indirectlylit** [comment]
getting some seemingly unrelated build failures.

```
Installing cryptography-2.3-cp36-cp36m-win32.whl...
--
  | Installing cryptography-2.3-cp37-cp37m-win32.whl...
  | parse_requirements(args)
  | File "build_tools/install_cexts.py", line 361, in parse_requirements
  | install(char_list[0].strip(), char_list[1].strip())
  | File "build_tools/install_cexts.py", line 338, in install
  | r = requests.get(link + name)
  | File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 75, in get
  | return request('get', url, params=params, **kwargs)
  | File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
  | return session.request(method=method, url=url, **kwargs)
  | File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
  | resp = self.send(prep, **send_kwargs)
  | File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
  | r = adapter.send(request, **kwargs)
  | File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 498, in send
  | raise ConnectionError(err, request=request)
  | requests.exceptions.ConnectionError: ('Connection aborted.', error(0, 'Error'))
  | make: *** [staticdeps-cext] Error 1
  | Makefile:149: recipe for target 'staticdeps-cext' failed
```

@lyw07 any thoughts on this?

**Comment by lyw07** [comment]
I think it's because the website where we get the cryptography packages for raspberry pi is down due to maintenance
hopefully it should be up soon

**Review by jonboiser — APPROVED** [review]

**Comment by jonboiser** [comment]
The `LogoutLanguagePersistenceTest` 
https://github.com/learningequality/kolibri/blob/84cdb01f079d882d1e7cef8fadb764bab941c643/kolibri/core/test/test_key_urls.py#L168

test case is failing because going to `/nyn/logout` and `/yo/logout` are returning a 404.

The `test_persistent_session_language_setting_on_logout` tests are failing on `yo` because the namespaced URL it gets redirected to is `/en/logout`.

**Comment by indirectlylit** [comment]
hallelujah

**Pull request merged**
