### PR TITLE
Add keyup handler to ensure proper triggering of input value event

### PR DESCRIPTION
**Pull request by bjester**
### Summary

Researching the internet, there's some indication that some soft keyboard events may not fire the same in WebView, especially without special handling in Java. I was able to reproduce this in Chrome for Android, so hopefully this resolves it for the Android WebView as well.

This simply adds another event handler for `keyUp` that sends the input target value to our throttled emitter. The component supported unthrottled updates so by default, there is now a small throttle of 15 milliseconds.

### References

Addresses: https://github.com/learningequality/kolibri/issues/6908

----

### Contributor Checklist

PR process:

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] ~If this is an important user-facing change, PR or related issue has a 'changelog' label~
- [ ] ~If this includes an internal dependency change, a link to the diff is provided~

Testing:

- [X] Contributor has fully tested the PR manually
- [ ] ~If there are any front-end changes, before/after screenshots are included~
- [ ] ~Critical user journeys are covered by Gherkin stories~
- [ ] ~Critical and brittle code paths are covered by unit tests~

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
nice!

**Comment by indirectlylit** [comment]
@mrpau-dev would you mind testing this change?

**Comment by mrpau-richard** [comment]
@bjester can you upload the Android installer for this PR, I'm trying to test this on my physical device but I can't find the Installer at the BuildKite.

**Comment by indirectlylit** [comment]
@DXCanas would you please advise on how to build the APK?

**Comment by DXCanas** [comment]
If this could bring in the latest changes from app-support via merge or rebase, the android pipeline will trigger. You’d then have the ability to unblock the android build with these changes in it

**Comment by indirectlylit** [comment]
thanks, merged in `app-support`

**Comment by indirectlylit** [comment]
@mrpau-richard the APK should now be built in buildkite: https://buildkite.com/learningequality/kolibri-android-installer/builds/228

**Comment by mrpau-richard** [comment]
>> @mrpau-richard the APK should now be built in buildkite: https://buildkite.com/learningequality/kolibri-android-installer/builds/228

Thanks @indirectlylit 

@mrpau-julius can you test this PR on your Android devices, The Kolibri app keep crashing on my Android 5.0.1. here's the installer to test this https://buildkite.com/learningequality/kolibri-android-installer/builds/228#ea6318d5-5ede-4e6c-a579-e15b1b0c3057

**Comment by mrpau-julius** [comment]
@mrpau-richard In an hour of testing on Android 9.0 (Pie). Launching the app is not working. Still in the page of `Starting Kolibri` and not proceed to Kolibri main setup.


Screenshot_20200609_132625_org learningequality Kolibri

**Comment by indirectlylit** [comment]
cc @kollivier thoughts?

**Comment by bjester** [comment]
I can rebase this if it helps.

**Review by indirectlylit — APPROVED** [review]
merging to get it ready for integration testing

**Pull request merged**
