### PR TITLE
Delete previously committed message files with outdated naming scheme update all translations

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* It seems that we had failed to cleanup previously committed English message files when we changed the naming scheme for message files, and they have been bloating the Kolibri distribution ever since.
* Updates the frontend JSON message file creation code to clear out existing JSON files before generating
* Regenerates all JSON files
  * Deletes old, unused message files
  * Adds in messages in message files where components have been additionally imported and are now required

## References
Seems to have been extant since this PR was merged: https://github.com/learningequality/kolibri/pull/5887

Finalizes translation message files for release

## Reviewer guidance
Should give no ill effects - smoke test by looking at the user interface, and ensuring that the console doesn't warn about missing strings from message files.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
Checked out the branch in development and switched to several different languages in the UI: no errors observed on the front end and nothing in the console.

I'll smoke test with the built asset before approving.

**Review by nucleogenesis — COMMENTED** [review]
Code updates LGTM - will leave final approval to Radina's smoke test

**Comment by radinamatic** [comment]
Still not seeing anything concerning in the UI on Ubuntu 20.04, and guessing these console errors have nothing to do with the changes in this PR.

Firefox | Chrome
-- | --
 |

**Review by radinamatic — APPROVED** [review]
LGTM, good to go! 💯 :shipit:

**Pull request merged**
