### PR TITLE
Modal event fixes

### PR DESCRIPTION
**Pull request by indirectlylit**
addresses user management issues caused by core-modal refactor

https://trello.com/c/njGVvqa0/599-look-into-breakage-around-enter-and-cancel-handling-in-user-mgmt-modals

### CODE REVIEW

**Comment by rtibbles** [comment]
This seems to work, but very frequently when I click 'confirm' or press enter, it immediately redirects me to the learn page. This seems undesirable UI. Assume this probably wasn't introduced by this PR, but would be nice to fix.

**Comment by indirectlylit** [comment]
I haven't noticed that on my end. Would definitely like to fix - maybe today I can spend 20 min trying to debug on your computer?

**Comment by rtibbles** [comment]
Sure - I imagine it must be related to the redirect that is in place in case a user deletes their own account from the management page?

**Comment by rtibbles** [comment]
Ahah, I think I know why. I am logged in as a DeviceAdmin. The database `id` for the DeviceAdmin I am using is `1`. The user_id for the user I am editing is `1`. This means I have just set the learner role for the id of my session_id, which prompts the redirect.

**Comment by rtibbles** [comment]
Yeah, confirmed. It only happens to the learner with the identical id.

**Comment by indirectlylit** [comment]
Okay - and that only happens when you change the role from Admin to Learner? Or it happens for other edits also (e.g. changing the name)?

**Comment by rtibbles** [comment]
When making any edit. I am not editing the learner at all, it just happens to have the same id as the DeviceAdmin I am logged in as. In fact, it wouldn't happen if I was editing a FacilityAdmin with the same id, because they would not have the Learner role.

**Comment by DXCanas** [comment]
@rtibbles, I know @ralphiee22 added a simple check to for user deletion, but I can't image why that would be interfering here. Gonna take a closer look at the PR when I'm done with classes.

**Comment by rtibbles** [comment]
See the comment chain above, @DXCanas - it's due to the fact that DeviceAdmins and other users can share a user id, because DeviceAdmins are a different Django model.

I have submitted a PR to fix this, that just checks if the user is a SUPERUSER as well.

**Comment by DXCanas** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;njGVvqa0&#x2F;599-look-into-breakage-around-enter-and-cancel-handling-in-user-mgmt-modals"> look into breakage around &#39;enter&#39; and &#39;cancel&#39; handling in user mgmt modals</a>

**Comment by indirectlylit** [comment]
@rtibbles - your PR was merged and this branch was rebased against master. Mind checking and merging?

**Comment by rtibbles** [comment]
@indirectlylit feel free to merge when Travis says so!

**Pull request merged**
