### PR TITLE
updates to learner quiz view

### LINKED ISSUE #5440: Submit button on top right corner of a quiz
**Observed behavior**
The students sometimes directly press the Submit button on the top right corner of any quiz without even start or just after attempting the first question. This inturn directly completes the quiz.

**Expected behavior**
The Submit button appears in the last page of the quiz so that students don't press it by mistake. On the last page of the quiz we can have the submit button in the place of next button.

**User-facing consequences**
The exams/quizzes get submitted even before they are attempted or completed. This in turn affects the teacher who had prepared and planned for the quiz.

**Steps to reproduce**
Create a quize and check using any tablet.

**Context**
Kolibri version : Kolibri 0.12.2
Operating system : ubuntu 14.04
Browser : Chrome
Screenshot_20190430-153902

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

Changes based in part on discussion with the team at design office hours and Ana's design work.

fixes #5440

* adds floating bottom bar
* adds 'Question X of Y' header above exercise
* 'next' and 'previous' button updates
    * remove the word 'question'
    * make them both primary
* 'submit' button updates
    * moves it next to the 'X of Y answered' text
    * makes it a flat secondary button
* layout updates
    * increases screen real estate on larger screens
    * removes question list on smaller screens
    * on mobile screens, 'submit' button moves to inner scrolling pane

**Old view:**

image

**New desktop view:**

desktop

**New tablet view:**

tablet

**New mobile view:**

mobile

### Reviewer guidance

there are also some changes in https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/188 which this PR leverages in terms of layout cleanup

### References

https://github.com/learningequality/clearinghouse/issues/291

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
Looks good... visually. My only concern would be the experience of users who navigate by keyboard, as having the `Submit quiz` button _in between_ the `Next` and `Previous` does not seem optimal.

Even in terms of tasks to be performed, submitting comes _after_ navigating between and answering questions, shouldn't the `Submit quiz` button be located "after" the `Next` and `Previous` ones, not only in the DOM that determines the <kbd>Tab</kbd> order, but visually too?

**Comment by indirectlylit** [comment]
thanks, good feedback!

**Comment by miyer03** [comment]
Few thoughts on this 

1. If the submit button could appear on the last page of the quiz, then there will not be any case when a student, presses the Submit button by mistake in between a quiz.

2. In case we can't go by the above suggestion, would suggest to have some symbols for previous, next and sumbit along with the text <-- for previous  --> for next . Also, agree with the previous suggestion that Submit should appear after next.

**Comment by khangmach** [comment]
slice

based on the feedback I'm seeing here:
- Incorporate arrows into the buttons to show directionality
- Group together like-actions (in this case the navigational actions of previous/next)
- In smaller breakpoints, only show the arrow buttons to save space

**Comment by miyer03** [comment]
@khangmach the above option look good.

**Comment by indirectlylit** [comment]
I ran into two issues with the proposal above:

1. Does not work for smaller breakpoints: 'x of y answered' text and 'submit quiz' button are large enough to dominate the footer
2. Inconsistent with other full-screen footers in the app, which all have primary buttons in the bottom-right

I've tried to work around these while still ensuring semantically-correct a11y ordering for both DOM order (screen readers) and keyboard tab order:

1. Next
2. Previous
3. Submit

Let me know if you think this satisfies all the constraints, including the original primary goal of emphasizing the next/prev functionality over submission.

Updated changes below, with semantic order of buttons highlighted:

### Desktop view

> image

### Desktop view (RTL)

> image

### Tablet view

> image

### Mobile view

> image

**Review by khangmach — APPROVED** [review]
Works for me. Nice call hiding the x of y text on smallest breakpoint

**Comment by radinamatic** [comment]
Maybe we don't need to address it right now, but I still find awkward that in the tablet view `SUBMIT` is _before_ `Next` and `Previous`, even visually... :confused:

**Comment by radinamatic** [comment]
What happens when the user tabs between answers, and then into `Next` or `Previous`, is the `SUMBIT` skipped every time?

**Comment by indirectlylit** [comment]
> What happens when the user tabs between answers, and then into Next or Previous, is the SUMBIT skipped every time?

Submit is initially skipped and then gets focus after 'Previous'

**Comment by radinamatic** [comment]
So if I understand correctly, user tabs through the answers, tabs to `Next`, but if they want to go back and correct, they will tab-back to `Previous`, and eventually run into `SUBMIT`, right?

**Review by jtamiace — APPROVED** [review]
Looks good to me as well. 

Any thoughts from you guys on switching the order of "SUBMIT QUIZ" and "X of Y questions answered"? I don't know why it feels a bit strange for the action to be floating in space like that

**Comment by indirectlylit** [comment]
> Any thoughts from you guys on switching the order of "SUBMIT QUIZ" and "X of Y questions answered"? I don't know why it feels a bit strange for the action to be floating in space like that

I actually had it like that originally, and it looked even weirder because the button has inner padding which makes the whole thing become visually indented, especially in this view:

image

**Comment by indirectlylit** [comment]
merging in. I'm sure there are improvements that can be made, so let's tackle that in subsequent updates

**Comment by nucleogenesis** [comment]
I have gone through and tested on several tablet/mobile views in BrowserStack and it looks and feels great. 

One thought I had is that as a mobile (small screen) user that I'd have the ability to select a specific question to view like you can in the larger views.

Perhaps the "Question X of Y" portion could be in its own section of the page above the portion that displays the exercise. Then that could display "Question X of Y ↓" and when clicked, display a dropdown list of all questions by number to allow the user to select a specific question.

**Comment by indirectlylit** [comment]
> Perhaps the "Question X of Y" portion could be in its own section of the page above the portion that displays the exercise. Then that could display "Question X of Y ↓" and when clicked, display a dropdown list of all questions by number to allow the user to select a specific question.

that's a great idea. I believe some version of that is being considered for a future iteration - @jtamiace @khangmach this is like what Ana is working on, no?

**Comment by jtamiace** [comment]
Yep she has several different design ideas exploring the show/hide question list approach

**Pull request merged**
