### PR TITLE
Fix incomplete progress bar

### PR DESCRIPTION
**Pull request by lyw07**
### Summary

This PR is to fix the issue that the size of the source file is smaller than the file size indicated in the database, which means the source file is corrupted. In the github issue #4014, the contentnode that is imported has three local files. The first local file doesn't exist, so it is skipped. The second local file exists, so it is successfully imported. The third local file exists in the disk but has file size `0`, so nothing is added to the progress bar, which caused the error that the progress bar didn't reach 100%. 
The fix is to skip the corrupted files like this, by directly adding the file sizes to the progress bar and not actually importing the files. 

### Reviewer guidance

The data to test is here: https://slack-files.com/T0KT5DC58-FBNQ0K9QB-b27524fe7d
1. put the data folder into an external drive and try to import the entire channel `Lebanon LE Training` from the external drive.
2. check whether the progress bar reached 100%.
3. note that since the channel only contains one content node, and this content node is not successfully imported, the channel will not show up in the imported channel list even after the progress bar reached 100%.

I also updated some error messages. Please feel free to let me know if you think the wording could be improved. Thank you!

### References

#4014 

----

### Contributor Checklist

- [X] Contributor has fully tested the PR manually
- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by lyw07** [comment]
tests are failing. I will fix them soon

**Comment by rtibbles** [comment]
Tested, works. Might be a bit misleading for the user in this particular test case (it showing success but nothing importing), but this fixes the issue!

**Review by rtibbles — APPROVED** [review]
Works, and is about as good as we can do until we can do more granular reporting of task progress.

**Comment by lyw07** [comment]
@rtibbles thank you! Yes I agree that it's very misleading to users. I guess it would be better if it fails as 0%? But in this case, we might need to update the progress not per local file but per content node?

**Pull request merged**
