### PR TITLE
Theme updates feature branch (for 0.15.3)

### PR DESCRIPTION
**Pull request by indirectlylit**
## Summary

Feature branch for theme-related updates that would be safer to release in our first patch to avoid blocking 0.15.0 or introducing regressions.

## References

See references below description

## Reviewer guidance

After 0.15.0 is released we should begin testing this and preparing for 0.15.1.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by marcellamaki** [comment]
@indirectlylit -- thanks for preparing this, it looks great. I have reviewed the code and would like to see if we can do some manual QA and get this into an upcoming patch. Do you have a suggestion of how to do some testing? Thank you!

**Comment by indirectlylit** [comment]
Hey @marcellamaki!

There should not be any user-facing changes here, so some simple sanity checks checking theming behavior should suffice. In particular, I would double check that Kolibri looks right with both the default theme and at least one of the other partner theme plugins applied.

More importantly, this PR adds two new functions, `validateObject` and `objectWithDefaults`, which bring Vue prop-like validation and default behavior to nested javascript objects. This can be used with component props, vuex and API validation, and other scenarios.

see:
* https://github.com/learningequality/kolibri/pull/8902
* https://github.com/learningequality/kolibri/issues/8640

This new functionality could be worth sharing with the team.

**Comment by pcenov** [comment]
@radinamatic the only issue I was able to identify is that the info sidebar is now displayed to the left of the screen instead of being displayed to the right but I'm not sure if it's caused by this PR so posting it here as FYI. The issue is observed in all supported browsers.
Info sidebar:


Folder resources sidebar:

**Review by rtibbles — COMMENTED** [review]
Overall this makes sense - the main question for me is whether the validation is going to actually ever be used, as the theme object is rarely changed in the development environment?

**Comment by indirectlylit** [comment]
The main goal was to help engineers creating new themes by strictly defining the theme API

**Comment by pcenov** [comment]
@rtibbles had another look at this using the following [build](https://buildkite.com/learningequality/kolibri-debian/builds/4166) and the issues mentioned above are fixed. No new issues observed.

**Review by radinamatic — APPROVED** [review]
Manual QA by @pcenov was successful, good to go! 👍🏽

**Pull request merged**
