### PR TITLE
height = width in import cards on thumbnail, fix misaligned text

### LINKED ISSUE #7751: Import from Kolibri Studio page - one of the channel cards is not horizontally aligned with all the others
### Observed behavior

On the Import from Kolibri Studio page one of the channel cards (Citoyennes de la Terre) is not horizontally aligned with all the others. Padding-left needs increase to align it with all the other channel cards.

channelsAlignment

### Expected behavior

All channel cards on the import from Kolibri Studio page have to be aligned correctly on the page.

### Steps to reproduce
1. Login to Kolibri LP
2. Click the Import button
3. Select Kolibri Studio (online)
4. Click Continue
5. Scroll down a bit to see the "Citoyennes de la Terre" channel card

### Context
Kolibri 0.14.6rc1
Windows 7 vm
Firefox 84.0.2 (32-bit)
IE 11.0.9600
Chrome (latest)

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Summary

Fixed issue with text not being aligned on cards during content import with @AllanOXDi 

There was not a width set, and our images are not forced to any particular aspect ratio by Studio (yet?) -- so we set a width there so the images all have an equal space to sit into.

image

…

## References

Fixes #7751 

## Reviewer guidance

Try to import from Studio on 0.15.x and see the misaligned images as noted in the linked issue.
- Checkout the release-v0.15.x branch locally and run the server
- Log in as your Super User account
- Go to the Device section (you should go there on login)
- Go to Import content, select Studio as the source
- See the cards listed out there, are they aligned as noted in the linked issue?

Then, checkout this branch/asset and see that the text and images are aligned.

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

### CODE REVIEW

**Review by marcellamaki — COMMENTED** [review]
lgtm, holding off on approval and merge until we tag 0.15.7, but good to go

**Review by rtibbles — APPROVED** [review]
0.15.7 has been tagged. Merging this!

**Comment by pcenov** [comment]
Hi @nucleogenesis, this fix should be applied to the 'Export channels' and 'Delete channels' modals as well:



cc @radinamatic

**Comment by marcellamaki** [comment]
@pcenov and @radinamatic  - I've filed a follow up PR https://github.com/learningequality/kolibri/pull/9764 since Jacob has been out

**Pull request merged**
