### PR TITLE
Adding support for Khmer, Chinese and Nepali languages

### PR DESCRIPTION
**Pull request by radinamatic**
### Summary
WIP - don't merge!

Khmer and Nepali load without issues:

Selection_434

Selection_435

Selecting Chinese for some reason does not work and it defaults to English :confused: 

zh

Could that be because I did not see the MO file for Chinese anywhere, despite commenting it in the `.gitignore` and running even the `make i18n-django-compilemessages`? 

### Reviewer guidance
Help me figure out where the MO files are...?

### References
…

----

### Contributor Checklist

PR process:

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jonboiser** [comment]
The django mo files got deleted again. I'll try to undo that and force push a new commit to this branch.

**Comment by jonboiser** [comment]
This might actually undo the issue with the WOFF files. The changes look similar to the #6802 PR

**Comment by indirectlylit** [comment]
just merged #6802

**Comment by radinamatic** [comment]
And we have a Chinese liftoff! 

Selection_438

Although I had to hack it a bit... [According to this](https://stackoverflow.com/a/40702450) the `intl_code` now needs to be `zh-hans` instead of simply `zh`, but after I changed it, the Webpack compilation errored out at the end:

```
Kolibri: Generated CSV messages file: kolibri.plugins.learn.app-messages.csv
Kolibri Build: Completed kolibri.plugins.facility.app bundle in 64.543s!
Kolibri: Generated CSV messages file: kolibri.plugins.facility.app-messages.csv
Kolibri Build: Completed kolibri.plugins.coach.app bundle in 67.091s!
Kolibri: Generated CSV messages file: kolibri.plugins.coach.app-messages.csv
Kolibri Build: Failed to compilekolibri.core.default_frontend bundle!
./kolibri/core/assets/src/utils/intl-locale-data.js
Module not found: Can't resolve 'intl/locale-data/jsonp/zh-HANS.js' in '/home/didivm/LE/kolibri/kolibri/core/assets/src/utils'
```
File name is actually `zh-Hans.js`, and I managed to make it work by manually correcting that in the lines [31 and 32](https://github.com/learningequality/kolibri/pull/6803/files#diff-985cad79e3fbe33a7cbf8b0d0654ee12R31) from `zh-HANS.js` to `zh-Hans.js`, to have the server start.

I guess the renaming logic used to produce the `intl-locale-data.js` gets confused with the locale name that has more than 2 characters in that second part, and [capitalizes them all](https://github.com/learningequality/kolibri/blob/develop/build_tools/i18n/intl_code_gen.js#L71). Since this is an auto-generated file, it will break every time someone runs the `make i18n-update...`, correct? Fixing that is out of my reach, and not even sure if we should try to fit it in the scope of this PR @jonboiser ?

**Comment by jonboiser** [comment]
Let's go ahead with this as long as the code in its current state works. I created an issue #6796 that collects different issues we found running the `make i18n` command around 0.13.2/3 so we can hopefully fix them in one go.

We just need to remember to do these manual fixes if we add another language in the short term.

**Comment by rtibbles** [comment]
Yeah, just capitalizing the second half is incorrect, so we should be doing the more nuanced processing here.

**Comment by mrpau-richard** [comment]
Chinese language tooltip display issue on IE11 Windows 7. 
temp

On Firefox and Chrome tooltip properly display.

**Comment by mrpau-richard** [comment]
Chinese language alignment issue on IE11 Windows 7.
Screen Shot 2020-04-24 at 12 26 37 PM

And this is the sample display on Chrome
temp1

**Comment by cpauya** [comment]
Initial results on Windows 10, did these:
* create and login users, import content, navigate content, change languages

Looks good over-all, except for these browser warnings/errors:

1. Edge v44.0 shows no issues so far except this warning:

    * `HTML1500: Tag cannot be self-closing. Use an explicit closing tag.`

2. Both Firefox v75.0 and Chrome v81.0 shows these issues:

    * `[WARN: kolibri/core/assets/src/utils/i18n.js] Could not load full font for 'zh-hans' i18n.js:242:14` -- sometimes this shows after the page was loaded, after about 18secs
    * `DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:8080/en/device/kolibri.plugins.coach.side_nav-0.13.3a0.dev0+git.4.gb2093cf2.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`


Firefox v75.0 errors and warnings

Screen Shot 2020-04-24 at 5 28 04 PM


Chrome v81.0 errors and warnings
Screen Shot 2020-04-24 at 5 34 07 PM


MS Edge v44.0 warnings
Screen Shot 2020-04-24 at 5 36 09 PM

VM Technical details from Kolibri Device Info page:
```
Version:           0.13.3a0.dev0+git.4.gb2093cf2
OS:                Windows-8-6.2.9200
Python:            3.4.3
Installer:         Windows
Server:            Kolibri internal server
Database:          C:\Users\IEUser\.kolibri\db.sqlite3
Device name:       MSEDGEWIN10
Free disk space:   48 GB
Server time:       Fri Apr 24 2020 02:50:26 GMT-0700 (Pacific Daylight Time)
Server timezone:   America/Los_Angeles
```

Weird: I am using a Win10 VM but it's showing Windows-8... for OS. 😸

**Comment by radinamatic** [comment]
I've tested the DEB on Ubuntu 16.04 and 18.04, and found no issues with display of Chinese characters on neither Firefox, nor Chrome. 

Given that the issues @mrpau-dev encountered on Windows in IE are not strictly related to font display (rather elements alignment and tooltips size/orientation), I think we should be good to merge this @jonboiser.

**Comment by radinamatic** [comment]
I just now remembered that we'll need to update Perseus too, so KA Chinese content and exercises can be properly displayed.

**Comment by indirectlylit** [comment]
PR will need to be updated per https://github.com/learningequality/kolibri/pull/6806/files#diff-0cf61197850bb54ce721468ec345d663

cc @rtibbles

**Comment by radinamatic** [comment]
Conflicts were too messy to warrant investing time to resolve, especially since we do not need KM and NP for now (translation server already has them, mea culpa :woman_facepalming: ), but just Chinese.
Closing in favor of #6820.

**Pull request closed without merging**
