### PR TITLE
ContentNodeViewset: Add content tags

### PR DESCRIPTION
**Pull request by manuq**
### Summary

Expose the tags to the frontent through the REST API.

### Reviewer guidance

- Add some tags to content using Kolibri Studio.
- Update the channel.
- Confirm that tags are passed to the frontend. For instance by adding a `{{ content.tags }}` to the `ContentPage.vue` component in the Learn plugin.

### References

…

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jonboiser** [comment]
Hi @manuq , this looks great! 

Would you mind adding a unit test to this test case (code snippet is one unit test in the `TestCase`) https://github.com/learningequality/kolibri/blob/e6964a4baecdc4809be89fd9322eeff609a1e7f1/kolibri/core/content/test/test_content_app.py#L543-L549

It could be named something like `test_contentnodes_return_tags` , etc. Set it up by

1. Creating a contentnode
2. Adding tags to it
3. Making a request to the `contentnode-detail` endpoint
4. Confirming that the tags are returned in the response payload.

**Comment by manuq** [comment]
> Hi @manuq , this looks great!
> 
> Would you mind adding a unit test to this test case (code snippet is one unit test in the `TestCase`)
> 
> https://github.com/learningequality/kolibri/blob/e6964a4baecdc4809be89fd9322eeff609a1e7f1/kolibri/core/content/test/test_content_app.py#L543-L549
> 
> It could be named something like `test_contentnodes_return_tags` , etc. Set it up by
> 
> 1. Creating a contentnode
> 2. Adding tags to it
> 3. Making a request to the `contentnode-detail` endpoint
> 4. Confirming that the tags are returned in the response payload.

Thanks for the request @jonboiser . Is taking me a bit to setup my local checkout for running the tests, but I will have the unit test soon.

**Comment by nucleogenesis** [comment]
@manuq  let us know if we can help you fix issues w/ your dev environment. 

I know I often forget to install the [testing dependencies while installing Python dependencies ](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#install-python-dependencies) `pip install -r requirements/test.txt`

**Comment by manuq** [comment]
> @manuq let us know if we can help you fix issues w/ your dev environment.
> 
> I know I often forget to install the [testing dependencies while installing Python dependencies ](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#install-python-dependencies) `pip install -r requirements/test.txt`

Thanks for offering! It was only a matter of time, I had a long weekend.

**Comment by manuq** [comment]
@jonboiser @nucleogenesis sorry for the amount of forced pushes. This is now ready for review.

**Review by rtibbles — APPROVED** [review]
I did some additional testing locally, and compared this implementation to one that does a direct annotation on the initial query. It seemed to produce no performance benefits, so the addiitonal query here seems fine to me!

**Comment by manuq** [comment]
> I did some additional testing locally, and compared this implementation to one that does a direct annotation on the initial query. It seemed to produce no performance benefits, so the addiitonal query here seems fine to me!

By additional query you mean this one? `for t in models.ContentTag.objects.filter( ... )` ? Thanks for comparing.

**Comment by rtibbles** [comment]
Yes - although I am now realizing I should have done it on a database with a larger set of imported content.

**Pull request merged**
