### PR TITLE
Compare file checksum with localfile id during content import

### PR DESCRIPTION
**Pull request by lyw07**
### Summary

This PR is to add checksum check, for content import so that content files will not be imported during content import if the checksum of the file is different from the original file (the localfile id in the database)

### Reviewer guidance

1. please check if all the tests pass
2. import one file from a channel through studio
3. export the file to USB
4. delete the channel on kolibri and stop kolibri
5. find the specific one in the storage folder and edit it so that it's different from the original content file
6. copy the content folder from the USB to <kolibri_home>
7. start kolibri again
8. find out the channel does not show up in the channel list but exists in the `api/content/channel/`

### References

https://github.com/learningequality/kolibri/pull/5419#issuecomment-487120782

----

### Contributor Checklist

PR process:

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [X] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [X] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
@lyw07 and I chatted about this, and because of the performance overhead this adds, decided this might be better done during the content import flow, than during annotation (the proportion of time it will take up will be much less in the import flow).

**Comment by lyw07** [comment]
I will squash the commits after approval, before merging.

**Review by rtibbles — APPROVED** [review]
Makes sense, and manual testing shows no breakage.

**Comment by rtibbles** [comment]
Did a squash merge by request.

**Pull request merged**
