### PR TITLE
updates to docs

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

* removes mentions of the 'master' branch
* adds some guidelines about PR merging processes

### Reviewer guidance

make sense?

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by nucleogenesis — APPROVED** [review]
Looks great!

**Comment by jonboiser** [comment]
I'm still seeing some references to master after grepping it. Like in 'noto_source.py':

https://github.com/learningequality/kolibri/blob/64c76323809c328034923413cbe35b74f4e78ca3/build_tools/i18n/noto_source.py#L179

**Comment by jonboiser** [comment]
There's a line in `if.sh` mentioning "master":

```
branches_to_always_test=( "master" "releases/*" )
```
Does that need to be updated?

**Comment by rtibbles** [comment]
I think we probably need to remove the conditional tests completely, as they are redundant with buildkite.

**Comment by indirectlylit** [comment]
Updated to remove reference to `master`. Will leave more drastic changes (e.g. removing conditional testing) to a separate PR

**Pull request merged**
