### PR TITLE
Optimize content port to 0.9

### PR DESCRIPTION
**Pull request by rtibbles**

### CODE REVIEW

**Comment by indirectlylit** [comment]
@lyw07 would you mind testing this?

**Comment by lyw07** [comment]
yes I will test this PR later today

**Comment by lyw07** [comment]
I'm getting the kolibri image when loading the recommend page
screen shot 2018-07-24 at 10 03 18 am


Console is showing this error:
screen shot 2018-07-24 at 10 04 40 am

**Review by lyw07 — APPROVED** [review]
Recommend page works now! :)

**Pull request merged**
