### PR TITLE
Align metadata dropdown order to the figma spec

### LINKED ISSUE #12057: Update the search select dropdowns for grade levels and accessibility options so they are in a consistent, correct order
## Observed behavior
In 0.16.x, the order in the dropdown menus in the Learn search/filter side panel is not to the original specification. 

|   |  Actual | Spec |
|---|---|---|
| Levels | Screenshot 2024-04-05 at 4 57 53 PM  | Screenshot 2024-04-05 at 5 00 49 PM |
| Accessibility | Screenshot 2024-04-05 at 5 00 39 PM | Screenshot 2024-04-05 at 5 03 31 PM |

## Expected behavior
The order should be aligned to the original hybrid learning specifications. (Note that some of the levels were changed - and separated into "categories" not just level). 

The ["resources needed" sort](https://github.com/learningequality/kolibri/blob/e3358a706c2c8302a88e83ac4701e9d6d896bc5a/kolibri/plugins/learn/assets/src/composables/useSearch.js#L42) can be used for reference.

## Steps to reproduce
In Learn, open the "levels" and "accessibility" options 

## Context
0.16.x +

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary

The list order for the accessibility, and (perhaps more relevantly) grade/level dropdown filters had never been implemented to spec. This creates a helper function to 

## References
Fixes #12057 

| before | after | reference | 
|---|---|---|
| image | Screenshot 2024-05-09 at 3 49 23 PM | image |
| image | Screenshot 2024-05-09 at 3 49 06 PM | image |

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by marcellamaki** [comment]
@pcenov @radinamatic this is ready for manual QA. please let me know if you need any additional details

**Review by rtibbles — COMMENTED** [review]
Code looks good, manual QA for merge!

**Comment by pcenov** [comment]
Hi @marcellamaki - LGTM - here's what I am seeing for both Level and Accessibility (having selected all possible options when I created the resources in Studio):



A note that in the Accessibility drop-down some of the options are always displayed truncated with ellipsis while in the spec the text goes on the next line.

Also on closer inspection I noticed that in all browsers the descenders of the letters (specifically the 'g's) are not fully visible - wondering whether that warrants filing a separate issue?

**Comment by marcellamaki** [comment]
Yes, @pcenov if you could file a follow up that includes both of those points, that would be fantastic! thank you

**Review by radinamatic — APPROVED** [review]
Follow up issues for non-regressions filed, this can is good to go! 👏🏽 💯 :shipit:

**Pull request merged**
