### PR TITLE
Import export

### PR DESCRIPTION
**Pull request by jonboiser**
1. Add channel contents info (file # and size) to grid
2. Added very basic time left estimate to 'task status'
3. Moved content import/export actions to own module
4. Moved channel grid to own vue component 'channels-grid.vue'
5. Implemented a 'deletion' feature, although it doesn't see to cleanup data from `./kolibri/contents`, just from DB.

screen shot 2017-04-20 at 2 14 30 pm
screen shot 2017-04-24 at 1 32 42 pm
screen shot 2017-04-24 at 1 33 12 pm

## Some issues

1. When client polls for Tasks, it has poor statistics for estimating time-left since it comes in the middle of an import/export. It would probably be better if time-left were computed on backend, since backend has the entire history (i.e. better statistics).
2. After cancelling an import, it will be restarted immediately for some reason. Sometimes takes cancelling it 3-4 times to get it to stop.
3. Querying DB for file information is expensive in terms of bandwidth, since it pulls the full file list. It might be better to have a custom endpoint that will aggregate file count/file size.
4. Channels are added to list before they are fully downloaded, while the design spec would have them appear after 100% complete with a green indicator.

### CODE REVIEW

**Comment by jamalex** [comment]
Current approach to Channel deletion will likely only delete the ChannelMetadata object; will also need to have it delete `*/content/databases/<channel_id>.sqlite`, otherwise it will rise like a zombie when the server is restarted. :)

**Comment by jamalex** [comment]
> When client polls for Tasks, it has poor statistics for estimating time-left since it comes in the middle of an import/export. It would probably be better if time-left were computed on backend, since backend has the entire history (i.e. better statistics).
`tqdm`, the lib we use for generating progress bars and progress stats, also does its own server-side estimation of task time remaining, but we don't currently pass that along -- @aronasorman, once he's returned, can help figure that piece out (he'll be tackling our task management backend more generally)

**Comment by indirectlylit** [comment]
Looks like there are a lot of unrelated commits in this PR. Mind merging `learningequality/develop` into `learningequality/import-export`? (you can push that directly since it's an unprotected feature branch)

**Comment by indirectlylit** [comment]
and thanks for keeping this in sync! we'll be able to get this into `develop` soon, once 0.4.0-beta1 is branched/tagged.

**Pull request merged**
