### PR TITLE
Remove spreadsheet generation

### LINKED ISSUE #5505: Integration Testing Spreadsheet Docker Implementation Improvements
### Things to resolve

The docker setup in #5313 introduces some things to be improved upon at a later time:
- extra requirements file used soley in docker containers
- some permissions reassignment issues that docker could handle for us
    - Improper use of a bind mount. I had avocated for it, but the approach changed and introduced the need for this permission change.
- Introduces potential security issues 
    - addition of a "secret" file directory to an env.list
    - multiple file copies between native machines and containers
- More-verbose-than-necessary environment variable copying
- Buildkite step was made multi-command

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* We are no longer using the generated QA spreadsheet, so this removes all the code associated with it.

## References
By removing the underlying code, it fixes #5505

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by radinamatic — APPROVED** [review]
Testing is managed and tracked through TQ platform, this is good to retire! 👍🏽

**Review by DXCanas — APPROVED** [review]
🙏🙏🙏🙏🙏

**Comment by DXCanas** [comment]
Excited about this, but is there any chance we can get this into the version branches we're maintaining?

**Comment by rtibbles** [comment]
> Excited about this, but is there any chance we can get this into the version branches we're maintaining?

Is there a strong need to backport it? Is it about being able to remove secrets that they might be depending on? Maybe we can just agree never to run it again, and you can remove the secrets and no one will know?

**Pull request merged**
