### PR TITLE
add 'needs help' info to progress bar

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

| before | after |
|--|--|
| image | image |

### Reviewer guidance

@khangmach @jtamiace thoughts?

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by jtamiace** [comment]
I guess this is a natural result since we decided to separate 'needs help' from 'in progress'... 

To me this doesn't feel as overwhelming or strange as it did in previous design mockups and iterations, and I think it's because the combination of text+icon and the visualized bar helps to explain and give each other context. To my eye it's also nicely scannable, but wondering if it would be good to make the red a bit "softer?" And also making the grey background a bit lighter to put more emphasis on the actual colors of progression?

**Comment by indirectlylit** [comment]
> it's because the combination of text+icon and the visualized bar helps to explain and give each other context

yeah that's what I was going for. I also played with the ordering a fair amount so it always goes

1. completed
2. started
3. needing help
4. not started

basically in order of "done-ness"

**Comment by khangmach** [comment]
Generally agree with what Jessica said. I think that ordering makes sense too

**Comment by indirectlylit** [comment]
> wondering if it would be good to make the red a bit "softer?"

yeah i'll try lowering it a bit. Started to feel kinda salmon/pink which didn't look great

**Review by khangmach — APPROVED** [review]

**Comment by indirectlylit** [comment]
follow-up issue on styling: https://github.com/learningequality/kolibri/issues/5077

**Pull request merged**
