### PR TITLE
Bump ifcfg to 0.21b1 for testing

### PR DESCRIPTION
**Pull request by benjaoming**
### Summary

There is an upstream change in ifcfg that can fix issues very likely to occur on localized non-English systems with `ifconfig`.

Need a confirmation if this environment update (LANG=C) works on Windows, since no one came up with a convincing "yes of course it does" :)

Test of python-ifcfg 0.21b1 to see if https://github.com/ftao/python-ifcfg/pull/48 and https://github.com/ftao/python-ifcfg/pull/47 works on Windows

### Reviewer guidance

Don't merge - let's just see if the Windows build works and wait for a stable release.

### References

Don't think we have any issues otherwise open about missing detection of IP addresses and such?

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by benjaoming** [comment]
@mrpau-dev @radinamatic do you have a Windows env to quickly judge if the build works? Just doing `kolibri start` and seeing a valid URL with the local IP address is enough.

**Comment by radinamatic** [comment]
Will do asap @benjaoming! :+1:

**Comment by radinamatic** [comment]
Running OK on Windows 7, should I test on Windows 10 too?

Win7 (new start)  Running  - Oracle VM VirtualBox_340

**Comment by benjaoming** [comment]
No, I think that this is sufficient :) Thanks!

**Comment by radinamatic** [comment]
Windows 10 looking good too!

Win10 (start)  Running  - Oracle VM VirtualBox_348

**Review by radinamatic — APPROVED** [review]
LGTM! :+1:

**Comment by benjaoming** [comment]
Ay :)

> Don't merge - let's just see if the Windows build works and wait for a stable release.

**Comment by indirectlylit** [comment]
whoops!

FYI, you can now make un-mergeable draft PRs: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by benjaoming** [comment]
Roger! Thanks, will use that new feature next time :)

**Pull request merged**
