### PR TITLE
Cherry-pick automated pre-release versioning fix from #3116 for 0.7.1

### PR DESCRIPTION
**Pull request by benjaoming**
### Summary

See #3116

### Reviewer guidance

Check out the artifacts of this PR for evidence?

### References

#3116

----

### Contributor Checklist

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] Contributor has fully tested the PR manually
- [x] Screenshots of any front-end changes are in the PR description
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by rtibbles** [comment]
The artifact names check out - it's an old code, but I was about to clear them.

**Comment by benjaoming** [comment]
Yup, seems neat..

image

**Comment by benjaoming** [comment]
Ah no, this isn't working properly with the VERSION file assertions...

```
  File "/home/benjamin/.pex/install/kolibri-0.7.1b1.dev_2_gfd48a7a-py2.py3-none-any.whl.fcaaab0b69dddadb91b233b14a273e50838aaae2/kolibri-0.7.1b1.dev_2_gfd48a7a-py2.py3-none-any.whl/kolibri/utils/version.py", line 356, in get_prerelease_version
    version_file_base
AssertionError: kolibri/VERSION file inconsistent with kolibri.__version__.
__version__ is: (0, 7, 1, 'alpha', 0), file says: 0.7.1b1.dev-2-gfd48a7a

0.7.1.dev0 should start with 0.7.1b1.dev-2-gfd48a7a
```

**Comment by benjaoming** [comment]
In order to keep up with best practice, I'll fix it in this PR and open another PR for documentation in `develop`.

**Comment by benjaoming** [comment]
Oh interesting! The above failure was because the `Version` object generated by `packaging.version.parse` didn't understand `0.7.1b1.dev-2-gfd48a7a`, so couldn't sort out a `base_version` (which is `0.7.1`) for the assertion.

But using the `+` notation to turn the latter part into a so-called "local" version component will make it work, and it makes sense for these builds, anyways:

The version would now become:

`0.7.1b1.dev+git-2-gfd48a7a`

**Comment by benjaoming** [comment]
@radinamatic this branch is now updated such that the Morango upgrade is included. If you could give a quick thumbs up on whether the Pex is working on a Debian-based system with `python3-cryptography` installed, that'd be great! I'll proceed to building and releasing the .deb afterwards.

**Comment by radinamatic** [comment]
@benjaoming Will do, as soon as PEX is ready! 👍

**Comment by radinamatic** [comment]
Drat, I tested the PEX from the previous failed build (it failed only on building EXE), do I need to test again? The first one run just fine on Ubuntu 16.04?

@benjaoming

**Comment by radinamatic** [comment]
Tested the new PEX as well, runnin' great on Ubuntu!

All ready for DEB building @benjaoming!!!!

**Pull request merged**
