### PR TITLE
Fixes #5566: Use fullscreen pseudo selector to avoid 0 height in resize event

### LINKED ISSUE #5566: entering and exiting full screen causes epub to become blank
### Observed behavior

entering and exiting full screen causes epub to become blank:

fullscreen

### Expected behavior

epub should render as normal

### User-facing consequences

user confusion

### Steps to reproduce

* open epub
* enter full-screen
* press 'escape'

epub will be blank

### Context

* 0.12.4 beta 4
* chrome
* mac

### PR DESCRIPTION
**Pull request by bjester**
### Summary

- Rely on `:fullscreen` which helps with order of operations when toggling between fullscreen, avoiding a computed height of 0 by epub.js which leads to blank document

screencast-localhost-8000-2019 05 29-12-58-42

### Reviewer guidance

- Open an EPUB, go fullscreen, and then exit fullscreen. Be sure to not have dev tools open as that can affect the appearance of this bug.
- I tested a bunch of browsers in Browserstack as well.

### References

https://github.com/learningequality/kolibri/issues/5566

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] ~If this is an important user-facing change, PR or related issue has a 'changelog' label~
- [ ] ~If this includes an internal dependency change, a link to the diff is provided~

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] ~Critical user journeys are covered by Gherkin stories~
- [ ] ~Critical and brittle code paths are covered by unit tests~

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jonboiser** [comment]
I'm noticing that in Safari, the controls (settings, search, and fullscreen button) disappear when in full-screen mode. Checking to see if this was extant before this.

**Comment by jonboiser** [comment]
> I'm noticing that in Safari, the controls (settings, search, and fullscreen button) disappear when in full-screen mode. Checking to see if this was extant before this.

Yeah, on release-v0.12.y HEAD, the controls appear in full-screen mode on Safari, but not on this branch.

**Comment by bjester** [comment]
@jonboiser Good catch! I'll take a look.

**Comment by bjester** [comment]
@jonboiser Wow, I renamed the class but forgot to change the styles. Not sure how this was working.

**Comment by bjester** [comment]
I just noticed the bottom bar is missing too.

**Comment by bjester** [comment]
@jonboiser Ready for re-review.

**Review by jonboiser — APPROVED** [review]
Looks good to me!

**Pull request merged**
