### PR TITLE
experiment - downgrade windows installer

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

downgrades windows installer to its state in 0.9.2:

https://github.com/learningequality/kolibri/pull/3930/files#diff-98fe30f219e4756715a0cf72bfe28da1

intended to help diagnose #3852

### Reviewer guidance

…

### References

…

----

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by mrpau-julius** [comment]
@indirectlylit In this PR,no error found or issues in both windows 7 and 10.

**Comment by indirectlylit** [comment]
super curious.

@mrpau-richard this seems to imply that one of these changes is causing the issue: https://github.com/learningequality/kolibri-installer-windows/compare/v1.1.2...v1.2.0

**Comment by radinamatic** [comment]
Tested on Windows 10, VM with 2GB RAM and a single core CPU, setup wizard has no issues. ([video, 17Mb](https://drive.google.com/open?id=14WBYGFVVtEjOacpiHhPVb_VpTyxjI585)).

**Comment by indirectlylit** [comment]
addressed in #3935

crazily, the reason things were breaking was [this change](https://github.com/learningequality/kolibri-installer-windows/compare/v1.1.2...v1.2.0#diff-03d5f197d7e34c30938a1baf6746d5daL187): switching from `http://127.0.0.1:8080/learn/#!/learn` to `http://127.0.0.1:8080/`

* It turned out that because the old URL included stuff after the `#` (which a browser normally wouldn't send), the server was responding with a `404`
* After we switched the new URL, the server responded with a `302` and activated middleware which hit the database by creating a session

In both cases, we were polling to see if the server was up. But after fixing the URL, it actually started weighing down the server enough to cause the DB locking.

Nice job @jamalex and @rtibbles on your debugging!

**Pull request closed without merging**
