### PR TITLE
Migrates the OSUser associated with a facility user when migrating users.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Migrates the OSUser associated with a local user when migrating them to a user imported from remote
* Should maintain os user based login for apps using the `get_os_user` capability

## References

…

## Reviewer guidance
* Run using the app integration testing script in a fresh KOLIBRI_HOME
* Open Kolibri using the special URL printed by the app integration script
* Use the 'on my own' workflow
* Go the user profile page
* Join a facility
* Logout
* Reopen Kolibri using the special URL
* Confirm that you are now logged in as the migrated user in the facility (and that it hasn't created a new user)

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by nucleogenesis — COMMENTED** [review]
How would I go about testing this? Code makes sense and sounds like a good idea anyway 😄

**Comment by rtibbles** [comment]
Probably the best way would be for me to rebase this on release, so you can test the 'on my own' setup wizard flow in the app context, then have you join a facility, and confirm that it still properly logs you in to your migrated user when accessing via the special URL.

**Review by jredrejo — APPROVED** [review]
It makes sense to me. Being inside the `try` block I don't see any problem having this code. Worst case scenario would be not having the `os_user` created.

**Comment by rtibbles** [comment]
The only problem is that I managed to encode a non-existent import... Thanks Copilot!

**Review by nucleogenesis — APPROVED** [review]
Tested and works as expected 👍🏻

**Comment by rtibbles** [comment]
Test failure is a known flaky test.

**Pull request merged**
