### PR TITLE
feat: docker hot reload

### LINKED ISSUE #11585: No hot reload for Docker development server
## Observed behavior

The docker deployment of kolibri did not specify a way for hot reloading on code changes.
There seems to exist `yarn run devserver-hot` but it has not been integrated with docker.

## Expected behavior

The `Makefile` should specify another command to start a live-edit development server (which utilizes `yarn run devserver-hot`.

## Notes

I've done some code changes (will open a PR soon) which try to fix this issue.

### PR DESCRIPTION
**Pull request by ThEditor**
## Summary

- Added `make docker-devserver-hot` inside `Makefile`
- Added `devhot.dockerfile`
- Implemented hot reloading for docker development server

## References

Closes #11585 

## Reviewer guidance

Setup kolibri using docker
- `make docker-build-base`
- `make docker-devserver-hot`

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by MisRob** [comment]
Hi @ThEditor, thanks for your contribution. We've got some refactor in progress https://github.com/learningequality/kolibri/pull/11443 and I am not sure how this will fit into it. I asked relevant folks for review, so let's see. cc @vkWeb

**Comment by vkWeb** [comment]
@ThEditor I really appreciate your initiative of looking into this and creating a pull request. We already have some work planned  on https://github.com/learningequality/kolibri/pull/11443 to overhaul our docker setup for development purposes. As I can see from this PR, you look pretty familiar with Makefile, dockerfile and I can observe your enthusiasm to solve this. 

We will love your help with https://github.com/learningequality/kolibri/pull/11443, so can you please email me on -- vivekmittalagrawal@gmail.com (we will schedule a google meet), we will together work to complete https://github.com/learningequality/kolibri/pull/11443. 

Closing this PR in favour of https://github.com/learningequality/kolibri/pull/11443.

**Comment by MisRob** [comment]
@vkWeb @ThEditor I also linked https://github.com/learningequality/kolibri/issues/11585 to @vkWeb's work in progress

**Comment by ThEditor** [comment]
@vkWeb I've sent you a mail, thanks.

**Pull request closed without merging**
