### PR TITLE
generate an overall progress bar for import/export channels

### LINKED ISSUE #1927: import/export progress bar can jump around with multiple channels
As indicated in https://github.com/learningequality/kolibri/issues/1882#issuecomment-319135695 the progress bar jumps around when multiple channels are being imported or exported. 

From a user's perspective, one would expect progress to reflect the cumulative progress of all channels in the pipeline.

### PR DESCRIPTION
**Pull request by lyw07**
## Summary
This PR is intended to fix #1927 and #2206 . It changes the structure of creating ProgressTrackers by creating only one ProgressTracker before importing/exporting in `api.py`. More specifically, for exporting, the channel and content sizes will be calculated first to be used as the total amount of data for the ProgressTracker. For importing, the channel's update_progress has been ignored so that users can't see the progress of importing channels. This is because content size will not be accessible until `importchannel` is finished. When importing multiple channels, this program will call`importchannel` first for all the channels to get the content metadata, calculate the size of content for all the channels, create an overall progressTracker for importing content and finally call `importcontent`.

### CODE REVIEW

**Comment by lyw07** [comment]
Travis failed because in the test scripts, the overall progressTracker is not included as a parameter, which is different from the new implementation.

**Comment by indirectlylit** [comment]
re-targeting this and associated issues to 0.7, since the change is fairly sizable

**Comment by indirectlylit** [comment]
> Travis failed because in the test scripts, the overall progressTracker is not included as a parameter, which is different from the new implementation. I'm not sure if I should change the test scripts to pass Travis or just leave it here for now.

@lyw07 yes, in general it's necessary to update tests to pass before merging in changes.

I @aronasorman should review your changes before you fix the tests though, so you don't waste effort if there's significant feedback.

**Comment by rtibbles** [comment]
I think I would prefer an approach that kept the current functionality, but added the optional `tracker` option that meant that `start_progress` did not need to be invoked.

Interested in your thoughts here @aronasorman

**Comment by rtibbles** [comment]
Superseded by other changes in content import and export.

**Pull request closed without merging**
