### PR TITLE
User Edit Updates

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

Mostly, covers case of Admin demotion of self. Rather than error or 400, users are logged out.

Resolves some role-manipulation-related bugs. Cleans up a previous bug fix.

I kind of want to add a test for some of these bugs, but feel like this should be merged first? @indirectlylit 

### Reviewer guidance

Test out some use cases from userEditModal. The ones I was tried (where I found the bug) were:
- Admin demoting self
    - to facility coach, class coach, and learner
- Admin demoting/promoting others
- Super admin demoting/promoting others

### References

- #4323
- #4160
- #4324
- #4211 

----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by mrpau-julius** [comment]
I tested this PR, in several time on windows 7 and 10. When I changed the role of Facility admin to Learner, it's automatically exit into login page. It's fixed the Issue #4160.

**Comment by indirectlylit** [comment]
Awesome, thanks!

@DXCanas would you mind updating our Gherkin stories to reflect the scenario in #4160

**Comment by DXCanas** [comment]
@indirectlylit I had been planning on submitting those in a separate PR, with all the "superuser" stuff updated. You think it's more appropriate here?

**Comment by indirectlylit** [comment]
gherkin stories are being addressed in #4358

**Review by indirectlylit — APPROVED** [review]
looks good!

**Pull request merged**
