### PR TITLE
Update of i18n names caused by automated 'node ./frontend_build/src/intl_code_gen.js' run

### PR DESCRIPTION
**Pull request by benjaoming**
### Summary

Opening up this to know if these upgrades are deliberate? They were auto-generated.

```
node ./frontend_build/src/intl_code_gen.js
```

on `release-v0.10x`

### Reviewer guidance

…

### References

…

----

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by rtibbles** [comment]
@indirectlylit had these files been modified by hand?

**Comment by benjaoming** [comment]
Also question here: I'm not sure if this potentially fixes anything? So I've scheduled it for 0.10.2 because it came up during language debugging and updates.

**Comment by rtibbles** [comment]
Hrm, these changes actually seem correct because `ka` is the language code for Georgian, not for Kannada, the latter we support, the former, we do not.

Also, this adds in the correct code for Burmese, so I think we should merge this.

**Review by rtibbles — APPROVED** [review]

**Comment by indirectlylit** [comment]
I'm not sure how it got into the state it did, but I did not modify the files by hand.

@benjaoming did you happen to check that Burmese and Kannada still work? If not I'll take a look soon

**Comment by benjaoming** [comment]
@indirectlylit nope, I was hoping someone would have answers :smile:

**Pull request merged**
