### PR TITLE
[DO NOT MERGE UNTIL 0.16.1] Fix Screen Flickering in Libarary page

### LINKED ISSUE #11838: Android app - Screen flickering at the Library page while scrolling down
## Observed behavior
This issue was initially reported as a comment to https://github.com/learningequality/kolibri/pull/11551 and was thought of as fixed, but I've found some other cases where it's not. Specifically it can be replicated when you are signed in as a Learner and there are some channels in your Library but there are no other libraries around you:

https://github.com/learningequality/kolibri/assets/79847249/8b07c1a1-798b-4b86-bcd9-1ba46cede163

Also happens when I am signed in as a Learner, there are no channels in my Library and there are some other libraries around me.

https://github.com/learningequality/kolibri/assets/79847249/3f6da8d6-fb41-4e5d-aeb2-96a8cbf8efc4

## Expected behavior

No flickering while exploring the Library

## Steps to reproduce the issue

1. Install the [latest Beta 13 Android app](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta13).
2. Follow the above mentioned scenarios.

## Usage Details
[Beta 13](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta13)
Ubuntu 22  - Chrome
Samsung Note 10 Lite, Android 13

### PR DESCRIPTION
**Pull request by iskipu**
## Summary

The issue got fixed after converting the margins into to padding.

https://github.com/learningequality/kolibri/assets/143542192/cf5f96b2-d534-4259-bb95-0d66d126df98

## References

fix #11838

## Reviewer guidance

…

----

### CODE REVIEW

**Comment by pcenov** [comment]
Hi @iskipu the [Android app](https://github.com/learningequality/kolibri/suites/20635584971/artifacts/1235499627) keeps force stopping when I launch it so there must be something wrong with the .apk build. Could you check why is this so?

**Comment by iskipu** [comment]
> Hi @iskipu the [Android app](https://github.com/learningequality/kolibri/suites/20635584971/artifacts/1235499627) keeps force stopping when I launch it so there must be something wrong with the .apk build. Could you check why is this so?

Hi @pcenov i checked few other apk builds from other PRs and they were not working too !!

**Comment by pcenov** [comment]
@rtibbles I need to test this in the Android app - could you please have a look and advise what needs to be done so that the app installer is not broken. Thanks!

**Comment by iskipu** [comment]
Hi @pcenov, @rtibbles had made a fix to the issue, so i rebased the commit and force pushed but not sure why kolibri build is failing any idea how to fix this ?

**Comment by rtibbles** [comment]
Not your fault, there's another [open PR](https://github.com/learningequality/kolibri/pull/11872) to fix this new issue! Never boring around here!

**Comment by iskipu** [comment]
> Not your fault, there's another [open PR](https://github.com/learningequality/kolibri/pull/11872) to fix this new issue! Never boring around here!

Oh Cool !! i was very confused why it was not working and also this is my first time trying git rebase so i was thinking i am doing something wrong :rofl: :rofl:

**Comment by MisRob** [comment]
Thanks @iskipu and @rtibbles. Seems builds are now working, @pcenov.

**Review by pcenov — APPROVED** [review]
Thank you @iskipu - I confirm that the flickering issue is fixed now!

**Comment by MisRob** [comment]
Hi @iskipu, thanks for the contribution and @pcenov for testing. I haven't noticed any issue related to the change from margin to padding so I think this is good. We will need to wait for merging though because we're about to release 0.16.0 but this change is planned for 0.16.1.

**Review by MisRob — APPROVED** [review]

**Comment by MisRob** [comment]
0.16.0 is out so we can merge

**Pull request merged**
