### PR TITLE
CSV Endpoint permissions and error handling

### LINKED ISSUE #8256: [Security] Tighten permissions for APIs that return files
## Observed behavior

The current behavior of `downloadcsvfile` API allows anonymous users to download the csv file. For example: https://kolibri-demo.learningequality.org/facility/api/downloadcsvfile/tmp11wsss.download/a3f606630690237bbe94fe2a1a850af4. 

After discussing this issue with @rtibbles we came to the conclusion that we should be tightening these specific API endpoints permissions. 

## Expected behavior

Anonymous users must not be allowed to download files like these.

## User-facing consequences

A major privacy issue for large organizations. 

## Steps to reproduce
1. Login as a superuser.
2. Fire up `exportuserstocsv` task.
3. From the `GET /api/tasks/tasks/` note down the `facility_id` and `filename`. 
4. Log out. Now we are anonymous. 
5. Build up the URL in expected format i.e. `<base_url>/facility/api/downloadcsvfile/<filename>/<facility_id>`.
6. Visit the URL.  

## Context
 * Kolibri version: https://kolibri-demo.learningequality.org
 * Operating system: Ubuntu 20.04
 * Browser: Chrome 91.0.4472.164 (Official Build) (64-bit)

### LINKED ISSUE #9656: Return 404 rather than 500 when facility does not exist in download CSV endpoints
Sentry Issue: [KOLIBRI-BACKEND-29Q](https://sentry.io/organizations/learningequality/issues/3305340239/?referrer=github_integration)

```
DoesNotExist: Facility matching query does not exist.
(1 additional frame(s) were not displayed)
...
  File "django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "kolibri/plugins/facility/views.py", line 30, in download_csv_file
    facility_name = Facility.objects.get(pk=facility_id).name
  File "django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 380, in get
    self.model._meta.object_name
```

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Consolidates 'download CSV' endpoints into the Facility plugin where they are used
* Moves exportlogsinfo endpoint into Facility plugin and expands remit to cover all exported CSV files
* Adds permissions checks and facility existence checks to both endpoints
* Adds permissions tests for the download CSV endpoint
* Updates the frontend to reference the single location for these endpoints and makes status checking consistent across session/summary log and user CSV exports

## References
Fixes #8256
Fixes #9656

## Reviewer guidance
Are the updates consistent in the frontend and backend?
Does the code refactoring seem suitable?

Note that this affects the Session/Summary Log and User Export CSV workflows and should be tested accordingly.

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [x] Critical user journeys are covered by Gherkin stories
- [x] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
@pcenov Cpuld you test this today? Thank you! 🙏🏽

**Comment by pcenov** [comment]
Tested with both Ubuntu and Windows assets and couldn't find any regressions in the export of the Session/Summary logs and import/export of users caused by the changes here. Everything is functioning correctly.
For some reason the 'Time of completion' column is not being populated in the Session logs but I can't remember whether it was not tracked somewhere else:

**Comment by rtibbles** [comment]
Hrm, I can fix this - there shouldn't be a `Completion timestamp` column on the SessionLog export, as the session log doesn't log a completion timestamp!

**Comment by rtibbles** [comment]
Updated to fix this hitherto unreported issue!

**Comment by pcenov** [comment]
Excellent - the 'Time of completion' column is removed now from the content session logs and everything else is functioning correctly.

**Review by radinamatic — APPROVED** [review]
Manual QA by @pcenov passed, good to go! 💯 :shipit:

**Review by jredrejo — APPROVED** [review]
I only have one doubt regarding the names of the exported files, they include the facility and the kind of log, but not a timestamp thus consecutive exports will replace previous files.I don't know if that's a conscious choice. If it's fine, if not, it should be considered.
Code looks good to me.

**Comment by rtibbles** [comment]
> but not a timestamp thus consecutive exports will replace previous files.I don't know if that's a conscious choice.

This was deliberate, in order to have a predictable filename (and therefore to be able to infer the name of the file only from the facility_id and the kind of exported CSV). If someone is using the management command they can still choose the output file name, so I think there's enough flexibility, whereas for the task use through the UI, we are only showing the most recently created file anyway, so overwriting is fine, I think.

**Comment by rtibbles** [comment]
Converting to draft to prevent merge until 0.15.7 has been released (as I cannot request changes on my own PR!)

**Pull request merged**
