### PR TITLE
Add support for captions for audio.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
Adds support for captions to audio playback

## Reviewer guidance
Test with the first audio file of the updated Kolibri QA channel

Screenshot from 2022-12-13 11-24-43

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
Both captions and transcript for audio files are looking gorgeous in Firefox on Ubuntu 😍 
@pcenov Could you confirm Chrome on Windows so we can approve and merge this? Thank you!

**Comment by pcenov** [comment]
@radinamatic I confirm - both captions and transcript for audio files are also looking gorgeous in Chrome on Windows! 😺

**Review by radinamatic — APPROVED** [review]
Manual QA passed, all ready to finally have the option to view captions for audio files!!! 😌 🥳

**Review by marcellamaki — APPROVED** [review]
👍 lgtm

**Pull request merged**
