### PR TITLE
Recent coach report

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Cherry pick of #2014 to attempt to fix issues related to #2088 uncaptured by #2354.

## TODO

- [X] Have tests been written for the new code?

### CODE REVIEW

**Comment by benjaoming** [comment]
The tests have been written and are passing... is it also manually verified that this indeed works?

I can't however, get the .pex file to work, neither with python 2.7 or 3.5.

```
ImportError: No module named 'kolibri.plugins.media_player'
```

Is this expected for the 0.4 release or did some kind of new issue sneak in?

**Comment by radinamatic** [comment]
I also thought that `media_player` was from 0.5 on... Did you try:

```
kolibri plugin kolibri.plugins.audio_mp3_render disable
kolibri plugin kolibri.plugins.video_mp4_render disable
kolibri plugin kolibri.plugins.media_player enable
```

...or would that mess something else up? :thinking:

**Comment by benjaoming** [comment]
`*doh*`

**Comment by benjaoming** [comment]
Tested this: If there is nothing in the database at all, "Recent Activity" is empty. If I solve something, it shows up correctly. If I back date the data in `contentsummarylog`, it disappears from the Recent Activity.

**Comment by benjaoming** [comment]
Nice work on this @rtibbles !

I propose we get someone to sign off on the final release after this is merged.

**Comment by rtibbles** [comment]
We need to add in the most recent Hindi translations - my plan was then to release a beta that could be tested by Nalanda, and then we can do a final release when we have confirmation of completeness!

**Pull request merged**
