### PR TITLE
Coach Docs!

### PR DESCRIPTION
**Pull request by radinamatic**
## Summary

Still WIP - (yet) more to come!

- [X] Recent tab
- [ ] Topic tab (still partial)

### CODE REVIEW

**Comment by radinamatic** [comment]
I'm so missing the inline help feature in KA Lite... :cry:

**Comment by indirectlylit** [comment]
Just a note - the design has changed fairly significantly since these docs were written

**Comment by indirectlylit** [comment]
(much of the text is still relevant, but the screenshots could probably be re-taken from the current mockups)

**Comment by radinamatic** [comment]
Thnx, it's in my pipeline for this week! :slightly_smiling_face:

**Comment by radinamatic** [comment]
Closing this in favor of #1412 which is ready for review!

**Pull request closed without merging**
