### PR TITLE
Build and upload our docs catalog files

### PR DESCRIPTION
**Pull request by aronasorman**
When we run `make makemessages`, not only do we build and upload interface strings, we now also include docs po files as well.

### CODE REVIEW

**Comment by aronasorman** [comment]
@rtibbles addressed your comment. Docs catalog files are now placed in a separate 'docs/' folder. Check it out here (in the `docs-po-files` crowdin branch): https://crowdin.com/project/kolibri/fil#

**Comment by rtibbles** [comment]
Seems to be some duplication going on now - everything is listed under the docs po files, and the others too....

**Comment by aronasorman** [comment]
Oh, that's the po files for my git branch! Once you merge it, I'll delete that and preserve master.

**Comment by rtibbles** [comment]
Ah, gotcha!

**Pull request merged**
