### PR TITLE
Only gzip and cache static file endpoint

### LINKED ISSUE #5109: Videos are not working on Safari 11.0.3
### Observed behavior
I can't play videos on Safari 11.0.3

screen shot 2019-02-20 at 5 28 16 pm

### Errors and logs

```
[Error] VIDEOJS: (4)
"ERROR:"
"(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)"
"The media could not be loaded, either because the server or network failed or because the format is not supported."
MediaError
	(anonymous function) (media_player_module-0.12.0b7.js:1:209326)
	error (media_player_module-0.12.0b7.js:1:435778)
	handleTechError_ (media_player_module-0.12.0b7.js:1:423419)
	dispatcher (media_player_module-0.12.0b7.js:1:222733)
[Error] Unhandled Promise Rejection: [object DOMError]
```

### Context

Tell us about your environment, including:
 * Kolibri version: 0.12-beta7
 * Operating system: macOS 11.13.3
 * Browser: Safari 11.0.3

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
Do gzipping and caching only on static files in cherrypy.

### Reviewer guidance
Do videos still work?

### References
Fixes #5109 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Review by ralphiee22 — APPROVED** [review]
Tested and videos work on safari.

**Comment by rtibbles** [comment]
cc @jredrejo I think this should properly set expires headers on the static files now. Wondering if we should also set them on the content endpoint too?

**Comment by rtibbles** [comment]
Updated to set expires headers on everything - but this will get overridden by any cache headers coming from Django (so this will only effect static and content).

**Comment by indirectlylit** [comment]
hallelujah

**Pull request merged**
