### PR TITLE
Informal facilities get 'Create an Account' button visible by default

### LINKED ISSUE #7505: Informal (aka "personal use") facilities should have "learners can sign up" default to true.
### Observed behavior

In the apps, the default workflow is the "Quick Setup" option (i.e. informal facility). Currently this setup has new user creation off by default, so no "Create an account" button appears unless the admin user turns it on in settings.

### Expected behavior

Since in the at-home case it may not be unusual for multiple family members to share a tablet or computer, and also it is unlikely for them to be familiar with facility management options like a facility admin would, we decided instead to change this default to true, so that creating a new account works out of the box.

### User-facing consequences

Multiple home users may think they need to share login / progress and not have individual progress tracking.

### PR DESCRIPTION
**Pull request by AdamStasiw**
### Summary

This is to fix #7505, such that facilities created with the "informal" settings will allow the creation of new learners by default. This way, when doing initial setup with the "Quick start" [approach](https://kolibri.readthedocs.io/en/latest/install/initial_setup.html), the admin doesn't need to activate this setting manually, and users will be able to create accounts by default.

Steps Taken:
1. Initialize the app with a fresh database
2. Create a new facility using "Quick start"
3. Logout of the resulting admin account
4. Observe the log-in landing page

Before:
Screen Shot 2020-10-09 at 5 51 11 PM

After:
Screen Shot 2020-10-09 at 6 16 30 PM

Clicking on "Create an Account" proceeds to the user creation page:
Screen Shot 2020-10-09 at 6 16 50 PM

I also modified the test_personal_setup_defaults test to account for this new default value. Running `pytest kolibri/core/device/test/test_api.py` completed successfully.

### Reviewer guidance

Since I'm brand new to the codebase (and this is actually my very first open source contribution ever!), I'm not sure if I should run other tests or if the CR tool runs them for me. To be safe, I ran `tox` and `pytest` to try running everything. I got mostly all successes, but then a collection of failures/errors before the tests started to hang on `discovery/test/test_connection_check.py` - though I tried again on the base `develop` branch without my changes, and got the exact same errors:

```
kolibri/core/content/test/test_import_export.py .........FFFFFF.F.FFFFFFEEEEEEEEEEE                                                                                                                                                  [ 50%]
kolibri/core/content/test/test_importability.py FF                                                                                                                                                                                   [ 50%]
kolibri/core/content/test/test_movedirectory.py FFFFFFF                                                                                                                                                                              [ 51%]
kolibri/core/content/test/test_redirectcontent.py EEEEEEEEEEEE                                                                                                                                                                       [ 51%]
kolibri/core/content/test/test_sqlalchemy_bridge.py ...........................                                                                                                                                                      [ 53%]
kolibri/core/content/test/test_upgrade.py FFFFFFFFFF                                                                                                                                                                                 [ 54%]
kolibri/core/content/test/test_zipcontent.py FFFFFFFFFFFFFFFFFFFFFFFFFF
```

Not sure if this is something I'm doing wrong in my local testing?  

### References

See #7505 for the original issue / motivation for the change

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone (I don't think I have the ability to add a milestone?)
- [ ] PR has 'needs review' or 'work-in-progress' label (Similarly, I couldn't find how to add a label to this Pull Request)
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [X] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [X] Contributor has fully tested the PR manually
- [X] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [X] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jonboiser** [comment]
Hi @AdamStasiw , thanks for this patch!

When running your tests using `pytest` or `make test`, does the suite pass? I generally don't expect all the environments in `tox` to work locally, and just worry if it passes on Travis (which it did here). So if the tests mostly pass with a simple `make test` command, that's good enough for me.

Also, this is a bit of internal process that isn't documented (yet) for community contributors like yourself, but issues with the `0.14.4` milestone need to be based on the `release-v0.14.x` branch. Issues with the `0.15.0` milestone would be based on the `develop` branch. What I'll do is merge this one to `develop` and cherry-pick it to the 0.14 branch so it gets into the next release!

**Review by jonboiser — APPROVED** [review]
Looks good, thank you!

**Comment by jonboiser** [comment]
@AdamStasiw If you're interested in a related issue, check out https://github.com/learningequality/kolibri/issues/7334 which is a fix to the Vue frontend code.

Basically, the problem is that when you click the "reset to default" button in the Facility Settings page, the "defaults" are not the ones chosen during setup. For example, if I set up my device using the quick setup (i.e. with the "personal/informal" preset) and then click the "reset to default" button later, the "shown download button with resources" setting gets unchecked).

**Comment by AdamStasiw** [comment]
Ah okay, awesome - thank you!

And I'm much more of a backend/Python developer than a frontend one, but I can give #7334 a look!

**Comment by jonboiser** [comment]
Actually, the fix to #7334 might be better handled on the backend. I'll add some notes to the issue.

**Pull request merged**
