### PR TITLE
Remote_Content frontend implementation

### LINKED ISSUE #8994: REMOTE_CONTENT option does not affect required storage at content import
## Observed behavior
When using the `REMOTE_CONTENT` option, the device plugin is not aware that this means that no local storage space is required in order to import content.

This means that on devices using this option, the amount of content that can be imported at one time will be artificially restricted.

## Expected behavior
Should be able to import any amount of content when `REMOTE_CONTENT` is set.

## User-facing consequences
Not able to provision servers effectively.

### PR DESCRIPTION
**Pull request by d0sadata**
## Summary

added a path to check if remote content is enabled, Thanks @rtibbles 
added checks for it to stop the disable of import buttons,
added check to hide free space available

## Screenshots
When Remote_Content is off, And file storage space is enough and not enough:
remote_off
remote_off_file_low

When Remote_Content is on, and file storage space is enough and not enough:
remote_on
remote_on_file_low

## References
@rtibbles Helped me with the python part, and linking it to the JS data ingestion point.
Resolves #8994

## Reviewer guidance
by using the Options.ini file to change REMOTE_CONTENT=TRUE or optimally by loading in remote content

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
Code looks good to me.

**Comment by pcenov** [comment]
Hi @d0sadata I tested this with both the Ubuntu and Windows builds and things are looking as described by you with the exception of a message about not enough space which is still being displayed after I've set `REMOTE_CONTENT = True` which I guess should also be removed:


A question for @rtibbles would be that since the imported content looks imported but it's actually not how can we test that we can interact with such remote content? Is this part of a separate PR?

**Comment by rtibbles** [comment]
> a message about not enough space which is still being displayed after I've set REMOTE_CONTENT = True which I guess should also be removed:

Looks like I missed this when going through this with you @d0sadata - I think this would be good to hide in this case too. I think this computed prop is what needs to be updated: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/device/assets/src/views/AvailableChannelsPage/index.vue#L237


@pcenov the ability to serve content from remote source is not built into Kolibri - it requires additional server configuration external to Kolibri at this point, so there's no way to test the content once imported.

**Review by rtibbles — APPROVED** [review]
This is the correct additional change to handle the other messaging!

**Comment by pcenov** [comment]
Retested and verified as fixed in the latest [build](https://buildkite.com/learningequality/kolibri-python-package/builds/5222).

**Pull request merged**
