### PR TITLE
kolibri-tools: Don’t delete all CSVs in the i18n target directory

### PR DESCRIPTION
**Pull request by pwithnall**
## Summary

When building a plugin which has multiple sub-packages, and wanting to extract translatable messages from all of them, it’s tempting to run a command like:
```
kolibri-tools i18n-extract-messages \
  --plugins kolibri_explore_plugin \
  --namespace package1 --searchPath ./packages/package1 \
  --namespace package2 --searchPath ./packages/package2 \
  …
```

This won’t work, however, as kolibri-tools is only designed to accept one `--namespace`/`--searchPath` pair.

So instead we run:
```
kolibri-tools i18n-extract-messages --plugins kolibri_explore_plugin &&
kolibri-tools i18n-extract-messages --namespace package1 --searchPath … &&
kolibri-tools i18n-extract-messages --namespace package2 --searchPath … &&
…
```

This works fine, aside from the fact that each `i18n-extract-messages` process unilaterally deletes *all* CSV files in the target directory, even ones it’s not going to write to. So only the CSV files from the final `i18n-extract-messages` invocation survive.

Fix that by limiting the deletion to only the files which `i18n-extract-messages` wants to write to.

## References

None

## Reviewer guidance

An alternative approach would be to modify `kolibri-tools` to support multiple `--namespace`/`--searchPath` pairs, and hence use the single (long) command to extract messages from all packages in one process. I didn’t do that as it would affect other `kolibri-tools` commands though (`--namespace`/`--searchPath` are used across multiple commands).

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pwithnall** [comment]
At Endless we probably want this on the 0.16.x branch if possible. I’ve targeted `develop` on the assumption that it could be backported. I can retarget it if you’d prefer to arrange things differently. Let me know!

**Comment by pwithnall** [comment]
Rebased on `release-v0.16.x`.

**Review by nucleogenesis — APPROVED** [review]
Looks great! Thanks for the improvement!

**Comment by pwithnall** [comment]
(I just pushed a small update to the commit message to re-trigger the github actions. No changes to the content of the branch.)

**Pull request merged**
