### PR TITLE
Allow licenses to be None.

### PR DESCRIPTION
**Pull request by jayoshih**
Topic nodes don't have licenses.

### CODE REVIEW

**Comment by jayoshih** [comment]
We add this, because some nodes (aka topics) can have no licenses! :hankey:

**Comment by jtamiace** [comment]
Merging because @aronasorman told me to

**Comment by aronasorman** [comment]
Hey! This clearly has @jayoshih's style all over it!

**Comment by 66eli77** [comment]
curious, why the IC test not run on this PR...

**Pull request merged**
