### PR TITLE
Fix #4242 epub location scrubber should update percentage as you move it 

### LINKED ISSUE #4242: epub location scrubber should update percentage as you move it
### Observed behavior

the progress percentage doesn't update until after you change it

image

### Expected behavior

I would expect the percentage to change as I move it so that I can see where I'm going

### User-facing consequences

harder to navigate to a particular location, e.g. "go to 56%"

### Context

develop

----

cc @christianmemije

### PR DESCRIPTION
**Pull request by Pursottam6003**
## Summary

From the above issue #4242  I have tried to update  the epub renderer slider by making some changes in the code `EpubRendererIndex.vue ` and `BottomBar.vue `

## References

https://kolibri-dev.readthedocs.io/en/develop/getting_started.html

## Reviewer guidance

**BEFORE**

[Screencast from 16-04-23 11:33:03 PM IST.webm](https://user-images.githubusercontent.com/81693090/232333726-6f37513b-98f0-4fa6-86a3-9c0b567f3895.webm)

**AFTER** 

Now its able to perform the operations smoothly and without unwanted jumps 

[Screencast from 16-04-23 11:34:54 PM IST.webm](https://user-images.githubusercontent.com/81693090/232333774-3fca079d-9fb7-48c1-8544-e4c9bd46aed9.webm)

----

## Testing checklist

- [X] Contributor has fully tested the PR manually
- [X] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by Pursottam6003** [comment]
Still Its failing one test case  :(

**Comment by Pursottam6003** [comment]
Hii @marcellamaki  @thanksameeelian  Could you please review this PR whenever you are free thanks

**Comment by marcellamaki** [comment]
Thanks @Pursottam6003 for the contribution here! We'll take a look. 

@pcenov and @radinamatic - would you have time next week for some manual QA on this? I think it would be good to review across a few different browsers just to be 👍

**Comment by Pursottam6003** [comment]
Hii @nucleogenesis I would be happy to get the code reviews from your side and please let me know if it needs certain modifications in the code 

Thank you :)

**Comment by pcenov** [comment]
Hi @Pursottam6003 and @marcellamaki - for some reason the Build Artefacts are missing and if I unblock the build asset from Buildkite when I try to move the slider I am getting the following error in the console: `Uncaught (in promise) Error: No Section Found` and it's not working correctly.

Video:

https://user-images.githubusercontent.com/79847249/235120245-2ffbf0c9-789d-4223-81c1-13fdcaf8deaf.mp4

**Comment by Pursottam6003** [comment]
Hii @pcenov I saw the video which you uploaded but I am not getting why the `Build Artefacts` are missing I have only made changes in `kolibri/plugins/epub_viewer/assets/src/views/BottomBar.vue` and `kolibri/plugins/epub_viewer/assets/src/views/EpubRendererIndex.vue`

Since i have made those changes i have edited the test file `kolibri/plugins/epub_viewer/assets/tests/BottomBar.spec.js` and its working perfectly on my laptop

Could you please provide me with the name of the resources that you have rendered  in the video I will also try to test that resource

**Comment by pcenov** [comment]
Hi @Pursottam6003 I was testing using the following [build](https://buildkite.com/organizations/learningequality/pipelines/kolibri-debian/builds/6596/jobs/0187959f-39ca-4351-9884-82316caa9a6a/artifacts/0187c74e-6ad0-4a1b-91a1-da515fbd0503).
And I was using the epub resources from the QA channel which can be imported with the following token: nakav-mafak

**Comment by marcellamaki** [comment]
Hi @Pursottam6003 - it's possible the build problem was on the github side. Can you [rebase](https://git-scm.com/docs/git-rebase) off of the lastest develop and force push? That might solve the problem and will re-run the build. Thank you!

**Comment by Pursottam6003** [comment]
> Hi @Pursottam6003 - it's possible the build problem was on the github side. Can you [rebase](https://git-scm.com/docs/git-rebase) off of the lastest develop and force push? That might solve the problem and will re-run the build. Thank you!

Done :) 
Thank you @marcellamaki

**Comment by Pursottam6003** [comment]
Hii @pcenov @nucleogenesis  could you please review it now  please let me know if it needs certain modifications

**Comment by nucleogenesis** [comment]
@Pursottam6003 Thanks for your work on this!

I'll give it a closer look Monday. At a quick glance it looks good so I look forward to testing this out next week!

**Comment by nucleogenesis** [comment]
@Pursottam6003 I ran into some issues during testing. It seems like the percentages are getting stuck and are acting a little bit wonky. It has been a long time since I worked on this code and with the rendition package so I'm at a loss on where the issue might be, specifically.

The percentage should reflect the position of the slider and how far into the book the user is. I hope the video helps.

https://user-images.githubusercontent.com/6356129/235410034-5b25c39b-b1b0-475a-837a-1e5d6039734d.mp4

**Comment by pcenov** [comment]
@Pursottam6003 unfortunately I can also confirm that the percentage indicator is incorrect. I am using the latest [deb asset](https://github.com/learningequality/kolibri/suites/12555307341/artifacts/670930540):

https://user-images.githubusercontent.com/79847249/235609250-84a1d6f1-9c19-4343-9a91-8563ffead65b.mp4

**Comment by Pursottam6003** [comment]
> @Pursottam6003 unfortunately I can also confirm that the percentage indicator is incorrect. I am using the latest [deb asset](https://github.com/learningequality/kolibri/suites/12555307341/artifacts/670930540):
> 
>  2023-05-02_10-38-51.mp4

I agree @pcenov @nucleogenesis  

Actually what I had done previously in the commit is I have changed the `sliderStep`  value to 1  and earlier we have `max `and `min `set to `0 `and `100 `but i have changed the `max `value as total no of pages present in the document

Since previously we have a floating issue regarding the percentage completed to resolve this issue I was calculating the percentage completed of documents by  `  this.percentComplete = location.end.percentage * 100;`

Since previously I have used the resources as `African Storybook Library (multiple languages)` there it was able to work correctly but it's not working fine in the epub document resources with `token: nakav-mafak`.

Maybe the issue is because I am unable to figure out how to get the total no of pages in the epub document

**Comment by nucleogenesis** [comment]
@Pursottam6003 
> Maybe the issue is because I am unable to figure out how to get the total no of pages in the epub document

This is what I recall being the issue I ran into a long while back when I took a whack at this problem. The ePub lib doesn't seem to reliably recalculate the number of pages as ePubs will "reflow" themselves whenever the screen or font size changes so the number of pages can change dynamically. I dug into it quite a bit but was ultimately unable to figure that part out.

This may require some more substantial changes to how our ePub renderer works altogether or we may consider identifying another library to manage the ePub if there is one available.
 
In any case, I appreciate all of your efforts on this, but unless you have a good bead on the solution to the problems discussed here, I think we'll need to close this and update #4242 to account for the work here

**Comment by Pursottam6003** [comment]
> @Pursottam6003
> 
> > Maybe the issue is because I am unable to figure out how to get the total no of pages in the epub document
> 
> This is what I recall being the issue I ran into a long while back whenhh  I took a whack at this problem. The ePub lib doesn't seem to reliably recalculate the number of pages as ePubs will "reflow" themselves whenever the screen or font size changes so the number of pages can change dynamically. I dug into it quite a bit but was ultimately unable to figure that part out.
> 
> This may require some more substantial changes to how our ePub renderer works altogether or we may consider identifying another library to manage the ePub if there is one available.
> 
> In any case, I appreciate all of your efforts on this, but unless you have a good bead on the solution to the problems discussed here, I think we'll need to close this and update #4242 to account for the work here

Ooh It's okay I will try next time to  solve this issue, maybe it needs a certain deep understanding of the epub renderer

**Comment by nucleogenesis** [comment]
@Pursottam6003 - if you're keen to give this another shot another time, let us know in #4242 - in the meantime I'll close this PR. 

Thanks again for all of your digging and work on this!

**Pull request closed without merging**
