### PR TITLE
Linting issue in no-console

### LINKED ISSUE #10208: Linting rules on `console.log` are missing
## Observed behavior

It appears, through code review, that linting isn't capturing `console.*` statements. 'We have the core logging library setup to allow deliberate logs to be left in.'

## Errors and logs

Observed https://github.com/learningequality/kolibri/pull/10206/files#r1128608156

## Expected behavior

Linting rules should test against the existence of `console.*` statements.

## User-facing consequences

Potential increased memory usage if logging objects(?)

### PR DESCRIPTION
**Pull request by thesujai**
## Summary

Inserted no-console in rules that will warn if a `conole.log` is left without exception(the exception would be to disable it by using `eslint-disable`)
…

## References

Fixes: #10208 
…

## Reviewers Guidance

If this is works, then i think a follow up would be to trace `console.log` from the code base

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
Interestingly, the WARN still gives an error in our linting, I think maybe we can just set this to ERROR instead, as we don't seem to differentiate.

To merge this, we will need to fix the linting here. For most cases, we should use the core logging library, for an example of how it should be used, see here: https://github.com/learningequality/kolibri/blob/dfe1a9dbee948586685764e7284f561d15397c3e/kolibri/core/assets/src/utils/navComponents.js#L4

We can use this in all cases, except for the `hashi` and `kolibri-tools` packages, where we should add the relevant ignore comment for now.

**Comment by thesujai** [comment]
> Interestingly, the WARN still gives an error in our linting, I think maybe we can just set this to ERROR instead, as we don't seem to differentiate.
> 
> To merge this, we will need to fix the linting here. For most cases, we should use the core logging library, for an example of how it should be used, see here:
> 
> https://github.com/learningequality/kolibri/blob/dfe1a9dbee948586685764e7284f561d15397c3e/kolibri/core/assets/src/utils/navComponents.js#L4
> 
> We can use this in all cases, except for the `hashi` and `kolibri-tools` packages, where we should add the relevant ignore comment for now.

Hello @rtibbles, Thank you for the review.
I will make the changes and let you know

**Comment by thesujai** [comment]
Hello 👋🏽 @rtibbles, I made the suggested changes. Please review once 
Read the docs are failing though 😕

**Comment by rtibbles** [comment]
Will review - don't worry about the read the docs build, this is not caused by your work, and has been fixed on the release branch!

**Review by rtibbles — APPROVED** [review]
Excellent work, thank you!

**Pull request merged**
