### PR TITLE
Removed box-shadow

### PR DESCRIPTION
**Pull request by whitzhu**
screen shot 2016-08-03 at 9 26 53 am
## Summary

*Short description*

## TODO

- [ ] Have tests been written for the new code?
- [ ] Has documentation been written/updated?
- [ ] New dependencies (if any) added to requirements file
- [ ] Add an entry to CHANGELOG.rst
- [ ] Add yourself it AUTHORS.rst if you don't appear there

## Reviewer guidance

*If you PR has a significant size, give the reviewer some helpful remarks*

## Issues addressed

List the issues solved or partly solved by the PR

## Documentation

If the PR has documentation, link the file here (either .rst in your repo or if built on Read The Docs)

## Screenshots (if appropriate)

They're nice. :)

### CODE REVIEW

**Comment by indirectlylit** [comment]
The goal with that shadow was to make clear to the user that the search pane is a modal overlay.

Do you guys think that cue is not necessary?

**Comment by 66eli77** [comment]
if we want to make it very clear that this is a different panel, another way is to change the search panel background color from the current default canvas color to something else, like turquoise :)

**Comment by indirectlylit** [comment]
image

**Comment by 66eli77** [comment]
I just stare at this image for 2 mins, so pleasing

**Comment by radinamatic** [comment]
Love the turquoise color, but staring at this just makes me dizzy... :anguished:

**Comment by indirectlylit** [comment]
After discussing with @whitzhu -

Her sense is that the shadow box does not convey the intended meaning taht the search pane is a modal overlay. Since it's not helping as a cue, we'll remove it

**Pull request merged**
