### PR TITLE
CSS Styling - adjusted position of page-wrapper so div sits flush wit…

### PR DESCRIPTION
**Pull request by whitzhu**
## Summary

*Short description*

Removed unwanted spacing.

screen shot 2016-07-08 at 12 25 36 pm

## TODO

- [ ] Have tests been written for the new code?
- [ ] Has documentation been written/updated?
- [ ] New dependencies (if any) added to requirements file
- [ ] Add an entry to CHANGELOG.rst
- [ ] Add yourself it AUTHORS.rst if you don't appear there

## Reviewer guidance

*If you PR has a significant size, give the reviewer some helpful remarks*

## Issues addressed

List the issues solved or partly solved by the PR

## Documentation

If the PR has documentation, link the file here (either .rst in your repo or if built on Read The Docs)

## Screenshots (if appropriate)

They're nice. :)

…h the browser window

### CODE REVIEW

**Comment by whitzhu** [comment]
Hey @indirectlylit , this is simple CSS update to remove unwanted spacing for the page-wrapper div.

**Comment by DXCanas** [comment]
Doesn't look like this is based off of the PR merged this morning? I think this was resolved on that. Also, if we do adopt Jeet (or any other type of gridding) we should be _really_ careful about where we use `absolute` positioning, since the width for everything is relative.

**Comment by indirectlylit** [comment]
yes, agreed @DXCanas

**Comment by indirectlylit** [comment]
btw here's a comparison of the change before and after merging into master - only difference I see is a slight left-hand margin change:

image

**Comment by indirectlylit** [comment]
whoops - I also merged without the latest grid change. In fact there's a conflict :)

**Comment by indirectlylit** [comment]
@DXCanas would be great if you could give us all a quick intro on proper use of the grid at some point. Tips like the one above aren't necessarily something we'll know intuitively.

**Comment by DXCanas** [comment]
@indirectlylit Yeah, definitely. I tracked down the source of the gap too, so I'll submit a PR in a few minutes. I'll be in in a while as well. I can meet with anyone who's available once in; when are you free? @whitzhu?

**Pull request closed without merging**
