### PR TITLE
adding Fulfulde Mbororoore (cameroon)

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

…

### Reviewer guidance

…

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by rtibbles** [comment]
Has something changed that we don't need to commit a mo file for languages unsupported by Django? (I see `nyn` still has a committed mo file, so am assuming we do need it?)

**Comment by radinamatic** [comment]
Nothing in the console while changing languages and at privacy info step in the setup wizard.

ubuntu 18 04 iso start running - oracle vm virtualbox_332

The first red I managed to bump into was while importing the KA Fulfulde channel, but nothing weird in the UI, and the import concluded correctly:

ubuntu 18 04 iso start running - oracle vm virtualbox_334
cc @ralphiee22 

KA on Kolibri in the _full Fulfulde flavor_... (it even rhymes :heart_eyes:)

ubuntu 18 04 iso start running - oracle vm virtualbox_335

Everything else was squeaky clean until one opens the actual exercise, but I guess that is because the Perseus plugin is still not built and released with the latest translations from Crowdin:

ubuntu 18 04 iso start running - oracle vm virtualbox_338


Some small hick-ups with blurred topic thumbnails can be seen here:

ubuntu 18 04 iso start running - oracle vm virtualbox_336
cc @jayoshih @ivanistheone

**Review by radinamatic — APPROVED** [review]
LGTM, perseus plugin needs a new release, but that's out of the scope for the present PR.

**Comment by indirectlylit** [comment]
> Has something changed that we don't need to commit a mo file for languages unsupported by Django? 

Not that I'm aware of. I did commit the .mo file as per the instructions though - https://github.com/learningequality/kolibri/pull/4703/files#diff-9beead18408f8cd16a576d9e7368e019

**Pull request merged**
