### PR TITLE
Move loading morango fixtures to kolibri

### PR DESCRIPTION
**Pull request by ralphiee22**
### Summary

Move the job of loading morango-specific fixtures to the calling application.

### Reviewer guidance

Start kolibri server, and ensure `morango_scopedefinition` is filled in the database.

### References

Attempts to address this issue.
https://github.com/learningequality/morango/issues/48

And in morango we reflect these changes.
https://github.com/learningequality/morango/pull/49

----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by indirectlylit** [comment]
@ralphiee22 this has milestone 0.9.1 but is targeted to `develop` - which one is correct?

**Comment by indirectlylit** [comment]
also, wouldn't this need a new version of morango? https://github.com/learningequality/kolibri/blob/develop/requirements/base.txt#L20

**Comment by rtibbles** [comment]
@ralphiee22 does this require a morango update?

**Comment by rtibbles** [comment]
And it is fine to call it twice?

**Pull request merged**
