### PR TITLE
Filters out empty nodes, add safety to breaking code

### PR DESCRIPTION
**Pull request by akolson**
## Summary

This pr ensures that the "Next in action" content loads correctly if a lesson has been deleted from the device but still referenced within the lesson by adding a check to filter out all deleted content(null contentnodes). Also a safety check has been added to a potion of code identified as potentially breaking
#### Before change
image

#### After change
image

## References

Fixes https://github.com/learningequality/kolibri/issues/9412

## Reviewer guidance

Please follow the instructions here as described by @radinamatic to [replicate](https://github.com/learningequality/kolibri/issues/9412#issuecomment-1221098515) an environment in which the bug occures and then proceed to test out the changes

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
Code changes look correct to me, but I have not manually tested. @radinamatic or @pcenov verify the fix?

**Comment by pcenov** [comment]
@radinamatic Tested and verified that https://github.com/learningequality/kolibri/issues/9412 is fixed now.
I'll just point out a that a lesson with removed resources is always displayed as in progress regardless of the fact that as a learner I've completed all of the available resources - perhaps it should be further discussed what is the expected outcome in that case.

**Comment by radinamatic** [comment]
> lesson with removed resources is always displayed as in progress regardless of the fact that as a learner I've completed all of the available resources

Good point @pcenov , we'll discuss it with @jtamiace 👍🏽

**Review by radinamatic — APPROVED** [review]
Manual QA by @pcenov confirms the fix, we can merge and work on the progress state in a separate PR after all UX considerations.

**Pull request merged**
