### PR TITLE
changed KResponsiveWindow to useKResponsiveWindow in Pdf Viewer plugin

### PR DESCRIPTION
**Pull request by ShivangRawat30**
## Summary

This PR changes the `KResponsiveWindow` to `useKResponsiveWindow` in Pdf Viewer plugin

## References

#11328 

## Reviewer guidance

…

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by thanksameeelian** [comment]
thanks for this, @ShivangRawat30! i can confirm the code looks correct. 

just a couple steps before it can be officially approved & merged:
- please merge in the latest `develop` into your branch, it should resolve the failing tests/conflicts 🙂
- once that has been done & tests are passing, i will tag QA & ask them to confirm accurate page responsiveness in the PDF viewer now that the composable is in use.

**Comment by MisRob** [comment]
Hi @ShivangRawat30, can we help here somehow?

**Comment by MisRob** [comment]
Failing tests should be resolved after develop is merged

**Comment by ShivangRawat30** [comment]
@MisRob I will look into it, I wasn't active because of my exams.

**Comment by MisRob** [comment]
Okay, take all the time you need and good luck with exams. Thanks for letting us know.

**Pull request closed without merging**
