### PR TITLE
remove text and increase size of spinner

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

 based on feedback from @khangmach 

> Let's remove the 'searching' text indicator. Just the loader should suffice as an indicator. Hehe..

| before | after |
|--|--|
|||

### Reviewer guidance

any issues?

### References

https://www.notion.so/learningequality/0-13-0-bug-bash-3-7eeb57a21dd14aaa8f672dca9981f3f9?p=4f7b5269d2104f1c8e4d7d78ed6e126d

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by micahscopes — APPROVED** [review]
Looks good!

**Comment by khangmach** [comment]
Possible to keep the loader the same size it was before?

**Comment by indirectlylit** [comment]
sure, it's easy - it just looked a little "dinky" to me :) do you prefer this more subtle version?

**Comment by khangmach** [comment]
yup! perfect

**Review by khangmach — APPROVED** [review]

**Comment by indirectlylit** [comment]
updated

**Comment by rtibbles** [comment]
Test failure is due to unpinned black issue - no Python was harmed in the making of this PR, so merging anyway.

**Pull request merged**
