### PR TITLE
Update Python version at the build_windows dockerfile

### PR DESCRIPTION
**Pull request by mrpau-richard**
### Summary
I updated the Python version at the windows build dockerfile 

### Reviewer guidance
Test the Windows installer built in this PR from the BuildKite.

### References

…

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by cpauya** [comment]
Looking good so far! Will review a while then approve this to get it merged.
Screen Shot 2020-06-17 at 3 32 38 PM

**Comment by cpauya** [comment]
@mrpau-richard Can you take a look why it's still extracting `python-setup\python-3.4.3.msi`?
Screen Shot 2020-06-17 at 3 38 28 PM

**Comment by cpauya** [comment]
Python 3.4.3 packages are still included in the installer.  

Let's remove them @mrpau-richard and this is good to go! 😸 
Screen Shot 2020-06-17 at 3 44 47 PM

**Comment by cpauya** [comment]
Can you also update this `Makefile`? https://github.com/learningequality/kolibri-installer-windows/blob/v1.4.0-beta1/src/Makefile#L2 - I assume it's the one downloading those `python-3.4.3.*` files.

**Comment by mrpau-richard** [comment]
> Can you also update this Makefile? https://github.com/learningequality/kolibri-installer-windows/blob/v1.4.0-beta1/src/Makefile#L2 - I assume it's the one downloading those python-3.4.3.* files.

Thanks @cpauya ,  I'll create another beta release for that changes in the Windows installer repo.

**Comment by cpauya** [comment]
For Reference, this fixes this issue: https://github.com/learningequality/kolibri-installer-windows/issues/171

**Comment by cpauya** [comment]
> > Can you also update this Makefile? https://github.com/learningequality/kolibri-installer-windows/blob/v1.4.0-beta1/src/Makefile#L2 - I assume it's the one downloading those python-3.4.3.* files.
> 
> Thanks @cpauya , I'll create another beta release for that changes in the Windows installer repo.

Nope, it should be changed in this PR to prevent downloading python packages twice.  

That `Makefile` is being called via the `make` command here https://github.com/learningequality/kolibri/pull/7072/files#diff-6a804582ce0ce188519a48b7721c5da9R37 - It's the script downloading those `python-3.4.3.*` files as per BuildKite logs: https://buildkite.com/learningequality/kolibri-python-package/builds/1131#93e2bb69-0530-4703-bc9b-111af5e5173a/163-220

And then the `curl` command gets called next which downloads the `python-3.6.8.*` files.

I think doing either of this will work fine:

1. You can make the changes to `python-3.6.8` in the `Makefile` and remove the `curl` commands;
1. Comment-out (let's not remove them yet) the `wget` commands in the `Makefile`.

Please check.

**Comment by cpauya** [comment]
Ah, I see you already made changes at https://github.com/learningequality/kolibri-installer-windows/pull/172/files -- please ignore my message above then. 😸

**Comment by mrpau-richard** [comment]
> Ah, I see you already made changes at https://github.com/learningequality/kolibri-installer-windows/pull/172/files -- please ignore my message above then. 

Yeah, I already made the v1.4.0-beta2 , Please test the next Windows installer built in this PR.

**Comment by mrpau-julius** [comment]
@mrpau-richard, @cpauya is right. We missed to change the Makefile. The python version are still in 3.4.3. It's just need to change to version 3.6.8 to make it work. Make.bat is use to local build only.

**Comment by cpauya** [comment]
@mrpau-richard You did not update the checksum values of the `python-3.6.8-*.exe` files - BuildKite is failing https://buildkite.com/learningequality/kolibri-python-package/builds/1132#f1c50507-48cf-4c63-85c6-1f6ec2b41674/164-1481
Screen Shot 2020-06-17 at 4 51 26 PM

The checksums are here: https://www.python.org/downloads/release/python-368/

**Comment by cpauya** [comment]
The artifact on [latest build at BuildKite for this PR](https://buildkite.com/learningequality/kolibri-python-package/builds/1136) now works!  We can now merge this to get the fixes into the `release-v0.14.x` branch.
Screen Shot 2020-06-17 at 6 42 22 PM

Thanks @mrpau-richard!

/cc: @radinamatic

**Review by cpauya — APPROVED** [review]
All good! Artifact from BuildKite tested on local Windows7 VM.

**Comment by cpauya** [comment]
And just to double-check, there's no more `python-3.4.3-*` files included in the package. 😸 
Screen Shot 2020-06-17 at 6 48 05 PM

**Pull request merged**
