### PR TITLE
UI cleanup of side panel 

### PR DESCRIPTION
**Pull request by ShivangRawat30**
## Summary

Did the UI cleanup of resource duration in Content Renderer side panel

before
266347589-b53df362-292a-46db-8f7c-21b39187c521

after
266353269-fdbe0345-ef47-477b-9af2-a9600cbb0939

## References

#11206 

## Reviewer guidance

…

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by AllanOXDi — APPROVED** [review]
LGTM! waiting for manual QA and we proceed to merge.

**Review by pcenov — APPROVED** [review]
Thank you @ShivangRawat30, this is implemented correctly as specified!

**Comment by rtibbles** [comment]
@pcenov before we merge this, could you test this specific fix on IE11? It's possible that the use of `min-height` for the item might trigger a bug in flex-direction: column that happens in IE11.

**Comment by pcenov** [comment]
Hi @rtibbles thank you for suggesting that, indeed in IE11 there is alaways a small white rectangle displayed after the name of the resource:

**Comment by rtibbles** [comment]
I think this is an acceptable degradation in IE11 - not worth blocking for.

**Pull request merged**
