### PR TITLE
Fix on my own merge account KCheckbox issue

### LINKED ISSUE #12758: On my own - Merge accounts - The checkmark for the 'I understand the consequences...' checkbox is not displayed
## Observed behavior
While merging my account the checkmark for the 'I understand the consequences of merging accounts' checkbox is not being displayed. The user is still able to enable the 'Continue' button by clicking on the checkbox. Here's a video of that:

https://github.com/user-attachments/assets/5ea42d8d-e3c4-4c23-8a2d-e777663f7c4c

## Expected behavior

The checkmark should be displayed.

## Steps to reproduce the issue

1. Install the [latest 0.17.3-beta0 build asset](https://github.com/learningequality/kolibri/releases/tag/v0.17.3-beta0).
2. Go through the 'On my own' setup flow.
3. Go to Profile > Change > Merge accounts

## Usage Details
[0.17.3-beta0](https://github.com/learningequality/kolibri/releases/tag/v0.17.3-beta0)
Ubuntu 22  - Chrome

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Summary
Fix merge account KCheckbox issue

image

## References

Closes #12758

## Reviewer guidance

Follow instructions in #12758

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
Checkbox now has the checkmark! 👏🏽 

This has nothing to do with the present PR, but why is the user redirected to _Select/Change facility_ again after signing in with the new credentials after the merge (1:48 in the video below) ? 🫤 


https://github.com/user-attachments/assets/1e598983-37a9-4e9f-92a0-b435813ea4ad

**Comment by rtibbles** [comment]
Hrm, not entirely clear why it's doing that, it doesn't seem like it's meant to! https://github.com/learningequality/kolibri/blob/3b49acb9f9f7105241c118f342fc54a880c4b3fe/kolibri/plugins/user_profile/assets/src/views/ChangeFacility/MergeFacility.vue#L285

**Comment by rtibbles** [comment]
Oh, it rather looks like the logging in as the new user is not happening properly, so instead, Kolibri thinks the user's authentication has timed out, and so they are redirected to the auth page (with the next redirect to send them back to where they were).

**Review by radinamatic — APPROVED** [review]
LGTM, good to go! 💯 :shipit:

**Review by rtibbles — APPROVED** [review]
I think I understand what is happening in the code here :)

**Comment by emily-dominguez** [comment]
> Oh, it rather looks like the logging in as the new user is not happening properly, so instead, Kolibri thinks the user's authentication has timed out, and so they are redirected to the auth page (with the next redirect to send them back to where they were).

hey @rtibbles! I'm working on this issue, and I was wondering  if I could get some help understanding the flow, so it seems like a user successfully mergers an account in the file confrimMerge.vue where does this request/path get sent to? is it suppose to call the LoginMergedUserViewset(APIView)? but it's not doing so?

**Pull request merged**
