### PR TITLE
Remove facilitydataset bootstrap directive from user.html

### LINKED ISSUE #5547: Facility settings change for guest access not reflected on sign-in page
### Observed behavior
Changing the facility settings seems to have inconsistent results on the sign-in page: sometimes it does not reflect correctly until the cache is cleared several times, the UI language is changed, or another setting is checked/unchecked.

facility-settings

In the above recording, after the `Allow users to access content without signing in` option has been unchecked, the `Explore without account` link remains on the sign-in page even after several reloads with the cache cleared. It only disappears once another option is changed, and sign-in page reloaded. Furthermore, when subsequently checked again, to try to re-allow guest access, the link does not reappear after reloads until the UI language is changed.

### Expected behavior
Facility settings change should have immediate and consistent results.

### User-facing consequences
Unclear functionality and inability to configure the facility access according to specific needs.

### Errors and logs
Nothing overt in the console

[server.log](https://github.com/learningequality/kolibri/files/3217288/server.log)
[kolibri.log](https://github.com/learningequality/kolibri/files/3217289/kolibri.log)

### Steps to reproduce
Try changing the facility settings for guest and simplified sign-in access, and observe the results on the user sign-in page.

### Context

 * Kolibri version: 0.12.4b3
 * Operating system: Ubuntu 16.04
 * Browser: Chrome & Firefox

### LINKED ISSUE #5594: Facility settings - allow learners and coaches to edit their username - does not work.
### Observed behavior
This is really weird behavior.  Under the `Facility settings` page, I've checked the `allow learners and coaches to edit their username` as a super admin user.

Tested on iPad 2 simulator-Safari 9.3 and on macOS - both Chrome 74.0.xxx and Safari 12.1.1

The `username` was shown as editable (textbox) on first attempt - but after I was successful at changing, logging-out then logging-in again - now it does not show the textbox. I have refreshed the browser using `Cmd+R` to reload.

This behaviour also manifests the other way around.  When setting is unchecked, then the textbox on the client browser is still shown even after logging-out or reloading the page.

**NOTE: But after about 4 minutes that I haven't touched the browsers, then come back to them and reload the page, the correct behaviour is shown.**  Are we using some timer of some sort for the correct behaviour to propagate to the client browsers?

I have attached a `.gif` to supplement this weird behaviour.  
kolibri--v0 12 4b4--facility-settings--allow learners and coaches to edit their username

### Expected behavior
If the setting is checked, the user can change username via textbox.  If unchecked, the user is shown only the username but cannot change it.

### User-facing consequences
If setting does not work, super admin user must manually change username per user. 

### Errors and logs
N/A

### Steps to reproduce
1. Login as super admin then check the `allow learners and coaches to edit their username` setting under the `Facility settings` page.  Logout.
1. Login as learner, go to the Profile page, then edit the username, save, then logout.
1. Login as super admin, then uncheck the setting. Logout.
1. Login as learner, go to the Profile page, then notice the username cannot be edited, logout.
1. Login as super admin, then check the setting to enable. Logout.
1. Login as learner, go to the Profile page, then notice the username still cannot be edited.

You may have to reload the page for the settings to take effect.  But after it is enabled back, the textbox will not re-appear anymore on the learner account.

### Context
Tell us about your environment, including:
 * Kolibri version: 0.12.4-beta4
 * Operating system: server=Ubuntu 18.04 vm
 * Browsers: Safari 12.1.1 and Chrome 74.0.xxx both under macOS 10.14.5, Safari 9.3 under iPad 2 on iOS 9.3 simulator

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

Removes the FacilityDataset bootstrapping optimization from `user.html`, which is the Django template used for all User pages including Sign In and the Profile page.

This change should fix the problems seen in #5547 and #5594 

### Reviewer guidance

Use the Buildkite-generated PEX file to test this, since I have not been able to see the problems described when running Kolibri from the devserver.

### References

Fixes #5547 
Fixes #5594

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jonboiser** [comment]
Uh oh, this is already a dud. If you uncheck "Allow users to access...", the Sign In page doesn't load and you get a bunch of errors.

Screen Shot 2019-05-31 at 11 13 39 AM

**Comment by jonboiser** [comment]
But the editting username/fullname setting is being reflected right away :+1:

**Comment by rtibbles** [comment]
I think my fix for #5519 may well resolve this further issue.

**Comment by jonboiser** [comment]
Okay, I'll rebase on #5519 once that's in and try again.

**Comment by rtibbles** [comment]
Testing my fix for #5519 needs this PR, so I am going to merge it.

**Review by rtibbles — APPROVED** [review]

**Pull request merged**
