### PR TITLE
Perseus bump

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

BUMPING PERSEUS

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If there are any front-end changes, before/after screenshots are included
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by radinamatic** [comment]
Downloading this one to test!

**Comment by lyw07** [comment]
@radinamatic Thank you!! Could you please let me know if it works so I can merge this PR?

**Comment by radinamatic** [comment]
Installing now @lyw07, will report back asap! 👍

**Comment by radinamatic** [comment]
Looking good @lyw07 🎉 

virtualbox_winps_28_03_2018_20_08_01

virtualbox_winps_28_03_2018_20_19_50

virtualbox_winps_28_03_2018_20_20_29

virtualbox_winps_28_03_2018_20_21_19

**Comment by lyw07** [comment]
@radinamatic Thank you for testing! Going to merge this PR now

**Comment by indirectlylit** [comment]
great job all

**Pull request merged**
