### PR TITLE
Remove FocusTrap in favor of KFocusTrap

### PR DESCRIPTION
**Pull request by lokesh-sagi125**
## Summary
I removed all instances of ' FocusTrap ' that were wrapping ' KModal ', as the focus trapping logic is now handled internally within the KModal component. Additionally, I renamed all remaining FocusTrap instances to KFocusTrap, and finally, I deleted the FocusTrap.vue file since it is no longer necessary. These updates ensure focus trapping is handled consistently throughout the system without causing any regressions.

…

## References

 * #12588 
 * https://github.com/learningequality/kolibri-design-system/pull/799

### CODE REVIEW

**Comment by MisRob** [comment]
Thank you, @lokesh-sagi125. Is this ready for review? If so, would you please fill in the PR description and also linked the issue this is resolving? It will help reviewers.

**Comment by MisRob** [comment]
Note related KDS PR https://github.com/learningequality/kolibri-design-system/pull/799. This PR can be merged after a new KDS release with that change is installed in Kolibri.

**Comment by MisRob** [comment]
I am not entirely sure why would the automatic lint affect another files [in this commit](https://github.com/learningequality/kolibri/pull/12718/commits/4e15663d3002ea1b898c3254ceceacd0a49eeeaf), but perhaps it's not an issue. @rtibbles may have an idea perhaps.

**Comment by MisRob** [comment]
Thanks for getting the PR description ready @lokesh-sagi125. I think this can be reviewed cc @akolson @nucleogenesis @LianaHarris360.

**Review by akolson — DISMISSED** [review]
The changes look correct to me but will review this more extensively once https://github.com/learningequality/kolibri-design-system/pull/799 has been approved and released. I suspect the failing tests are to do with it. Thanks @lokesh-sagi125

**Comment by AlexVelezLl** [comment]
Hey @lokesh-sagi125! We just released the changes made in https://github.com/learningequality/kolibri-design-system/pull/799, and updated the KDS version in develop with the new release. You can now rebase this PR on top of develop, and run `yarn install` to fetch the new KDS version :hugs:

**Comment by lokesh-sagi125** [comment]
yes @AlexVelezLl  will do.

**Review by nucleogenesis — DISMISSED** [review]
The updates of FocusTrap -> KFocusTrap look good to me, but there's some misc file changes that look like they might be related to your rebase and/or some linting (ie, reordering of imports, update to .gitignore).

I thought at first it might be related to the automatic linting CI bot that automatically added the commits to your PR but that doesn't appear to be the case.

I think you may need to `git fetch --all` and `git rebase upstream/develop` (assuming that `git remote -v` shows `upstream` pointing to the `learningequality` repository -- use whichever remote you have pointing to our repo). 

If you don't have our repository setup in your remotes: `git remote add upstream https:/github.com/learningequality/kolibri.git` then `git fetch upstream` will get you the latest `develop` locally, then you can run the `git rebase upstream/develop` and observe and correct any conflicts that come up.

Please let me know if you have any questions or, if you're a part of our Slack community feel free to reach out in our #dev-community channel for some more direct help

**Review by rtibbles — APPROVED** [review]
As long as tests and linting pass, this should be good to go.

**Pull request merged**
