### PR TITLE
Prevent excessive completion modals

### LINKED ISSUE #9824: The completion modal keeps reappearing when viewing already completed resources
## Observed behavior
While testing https://github.com/learningequality/kolibri/pull/9814 I noticed that the completion modal keeps reappearing when viewing already completed resources. for some resources such as PDF once the completion is displayed it seemingly cannot be closed as hitting the x icon or 'Stay here' results in the modal being immediately displayed again. Valid in all supported browsers.
For resources of type exercise the completion modal is correctly displayed only once.
This issue is not being observed in the beta build without the KDS updates.

## Expected behavior
The completion modal should be displayed only once after having completed a resource.

## Steps to reproduce the issue
1. Install the the latest [beta build ](https://github.com/learningequality/kolibri/releases/tag/v0.15.9-beta1) with the KDS updates
2. Complete a resource and then attempt to view the resource again.

## Videos
PDF:

https://user-images.githubusercontent.com/79847249/201088498-9b73fad9-9592-4ea0-afff-dd42cab956b3.mp4

Video:

https://user-images.githubusercontent.com/79847249/201088536-4851fe73-ab33-4fe2-b1c3-4ce4ff2630b1.mp4

EPUB:

https://user-images.githubusercontent.com/79847249/201088676-456f4ac6-5d2a-43e7-b19d-eb5c6bbd3849.mp4

## Usage Details
Windows 10, Ubuntu - Chrome

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Reverts a previous change that caused completion modals to pop up whenever a user finished a piece of content, and not just on first completion
* Adds a next steps button which will reopen the completion modal
* Add an animation (which gets turned off for users with a reduced motion setting) which emphasizes the next steps button when a finish event is fired again
* Ensures the completion modal is shown when a learner marks a resource as complete

## References
Fixes https://github.com/learningequality/kolibri/issues/9825
Fixes #9824
Fixes https://github.com/learningequality/kolibri/issues/9840

This was discussed with @jtamiace before implementation

## Reviewer guidance
Does this resolve the issue above? Does the new button function as intended? Is the cleanup of the action bar logic in the learning activity bar sensible?

Will this be easy to migrate into develop across the refactor?

[Screencast from 11-10-2022 05:18:18 PM.webm](https://user-images.githubusercontent.com/1680573/201239976-fff85bf4-df32-48a1-86d6-78fe69b21f70.webm)

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by marcellamaki — COMMENTED** [review]
The button does work as expected to reopen the modal after the content has already been completed once. I personally am not a "bounce" person as I find those sorts of user hints confusing, but I know they are common and defer to Jessica's judgement 😄 

I don't have any specific concerns about this and the `develop` refactors, because not much has changed in the content page as far as I can recall. While there might be some adjustments needed, I don't think it will be a major issue. 

One thing I do want to flag is that @nucleogenesis should take a look and make sure that this aligns okay with his fix for the follow up comment that Peter left: https://github.com/learningequality/kolibri/pull/9808#issuecomment-1308996513. I don't think, based on looking at the code, that the approaches are really getting in the way of each other. Just maybe some merge conflicts that will need to be sorted out.

**Comment by rtibbles** [comment]
> I personally am not a "bounce" person as I find those sorts of user hints confusing

We did experiment with a 'pulse' but doing the box-shadow colour consistent with the dynamic theme would require css variables, or some quite involved javascript hackery of the keyframes.

**Comment by rtibbles** [comment]
Updated to include completion modal display for mark as complete. Addresses delay issue noted in https://github.com/learningequality/kolibri/pull/9828#pullrequestreview-1179252716

[Screencast from 11-14-2022 11:30:41 AM.webm](https://user-images.githubusercontent.com/1680573/201757578-cf55c294-88b2-4683-96d7-e73505784278.webm)

**Comment by pcenov** [comment]
@rtibbles The completion modal gets displayed correctly now after completing a resource or marking is as 'complete' however I was able to identify some additional issues and inconsistencies.

Not signed in user:
1. When I am exploring the Library without being signed in and I click the 'Mark resource as complete' button for an audio/video resource the completion modal gets displayed, however if I press the pause button I see an error screen. Also the star icon never appear next to the title of the resource or the library card:

https://user-images.githubusercontent.com/79847249/201961630-adcd67a7-436f-477c-a419-8c146a219400.mp4

```
{
  "data": [
    {
      "id": "MAX_VALUE",
      "metadata": {
        "field": "progress_delta",
        "message": "Ensure this value is less than or equal to 1.0."
      }
    }
  ],
  "status": 400,
  "statusText": "Bad Request",
  "headers": {
    "allow": "PUT, OPTIONS",
    "content-length": "118",
    "content-type": "application/json",
    "date": "Tue, 15 Nov 2022 15:34:13 GMT",
    "server": "Cheroot/unknown",
    "vary": "Accept, Cookie",
    "x-content-type-options": "nosniff",
    "x-frame-options": "SAMEORIGIN"
  },
  "config": {
    "url": "/api/logger/trackprogress/fe3ff2b2a69788f1588f643220937c87/",
    "method": "put",
    "data": "{\"progress_delta\":1.262,\"time_spent_delta\":12.407}",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json;charset=utf-8",
      "X-Requested-With": "XMLHttpRequest",
      "X-CSRFToken": "V28Oo23f0F5WquE1ILvtD1bMT0jFZoo1YkFeb7ASXxzNpNj6kA8kboN64QcixCdr"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "kolibri_csrftoken",
    "xsrfHeaderName": "X-CSRFToken",
    "maxContentLength": -1
  },
  "request": {}
}
```
https://user-images.githubusercontent.com/79847249/201964229-61a8a78f-7dd3-481b-8eae-b72490515e09.mp4

2. For the other resources it appears that after completing a resource it is marked correctly as completed, however if I simply refresh the page the completion is lost. For the exercises the completion icon is never displayed in the library card..

https://user-images.githubusercontent.com/79847249/201964025-c761e1a3-5536-4626-9006-cac950bc52ed.mp4

Signed in user:

1. The newly added 'Next steps' icon is confusing, as when clicked it shows again the resource completion modal with the +500 points message. In that case it would be better to no longer show the number of earned points.
2. There's a delay before the 'In progress' icon gets changed to the star icon. This can be somewhat confusing.

https://user-images.githubusercontent.com/79847249/201966538-93e58082-387f-4e4f-8e03-bf6f8667d526.mp4

The above mentioned issues can be replicated by importing the following channel: bujir-japir

**Comment by rtibbles** [comment]
I had also seen the API error you note in testing, will be fixing here.

The signed out behaviour you describe is expected - if you refresh the page, we lose any record of your previous interactions, as you're not signed in. We could attempt to rectify this in future, but for now this is intended behaviour.

Hiding the points for subsequent displays makes sense.

Seems like we might need to do a more optimistic update of the client side to ensure the completion status is registered earlier.

**Comment by rtibbles** [comment]
OK, all the above noted issues should be resolved, and the added next steps icon also 'resolves' the issue raised in https://github.com/learningequality/kolibri/pull/9808#issuecomment-1308996513 because it never reduces the number of icons.

**Comment by pcenov** [comment]
Excellent @rtibbles all of the previously reported issues are resolved now. I have reported separately the following issue: https://github.com/learningequality/kolibri/issues/9840

**Comment by rtibbles** [comment]
Should also fix https://github.com/learningequality/kolibri/issues/9840 too now, @pcenov .

**Review by nucleogenesis — APPROVED** [review]
Code review LGTM.

**Comment by pcenov** [comment]
@rtibbles happy to report that indeed that fixes https://github.com/learningequality/kolibri/issues/9840!
I have reported separately the disabled bookmarks icon issue here: https://github.com/learningequality/kolibri/issues/9864

**Pull request merged**
