### PR TITLE
Fix selected users count

### LINKED ISSUE #9632: Select all users - Incorrect value for the number of selected users
## Observed behavior
Selecting and deselecting the 'Select all' button after selecting or deselecting a specific user results in incorrect number of users displayed as selected. This is valid for both Facility > Class > Enroll learners and Facility > Class > Assign coaches
This results in minor confusion.

## Steps to reproduce the issue
1. Install the latest 0.16 develop build
2. Go to Facility > Class > Enroll learners or Facility > Class > Assign coaches
3. Select the 'Select all' checkbox and observe the number of the selected users
4. Deselect some of the users and after that select again the 'Select all' checkbox - note that the number of selected users is no longer correct

## Video
https://user-images.githubusercontent.com/79847249/185088853-011d8b9f-0f61-4709-911d-1e16f3ca7256.mp4

## Usage Details
Windows 10 and Ubuntu 20 - Chrome, Firefox, Edge

### PR DESCRIPTION
**Pull request by Kej-r03**
## Summary

Fixed Selected Users count error after reselecting all users.

https://user-images.githubusercontent.com/99071926/209391817-6161a530-09d1-4da3-a932-ffaa89ebca23.mp4

## References

Fixes #9632 

## Reviewer guidance

Go to Facility>Class>Enroll Learners or Facility>Class>Assign Coaches.
Select All the users, then deselect some of them and again select all users, the count displayed at the bottom shows correct value now.

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by Kej-r03** [comment]
hi @pcenov, it would be great if you can review the request

**Comment by pcenov** [comment]
@Kej-r03 thank you for your contribution! Manual testing confirms that the issue is fixed now.
cc @radinamatic

**Review by radinamatic — APPROVED** [review]
Manual QA passed, cc @marcellamaki or @MisRob for a code review!

**Review by akolson — COMMENTED** [review]
Hi @Kej-r03, your contribution is very much appreciated, LGTM. However this change breaks what seems to be a crucial test. @MisRob  is better placed to advise and provide context on this. cc @marcellamaki

**Comment by MisRob** [comment]
Yes, we need to preserve behavior that is described by the failing test. I'll have a look at it soon and try to provide some more guidance. Thank you for your contribution @Kej-r03.

**Review by MisRob — CHANGES_REQUESTED** [review]
The motivation behind keeping `...this.value` in the `input` event's payload that was removed in this PR was not to lose values in paginated contexts as described in the commit where it was first added https://github.com/learningequality/kolibri/commit/6a060ba (you can find this commit referenced above the test scenario that's failing but it seems it'd be better to comment on this on the line with implementation as it's not clear without having some historical context). Enrolling learners to a group as a coach is one place where it can be tested:

| `develop` before changes introduced by this PR | this PR |
| --- | --- |
| select-all-develop | select-all-pr |

cc @pcenov @radinamatic 

No problem to tweak `UserTable` component if it's the source of trouble but we will need to make sure that user selection is preserved when navigating between pages.

**Comment by MisRob** [comment]
@Kej-r03 Please let me know if you need some further assistance

**Comment by Kej-r03** [comment]
hi @MisRob I have rectified the change.
Now it only merges the non-duplicate values of currentUser with this.value, and also, on changing page, user selection is retained.

**Review by MisRob — APPROVED** [review]
Thank you, @Kej-r03, code is looking good to me, and the tests are passing. If you'd like to, please add your name to the list of contributors https://github.com/learningequality/kolibri/blob/develop/AUTHORS.md before we merge this

**Comment by pcenov** [comment]
Manual QA passes as well - this is implemented as specified and the issue mentioned by @MisRob is corrected now.

**Comment by rtibbles** [comment]
Merging now so we can cherry-pick this back to 0.15. @Kej-r03 please feel free to open a separate PR adding yourself to the AUTHORS.md. Otherwise I'll do it in the future.

**Pull request merged**
