### PR TITLE
WIP - Coach prompts strings updates

### PR DESCRIPTION
**Pull request by radinamatic**
### Summary

Adding the in-progress changes for user strings, plus a suggestion to eliminate tables (used for formatting, not tabular data, so table is not really kosher).

### Reviewer guidance
...

### References

[Reference doc & discussion](https://docs.google.com/document/d/1IapGxicJ4OM-_crQ31HGhe4-1R7hD_p8ELfvLTiq-Yc/edit).

----

### Contributor Checklist

PR process:

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
@indirectlylit I'm continuing off what you stubbed out in https://github.com/radinamatic/kolibri/pull/4, but apparently something is missing and the mock prompts page is not displaying:

LEDev20 04  Running  - Oracle VM VirtualBox_444

It's not a major impediment as I can continue, but it would be good to be able to see the prompt  strings again, if possible.

**Comment by radinamatic** [comment]
Apparently, Travis failed because of one single extra line at the end of the file...? :unamused: 

@indirectlylit All prompt strings are now in there, but before merging this (even if it does not get into 0.14), it would be good to be able to actually see the rendered page, to check the HTML structure and see if it passes the a11y pain points.

**Comment by radinamatic** [comment]
Just realized that I could add context to several of these strings, so putting back the WIP label!

**Review by indirectlylit — APPROVED** [review]
looking good!

**Comment by jonboiser** [comment]
I moved these commits to the `coach-prompts` branch, as a starting point for the full feature that should be in 0.14.1 or later.

**Comment by indirectlylit** [comment]
thank you

**Pull request closed without merging**
