### PR TITLE
I18n update - regenerated files

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

Download latest strings and regenerate all i18n files

### Reviewer guidance

Do all fonts work?

### References

This PR depends on #4427, which should be merged first (or closed in favor of this one)

----

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by benjaoming** [comment]
I made a review over in #4427

**Comment by benjaoming** [comment]
@indirectlylit does this PR contain several commits redoing font files? and what is the impact on repo size?

```
du -sh kolibri/core/static/assets/fonts
22M	kolibri/core/static/assets/fonts
```

If possible to save a few commits, please do so, this will lessen the repo's data footprint.

One way to achieve this:

```
git reset upstream/develop
git add .
git commit -m "Everything in one commit"
git push -f
```

**Comment by indirectlylit** [comment]
>  does this PR contain several commits redoing font files?

No, everything is in a8d4e7ecf75bb6c16c3320f524e3e3444ffdb825

All the other commits are part of #4427 which should be merged first

> what is the impact on repo size?

Agreed this is something we need to be careful about as we move forward. I'm open to ideas. In #4364 I suggested building the fonts during the make assets step, but then we still need to either download or check in lots of TTF files. Git LFS is another option.

**Comment by indirectlylit** [comment]
These fonts are getting much larger than I was hoping. I really wanted to expand our unicode support even more, but even as it stands all 22mb will go into the bundled dist size :/

Let's hold off merging this until we weight the costs & benefits

**Comment by indirectlylit** [comment]
Looks like size got so big in part because I'm base64-encoding the files and embedding them in CSS. This is fine for clients because it's gzipped in the response, but not great for distributing.

Thoughts on how to do this better @benjaoming @rtibbles? Maybe generate them dynamically on first request and cache the results?

**Comment by benjaoming** [comment]
Thanks for being large-minded by open a PR with lots of work and then closing it again @indirectlylit :1st_place_medal: 

> as it stands all 22mb will go into the bundled dist size :/

It would certainly be nice to improve this. Let's verify the difference of dist size and installed size at least. If they are embedded in CSS, they have a fair chance of being compressed?

```
du -sh dist/*
70M     dist/kolibri-0.10.3-py2.py3-none-any.whl
64M     dist/kolibri-0.10.3.tar.gz
```

This PR:

```
du -sh dist/*
81M     dist/kolibri-0.11.0b1.dev0+git.49.ga8d4e7ec-py2.py3-none-any.whl
75M     dist/kolibri-0.11.0b1.dev0+git.49.ga8d4e7ec.tar.gz
```

So +11 MB. The limit on PyPi was 100 MB (see: `https://github.com/pypa/packaging-problems/issues/116`).

**Comment by indirectlylit** [comment]
moving to #4461

**Comment by benjaoming** [comment]
@indirectlylit updated above comment ^

**Pull request closed without merging**
