### PR TITLE
Properly redirect on authentication failure

### LINKED ISSUE #11773: Quiz creation route not redirecting to user_auth on 401/403
## Overview

I've found when I step away from working on the quiz creation project that if my session has timed out then I just get a blank screen.

The expectation on a permissions error response is that we ship the user to the sign in page with a query param `next` which is set to the path that the user was trying to access.

Once the user signs in, they're redirected back to where they're trying to go in the first place.

## Guidance, Replication

This seems to occur in multiple places in Coach -- I've confirmed it during Lesson creation & Quiz creation.

- On `develop` branch
- Sign in as an admin/coach, navigate to the Coach > Class > Plan > Quizzes > New Quiz
- Go to your cookies in the devtools and delete the cookies, then quickly refresh the page (this emulates the session timeout situation consistently in my attempts)
- _The thing that really makes this a problem_ is that refreshing again and again results in the same blank page.

Look into [this part](https://github.com/learningequality/kolibri/blob/66589c69dd0c59c443acf33e54a062ff89af99d7/kolibri/plugins/learn/assets/src/app.js#L26-L41) of the Learn router for inspiration. We may consider adding something similar to the coach app's beforeEach router guard as well -- but note that we'll only really want to check if the user is logged in there.

This solution will not directly handle the 401 -- however, it will properly send the user to the AuthMessage, which they can then click to access the sign in page w/ the proper `?next` parameter

## Acceptance criteria

- [ ] Signing out due to inactivity doesn't result in being stuck on a blank page during Quiz Creation (or any other part of Coach)

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Reorder authentication classes for consistent dev and production errors.
* Check user_id not id for forbidden redirects.
* When redirecting a user because they were logged out, persist a next parameter to return them to the last page they were on before logout

## References
Fixes #11773

## Reviewer guidance
Delete your session cookie while on the quiz creation page, make sure you get properly redirected there and back again.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
This is now fixed in all steps of the quiz creation process, and it redirects properly upon session end (tested in Firefox on Ubuntu).


https://github.com/learningequality/kolibri/assets/1457929/77fcf185-81fc-402d-90ff-ea43ee259443

@pcenov Could you do some additional checks with Chrome on other coach user workflows? Thank you!

**Review by radinamatic — APPROVED** [review]
Quiz creation redirect when session ends is a go! 👏🏽 

Let's test redirects on some more coach workflows before we give a final approval 🙂

**Review by marcellamaki — COMMENTED** [review]
The code changes here seem correct to me, and my own manual QA when running the dev server did properly redirect me out of coach when doing quiz creation. 

I'll wait for some final checks from Peter though, per Radina's comment.

**Comment by pcenov** [comment]
Hi @marcellamaki - I noticed two possible follow-up issues if we want to dig deeper in this:

1. When my session has ended while I've been editing a quiz then I am brought back to the sign-in page where I can sign in as a learner user in which case I am redirected back to the quiz editing page and since I don't actually have permissions to see it I am getting a  blank screen:

https://github.com/learningequality/kolibri/assets/79847249/07833bde-a081-4851-8ee3-27d94dfd850e

2. If as a coach I've made some changes to the quiz without saving them, then when I sign in they are lost (which is fine in that case) however the contents of the first section are also not displayed until I click on the section tab, which can be confusing:

https://github.com/learningequality/kolibri/assets/79847249/ea21e02a-04cd-48c1-90d0-f1efb1856cdb

**Comment by rtibbles** [comment]
I think issue 2 has been independently resolved by @nucleogenesis elsewhere. Issue 1 can be filed as a follow up.

**Pull request merged**
