### PR TITLE
2 + 3 again

### PR DESCRIPTION
**Pull request by aronasorman**
Fixes the daemonization issue in https://github.com/learningequality/kolibri/issues/1786. We do this by making sure we only start the BBQ machinery when we actually start Django, not when we just load the tasks/api.py module.

Also fixes the python-2-and-python-3-from-a-single-pex issue.

### CODE REVIEW

**Comment by aronasorman** [comment]
@laurenlichtman thanks for checking the windows installer! It should be posted here once it's done building.

**Comment by rtibbles** [comment]
## Build Artifacts
**Kolibri Installers**
Windows Installer: [KolibriSetup-0.4.0.dev448.exe](https://www.googleapis.com/download/storage/v1/b/le-downloads/o/kolibri%2Fbuildkite%2Fbuild-1816%2F1687%2FKolibriSetup-0.4.0.dev448.exe?generation=1499729976738068&alt=media)

**Python packages**
Pex: [kolibri-v0.4.0-448-g21afa40.pex](https://www.googleapis.com/download/storage/v1/b/le-downloads/o/kolibri%2Fbuildkite%2Fbuild-1816%2F1687%2Fkolibri-v0.4.0-448-g21afa40.pex?generation=1499729945340026&alt=media)
Whl file: [kolibri-0.4.0.dev448-py2.py3-none-any.whl](https://www.googleapis.com/download/storage/v1/b/le-downloads/o/kolibri%2Fbuildkite%2Fbuild-1816%2F1687%2Fkolibri-0.4.0.dev448-py2.py3-none-any.whl?generation=1499729937431126&alt=media)
Zip file: [kolibri-0.4.0.dev448.zip](https://www.googleapis.com/download/storage/v1/b/le-downloads/o/kolibri%2Fbuildkite%2Fbuild-1816%2F1687%2Fkolibri-0.4.0.dev448.zip?generation=1499729959733105&alt=media)
Tar file: [kolibri-0.4.0.dev448.tar.gz](https://www.googleapis.com/download/storage/v1/b/le-downloads/o/kolibri%2Fbuildkite%2Fbuild-1816%2F1687%2Fkolibri-0.4.0.dev448.tar.gz?generation=1499729950938623&alt=media)

**Comment by rtibbles** [comment]
Daemon threading error in test.

**Comment by rtibbles** [comment]
Only occurred in one suite, so I imagine it is racy.

**Comment by radinamatic** [comment]
Tested both by usual start (`./kolibri-XXX.pex start`) and with Python 2 (`python2 kolibri-XXX.pex start`), and it's looking good @aronasorman :+1: 

Btw, @rtibbles, the [`undefined`](https://github.com/learningequality/kolibri/issues/1811) resurfaced... :unamused: 

ubuntu3 start running - oracle vm virtualbox_341

**Comment by aronasorman** [comment]
@rtibbles looks like a critical error. Based on some [googling](https://bugs.python.org/issue23309), looks like it might be caused by a thread exiting without releasing the stderr lock. The patch above makes sure it errors out properly and prints to the console.

**Comment by radinamatic** [comment]
Windows 7 looks good too, @aronasorman :+1: 

I think you can merge this, as soon as the test/checks permit!

**Comment by aronasorman** [comment]
Tried replicating it on my side, didn't work. I'll do a couple of fixes that might help, and then hope for the best.

**Comment by rtibbles** [comment]
Note that there is an open issue for this on pytest itself: https://github.com/pytest-dev/pytest/issues/1725

Does seem to be daemon thread related though!

**Comment by rtibbles** [comment]
All seems to boil down to the basic issue of ensuring a clean shutdown with daemon threads - and that seems to be the hard part!

**Comment by rtibbles** [comment]
@aronasorman I am going to merge this for now - could you open a separate issue for the test error seen here, and follow up with a potential fix?

**Pull request merged**
