### PR TITLE
add on-device resource information into channelmetadata

### PR DESCRIPTION
**Pull request by lyw07**
# Checklist

- [X] PR has the correct target milestone when it's merged
- [X] Automated test coverage is satisfactory
- [ ] PR has been fully tested manually
- [ ] Documentation is updated as necessary
- [ ] External dependency files are updated (`yarn` and `pip`)
- [ ] If internal dependency are updated, link to diff is included
- [ ] Screenshots of any front-end changes are in the PR description
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] You've added yourself to AUTHORS.rst if you're not there

# Details

### Summary

* description of the change

After discussing with @jonboiser , we think that it will be better to add on-device resource information (on_device_resources and on_device_file_size) into the ChannelMetadata endpoint so that when the `file_sizes` parameter is set to be True (or anything except False, as the code suggested), then the endpoint will return additional information `total_resources`, `total_file_size`, `on_device_resources` and `on_device_file_size`. 
 
* manual verification steps performed

1. Do `importchannel` through command line
2. open browser and type `/api/channel/?file_sizes=True to see total_resources and total_file_size. Note that on_device_resources and on_device_file_size should be zero.
3. Do `importcontent` through command line
4. open browser and type `/api/channel/?file_sizes=True to see that on_device resources and total_resources should be the same. Also, total_file_size should be the same as on_device_file_size.

### Reviewer guidance

Both Jonathan and me think that the parameter `file_sizes` may not be a good variable name for now, since it's now returning four different resource information. May need to find a new variable name for this.

### References

when applicable, please provide:

* links to mockups or specs for new features
Please see `Downloaded channel detail` and `Downloaded channel list` sections in this [doc](https://docs.google.com/document/d/1FGR4XBEu7IbfoaEy-8xbhQx2PvIyxp0VugoPrMfo4R4/edit?pli=1#heading=h.ky6rn0inhd26)

mockups [here](https://projects.invisionapp.com/share/Q9D1VQD67#/screens/254175337).

### TODO
- Need to test on Ubuntu and Windows after the pex file and windows installer are built through buildkite.

### CODE REVIEW

**Comment by rtibbles** [comment]
Approving, assuming that you and @jonboiser had decided not to separate the endpoints.

**Comment by rtibbles** [comment]
The code looks precisely right.

**Comment by lyw07** [comment]
@rtibbles Yes, I think that's what we finally decided yesterday, as it might be more consistent with previous code. I'll test more on different platforms, as well as with Aron's PR to check the granular import/export and update it here.

**Comment by rtibbles** [comment]
Yeah, I imagine switching would require more frontend refactor, so this is probably the path of least resistance for now!

**Comment by lyw07** [comment]
Update: tested with granular import by only importing one resource on Mac OS X/Ubuntu 14.04/Windows 10, and they all look good to me.

**Pull request merged**
