### PR TITLE
"Content kinds" -> "Type"

### PR DESCRIPTION
**Pull request by indirectlylit**
based on feedback from @khangmach during hack session, and also relates to ongoing conversation in #1663

----

before:

image

after:

image

### CODE REVIEW

**Comment by christianmemije** [comment]
`Resource type` is singular but the labels of the options are plural.

**Comment by indirectlylit** [comment]
Hm yeah it does read a little weird.

**Comment by indirectlylit** [comment]
It's the word "resources" that should be pluralized though, not "type".

> What type of sandwiches do you like? Hot sandwiches.

I think it would simplify things to just change the label to "Type", and leave out the word "Resources" altogether here.

**Comment by indirectlylit** [comment]
after after: 

image

**Pull request merged**
