### PR TITLE
add title and description for manage lesson resources

### LINKED ISSUE #6957: Lesson resource selection is missing topic title and description
### Observed behavior
The lesson resource page pictured on the left is missing the topic title and description. Quiz exercise selection does this correctly, pictured on the right.

Screen Shot 2020-05-29 at 1 59 19 PM

### Expected behavior
Titles and descriptions show for the current node the user is on. Unless we have a really good reason for omitting this information, the two modes should show as much consistent information as possible

### User-facing consequences
Users dealing with two similar interfaces with different information for ambiguous reasons.

### Steps to reproduce
- Open lesson resource management on a lesson
- Create a new quiz 
- Navigate to the same topic for both
- Compare

### Context
Tell us about your environment, including:
 * Kolibri version: 0.14 pex
 * Operating system: macOS
 * Browser: Chrome

### PR DESCRIPTION
**Pull request by Tlazypanda**
### Summary 
Fixes #6957 Added title and description for manage lesson resources page.

## Screenshots 
Before 

Screenshot from 2020-06-01 01-51-52

After  

Screenshot from 2020-06-01 01-57-57

### Reviewer guidance
Open lesson resource management on a lesson

### Contributor Checklist
PR process:

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@khangmach @indirectlylit @benjaoming can you kindly review? Thanks :v: again not really sure why travis is failing :cry:

**Comment by rtibbles** [comment]
It failed due to Python linting - as you haven't edited any Python files here, my guess is that you were working from an older version of develop. If you rebase the PR to latest develop, I think it should resolve the test failure.

**Comment by Tlazypanda** [comment]
@rtibbles Looks like buildkite is failing now :sweat_smile:

**Comment by rtibbles** [comment]
Ah yes - don't worry about that, the python package built fine, it's to do with some internal buildkite processes that this broke!

**Review by indirectlylit — APPROVED** [review]
thank you!

**Pull request merged**
