### PR TITLE
Remove unneeded future imports

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
Deletes the following future imports from the codebase:
* division
* absolute_import
* with_statement
* print_function
* unicode_literals

As can be seen from here: https://docs.python.org/3/library/__future__.html#module-contents all of these language features have been mandatory since Python 3 (the with statement since Python 2.6), so there is no longer any need to import these futures to enforce this behaviour.

## References
Further follow up after dropping Python 2.7

## Reviewer guidance
All the Python tests passing should be sufficient.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by AllanOXDi — COMMENTED** [review]
Looks good to me.  I am only wondering why the [documentation](https://github.com/rtibbles/kolibri/blob/no_future_no_future_no_future_for_me/docs/backend_architecture/upgrade.rst#L21) still mentions using `from __future__ import unicode_literals` for Django migrations. Since this PR removes future imports as they're no longer needed . Is  this guidance is still necessary, or it should be updated to reflect the removal of `__future__` imports?

**Comment by rtibbles** [comment]
Good point, @AllanOXDi - that can be removed as well. Will update!

**Comment by rtibbles** [comment]
Updated!

**Review by AllanOXDi — APPROVED** [review]
Looks good!

**Pull request merged**
