### PR TITLE
added backroute for immersive pages

### LINKED ISSUE #5889: Some immersive pages have the wrong exit link, esp. if coming from a notification
### Observed behavior

Some immersive-style coach pages like 'ReportsLessonLearnerExercisePage' can be linked to by certain notifications on the Class home page activity feed and activity page, and should go back to _those_ pages when exiting via the "X" button on the top of the page. Some of these pages, however, have their exit linked hardcoded to a specific page:

https://github.com/learningequality/kolibri/blob/9d2a49d03349e4d1165747fde2aac99926e8930a/kolibri/plugins/coach/assets/src/views/reports/ReportsLessonLearnerExercisePage.vue#L32-L36

Here's one of the pages where the URL correctly remembers the last location

https://github.com/learningequality/kolibri/blob/9d2a49d03349e4d1165747fde2aac99926e8930a/kolibri/plugins/coach/assets/src/views/reports/ReportsLessonExerciseLearnerPage.vue#L32-L36

### Expected behavior

Immersive pages that can be linked to from more than one place should go back to the correct location when hitting the exit button.

### Context
Kolibri 0.12.8 as of 9d2a49d03349e4d1165747fde2aac99926e8930a

### PR DESCRIPTION
**Pull request by priyanka-choubey**
### Summary
Fixes #5889 
Added backroute for ReportsLessonExerciseLearnerPage

----

### Contributor Checklist

PR process:

- [X] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by priyanka-choubey** [comment]
@kollivier @indirectlylit @jonboiser On searching for such routes I found a lot of results with no back route. Since I am new to this, can you help me figure out which files need these changes. Thankyou

**Comment by jonboiser** [comment]
@priyanka-choubey Here is a map that matches Notification objects with the component they should link to

https://github.com/learningequality/kolibri/blob/59844ae1c0a14c9aeca8c89bf0123b4a4bfd3ec5/kolibri/plugins/coach/assets/src/modules/coachNotifications/gettersUtils.js#L121

So I think if you look through all of those components (the `value` field is the component `name`), check if

1. they are immersive `corebase.immersivePage` is true
1. they have a hard-coded exit link.

If possible, test the change manually by creating a Coach notification and following the link.

**Comment by priyanka-choubey** [comment]
@jonboiser @indirectlylit @kollivier looked through the notification objects, only `ReportsGroupReportLessonExerciseLearnerPage` required a change. Apart from the I have made changes in all immersivePages with wrong exit link as the issue demanded. The following files were changed-
`kolibri/plugins/coach/assets/src/views/reports/ReportsGroupReportLessonExerciseLearnerPage.vue
``kolibri/plugins/coach/assets/src/views/reports/ReportsGroupReportLessonExerciseQuestionPage.vue`
`kolibri/plugins/coach/assets/src/views/reports/ReportsGroupReportQuizLearnerPage.vue`
`kolibri/plugins/coach/assets/src/views/reports/ReportsGroupReportQuizQuestionPage.vue`
`kolibri/plugins/coach/assets/src/views/reports/ReportsLearnerActivityExercisePage.vue`
`kolibri/plugins/coach/assets/src/views/reports/ReportsLearnerReportLessonExercisePage.vue`
`kolibri/plugins/coach/assets/src/views/reports/ReportsLessonExerciseQuestionPage.vue`
`kolibri/plugins/coach/assets/src/views/reports/ReportsLessonLearnerExercisePage.vue`
`kolibri/plugins/coach/assets/src/views/reports/ReportsQuizQuestionPage.vue`
 kindly review.

**Comment by jonboiser** [comment]
Cool, thanks for going through all of these pages!

**Comment by jonboiser** [comment]
@priyanka-choubey Could you try rebasing on `develop/HEAD`? The Buildkite checks are not passing, otherwise this PR looks good to me!

**Review by jonboiser — APPROVED** [review]

**Comment by DXCanas** [comment]
@priyanka-choubey so sorry, had no intention of associating my name with your commits. Just wanted to get this merged ASAP. I was the one that made the changes requiring a rebase. This alright? If not, we can totally wait for you to rebase yourself on top of this so the commit is 100% you :)

**Comment by indirectlylit** [comment]
that's fine, still has full author credit:

image

**Pull request merged**
