### PR TITLE
test1

### PR DESCRIPTION
**Pull request by thesujai**
## Summary

…

## References

…

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
Unfortunately it seems to be as I feared.

**Comment by thesujai** [comment]
Yes it doesn't works.
But i tried it on forks before, check this:
This was a PR i asked someone to do to my main repo by forking it: https://github.com/thesujai/gh-actions/pull/8
Here see the commit history

**Comment by thesujai** [comment]
BTW pre-commit lite is installed?

**Comment by rtibbles** [comment]
> BTW pre-commit lite is installed?

Oh - that would definitely explain it, needs to be installed for the pre-commit bot user to have permissions.... I have installed now - please push again!

**Comment by thesujai** [comment]
Test passed!!

**Comment by thesujai** [comment]
Just a small clarification:
In the two approaches i mentioned before, Is there any bloatware associated with pre-commit.ci (non lite) that we dont require, so you decided to move forward with current approach? Because it has the fix on comment right?https://pre-commit.ci/#configuration-autofix_prs

**Comment by rtibbles** [comment]
From my recollection (and I just checked the documentation again to see if anything changed) - the issue with the fully managed solution is that our locally defined hooks would not work, as they rely on `yarn install` having been run - and there's no way to configure their fully managed solution to do that.

**Comment by thesujai** [comment]
Oh Okay. Then the current solution is good

**Comment by rtibbles** [comment]
Hrm, the only worrying thing here is that flake8 is still failing, but black is not autofixing?

**Comment by thesujai** [comment]
In my local also i tried this, and same thing flake8 failed but black didn't autofixed it or detected the E302(expected 2 blank lines, found 0), also i observed with E501(line too long )
Maybe was a existing issue identified now? And maybe the issue with packages itself?

**Comment by rtibbles** [comment]
That seems most likely - we'll see how it goes, so we can close this test PR. Thanks for the work here @thesujai!

**Pull request closed without merging**
