### PR TITLE
Use url utilities to format urls

### PR DESCRIPTION
**Pull request by bjester**
## Summary

- Resolves issue syncing with manual (static) network locations caused by invalid url formatting

## References

https://community.learningequality.org/t/how-can-i-install-the-0-14-kolibri-version/2288

### New instance setup
1. Prepare a new Kolibri instance to sync with a separate, existing Kolibri instance
2. In the setup flow, choose to the advanced flow and import a facility from an existing instance
3. Manually add the location of the existing Kolibri instance when selecting the instance to import from
3. Verify you can complete the setup flow and the facility is synced

### Existing instance
1. Prepare an existing Kolibri instance to sync a new facility from a separate, existing Kolibri instance
2. From Device facilities page, choose to import a facility from an existing instance
3. Manually add the location of the existing Kolibri instance when selecting the instance to import from
3. Verify you can complete the sync process
----

## Testing checklist

- [X] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
Code makes sense, will do some manual checks before approving!

**Comment by radinamatic** [comment]
Will test out asap, but flagging for @pcenov too, to review the current Gherkin scenarios and ensure we have it covered.

**Comment by pcenov** [comment]
@radinamatic I tested the above described scenarios in both Windows and Ubuntu and both the import and syncing of a facility are functioning correctly in my network.
I'll update 2 of our feature files to have the manual addition of a URL covered.

**Review by rtibbles — APPROVED** [review]
Code looks good and manual QA checks out!

**Pull request merged**
