### PR TITLE
Add Kolibri locale bg-BG v0.10.x

### PR DESCRIPTION
**Pull request by ivanistheone**
### Summary

Added js and dj localization files for Koilibri  Bulgarian `bg-BG` strings.

### Reviewer guidance

imitation of https://github.com/learningequality/kolibri/pull/4193/files

### References

This is to test translation work done by people at [Education Without Backpacks](https://obr.education/en/), and support Kolibri integration.

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by indirectlylit** [comment]
This seems to be working fairly well; however I think we're missing some of the necessary font packs because it seems to be falling back on system defaults. Note the serif characters:

image

We have a similar problem with Yoruba, but it's less pervasive: #3648

I believe before merging this we'll need to make sure that the proper Cyrillic alphabet is available

**Comment by benjaoming** [comment]
> however I think we're missing some of the necessary font packs

Isn't that a host system issue?

**Comment by indirectlylit** [comment]
> Isn't that a host system issue?

Nope, we embed fonts. I've been working on this the past few days

**Comment by ivanistheone** [comment]
I rebased on top of latest 0.10.x release as of today.

@indirectlylit do you think the [intl. font PR](https://github.com/learningequality/kolibri/pull/4254) will be done in time for the next 0.10.x release? If so that would be nice, but not necessary.

The Bulgarian folks (OBR) reached are taking this into schools already and they don't mind the missing fonts, so I would motion to merge as is and fix the fonts in next release.

**Comment by benjaoming** [comment]
@ivanistheone I tend to agree in a general way: Let's reward translation work as much as we can. The font work is not a blocker. Not knowing about BG users, I think that such users will 1) exist and need 0.10 + benefit regardless of font issues or 2) not exist or not want 0.10 and then we can still merge this w/o issues.

@indirectlylit would that work? It's a nice exercise to get translations added in patch releases, which I think is a valid case for patch releases...?

**Comment by rtibbles** [comment]
I think it seems reasonable to add this in as a language for the patch release (which is a very common case for our patch releases), and then work on getting the fonts to be awesome in 0.11.

**Comment by indirectlylit** [comment]
Okay, sounds good!

**Review by indirectlylit — APPROVED** [review]

**Pull request merged**
