### PR TITLE
Tests text wrapping in KRadioButton

### PR DESCRIPTION
**Pull request by akolson**
## Summary

This PR tests that the `KRadioButton` labels wrap text and not truncate text
Before
Screenshot 2022-10-26 at 22 31 19

After:
Screenshot 2022-10-26 at 22 29 31

Please note that my KDS fork has been referenced for testing purposes. This will be reverted once KDS PR https://github.com/learningequality/kolibri-design-system/pull/380 gets merged

## References

https://github.com/learningequality/kolibri-design-system/pull/380

## Reviewer guidance

- Navigate to `http://localhost:8000/en/device/#/settings` or any other page where the `KRadioButton` is used.
- Resize the window to verify that the `KRadioButton` labels are wrapping and not truncating text
**Note:** This pr build has a known lint failure that is resolved by https://github.com/learningequality/kolibri/pull/9810

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by akolson** [comment]
This PR is ready for merging once review process is complete as https://github.com/learningequality/kolibri-design-system/pull/380 has been merged

**Review by nucleogenesis — CHANGES_REQUESTED** [review]
Should be good to go once the KDS version business is updated as it looks like your KDS PR was merged.

**Comment by akolson** [comment]
Yes @nucleogenesis this is the case., the KDS PR has been merged. An approval would now allow the merge. Thanks

**Comment by pcenov** [comment]
Manual QA passes as well - good to go! @radinamatic

**Review by radinamatic — APPROVED** [review]
Excellent news from QA, thank you @akolson for fixing this! 💯 :shipit:

**Review by nucleogenesis — APPROVED** [review]
:+1:

**Pull request merged**
