### PR TITLE
"Sync All" button visible only if a facility is registered with KDP 

### LINKED ISSUE #10755: Hide 'Sync All' button when no facilities are registered with KDP
## Observed behavior

None of my facilities are registered with KDP but the <kbd>SYNC ALL</kbd> is only applicable to KDP

## Expected behavior

We hide the <kbd>SYNC ALL</kbd> button when none of the facilities are registered with KDP.

## User-facing consequences

You need to have access to Kolibri Data Portal to use the 'Sync all' button. However, if you do not have access, the button should probably not be shown. The admin users on my facility gets confused everytime about the button when trying to sync the computers with each other.

msedge_3HsrdDUfaT

None of the devices are registered with Kolibri Data Portal nor is the facility.

## Steps to reproduce

Have one or more facilities, none of which are registered with KDP

## Context

 * Kolibri version: 0.15.12
 * Operating system: Windows
 * Browser: Chrome

### PR DESCRIPTION
**Pull request by im-NL**
## Summary

- fixes #10755 
- Sync all button disappears when no registered facilities are present.

## References

- References to issues: fixes #10755 and #10758 might be relevant

## Reviewer guidance

- changes can be tested by having one or more unregistered facilities and then going to the `devices` > `facilities`
- no risky areas 

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
Hi @im-NL - thanks for submitting the fix - looks very neat to me!

**Comment by im-NL** [comment]
> Hi @im-NL - thanks for submitting the fix - looks very neat to me!

Thanks so much! This is my first time contributing I'd love to know what I can do better/what I can fix. 

Also, we might want to _disable_ the 'Sync All' button if KDP itself is offline. I read this in the comments of an earlier commit and it seemed useful.

**Review by pcenov — APPROVED** [review]
Hi @im-NL - thanks for this contribution! @radinamatic no issues observed while manually testing this, the Sync all button appears when I import a facility which is registered to KDP and disappears when I remove the facility.

**Comment by radinamatic** [comment]
@im-NL For the failing linting checks run `yarn run lint-frontend:format` to get your code in line with the linting rules, and then commit and push those changes, so we can merge after the formal code review and approval.

**Comment by rtibbles** [comment]
> Also, we might want to disable the 'Sync All' button if KDP itself is offline. I read this in the comments of an earlier commit and it seemed useful.

Yes - that would indeed be useful. We have some other issues for tracking the connection status to KDP, so we'll cover this idea in the scope of that!

**Comment by im-NL** [comment]
> @im-NL For the failing linting checks run `yarn run lint-frontend:format` to get your code in line with the linting rules, and then commit and push those changes, so we can merge after the formal code review and approval.

Hey, thanks for this. On running `yarn run lint-frontend:format`, multiple files are being changed. Should I commit all of them or just ``index.vue``  (the file I've edited)?

**Comment by rtibbles** [comment]
Just the file you edited - in the linting check only the file you edited was causing an issue, so if there are other changes it must be due to an unrelated issue!

**Review by LianaHarris360 — APPROVED** [review]

**Pull request merged**
