### PR TITLE
enable scroll on setup_wizard

### PR DESCRIPTION
**Pull request by 66eli77**

### CODE REVIEW

**Comment by jtamiace** [comment]
screen shot 2016-08-15 at 3 57 20 pm


currently unscrollable and logo is wide?

**Comment by 66eli77** [comment]
wow, thanks for the feedback @jtamiace , is it running on firefox?

**Comment by indirectlylit** [comment]
remember to check em all on browserstack @66eli77 :)

**Comment by jtamiace** [comment]
Tested via browserstack and works on all major browsers

**Pull request merged**
