### PR TITLE
possible k-grid component

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

attempting to component-ize grids

### Reviewer guidance

does this help

### References

https://github.com/learningequality/kolibri/issues/3324#issuecomment-371695220

### CODE REVIEW

**Comment by christianmemije** [comment]
I like this!

**Comment by jonboiser** [comment]
Found a few more instances of "pure" in this fork. Will k-grid work here too?

```
kolibri/plugins/coach/assets/src/views/exam-report-detail-page/page-status.vue
4:    <div class="column pure-u-3-4">
20:    <div class="column pure-u-1-4">

kolibri/plugins/coach/assets/src/views/lessons/LessonContentPreviewPage/index.vue
127:  // might want to explore doing this with pure (original plan)

kolibri/plugins/coach/assets/src/views/reports/learner-exercise-detail-page/learner-exercise-report.vue
4:    <div class="pure-u-1-1">
13:      <div class="attempt-log-container pure-u-1-3">
21:      <div class="exercise-container pure-u-2-3">

kolibri/plugins/coach/assets/src/views/reports/learner-exercise-detail-page/attempt-summary.vue
4:    <div class="column pure-u-3-4">
47:    <div class="column pure-u-1-4">
```

**Comment by christianmemije** [comment]
Yes in those places ^, there should have been divs with pure-g classes. So the k-grid should also be used there @indirectlylit

**Comment by indirectlylit** [comment]
I intentionally skipped those for now because they actually looked broken to me - they're all missing a parent `pure-g` class.

I'll do another pass after this PR and do a bit more refactoring

**Comment by christianmemije** [comment]
@indirectlylit Forgot to import the components into the preview-exam-modal

**Pull request merged**
