### PR TITLE
Setup wizard progress indicators

### PR DESCRIPTION
**Pull request by DXCanas**
## Summary

Prevents repeated user submissions for new device owner + facility and notifies user that it's in progress. Needed now due to longer facility setup time. Found by @laurenlichtman, requested by @jamalex 

## Screenshots (if appropriate)

newsubmissionindicators

### CODE REVIEW

**Comment by rtibbles** [comment]
Maybe move the alert down to just above the button (where they have just clicked) and then disable all the input boxes too?

**Comment by indirectlylit** [comment]
For consistency I think we should avoid introducing a new "spinner icon button" - not in the style guide.

would this suffice?

* have the "setting up your device" messaging
* disable form fields and button during 'busy' state

cc @jtamiace @khangmach re: "in progress" states for forms

**Comment by DXCanas** [comment]
@rtibbles had put it there initially, @jtamiace thought the loading button was enough indication at the bottom, iirc.

Will disable the other fields

**Comment by laurenlichtman** [comment]
I agree with @rtibbles that it should be lower on the button. Would be ideal if it could overlay on the whole page but I understand that it may not be possible.

**Comment by jtamiace** [comment]
The spinner icon button is actually Keen UI's pattern, and I remember in passing that @christianmemije had also suggested introducing it. It's not in the guide but I'm not opposed to accepting it as a pattern and integrating it with the guide. 

The error message currently appears at the top. I had suggested moving the "in progress" message at the top for consistency on where system messages appear. I'm fine with the in progress message appearing above the button but should the error message also appear there?

Disabling the form fields is a good call, I think.

**Comment by christianmemije** [comment]
As @laurenlichtman mentioned, instead of disabling everything one by one, a non-dismissable small modal would be ideal.

**Comment by DXCanas** [comment]
@christianmemije @khangmach  @laurenlichtman I'm not opposed to the modal, and it wouldn't be hard to implement, but it doesn't strike me as the appropriate pattern for a submission, personally. At least not a full-on window-style modal like we use everywhere else

@jtamiace thoughts?

**Comment by DXCanas** [comment]
@indirectlylit @jtamiace - latest state of things:
newsubmissionindicators

**Comment by jtamiace** [comment]
We currently do not have a pattern for dealing with transient states of forms. Spinning icon buttons and nondismissible modals are not defined in the style guide, and per @indirectlylit 's concerns about deviating from the style guide I suggest that we use the components that we defined over the 3 weeks and decide on appropriate patterns for forms very soon.

**Comment by khangmach** [comment]
Question: does the "setting up your device" UI appear as an affirmation that all the fields are satisfied? We can probably implement a screen something like this, since it'll be appearing in onboarding anyways: 

https://user-images.githubusercontent.com/25045166/27625416-61c7fc2e-5b99-11e7-857c-95125080f3aa.png

**Comment by jtamiace** [comment]
@khangmach Yes. Also, because there was no system feedback and the devices being used were older/slower during training, users would repeatedly click the "submit" button and end up sending requests for multiple device owners to be made. Disabling the form fields & button and displaying the message helps to communicate that there was success, and now they just have to wait because their device is slow to process. 

I think user onboarding/setup wizards are generally okay to be a little more freeform in terms of styling than all the default UI elements. However, I think this needs to be quickly implemented for 0.5.x so not sure how much time it would take to implement a separate loading screen like that.

**Pull request merged**
