### PR TITLE
Update pyzeroconf to allow for more interruptability and quicker shutdown

### LINKED ISSUE #6809: Speed up Zeroconf service thread exit
# Observed behavior

When Kolibri shuts down, it stalls for a reported 23 seconds on Raspberry Pi waiting for Zeroconf discovery threads to exit.

The issue was reported and thoroughly investigated on the [Community Forums](https://community.learningequality.org/t/slow-system-shutdown-on-linux-systems-systemd-service/1482) by @JamesKainer.

As another means to fix this, #6710 suggested an option to disable the Zeroconf service.

This is important because RACHEL-based implementations with emergency power supplies are required total system shutdown times of less than 30 seconds for the emergency power bank to guarantee a clean shutdown. See: http://community.rachelfriends.org/t/new-image-shutdown-period/1687

Emergency power supplies are super cool because they can be made really cheaply and can mitigate damages caused by sudden power interruptions, which are common, both on grid and non-grid.

Related issues: #6615 #6610 

### Expected behavior

The below tests show that **Kolibri can shut down in 2 seconds** if the thread interrupts are favorable :four_leaf_clover: 

The Zeroconf background service for discovering other nodes can be made smarter, intervals can be adjusted etc.

The database-writing parts could perhaps be split out, such that the Zeroconf worker thread can be a daemon thread that terminates when the main thread exits?

### User-facing consequences

If Kolibri fails to shut down before emergency power supplies run out, the shutdown can be unclean and that's bad for the database etc.

The situation can lead to a monkey patch on Kolibri. That typically leads to other issues down the road :)

Something [in this message](http://community.rachelfriends.org/t/new-image-shutdown-period/1687/27) hints reverting to KA Lite as a work-around.

### Errors and logs

The bulk of the implementation is here: https://github.com/learningequality/kolibri/blob/develop/kolibri/utils/server.py

### Steps to reproduce

```
while true
do
  kolibri start > /dev/null 2>&1
  START_TIME=$SECONDS
  kolibri stop > /dev/null 2>&1
  ELAPSED_TIME=$(($SECONDS - $START_TIME))
  echo "It took $ELAPSED_TIME seconds to stop"
done
```

Example output on i7 8 GB laptop

```
It took 12 seconds to stop
It took 3 seconds to stop
It took 3 seconds to stop
It took 8 seconds to stop
It took 8 seconds to stop
It took 12 seconds to stop
It took 12 seconds to stop
It took 22 seconds to stop
It took 14 seconds to stop
It took 3 seconds to stop
It took 12 seconds to stop
It took 20 seconds to stop
It took 12 seconds to stop
It took 22 seconds to stop
It took 13 seconds to stop
It took 13 seconds to stop
It took 3 seconds to stop
It took 3 seconds to stop
It took 13 seconds to stop
It took 22 seconds to stop
It took 23 seconds to stop
It took 7 seconds to stop
It took 20 seconds to stop
It took 11 seconds to stop
It took 3 seconds to stop
It took 19 seconds to stop
It took 13 seconds to stop
It took 13 seconds to stop
It took 7 seconds to stop
It took 3 seconds to stop
It took 14 seconds to stop
It took 23 seconds to stop
It took 7 seconds to stop
It took 2 seconds to stop
It took 3 seconds to stop
It took 3 seconds to stop
It took 21 seconds to stop
```

### Context

0.13+

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
Brings in update to pyzeroconf that allows for more interruptability inside its child threads.
Allows for quicker shutdown of Kolibri as a consequence.

### Reviewer guidance
Ensure that Kolibri properly starts and shuts down.
For more intensive testing see bash commands in the associated issue.

### References
Fixes #6809

Dependency diff: https://github.com/learningequality/python-zeroconf-py2compat/compare/28a8a381cbe6d0903d0801c7bad2d803b09bcd86...learningequality:master

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by lyw07** [comment]
it seems that due to the change in the dependency, some tests failed?

**Comment by rtibbles** [comment]
Ah yes - the mocks in the tests are no longer mocking correctly!

**Comment by rtibbles** [comment]
Updated the mock, so tests *should* be ok now!

**Review by lyw07 — APPROVED** [review]
LGTM!

**Pull request merged**
