### PR TITLE
For testing: kolibri-installer-windows/pull/103

### PR DESCRIPTION
**Pull request by benjaoming**
### Summary

Testing builds with https://github.com/learningequality/kolibri-installer-windows/pull/107

How does this work? And while testing it, consider making some notes to create Gherkin scenarios :)

### Reviewer guidance

Don't merge

### CODE REVIEW

**Comment by radinamatic** [comment]
No problems installing the asset from this PR on Windows 10 with the previous installation of Kolibri 0.8 (that used Python 2.7). 
1. I expressly started the new installer **while the 0.8 server was running** to test for conflicts: none appeared, as the installer apparently stopped the server and proceeded with the Python 3.4 installation.
2. It took a bit (4-5 minutes on a single core, 2GB RAM VM) for the upgraded Kolibri to start again, but it eventually did.
3. No errors or problems whatsoever in viewing the old content, lessons, exams 👍 
4. I was able to use `kolibri stop/status/start` right of the bat, no messing with the proper path, so 🆒 



I'll test on Windows 7, but this looks like an awesome addition, good job team! 💥

**Comment by radinamatic** [comment]
All checks pass after upgrading from Kolibri 0.8 to this 0.13dev on Windows 7 too! 👍 



Let me know if there are more specific things to poke and prod, but for now this looks good to me!

**Comment by cpauya** [comment]
Thanks much for testing this @radinamatic - will do a final sweep then will merge and close this today.

**Comment by cpauya** [comment]
Closing this now that https://github.com/learningequality/kolibri-installer-windows/pull/107 was merged.

**Pull request closed without merging**
