### PR TITLE
Update le-utils.

### PR DESCRIPTION
**Pull request by christianmemije**
## Summary

Update le-utils to latest version that includes the html5 within the format presets.

### CODE REVIEW

**Comment by indirectlylit** [comment]
uh oh - looks like some tests are failing now (e.g. `DownloadContentTestCase.test_download_existing_file`)

**Comment by christianmemije** [comment]
Will fix this these tests.

**Comment by christianmemije** [comment]
@indirectlylit Cannot quite figure out the issue...

**Comment by indirectlylit** [comment]
@rtibbles I know you're working on getting tox to run locally again. Wonder if you might have some thoughts on the test failures we're seeing with this PR

**Comment by rtibbles** [comment]
The issue is that in latest le_utils, when this line: 
https://github.com/learningequality/kolibri/blob/develop/kolibri/content/test/test_downloadcontent.py#L29 tries to access the `choices` variable it refers to this: https://github.com/learningequality/le-utils/blob/master/le_utils/constants/file_formats.py#L56 which gives 'PDF Document" as the result, not a file extension.

Not sure how this has changed over time, but perhaps @jayoshih and @aronasorman can advise on how best to select the file extension now - although it seems like we could just add `pdf` directly, instead of doing a look up.

**Pull request merged**
