### PR TITLE
Automated pi builds

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

Includes a few minor updates to MacOS pipeline trigger

### Reviewer guidance

- Make sure this PR's builds Kolibri version is the one being packaged (_not_ the installer on public pip)
    - Especially the rPi's

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
Failing on the artifact upload step:

```
2019-12-14 16:45:00 INFO   Searching for artifacts: "dist/*.pex"
--
  | 2019-12-14 16:45:01 INFO   Found 1 artifacts. Starting to download to: /var/lib/buildkite-agent/builds/vader-1/learningequality/kolibri/dist
  | 2019-12-14 16:45:11 INFO   Successfully downloaded "dist/kolibri-0.13.0b7.dev0_git.8.gceac0d72.pex" 101712281 bytes
  | 2019-12-14 16:45:11 INFO   Searching for artifacts: "dist/*.whl"
  | 2019-12-14 16:45:11 INFO   Found 1 artifacts. Starting to download to: /var/lib/buildkite-agent/builds/vader-1/learningequality/kolibri/dist
  | 2019-12-14 16:45:21 INFO   Successfully downloaded "dist/kolibri-0.13.0b7.dev0+git.8.gceac0d72-py2.py3-none-any.whl" 99671869 bytes
  | 2019-12-14 16:45:21 INFO   Searching for artifacts: "dist/*.tar.gz"
  | 2019-12-14 16:45:22 INFO   Found 1 artifacts. Starting to download to: /var/lib/buildkite-agent/builds/vader-1/learningequality/kolibri/dist
  | 2019-12-14 16:45:30 INFO   Successfully downloaded "dist/kolibri-0.13.0b7.dev0+git.8.gceac0d72.tar.gz" 92423453 bytes
  | 2019-12-14 16:45:30 INFO   Searching for artifacts: "dist/*.deb"
  | 2019-12-14 16:45:31 INFO   Found 1 artifacts. Starting to download to: /var/lib/buildkite-agent/builds/vader-1/learningequality/kolibri/dist
  | 2019-12-14 16:45:37 INFO   Successfully downloaded "dist/kolibri_0.13.0b7.dev0+git.8.gceac0d72-0ubuntu1_all.deb" 55977744 bytes
  | 2019-12-14 16:45:37 INFO   Searching for artifacts: "dist/*.exe"
  | 2019-12-14 16:45:38 INFO   Found 1 artifacts. Starting to download to: /var/lib/buildkite-agent/builds/vader-1/learningequality/kolibri/dist
  | 2019-12-14 16:45:51 INFO   Successfully downloaded "dist/kolibri-0.13.0b7.dev0+git.8.gceac0d72-unsigned.exe" 129164246 bytes
  | 2019-12-14 16:45:51 INFO   Searching for artifacts: "dist/*.dmg"
  | 2019-12-14 16:45:52 INFO   Found 1 artifacts. Starting to download to: /var/lib/buildkite-agent/builds/vader-1/learningequality/kolibri/dist
  | 2019-12-14 16:46:04 INFO   Successfully downloaded "dist/kolibri-0.13.0b7.dev0+git.8.gceac0d72-macos-b6117e9.dmg" 106992016 bytes
  | 2019-12-14 16:46:04 INFO   Searching for artifacts: "dist/*.zip"
  | 2019-12-14 16:46:05 FATAL  No artifacts found for downloading
  | 🚨 Error: The command exited with status 1
```

**Comment by DXCanas** [comment]
Yep still working that bit out. We got build dirs interacting with upload dirs inside containers with chroots. It's great.

**Comment by jredrejo** [comment]
@indirectlylit the problem is fixed

**Review by jredrejo — APPROVED** [review]
Great work, thanks

**Pull request merged**
