### PR TITLE
For testing: kolibri-installer-windows/pull/108

### PR DESCRIPTION
**Pull request by cpauya**
### Summary

Testing builds with learningequality/kolibri-installer-windows#108

Look-up the BuildKite assets below if there are no errors raised during build.  Look for the installer `.exe/.msi` to use for testing the Kolibri Windows installer.

### Reviewer guidance

DON'T merge

/CC: @mrpau-julius @nucleogenesis @radinamatic

### CODE REVIEW

**Comment by nucleogenesis** [comment]
I have installed and tested quite a bit and everything has run very smoothly. I installed it once clean and once as an upgrade from v0.5.0 and both had no issues with the installation.

Are there any particular scenarios or aspects of installation that I could test to ensure I'm covering edge cases? 

@cpauya

**Comment by cpauya** [comment]
Thanks for the feedback! This should hopefully address this issue https://github.com/learningequality/kolibri-installer-windows/issues/94

So one edge case you could test is perhaps by deleting/renaming `C:\Python34\Scripts\pip.exe` after the Python installer is done (this happens in the middle of the Kolibri Windows installation) - to simulate the error display.

Hopefully @mrpau-julius and @mrpau-richard can also chime-in for other edge-cases.

**Comment by mrpau-richard** [comment]
@nucleogenesis I create an initial  and a work in progress [PR](https://github.com/learningequality/kolibri/pull/5742) for the Gherkin stories of this.

**Comment by nucleogenesis** [comment]
> Thanks for the feedback! This should hopefully address this issue [learningequality/kolibri-installer-windows#94](https://github.com/learningequality/kolibri-installer-windows/issues/94)
> 
> So one edge case you could test is perhaps by deleting/renaming `C:\Python34\Scripts\pip.exe` after the Python installer is done (this happens in the middle of the Kolibri Windows installation) - to simulate the error display.
> 
> Hopefully @mrpau-julius and @mrpau-richard can also chime-in for other edge-cases.

I have tested the installation by removing pip and got the expected error message with a working link to the setup-log file. Everything here looks good.

If you add more Gherkin stories that you'd like me to review, please tag me in Slack and I'll run the scenario.

**Comment by cpauya** [comment]
Thanks much for testing @nucleogenesis 

I will merge this now to get these merged into `develop`.  Further testing can continue in this testing PR: https://github.com/learningequality/kolibri/pull/5749

**Pull request closed without merging**
