### PR TITLE
EQM: Fix unlinted files

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Overview

In her work on #12427 @MisRob discovered that the file she'd updated had some extant linting issues that somehow got past the guards.

She fixed the ones in QuestionListPreview in that PR, here I fix the other two files for which I found linting errors when running the linter locally.

## Reviewer guidance

- Checks pass?

### CODE REVIEW

**Comment by MisRob** [comment]
Interestingly, when I discovered it, GitHub checks passed. But local linter revealed issues.

**Review by marcellamaki — COMMENTED** [review]
@nucleogenesis these changes look fine, but when I run locally, I still have some linting errors. Did you notice anything else locally? 

On a more meta level, I feel a little bit confused about why we seem to all be running into different local linting errors

**Comment by MisRob** [comment]
@marcellamaki Are the extra errors you see coming from `QuestionListPreview`? If so, I fixed them in https://github.com/learningequality/kolibri/pull/12427.

**Comment by marcellamaki** [comment]
Oh yes, okay. I didn't realize this wasn't rebased on top of that -- sorry that I didn't totally follow the division of the work between those PRs. This should be fine then. Thank you!

**Review by marcellamaki — APPROVED** [review]

**Pull request merged**
