### PR TITLE
Update Kolibri Windows installer to v1.2.0

### LINKED ISSUE #3521: update Windows installer to 1.2.0
### Observed behavior

There will be upgrades to the Windows installer: https://github.com/learningequality/kolibri-installer-windows/milestone/4

### Expected behavior

Upgrade to 1.1.3

### PR DESCRIPTION
**Pull request by mrpau-richard**
### Summary
Merge this PR after this [Milestone](https://github.com/learningequality/kolibri-installer-windows/milestone/4) finish.

### References
This fixes #3521 

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by indirectlylit** [comment]
@mrpau-richard please remember to set milestones on PRs

**Comment by benjaoming** [comment]
I think the Windows Installer should have a proper version bump when the Python version is changed, 1.2.0 sounds better. In case fixes are incoming for the 1.1.x installer, they can still be published in that series for Kolibri 0.9.x.

**Comment by indirectlylit** [comment]
sounds fine to me. I updated the milestone names: https://github.com/learningequality/kolibri-installer-windows/milestones

**Comment by benjaoming** [comment]
Thanks @indirectlylit 

@mrpau-richard you would need to amend this commit with the new version (once released anyways)

**Pull request merged**
