### PR TITLE
changelog for 0.12.9

### PR DESCRIPTION
**Pull request by indirectlylit**
Does this look correct?

Any typos?

### CODE REVIEW

**Review by lyw07 — APPROVED** [review]
Looks good to me! just wondering about one small thing - does the order of Internationalization and localization, Changed or fixed, Added matter here?

**Comment by indirectlylit** [comment]
>  does the order of Internationalization and localization, Changed or fixed, Added matter here?

These headers are a fairly recent addition. Do you have any recommendations?

**Comment by lyw07** [comment]
Oh I was asking just because our previous releases seem to list them in the order like:
```
Changed or fixed
Added
Internationalization and localization
```
so I was wondering if we have a convention or not. If we don't, then everything looks good to me!

**Comment by indirectlylit** [comment]
good catch! I've updated the ordering to be consistent

**Comment by lyw07** [comment]
thank you for addressing that! please feel free to merge it if you think everything is good to go :)

**Pull request merged**
