### PR TITLE
automatic database backup at version change

### PR DESCRIPTION
**Pull request by benjaoming**
## Summary

This adds automatic database backups during any kind of version change detected when `kolibri.utils.cli.initalize` runs. Files are stored in `~/.kolibri/backups/db-v1.2.3-2017-10-06_23-59-59`.

I added both time and version to the backup file name to make it more portable. For instance, someone emails a backup, then wonders "eh which Kolibri can run this".

The simple approach means that a lot of database backup files are potentially generated, so we should have a variant of this that implements user interaction and is sensible to whether database migrations are taking place while upgrading.

The database backup might also be moved to a different location, such as a management command so we provide users with something that's easy to automate as a cron-like job.

Blah blah - this is by the way a release blocker for 0.6, so good to get merged :)

## TODO

- [x] Mock with an actual database file rather than the in-memory test database.
- [x] Have tests been written for the new code?
- [x] Has documentation been written/updated?
- [x] New dependencies (if any) added to requirements file
- [x] Add an entry to CHANGELOG.rst
- [x] Add yourself it AUTHORS.rst if you don't appear there

## The approach

1. ~A raw file copy that most certainly fails if the database is unexpectedly open while upgrading (WHICH IT SHOULD NOT)~
1. A bullet-proof dump that users can only use if they restore using the sqlite CLI, which isn't installed on most systems

~I go for 1) - I just want to make sure that everyone knows that I've put an upgrade-breaker in case the database connection is open while upgrading and making the backup, so we don't suddenly have a situation where the backup fails and just skips.~

The 2) option has been chosen because I didn't find a way to guarantee that the database file was in a consistent state before doing a dump. Rather, we go for [iterdump](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.iterdump), which invokes SQLite core libraries and generates an SQL file.

This necessitates a custom `restore` command, which is great because of the custom Morango consistency updates.

## Issues addressed

Entirely solves #2266 
Partly solves #2137

### CODE REVIEW

**Comment by rtibbles** [comment]
My concern with the raw file copy approach is the issue previously raised by @jamalex, whereby we should be changing an id to prevent morango database id collisions.

**Comment by benjaoming** [comment]
@rtibbles can you state the case for such a collision? Because it seems to not be about the dumping process, but rather the restoring?

**Comment by benjaoming** [comment]
An important part that's missing here: Documentation about how to restore from a backup + a sensible CLI instruction after upgrading (for what it's worth -- I know that unattended upgrades are maybe the common case).

**Comment by benjaoming** [comment]
To assert that I'm not suggesting that we go down the wrong path: If it's possible from a management command to copy in a raw `.sqlite3` file as the default database and then perform a database query (for Morango) without issues, then IMO the raw copy seems feasible. I will be very skeptic though if at this stage it's a problem to create a very simple restore management command.

**Comment by indirectlylit** [comment]
fyi - lots of lint errors

```
pythonlint runtests: PYTHONHASHSEED='2445145843'
pythonlint runtests: commands[0] | flake8 kolibri
kolibri/utils/cli.py:35:1: E402 module level import not at top of file
kolibri/utils/cli.py:286:1: W293 blank line contains whitespace
kolibri/utils/cli.py:288:1: W293 blank line contains whitespace
kolibri/utils/cli.py:293:1: W293 blank line contains whitespace
kolibri/utils/cli.py:296:1: W293 blank line contains whitespace
kolibri/utils/cli.py:298:1: W293 blank line contains whitespace
kolibri/utils/cli.py:299:8: E713 test for membership should be 'not in'
kolibri/utils/cli.py:302:1: W293 blank line contains whitespace
kolibri/utils/cli.py:304:1: W293 blank line contains whitespace
kolibri/utils/cli.py:316:1: W293 blank line contains whitespace
kolibri/utils/cli.py:319:1: W293 blank line contains whitespace
kolibri/utils/cli.py:324:1: W293 blank line contains whitespace
kolibri/utils/cli.py:327:1: W293 blank line contains whitespace
kolibri/utils/cli.py:330:1: W293 blank line contains whitespace
kolibri/utils/tests/test_cli.py:28:1: W293 blank line contains whitespace
kolibri/utils/tests/test_cli.py:30:1: W293 blank line contains whitespace
kolibri/utils/tests/test_cli.py:40:1: W293 blank line contains whitespace
kolibri/utils/tests/test_cli.py:43:1: W293 blank line contains whitespace
kolibri/utils/tests/test_cli.py:45:1: W293 blank line contains whitespace
kolibri/utils/tests/test_cli.py:205:1: W293 blank line contains whitespace
kolibri/utils/tests/test_cli.py:208:1: W293 blank line contains whitespace
kolibri/utils/tests/test_cli.py:216:1: W293 blank line contains whitespace
kolibri/utils/tests/test_cli.py:227:1: W293 blank line contains whitespace
kolibri/utils/tests/test_cli.py:229:1: W293 blank line contains whitespace
kolibri/utils/tests/test_cli.py:233:1: W293 blank line contains whitespace
kolibri/utils/tests/test_cli.py:238:1: W293 blank line contains whitespace
kolibri/utils/tests/test_cli.py:241:1: W293 blank line contains whitespace
```

**Comment by benjaoming** [comment]
@indirectlylit I know I know - it's because pre-commit hooks broke, was wondering if my fix would make it from `release-v0.5.x` to `release-v0.6.x` in time :)

**Comment by benjaoming** [comment]
Almost there, but I'm going to move `kolibri.utils.cli.dbrestore` to a management command in `kolibri.core.sysadmin`

Speaking of which...

I added `kolibri.core.sysadmin` because I found no better place for a management command for backup and restore. I would propose that other future changes like deployment duplication (import/export) find its way here.

We currently already have an "administrator" and "device owner" term, so I found it confusing and used "sysadmin" for clarity.

**Comment by indirectlylit** [comment]
> We currently already have an "administrator" and "device owner" term, so I found it confusing and used "sysadmin" for clarity.

Note that 'device owner' is now deprecated, and there's a new 'superuser' device permissions flag.

**Comment by indirectlylit** [comment]
rather than `kolibri.core.sysadmin`, `kolibri.core.device` of `kolibri.core.deviceadmin` might be more consistent with our current nomenclature

**Comment by benjaoming** [comment]
Thanks @indirectlylit - I like `deviceadmin` better!

**Comment by benjaoming** [comment]
Will squash all this.

**Comment by benjaoming** [comment]
Just wanna make it absolutely clear that I switched from raw file dumps because I couldn't find a way to really guarantee that the database file wasn't somehow corrupt, so better to dump with `iterdump` and if something fails, we can become wiser! :)

This needs testing on all platforms, though.

**Comment by benjaoming** [comment]
So just finding out some new things about how Github understands force-pushes... you cannot re-create an entire new branch history. You have to force-push somehow, but I deleted the branch and created a new one with the same name, which doesn't work.

**Pull request closed without merging**
