### PR TITLE
Schedule-Sync: Frequency drop-down Label Correction

### LINKED ISSUE #10778: Scheduled sync - The 'Frequency' drop-down is labeled incorrectly
## Observed behavior
This as a follow-up issue noticed in https://github.com/learningequality/kolibri/pull/10748
The 'Frequency' drop-down is labeled incorrectly as 'Frequence'

## Expected behavior
The label should be corrected.

## Steps to reproduce the issue
1. Install the latest build asset from https://github.com/learningequality/kolibri/pull/10748
2. Go to Device > Facility
3. Click the 'Create sync schedule' link
4. Click 'Add device' and select either KDP or Local network

## Usage Details
Kolibri 0.16alfa14
Windows 10, Ubuntu - Chrome

### PR DESCRIPTION
**Pull request by Shashank245**
## Summary

…

## References

…

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by Shashank245** [comment]
Hello, I have made the changes in the file as required and created the PR for the same

**Comment by rtibbles** [comment]
Hi @Shashank245 could you also update the spelling here? https://github.com/learningequality/kolibri/blob/develop/packages/kolibri-common/components/SyncSchedule/EditDeviceSyncSchedule.vue#L380 then this PR should be good to go.

Also, please feel free to add yourself to the AUTHORS.md file if you are not already listed!

**Comment by Shashank245** [comment]
Hi Richard, I will surely make the changes in the link that you provided
also, I will add myself in the AUTHORS.md file if not already listed.
Looking forward to work on few more issues.

Thanks and Regards

**Comment by Shashank245** [comment]
Richard, I have made the changes created a new branch and a pull request: Here you go  

Shashank245:Issue#10783FrequencydropdownLabelCorrection

**Review by rtibbles — APPROVED** [review]

**Comment by rtibbles** [comment]
Thanks - I saw the follow up PR, will merge both.

**Comment by Shashank245** [comment]
Ok, Thanks for confirming

**Pull request merged**
