### PR TITLE
Provide task arguments in API response

### PR DESCRIPTION
**Pull request by dbnicholson**
It's not possible to identify a task's purpose using only its type and extra metadata. Expose the task's `args` and `kwargs` through the API responses so that frontend code can match jobs to specific resources.

## Summary

The tasks API only exposes the type and extra metadata in job responses. In many cases this is not enough to identify the actual purpose of the job. For example, a `kolibri.core.content.tasks.remotecontentimport` will only have the channel ID in extra metadata. This doesn't tell you about the `node_ids`, `exclude_node_ids` or `all_thumbnails` keyword arguments, so you don't really know what the task was used for.

Alternatively, I have a branch that adds the above properties to the extra metadata in `ChannelResourcesValidator` and `ChannelResourcesImportValidator`. Simply sending the `args` and `kwargs` seemed more general, though.

## References

None, but I can open an issue describing the above situation.

## Reviewer guidance

Start a download task, go to the device content page and use the browser's devtools to inspect a job response. It should contain `args` and `kwargs`.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — APPROVED** [review]
This is fine, and is definitely a glaring omission in the current API. Thanks for the fix.

The test failure is very weird - going to rerun as I can't see any reason why this should be impacted here.

**Comment by dbnicholson** [comment]
> The test failure is very weird - going to rerun as I can't see any reason why this should be impacted here.

I looked at the 3.11 error and it appears that `urllib.parse.urlparse` now checks the address with `ipaddress.ip_address` first. I believe it's [this commit](https://github.com/python/cpython/commit/29f348e232e82938ba2165843c448c2b291504c5). I think the fix is to catch `ValueError` from `urlparse` and convert it to `InvalidHostname`.

**Comment by rtibbles** [comment]
Yes, we'll be fixing it in upstream, no need to change it here!

**Comment by dbnicholson** [comment]
> Yes, we'll be fixing it in upstream, no need to change it here!

I just prepped a patch. Should I send it?

**Comment by dbnicholson** [comment]
> > Yes, we'll be fixing it in upstream, no need to change it here!
> 
> I just prepped a patch. Should I send it?

#10854

**Comment by rtibbles** [comment]
Test failure is fixed upstream. Merging.

**Pull request merged**
