### PR TITLE
Update side panel focus trapping

### LINKED ISSUE #9096: Focus is not working when Learner opens info side panel while in an activity
## Observed behavior
When a learner opens up an activity from the Library and uses the keyboard to navigate to the "view information" icon to open the side panel, they are unable to use the keyboard to navigate the opened side panel.

Additional notes:
- in the code, these are the `FullScreenSidePanel` components in `LearnImmersiveLayout`
- there is an existing pattern with `FullScreenSidePanel` and the use of the `FocusTrap` component that can be applied in this issue
- You may run into issues with figuring out what the first element to focus in this particular side panel should be

## Expected behavior
Focus behavior should match other instances of a full screen side panel

## User-facing consequences
It is an accessibility issue

## Steps to reproduce
1. As a learner, navigate to an activity
2. When the activity is opened, use the keyboard to navigate through the top app bar
3. Press "enter" when you reach the "view more information" icon on the furthest righthand side
4. Note that you cannot successfully navigate through the side panel with the keyboard

## Context
Kolibri v0.15.1

### LINKED ISSUE #9175: Cannot use keyboard to navigate through the info side panel for videos in Learn
## Observed behavior
When the informational side panel is open for videos, a learner cannot navigate through the opened side panel.

|Informational side panel in video in Learn|
|--|
|Screen Shot 2022-03-11 at 4 30 53 PM|

## Errors and logs
None

## Expected behavior
Learners should be able to use their keyboard to navigate the side panel, as seen below:

## User-facing consequences
Accessibility issue

## Steps to reproduce
1. As learner, use keyboard to navigate to a video in a lesson
2. Use the keyboard to navigate to the `Info` icon and press `Return`
3. Notice that you cannot navigate through this side panel using the keyboard.

## Context
Kolibri 0.15
MacOS
Chrome

### LINKED ISSUE #9178: Focus is still in main content when folder resources panel opens in an exercise in Learn
## Observed behavior
Focus ring does not immediate jump to the side panel (`FullScreenSidePanel`) when the side panel is opened by keyboard navigation.

## Errors and logs
None

## Expected behavior
Whenever a side panel opens by keyboard navigation, the focus should immediately be directed to that side panel, and not remain with the main content.

## User-facing consequences
Confusing for users who are navigating with keyboard.

## Steps to reproduce
1. Sign in as Learner
2. Open an exercise
3. Use the keyboard to navigate to the first icon the right-hand side (the one furthest to the left), called "View folder resources"
4. Notice that when you click `Enter`, and use `Tab` to navigate, the focus remains on the main content

## Context
Kolibri 0.15
MacOS
Chrome

…

### LINKED ISSUE #9193: `FullScreenSidePanel` focus is inconsistent in Firefox
## Observed behavior
In all side panels, there are varying behaviors for focus. Particularly with the `FullScreenSidePanel` component, for example, some of the inconsistencies are:

Exercises/HTML5 exercises
- Folder resources (only the close button, and after main content has been focused through)
- Info panel (no focus)

Browsing a channel
- Info panel (never gets to the close icon)

## Errors and logs
None

## Expected behavior
Focus behavior should be consistent.

## User-facing consequences
Confusing and user is unable to access all parts of the app via keyboard navigation.

## Steps to reproduce
There are many places where the side panel is open for a learner. Navigate to any of those places (through info icon in a content card, for example).

## Context
Kolibri 0.15
Firefox

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary
This PR uses a slightly modified version of the existing FocusTrap pattern's functions to ensure the focus shifts to the side panel correctly within the Content display and that a user can tab through each element of the side panel. 

## References
Fixes learningequality/kolibri#9178 
Fixes learningequality/kolibri#9096 
Fixes learningequality/kolibri#9175 
Possibly fixes learningequality/kolibri#9193 ? (A few extra tabs are required vs. in Chrome and Safari, but all elements are accessible via tab key when correct settings are enabled... I will see if I can continue to improve this in follow up, but I think the initial improvements are at least a step in the right direction since the content is now _available_ even if it is not the best experience) 

…

## Reviewer guidance
Use the tab key to navigate within various pieces of content (videos, exercises, etc.)
Opening the side panel to view information or to view additional resources should: 
- shift the focus to the side panel 
- cycle through the focusable elements - including links or buttons as well as the main close button 
- should work in Safari and Chrome. Improvements tbd in Firefox...

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
Definitely a step in the right direction! 💯 

Tested in Firefox and Chrome on Linux, it's possible to Tab-navigate correctly in and out the side panel, and focus & interact with all the elements **except downloading the resources**: the ``Download`` button itself gets the focus, and opens the available options to download, but those options (resources) cannot be selected (focused) by keyboard.

I'd say it's OK to deal with the additional Tab-presses in Firefox in the following PR, but let's fix this last issue before we merge. Thank you!

Was it intentional that the focus outline is rectangular in Chrome but rounded in Firefox? 🤔

**Comment by marcellamaki** [comment]
Good catch @radinamatic -- thank you! I will look into the download button issue. 

As for the focus outline... it was not intentional, but I also didn't try to ensure they were the same 😄

**Comment by marcellamaki** [comment]
@radinamatic -- past Marcella has come back to haunt me. There is [an open issue in KDS ](learningequality/kolibri-design-system#329) that I created, assigned to myself, and didn't finish, to address this very problem 🤦‍♀️  I will return to that PR to try to wrap it up and then after we release an updated KDS, if all goes well, hopefully that will help me fix this here.

**Review by sairina — APPROVED** [review]
Code looks good. Manual testing needs to be done to be sure.

**Comment by radinamatic** [comment]
Ok, if I understand correctly, the _unfocusability_ of the options in KDropdown is [tracked in KDS](https://github.com/learningequality/kolibri-design-system/issues/178) (I just upped the priority 😈), so we can approve and merge this.

**Review by radinamatic — APPROVED** [review]
Manual QA passes, pending issue to be resolved in KDS.

**Pull request merged**
