### PR TITLE
Old android build cleanup

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

Cleaning up build residuals for Android from 0.10 -> now. Will bring in new Android build with
https://github.com/learningequality/kolibri/tree/app-support

There's been a good amount of confusion about the android pipeline since this was disabled, so I want to remove the false lead.

### Reviewer guidance

Just make sure things didn't break because of the removal of these pieces.

### References

#6895 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by lyw07** [comment]
the cleanup looks good to me! I'm just not sure why the PR shows changes that have existed in the develop branch already...

**Comment by DXCanas** [comment]
@lyw07 It was because I was targeting the wrong branch :sweat_smile:

**Comment by DXCanas** [comment]
@lyw07 idk why, but travis was never triggered. Had to amend a commit to get it going, but once that's done, I think this is ready for merge. Thanks :)

**Review by lyw07 — APPROVED** [review]
Looks good to me!

**Pull request merged**
