### PR TITLE
Upgrade pex to newer version and remove wheel from build.txt

### PR DESCRIPTION
**Pull request by lyw07**
### Summary

This PR is to upgrade `pex` to newer version (currently 1.5.1, but pinned to be smaller than 1.6 in the PR) and remove `wheel` from build.txt so that we don't have version conflict warning during build time. I also changed the pinned version of `setuptools` to match with the requirements in [pex](https://github.com/pantsbuild/pex/blob/master/pex/version.py#L6).

### Reviewer guidance

Please check if the pex file works.

### References

#3675 

----

### Contributor Checklist

- [X] Contributor has fully tested the PR manually
- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Review by benjaoming — APPROVED** [review]
LGTM :+1:

I think that the Pex version was originally pinned for some reason. I can't recall it though, and I'm sure that it has received substantial updates and bug fixes since then.

But it needs thorough testing on various platforms, especially Mac (where installers do not exist).

@mrpau-dev would you be able to verify on existing popular platforms and Mac that this is working?

**Comment by mrpau-richard** [comment]
I tested this on Mac 10.11.3 and 10.13.3 the `.pex` file on this build  ran correctly.

**Comment by mrpau-julius** [comment]
I tested this PR in Ubuntu 18.04 and Xubuntu 17.04, no errors and it's works fine. 👍

**Comment by lyw07** [comment]
thank you @benjaoming for approving the PR! From this issue https://github.com/learningequality/kolibri/issues/1710, you mentioned that it has been fixed in 1.2.8. And I think that's why we were pinning pex to avoid any potential issues from upgrading it. 

also thank you @mrpau-richard and @mrpau-julius for the thorough testing!!

**Comment by benjaoming** [comment]
Awesome, no problem merging this for 0.12, plenty of time also for subsequent testing to catch any issues! :+1:

**Pull request merged**
