### PR TITLE
Including version info in metadata for pipeline ease-of-use

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

Each pipeline needs the version info to be passed in one way or another. Some used envars. Those are harder to carry between builds, though. Others had to extract the version manually from archived formats.

Uploading the VERSION file, which is scoped by entire builds, is a simple alternative and saves a step in each pipeline.

### Reviewer guidance

Check to make sure that the VERSION file is included in the python packaging step. 

### References

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
should we retarget this to 0.14 (or earlier)?

**Comment by DXCanas** [comment]
It's more of a nice-to-have. It's an ease of use thing that would be handy but it doesn't carry urgency. So no? ~Merging now anyway~

**Comment by DXCanas** [comment]
Scratch that, this was supposed to be targeted sooner in any case.

**Comment by DXCanas** [comment]
And I can't change targets anymore? 

I guess I'll just close it.

**Pull request closed without merging**
