### PR TITLE
Test experimental branch for windows installer

### PR DESCRIPTION
**Pull request by benjaoming**
This PR is a test of https://github.com/learningequality/kolibri-installer-windows/pull/91 by @mrpau-julius to see the Buildkite artifacts.

Not to be merged.

### CODE REVIEW

**Comment by benjaoming** [comment]
@rtibbles there's an error in the build.. I assume that node-js maintainers delete old versions.. which is a very critical behavior (because it hinders security audits and forensics).

```
 ---> Running in 79ccf82968f4
Hit:1 https://deb.nodesource.com/node_10.x bionic InRelease
Get:2 https://dl.yarnpkg.com/debian stable InRelease [13.3 kB]
Get:3 https://dl.yarnpkg.com/debian stable/main all Packages [8168 B]
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Get:5 https://dl.yarnpkg.com/debian stable/main amd64 Packages [8168 B]
Hit:6 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Fetched 29.7 kB in 1s (29.3 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '10.14.1-1nodesource1' for 'nodejs' was not found
```

**Comment by rtibbles** [comment]
Yeah, this happened to me on the PR that introduced this. Why would they do this?!

**Comment by benjaoming** [comment]
Probably to force people to upgrade because they think this is the best way. But it isn't.

**Comment by benjaoming** [comment]
Builds are working - now I guess we just need a quick verification of the Windows installer produced? @radinamatic @mrpau-dev

**Comment by mrpau-julius** [comment]
hi @benjaoming, I tested the Kolibri windows installer, it is not working, has error `python installer not found` and the name version was not changing. 
error python was not found

**Comment by benjaoming** [comment]
Hi @mrpau-julius  - the Windows installer size is just 56.7 MB.

As you can see, I am pulling in the test branch `download-python.exe` for these build. You can see the branch here: https://github.com/learningequality/kolibri-installer-windows/tree/download-python.exe

If you can push your changes/debug efforts directly to this branch, then just flag me when you need Buildkite to re-build.

**Comment by mrpau-julius** [comment]
Thanks, @benjaoming. 
I'm confused how they pass through if there is an error? Yes, I have some changes in the code but not yet done.

**Comment by benjaoming** [comment]
> I'm confused how they pass through if there is an error?

Well, I can't tell from the log output. It doesn't mention anything about downloading or bundling the python 3.4 .exe.

You can see the log output from this particular Buildkite job here: https://buildkite.com/organizations/learningequality/pipelines/kolibri/builds/8815/jobs/44146242-ef44-4031-9eeb-d8fe07246797/download.txt

```

wine: configuration in '/root/.wine' has been updated.


Inno Setup 5 Command-Line Compiler


Copyright (C) 1997-2016 Jordan Russell. All rights reserved.


Portions Copyright (C) 2000-2016 Martijn Laan


Inno Setup Preprocessor


Copyright (C) 2001-2004 Alex Yackimoff. All rights reserved.





Compiler engine version: Inno Setup 5.5.9 (u)





[ISPP] Preprocessing.


[ISPP] Preprocessed.





Parsing [Setup] section, line 11


Parsing [Setup] section, line 12


Parsing [Setup] section, line 13


Parsing [Setup] section, line 14


Parsing [Setup] section, line 15


Parsing [Setup] section, line 16


Parsing [Setup] section, line 17


Parsing [Setup] section, line 18


Parsing [Setup] section, line 19


Parsing [Setup] section, line 20


Parsing [Setup] section, line 21


Parsing [Setup] section, line 22


Parsing [Setup] section, line 23


Parsing [Setup] section, line 24


Parsing [Setup] section, line 25


Parsing [Setup] section, line 26


Parsing [Setup] section, line 27


Reading file (WizardImageFile)


   File: Z:\kolibri-installer-windows\windows\inno-compiler\WIZMODERNIMAGE.BMP


Reading file (WizardSmallImageFile)


   File: Z:\kolibri-installer-windows\windows\inno-compiler\WIZMODERNSMALLIMAGE.BMP


Preparing Setup program executable


   Updating icons (SETUP.E32)


Determining language code pages


Parsing [Languages] section, line 30


   File: Z:\kolibri-installer-windows\windows\inno-compiler\Default.isl


Parsing [Languages] section, line 31


   File: Z:\kolibri-installer-windows\windows\inno-compiler\Languages\Spanish.isl


Parsing [Languages] section, line 32


   File: Z:\kolibri-installer-windows\windows\inno-compiler\Languages\French.isl


Parsing [Languages] section, line 33


   File: Z:\kolibri-installer-windows\windows\inno-compiler\Languages\German.isl


Parsing [Languages] section, line 34


   File: Z:\kolibri-installer-windows\windows\inno-compiler\Languages\Greek.isl


Parsing [Languages] section, line 35


   File: Z:\kolibri-installer-windows\windows\inno-compiler\Languages\Nepali.islu


Parsing [Languages] section, line 36


   File: Z:\kolibri-installer-windows\windows\inno-compiler\Languages\Portuguese.isl


   Messages in script file


Reading default messages from Default.isl


Parsing [Languages] section, line 30


   File: Z:\kolibri-installer-windows\windows\inno-compiler\Default.isl


Parsing [Languages] section, line 31


   File: Z:\kolibri-installer-windows\windows\inno-compiler\Languages\Spanish.isl


   Conversion code page: 1252


   Conversion code page: 1252


   Conversion code page: 1252


Parsing [Languages] section, line 32


   File: Z:\kolibri-installer-windows\windows\inno-compiler\Languages\French.isl


   Conversion code page: 1252


   Conversion code page: 1252


   Conversion code page: 1252


Parsing [Languages] section, line 33


   File: Z:\kolibri-installer-windows\windows\inno-compiler\Languages\German.isl


   Conversion code page: 1252


   Conversion code page: 1252


   Conversion code page: 1252


Parsing [Languages] section, line 34


   File: Z:\kolibri-installer-windows\windows\inno-compiler\Languages\Greek.isl


   Conversion code page: 1253


   Conversion code page: 1253


   Conversion code page: 1253


Parsing [Languages] section, line 35


   File: Z:\kolibri-installer-windows\windows\inno-compiler\Languages\Nepali.islu


Parsing [Languages] section, line 36


   File: Z:\kolibri-installer-windows\windows\inno-compiler\Languages\Portuguese.isl


   Conversion code page: 1252


   Conversion code page: 1252


   Conversion code page: 1252


Parsing [LangOptions], [Messages], and [CustomMessages] sections


   Messages in script file


Reading [Code] section


Parsing [Dirs] section, line 58


Parsing [Icons] section, line 50


Parsing [Icons] section, line 51


Parsing [Icons] section, line 52


Parsing [Icons] section, line 53


Parsing [Icons] section, line 54


Parsing [Icons] section, line 55


Parsing [InstallDelete] section, line 64


Parsing [UninstallDelete] section, line 67


Parsing [UninstallDelete] section, line 68


Parsing [UninstallDelete] section, line 69


Parsing [Run] section, line 61


Parsing [UninstallRun] section, line 72


Parsing [Files] section, line 39


   Reading version info: Z:\kolibri-installer-windows\windows\installer-source\..\kolibri-0.12.0.dev0+git.20181213193950-py2.py3-none-any.whl


Parsing [Files] section, line 40


   Reading version info: Z:\kolibri-installer-windows\windows\installer-source\..\scripts\reset-env-vars.bat


Parsing [Files] section, line 41


   Reading version info: Z:\kolibri-installer-windows\windows\installer-source\..\scripts\add_systemstart_task.bat


   Reading version info: Z:\kolibri-installer-windows\windows\installer-source\..\scripts\remove_systemstart_task.bat


   Reading version info: Z:\kolibri-installer-windows\windows\installer-source\..\scripts\uninstall-kolibri.bat


Parsing [Files] section, line 42


Parsing [Files] section, line 43


Parsing [Files] section, line 44


Parsing [Files] section, line 45


Parsing [Files] section, line 46


Compiling [Code] section


Creating setup files


   Updating icons (SETUP.EXE)


   Compressing: Z:\kolibri-installer-windows\windows\installer-source\..\kolibri-0.12.0.dev0+git.20181213193950-py2.py3-none-any.whl


   Compressing: Z:\kolibri-installer-windows\windows\installer-source\..\scripts\reset-env-vars.bat


   Compressing: Z:\kolibri-installer-windows\windows\installer-source\..\scripts\add_systemstart_task.bat


   Compressing: Z:\kolibri-installer-windows\windows\installer-source\..\scripts\remove_systemstart_task.bat


   Compressing: Z:\kolibri-installer-windows\windows\installer-source\..\scripts\uninstall-kolibri.bat


   Compressing: Z:\kolibri-installer-windows\windows\installer-source\..\gui-packed\Kolibri.exe


   Compressing: Z:\kolibri-installer-windows\windows\installer-source\..\gui-packed\guitools.vbs


   Compressing: Z:\kolibri-installer-windows\windows\installer-source\..\gui-packed\images\logo48.ico


   Compressing: Z:\kolibri-installer-windows\windows\installer-source\..\gui-packed\icon\logo48.ico


   Compressing: Z:\kolibri-installer-windows\windows\installer-source\..\python-setup\python-exe.bat


   Compressing Setup program executable


   Updating version info





Warning: Line 228, Column 5: [Hint] Variable 'RETCODE' never used


Warning: Line 294, Column 10: [Hint] Variable 'Result' never used


Warning: Line 432, Column 3: [Hint] Variable 'USERKOLIBRIDIR' never used


Warning: Line 433, Column 3: [Hint] Variable 'EXTRACTCONTENT' never used


Warning: Line 80, Column 3: [Hint] Variable 'STARTUPOPTIONSPAGE' never used


Warning: Line 85, Column 3: [Hint] Variable 'SAVEDATABASETEMP' never used


Warning: Line 87, Column 3: [Hint] Variable 'RESTOREDATABASETEMP' never used





Successful compile (9.306 sec). Resulting Setup program filename is:


Z:\kolibri-installer-windows\windows\KolibriSetup-0.11.0b2.exe
```

**Comment by mrpau-julius** [comment]
Ok thanks, @benjaoming 😃

**Comment by cpauya** [comment]
@mrpau-julius Please make the changes as discussed and check this PR again to verify if the issue is still there regarding `how they pass through if there is an error`.

**Comment by benjaoming** [comment]
Oh also, should clarify this that I wrote before:

> Well, I can't tell from the log output. It doesn't mention anything about downloading or bundling the python 3.4 .exe.

What I mean is that you might want to add some more logging, because it's hard to see from current logs what's going on.

**Comment by indirectlylit** [comment]
closing PR due to inactivity. please re-open if necessary

**Pull request closed without merging**
