### PR TITLE
Verify that database backend isn't loaded when invoking status and stop

### PR DESCRIPTION
**Pull request by benjaoming**
### Summary

CC: @rtibbles @jredrejo @jamalex @ralphiee22 

Let's ensure that `stop` and `status` do not cause the database to be loaded since this can happen during upgrades.

In this PR, I propose that a simple solution could be to inject an invalid setting for the database backend to catch any unnecessary access. It already fails, so we need to investigate how that can be altered -- or if it can't, I can propose different ways to fail upon database access during stop/status commands.

Also of interest: The `manage shell` command is important to be able to access despite database issues.

The risk of accessing the database during stop/status is that a different database schema is loaded or different versions of Python libraries are applied on a SQLite database file used by another process. This could be a reason for the malformed database issues.

### Reviewer guidance

* Do you know if the currently failing database backend loading can be avoided?

### References

#6247 
#6201 

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by benjaoming** [comment]
Fixed: tox.ini cannot add an environment variable a single invocation of a command, needs it for the full test env. Therefore, added `dbaccess` to the test matrix.

**Comment by rtibbles** [comment]
Looking at the test run, it seems like this will always fail, because it invokes start, which will always need to access the DB.

**Comment by benjaoming** [comment]
> Looking at the test run, it seems like this will always fail, because it invokes start, which will always need to access the DB.

Ah no that should not be the case, I don't think it needs to start Kolibri before invoking status/stop.

**Comment by benjaoming** [comment]
@rtibbles you can run this PR locally like this:

```
KOLIBRI_DATABASE_ENGINE="raise.importerror.if.loaded" kolibri status
```

This currently renders the following error which I find highly suspicious:

```
WARNING:root:No C Extensions available for this platform.

INFO     Option DATABASE_ENGINE in section [Database] being overridden by environment variable KOLIBRI_DATABASE_ENGINE
INFO     Option RUN_MODE in section [Deployment] being overridden by environment variable KOLIBRI_RUN_MODE
Traceback (most recent call last):
  File "/home/user/.virtualenvs/kolibri/bin/kolibri", line 11, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "/home/user/.virtualenvs/kolibri/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/user/.virtualenvs/kolibri/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/user/.virtualenvs/kolibri/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/user/.virtualenvs/kolibri/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/code/kolibri/kolibri/utils/cli.py", line 34, in <module>
    from kolibri.core.deviceadmin.utils import IncompatibleDatabase
  File "/code/kolibri/kolibri/core/deviceadmin/utils.py", line 13, in <module>
    from kolibri.core.tasks.main import scheduler
  File "/code/kolibri/kolibri/core/tasks/main.py", line 85, in <module>
    priority_queue = Queue(priority_queue_name, connection=connection)
  File "/code/kolibri/kolibri/core/tasks/queue.py", line 13, in __init__
    self.storage = Storage(connection)
  File "/code/kolibri/kolibri/core/tasks/storage.py", line 58, in __init__
    self.Base.metadata.create_all(self.engine)
  File "/home/user/.virtualenvs/kolibri/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4005, in create_all
    tables=tables)
  File "/home/user/.virtualenvs/kolibri/lib/python3.6/site-packages/sqlalchemy/engine/interfaces.py", line 1165, in _run_visitor
    raise NotImplementedError()
NotImplementedError
```

**Comment by indirectlylit** [comment]
> The risk of accessing the database during stop/status is that a different database schema is loaded or different versions of Python libraries are applied on a SQLite database file used by another process. This could be a reason for the malformed database issues.

@benjaoming have you reproduced this scenario?

**Comment by rtibbles** [comment]
The suspicious lines can probably be resolved by doing some lazy instantiation, but also it is not accessing the default DB.

**Comment by rtibbles** [comment]
Superseded by #6281

**Pull request closed without merging**
