### PR TITLE
Consistent ordering for custom Vue options

### PR DESCRIPTION
**Pull request by MisRob**
### Summary

- extend default `vue/order-in-components` with custom options - `metaInfo`, `$trs`, `beforeRouteEnter`, `beforeRouteUpdate` and `beforeRouteLeave`

All fixes needed can be found in the last commit. Most of them were done automatically, but I needed to apply a couple of them manually, run auto-fix again and repeat this process a couple of times, so it made more sense to leave everything in one commit.

### Reviewer guidance

- Is the new order fine?
- Are there any other custom properties to order? I checked a couple of components and haven't found any so far.

### References

Solves second part of #4088

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by rtibbles** [comment]
My tendency has been to put `$trs` higher up in the component order, because that puts them nearer the template, which is useful for cross referencing when they are being used in the template.

Somewhere closer to the `name` property would be my vote, but happy to go with a majority view.

**Comment by MisRob** [comment]
OK, I'll wait a while to see if there's anyone else with any other preferences and then eventually reorder it. As far as I'm concerned, this choice was more or less random based on the previous location which was either in the beginning or at the end. I don't have any preferences on translations location, as long as it's in the same place everywhere, it's fine.

**Comment by indirectlylit** [comment]
@rtibbles's logic makes sense to me

**Comment by MisRob** [comment]
Oki. @jonboiser Are you OK with everything? In case there are no more suggestions, I'll update it this evening.

**Comment by jonboiser** [comment]
I'd prefer to go with the majority usage (place on the end), since it will result in a smaller change.

From an ergonomics perspective, I actually prefer it on the end because the strings aren't as referenced as often as the component's logic, so I like not having to scroll up/down extra lines to go between the template and the main options.

**Comment by MisRob** [comment]
Perfect opportunity for https://justflipacoin.com/

**Comment by rtibbles** [comment]
Like I said, I'm not hugely opinionated, and smaller diff sounds fine to me. End it is!

**Comment by MisRob** [comment]
OK, leaving it as is then.

**Review by rtibbles — APPROVED** [review]

**Pull request merged**
