### PR TITLE
Don't allow answer submission after exam is inactive or closed.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Fixes the backend element of #2085 

[x] - Tested

### CODE REVIEW

**Comment by ralphiee22** [comment]
Given this logic, won't the frontend display the big ole error message if they try to submit an answer after the exam has been closed? don't know if we are handling that, or if this just a hotfix for this problem

**Comment by rtibbles** [comment]
@christianmemije made a frontend fix that should stop them getting to the page at all if the exam has been closed, so if they got here, they should feel bad.

**Comment by rtibbles** [comment]
But yeah, mostly a hotfix. Would be nice to handle the error more gracefully on the frontend in future.

**Comment by ralphiee22** [comment]
Also, should we add handling the this error in the frontend to the clearinghouse? not sure if it goes there

**Comment by rtibbles** [comment]
I'll open a github issue directly.

**Comment by rtibbles** [comment]
Issue here: https://github.com/learningequality/kolibri/issues/2372

**Pull request merged**
