### PR TITLE
Adds explicit mimetypes file to ensure cross platform compatibility

### LINKED ISSUE #1199: `TypeError: this.items is null` on Windows
## Summary

Appears on all the non-PLIX and non-Flexbox exercises in CK-12 channel.
@rtibbles tried one approach in #1197, but the error is still there. 

## System information

 - Version: 0.3.1b2.dev4
 - Operating system: Windows 7
 - Browser: FF & Chrome

## Traceback or relevant snippet from server.log or browser console

```
TypeError: Cannot read property 'length' of undefined
    at qt.loadItemData (exercise_perseus_render_module-0.3.1beta1.dev2.js:42)
    at qt.n [as loadItemData] (default_frontend-0.3.1beta2.dev4.js:13)
    at qt.<anonymous> (exercise_perseus_render_module-0.3.1beta1.dev2.js:42)
    at nr.run (default_frontend-0.3.1beta2.dev4.js:14)
    at B (default_frontend-0.3.1beta2.dev4.js:13)
    at Array.<anonymous> (default_frontend-0.3.1beta2.dev4.js:14)
    at t (default_frontend-0.3.1beta2.dev4.js:14)
```

## How to reproduce

Try any non-PLIX and non-Flexbox exercise.

### Firefox
virtualbox_windows 7_07_04_2017_14_21_39

### Chrome
virtualbox_windows 7_07_04_2017_14_24_47

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Adds a copy of the Ubuntu mime.types file to the repo to ensure identical behaviour across all platforms in mimetype recognition.

Fixes #1199.

### CODE REVIEW

**Comment by aronasorman** [comment]
@rtibbles don't forget to add that new file to `MANIFEST.in` too! And can you test if it's getting imported properly in the whl file as well? I think we have to do something finicky for non-python files.

**Comment by aronasorman** [comment]
Buildkite should handle the whl file building for you.

**Comment by rtibbles** [comment]
Currently all files under the content folder (except those specifically excluded) are recursively included in the manifest. I thought the same thing and then checked the manifest file and found that.

**Comment by aronasorman** [comment]
Oh, sounds good then!

**Comment by aronasorman** [comment]
I'll do one more sanity test.

**Comment by aronasorman** [comment]
Can confirm. It's in there.

**Pull request merged**
