### PR TITLE
Coach Reports: Handle if no channels exist.

### PR DESCRIPTION
**Pull request by christianmemije**
## Summary

Coach Reports: Handle if no channels exist. Logic similar to that in Learn.

## Screenshots 

image

### CODE REVIEW

**Comment by indirectlylit** [comment]
> This seems like a point where content unavailable needs to migrate to the core app and then be used by both learn and coach reports.
> 
> Would prefer that to this approach which copies the functionality into coach reports.

For context - we'd discussed the trade-offs of DRY vs duplicated logic here.

I recommended duplicating to avoid the extra complexity of a new core component that's only used twice and might be thrown out very soon anyway - see e.g. the [rule-of-three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)

I'd argue that If we see a long-term need to make this a re-usable component in the future, it would be easy enough to consolidate. But it might be preemptive now?

**Comment by rtibbles** [comment]
What is the long term prospectus where we no longer need to flag content as unavailable? Are you seeing the more sustainable solution as something similar to the setup_wizard, where we just let people login, and then don't let them do anything unless they are an admin?

**Comment by indirectlylit** [comment]
It's a good question - I don't know. We can bring it up in the context of the current navigation redesign that Khang & co are working on so we have a design from the start, because that has changes to channel switching etc in it...

**Comment by rtibbles** [comment]
OK, in that case, I think it is fair to assume that we would want the device to essentially be 'locked down' to learners and coaches if there is no content (because it is useless to them), and to put an admin into the correct point in the setup flow. I think this is something that we could do from the Django side in the future, but this will do for now!

**Comment by indirectlylit** [comment]
Cool, let's make sure to bring up this question with the design folks

**Comment by rtibbles** [comment]
@khangmach @jtamiace see discussion above.

**Pull request merged**
