### PR TITLE
Remove camel/snakeCaser functions, refactor facility settings page

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

1. Removes the camelCase/snakeCase transformer functions that were basically used to convert the keys in the FacilityDataset model from snake case to camel case.
1. Updates the components/codes/tests, and do some basic refactors.

### Reviewer guidance

1. Manually test the FacilitySettingsPAge, as it is the only page affected by this.

### References

…

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Review by indirectlylit — APPROVED** [review]
This seems fine to me.

It does make me wonder whether we'll ever be able to achieve consistency of case conventions without changing the whole frontEnd to snake_case...

Any thoughts on a long-term strategy?

**Comment by indirectlylit** [comment]
@jonboiser do you recall which milestone this was done under?

**Comment by jonboiser** [comment]
No milestone, it was just some maintenance work. It was merged into the develop branch though.

**Comment by indirectlylit** [comment]
every change should have a milestone - we just forgot to set it :)

> image

I was trying to figure out how this change could have caused #5428 since presumably this change was never released, but #5428 was observed in 0.12.2

**Comment by jonboiser** [comment]
If #5428 was seen in 0.12.2 it might be for a different reason than this PR. Are these commits in the release branch somehow?

**Comment by rtibbles** [comment]
I don't think that's the issue - the issue seems to be that `learnerCanEditPassword` is actually missing from the list of settings in 0.12:
https://github.com/learningequality/kolibri/blame/release-v0.12.x/kolibri/plugins/facility_management/assets/src/views/FacilityConfigPage/index.vue#L76

**Comment by indirectlylit** [comment]
these commits are definitely not in the 0.12.x branch

**Comment by rtibbles** [comment]
It's also missing in 0.11.x https://github.com/learningequality/kolibri/blob/release-v0.11.x/kolibri/plugins/facility_management/assets/src/views/FacilityConfigPage/index.vue#L76

**Comment by indirectlylit** [comment]
i suppose this says something about how often passwords get updated!

**Comment by rtibbles** [comment]
The last reference I can find to these is 0.4.x: https://github.com/learningequality/kolibri/blame/release-v0.4.x/kolibri/plugins/management/assets/src/views/facilities-config-page/index.vue

**Comment by rtibbles** [comment]
Looks like `learner_can_delete_account` also went missing.

**Comment by jonboiser** [comment]
Yeah, not all of those options are configurable in the UI (for reasons I've forgotten). But they all have default values. The default value for `learner_can_edit_password` has always been true, though.

**Comment by rtibbles** [comment]
Looks like `learner_can_delete_account` is a no op, so we should leave it hidden. But we can put the learner edit password back in as per your issue above.

**Pull request merged**
