### PR TITLE
update 'delete user' strings

### LINKED ISSUE #4424: 'All learning records' might be confusing, especially for a coach user
### Observed behavior
@laurenlichtman reports while deleting a coach user:
"All the learning records for 'bbadmin' will be lost." (1) 'bbadmin' was a Coach (assuming this user also has logs). (2) I'm not sure if we use the terminology "learning records" anywhere and it may be confusing. How about "All data for 'bbadmin' will be lost."?

### Expected behavior
A message that better summarizes what is happening?

### User-facing consequences
Miscomprehension of what is being deleted.

### Context
v0.11.0-beta1

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

| Before | After |
|--|--|
| image |  image |

### Reviewer guidance

make sense?

### References

fixes #4424

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by radinamatic** [comment]
You changed the pic, right? Something _was_ wrong with the first one, this looks better.

I'm just not completely sure about the word `logs`... 🤔 
My guess is that we previously went with `learning records`, to make it less technical.

**Comment by radinamatic** [comment]
@indirectlylit Remind me what was the rationale for this change (`learning records` to `data logs`)? Was it to underline that _everything_ regarding the user will be lost, or there was a CH issue or another discussion somewhere I might have missed?

**Comment by indirectlylit** [comment]
only what's mentioned by @laurenlichtman in #4424:

> "All the learning records for 'bbadmin' will be lost."
> 
> (1) 'bbadmin' was a Coach (assuming this user also has logs).
> (2) I'm not sure if we use the terminology "learning records" anywhere and it may be confusing. How about "All data for 'bbadmin' will be lost."?
> Or maybe "All data logs" or "All logs" just to use terminology consistent in Kolibri.

Open to revisions!

**Comment by indirectlylit** [comment]
updated to 

> All data and logs for this user will be lost

**Pull request merged**
