### PR TITLE
Ensure adhocgroup is managed in notifications

### PR DESCRIPTION
**Pull request by nucleogenesis**
### Summary

Notifications for activity related to individual learners is now addressed re: https://github.com/learningequality/kolibri/issues/6341

**NOTE** that when a learner has activity and is assigned as part of a group - the notification card will say something like `Group 2 - Lesson 1`.

There is no such item for "Individual learners" but it may be worth considering if we should put a string saying "Individually assigned" in that context the next time we're able to add strings.

**NOTE 2** typically groups of events on the same item would be combined into things like "Radina and N others completed The Quiz" or "Everyone in Group 1 started Lesson #1". Individual learners are not grouped similarly so the "Everyone..." type events are not shown at all. The "Learner and N others..." types are also not used here because those types of notifications link to Reports > Groups reports and there is not a report like that for Individual learners. Therefore, Individual learners notifications are all individually listed in Class Home > Class Activity.

### Reviewer guidance

__Quizzes__

- Create a quiz, assign only individual learners.
- Create a quiz, assign a group and individual learners.
- Open the "Class Home" for that class as coach.
- Take the quizzes as both individual learners and learners who are a part of the group you assigned.
- See all started and completed notifications showing in the Class Home page for the learners as expected.

- Repeat by adding an Individual Learner to an existing quiz (existed prior to you testing this) if you have one.

__Lessons__

- Do the same as above, but with Lessons.
- Note also that "Needs help" notifications should appear so try answering 3 questions incorrectly as an individual learner.

### References

https://github.com/learningequality/kolibri/issues/6341

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by jredrejo — DISMISSED** [review]
As you can see at 
image
Even if a lesson is assigned to one individual learner, the "Entire class" message appears.
The problem is in` kolibri/plugins/coach/assets/src/views/common/Recipients.vue` , in the code   
 ```
<template v-else-if="hasAssignments">
      {{ coachString('entireClassLabel') }}
    </template> 
```
where Entire class is always used if there are assignemnts


On the other hand, the NeedsHelp message does appear after failing answering some questions when the lesson is assigned to an Individual learner, so we are good on this point.

**Review by jredrejo — APPROVED** [review]

**Comment by jredrejo** [comment]
After the last commit the remaining issue has disappeared. All good. Thanks!

**Review by jredrejo — APPROVED** [review]
After the last commit the remaining issue has disappeared. All good. Thanks!

**Comment by lyw07** [comment]
Is this ready to be merged? Thanks!

**Pull request merged**
