### PR TITLE
Don't set bookmark data from backend that is stale.

### LINKED ISSUE #9869: Class > Lesson - Resources get displayed as bookmarked while they are not
## Observed behavior
After I bookmark a resource and I click on another resource in the lesson and then go back and forth then eventually the other resource is also displayed incorrectly as bookmarked. 

## Expected behavior
The 'Save to bookmarks' option should not get incorrectly enabled.

## Steps to reproduce the issue
1. Install the the following [build ](https://github.com/learningequality/kolibri/releases/tag/v0.15.9-beta3) 
2. While at Class > Lesson bookmark a resource by selecting the 'Save to bookmarks' option.
3. Click the Back arrow to go back to the lesson resources page.
4. Open another resource which has not been bookmarked.
5. Go back and open the bookmarked one.
6. Go back to the other resource and observe that it gets bookmarked.

## Video

https://user-images.githubusercontent.com/79847249/203820482-de451a28-c35e-42d8-a38c-8f956ea3abfd.mp4

## Usage Details
Windows 10, Ubuntu - Chrome

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Adds defensive checks to make sure we never set stale bookmark data into component state

## References
Fixes #9869

## Reviewer guidance
I had difficulty reproducing this, but hopefully @radinamatic or @pcenov can confirm the fix here.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
Tested  with Firefox and Chrome in Ubuntu 18.04, and not able to replicate the improper bookmarking of resources. Leaving it to @pcenov to give the final confirmation.

**Review by marcellamaki — COMMENTED** [review]
Code looks fine to me - lets see if Peter can confirm his time tomorrow, and then I will merge!

**Comment by pcenov** [comment]
@marcellamaki @radinamatic - I confirm, this one is fixed now! :)

**Review by radinamatic — APPROVED** [review]
Manual QA passes, good to go! 💯 :shipit:

**Pull request merged**
