### PR TITLE
updated language switcher

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

As reported in #3652, the language switcher is kind of a mess.

This PR simplifies the UI drastically and makes it consistent with the other language switcher in the main app:

* use a globe icon to indicate the current language
* use a modal - more effective at handling a large number of languages than the select box

| Before | After |
|--|--|
| image | image |

| select 1 | select 2 | same modal for both |
|--|--|--|
| image | image | image |

The main downside I can think of is that there's no longer a few other visible languages. However, I'd argue that this is a reasonable thing to give up...

### Reviewer guidance

Please review both the design and implementation

### References

#3652

----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If there are any front-end changes, before/after screenshots are included
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by jtamiace** [comment]
I think the enhancement to open into a modal is great and so is the globe icon and current language but would like to still advocate for displaying a few languages in different scripts to help especially less digitally literate users. 

The UI components here (footer vs dropdown) are completely different so I would argue that consistency is not a good reason to take them out. There's more screen real-estate afforded in the footer than a dropdown, so why not use it? 

screen shot 2018-06-20 at 5 18 06 pm

I just deleted components with inspect element, but I wouldn't expect someone who's entirely new to computers to know where to change the language here, even with the globe icon.

**Comment by indirectlylit** [comment]
okay, I'll look at a variation with a few languages displayed

**Comment by khangmach** [comment]
- I like the switch to a "Change language" button and also the usage of the modal. 
- The globe icon definitely helps this section stand out
- RE: showing more languages: Accommodating those who aren't computer literate is important...although I think the chances are still  low for a user to chance upon their native language even if we display 2+ languages outside of the modal
- I think we can do without the "Selected language" label text, esp if we include the globe icon

**Comment by jtamiace** [comment]
> the chances are still low for a user to chance upon their native language even if we display 2+ languages outside of the modal

The point is more so to use the display of different scripts to signal that there is likely a mechanism to change language nearby. 

I guess another argument against displaying scripts is that a less digitally literate user still may not understand that signal, and they'll be in a social environment anyway where they can ask someone why Kolibri is in a language they don't understand.

**Comment by indirectlylit** [comment]
Seems like the idea is that by showing foreign-looking characters/words juxtaposed, we can evoke the idea of "multiple languages". That seems to be strategy with icons like these:

image image image image

If we show the names of a few languages, we're kind of using them as abstract icons...

_UNLESS_ we had a way of knowing the "most likely" languages. If we knew that, then it actually becomes really useful to show them up front as quick-links.

**Comment by indirectlylit** [comment]
Update:

Now shows a few language links randomly chosen from our most common languages:

* arabic
* english
* spanish
* french
* hindi
* swahili

The number of languages shown is variable based on the browser width.

image

**Comment by indirectlylit** [comment]
also fixes https://github.com/learningequality/kolibri/issues/3851

**Review by khangmach — APPROVED** [review]

**Review by jtamiace — APPROVED** [review]

**Review by christianmemije — APPROVED** [review]

**Pull request merged**
