### PR TITLE
Add APK building to PR asset building and release pipelines

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Adds building of a release asset for all Kolibri releases which will get released to the internal testing track on the play store
* Adds promoting of internal testing track asset to open testing track for final releases
* Adds building and uploading of non-release APK files to PR assets

## References
Integrates https://github.com/learningequality/kolibri-installer-android/pull/152 into Kolibri

## Reviewer guidance
The only real way to test the release part of this is to merge it, but please double check my yml.

PR build showing an APK should be a sign of success for the other part!

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by jredrejo — COMMENTED** [review]
Nothing to object on this PR changes, but it seems the `build_apk` workflow has a problem with a required dependency on `setuptools`

**Comment by rtibbles** [comment]
Yeah, I am making some tweaks on the other repo to fix up these issues.

**Comment by rtibbles** [comment]
This is now only failing because of permissions issues for the secrets I am referencing. I am pretty confident that this is good to merge.

**Comment by rtibbles** [comment]
Merging, on my own head be it if anything breaks.

**Pull request merged**
