### PR TITLE
Fix language switcher errors

### LINKED ISSUE #12447: Display issues for login language switcher
## Observed behavior
Incorrect overflow observed:
Screenshot from 2024-07-15 17-40-50

Modal positioned incorrectly:
Screenshot from 2024-07-15 17-40-41

## Expected behavior
Language switcher should not overflow onto second line, modal should not be causing unnecessary page scroll.

## User-facing consequences
Odd experience on many people's first use of Kolibri

## Steps to reproduce
Go to the login page on desktop.
See the languages overflowing.
Click change language, see the modal awkwardly positioned.

## Context
There has been recent work to update the language switcher (mostly in the context of the setup wizard) that may have contributed to this, but it seems likely that there has been an unintended interaction with other changes in 0.17 as well.

Fixing this should also make sure _not_ to cause regressions in the setup wizard language switching display.

### PR DESCRIPTION
**Pull request by AlexVelezLl**
(Note) This PR depends on https://github.com/learningequality/kolibri-design-system/pull/680 to be merged and released.

## Summary

Updates KDS to fix KListWithOverflow overflow items calculation, and fix KLanguageSwitcherModal positioning. I also checked the Setup wizard, and no regressions were observed.

Before:
image

After:
image

## References

Fixes #12447.

## Reviewer guidance

Follow #12447.

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by MisRob** [comment]
Thank you @AlexVelezLl, I can confirm the fixes work well and I didn't observe any regressions.

**Comment by MisRob** [comment]
Ah one more thing, after new KDS version is installed here, would you also removed <`Teleport`> from here https://github.com/learningequality/kolibri/blob/542d558aabe4ca2c0dc190b857c79dcb744b4cc5/kolibri/plugins/learn/assets/src/views/SearchFiltersPanel/CategorySearchModal/index.vue#L4-L8 or do you prefer follow-up issue?

**Comment by rtibbles** [comment]
Would be a matter of adding `:appendToBody="windowIsLarge"` I think, then removing Teleport, and the teleport dependency in the learn plugin. Should be straight forward, but fine for a follow up if preferred.

**Comment by MisRob** [comment]
@rtibbles 

So this syntax says

```
<Teleport 
   v-if="windowIsLarge" 
   to="body" 
 > 
```

to use Teleport only if `windowIsLarge`? Sounds like silly question :) My read of this was that the modal is rather not supposed to get rendered at all for `windowIsLarge`.

**Comment by MisRob** [comment]
> Would be a matter of adding :appendToBody="windowIsLarge" I think

Asking because I left a note for @AlexVelezLl just for consideration of having `appendTo` prop so we can choose the element to append to (you can see the KDS issue for reasons for that). However, if we'd need to support conditional teleport application, in such case KDS would need to support something like `appendTo=windowIsLarge ? 'body' : null` where `null` would indicate we don't want to append it, if that was the direction to take (or some alternative interface that would allow for condition)

**Comment by rtibbles** [comment]
Oh... yes, sorry - so we should just move the v-if to the KModal instead, you're right and it would just be `appendToBody` as it is here...

**Comment by MisRob** [comment]
No problem :) That simplifies the situation around potential `appendTo`.

**Comment by MisRob** [comment]
I thought that perhaps Teleport does some nice magic around `v-if`s after reading your comment :)

**Comment by MisRob** [comment]
As soon as we install the new release here, we can merge. Thanks @AlexVelezLl.

**Review by MisRob — APPROVED** [review]
As soon as we install the new release here, we can merge. Thanks @AlexVelezLl.

**Review by rtibbles — APPROVED** [review]

**Pull request merged**
