### PR TITLE
Getting Started for new contributors

### PR DESCRIPTION
**Pull request by radinamatic**
## Summary

More "extended" version of the existing **Getting Started** doc to help new contributors find their way out of the rabbit hole easier!
## TODO
- [ ] Probably a lot can still be improved, suggestions and corrections are welcome... :wink:

### CODE REVIEW

**Comment by indirectlylit** [comment]
A lot of the content here is copied from the 'getting started' page, so there's a risk that they'll get out of sync over time...

I wonder if there's a way to add the additional details but still keep things [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)? (E.g. margin notes, footnotes, links small external pages, etc)

**Comment by radinamatic** [comment]
DRYing is certainly something we could try, but I would like to avoid dispersing to other external/small pages, and ideally keep this as one long (as consequential as possible) list of steps to have a working Kolibri dev environment. Newbies already get lost more than enough among tabs/pages with several other tutorials, resources and error search results (been there more times than I'd like to remember :unamused:).

Why don't you flag the blocks that are more susceptible to future updates, as there are those that are less likely to change (the whole Git-GitHub-fork-clone shebang, for example), and I can experiment with naming/referencing or using `literalinclude` [directive for code-blocks in RST](http://www.sphinx-doc.org/en/stable/markup/code.html#includes)? Maybe that way we can stay dry enough... :wink:

**Comment by indirectlylit** [comment]
Sorry I didn't follow up from before. FYI though, the `getting_started` page recently updated with the replacement of `npm` with `yarn`.

Back to the previous discussion though

> I would like to avoid dispersing to other external/small pages

Yes, I agree that's suboptimal. Footnotes are an option that doesn't require external pages, but are also sub-optimal because they require lots of scrolling.

IMO the ideal solution would be some kind of collapsible inline notes or margin notes. With something like that, experienced developers can move quickly through the critical steps, and the newbies can get additional info without losing context. I don't think our current system supports that though.

My inclination for this PR would be to move all the content you've written here to the existing `getting_started` page. It's important stuff.

----

Longer term:

I'd like to explore moving from [readthedocs.io](https://readthedocs.org/) and [sphinx](http://www.sphinx-doc.org/en/1.5.1/) to [gitbook](https://www.gitbook.com), which:

* has plugin support so we can extend it with what ever features we want. see e.g. [this margin-notes plugin](https://plugins.gitbook.com/plugin/marginal)
* is still hosted in our git repo alongside the source code
* still has export-to-PDF support
* uses markdown, which our devs are much more likely to be familiar with than restructuredtext
* has an online editor

**Comment by radinamatic** [comment]
> My inclination for this PR would be to move all the content you've written here to the existing getting_started page. It's important stuff.

Ok, will make a new PR!

> I'd like to explore moving from readthedocs.io and sphinx to gitbook.

I like RTD, but I'm not married to it. If you believe the difference between rST & Markdown will make it easier for the devs to contribute documentation, it's worth the try. I find GitBook a bit "watered down", but that's just me... I'm inviting @benjaoming to the [Trello discussion](https://trello.com/c/ihPRFiDa/719-investigate-migrating-from-sphinx-readthedocs-to-gitbook) since he was instrumental into our adopting RTD for docs.

**Comment by indirectlylit** [comment]
superseded by #831

**Pull request closed without merging**
