### PR TITLE
Fufulde perseus update

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
Updates perseus for fufulde.
Updates latest strings.
Adds mimetypes for font generation.

### Reviewer guidance
Check Fufulde exercises with Fufulde interface language.
Check non-Latin fonts.

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by radinamatic** [comment]
Grabbed the assets, testing! :+1:

**Comment by radinamatic** [comment]
Everything checks out on Ubuntu, translated exercises, privacy strings, and non-Latin fonts :+1: 

ubuntu 18 04 iso start running - oracle vm virtualbox_350

ubuntu 18 04 iso start running - oracle vm virtualbox_353

On to the Windows check!

**Comment by radinamatic** [comment]
Everything checks out on Windows too! :100: 
Thank you captain! :pray:  :bowing_woman: 

win10 start running - oracle vm virtualbox_357

win10 start running - oracle vm virtualbox_356

**Review by radinamatic — APPROVED** [review]
Beautiful! :heart:

**Comment by rtibbles** [comment]
Merging now to tag a beta, @indirectlylit if there is anything fishy about my strings, let me know!

**Pull request merged**
