### PR TITLE
Removed debugger from the setup wizard #10458

### PR DESCRIPTION
**Pull request by SURAJKP**
Reviewer guidance
On a learning facility, change the facility of the last user.
After the facility change, the user should be a superuser on the device and only the target facility should be on the device.
Test that the chooseAdmin page still displays if there are other users in the source facility.
Test the workflow when creating a new account or merging accounts with an existing user in the remote facility.
Testing checklist
 Contributor has fully tested the PR manually
 If there are any front-end changes, before/after screenshots are included
 Critical user journeys are covered by Gherkin stories
 Critical and brittle code paths are covered by unit test

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by SURAJKP** [comment]
Hi @marcellamaki , please review a PR.

**Comment by rtibbles** [comment]
Hi @SURAJKP - is this fixing a specific issue? It seems all you have done is delete a heading, which is not sufficient to do what you are describing here.

**Comment by nucleogenesis** [comment]
Was there an issue made to remove the debugger? It only shows while running in development mode and can be a big help in working out how all of the data gathered combines into the final API request payload(s).

Note that I might be biased because I made it -- but I'm not seeing any reason to remove it.

And as @rtibbles noted, the changes here don't do anything to actually remove the debugger, but only the heading.

Additionally, your PR description doesn't seem to be related to the change or title - please provide more context for your intended change and why you've made it. If you're addressing a particular Issue on Github, please make note of that in your PR description.

**Comment by marcellamaki** [comment]
@nucleogenesis - @SURAJKP is referring to https://github.com/learningequality/kolibri/issues/10458, which I opened to remove the debugger when we no longer needed it. 

@SURAJKP - as I explained in a comment on this issue to another open source contributor, this issue is a reminder for the team to come back to a particular workflow and remove a debugging state that is currently in the UI at a later date. It is not something that needs to be addressed immediately. The issue is there so we don't forget, and it would be better to pick a different issue to contribute on. The LE dev team will address this issue when appropriate. You can look at [issues that are tagged with Help Wanted](https://github.com/learningequality/kolibri/issues?q=is%3Aopen+is%3Aissue+label%3A%22TAG%3A+help+wanted%22) for issues where we are seeking open source community contributions.

**Comment by SURAJKP** [comment]
Hey @marcellamaki , Thanks for the details.

**Comment by rtibbles** [comment]
Closing due to the above considerations.

**Pull request closed without merging**
