### PR TITLE
Implement preview button on exercise difficult question list page

### PR DESCRIPTION
**Pull request by bjester**
### Summary

Fixes https://github.com/learningequality/kolibri/issues/5636 by implementing <kbd>Preview</kbd> on Reports page for Exercise's Difficult Questions

### Reviewer guidance

Ensure you have an exercise set up in a lesson, then go to `Coach > Reports > Lessons > '<lesson>' > Difficult questions` and press the Preview button

### References

https://github.com/learningequality/kolibri/issues/5636

----

### Contributor Checklist

PR process:

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] ~If this is an important user-facing change, PR or related issue has a 'changelog' label~
- [ ] ~If this includes an internal dependency change, a link to the diff is provided~

Testing:

- [X] Contributor has fully tested the PR manually
- [ ] ~If there are any front-end changes, before/after screenshots are included~
- [ ] ~Critical user journeys are covered by Gherkin stories~
- [ ] ~Critical and brittle code paths are covered by unit tests~

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
Code makes sense to me. @radinamatic would you be able to confirm the fix on this PR?

**Review by rtibbles — APPROVED** [review]
Manual testing shows the issue fixed here!

**Comment by radinamatic** [comment]
So the original issue has been resolved after installing the asset from this PR, exercise preview opens from the Difficult questions subtab :+1: 

@rtibbles 
Some images are not loading correctly in the Perseus exercises in this build:

1. I first installed it on top of the previous 0.12.4b7 install where exercise was displayed correctly
2. Then I tried on top of a previous install of Kolibri 0.10.3 (where the Perseus image was also correct)
3. Last on a fresh VM with no previous Kolibri installed, where I imported the same topic from the KA FR

In all 3 cases the same exercise was missing the image. Could something be wrong with the Perseus plugin in this build...?

Ubuntu16 04 (0 10 3)  Running  - Oracle VM VirtualBox_090
Ubuntu16 04 (0 10 3)  Running  - Oracle VM VirtualBox_093
Ubuntu16 04 (0 10 3)  Running  - Oracle VM VirtualBox_092
Ubuntu16 04 (0 10 3)  Running  - Oracle VM VirtualBox_091

**Comment by rtibbles** [comment]
Odd. Does seem more likely an issue with the renderer if it happened on upgrade. 

Please file an issue.

**Pull request merged**
