### PR TITLE
Haitian creole

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Adds the ability to add our own copies of locale data for locales not supported by intl.js and/or vue-intl's locale data
* Adds copies of these for Haitian Creole
* Adds Haitian Creole as a supported language

## Reviewer guidance
Check the interface in Haitian Creole, paying particular attention to places where relative time formatting is used, and other rendering of dates and times.

Screenshot from 2023-02-27 18-39-26

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
Hi @rtibbles here are the small number of issues I was able to identify:
1. All input fields are stretched, valid only for Creole:



2. In the the Library search the labels of the dropdowns are not positioned correctly for Creole:



3. The text in the search field is cut-off but that's also the case for other languages, so I'm just mentioning it:

**Comment by rtibbles** [comment]
This feels like a line height issue. Will look into it - thanks!

**Comment by holta** [comment]
Side question:

Is Haitian Creole (Kreyòl ayisyen) expected to be a part of Kolibri 0.16 and usable by around mid-2023?

**Comment by rtibbles** [comment]
This PR is targeted to be included in a 0.15.x patch release - while we have stopped most significant updates in the 0.15.x series to focus on releasing 0.16.0, we will be releasing some low risk minor bug fixes, as well as this update with Haitian Creole language support.

**Comment by rtibbles** [comment]
Thanks @pcenov - it looks like there had been an issue with font file generation, I had a stale copy of language_info.json that caused it to skip generating the font files for Haitian Creole, and so it just didn't generate them! With the font files in place, this seems to behaving as expected:

image

**Comment by radinamatic** [comment]
Confirming that the with the fonts properly loaded, the text input fields are looking good again 👍🏽 

I also checked the strings with time intervals, and they also seem to be good:

1 | 2
--- | ---
Selection_038 | Selection_039

**Review by radinamatic — APPROVED** [review]

**Review by nucleogenesis — APPROVED** [review]
Code requested for review LGTM!

**Comment by holta** [comment]
Who can add Haitian Creole (kreyòl ayisyen) to Kolibri's docs in places like https://kolibri.readthedocs.io/en/latest/manage/options_ini.html#configure-supported-languages ?

**Comment by holta** [comment]
> Who can add Haitian Creole (kreyòl ayisyen) to Kolibri's docs in places like https://kolibri.readthedocs.io/en/latest/manage/options_ini.html#configure-supported-languages ?

A new screenshot might also be added here:
https://kolibri.readthedocs.io/en/latest/access/change_language.html

(3 languages are missing from the screenshot...)

1. kreyòl ayisyen (Haitian Creole)
2. ελληνικά (Greek)
3. українська мова (Ukrainian)

image

**Pull request merged**
