### PR TITLE
Fix 0.5 release branch + fixes to dist

### PR DESCRIPTION
**Pull request by benjaoming**
## Summary

 * [x] Fixes pre commit for python import sorter (relevant for all branches)
 * [x] Cherry picks Android APK buildkit changes (which fixes broken Buildkite)
 * [x] Updates setup.py to remove `setup_requires` (required for Debian builds, and YAGNI)
 * [x] Removes stale BDD example code (YAGNI)
 * [x] Should not ship BOTH with bundled deps as dependencies **BIG WOOPS**

Regarding the **BIG WOOPS**: This affects everything shipped so far. We have dependencies bundled AND specify them so they get pip installed, too.

pytest-runner allows us to do `setup.py test` such that it invokes pytest - however, we haven't fixed our sources to actually work without tox.ini, so only tox invocation works currently, anyways.

The problem with `setup-requires` is that it breaks default Debian building, and potentially other ways of building too (Debian's pybuild blocks requesting URLs for dependencies while building)

I've started building Debian packages in 0.5.0, which is why I'm lobbying for this change - but there's also a broken pre-commit hook, which is nicely dealt with.

I suppose we still intend to sync branches like release-v0.5.x into release-v0.6.x

### CODE REVIEW

**Comment by benjaoming** [comment]
Unexpected bumps while building the Debian package, not at all intentional changes here - or now they are :)

**Comment by indirectlylit** [comment]
It might be easier to just target this to develop, 0.7 - the initial public release.

I don't believe there's a need to make old releases available as debian packages?

**Comment by indirectlylit** [comment]
actually - did we need deb for 0.6 @jamalex ?

**Comment by benjaoming** [comment]
@indirectlylit 

If the 0.5 branch is still relevant to someone and has to be supported, I would merge this because of the fixes stated in the description.

**Comment by benjaoming** [comment]
This is ready now, please see the above description.

**Comment by indirectlylit** [comment]
Would you mind providing some notes on how to test this? We can give it a go and get it merged in.

> If the 0.5 branch is still relevant to someone and has to be supported, I would merge this because of the fixes stated in the description.

It's not harmful to merge in, but we don't have any plans to release another version of 0.5 so this won't impact any users.

(This PR has conflicts with 0.6 and develop, which is why I was suggesting it would be easier to skip 0.5)

**Comment by benjaoming** [comment]
> (This PR has conflicts with 0.6 and develop, which is why I was suggesting it would be easier to skip 0.5)

Conflicts you say? It's confusing that `release-v0.5.x` isn't mergeable into `release-v0.6.x` - isn't that breaking some assumptions?

**Comment by benjaoming** [comment]
> Would you mind providing some notes on how to test this? We can give it a go and get it merged in.

Hmm, not sure how to test it as such - it's more I think a code review thing.

Maybe if it's verified that the artifacts from Buildkite are okay, then it's easy to say that the critical setup.py changes are okay? .deb builds are okay!

I can get this merged into the other branches after it lands in 0.5.0 - btw that's our current 'stable' release which is why I built the .debs for it, don't know if I ever mentioned that!! :)

**Comment by indirectlylit** [comment]
>  It's confusing that release-v0.5.x isn't mergeable into release-v0.6.x - isn't that breaking some assumptions?

nope - 0.6 is fully up-to-date with the current state of 0.5. 

There are just a couple minor conflicts with this PR, particularly with this line: https://github.com/learningequality/kolibri/blob/release-v0.6.x/Makefile#L68

**Comment by benjaoming** [comment]
I dare merge this now. I've added a changelog entry as an unreleased '0.5.1dev'. The rationale would be the following:

 * Something serious enough was fixed in the 0.5.x series, so that should be released
 * Merging this branch into the other branches will give a conflict that I need to solve for the changelog. This is welcomed, as the 0.5.x changelog has to be inserted below other changelogs.

Once 0.5.1 is released, we will have to sync branches again, and the changelog will have a version bump - but this part shouldn't give any merge conflicts, as the 0.5.1dev entry is already there.

**Comment by benjaoming** [comment]
Have tested the .pex and it works fine. Looking at file sizes, it doesn't seem like we have any problems with missing dependencies, neither.. all sizes remain intact.

The Android APK is now 38 MB (before: 21 MB), but guessing the build is very different now @christianmemije ?

**Pull request merged**
