### PR TITLE
For Nigeria Deployment from dadeng

### PR DESCRIPTION
**Pull request by dade-ally**
## Summary

Please provide a link to the APK once the issue is resolved and the APK builds

## TODO

- [ ] Have tests been written for the new code?
- [ ] Has documentation been written/updated?
- [ ] New dependencies (if any) added to requirements file
- [ ] Add an entry to CHANGELOG.rst
- [ ] Add yourself it AUTHORS.rst if you don't appear there

## Reviewer guidance

*If you PR has a significant size, give the reviewer some helpful remarks*

## Issues addressed

List the issues solved or partly solved by the PR

## Documentation

If the PR has documentation, link the file here (either .rst in your repo or if built on Read The Docs)

## Screenshots (if appropriate)

They're nice. :)

### CODE REVIEW

**Comment by indirectlylit** [comment]
Thanks David - waiting on https://github.com/learningequality/kolibri-kivy/issues/11

**Comment by indirectlylit** [comment]
Hi @dade-ally – looks like we've still got one outstanding PR that needs to be merged before the APK will build properly. See #2202

thanks for your patience

**Comment by indirectlylit** [comment]
Hi @dade-ally -

Thanks for your patience. Here's [the link to the built APK](https://www.googleapis.com/download/storage/v1/b/le-downloads/o/kolibri%2Fbuildkite%2Fbuild-2175%2F2728%2Fkolibri-0.6.dev020170928223827_git-py2.py3-none-any.apk?generation=1506639288357773&alt=media) with the alternative content server location.

Note that I rebased your change to v0.6.x rather than develop and force-pushed to your repo. If this doesn't make sense, don't worry about it :)

**Comment by christianmemije** [comment]
@dade-ally New APK download link https://www.googleapis.com/download/storage/v1/b/le-downloads/o/kolibri%2Fbuildkite%2Fbuild-2175%2F3143%2Fkolibri-0.6.dev020171020180700_git-py2.py3-none-any.apk?generation=1508523835871871&alt=media

**Pull request closed without merging**
