### PR TITLE
Users export to csv

### PR DESCRIPTION
**Pull request by jredrejo**
### Summary

Export to a csv file of users, their roles, classrooms and users assignments and enrollement to these classrooms.
The resulting csv follows the schema related at https://docs.google.com/document/d/1CobblEL--x7iyolahdY5f2PgGnTdvJetskIESyfDXP0/edit

The output format of the file will be the same used as an input for the `bulkimportusers` command

So far, this PR includes the backend part.
Using the command:
`kolibri manage bulkexportusers `
The output will produce a csv file in the kolibri temp folder. Other options of the command are 
`--output-file=`name_of_the_file  (to be created in the folder where the command is executed)
`--facility=`id_of_the_facility whose users will be exported (if not provided it will use the default facility)
`--overwrite` to overwrite, if exists, a previous file with the name of the output file

Using the frontend:
Export the users and check the data, specially enrolled and assigned classes match the current facility

### Reviewer guidance

- Try to execute the command in an existing Kolibri installation, example:

`kolibri manage bulkexportusers --output-file=kk.csv`

- Signed as an user with admin right in an existing kolibri server, do a POST to 
/api/tasks/tasks/exportuserstocsv/
Afterwards, looking at the /api/tasks/tasks/  page the job should be complete and including the csv filepath in its metadata. Example:
```
    {
        "status": "COMPLETED",
        "exception": "None",
        "traceback": "",
        "percentage": 1.0,
        "id": "10f07fee56f44cd29abbe0fec40ed615",
        "cancellable": false,
        "type": "EXPORTUSERSTOCSV",
        "started_by": "6a256feb4d882f5d90b862f83e789166",
        "overall_error": [],
        "users": 4,
        "filename": "tmpa6k0ibe_.download"
    }
```

### References
Relates #6674 

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
Looking good!

However I'm seeing a few discrepancies between the export and actual data.

## My data

| Classes |  Users |
|--|--|
|image | image |

## Output

Username | Password | Full name | User type | ID number | Birth year | Gender | Enrolled in | Assigned to
-- | -- | -- | -- | -- | -- | -- | -- | --
learner |   | learner | LEARNER |   |   |   |   | first class
learner2 |   | learner2 | LEARNER |   |   |   |   | Individual learners,my group,second class
student4now |   | Alice | LEARNER | ABC123 | 2008 | MALE |   |  
teach4life |   | Mr Jones | COACH |   | 1975 |   | Geometry, Geometry, Geometry, Geometry | Algebra 1, Geometry

## Discrepancies observed

* Some users are missing
* "Enrolled in" column has duplicate entries for a single class ("Geometry")
* "Assigned to" column includes groups in addition to classes ("Individual learners" and "my group" are not classes)
* Passwords are not included. Should they be? 🤔 

Finally, when I went to re-import the file that was just exported, I got this error:

```
ERROR    Job 15c72f76303d4802accabc75487214fd raised an exception: Traceback (most recent call last):
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/worker.py", line 73, in handle_finished_future
    result = future.result()
  File "/Users/d/.pyenv/versions/3.7.6/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/Users/d/.pyenv/versions/3.7.6/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/d/.pyenv/versions/3.7.6/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/worker.py", line 224, in wrap
    return f(*args, **kwargs)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/job.py", line 178, in y
    result = func(*args, **kwargs)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/management/commands/base.py", line 102, in handle
    return self.handle_async(*args, **options)
  File "/Users/d/Projects/le/k013x/kolibri/core/auth/management/commands/bulkimportusers.py", line 553, in handle_async
    self.exit_if_error()
  File "/Users/d/Projects/le/k013x/kolibri/core/auth/management/commands/bulkimportusers.py", line 528, in exit_if_error
    raise CommandError("File errors: {}".format(str(self.overall_error)))
django.core.management.base.CommandError: File errors: ['Mix of valid and invalid header labels found in first row']
```

**Comment by jredrejo** [comment]
> Looking good!
> 
> However I'm seeing a few discrepancies between the export and actual data.
> 
> ## My data
> Classes	Users
> image	image
> ## Output
> Username	Password	Full name	User type	ID number	Birth year	Gender	Enrolled in	Assigned to
> learner	 	learner	LEARNER	 	 	 	 	first class
> learner2	 	learner2	LEARNER	 	 	 	 	Individual learners,my group,second class
> student4now	 	Alice	LEARNER	ABC123	2008	MALE	 	 
> teach4life	 	Mr Jones	COACH	 	1975	 	Geometry, Geometry, Geometry, Geometry	Algebra 1, Geometry
> ## Discrepancies observed
> * Some users are missing
> * "Enrolled in" column has duplicate entries for a single class ("Geometry")

For the above two problems: would you mind emailing me your database. For the missing users I can imagine the reason (they are not in any classroom enrolled not assigned) but for the duplicated entries I have no clue (unless you have several rows for the same user in the memberships table, what should not be happening unless there's a bug in Kolibri)


> * "Assigned to" column includes groups in addition to classes ("Individual learners" and "my group" are not classes)

I never thought we should exclude groups, I can do it easily if needed.


> * Passwords are not included. Should they be? thinking
> 

They are encrypted in the database, theorically we can't unencrypt them (I would be worried if we can )


> Finally, when I went to re-import the file that was just exported, I got this error:
> 
> ```
> ERROR    Job 15c72f76303d4802accabc75487214fd raised an exception: Traceback (most recent call last):
>   File "/Users/d/Projects/le/k013x/kolibri/core/tasks/worker.py", line 73, in handle_finished_future
>     result = future.result()
>   File "/Users/d/.pyenv/versions/3.7.6/lib/python3.7/concurrent/futures/_base.py", line 428, in result
>     return self.__get_result()
>   File "/Users/d/.pyenv/versions/3.7.6/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
>     raise self._exception
>   File "/Users/d/.pyenv/versions/3.7.6/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/Users/d/Projects/le/k013x/kolibri/core/tasks/worker.py", line 224, in wrap
>     return f(*args, **kwargs)
>   File "/Users/d/Projects/le/k013x/kolibri/core/tasks/job.py", line 178, in y
>     result = func(*args, **kwargs)
>   File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 131, in call_command
>     return command.execute(*args, **defaults)
>   File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
>     output = self.handle(*args, **options)
>   File "/Users/d/Projects/le/k013x/kolibri/core/tasks/management/commands/base.py", line 102, in handle
>     return self.handle_async(*args, **options)
>   File "/Users/d/Projects/le/k013x/kolibri/core/auth/management/commands/bulkimportusers.py", line 553, in handle_async
>     self.exit_if_error()
>   File "/Users/d/Projects/le/k013x/kolibri/core/auth/management/commands/bulkimportusers.py", line 528, in exit_if_error
>     raise CommandError("File errors: {}".format(str(self.overall_error)))
> django.core.management.base.CommandError: File errors: ['Mix of valid and invalid header labels found in first row']
> ```

I have just fixed it, the `Identifier` header was incorrect in the export. I had set it to `ID number` instead.

**Comment by jredrejo** [comment]
i18n applied to error messages:
image

**Review by indirectlylit — APPROVED** [review]
great job!

Needs more testing but an initial test looked good. Opened one follow up issue: https://github.com/learningequality/kolibri/issues/6749

Next, we'll want to write unit tests and gherkin stories.

**Pull request merged**
