### PR TITLE
[DO NOT MERGE] Flatpak MVP build PR

### PR DESCRIPTION
**Pull request by indirectlylit**
This PR tracks changes from the `flatpack-mvp` release branch, as compared to `release-v0.13.x` branch, which it was originally based on, via the `app-support` branch.

Notes:

* these builds will be used for short-term releases through flatpack, and so changes to this branch should be kept low-risk
* changes should be associated with the `flatpak-mvp` milestone: https://github.com/learningequality/kolibri/milestone/53
* all changes in here should be periodically merged to `app-support`: https://github.com/learningequality/kolibri/tree/app-support
* both `flatpack-mvp` and `app-support` should be merged periodically to `develop` and/or  `release-v0.14.x` for the 0.14.0 release
* neither `flatpack-mvp` or `app-support` should _ever_ be merged to the `release-v0.13.x`

### CODE REVIEW

**Comment by benjaoming** [comment]
Not a Flatpak advocate, just wanna note that it's spelled Flatpak without the "c" :innocent:

**Comment by wjt** [comment]
I think this is now past-tense?

**Comment by rtibbles** [comment]
@wjt meaning that we can close this PR?

**Comment by wjt** [comment]
Yes – the Flatpak is on Flathub, and (correct me if I'm wrong) I think it's now based on mainline Kolibri, or at least not this mvp branch. @dylanmccall correct me if I'm wrong!

**Comment by dylanmccall** [comment]
Yep, that's correct. The Kolibri flatpak uses a dedicated desktop front-end and launcher, which is over here (along with a reference manifest file in build-aux/flatpak):

https://github.com/learningequality/kolibri-installer-gnome

It is published on Flathub, over here:

https://github.com/flathub/org.learningequality.Kolibri

It is applying a small patch (from #7714, which needs a bit more work to be in Kolibri proper), but otherwise uses vanilla Kolibri from pypi.

**Comment by rtibbles** [comment]
All commits in this branch appear to be in release-v0.14.x so am deleting the branch also.

**Pull request closed without merging**
