### PR TITLE
trying to update VF to 0.2.0

### PR DESCRIPTION
**Pull request by indirectlylit**
trying to upgrade, but it doesn't work...

```
ImportError: No module named auth.phone_hashing_settings
```

would also be preferable to reference a tag instead of a git hash

### CODE REVIEW

**Comment by rtibbles** [comment]
When do you get this error? During plugin activation?

**Comment by indirectlylit** [comment]
when running the devserver

```
(le2)~/P/l/r/k2 (release) $ Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/d/Projects/learning_equality/repos/k2/kolibri/__main__.py", line 8, in <module>
    main(args=sys.argv[1:])
  File "kolibri/utils/cli.py", line 279, in main
    django.setup()
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named auth.phone_hashing_settings
child_process.js:533
    throw err;
    ^

Error: Command failed: python -m kolibri manage webpack_json -- --outputfile /var/folders/n9/k997qvqs3f7_m_310crwsxyc0000gp/T/117213-25852-2fnihj.utj9u7syvi.json
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/d/Projects/learning_equality/repos/k2/kolibri/__main__.py", line 8, in <module>
    main(args=sys.argv[1:])
  File "kolibri/utils/cli.py", line 279, in main
    django.setup()
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named auth.phone_hashing_settings

    at checkExecSyncError (child_process.js:490:13)
    at execSync (child_process.js:530:13)
    at module.exports (/Users/d/Projects/learning_equality/repos/k2/frontend_build/src/read_webpack_json.js:10:3)
    at readBundlePlugins (/Users/d/Projects/learning_equality/repos/k2/frontend_build/src/read_bundle_plugins.js:34:17)
    at Object.<anonymous> (/Users/d/Projects/learning_equality/repos/k2/frontend_build/src/webpack.config.js:14:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by indirectlylit** [comment]
Looks like `auth` is missing from the instant schools manifest

**Comment by indirectlylit** [comment]
out-of-date

**Pull request closed without merging**
