### PR TITLE
Reintroduction of Android Builds

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

Reintroducing Android to the Kolibri build pipeline!

### Reviewer guidance

Monitor build - Android pipeline should be triggered, but the artifact shouldn't be build unless you explicitly unblock the step. If it _has_ been triggered, ensure that the build passes.

Signing is enabled on the Android build pipeline, but still thinking through the best way to trigger it. In any case, that would probably be handled by the Android pipeline anyway. Adding the `LE_TRIGGERED_FROM_KOLIBRI_VERSION_TAG` envar just in case.

### References

Redo of #6413 
#6421 
#6413 
#2451

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

Tagging @indirectlylit @rtibbles and @jamalex because I think they'd be interested to know this is coming in.

### CODE REVIEW

**Comment by lyw07** [comment]
do you mind pulling from the latest app-support branch? it should have the fix for the build failure now. thank you! :)

**Comment by DXCanas** [comment]
@lyw07 After a rebase, seems to be working great :)

**Comment by indirectlylit** [comment]
ready to merge? Or more work to be done?

**Comment by lyw07** [comment]
It looks like the android build itself failed. https://buildkite.com/learningequality/kolibri-android-installer/builds/151#8694cd54-ac79-46f1-a712-5a04cf4bc715
Is this expected and will be fixed in another PR? thank you!

**Comment by DXCanas** [comment]
Yeah, seems like the branches are all out of wack on the android side, as they're under active development. I think this should be merged, and the android build fixes will happen in that repo!

**Pull request merged**
