### PR TITLE
update changelog

### PR DESCRIPTION
**Pull request by indirectlylit**
fixes https://github.com/learningequality/kolibri/issues/6422

please check for typos and correctness

### CODE REVIEW

**Comment by lyw07** [comment]
looks like the travis failed at a demographic data related test... not sure why:
```
{'dsl': {'bys': {'a': 1966.4, 'd': 0, 'ns': 0, 'sd': 17.51, ...}, 'gc': {'DEFERRED': 7, 'MALE': 4, 'NOT_SPECIFIED': 9}}} != {'dsl': {'bys': {'a': 1966.4, 'd': 0, 'ns': 0, 'sd': 17.51, ...}, 'gc': {'DEFERRED': 7, 'FEMALE': 0, 'MALE': 4, 'NOT_SPECIFIED': 9}}}
```

also do you mind pulling latest release branch to make buildkite build pass? thank you!

**Comment by indirectlylit** [comment]
pushed

**Review by jonboiser — APPROVED** [review]

**Comment by lyw07** [comment]
I canceled the build to get a change in the rpi build in first, because otherwise this build would fail. I will retry the build afterwards

**Comment by lyw07** [comment]
force merging this since there's no code change. the build is taking more time than I expected.

**Pull request merged**
