### PR TITLE
Creating useSnackbar composable and replacing existing logic with it

### LINKED ISSUE #12206: Create composable for snackbar state and replace existing logic with it
Currently the snackbar state is handled by [vuex state](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/state/modules/snackbar.js).

This should be replaced by a composable module exposed on the core API that provides access to the state and methods for manipulating the snackbar. All state should be stored in the module to provide a global store.

### PR DESCRIPTION
**Pull request by nathanaelg16**
## Summary
This change creates a new `useSnackbar` composable and migrates existing logic to use it.

## References
- Fixes #12206

## Testing checklist

- [X] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by nucleogenesis** [comment]
Thank you for this @nathanaelg16 -- I'm going to give this a closer look early next week and test it out and I'm looking forward to it :)

**Comment by rtibbles** [comment]
I have taken a first look at this, and nothing raised any concerns.

We just merged a PR up from release-v0.17.x which has caused a merge conflict, so if you could rebase and fix that, that would be great!

**Review by rtibbles — COMMENTED** [review]
This all seems correct, and very straight forward! I'll do a quick manual test to ensure there's nothing concerning here, but I don't see any reasons to think so from the code.

**Review by rtibbles — APPROVED** [review]
A quick manual QA of several affected places shows no regressions. This is good to go!

**Comment by rtibbles** [comment]
Excellent work again, @nathanaelg16 - this is very thorough and systematic!

**Pull request merged**
