### PR TITLE
Build System Docs

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

Was surprised to find that sphinx parsed and converted Markdown, too!

Can leave as is or begin converting to rst, but structure will likely remain the same. 

### Reviewer guidance

`make docs`, then check out the build HTML under "Build System"

### References

resolves https://github.com/learningequality/kolibri/issues/7089

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
let me know when you'd like me to review

**Comment by DXCanas** [comment]
> let me know when you'd like me to review

I think what I really want to know is if I should bother translating it to RST￼

**Comment by indirectlylit** [comment]
If it works (in the sense of appearing correctly in the TOC and having headers etc formatted consistently) I don't think it's necessary

**Comment by DXCanas** [comment]
Then it's ready!

**Comment by radinamatic** [comment]
> ...surprised to find that sphinx parsed and converted Markdown, too!

Told you it would :wink: 

I'm not very well versed in the build system engineering, so I cannot really comment on the content of these docs until I manage the time to do more than click the `Restart build` button on Buildkite :relaxed: 

Just a few comments regarding the writing and structure:

* Switch to the sentence case for headings to be consistent with the rest of the dev docs
* Drop the word _documentation_ and rename the H1 to `Build system and workflow` or similar, for example
* Move the doc one item below in the main TOC (just under the `Development workflow`). To me at least, it seems like a more organic place for the build docs.
* Does this subheading nesting feels OK? Not saying it shouldn't, mostly checking because FAQ on top looks a bit awkward to me... 
  Selection_054


No need to go deeper in the language style edits at this point: dev docs are the result of many voices and writing styles that would require a major push to fully edit, revise and update. Just bumped into a phrase with `...For an upcoming 0.3.0 release...` :joy:

**Comment by indirectlylit** [comment]
> Does this subheading nesting feels OK? Not saying it shouldn't, mostly checking because FAQ on top looks a bit awkward to me...

I think it's fine to lead with the FAQs if they are in fact frequently asked. Might actually spell it out though.

However, the nesting goes too deep. I think the "Architecture" section can be flattened significantly, leaving an outline like:

* Build system
    * Frequently asked questions
    * Design goals
    * Overview of Buildkite
        * API and concepts
        * Github integration
        * Agents
        * Self-hosting
    * Pipelines
    * Pipeline orchestration
    * Block steps
    * Release builds

**Comment by DXCanas** [comment]
I actually put in the FAQ's based on the issue that spurred the docs:
#7089 

Based on the fact that those were put in there, I just assumed they were "frequently asked". I can rename or move the section if y'all think it's necessary :man_shrugging:

**Comment by DXCanas** [comment]
That nesting might not make the most sense, I think. 

Pipelines
Pipeline orchestration
Block steps
Release builds

Shouldn't all be at the same conceptual "level" IMO

Pipelines is describing LE's use of pipelines. Orchestration, block steps, and release builds are all children of that concept; they don't make a lot of sense out of the overarching context of "LE's use of pipelines". That's also why it's named that way. Pipelines themselves were defined in the Buildkite section. We're doing things a little differently, making use of niche features that aren't well documented in Buildkite's docs.

**Comment by DXCanas** [comment]
This is what I went with:
image
image

**Comment by radinamatic** [comment]
Looks good to me :100:, but I'll leave the last word to @indirectlylit!

**Review by indirectlylit — APPROVED** [review]
let's do it

**Comment by DXCanas** [comment]
Checking travis errors before merge

**Pull request merged**
