### PR TITLE
Allows superusers and those with can_manage_content permision to access '/ispinvalid' API resource

### LINKED ISSUE #10238: The device management PIN functionality is not functioning correctly on a Learn-only device
## Observed behavior
After creating a Learn-only device I do see the PIN modal however it's not accepting the the PIN. Also after removing the PIN from the main facility and restarting both servers, the PIN modal is still being displayed.

## Expected behavior
Fully functional PIN functionality.

## Steps to reproduce the issue
1. Install the the [following build ](https://buildkite.com/learningequality/kolibri-debian/builds/6281) 
2.  Setup a full facility and add a Device management PIN at Facility > Settings
3. Setup a Learn-only facility and attempt to import a channel.

## Usage Details
Windows 10, Ubuntu 22  - Chrome

### PR DESCRIPTION
**Pull request by akolson**
## Summary

This pr fixes issues raised [here](https://github.com/learningequality/kolibri/issues/10238) related to the device management pin feature picked up during manual QA. The `/ispinvalid`(previously `/is-pin-valid` before this fix) resource has been updated to allow access to both superusers and users with the `can_manage_content` permission.

## References

Fixes https://github.com/learningequality/kolibri/issues/10238 https://github.com/learningequality/kolibri/issues/10275

## Reviewer guidance

Please see https://github.com/learningequality/kolibri/pull/10135

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
Code read through makes sense to me. QA sign off and we can merge!

**Comment by pcenov** [comment]
Hi @akolson I confirm that the PIN modal is displayed correctly now on a Learn-only device and the PIN is accepted. I have reported separately the following issues: https://github.com/learningequality/kolibri/issues/10273, https://github.com/learningequality/kolibri/issues/10274, https://github.com/learningequality/kolibri/issues/10275

It's also worth mentioning that I am being prompted to enter the PIN several times while in the Device plugin which seems a bit excessive and should be further discussed:

https://user-images.githubusercontent.com/79847249/225896993-fc6c1bea-3f58-4fb0-baf3-2305a997041b.mp4

**Comment by akolson** [comment]
Hi @pcenov I appreciate the feedback. Concerning the pin prompt being requested several times, the authentication expires in 15 seconds according to the spec. @marcellamaki, @rtibbles  and probably @jtamiace,@tomiwaoLE can weigh in on this on how we could better align this

**Comment by marcellamaki** [comment]
Hi @akolson and @pcenov - Thanks for flagging. You definitely implemented according to spec, but I did not write a very well-thought-out spec. Sorry about this! 

So, for this part:
> A user should not be able to navigate directly via a URL without being prompted to authenticate, but should not have to enter the PIN twice, once when pressing "Device" in the navigation, and then again when redirected

The 15-second here was not very well thought out, and I was thinking only of the experience of the user being redirected to the route. I do not have enough context of your implementation at the top of my mind, Samson, but depending on how you did this, there is probably a check on the route that prompts the user to enter a PIN on route enter. 

When the user presses "Device", they are prompted to enter the PIN on that event, even though they have not actually been redirected, yet. Then, we want to make sure that they don't get that second prompt, based on the check associated with the "on route enter" check.

But, now that I think about it more, I do think there would be value in having this cookie persist longer, although I am not sure what interval might be appropriate. Perhaps 15 minutes, while the admin is working on the tablet? And/or, perhaps the cookie could be cleared on navigation back to Learn. So, if you are doing a task, and you have completed and you pass the device back to the learner, you can just click back into learn, and know that they will not have the ability to continue the admin session in device (intentionally or inadvertently)

@rtibbles any other thoughts, ideas, or context? Sorry @akolson that we are figuring some of this out very much on the fly. Thank you for your patience.

**Comment by akolson** [comment]
Thanks @marcellamaki for this, and no worries. Some features only get better after such refinements :). I still appreciate the detail put into these issues regardless. 

Now concerning the implementation, on a very high level, the PIN check(if set up in facility settings) happens just before a user is redirected to any of the device plugin's routes. The stored cookie is checked in the process to avoid re-authentication if it is still valid. This all happens in the `beforeResolve` navigation guard of the device plugin.

My thinking during implementation of this issue was to remove cookie expiry when browsing within the device plugin and set it with expiry after navigating away to other plugins but my approach highly depended on using the `beforeResolve` navigation guard within the context of cross plugin navigation which currently has it's limitations as each plugin's navigation is treated in complete isolation. I am very happy to hear thoughts on other ways this could be achieved, while maintaining the same approach or otherwise @rtibbles?

**Comment by rtibbles** [comment]
A simple fix for not forcing reauthentication with the PIN while navigating within the Device plugin might be to first try to read the value from a stored value in Javascript (so some global state in Javascript) and then to read it from the cookie. If the cookie is set, also set the global JS state.

If the cookie is not set, do the PIN auth, and then set both the cookie and the JS state. The JS state will persist within navigation within the device tab unless someone does a hard refresh on the page, but will not persist once someone has navigated away from the Device plugin. I feel like this might prevent continual reauthentication while still making it not persist too long?

**Comment by akolson** [comment]
Thanks Richard for the suggestion. Let me try this out and revert.

**Comment by akolson** [comment]
Multiple PIN prompting while navigating within the Device plugin has been resolved, thanks to @rtibbles @marcellamaki. Below is a description of the various scenarios under which it will be shown provided PIN authentication has been setup;

- Initially prior to inputing of the PIN
- Navigating to Device plugin, authenticating with PIN, navigating to other plugin, and returning back to the device plugin after 15 second(The time taken for the cookie to expire)
- If you refresh your current page within the Device plugin when the cookie session has expired(Expires within 15 second)

**Comment by pcenov** [comment]
Hi @akolson now no matter what I do the PIN modal never shows up. I'm testing using the following build: https://buildkite.com/organizations/learningequality/pipelines/kolibri-debian/builds/6373/jobs/018705db-d71e-4a07-85d3-8c024059e354/artifacts/01870924-419a-497b-a711-c1b7f1b36b8e
Could you please check as well?

**Comment by akolson** [comment]
Hi @pcenov , My apologies, I committed a piece of test code that disables the PIN prompt on LODs. This has been reverted and all should be fine now.

**Comment by pcenov** [comment]
@akolson I confirm - now the PIN modal is displayed as described in your comment and it's much more user friendly. Thanks!

**Review by radinamatic — APPROVED** [review]
We pinned the PIN, go us!!! 🎉 💯 :shipit:

**Pull request merged**
