### PR TITLE
Username

### PR DESCRIPTION
**Pull request by photon0205**
Whenever I open kolibri this issue always irritated me, so I corrected it myself and saw an issue regarding it so I resolved the issue #10288

### CODE REVIEW

**Comment by rtibbles** [comment]
Thanks for the contribution @photon0205 - could you ensure that you have run linting on your changed files? Seems like you may not have pre-commit installed. https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#linting-and-auto-formatting

**Comment by rtibbles** [comment]
(or rather, looking at your commit history, it appears that linting did get run, but not the correct linting)

**Comment by photon0205** [comment]
@rtibbles now is it good?

**Comment by rtibbles** [comment]
Yes, linting is now passing!

**Review by rtibbles — APPROVED** [review]

**Pull request merged**
