### PR TITLE
setup wizard "back" button handling

### LINKED ISSUE #9027: Browser's back button behaves differently in setup flow than on-page back button
## Observed behavior

If you use the browser's back button in the setup flow, the experience is different than using the on-page back button which behaves properly.

## Errors and logs

No errors / logs

## Expected behavior

The browser's back button should behave the same as the in-page back button

## User-facing consequences

- A broken setup flow experience and user confusion

## Steps to reproduce

1. Start a fresh instance of Kolibri
2. Continue past the language selection and select `Quick start`
3. Observe you're properly presented with the `Create super admin account` form
3. Go back using browser's back button
4. Select `Advanced setup` instead of `Quick start` and proceed
5. Observe you're incorrectly presented with the `Create super admin account` form again, but should be presented with the facility name form
6. Click browser's back button again
7. Select `Quick start` again and proceed
7. Observe you're incorrectly presented with the `Select a facility setup for this device` form, having never even entered a facility name

## Context

Kolibri 0.15.0
Ubuntu 20.04
Chrome 97.0.4692.71
Perhaps related to https://github.com/learningequality/kolibri/issues/7343

### LINKED ISSUE #10240: SetupWizard: Verify proper functionality when going backward in the forms
## Observed behavior

@nucleogenesis has done a bit of this, but this would be worth reviewing.

During the code review, @jredrejo noted that you can use [XState's History](https://xstate.js.org/docs/guides/history.html) to go directly back to a previous state -- however it should be noted that a user's selection from forms are saved to the state machine's context _on transition_ -- so if you go back directly to the previous state the user's selection will not be reflected.

In this case, we should be sure that the user's selection is reflected in the various forms by not using the "history go back" functionality in XState, but rather to ensure that each form populates it's initial value if there is already a selection for its relevant value within the machine's context.

**[Notion Report](https://www.notion.so/learningequality/Bypass-of-credential-screen-in-Import-facility-flow-a8770add596e4c418c9dc29498c88db4?pvs=4) -**
[Another Notion Report](https://www.notion.so/learningequality/A-user-should-not-be-able-to-proceed-past-the-Select-facility-page-if-an-import-address-has-not-be-93ffa32011374777b5e49171c5791b35?pvs=4) -

#### NOTE This is a specifically noted issue to review.
 **LOD -> Create new user:** Once a user has been created, there should not be any more "Back" buttons available to the user - the`OnboardingStepBase -> noBackAction` prop is used to hide the back button.

### PR DESCRIPTION
**Pull request by thanksameeelian**
## Summary

as reported in #10240 & #9027, navigation behavior using the browser "back" & "forward" buttons in the setup wizard has not been consistent with the navigation behavior using the `Go back` & `Continue` buttons provided by the wizard UI. this led to odd and unexpected behavior, including the ability to navigate away from wizard steps that were designed to be "points of no return." in one extreme example, if you got to the second-to-last step of the wizard, used the browser "back" button to get all the way to the beginning of the wizard ("How are you using Kolibri?") and pressed the `Continue` UI button once from that page, you'd be catapulted all the way forward to the finalizing step of the wizard, the "Setting up Kolibri" view. 

with the update presented in this PR, "back" navigation using the browser buttons is disallowed within the wizard. this has been accomplished by changing instances of `$router.push` in `synchronizeRouteAndMachine` to `$router.replace`.

with these changes, now if the user engages the browser "back" button, they will be sent to wherever they were before they entered the wizard. if they go forward in the browser from that page, they will be returned to the step in the wizard where they left off. out of many attempted approaches to solve the problem, this appeared to be the cleanest solution that introduced the least unexpected behavior and general bugginess. 

### TODO: 
potentially introduce an alert before browser "back" navigation occurs, so the user can be informed that they will be exiting the wizard and they can accept this choice or reject it to remain on their present page in the wizard. currently, there are not translated strings available to convey this message to all users, so the alert has not been implemented. 

## References
fixes #10240
fixes #9027

## Reviewer guidance
- remove/rename your `.kolibri` folder or `rm -rf $KOLIBRI_HOME` so you have a fresh device
- start up kolibri in your terminal & enter the setup wizard
   - if you find yourself on an unexpected step of the wizard upon first entering it & you're using a fresh device, delete `savedState` from your browser local storage 
- navigate through the wizard using a mix of the UI buttons and browser buttons:
   - UI buttons `Go back` & `Continue` should continue to work as established & as expected
   - browser "back" should take you to the page you were on before entering the wizard
   - browser "forward" should take you to the wizard page you were on before engaging browser "back" 
      - once you are back in the wizard, browser "forward" should no longer be available
      
**Note:** if you use the browser buttons to navigate away from a page you have entered information into, that data may not be retained when you return using the browser buttons. in chrome, it may be the case that your previously-entered information is visible until you focus an element on the page. while ephemeral information may not be retained, no submitted information should ever be lost using any browser. 

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by akolson — COMMENTED** [review]
Changes look correct to me! Thanks @thanksameeelian! Tagging @radinamatic to take a look as well.

**Comment by radinamatic** [comment]
In the 'On my own' workflow I did not find any issues with either setup wizard or browser back/forward buttons behavior.

With the 'Group learning' I bumped into this not optimal and confusing situation using the browser back button where it leads to the page that asks the user to sign in despite them being far from having even created a facility or any user account at all... 😕 

https://github.com/learningequality/kolibri/assets/1457929/06e73d9d-aac6-4081-9362-5807af0ee96c

The link 'Sign in to Kolibri' does lead back to the last step in the setup wizard they were at, but it's still confusing since they can open the sidebar and see the options under the 'Learn'.

Selection_187


I know you have been discussing the various options at length, but here it seems to me that the browser back button should take the user to the page where they were on before entering the wizard, same as in the  'On my own' workflow, but currently it does not.

Tested in Firefox on Ubuntu 20.04.

**Comment by radinamatic** [comment]
Re-tested in Chrome on Ubuntu 20.04, and could not replicate (browser back button does take the user to the page where they were on before entering the wizard), so this seems to be Firefox-specific.

**Comment by thanksameeelian** [comment]
> Re-tested in Chrome on Ubuntu 20.04, and could not replicate (browser back button does take the user to the page where they were on before entering the wizard), so this seems to be Firefox-specific.

🤔 hmmm. good looking out, @radinamatic - thank you! jacob & i noted some behavioral differences between chrome & firefox while we were developing this solution, but i don't think we uncovered this exact issue. wondering if you might have any thoughts about this, @nucleogenesis?

**Comment by nucleogenesis** [comment]
Hmm... I'll try to replicate it on Firefox locally and see what is happening there to get a better idea of the cause.

**Comment by nucleogenesis** [comment]
@radinamatic I'm not able to replicate that issue on the Group Learning flows in Firefox. I think that as a follow-up issue we ought to do some checking on our "redirect the user to the setup wizard if the device isn't provisioned no matter what" check wherever that is in the code which ought to handle this error if it does come up for a user in any case.

**Comment by thanksameeelian** [comment]
@radinamatic, it's my understanding that, in addition to what @nucleogenesis writes here, when he tried again to replicate he _was_ able to but found that the bugginess was directly related to having lingering, old setup wizard data that hadn't been cleared out of his local storage when he tried the flow a second time (please correct me if i'm wrong, @nucleogenesis!)

with that in mind, i was hoping this could be re-reviewed or, if that was the only issue, resolved since (as far as i'm aware) the problem you noticed was not specifically caused by the changes introduced by this PR. i see that @pcenov may be reviewing currently, so my apologies if this is redundant/unneeded! 🙂

**Comment by radinamatic** [comment]
> he was able to but found that the bugginess was directly related to having lingering, old setup wizard data that hadn't been cleared out of his local storage when he tried the flow a second time

Yes, I asked @pcenov to try to replicate precisely for that reason. When testing all the possible setup wizard branching scenarios, **I always**:

- stop Kolibri service
- delete the `.kolibri` home folder
- delete all the cache and browser data
- check for and delete all the cookies in the browser storage
- restart the browser

Is there any other place where the _old setup wizard data_ could remain and cause the bugginess? The only other option I see for testing all the setup wizard scenarios fully from scratch is to restore the blank initial VM snapshot and install again **each time**, which makes it more cumbersome... My only concern is that going back to beginning and trying again is not completely unlikely scenario for a new Kolibri user who is unsure about various options, and may bump into the same _bugginess_ 😕

**Comment by nucleogenesis** [comment]
@radinamatic the only time I could replicate this was if I failed to do these:

> delete all the cache and browser data
> check for and delete all the cookies in the browser storage

I think the best way to avoid this is to always start each new test session with opening a brand new Incognito/Private browsing session. This will always guarantee that you're testing without errant data in place and can only get tricky if you fail to close out your Incognito windows between testing sessions.

In any case, I think that the way to handle this is to ensure that we never go anywhere but the SetupWizard when the device isn't provisioned and that we can never go to the SetupWizard when a device _is_ provisioned. I'm not sure exactly where we need to look to make this check right now.

Considering that this is an edge case that is solved with a page refresh or by clicking the link, I think that we can make a follow-up issue to investigate this and devise a solution to better defend against users ending up in this position.

**Comment by radinamatic** [comment]
> ensure that we never go anywhere but the SetupWizard when the device isn't provisioned and that we can never go to the SetupWizard when a device is provisioned. 

Sounds like a good approach for now. Let's wait for @pcenov to give it one last go, and we'll approve if nothing else jumps out at us. As I said, I was unsure if this can be easily labeled as an edge case, as I hardly see end users starting a brand new incognito session while running the Kolibri setup wizard.

**Review by pcenov — DISMISSED** [review]
In Chrome if one is starting the setup wizard for the first time with no cookies/cached data from previous interaction with Kolibri the browser's back button is disabled which effectively forces the user to use the 'Go back' button and that's fine. 
Still I was able to replicate the issue observed by @radinamatic by instead selecting a valid Kolibri link saved as a bookmark. In that case the user sees the 'You must be signed in to view this page" message and after clicking the link to the sign in page is redirected to the Setup Wizard with enabled Back button:

https://github.com/learningequality/kolibri/assets/79847249/857c07a8-925e-4690-ac9a-6bcc00eaaee6

In Firefox the browser's back button is enabled which results in weird behavior, and also allows me to go back to the Setup Wizard after having completed the setup process:

https://github.com/learningequality/kolibri/assets/79847249/b662664a-bcc7-41d6-844c-2c6f63354f3e

<del>Wanted to test this in Internet Explorer 11 as well, but the wizard was not working at all there so it's best to check if you have code which is not supported by old browsers.</del> - was some caching issue on my end I guess, works fine in IE11

**Comment by nucleogenesis** [comment]
Overall I think that the issues above can be addressed by making a query to the server to know if the server is provisioned or not every time we load up the SetupWizard -- however, it seems like Firefox maybe is trying to just present you the same page you were on from memory rather than actually navigating you to the URL?

Like -- if you finish provisioning and go back, then refresh, it redirects properly, right? Seems that the client side is just rendered by Firefox directly from memory as it was before navigating away, bypassing our server-side redirect logic altogether.

> Still I was able to replicate the issue observed by @radinamatic by instead selecting a valid Kolibri link saved as a bookmark.

I think this is a true edge case only likely to be encountered by devs and QA and, _mayyyybe_ somebody who is playing fast and loose with their Kolibri installations who would most likely be quick to fix the issue w/ a refresh.

---

I don't think we should block merging this due to a couple of edge cases like these as they are not likely to impact anybody and if they _do_ impact a user, then a refresh or clicking the link will take the user to wherever they're supposed to be anyway.

I'll defer final judgement on that to @marcellamaki and @rtibbles and think that Richard might have the best sense of how/where exactly we could make sure a user never ends up on that "Sign in..." page.

**Comment by rtibbles** [comment]
This looks like Firefox behaving badly to me - why isn't it reaching back out to the server? We have no caching headers on the setup wizard page, so it should be making a fresh request to the setup wizard URL. When IE11 is doing a better job of being a spec compliant browser, you need to look again, Firefox!

I think this can be punted to a non-release blocking follow up issue, as it is confined to a single browser, and is also not new behaviour in 0.16.0.

**Review by rtibbles — APPROVED** [review]
Code changes make sense to me - and I think the important issue here is fixed. I have moved the remaining more extreme edge cases to a follow up issue. As it is not a regression on existing behaviour, I haven't flagged it as a release blocker.

**Pull request merged**
