### PR TITLE
Do not use `--skip-update` when running Kolibri in development mode

### LINKED ISSUE #7302: First `yarn devserver` on new KOLIBRI_HOME fails first time only
### Observed behavior

I've seen this before and thought it was to do with me getting crazy with changing my KOLIBRI_HOME and branches because I used to just run all of my pip and yarn installs then retry starting the dev server - but now that I've seen it a few times I figure I should make an issue - especially after it just worked without me doing all of that reinstalling of dependencies.

1. Set your KOLIBRI_HOME to a non-existent folder
2. `yarn devserver`
3. See that it fails:

```
Traceback (most recent call last):
  File "/home/jacob/.pyenv/versions/3.7.7/bin/kolibri", line 11, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "/home/jacob/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/jacob/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/jacob/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/jacob/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jacob/Code/LearningEquality/kolibri/kolibri/utils/cli.py", line 29, in <module>
    from . import sanity_checks
  File "/home/jacob/Code/LearningEquality/kolibri/kolibri/utils/sanity_checks.py", line 10, in <module>
    from .conf import KOLIBRI_HOME
  File "/home/jacob/Code/LearningEquality/kolibri/kolibri/utils/conf.py", line 42, in <module>
    os.mkdir(KOLIBRI_HOME)
FileExistsError: [Errno 17] File exists: '/media/hdd/kolibris/14-informal'
```

4. `yarn devserver` - now it works as expected.

Looks like the new home folder is being made twice without something catching the error when it tries and fails after it first finds that the folder doesn't exist yet?

### Expected behavior

I make a new KOLIBRI_HOME and can start the devserver on the first try.

### User-facing consequences

Confusing for developers and contributors.

### Context

0.14-beta9
Debian 10
Chrome

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

Changes the `devserver` npm scripts to use the `python-devserver` script, which invokes `kolibri start` without the `--skip-update` flag. 

This means, when you start Kolibri after deleting your `KOLIBRI_HOME` folder, or updating the `KOLIBRI_HOME` variable, etc, running the devserver for the first time will create the dev database and run the migrations first.

This also uses the `run-p` shorthand to replace `npm-run-all --parallel` in the 4 scripts

I also updated the "Getting started" guide to explain this change to the onboarding experience as well as the KOLIBRI_HOME env variable.

CleanShot 2021-03-30 at 18 19 43
CleanShot 2021-03-30 at 18 17 40

### Reviewer guidance

Check to see that this new script works in different common situations like:

1. Running Kolibri for the first time 
2. Running Kolibri for a second time
3. Simulating an upgrade or a downgrade and running the `devserver` script.
 
### References

Fixes #7302

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — APPROVED** [review]

**Comment by jonboiser** [comment]
@rtibbles What needs to be updated in the dev docs? I can just add it to this PR

**Comment by rtibbles** [comment]
@radinamatic had just added this: https://github.com/learningequality/kolibri/blob/develop/docs/getting_started.rst#database-setup because of this exact issue, but with this change it's now redundant :)

**Comment by radinamatic** [comment]
Oh, well... 🤷🏽‍♀️ 

Do we need to revert and delete the *Database setup* step now?

**Comment by jonboiser** [comment]
> Do we need to revert and delete the _Database setup_ step now?

I removed that section, but added some explanation that the database setup happens as part of the first `yarn run devserver` command. 

Hopefully, after this change. The onboarding experience is simple as 1. clone the repo, 2. install deps, 3. `yarn run devserver`

**Comment by rtibbles** [comment]
@jonboiser not seeing the docs updates in this PR, did you push them?

**Comment by jonboiser** [comment]
Whoops, I did not!

**Comment by jonboiser** [comment]
Here's the diff that I did not push 😭 

https://github.com/jonboiser/kolibri/commit/23cbb34b1d36fb43a555957263c783509baa0aab

I can revisit this after #7940 is merged, just to make sure the whole onboarding story is documented consistently.

**Comment by rtibbles** [comment]
Have merged #7940

**Pull request merged**
