### PR TITLE
Use binary mode for dbbackup/restore

### PR DESCRIPTION
**Pull request by benjaoming**
### Summary

Bummer, should have opened the file in binary mode to avoid the system's encoding (or lack of) to interfere...

### Reviewer guidance

Could you test on Windows 10, @indirectlylit ?

### References

#2875

----

### Contributor Checklist

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] Contributor has fully tested the PR manually
- [x] Screenshots of any front-end changes are in the PR description
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by benjaoming** [comment]
Change works, remember to test both `kolibri manage dbbackup` and `kolibri manage dbrestore --latest`

**Comment by indirectlylit** [comment]
maybe this should be targeted to 0.7.1?

**Comment by benjaoming** [comment]
Ah yes, that shouldn't be a problem!

**Comment by indirectlylit** [comment]
whoops looks like it needs to be cherrypicked over

**Pull request closed without merging**
