### PR TITLE
Attempted fix : Enter Channel Token

### LINKED ISSUE #6831: Kolibri "Enter channel token" form starts with capitals
### Observed behavior
When using Kolibri on a mobile device (Android) and going to import a channel, the Channel token form field defaults to capitalize-first keyboard.

Enter channel token starts with capital

### Expected behavior

Let me start typing with lowercase letters.

### User-facing consequences

Requires an extra step to change to lowercase keyboard.

Users who don't know channel tokens are case sensitive will get an error
Screenshot_20200423-170138_Kolibri

### Context
 * Kolibri version: 0.13.2
 * Operating system: Android
 * Browser: webview inside Android app; but same behaviour observed previsously in client-server model when client is mobile browser

### Possible solution

set `autocapitalize="none"` on the form field: https://stackoverflow.com/a/5171812

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
I don't know if this will work. How can I test it?

### Summary

Attempts to add autocapitalize attribute to KTextbox (could not find it's definition)

### Reviewer guidance

I am still working this out. Not ready for review, but I cannot add labels

### References

Fixes #6831 (if it works) uses the suggested path to solving

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by Lewiscowles1986** [comment]
Looks like I'll need to PR https://github.com/JosephusPaye/Keen-UI/blob/0.8.9/src/UiTextbox.vue as well as Kolibri own https://github.com/Techlete/kolibri-design-system/blob/develop/lib/KTextbox/index.vue I think

"modern" JS 😏

**Comment by Lewiscowles1986** [comment]
This looks like it will need https://github.com/learningequality/kolibri-design-system/pull/29

I thought originally it might need Keen, then Kolibri Design System, but it turns out you'd forked the element I needed to patch. This cannot be ready for review without https://github.com/learningequality/kolibri-design-system/pull/29

**Comment by indirectlylit** [comment]
thank you - will review asap.

**Comment by Lewiscowles1986** [comment]
@indirectlylit until the styleguide gets merged, this one won't be ready for review. Once it is merged I think I've uncovered a user-facing documentation challenge regarding custom keyboards for android at least.

**Comment by indirectlylit** [comment]
thanks - I've merged your work in https://github.com/learningequality/kolibri-design-system/pull/57

I'm going to go ahead and merge this as it's a fairly safe change. Testing will require updating to a new pre-release of the design system and building a new APK which is fairly involved - we'll do that later this week and test then

**Review by indirectlylit — APPROVED** [review]

**Comment by Lewiscowles1986** [comment]
Is there any way for non learning eqaulity engineers to get a peek into that?

thanks for getting this merged and hope the changes help.

🎉 🚀

**Comment by lauradanforth** [comment]
> Is there any way for non learning eqaulity engineers to get a peek into that?
> 
> thanks for getting this merged and hope the changes help.
> 
> 🎉 🚀

Hi Lewis! Can you send me an e-mail at laura@learningequality.org? I'll reply with some information on this. Cheers!

**Pull request merged**
