### PR TITLE
cherry-pick to develop: use python 3.5 instead of 3.4 when uploading artifacts

### PR DESCRIPTION
**Pull request by lyw07**
### Summary

This PR is to cherry-pick the commit from #6438 to fix the buildkite build issue for PRs targeting develop branch.

### Reviewer guidance

please check if the build passes

### References

…

----

### Contributor Checklist

PR process:

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — APPROVED** [review]

**Comment by rtibbles** [comment]
Noting that this will cause a merge conflict when we merge 0.13 into develop.

**Comment by lyw07** [comment]
should I do direct merge from 0.13.x to develop instead of cherry-picking? I was unsure because I didn't know if https://github.com/learningequality/kolibri/commit/1f89884c27923093a8a82c2adee3aba931026779 can be merged to develop now or not... thank you!

**Comment by rtibbles** [comment]
The cherry pick should be fine for the purpose of getting builds running quickly - just wanted to flag that this will give us a spurious merge conflict.

**Comment by lyw07** [comment]
thank you for the explanation!

**Pull request merged**
