### PR TITLE
temporarily disable android build

### PR DESCRIPTION
**Pull request by lyw07**
### Summary

this PR is to temporarily disable android build on buildkite.

### Reviewer guidance

please check if the build passes on buildkite without andriod builds.

### References

…

----

### Contributor Checklist

PR process:

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by DXCanas** [comment]
I'm actually working on something like this right now, sorry not to keep y'all updated

**Comment by lyw07** [comment]
@DXCanas ah sorry! please feel free to close this PR if you are going to open your PR soon

**Comment by lyw07** [comment]
closing this in favor of #6413

**Comment by lyw07** [comment]
re-opening this because the build in #6413 failed

**Comment by lyw07** [comment]
I might find the solution to our current android build failure so let's not do any actions to this PR for now. thank you!

**Review by kollivier — APPROVED** [review]
LGTM!

**Pull request merged**
