### PR TITLE
Lint integration testing

### PR DESCRIPTION
**Pull request by benjaoming**
### Summary

Linting updates in preparation for #6583

### Reviewer guidance

Spot any problematic lints?

### References

n/a

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [x] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by benjaoming** [comment]
Travis succeeded but Github was down.

**Review by indirectlylit — APPROVED** [review]
which rule or tool lints .feature files?

**Comment by radinamatic** [comment]
> which rule or tool lints .feature files?

Good question, interested too!

All I can see for now is it deletes extra spaces...

**Comment by benjaoming** [comment]
> which rule or tool lints .feature files?

I think it was the rule about not leaving blank spaces at the end of lines and the "end of file" fixer?

https://github.com/learningequality/kolibri/blob/develop/.pre-commit-config.yaml#L5

**Comment by benjaoming** [comment]
These rules can totally be left out btw... I just didn't want to go any further for now, than to accept what linting was already put in place (but not applied).

**Pull request merged**
