### PR TITLE
Library - Connection state's position when there are no libraries around fixed

### PR DESCRIPTION
**Pull request by JennyPoudel**
Fixes ##11442
<!--
 The screenshot of the required UI:
expected ui

### CODE REVIEW

**Comment by JennyPoudel** [comment]
SS of the UI:
expected ui

**Comment by MisRob** [comment]
Thanks for your first contribution, @JennyPoudel! We will review.

**Review by LianaHarris360 — CHANGES_REQUESTED** [review]
Hi @JennyPoudel, great work on this! I noticed on smaller screens, the position of the string drops beneath the title of the first library, but it should remain positioned beneath “Other Libraries”. 
otherLibraries

Another issue occurring on smaller screens is the string being positioned a little too far left, like shown in the screenshot below with the string `No other libraries around you right now`.

noOtherLibraries

**Comment by JennyPoudel** [comment]
@LianaHarris360 thankyou for the review, I will look into that

**Comment by MisRob** [comment]
Hi @JennyPoudel, are you planning to finish this or is there something we can help with?

**Comment by MisRob** [comment]
Closing due to inactivity

**Pull request closed without merging**
