### PR TITLE
Refactor sidebar to use slots

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary
Makes use of slots
Reduces the number of sticky calculations (no longer one for the tabs)

## References

https://github.com/learningequality/kolibri/assets/17235236/c26a49ee-a5f9-4f6b-ac3f-4d1104351d15

## Reviewer guidance
This whole approach might be questionable because it is Friday evening

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by thanksameeelian** [comment]
this is not my actual sentiment, but reading your branch name made my brain go right to:

https://github.com/learningequality/kolibri/assets/43046460/075aadb5-b5a4-499e-b0f2-69005a9924d1

**Comment by thanksameeelian** [comment]
i noticed that this introduced a bit of weirdness with the sidebar headers that i couldn't recreate on `develop` - the "search" header stretching beyond the bounds of the sidebar it's heading up when the window is medium size.
Screen Shot 2023-06-23 at 6 04 04 PM

https://github.com/learningequality/kolibri/assets/43046460/3243575b-3a3b-4bcb-a177-aeddfd6968b0


i didn't encounter the same thing on `develop`: 
Screen Shot 2023-06-23 at 6 10 20 PM

even though it's a small difference, i think it takes away a little bit from the clarity of what those headers control.

as an aside, i think it would be really nice if we could use[ CSS to truncate the search box placeholder text & add an ellipsis](https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/) in this medium-size case where the text is not fully visible, as it cuts off a bit abruptly and as placeholder text isn't scrollable, so it feels a bit mysterious if you're only viewing it in a medium window size haha. but i know it's the same way on `develop`! it just caught my eye during this review and i thought it might be worth a small follow-up issue if others agree.

**Comment by marcellamaki** [comment]
> the "search" header stretching beyond the bounds of the sidebar it's heading up when the window is medium size

ah good catch, I thought I had reverted that (unintentional) change! yes this should definitely be fixed

**Review by rtibbles — APPROVED** [review]
Merging to prevent the sidebar issue interfering with QA.

**Pull request merged**
