### PR TITLE
Consistency 3

### PR DESCRIPTION
**Pull request by indirectlylit**
Proposal for a whitespace convention for .vue files. Let me know if you have feedback on this. It's not super compact, but I think it's very readable.

It would be nice to have a linter rule for this sort of thing, but I'm not sure offhand how that would be implemented.

The proposed rules are:
* two lines _between_ top-level tags (`template`, `script`, and `style`)
* one line of padding _inside_ top-level tags
* one level of indent for content inside top-level tags tags
* empty top-level tags are on one line

For example:

```html
<template>

  <select v-model="selected">
    <template v-for="option in list">
      <option :value="option">
        {{ option.name }}
      </option>
    </template>
  </select>

</template>


<script>

  module.exports = {
    props: {
      list: {
        type: Array,
      },
      selected: null,
    },
  };

</script>


<style lang="stylus" scoped></style>
```

Also migrated `export default` es6 syntax to `module.exports =`

### CODE REVIEW

**Comment by rtibbles** [comment]
Spaces or tabs?

**Comment by indirectlylit** [comment]
Two spaces. that's already being linted though - the proposal here wasn't meant to affect that

**Comment by MCGallaspy** [comment]
Probably still a good idea to add a linter check for this. I guess at a minimum you could add an extra build step that checks all `.vue` files against some regex?

**Comment by rtibbles** [comment]
Would be nice - and maybe adding html linting to HTML?

**Comment by indirectlylit** [comment]
agree with both - I'll add trello cards for these

**Pull request merged**
