### PR TITLE
[Pdf_Viewer] Backport changes from develop to 0.15.x

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Summary

Backport develop changes of pdf_viewer from develop to 0.15.x.

## References

Backported changes:

* Update PDFJs version to 2.14 #9526 
* Rendering PDF text layer #9536 
* Rendering PDF struct tree layer #9585 
* Add unit tests #9586 
* Render SidePanel with PDF Bookmarks #9743 
* Fix page height and width calculations #9888 
* Support for rotated PDFs #9907 

## Reviewer guidance

Test everything with pdfs rendering works ok in release-v0.15.x. 

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
Hi @AlexVelezLl I tested this in both Ubuntu and Windows and the .pdf resources are not being rendered correctly anywhere now:
Screenshot:



Errors in the console:
```
GET http://127.0.0.1:8080/en/learn/pdfJSWorker-0.15.10.dev0+git.20230102181911.js 404 (Not Found)
pdf.js:456 Warning: Setting up fake worker.
pdf.js:9089          GET http://127.0.0.1:8080/en/learn/pdfJSWorker-0.15.10.dev0+git.20230102181911.js net::ERR_ABORTED 404 (Not Found)
(anonymous) @ pdf.js:9089
exports.loadScript @ pdf.js:9073
loader @ pdf.js:5978
get _setupFakeWorkerGlobal @ pdf.js:5982
_setupFakeWorker @ pdf.js:5882
terminateEarly @ pdf.js:5810
onWorkerError @ pdf.js:5816
error (async)
_initialize @ pdf.js:5820
PDFWorker @ pdf.js:5764
getDocument @ pdf.js:4667
created @ PdfRendererIndex.vue:263
invokeWithErrorHandling @ vue.runtime.esm.js:1863
callHook @ vue.runtime.esm.js:4235
Vue._init @ vue.runtime.esm.js:5022
Sub @ vue.runtime.esm.js:5168
(anonymous) @ vue.runtime.esm.js:3304
init @ vue.runtime.esm.js:3133
(anonymous) @ vue.runtime.esm.js:6022
createElm @ vue.runtime.esm.js:5969
(anonymous) @ vue.runtime.esm.js:6560
Vue._update @ vue.runtime.esm.js:3963
updateComponent @ vue.runtime.esm.js:4081
Watcher.get @ vue.runtime.esm.js:4495
Watcher.run @ vue.runtime.esm.js:4570
flushSchedulerQueue @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
flushCallbacks @ vue.runtime.esm.js:1915
Promise.then (async)
timerFunc @ vue.runtime.esm.js:1942
nextTick @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
Watcher.update @ vue.runtime.esm.js:4560
Vue.$forceUpdate @ vue.runtime.esm.js:3984
forceRender @ vue.runtime.esm.js:3668
(anonymous) @ vue.runtime.esm.js:3690
(anonymous) @ vue.runtime.esm.js:336
Promise.then (async)
asyncFactory @ vue.runtime.esm.js:3716
createComponent @ vue.runtime.esm.js:3219
(anonymous) @ vue.runtime.esm.js:3443
createElement @ vue.runtime.esm.js:3374
vm.$createElement @ vue.runtime.esm.js:3515
render @ KContentRenderer.js:40
(anonymous) @ vue-composition-api.esm.js:1585
activateCurrentInstance @ vue-composition-api.esm.js:1545
$options.render @ vue-composition-api.esm.js:1585
Vue._render @ vue.runtime.esm.js:3569
updateComponent @ vue.runtime.esm.js:4081
Watcher.get @ vue.runtime.esm.js:4495
Watcher @ vue.runtime.esm.js:4484
el @ vue.runtime.esm.js:4088
Vue.$mount @ vue.runtime.esm.js:8459
init @ vue.runtime.esm.js:3137
(anonymous) @ vue.runtime.esm.js:6022
createElm @ vue.runtime.esm.js:5969
(anonymous) @ vue.runtime.esm.js:6260
patchVnode @ vue.runtime.esm.js:6363
(anonymous) @ vue.runtime.esm.js:6526
Vue._update @ vue.runtime.esm.js:3963
updateComponent @ vue.runtime.esm.js:4081
Watcher.get @ vue.runtime.esm.js:4495
Watcher.run @ vue.runtime.esm.js:4570
flushSchedulerQueue @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
flushCallbacks @ vue.runtime.esm.js:1915
Promise.then (async)
timerFunc @ vue.runtime.esm.js:1942
nextTick @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
Watcher.update @ vue.runtime.esm.js:4560
Dep.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
sharedPropertyDefinition.set @ vue.runtime.esm.js:4644
(anonymous) @ ContentPage.vue:178
Promise.then (async)
created @ ContentPage.vue:177
invokeWithErrorHandling @ vue.runtime.esm.js:1863
callHook @ vue.runtime.esm.js:4235
Vue._init @ vue.runtime.esm.js:5022
Sub @ vue.runtime.esm.js:5168
(anonymous) @ vue.runtime.esm.js:3304
init @ vue.runtime.esm.js:3133
(anonymous) @ vue.runtime.esm.js:6022
createElm @ vue.runtime.esm.js:5969
createChildren @ vue.runtime.esm.js:6097
createElm @ vue.runtime.esm.js:5998
createChildren @ vue.runtime.esm.js:6097
createElm @ vue.runtime.esm.js:5998
(anonymous) @ vue.runtime.esm.js:6560
Vue._update @ vue.runtime.esm.js:3963
updateComponent @ vue.runtime.esm.js:4081
Watcher.get @ vue.runtime.esm.js:4495
Watcher.run @ vue.runtime.esm.js:4570
flushSchedulerQueue @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
flushCallbacks @ vue.runtime.esm.js:1915
Promise.then (async)
timerFunc @ vue.runtime.esm.js:1942
nextTick @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
Watcher.update @ vue.runtime.esm.js:4560
Dep.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
SET_STATE @ index.js:24
(anonymous) @ vuex.esm.js:785
(anonymous) @ vuex.esm.js:407
(anonymous) @ vuex.esm.js:406
Store._withCommit @ vuex.esm.js:565
Store.commit @ vuex.esm.js:405
Store.commit @ vuex.esm.js:350
(anonymous) @ handlers.js:25
(anonymous) @ conditionalPromise.js:36
Promise.then (async)
value @ conditionalPromise.js:33
handler @ handlers.js:17
value @ router.js:22
iterator @ vue-router.esm.js:2225
step @ vue-router.esm.js:1896
(anonymous) @ vue-router.esm.js:1897
(anonymous) @ vue-router.esm.js:2247
(anonymous) @ app.js:40
iterator @ vue-router.esm.js:2225
step @ vue-router.esm.js:1896
step @ vue-router.esm.js:1900
runQueue @ vue-router.esm.js:1904
History.confirmTransition @ vue-router.esm.js:2255
History.transitionTo @ vue-router.esm.js:2125
HashHistory.push @ vue-router.esm.js:2595
VueRouter.push @ vue-router.esm.js:2916
handler @ vue-router.esm.js:1100
invokeWithErrorHandling @ vue.runtime.esm.js:1863
invoker @ vue.runtime.esm.js:2188
original._wrapper @ vue.runtime.esm.js:6961
:8080/en/learn/#/topics/c/9e53d545aaf44c3787a29a34b189c56a?lessonId=f151f56c6ada2f496aa858d259b9d629&classId=432558d99da721a82c23a6a5dcaaba6d&last=LESSON_PLAYLIST:1 Refused to execute script from 'http://127.0.0.1:8080/en/learn/pdfJSWorker-0.15.10.dev0+git.20230102181911.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
pdf.js:5903 Uncaught (in promise) Error: Setting up fake worker failed: "Cannot load script at: http://127.0.0.1:8080/en/learn/pdfJSWorker-0.15.10.dev0+git.20230102181911.js".
    at pdf.js:5903:36
```

**Comment by AlexVelezLl** [comment]
Hi! @pcenov It seems that the error is fixed now, can you try again pelase 😄.

**Comment by pcenov** [comment]
Hi @AlexVelezLl viewing and completing .pdf resources is now identical to the state in 0.16. I have reported separately the following issue, caused by the introduction of Bookmarks menu: https://github.com/learningequality/kolibri/issues/9983

**Review by marcellamaki — APPROVED** [review]
Nice work @AlexVelezLl - thanks for getting this in! I did a re-read of the code, but since it's already been reviewed and manual QA checks out - I think we are good to go.

I will speak with @rtibbles about the follow up issue that @pcenov created, and we will work on getting that in to the 0.15 release. 

Thanks again, Alex! So excited to have this work getting out to our users very soon 🎉

**Pull request merged**
