### PR TITLE
adding latest translations

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

pulls the latest from crowdin prior to beta1

corresponding PR in perseus: https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/164

### Reviewer guidance

please make sure latest translations work in both perseus and kolibri

----

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by indirectlylit** [comment]
hmm actually something's not quite working - translations aren't being picked up by kolibri.

**Comment by benjaoming** [comment]
There's also some font stuff in this PR, is that intentional?

**Comment by indirectlylit** [comment]
> There's also some font stuff in this PR, is that intentional?

Yes, fonts now need to be updated with every translation update

**Review by rtibbles — APPROVED** [review]
Have tested locally, and languages are working properly. Some languages still need additional updates from Crowdin ofc.

**Pull request merged**
