### PR TITLE
Fix selection behaviour on the My Downloads page

### LINKED ISSUE #11378: Explore libraries - The option 'Remove from my library' is not positioned correctly and not working
## Observed behavior
The option 'Remove from my library' is not displayed correctly and not working

## Expected behavior
Correctly displayed and fully functioning 'Remove from my library' option

## Steps to reproduce the issue
1. Install the latest build from https://github.com/learningequality/kolibri/pull/11177
2. Go to Explore libraries and click the download icon on a card.
3. Observe the position of 'Remove from my library'
4. Click 'Remove from my library' and go to 'My downloads' to confirm that the resource is actually removed.

## More information

https://github.com/learningequality/kolibri/assets/79847249/e9627a35-ee46-4e46-bd7a-8e6874af66fc

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome, Firefox

### LINKED ISSUE #11389: My downloads - 'Select all' is not working properly
## Observed behavior
This is a follow-up issue observed while testing https://github.com/learningequality/kolibri/pull/11177 - when I have selected all items on the first page and I go to the second page, the 'Select all' checkbox is marked as selected on the second page while it shouldn't be. Also if I attempt to select all items on the second page I have to click the box several times for it to start working and then if I move to the 3-rd page it stops working altogether:

## Expected behavior
It should be possible to freely select all or additional resources for removal.

## Steps to reproduce the issue
1. Install the latest build from https://github.com/learningequality/kolibri/pull/11177
2. Create a Learner user and sign in with that user
3. Go to the Library and download more than 25 resources
4. Go to 'My downloads' and click the 'Select all' checkbox on the first page of the table.
5. Attempt to do so for the next pages.

## More information

https://github.com/learningequality/kolibri/assets/79847249/4de46593-e3a5-4c09-bbcb-6dcb70306575

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome, Firefox

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Updates the `removeDownloadRequest` function to accept a contentnode_id as its only argument (in the process, fixing the latter part of #11378)
* Removes duplication in the responsive view of the My Downloads page to make it easier to reason about
* Updates the resource selection to be a map from `contentnode_id` for the request to `true` to enable easy lookup in the `downloadRequestMap` and to be compatible with the updated `removeDownloadRequest` function
* Adds indeterminate selection determination to the select all checkbox
* Updates deletion setting to use the new map
* Updates checked setting to use the new map

## References
Fixes [#11389](https://github.com/learningequality/kolibri/issues/11389)
Fixes #11378 - now that the z-index issue has been fixed by @LianaHarris360 

## Reviewer guidance
Ensure that all selection behaviour behaves as expected:
* Selecting one should toggle the Select All checkbox to an indeterminate state
* Selections should be preserved across page navigation, but the Select All checkbox state and effect should be scoped to the current page
* Clicking on the Select All checkbox in an indeterminate state will Select All on the page
* Clicking on the Select All checkbox in a checked state will deselect all on the page
* Clicking on the Select All checkbox in an unchecked state will select all on the page
* Table should render properly in smaller screen sizes

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by pcenov — CHANGES_REQUESTED** [review]
@rtibbles I confirm that the selection behaviour is fixed now and the option 'Remove from my library' is functioning.
What puzzles me is that now both 'Remove' and 'Remove selected' are not functioning at all:

https://github.com/learningequality/kolibri/assets/79847249/09f69f3e-00af-48ed-babd-9445a660181c

Also when I remove a resource from the library there is no 
snackbar 'Resource removed from my library' as specified in [Figma](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?type=design&node-id=194-2922&mode=design):

https://github.com/learningequality/kolibri/assets/79847249/ee769e0d-41d1-455e-93bf-677ba8192030

**Comment by rtibbles** [comment]
Not terribly confusing - I have clearly messed something up :) Thanks for checking my working.

**Comment by rtibbles** [comment]
Removal should be working everywhere now, and the snackbar should display when removing a download while browsing a remote library.

**Review by pcenov — APPROVED** [review]
Implemented as specified.

**Review by marcellamaki — APPROVED** [review]
Code changes look good to me, and since this has the Peter stamp of approval, I think we are good to merge. Thanks for the code cleanup and simplification here, @rtibbles :)

**Pull request merged**
