### PR TITLE
Frontend arch

### PR DESCRIPTION
**Pull request by indirectlylit**
combination of Michael's frontend-arch branch and Richard's learn branch

### CODE REVIEW

**Comment by MCGallaspy** [comment]
@indirectlylit let's resolve these test failures before merging.

**Comment by MCGallaspy** [comment]
Merging, and then @dxcanas and I will address test failures in subsequent PR.

**Comment by benjaoming** [comment]
Hi @MCGallaspy and @indirectlylit 

I would like to rebase against current master and sort out loads of merge conflicts now due.. but it sort of sucks to have to face test failures on top of that :)

Anyways, a lot of the work regarding assets has been simplified and made more explicit through hooks classes. I'll take it to the test when I rebase and refactor the new stuff in this PR.

**Comment by indirectlylit** [comment]
apologies about the test failures - I need to learn how to make sure my PRs are green

**Comment by MCGallaspy** [comment]
@indirectlylit install pre-commit hooks to lint on every commit. That was one error. The other would be to just be sure to run tests locally before opening a PR -- my mistake, too.

**Comment by MCGallaspy** [comment]
@benjaoming fortunately you will not face test failures on master, as this is not targeting that branch.

**Comment by MCGallaspy** [comment]
Moreover @benjaoming I would suggest that you *not* try to refactor the stuff in this PR -- we're planning on refactoring based on *your* changes already, when they come in.

**Pull request merged**
