### PR TITLE
sets Kolibri v0.7.0 to track the develop branch of the windows installer

### PR DESCRIPTION
**Pull request by indirectlylit**
* cherry-picks changes from #2431
* track the `develop` branch

cc @radinamatic @mrpau-richard

### CODE REVIEW

**Comment by radinamatic** [comment]
@indirectlylit The installer from this build is not localized yet, correct?

**Comment by mrpau-richard** [comment]
@indirectlylit I think you should pin this into the latest commit at Kolibri windows installer develop branch to include the localized Installer.

**Comment by indirectlylit** [comment]
@mrpau-richard @radinamatic - updated this PR to track the `develop` branch, which should make it easier to see updates.

Notes:

* it's important that we pin to a specific installer release before releasing kolibri (cc @rtibbles maybe something to add to the release process)
* when changes are made to the installer, a new kolibri build needs to be manually triggered in buildkite to see the changes

**Comment by indirectlylit** [comment]
if the changes are acceptable, if someone could merge this in, would be appreciated!

**Comment by benjaoming** [comment]
@indirectlylit Agreed on your the suggested process of aligning develop branches with develop branches of installers -- and then swapping to commit hashes or likewise when moving from develop to release-v0.x.y

If we need more explicit behavior because changes in an installer's develop branch are being mistaken as issues in Kolibri, we can always switch back, but right now there are a lot of changes happening in the installers. I would probably want the same tracking to take place for the .deb build when it's in buildkite.

**Comment by benjaoming** [comment]
Merging now, @radinamatic note that currently open PRs against develop will have to be updated before new Windows installers are built.

**Pull request merged**
