### PR TITLE
Remove content_session_receiver signal

### PR DESCRIPTION
**Pull request by bonidukic**
### Summary
In this commit we have removed the `content_session_receiver` signal and
transferred the task of handling updating the `UserSessionLog` to the
frontend by explicitly setting `active` state on the hearbeat for each of
the callback methods in the content renderer vue module.

This should give us a small performance improvement, but improvement nevertheless.

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by rtibbles** [comment]
Please rebase and retarget to release-v0.10.x!

**Review by rtibbles — COMMENTED** [review]
Code looks good to me. Will merge once retargeted.

**Comment by bonidukic** [comment]
@rtibbles sanity check:
- checkout a local backup of `bonidjukic:feature/contentsessionlog-signal`
- removed local `bonidjukic:feature/contentsessionlog-signal`
- checkout new local `bonidjukic:feature/contentsessionlog-signal` from `learningequality:release-v0.10.x`
- cherry-picked last commit from the backup branch
- force-pushed to `bonidjukic:feature/contentsessionlog-signal`
- updated base for the PR to `release-v0.10.x`

I think this should do it.

**Review by rtibbles — APPROVED** [review]

**Comment by rtibbles** [comment]
Yep, looks right - it doesn't have any extra commits, which is the best sign!

**Comment by rtibbles** [comment]
Travis is doing something funky here, so I am going to merge on my own recognizance.

**Pull request merged**
