### PR TITLE
Responsivity improvements of the mastery bar on an exercise page

### LINKED ISSUE #8727: Unstuck bottom bar in the Perseus renderer on small mobile screens
## Observed behavior
Bottom bar in the Perseus renderer (where the <kbd>Check</kbd> button is located) is supposed to be sticky, and not scroll up and down with the exercise when the height of the resource is bigger than the available screen space

(disregard the icons of the screencasting apps)

### Android app
https://user-images.githubusercontent.com/1457929/142364399-72aaa4b3-fc1d-4d0f-9c7b-af775a2435c1.mp4

### Browser on Android client
https://user-images.githubusercontent.com/1457929/142364602-a435826a-dc45-4921-947a-c4e4b2980c06.mp4

## Errors and logs
…

## Expected behavior
Bottom bar should stick to the edge and not scroll with the content.

## User-facing consequences
…

## Steps to reproduce
…

## Context
Tell us about your environment, including:
 * Kolibri version: 0.15b2
 * Operating system Android
 * Browser all

### PR DESCRIPTION
**Pull request by MisRob**
## Summary

- Fixes x-overflow problems with hints button on small mobile screens by moving the button below the requirements text
- Fixes the bottom bar not being sticky on small mobile screens
- Introduces `BaseToolbar` component as it was simpler than overriding `UiToolbar`. See `BaseToolbar`'s docstring for more information.
- Components, styles, and data flow simplifications in related components

| Before | After |
| --------- | ------ |
| before | after |

(the noise is caused by bad conversion to gif)

## References

Fixes #8727

## Reviewer guidance

Navigate to the "Recognize fractions" exercise in the "Kolibri QA channel" > "Exercises" > "Channel based quizzes" and see the mastery bar for different screen sizes.

As for #8727, reproducing was possible only under quite specific conditions so when testing the bottom bar stickiness, please use the following conditions as well:
- switch Kolibri language to Spanish
- test on your real device or a BrowserStack real device
- test for a question that is higher than the screen so that you can scroll up and down

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by MisRob** [comment]
@jtamiace is it okay to move the hints button to the second row like this on small screens when it doesn't fit one row?
Screenshot from 2021-11-29 08-56-27

It's intended as a hotfix since it was breaking the bottom bar on small screens (#8727) as well, but no problem to shift things differently if you'd prefer to prepare designs.

**Comment by MisRob** [comment]
@radinamatic Could you please try this on the same device used in #8727 bug report and (if it's already possible) also test in the Android app?

**Comment by jtamiace** [comment]
@MisRob I think expanding to a second line is okay 👍🏼 Top bars aren't sticky and probably? won't block the exercise content too much

**Comment by MisRob** [comment]
@jtamiace Okay, thank you. That's right, top bars aren't sticky.

**Comment by radinamatic** [comment]
Yey, sticky all the way (APK asset on my MotoG6 phone) 🙂 

You effectively _cemented_ that bar to the bottom, great job!!! 🎉 

bottom-bar

**Review by radinamatic — APPROVED** [review]
:shipit: 👍🏽

**Comment by radinamatic** [comment]
Tested the EXE asset on IE11/Windows 7 combo, not seeing anything alarming @rtibbles 

1 | 2
--- | ---
ie11-3 | Win7 (start)  Running  - Oracle VM VirtualBox_010

**Comment by rtibbles** [comment]
Thanks - just wanted a double check because of the confluence of `display: flex` and `min-width` and `justify-content`.

**Review by rtibbles — APPROVED** [review]

**Pull request merged**
