### PR TITLE
Navigation tweaks

### LINKED ISSUE #11253: Coach routing - Minor issues
## Observed behavior
Observed while testing https://github.com/learningequality/kolibri/pull/11224: In a setup with multiple facilities and classes if I go to Facility > Coach > Class home > View learners and then if I click the back arrow I am brought back to the Facilities table instead of just going to the class Home page.
Also regardless of the setup (single or multiple facilities) when I open the left navigation and click on any of the links under Coach I can see the URL changing but the navigation bar is not automatically closed so it seems that nothing has happened.

## Expected behavior
1. For the first case the user should be brought back to the class Home page.
2. In the second case the navigation should be automatically closed so the user can select a facility/class and proceed to the initially selected page.

## Steps to reproduce the issue
1. See the attached videos

## Video

https://github.com/learningequality/kolibri/assets/79847249/6179a0cd-085a-4b36-8850-1e047f4aa9fa

https://github.com/learningequality/kolibri/assets/79847249/888796b4-9a18-4862-aaba-e73b25cb08de

## Usage Details
[Kolibri 0.16beta5](https://github.com/learningequality/kolibri/pull/11224)
Windows 10, Ubuntu - Chrome

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Prevents redundant navigation errors by using `next` rather than `router.replace` for synchronous navigation guards
* Ensures that the side nav always closes for navigation events, now that it always displays as a modal
* Ensures backlink gets properly generated for Home Page by passing classId parameter

## References
Fixes #11253

## Reviewer guidance
Are all the behaviours working as one might expect?
Did I miss any instances where Home, Reports, or Plan links are being generated without a classId (now that the parameter is optional, it does not automatically get supplied by the `getRoute` method.

New side nav behaviour - only does the toggle behaviour when navigating within an SPA, otherwise it looked a bit janky:
[Screencast from 09-15-2023 04:03:30 PM.webm](https://github.com/learningequality/kolibri/assets/1680573/047c32ea-388d-4ec9-a258-84ff0be10a17)

Bug fix for back route:
[Screencast from 09-15-2023 04:00:21 PM.webm](https://github.com/learningequality/kolibri/assets/1680573/226c7704-a19d-4813-aac9-f87cf88fa239)

No redundant navigation errors:
[Screencast from 09-15-2023 04:01:35 PM.webm](https://github.com/learningequality/kolibri/assets/1680573/c102e022-9aa8-44da-8b03-be1fa2640fe0)

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by thanksameeelian — COMMENTED** [review]
i've read through the code and have been clicking around and almost everything is looking good to me. and kudos to @pcenov for finding that redundant navigation problem! 

the only small issue i noticed was while i was testing out that scenario of clicking on the same sidenav link twice. afterwards, the page gave the appearance of perpetual loading, with the top loading bar running continuously

https://github.com/learningequality/kolibri/assets/43046460/a22619a7-d90c-41a8-b7ae-887c7ea7b990

**Comment by rtibbles** [comment]
Seems like this was happening because we always set the global loading state to true before entering any route in coach. Have resolved it for now by turning it off when the class param required guard returns true.

Ultimately, my suggestion elsewhere has been that we should only use the core loading state to show navigation is still in progress and control it entirely from navigation guards in the core of the app - but that's for another day!

**Review by pcenov — APPROVED** [review]
Thanks @rtibbles and @thanksameeelian - no extra issues uncovered while regression testing, good to go!

**Review by thanksameeelian — APPROVED** [review]
looks great to me!

**Pull request merged**
