### PR TITLE
add Korean as a supported language

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

add Korean language files

### Reviewer guidance

~depends on merge and release of https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/197~ merged

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jonboiser** [comment]
Just a couple places where icons look unusual when using the Korean locale:

**Import/export channel list**

Screen Shot 2019-07-16 at 3 14 03 PM

**Points icon**

Screen Shot 2019-07-16 at 3 14 38 PM

**Comment by indirectlylit** [comment]
okay. I'll leave this open and try to tackle it next week

**Comment by indirectlylit** [comment]
punting this to our next patch release

**Comment by indirectlylit** [comment]
Tried pushing fixes to the two issues mentioned. Needed to do some tweaking to points icon, which I still don't fully understand

**Comment by radinamatic** [comment]
Few pages loaded fine on the Facility side, but when I jump to Learn:

LEDev1911n  Running  - Oracle VM VirtualBox_030

Coach:

LEDev1911n  Running  - Oracle VM VirtualBox_032

Device:

LEDev1911n  Running  - Oracle VM VirtualBox_033

Facility still loads fine after the above:

facility-korean

**Comment by radinamatic** [comment]
I did do the `make clean`, and even `yarn clean` before running the server...

**Comment by indirectlylit** [comment]
@radinamatic those errors are unrelated to my PR. Is there a chance the database was run on `develop` in addition to 0.12.x?

**Comment by radinamatic** [comment]
Yes, i was under the impression `make clean` would take care of that, but apparently it doesn't :confused: 

Let me retry with a clean DB!

**Comment by radinamatic** [comment]
Yep, all seems good with the fresh DB, setup wizard included!

korean

I'll give it a spin in Chrome, and do a sanity check on Windows too.

**Comment by indirectlylit** [comment]
thank you!

**Comment by radinamatic** [comment]
Two potentially unrelated issues, somewhat similar to what @jonboiser reported before:

LEDev1911n  Running  - Oracle VM VirtualBox_034

The :lock: icon is a bit lowered, and resizing at one point leaves a character hanging (maybe not a deal-breaker...?)

korean2

**Comment by radinamatic** [comment]
Everything seems to be running smooth even on Windows 7 (going to take that as a yes for 10 too), no funny artifacts that would imply i18n problems.

Not related: Chrome does not allow to resize the window as freely as FF, I don't remember noticing that before...

Win7 (start)  Running  - Oracle VM VirtualBox_037

**Review by radinamatic — APPROVED** [review]
LGTM! :+1:

**Pull request merged**
