### PR TITLE
Manage tool bar styling

### PR DESCRIPTION
**Pull request by whitzhu**
screen shot 2016-08-04 at 3 27 37 pm
screen shot 2016-08-04 at 3 27 45 pm
screen shot 2016-08-04 at 3 27 49 pm

## Summary

*Short description*

## TODO

- [ ] Have tests been written for the new code?
- [ ] Has documentation been written/updated?
- [ ] New dependencies (if any) added to requirements file
- [ ] Add an entry to CHANGELOG.rst
- [ ] Add yourself it AUTHORS.rst if you don't appear there

## Reviewer guidance

*If you PR has a significant size, give the reviewer some helpful remarks*

## Issues addressed

List the issues solved or partly solved by the PR

## Documentation

If the PR has documentation, link the file here (either .rst in your repo or if built on Read The Docs)

## Screenshots (if appropriate)

They're nice. :)

### CODE REVIEW

**Comment by radinamatic** [comment]
One thing I've been reviewing today is the keyboard navigation. Chrome has fairly evident native style for elements in `:focus`, but the thin dotted line in Firefox is clearly insufficient IMHO. 

So I'd really like to see our own style for nav elements (in this management top bar, or in the main one) when they gain `:focus` with `TAB` key. For example something along these lines:

focus
 
@whitzhu @jtamiace @indirectlylit

**Comment by indirectlylit** [comment]
doesn't seem to handle smaller screens very well:

image

**Comment by whitzhu** [comment]
@indirectlylit Added media query and removed previous focus styling

**Comment by whitzhu** [comment]
screen shot 2016-08-05 at 2 45 48 pm

**Comment by whitzhu** [comment]
screen shot 2016-08-05 at 3 01 18 pm

**Comment by indirectlylit** [comment]
strange, I'm not seeing the tab-focus styling: 

image

**Pull request merged**
