### PR TITLE
Card heights

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Uses ContentNodeThumbnail in the HybridLearningContentCard CardThumbnail implementation to give consistent empty thumbnail and sizing experience across the different hybrid learning card types
* Reduces the max lines for content node titles used in HybridLearningContentCard from 5 to 3 (as this should cover 99% of titles in the public library)
* Reduces the height of the text box below the thumbnail accordingly
* Fixes an uncaught bug in the progress bar width calculation
* Repositions the progress bar and completed label slightly to be better aligned with the other footer elements
* Updates LibraryPage and TopicsPage grids to have consistent numbers of columns across sections and pages
* Shows a subtopic's full children when it's the only one
* Shows all channels to a learner who has no other recommendations

## References
No precise issue.

## Reviewer guidance
The HybridLearningContentCard CardThumbnail implementation is only used in the HybridLearning* card components, so that's the only place that we'd need to double check for regressions.

Full channels for new learner:
Screenshot from 2021-12-16 18-16-50

Consistent grid spacing on Library Page and fixes to progress bar width:
Screenshot from 2021-12-16 18-23-51

More consistent node thumbnails and reduced card white space:
Screenshot from 2021-12-16 18-24-05

No adverse effects on bookmarks?
Screenshot from 2021-12-16 18-24-38

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
The main thing you might identify as a regression here is that small thumbnails are no longer being stretched to fill the space available - not sure if this is necessarily a bad thing or not.

**Comment by jtamiace** [comment]
👏🏼 These changes look great on all screen sizes. 

Found one issue with bookmarks on mobile
Screen Shot 2021-12-17 at 9 41 40 AM

**Comment by sairina** [comment]
Will any of this be affected by this PR? https://github.com/learningequality/kolibri/pull/8944

**Comment by rtibbles** [comment]
I think the bookmarks changes specifically will interact with #8944 - I think the best thing for me to do is to mitigate the issue that @jtamiace has raised, and then we do a quick sanity check post merge of both PRs.

**Comment by rtibbles** [comment]
That said - I just went to try to do this, and any changes I make to address the bookmark issue will almost certainly interact with these changes, so I think getting #8944 merged first and then rebasing this might be best.

**Comment by marcellamaki** [comment]
Attempted to mitigate conflicts between @rtibbles's and @indirectlylit's changes. Ensures correct footer icons -- both view information and  the coach content icon on the list view on all pages.

@rtibbles -- is this still what you were going for with the cards? @indirectlylit did I just undo all of the lovely changes you made to the footer? 

Screen Shot 2021-12-17 at 4 46 15 PM
Screen Shot 2021-12-17 at 4 46 34 PM
Screen Shot 2021-12-17 at 4 46 45 PM
Screen Shot 2021-12-17 at 4 47 10 PM

**Comment by indirectlylit** [comment]
@marcellamaki for my changes, please just check that the issue I flagged in this PR is not, um, extant: https://github.com/learningequality/kolibri/pull/8879


In particular:

* all of the card should be clickable except the bottom-right buttons (which should do their own thing)
* the keyboard focus outline should still be a nice rectangle around the whole card

**Comment by marcellamaki** [comment]
@indirectlylit - check, and check!

**Comment by rtibbles** [comment]
I don't see any changes that conflict with the changes I made.

**Comment by sairina** [comment]
This is the only thing I saw:

**Comment by marcellamaki** [comment]
Updates to account for weird description text alignment, and somewhat reduce extra white space
bookmarks-responsive

**Review by nucleogenesis — APPROVED** [review]
LGTM nothing blocking that I see here

**Pull request merged**
