### PR TITLE
#6754 truncatefy fix

### PR DESCRIPTION
**Pull request by rationality6**
### Summary

this is fix for number #6754 

https://github.com/learningequality/kolibri/issues/6754

before
before

after

after

Added one div tag in KRadioButton for class

and add css for truncate texts

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
It looks the `div` is a sibling of a `span`, which is not typical because one is `block` and the other is `inline-block`. I would expect siblings to use the same `display` property.

**Comment by rationality6** [comment]
@indirectlylit Is the way that Kolibri code intends? Let me know if I've misunderstood. Then I'll fix again.

**Comment by indirectlylit** [comment]
I'm still a bit confused - now it's two inline blocks with width 100%?

image

My guess is that both those spans (for the label and description) should actually just be divs with their default `display: block` properties?

**Comment by indirectlylit** [comment]
thanks @rationality6 

code looks good to me. @nucleogenesis would you mind testing? Also flagging in https://github.com/learningequality/kolibri-design-system/issues/12

**Comment by rationality6** [comment]
I forgot to comment on code after commit, sorry. Thank you for reviewing @indirectlylit.

**Comment by nucleogenesis** [comment]
@indirectlylit @rationality6 

I'm not getting the ellipses - rather the text is wrapping in its container. Tested in Firefox and Chromium.

long-name-network-source-kolibri

I can get the `overflow: ellipsis` to work if I add the `white-space: nowrap;` CSS property to the `text-truncate` class though. However, I do think that wrapping looks good. There is a 40 character limit to the name of the network when added and named through this dialog (seen in the above example) - and even if network names could be longer by some other means, it looks fine enough IMO. See the below image for an exaggerated example of a very very very long network name. 

extra-super-long-name-network-source-kolibri

**Comment by rationality6** [comment]
Thank you @nucleogenesis. I found out what I made a mistake. "White-space: nowrap;" as you say
. If there is a whitespace in String, it will have new line Or it works the way I thought it would.
Once I added "white-space: nowrap;" I think it's okay to just change the line, as you said. Let me know, If the way would be better.

Screen Shot 2020-05-12 at 12 48 31 PM


after with nowrap


Screen Shot 2020-05-12 at 12 59 54 PM

**Comment by rationality6** [comment]
@nucleogenesis, @indirectlylit 
Do you guys know what am I missed? I just put in a single line of css.

**Comment by nucleogenesis** [comment]
Hey @rationality6 that looks good to me so far.

As for the failing Buildkite, there were some issues with the build system. I just restarted it so it will likely pass and be ready for merge. I'll check back on it and merge when passing.

Thank you @rationality6 !!!

**Review by indirectlylit — APPROVED** [review]
thank you!

**Pull request merged**
