### PR TITLE
Capture more errors from the backend and show error messages for them

### LINKED ISSUE #11711: [Follow-up issue] Setup Wizard - Validation messages at 'Import individual user accounts' and 'Use an admin account'
## Observed behavior
While regression testing https://github.com/learningequality/kolibri/pull/11704 I noticed the following additional minor validation related issues:

- there's no error message displayed if the user attempts to submit an empty form (that's valid both at 'Import individual user accounts' and 'Use an admin account')
- when we have only the 'Username' field being displayed and I enter an admin username then I am still seeing the "Incorrect username or password" - I think in that case we should be showing the `Device limitations` modal, the same as when the Password field is visible
- if after seeing the "Incorrect username or password" message I click the `Use an admin account` link then the "Incorrect username or password" message is still being displayed above the empty form for the admin credentials
- when we have both the Username and Password fields displayed and I enter the username of a learner who was originally created without a password then it's not accepted as valid credentials and I have to import that learner signed in as an admin. This is probably OK, but just mentioning it here as an edge case in case that could be considered.

## Expected behavior

The issues should be further discussed and either fixed with separate PRs or disregarded.

## Steps to reproduce the issue

1. Install the [latest Beta 10 build asset](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta10).
2. In the setup wizard go through Group learning > Learn-only device > Import one or more existing user accounts from an existing facility
3. At the Import individual user accounts you will either see only the 'Username' field or both the 'Username' and 'Password' fields if the option 'Require passwords for learners' checkbox is selected at Device > Settings on the server.

## Usage Details
[Beta 10](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta10)
Ubuntu 22  - Chrome

### PR DESCRIPTION
**Pull request by jredrejo**
## Summary

In the wizard setup, when importing users from a remote facility
- Force validation in some cases that were not covered
- Better capture of the error messages provided by the backend
- Clean previous errors when the modal to use admin credentials is shown

## References
Closes #11711

In reference to #11711 , the last point of the description:
> when we have both the Username and Password fields displayed and I enter the username of a learner who was originally created without a password then it's not accepted as valid credentials and I have to import that learner signed in as an admin

has not being changed as it seems a correct behaviour of the application. When facility settings are changed, previous user not requiring a password to login can't login until they have a password. Importing them remotely should not be different. In any case, if @jtamiace has a better solution, perfect.

## Reviewer guidance
Follow the steps @pcenov described in #11711

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
> when we have both the Username and Password fields displayed and I enter the username of a learner who was originally created without a password then it's not accepted as valid credentials and I have to import that learner signed in as an admin

I think this is correct, and only allowing to do this on the Kolibri device the user is on and _not_ remotely seems more secure.

**Comment by pcenov** [comment]
Hi @jredrejo while regression testing the import of individual user accounts I noticed that now if I select the 'Use an admin account' option, when I click the 'Back' arrow then I am brought back to the 'Import individual user accounts' page and I can't proceed because now the 'Username' and 'Password' fields are required.
This workflow was confusing previously as well but the admin was still able to click the 'Continue' button and proceed with the import. So it should be further discussed how to handle that case.

Here's a video of what I am doing:

https://github.com/learningequality/kolibri/assets/79847249/0691453a-795b-4e16-b72e-b088e81c4cf6

**Comment by jredrejo** [comment]
> Hi @jredrejo while regression testing the import of individual user accounts I noticed that now if I select the 'Use an admin account' option, when I click the 'Back' arrow then I am brought back to the 'Import individual user accounts' page and I can't proceed because now the 'Username' and 'Password' fields are required. This workflow was confusing previously as well but the admin was still able to click the 'Continue' button and proceed with the import. So it should be further discussed how to handle that case.
> 
> Here's a video of what I am doing:
> 
>  2024-01-29_18-28-18.mp4

@pcenov fixed!

**Review by pcenov — APPROVED** [review]
Thank you @jredrejo - manual QA passes, good to go!

**Review by rtibbles — APPROVED** [review]
All changes make sense, manual QA checks out. @marcellamaki I suspect we should merge this for 0.16.0.

**Comment by marcellamaki** [comment]
Yes - that sounds good to me @rtibbles. This seems worth including, and as @pcenov has done manual QA, I feel confident about us merging it in :)

**Pull request merged**
