### PR TITLE
Removed Double Arrow in IE

### PR DESCRIPTION
**Pull request by christianmemije**
## Summary

* Removed the background arrow because IE does not support the css property 'appearance' so it was creating a 2nd arrow. I reduced the border radius because the arrow was getting cut off in Firefox.

## Issue addressed

* https://trello.com/c/DzlEJz0Z/511-ie-11-double-arrows-on-channel-switcher

### Before
image

### After
image

### CODE REVIEW

**Comment by rtibbles** [comment]
We had a similar issue for the search box, where, I think in IE, it automatically generated a 'clear' button, which then ghosted the one we had. How was that resolved, and can we do something similar here to maintain the previous look and feel?

**Comment by christianmemije** [comment]
@whitzhu @indirectlylit ^

**Comment by indirectlylit** [comment]
thanks, will take a look

**Comment by indirectlylit** [comment]
unfortunately, doesn't look too hot in firefox:

image

One thing I noticed is that as soon as we start applying styles like background color and borders, firefox's styling essentially resets.

I don't think there are many good, clean solutions here. [1] [2]

My recommendation is to remove as much styling as possible and let the browser defaults take care of things:

```
  .chan-select
    color: $core-text-annotation
    font-size: 0.9rem
    position: absolute
    top: 0.5rem
    right: 6em
```

thoughts?


[1] https://css-tricks.com/dropdown-default-styling/
[2] http://red-team-design.com/making-html-dropdowns-not-suck/

**Comment by rtibbles** [comment]
I think stripping back to defaults as much as possible is probably preferable.

**Comment by indirectlylit** [comment]
Hey @christianmemije - opened a PR here: https://github.com/christianmemije/kolibri/pull/6

This resolves the merge conflicts, ensures the drop-down is aligned with the search button, and cleans up a bunch of code surrounding the toolbar

**Comment by christianmemije** [comment]
@indirectlylit Merged.

**Pull request merged**
