### PR TITLE
enable daemon mode.

### PR DESCRIPTION
**Pull request by 66eli77**
How to run kolibri in daemon mode:
1. `webpack --config frontend_build/src/webpack.config.js`
2. `kolibri start`

to stop the server
`kolibri stop`

### CODE REVIEW

**Comment by indirectlylit** [comment]
Is this something that we need to support the android work? Should we resolve the conflicts and get this merged in before you leave @66eli77?

**Comment by jamalex** [comment]
This will be necessary for Android, and for Kolibri more generally. I know @benjaoming was going to port over the KA Lite daemonization code; it looks as if this PR was a first pass at that.

**Comment by benjaoming** [comment]
Also, it's missing tests... so by policy, can't be merged :)

**Comment by rtibbles** [comment]
@benjaoming would you be able to take over this PR as part of your `infiltration` back into Kolibri (or whatever the phrasing you used was)?

**Comment by benjaoming** [comment]
Will take over this as per #1548

**Pull request closed without merging**
