### PR TITLE
updates to router and vue initialization

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

follow-up from https://github.com/learningequality/kolibri/pull/5770 and e31fc60

As far as I can tell, the async promise behaviors were not necessary, and were causing issues with initialization.

### Reviewer guidance

please look and test

### References

originally stemmed from work in https://github.com/learningequality/kolibri/pull/5761

There, I wanted to be able to initialize the router with alternate options, and the "kolibri app" framework was making that difficult

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
The main motivation for waiting for the initial heartbeat poll is that until that has happened the session information is not loaded into vuex state, which can cause inconsistencies or errors in the UI.

If this is not the case, this should be fine.

**Comment by rtibbles** [comment]
Oh, and until the heartbeat has finished the initial retrieve, any API writes to the server will result in a 403 - which could happen if the session endpoint is slow to respond and the app logic kicks off without waiting for it to complete.

So, on second thoughts, we shouldn't do this.

**Comment by rtibbles** [comment]
Third thoughts - after conversation, it seems like Vue Router only starts serving routes after it has been passed into the root Vue component at vue app initialization. So, it seems like this will be non-harmful, because nothing will happen until the heartbeat promise has been fulfilled and all necessary state is in place!

**Comment by luna215** [comment]
Is there a reason this pull hasn't been merged? This will definitely fix a bug that's in currently in the most recent develop branch.

**Review by rtibbles — APPROVED** [review]

**Pull request merged**
