### PR TITLE
Stop caching content API responses

### LINKED ISSUE #10968: Stale content API responses
## Observed behavior

Content API responses are cached to avoid expensive database queries. This is great since the content doesn't typically change frequently, but it also means stale responses will be sent until the cached responses expire. The current workaround is to include the content cache key in a query parameter so that the URL changes and bypasses both the browser and server caches. However, the content cache key value is only made available to the frontend statically in HTML, so the only way to ensure fresh API responses is to reload the page. That makes dynamic content management in the frontend difficult.

See https://github.com/endlessm/kolibri-explore-plugin/issues/687 for how this was affecting kolibri-explore-plugin. We worked around it by adding our own API endpoints that don't do caching, but I think this is more appropriate upstream. See #10898 for some other background and my previous attempt to fix this while retaining caching.

## Errors and logs

There are no errors, but if you run kolibri with `--debug-database`, you can see that it is not performing database queries even if `ContentCacheKey` is updated unless different URLs are sent.

## Expected behavior

When the content is updated in the backend, API responses include the new data.

## User-facing consequences

The frontend can show new content without reloading the page.

## Steps to reproduce

Start a kolibri server with `kolibri start --debug --debug-database --foreground`. From another shell query the channel API using `curl -I 'http://127.0.0.1:8080/api/content/channel/'`. Note the `ETag` header in the response so it can be used as the `contentCacheKey` query parameter.

Now make 2 requests using the `contentCacheKey` query parameter like the frontend would do but update the content cache key between the requests:
```
$ curl -sI 'http://127.0.0.1:8080/api/content/channel/?contentCacheKey=1688997709' | grep -i -e etag: -e expires:
Expires: Fri, 12 Jul 2024 02:21:37 GMT
ETag: "1688997709"
$ kolibri manage shell -c 'from kolibri.core.device.models import ContentCacheKey; ContentCacheKey.update_cache_key()'
$ curl -sI 'http://127.0.0.1:8080/api/content/channel/?contentCacheKey=1688997709' | grep -i -e etag: -e expires:
Expires: Fri, 12 Jul 2024 02:21:37 GMT
ETag: "1688997709"
```

If you look at the kolibri logs from the server, you'll see that no database queries are being made. If the `contentCacheKey` value is changed, then it will be a new URL and a new database query will be made along with a new response:

```
$ curl -sI 'http://127.0.0.1:8080/api/content/channel/?contentCacheKey=1688997710' | grep -i -e etag: -e expires:
Expires: Fri, 12 Jul 2024 02:31:49 GMT
ETag: "1689194283.413364"
```

The problem is that the client doesn't know when the `contentCacheKey` value has changed.

## Context

Kolibri 0.16.0alpha19
Linux
Chrome

### PR DESCRIPTION
**Pull request by dbnicholson**
Currently channel and content node API responses are cached by Django to avoid expensive queries. Since the Django cache doesn't respect `Cache-Control` request headers, the client will continue to receive cached responses until they expire or the backend removes the stale entries.

To workaround this, the frontend includes a `contentCacheKey` query parameter using the current `ContentCacheKey` value exported by the backend. This changes the URL when the content cache key is updated and bypasses both the browser and server caches. However, the cache key value is provided to the frontend statically in the HTML `head` element. Unless the frontend reloads the page, it will continue to use an old `contentCacheKey` query parameter and receive cached responses from the server. If the frontend wants to offer content downloads and update the page when the content has changed, it has no choice but to reload the page to ensure it receives current data from the API.

Since the caching can't be made to work in all cases, stop using it. The content cache key is still used as the ETag, which allows the frontend (browser) to send an `If-None-Match` HTTP header and the backend to respond with a 304 Not Modified. That ensures the API responses will always be current but avoids the database queries if the content cache key hasn't changed

Fixes: #10968

## Summary

See above commit message.

## References

#10968

## Reviewer guidance

Make curl requests to the channel API endpoint on a locally running server and note the `ETag` in the response:

```
$ curl -sI 'http://127.0.0.1:8080/api/content/channel/' | grep -i etag:
```

In subsequent requests, include an `If-None-Match` header using the previous `ETag`:

```
$ curl -sI -H 'If-None-Match: "<etag>"' 'http://127.0.0.1:8080/api/content/channel/' | grep -i etag:
```

If the content cache key hasn't changed, a 304 response will be received instead of a 200. To update the content cache key, run

```
$ kolibri manage shell -c 'from kolibri.core.device.models import ContentCacheKey; ContentCacheKey.update_cache_key()'
```

The next request will always receive a 200 with a corresponding database query and new `ETag` since the content cache key used in `If-None-Match` header will no longer match the content cache key value used for the response `ETag`.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by jredrejo — APPROVED** [review]
I really like these code changes and I can't find any problem with them (but I must confess I always fall in love with changes deleting code) . @dbnicholson  thanks for the great explanation in the description of the PR and the detailed tests.

However, as this code affects deeply to the behaviour of the content api , It would be great to hear more opinions on this, in case I'm missing some corner case @rtibbles

**Review by rtibbles — CHANGES_REQUESTED** [review]
We can't merge this without further testing on the impact it will have on server load, as I suggested in slack conversations about this previously.

**Comment by dbnicholson** [comment]
What sort of testing would you like to see?

**Comment by rtibbles** [comment]
My main concern is the overhead of serving quite a few unmodified responses versus letting the browser cache handle it - I'll do some testing, as I think the sweet spot may be to keep a relatively short cache time in case of rapid navigation, but still allow refresh on longer time scales.

The ideal solution for this would be a 'serve cache while revalidate' strategy - but the simplest way to do that would be by using a PWA, which is only applicable in an application/localhost context, where the concerns about server load are fairly moot, because the server is only serving a single user.

**Comment by dbnicholson** [comment]
> My main concern is the overhead of serving quite a few unmodified responses versus letting the browser cache handle it - I'll do some testing, as I think the sweet spot may be to keep a relatively short cache time in case of rapid navigation, but still allow refresh on longer time scales.

These changes make it the same as every other API kolibri offers except you avoid database queries most of the time since there's an ETag. I just can't see how you can do any caching of dynamic content unless you actively purge the caches when the content is stale. I think you were pretty clear on Slack that you don't want to invalidate server cache entries. Even with a short cache time you're bound to be wrong sooner or later and the frontend has no means to do anything about it since the Django cache will persist until the TTL expires.

> The ideal solution for this would be a 'serve cache while revalidate' strategy - but the simplest way to do that would be by using a PWA, which is only applicable in an application/localhost context, where the concerns about server load are fairly moot, because the server is only serving a single user.

That's essentially what's happening. The browser will still cache the response and reuse it when the server says it's OK to use. The default `max-age=0` TTL means that it has to revalidate every request since it's immediately stale. It's effectively the same as [`no-cache`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#no-cache).

**Comment by rtibbles** [comment]
Superseded by #11157

**Pull request closed without merging**
