### PR TITLE
Unsupported browser message internationalization

### LINKED ISSUE #6240: 'unsupported browser' message is not internationalized
### Observed behavior

Regardless of what language Kolibri or a user's browser is set to, they always see the message in English:

image

### Expected behavior

'unsupported browser' should show in the default language of the server

### User-facing consequences

less helpful message in other language

### Steps to reproduce

* set default device language to something other than english
* load any page using a user agent of an unsupported browser

### Context

0.13.0

### PR DESCRIPTION
**Pull request by priyanka-choubey**
### Summary
Fixes #6240 
Internationalization added for 'Unsupported browser' string.

----

### Contributor Checklist

PR process:

- [X] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by priyanka-choubey** [comment]
@indirectlylit @kollivier @jonboiser since I am working on ubuntu I was not able to test it. But I think it should work. Kindly review and let me know if any changes are required.

**Review by kollivier — CHANGES_REQUESTED** [review]
Thank you for looking into this, but this is not the correct fix. `$tr` is to be used in Vue templates (files with `.vue` extension), but this is a Django template file. Also, you only applied the change to the page's title string and not any of the text in it, so even if your fix had worked, only the "Unsupported browser" text would be translated into the correct language. The description would have remained in English. 

Had you tested your changes locally, you would have realized this was not the correct fix before submitting the change for review. If you wish to submit PRs for code changes, please use our documentation to learn how to setup your dev environment and test locally before submitting.

**Comment by priyanka-choubey** [comment]
@kollivier  Yeah, just noticed the same when I saw the travis logs. I was not able to test this since I am working on ubuntu and all the browsers are compatible with it. I tried changing the browserslist file and used the command `npx browserslist` to remove firefox, but it didnot work. I also tried running it on obsolete browsers like arora and pale moon, but it was still compatible. Can you tell how I can test this on ubuntu. Thankyou

**Comment by kollivier** [comment]
@priyanka-choubey The unsupported browser page can be viewed on a supported browser by directly loading the URL for that page into the browser. The correct URL to load can be found by checking the code.

**Comment by indirectlylit** [comment]
@priyanka-choubey see:

https://developers.google.com/web/tools/chrome-devtools/device-mode/override-user-agent

Looks like this is no longer an issue: I am able to control the language with the device settings.

However while testing I opened this new issue: https://github.com/learningequality/kolibri/issues/6640

**Pull request closed without merging**
