### PR TITLE
Updates points pop up

### LINKED ISSUE #1576: Improve points popover
## Summary

* Improve points popover. Currently not centered. Maybe make use of the `core-modal`?
* See https://github.com/learningequality/kolibri/issues/1471#issuecomment-302723662

### PR DESCRIPTION
**Pull request by christianmemije**
## Summary

* Updates points pop up
* Fixes #1576

## Before

before

## After
after

### CODE REVIEW

**Comment by rtibbles** [comment]
Lint error: https://travis-ci.org/learningequality/kolibri/jobs/239727782#L523

**Comment by rtibbles** [comment]
@khangmach please weigh in for styling. Code looks fine, needs lint though.

**Comment by khangmach** [comment]
@richard looks fine. bit more bottom margin below the buttons. lots of room for clicking error if a user wanted to click next item but clicked out of the modal.

**Comment by christianmemije** [comment]
@rtibbles Addressed lint issue. 
@khangmach Updated spacing

new

**Pull request merged**
