### PR TITLE
Merge 012 into develop

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

0.12 merge

### Reviewer guidance

resolves some conflicts related to #5356 - @rtibbles @MisRob mind checking this out?

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by MisRob** [comment]
I'm not sure what were conflicts related to #5356 exactly but can see that there are some modifications of `kolibri/plugins/coach/class_summary_api.py` in this PR's diff which is the only file that was also modified in #5356, but those changes are not related to permissions so from this point of view, this merge looks good to me.

**Comment by MisRob** [comment]
Oh yes, I can see what you mean now, tried to merge 012 to develop locally and more #5356 files were affected. Those conflicts seem to have something in common with formatting. I probably cherry-picked them after we had black formatting turned on already in develop but didn't check if there are some newer changes to be applied to those files. Sorry for that - hope it wasn't complicated. According to the diff against develop, looks good (but not sure about other files that are not related to  #5356).

**Review by rtibbles — CHANGES_REQUESTED** [review]
The changes in `class_summary_api.py` should be resolved in favour of develop. These are recent additions in develop, not things that have been removed in 0.12.x.

**Comment by indirectlylit** [comment]
thanks, updated!

**Review by rtibbles — APPROVED** [review]

**Pull request merged**
