### PR TITLE
Old android build cleanup 0.11

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

Bringing in build cleanup from 0.10

### Reviewer guidance

Should build just fine, but just make sure of it.

### References

#6897 

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by DXCanas** [comment]
Some conflicts needed resolving

**Comment by lyw07** [comment]
should we also remove the file `build_apk.sh`? thanks!

**Comment by DXCanas** [comment]
> should we also remove the file `build_apk.sh`? thanks!

Somehow I messed that part up during the conflict resolution :upside_down_face:

**Review by lyw07 — APPROVED** [review]
LGTM! The builds failed, but are expected.

**Pull request merged**
