### PR TITLE
Nav feature branch

### PR DESCRIPTION
**Pull request by indirectlylit**
## Summary

WIP PR for the Nav feature branch, here so we can easily see changes.

## TODO

- [ ] Have tests been written for the new code?
- [ ] Has documentation been written/updated?
- [ ] New dependencies (if any) added to requirements file
- [ ] Add an entry to CHANGELOG.rst
- [ ] Add yourself it AUTHORS.rst if you don't appear there

## Reviewer guidance

*If you PR has a significant size, give the reviewer some helpful remarks*

## Issues addressed

List the issues solved or partly solved by the PR

## Documentation

If the PR has documentation, link the file here (either .rst in your repo or if built on Read The Docs)

## Screenshots (if appropriate)

They're nice. :)

### CODE REVIEW

**Comment by rtibbles** [comment]
What's the plan for this branch? Is there any code here that isn't in master that we need to keep?

**Comment by radinamatic** [comment]
@rtibbles I added back a11y stuff in #240, so for me this branch can be deleted!

**Comment by indirectlylit** [comment]
Looks like the main thing we need to look at is `core/assets/src/navigation.vue` and how it gets populated with cross-plugin URL info. Eventually we'll need to integrate this with the learn-plugin-specific nav component we have for the MMVP app.

**Comment by indirectlylit** [comment]
This PR hasn't been kept up-to-date with master, so I'm going to close it. There may still be some useful code in here for the nav and management work coming up, but we can simply use this as reference.

**Pull request closed without merging**
