### PR TITLE
Fix for issue #5366

### PR DESCRIPTION
**Pull request by dolfandringa**
### Summary

Changed ChannelMetadata.published_size from IntegerField to BigIntegerField. This is necessary at least for PostgreSQL to be able to handle large content libraries such as the library from the Khan Academy. See issue #5366. The Khan Academy data is over 30Gb, which in bytes (3.22e10) is over 10 times the maximum size of a regular integer in postgresql (2.15e9). SQLite doesn't seem to distinguish between int and bigint, but postgresql certainly does. Bigint in postgresql uses 8 bytes for the integer, just like the maximum size for sqlite.

I have run the unit tests, but a lot of them failed with SQLite errors that tables didn't exist. I couldn't find any relation to my work, so don't want to dig in deeply why the tests are failing. I also manually patched the installation I have running using the kolibri-server (from the proposed ppa), and the problem I was having in issue #5366 seems fixed with my change.

### Reviewer guidance
Run the application with PostgreSQL as a db, and try to import the full (english) Khan Academy collection. 

### References
 * https://www.postgresql.org/docs/9.1/datatype-numeric.html
 * https://www.tutorialspoint.com/sqlite/sqlite_data_types.htm

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by rtibbles** [comment]
If you try to run the full test suite locally, we have an outstanding issue whereby our dbrestore tests are insufficiently sandboxed, and create leakage which causes errors in unrelated tests, so this may have been what you are seeing. If Travis gives this the OK, then we should be fine!

**Comment by dolfandringa** [comment]
I'd be happy to add tests or run the current set of tests locally to improve the PR if required. Suggestions are welcome.

**Comment by rtibbles** [comment]
Sorry, tried to retarget to `release-v0.12.x` so that we could release this sooner, but the branch would require a rebase to do that, would you be able to do that? (if not, I can cherry pick this back later, so no worries).

**Comment by dolfandringa** [comment]
> Sorry, tried to retarget to `release-v0.12.x` so that we could release this sooner, but the branch would require a rebase to do that, would you be able to do that? (if not, I can cherry pick this back later, so no worries).

Checking.

**Comment by dolfandringa** [comment]
> > Sorry, tried to retarget to `release-v0.12.x` so that we could release this sooner, but the branch would require a rebase to do that, would you be able to do that? (if not, I can cherry pick this back later, so no worries).
> 
> Checking.

Nope, a ton of issues. It would be quicker to just create a new branch of 0.12.x and then a new PR.

**Comment by dolfandringa** [comment]
> > > Sorry, tried to retarget to `release-v0.12.x` so that we could release this sooner, but the branch would require a rebase to do that, would you be able to do that? (if not, I can cherry pick this back later, so no worries).
> > 
> > 
> > Checking.
> 
> Nope, a ton of issues. It would be quicker to just create a new branch of 0.12.x and then a new PR.

I'd rather have it released sooner rather than later, so if I can re-do the PR from the 0.12.x branch, that'd be fine by me.

**Comment by rtibbles** [comment]
No worries, we'll review it as is, and can then cherry pick for release-v0.12.x.

**Review by ralphiee22 — APPROVED** [review]

**Pull request merged**
