### PR TITLE
Clean up renderer height styling behaviour

### LINKED ISSUE #11311: Coach>Plan/Reports - Missing scrollbar when previewing a resource of type PDF
## Observed behavior
There's no scroll bar while previewing a resource of type PDF. A scrollbar is displayed for the rest of the available resource types.

## Expected behavior
A scrollbar should be displayed when previewing a PDF resource.

## Steps to reproduce the issue
1. Install the latest Beta 6 build.
2. Go to Coach>Reports>Lessons>Lesson>PDF resource>Preview or Coach>Plan>Lessons > Lesson > PDF resource

## More information

https://github.com/learningequality/kolibri/assets/79847249/eecea9cc-281b-41f3-b71c-d978f82b1aca

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome, Firefox

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Removes use of Learn specific height remediations from HTML5 app renderer and PDF renderer
* Reworks styling of PDF renderer to no longer require a global attribute setting on the page html tag, which was causing an issue when the PDF renderer was embedded in pages that needed to scroll independently of the PDF
* Makes styling of the PDF renderer consistent as long as the embedded use of the KContentRenderer has a specified height

## References
Fixes #11311

## Reviewer guidance
Create a lesson
Manage resources
Try to add a PDF and preview it
Observe that the page can still scroll
image

View a PDF in Learn, ensure that it behaves as expected
image

View an HTML5 app in Learn ensure that it behaves as expected

image

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [X] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by nucleogenesis — COMMENTED** [review]
Looking through the code things look good. I'll spin it tomorrow so I can better visualize the styles in devtools and test things out.

**Review by pcenov — CHANGES_REQUESTED** [review]
Both pdf and HTML resources are displayed correctly except in mobile view where the PDFs are initially displayed in all black that is until the user selects the bookmarks menu. Seems that this is happening when viewing in resolution less than 840 px. 

https://github.com/learningequality/kolibri/assets/79847249/4c8085c6-2e8e-45a6-8e91-acc0d6b2e747

**Comment by rtibbles** [comment]
Interesting, thanks for the check, @pcenov! I'll see what's happening there.

**Comment by rtibbles** [comment]
OK, I think this should all be working as expected now!

**Review by pcenov — APPROVED** [review]
I confirm - everything is working as expected now.

**Pull request merged**
