### PR TITLE
Upgrade to KDS v3.0.0 and reference npm package

### PR DESCRIPTION
**Pull request by MisRob**
## Summary

- Upgrades KDS from somewhere in the middle of v3.0.0 commits to v3.0.0. Includes Kolibri code updates related to the breaking change in regards to `value` --> `buttonValue` renaming. See [KDS v3.0.0 release notes](https://github.com/learningequality/kolibri-design-system/releases/tag/v3.0.0). I've manually tested a few places with radio buttons after the update but not all of them.

- Uses npm package to install KDS
  - I discussed with @rtibbles that it doesn't matter that much if we pin minor or patch because of the dependabot workflow, so we went with patch `~`. This has a benefit of knowing exactly what version is installed.

## Reviewer guidance

- `value` --> `buttonValue`
  - You could check that for all radio buttons I updated, the intention for using `value` was indeed to use it as a prop to set the radio button's value HTML attribute (rather than as Vue value binding - in such cases it should stay `:value`) 
  - Are there some forgotten places that still need to be updated?
  - You could test manually few places with radio buttons

----

## Testing checklist

- [x] Contributor has ~fully~ partially :) tested the PR manually
- [ ] ~If there are any front-end changes, before/after screenshots are included~
- [ ] ~Critical user journeys are covered by Gherkin stories~
- [ ] ~Critical and brittle code paths are covered by unit tests~

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] ~If this is an important user-facing change, PR or related issue has a 'changelog' label~
- [ ] ~If this includes an internal dependency change, a link to the diff is provided~

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by MisRob** [comment]
Hi @pcenov, would you have a moment to confirm that radio buttons at a few (any) places in Kolibri still work well?

**Review by pcenov — APPROVED** [review]
Hi @MisRob - no issues observed with the radio buttons in the setup wizard and anywhere else!

**Review by LianaHarris360 — APPROVED** [review]
I did not find any places that still needed changes, everything looks good and works as expected!

**Comment by MisRob** [comment]
Thanks both

**Pull request merged**
