### PR TITLE
Remove Last-Modified from response. Not needed.

### PR DESCRIPTION
**Pull request by aronasorman**
Keeping this line gives an error on Windows.

### CODE REVIEW

**Comment by indirectlylit** [comment]
this is targetted to the release branch. Did you want it merged in?

**Comment by aronasorman** [comment]
@indirectlylit yup. This prevents the windows installers from serving Perseus zip files. 

Although now that I think about it, it's not required since VF won't be running the servers on Windows. We'll want this at least for future releases though. Maybe retarget to develop?

**Comment by indirectlylit** [comment]
> Although now that I think about it, it's not required since VF won't be running the servers on Windows. We'll want this at least for future releases though. Maybe retarget to develop?

Yes please

**Comment by aronasorman** [comment]
@indirectlylit retargeted using Github's PR retargeting feature. There's extra commits here now, but some of them are essential, such as the fixes for i18n serving.

My sense is to continue with this PR (after I resolve the merge conflict) and get these important changes into develop. What do you think?

**Comment by indirectlylit** [comment]
Master hasn't been merged back to Develop yet. Some commits might disappear once that happens.

If you merge Master into this branch and resolve any conflicts, this PR will be good.

**Comment by aronasorman** [comment]
Alright, pushed. The conflict should resolve itself once master and develop are merged again 👍

**Comment by indirectlylit** [comment]
for some reason this PR still shows a bunch of commits that shouldn't be there

**Comment by indirectlylit** [comment]
see #1102

**Pull request closed without merging**
