### PR TITLE
fix: validation

### LINKED ISSUE #11540: Setup Wizard > LOD > Import user - Missing validation for uppercase in the usernames and passwords
## Observed behavior

Initially I thought that the import of a learner from the server to the LOD is not functioning anymore after the latest changes in https://github.com/learningequality/kolibri/pull/11525. In reality both the username and the password of the learner I was trying to import were in uppercase while I was inputting them in lowercase. Therefore the issue is about the proper validation for uppercase.

https://github.com/learningequality/kolibri/assets/79847249/65406d93-2b36-48bf-8162-98d213bb6d5a

## Expected behavior

The user should see validation for incorrect username and password. This should be fixed for both the learner credentials form and the admin credentials form.

## Steps to reproduce the issue
1. Install the [latest Beta 8 build asset](https://github.com/learningequality/kolibri/pull/11525).
2. Setup a server device with learners and assigned lessons.
3. On a separate device start the setup wizard and attempt to import an individual learner through the learn-only device user flow by inputting either the password or the username in incorrect letter case.

## Logs

https://drive.google.com/drive/folders/1OImtokSocwqMa84Yv4acDRn8e8uylv91

## Usage Details
Ubuntu 22  - Chrome, Android 13

### PR DESCRIPTION
**Pull request by nick2432**
## Summary

I updated the response in error so that the correct error can be catched on the frontend.
Screenshot from 2023-12-25 14-21-53

Screenshot from 2023-12-25 14-21-49

## References
Fixes https://github.com/learningequality/kolibri/issues/11540

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by nick2432** [comment]
@AlexVelezLl  @radinamatic Why are these tests failing?

**Comment by radinamatic** [comment]
@nick2432 Did you try [running the recommended commands](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#linting-and-auto-formatting) to fix the linting errors?

**Review by AlexVelezLl — COMMENTED** [review]
Tried to replicate the issue but couldn't be able to get the 500 error that @pcenov reported. Will wait for @pcenov to review the PR and confirm that it solves the problem.

**Comment by nick2432** [comment]
> Tried to replicate the issue but couldn't be able to get the 500 error that @pcenov reported. Will wait for @pcenov to review the PR and confirm that it solves the problem.

ok

**Comment by nick2432** [comment]
> @nick2432 Did you try [running the recommended commands](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#linting-and-auto-formatting) to fix the linting errors?

No, I haven't tried the recommended commands yet. I'll give them a shot. Thanks for the suggestion!

**Comment by radinamatic** [comment]
@pcenov Artifacts should be ready for testing, thank you!

**Comment by pcenov** [comment]
Hi @nick2432 could you double check what is going here as when testing with the [latest .deb asset](https://github.com/learningequality/kolibri/suites/19471739725/artifacts/1148303106) I am not seeing any changes to the issues described in https://github.com/learningequality/kolibri/issues/11540
Specifically if I try to import a learner by inputting the username with incorrect letter case (the correct username is L1 while I am typing l1) then when I click the Finish button I still get an error screen. 

https://github.com/learningequality/kolibri/assets/79847249/6a6eb274-ddf1-4e3e-8284-63641c05d897

Also there's still the `500 Internal Server error` issue if on the server I have enabled the `Require password for learners` setting at Facility >Settings:

https://github.com/learningequality/kolibri/assets/79847249/53b14c13-b144-433a-9260-c452ad97fee6

On a side note @radinamatic while taking a closer look at the required fields validation behavior at both `Import individual user accounts` and `Use an admin account` it's completely missing at the moment. I think this will be covered by work here https://github.com/learningequality/kolibri/issues/11605 but posting a recording of what I am observing to keep things consolidated:

https://github.com/learningequality/kolibri/assets/79847249/860075e0-8baf-458f-80e3-d5acc9d08652

**Comment by nick2432** [comment]
@pcenov  yes, this one is not working, but when I made changes to the code and tested it locally, it worked fine. I believe the 500 internal error is resolved by @bjester  . Link: (https://github.com/learningequality/kolibri/pull/11541). I only resolved the validation error part.

https://github.com/learningequality/kolibri/assets/77477551/ae6579e1-2591-4db7-a00a-fbc1258866d7

**Review by bjester — CHANGES_REQUESTED** [review]
As @pcenov noted, this introduces a regression that was fixed in https://github.com/learningequality/kolibri/pull/11541 and therefore causes a 500 error under specific circumstances:
> Also there's still the 500 Internal Server error issue if on the server I have enabled the Require password for learners setting at Facility >Settings

**Comment by nick2432** [comment]
When I used this change, I did not encounter a 500 error, as shown in the video above, @bjester  .
> @pcenov yes, this one is not working, but when I made changes to the code and tested it locally, it worked fine. I believe the 500 internal error is resolved by @bjester . Link: (#11541). I only resolved the validation error part.
> 
>  2024-01-06.09-36-35.mp4

**Comment by bjester** [comment]
@nick2432 There are two code paths that you changed, which result in two different `AuthenticationFailed` scenarios. The video you shared seems to produce one of them, but what about the other? If we assume the 500 error is a regression and caused by the same issue, and you take a look at the fix for the 500 error, it occurred when the server was preparing a 403 response:
```
  File "/usr/lib/python3/dist-packages/kolibri/core/utils/exception_handler.py", line 21, in custom_exception_handler
    response.data = _handle_403_format(response, context)
  File "/usr/lib/python3/dist-packages/kolibri/core/utils/exception_handler.py", line 60, in _handle_403_format
    "id": response.data["detail"].code.upper(),
TypeError: list indices must be integers or slices, not str
```

Your video shows a 401 response being returned.

**Comment by rtibbles** [comment]
Before continuing to work on this here, it is worth noting that some intersecting work on a related issue may be useful to work on top of. @jredrejo's PR #11704 when merged will be good to work on top of (and may be perhaps worth starting fresh on top of to solve just the uppercase validation issue).

**Comment by nick2432** [comment]
@rtibbles  , should I close this PR and wait until https://github.com/learningequality/kolibri/pull/11704 is merged?

**Comment by rtibbles** [comment]
#11704 has now been merged. I'd suggest starting from current release-v0.16.x, focusing specifically on the casing issue.

**Comment by nick2432** [comment]
> #11704 has now been merged. I'd suggest starting from current release-v0.16.x, focusing specifically on the casing issue.

@rtibbles @pcenov @bjester 
If the letter case is incorrect, what should I do? Should it return an error stating 'username not valid'?

**Pull request closed without merging**
