### PR TITLE
Update videojs to latest version to allow CC menu to close on touch

### LINKED ISSUE #4602: While watching a video on a tablet, the cc options menu will not close
### Observed behavior
While watching video on tablet, when user click CC button then CC button options don't disappear clicking on it.

Please watch attached video.

### Expected behavior
It must appear when we click on button and must go behind on click.

### Steps to reproduce
1. Login with learner on tablet.
2. Watch video and click on CC button.

### Context
 * Kolibri version : kolibri 0.11.0
 * Operating system : Ubuntu 14.04
 * Browser : chrome

### screenshot:
img_20181213_164656

[VID_20181213_164504.mp4.zip](https://github.com/learningequality/kolibri/files/2675921/VID_20181213_164504.mp4.zip)

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
A bug in our current version of VideoJS prevents the CC menu from closing due to touch events.
I looked at the VideoJS source and found that the current version properly handles this.
Tried upgrading, it fixed it, and nothing seemed to break (I checked the major version changelog, and the only thing that seemed to happen was dropping support for IE<=10).

### Reviewer guidance
Make sure the video player still works as expected.
Test on a touch device or browser stack to confirm the fix.

Before
subs_pre_fix

After
subs_post_fix

### References
Fixes #4602 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Review by indirectlylit — APPROVED** [review]
great - merging in for hack session today

**Comment by radinamatic** [comment]
Dang, too fast for me, will hack over tonight!

**Comment by indirectlylit** [comment]
thanks :) sorry I'm going against protocol with the idea that folks will be more likely to surface any issues during hack today

**Comment by rtibbles** [comment]
Apologies for the potato gif.

**Pull request merged**
