### PR TITLE
fix issue #32 by silently canceling save on immediate cyclic related_…

### PR DESCRIPTION
**Pull request by 66eli77**
## Summary

This PR will allow user save on immediate cyclic related relationship, but silently cancel the save

## TODO

- [x] Have tests been written for the new code?

## Issues addressed

#32 

They're nice. :)

### CODE REVIEW

**Comment by MCGallaspy** [comment]
Please try to follow the PR template: https://github.com/learningequality/kolibri/blob/master/CONTRIBUTING.rst#pull-request-guidelines

Also, you seem to be *losing* test coverage -- I think in these early stages, we should aim to at least break even if not *increase* test coverage with every PR.

**Comment by 66eli77** [comment]
I think the coverage lost is due to a couple of functions are deleted.
That's perfectly healthy.

**Comment by rtibbles** [comment]
Coverage would not go down in that case, as it is expressed as a percentage
of the total code base.

**Comment by 66eli77** [comment]
I see. the commit above should recover the lost

**Comment by 66eli77** [comment]
@rtibbles what do you think about this approach to deal with symmetric relationship? It will behave the same as if symmetric relationship is allowed

**Comment by rtibbles** [comment]
I am not sure disallowing the symmetric relationship for the related content is particularly important.

What is more important is what I detailed in the issue - that when we reference 'related_content' it returns a unique set of both the relation and reverse relation.

**Comment by rtibbles** [comment]
See my comment, this doesn't fix the issue.

**Comment by 66eli77** [comment]
I'm not quite sure If I understand the desire behavior you have in mind. The current behavior is that when call c1.is_related.all(), you get all the nodes that's related to c1, no matter the relationship is established by other nodes or by c1 itself. Isn't this what you want?

**Pull request merged**
