### PR TITLE
[UAP] Roles and collections hierarchy

### PR DESCRIPTION
**Pull request by MCGallaspy**
## Summary

Continue implementing the UAP backend. Looking back, I'm not finding the commit names super informative -- happy to amend the messages for this PR at request. Supersedes #19.

## TODO

- [x] Have tests been written for the new code?
- [x] Has documentation been written/updated? **Updates existing docs page through automodule directive**
- [x] New dependencies (if any) added to requirements file
- [x] Add an entry to CHANGELOG.rst

## Reviewer guidance

4 new Models added, which is the main action of this PR. Their purpose is described in the technical spec (see documentation section below). This PR mainly implements `HierarchyNode`, with following PRs implementing `Role` and `Collection`, as well as permissions checking.

## Documentation

See the [UAP tech spec](https://docs.google.com/document/d/1BcOSxhoAOZGKjg9e7C6PpeQfHj9zkDqrKIk1WrbLsDU/edit#heading=h.fzctnhrv2u2t) for more info.

### CODE REVIEW

**Comment by MCGallaspy** [comment]
By the way, this supersedes #19 because we've decided the "natural" tree structure for Collections and Roles is not less efficient than the one built in #19.

**Comment by benjaoming** [comment]
My intuition was misguided: I thought "roles" had something to do with permissions given its location in the `auth` app :)

I think [this](https://docs.google.com/drawings/d/1CI_li7fqYpymWDwbhpjkzpB9es76-nzH5lp4hm7akZA/edit) illustration deserves to be in the docs!

Btw. amazing work elaborating you guys, I can see you've had a long day of discussions and illustrating on the whiteboard :)

**Comment by MCGallaspy** [comment]
> I think this illustration deserves to be in the docs!

Done.

**Comment by MCGallaspy** [comment]
@benjaoming thanks for the reviews so far, are you happy to continue reviewing these PRs? Or should we pass the buck to someone else?

**Comment by benjaoming** [comment]
@MCGallaspy no for the sake of keeping up2date with everything, I like to review, and I want to at least keep doing that while shipping KA Lites :)

**Comment by benjaoming** [comment]
So this is good to go, right? I have no further comments at this moment, everything I commented on was wonderfully addressed :+1:

**Comment by MCGallaspy** [comment]
Yes, I'll merge this, rebase the later PRs and coordinate with you @benjaoming for the next steps.

**Pull request merged**
