### PR TITLE
Update background

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Cherry picks https://github.com/learningequality/kolibri/pull/12207 back into 0.16.x where it was meant to be targeted
* Updates the background image for the rebrand
* Updates how we display the background image, allowing us to apply a `blur` filter on compatible browsers (most browsers that we support, except IE11) to prevent the image looking lower quality on higher resolution screens. This was previously masked by the use of a higher opacity overlay on the image, but this has been reduced in order to make colors in the background image more vibrant.

### CODE REVIEW

**Review by nucleogenesis — COMMENTED** [review]
I ran it locally and it looks awesome -- totally jives with the new theme much better.

Just one question - why the move of the `static/assets/default_theme` into kolibri core from the `default_theme` plugin?

**Comment by rtibbles** [comment]
> Just one question - why the move of the static/assets/default_theme into kolibri core from the default_theme plugin?

This was a result of my putting a lot of these images in the wrong place, and then @marcellamaki cleaning them up somewhat. But I do think they could be put into the default theme plugin static folder instead of the core static folder (that was a result of my miscommunicating the cleanup to @marcellamaki, and missing this when I merged the PR). Will clean up now.

**Comment by rtibbles** [comment]
Updated!

**Review by nucleogenesis — APPROVED** [review]
Thanks for clarifying! Code / dir updates look good

**Comment by radinamatic** [comment]
Looking good in 3 browsers on both Ubuntu 20.04 and Windows 10:

Ubuntu | Windows
-- | --
Ubuntu20 04 | Windows10

**Review by radinamatic — APPROVED** [review]
LGTM, :shipit:

**Pull request merged**
