### PR TITLE
Silence the `make dist` output.

### PR DESCRIPTION
**Pull request by aronasorman**
To minimize test logs.

### CODE REVIEW

**Comment by benjaoming** [comment]
It's not supposed to be running though, unless build stuff is changed... is something wrong with the conditioned testing?

**Comment by rtibbles** [comment]
@benjaoming it seems to be running all the time, yeah.

**Comment by benjaoming** [comment]
Wow that's a bummer, it makes the tests much slower because running `make dist` is quite huge. How did you live with that? :)

**Comment by benjaoming** [comment]
I'm looking at it now...

**Comment by rtibbles** [comment]
It's been tough, thanks!

**Comment by benjaoming** [comment]
No matter that there is a conditional thing that calls this test on every build, I support killing off the output since it's unreadable on a laptop with less than 1024 GB RAM.

**Comment by rtibbles** [comment]
Yay! I can read logs now!

**Pull request merged**
