### PR TITLE
Make a tabs core component.

### PR DESCRIPTION
**Pull request by christianmemije**
## Summary

Made a tabs core component.

## Reviewer guidance

I emit the index of the tab upon click, let me know if there's a cleaner solution to this. Allows plugin to determine what happens upon click regardless if that tab is already selected. Feedback appreciated.

### CODE REVIEW

**Comment by 66eli77** [comment]
I wonder if you can set `@click=gotClicked(item.title)` to ui-tab component, will it work. If it works, there's no need to set the ref and the for loop.

**Comment by rtibbles** [comment]
I've just been experimenting with that, it doesn't seem to. Not quite sure of the cause, although within the Keen component itself, there is a lot of suppression of event propagation.

**Comment by christianmemije** [comment]
@66eli77 That was not possible, that's why I used this hacky way.

**Comment by indirectlylit** [comment]
maybe it would be possible to make a wrapper component around `ui-tab` which emits the click?

**Comment by 66eli77** [comment]
This is the pattern I saw in Keen.ui's source code. 
The `ui-tab` component we passed in to `ui-tabs` are set to `display=none`(therefore no click event), but serve as an intermediary to feed data to the `ui-tab-header-item` component, which gets displayed by `ui-tags` component. Not entirely sure what's the purpose to have this intermediary pattern.
after I change the css of `ui-tab` to `display=block`, the click event fires successfully.

**Comment by 66eli77** [comment]
@christianmemije  I opened a PR (https://github.com/christianmemije/kolibri/pull/12) targeting this branch for an alternative solution.

**Pull request merged**
