### PR TITLE
Updates to the generateuserdata management command - part 2

### PR DESCRIPTION
**Pull request by cpauya**
### Summary

**Original PR with discussions** https://github.com/learningequality/kolibri/pull/6983 - *Most texts below are just copy-pasted from the original PR mentioned above.*

Some updates for the `generateuserdata` management command useful for integration testing.
* ARG: `device-name` - prepend this to the name of facilities, classes, groups, learners when created.  This is useful when testing P2P syncing of data.
* ARG: `max-channels` - limit to number of channels to create learner activity, instead of all which will take time
* Use `kolibri manage help generateuserdata` to show all possible arguments.
* Examples: 
    * `kolibri manage generateuserdata --no-onboarding --facilities 2 --device-name VM1`
    * `kolibri manage generateuserdata --no-onboarding --facilities 1 --classes 4 --users 20 --max-channels 1 --device-name VM1`

#### Use of the `device-name` argument
When specified, the command does the following:
* Device name prepended to the facilities and users created.
* The Facility name (with prepended device name above) is prepended to the classes created.
* Example: `kolibri manage generateuserdata --no-onboarding --facilities 2 --users 2 --device-name VM1`
    * Generates the following sample data:
    ```
        * VM1 Facility1
            * VM1 Facility1 Class1A
                * VM1 learner-name-from-csv
                * VM1 learner-name-from-csv
            * VM1 Facility1 Class1B
                * VM1 learner-name-from-csv
                * VM1 learner-name-from-csv
        * VM1 Facility2
            * VM1 Facility1 Class2C
                * VM1 learner-name-from-csv
                * VM1 learner-name-from-csv
            * VM1 Facility1 Class2D
                * VM1 learner-name-from-csv
                * VM1 learner-name-from-csv
    ```

### ToDos:
- [ ] Generate classes, groups, lessons, and learners without importing a channel first.
- [ ] Implement the `num-groups` argument
- [ ] For generating learner activities, use channel token/s instead of just limiting the number of channels with `max-channels`
- [ ] Other notes at the [Notion Page for this task](https://www.notion.so/learningequality/Look-at-generateuserdata-if-can-be-modified-to-be-useful-for-integration-testing-0d5de37ed3d942b89f04e2f044608597)
    - [ ] Quizzes
    - [ ] Lessons
    - [ ] etc

### Reviewer guidance

To test, do the following:

#### Part 1 - Run `generateuserdata` command and test it's arguments and data generated:

1. Checkout this branch and follow the [instructions how to setup Kolibri for development](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#setting-up-kolibri-for-development).  Stop after installing Yarn, just before running Kolibri.
1. Optional: Delete the Sqlite3 database, make a backup if you still need it!  Run in terminal:
    * `rm ~/.kolibri/db.sqlite3`
    * repeat this step during devt and testing for a clean database
1. Test the command:
    * `kolibri manage generateuserdata --no-onboarding --facilities 2 --device-name VM1`
    * this will auto-run migrations if needed
    * variations, experiment with the arguments:
        *    `kolibri manage generateuserdata --facilities 1 users 40`
        *    `kolibri manage generateuserdata --facilities 1 --classes 4 users 20 --device-name VM1`
        *    `kolibri manage generateuserdata`

1. Run Kolibri
    * `yarn devserver`
1. Open http://0.0.0.0:8000/ in web browser
    * login as superuser/password
    * this super user account is auto-generated with the `--no-onboarding` argument
1. Navigate to the Facility, Coach, and Learners pages

#### Part 2 - Import a Channel and generate learner activities on the channel
The following imports content then re-runs the command to auto-create learner activities on the imported channel:
1. Import channel content using this token: `nakav-mafak` = Radina's Testing Channel
1. After importing channel content, stop Kolibri then run in Terminal: 
    * `kolibri manage generateuserdata --no-onboarding --facilities 2 --device-name VM1`
    * this will add activity data for the learners
1. You can import more channels to test the `max-channels` argument.  Then stop Kolibri and run in Terminal: 
    * `kolibri manage generateuserdata --no-onboarding --facilities 2 --device-name VM1 --max-channels 2`
        * this will add activity data for the learners up to 2 channels only
        * WARNING: This will take a long time, depends on how large the channel and the number of users. 
1. Start Kolibri again, run in Terminal: `yarn devserver`
1. Open http://0.0.0.0:8000/ in web browser and navigate to the Facility, Coach, Quizzes, Learners, Reports, and Activity pages.

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [x] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [x] Critical user journeys are covered by Gherkin stories
- [x] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
All apparently working as described, so easy now to have various facilities ready! :+1: 

It is a bit unintuitive to have to run the same command for the second time after content import, but hey, as long as we get interactions, sounds good. We can keep improving in future iterations.

One other thing may be misleading is the `--device-name` argument, as it just defines the prepend- string to distinguish the device, but it does NOT actually rename it, right?

It would be good to get some feedback and/or suggestions from @jonboiser, before we merge this.

**Review by jonboiser — APPROVED** [review]
Looks good to me!

**Comment by jonboiser** [comment]
I'll leave it to @cpauya to merge when it's ready!

**Comment by radinamatic** [comment]
@cpauya Let's merge this so the implemented features can be available for the installer we are going to use during integration testing starting on Monday, and transfer the remaining ToDo's to a new PR so you can work on them for the subsequent betas. Great work!

**Pull request merged**
