### PR TITLE
Improve performance of facility class admin pages

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
The `HierarchyRelationsFilter` produces complex queries that are not performant. This results in very slow queries to the point of timing out in large class sizes when querying the facility user endpoint with a `member_of` query parameter.

This changes how the `member_of` query parameter filters users, by instead looking for a direct membership. This means that users will no longer show as members of a parent collection by virtue of being a member of the child collection. Practically, this makes no difference, as we do not allow such things to be set through the interface, but we should eventually make this necessary in order to enforce this properly in the code.

### Reviewer guidance
Load the Facility admin page for a specific class - make sure it loads, and is accurate.

### References
Query summary before the change:
Screenshot from 2020-03-30 15-48-24

Query summary after the change:
Screenshot from 2020-03-30 15-48-36

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by indirectlylit — DISMISSED** [review]
This update causes a regression where the users tab becomes empty:

| after | before |
|--|--|
| image |image|

Maybe it would help to have two filters, e.g 

* `filter_member_of` which handles recursion
* `filter_direct_member_of` which is used where we know we only need direct children

**Comment by rtibbles** [comment]
Thanks for testing, I obviously missed something here.

> Maybe it would help to have two filters

We could - the main question is whether this is helpful going forwards, as we never allow indirect membership in practice (so perhaps we should outlaw it and enforce denormalized membership?)

**Comment by indirectlylit** [comment]
From what I can tell, membership in a facility is _not_ stored in the Membership table, but is instead stored implicitly by the Facility attribute on the User model, so there is some inconsistency there.

I don't know what the right answer is, but I do believe that we may eventually want to surface KDP collection concepts above facility (like Organization) within Kolibri, so that's a consideration when deciding whether all membership concepts should be denormalized.

One other thought: `HierarchyRelationsFilter` is used in many places besides here. Should we update this comment with warnings about the efficiency?

https://github.com/learningequality/kolibri/blob/18ddeea5a9b1e08a4fa0e1c66c612db0aef40f37/kolibri/core/auth/filters.py#L9-L16

**Comment by indirectlylit** [comment]
removing 0.13.2 milestone

**Comment by rtibbles** [comment]
Updated to fix issue - now filtering by collection membership or facility.

Performance remains the same.

**Review by indirectlylit — APPROVED** [review]
this looks good to me.

Before releasing 0.13.3, we can do a sanity-check integration test pass on coach and facility functionality with just a single platform

**Pull request merged**
