### PR TITLE
Optimize loader

### PR DESCRIPTION
**Pull request by MisRob**
#### Description
Replace poorly exported gif loader with inline SVG (optimized with [svgo](https://github.com/svg/svgo)) + css animation.

#### Manual checks
 - locally - Safari, Chrome, Firefox (latest)
- Browserstack - IE9 (NOK), IE10, IE11, Edge

IE9 doesn't support CSS animations => loader is not working properly there (looks simply like static image). In [dev docs](https://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#cross-browser-and-os-testing) I noticed the following browser support criteria:
> IE 9+ on Windows XP and up

On the other hand, I needed to temporarily remove `supported_browser` context processor to be able to test the behaviour in IE9 and IE10. So I am not sure - should I prepare fallback when the user will see "Unsupported browser" message in IE9 anyway? Or should the doc be updated? It's my first attempt to contribute to Kolibri so any guidance on browsers support will be appreciated.

#### Before

loading-spinner

#### After

kolibri-loader

#### How to test the loader

Probably not the smartest way but I was able to preview the loader in the app after commenting out [FE bundle import](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/templates/kolibri/base.html#L37)
(EDIT: I realized network throttling could be more useful for review :)

#### What to pay attention to

The animation is now smoother since I could use the full power of CSS animations. Though, I am not sure if that's OK - should I imitate the original gif more accurately or do you have any other preferences (timing adjustments..)?

### References

#4329 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by MisRob** [comment]
Hello, it's my first contribution - I went through contributor checklist but it seems I am not authorized to add a label or a reviewer so I'm leaving it like it is now. I suppose only core team members can do that or have I missed something? Thanks :)

**Comment by indirectlylit** [comment]
this is great! will review asap

**Review by khangmach — APPROVED** [review]

**Comment by jamalex** [comment]
Awesome, thanks for the contribution!!

**Comment by MisRob** [comment]
My honour. I appreciate what you've managed with Kolibri and KALite. I've been planning to check codes for a while :)

Now I can see coverage is a bit lower. I am not 100% sure since I don't know the codebase, but issues don't seem to be related. Is it all right?

(I was considering adding a test but to be honest I wasn't sure how to test the loader in base template - seems there's a lot of async stuff happening in the background. If I would want to test the template only, it seems it would require mocking Webpack hooks somehow and I am not sure if such test would be useful in this case. Or maybe some e2e test could help (though that would probably require some throttling)? I checked integration tests briefly so I am not sure if something like this would be suitable. So if you have any recommendations :)

**Comment by rtibbles** [comment]
> Now I can see coverage is a bit lower. I am not 100% sure since I don't know the codebase, but issues don't seem to be related. Is it all right?

This is fine - this is mostly related to the fact that the SVG is many more lines than the IMG tag that you replaced. We don't currently have a good mechanism for testing your change, so I wouldn't expect you to come up with a test!

**Review by rtibbles — APPROVED** [review]
Code looks good to me!

**Comment by MisRob** [comment]
OK thanks for the explanation

**Pull request merged**
