### PR TITLE
Re-enable filtering content-to-import by renderability, but faster!

### PR DESCRIPTION
**Pull request by jamalex**
### Summary

In #3563, we addressed #3497 by simply disabling "filter by renderability" completely. This PR reintroduces this as the default behavior, but approximately infinitely faster. :)

Performance tests for the old code (pre-#3563, so with "filter by renderability" still enabled) and the updated code can be found here, for 2 channels of different sizes:
https://docs.google.com/document/d/1yNo_Abd_Dz6NBtMIiQ_WXbbYl6oUC8jlx8g3e85PLuU/edit

tl;dr, performance for *all* combinations of filters is improved, including going from ∞ (forever) down to 3.5s with all filters enabled on the KA channel, and 4.5s to 180ms on the African Storybook channel. For KA, the current filtered solution also outperforms the temporary fix in #3563, which still took 47s. Even performance when not filtering at all is substantially improved.

The main thing causing performance issues in the original code was the chaining of multiple filter calls using the same related lookup. This resulted in multiple parallel joins to the same table within the generated SQL query, which grows n^2 as a function of the number of content nodes.

See: https://docs.djangoproject.com/en/1.8/topics/db/queries/#spanning-multi-valued-relationships for how such lookups are handled.

Additional gains came from doing `ContentNode.objects.filter(channel_id=channel_id)` instead of `files_to_transfer.filter(files__contentnode__in=node_ids)`.

### Reviewer guidance

Try importing content. See if you can still see the "Preparing..." step before it disappears, after selecting content for import and starting the process!

### References

Addresses #3497 more efficiently (and with fuller functionality) than the temp fix in #3563.

Benchmark reference: https://docs.google.com/document/d/1yNo_Abd_Dz6NBtMIiQ_WXbbYl6oUC8jlx8g3e85PLuU/edit

----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by jamalex** [comment]
CC @bonidjukic @jredrejo

**Comment by lyw07** [comment]
Sorry will look into this as my first thing tomorrow morning! 
I noticed that there’s an error in Travis ci, but I didn’t see it before. Will also look into this more

**Comment by rtibbles** [comment]
Docs build failure unrelated to PR.

**Comment by jamalex** [comment]
Oh, hmm, yeah -- doesn't seem to be related to the changes, and only happened in one tox env. Maybe we should just retry?

```
WARNING: autodoc: failed to import module 'kolibri.auth.test.test_api'; the following exception was raised:
No module named 'factory'
WARNING: autodoc: failed to import module 'kolibri.auth.test.test_permissions_classes'; the following exception was raised:
No module named 'mock'
Exception occurred:
  File "/home/travis/build/learningequality/kolibri/.tox/docs/lib/python3.5/site-packages/sphinx/domains/python.py", line 568, in run
    (modname, self.env.doc2path(modules[modname])),
AttributeError: 'DirectiveAdapter' object has no attribute 'env'
The full traceback has been saved in /tmp/sphinx-err-9lvbldiy.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[1]: *** [html] Error 2
make[1]: Leaving directory `/home/travis/build/learningequality/kolibri/docs'
make: *** [docs] Error 2
ERROR: InvocationError for command '/usr/bin/make docs' (exited with code 2)
```

**Comment by jamalex** [comment]
Ops, sorry, GH hadn't refreshed to show @rtibbles comments. :+1:

**Comment by jamalex** [comment]
>significantly faster

0.9.0 -> ∞ (all the seconds)
0.9.1 -> 47s (with no renderability filtering)
0.9.2 -> 3.5s (full functionality reinstated)
...
0.9.3 -> it preempts your intentions and loads content before you know you want it

**Comment by indirectlylit** [comment]
wow

**Pull request merged**
