### PR TITLE
First pass user data generation management command.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Have you ever wanted to generate a bunch of user data, but were just too tired to create all those accounts and login as all of them, then do the equivalent of the classroom engagement of 40 students over the course of months?! You were? Then this is the answer for you - with this new management command, you won't believe that it is not real data that you're looking at (until you go into the exercise detail view, when you'll realize it really isn't, because generating fake perseus question answers is just really hard).

## Screenshots (if appropriate)

image

### CODE REVIEW

**Comment by benjaoming** [comment]
So one thing that was causing issues with the KA Lite `generaterealdata` was that it wasn't maintained and wasn't documented for other devs. So think it was out for lunch for maybe a year or so? Well, I remember fixing it and after being like "hey that's really nice".

How long does it take to run it?

Could add just a simple test with `call_command`, everything is in a transaction and rolled back after..

**Comment by benjaoming** [comment]
Also, this can't be merged, it's bad luck:

image

**Comment by rtibbles** [comment]
That's from a mistranslation in Revelations - the real number of the beast is 616! https://en.wikipedia.org/wiki/Number_of_the_Beast#616

But yes, some documentation would certainly help - and can add some tests as you suggest.

**Comment by benjaoming** [comment]
Yeah, put in a simple test and mention it in the dev docs, should be good to go them IMO!

**Comment by radinamatic** [comment]
> it's bad luck:

It was 2/3ds lucky for me (born on 6/6)... :smiling_imp:

**Comment by rtibbles** [comment]
Retargeting this to 0.5.x for demo server purposes.

**Comment by jamalex** [comment]
Oh, plus, you added a test! :fireworks:

**Comment by rtibbles** [comment]
Yeah, the test was pretty helpful, because it allowed me to do a bit of refactor to clean up without worrying about breakage!

**Comment by jamalex** [comment]
> Yeah, the test was pretty helpful, because it allowed me to do a bit of refactor to clean up without worrying about breakage!

**Pull request merged**
