### PR TITLE
Assign an h5p learning activity kind

### LINKED ISSUE #8882: H5P kind has no icon & is not handled in constants.js
## Observed behavior

When viewing a coach reports here: https://github.com/learningequality/kolibri/blob/a062fc6bf358d5f3d89e09053e24310351b49e48/kolibri/plugins/coach/assets/src/views/reports/ReportsLessonResourceLearnerListPage.vue#L30-L32 

If the content kind is "h5p" then you get the error "KIcon no icon for 'h5p'" and it applies the left padding like:

image

Also - in constants.js https://github.com/learningequality/kolibri/blob/a062fc6bf358d5f3d89e09053e24310351b49e48/kolibri/core/assets/src/constants.js#L29-L43 

seems we ought to have a mapping for H5P as well? 

Perhaps moving the LearningActivityIcon logic into core is worthwhile since we display it in two plugins? Otherwise we should consider copying it over to Coach.

## Expected behavior

Every KIcon shows the correct icon.

## User-facing consequences

Misaligned text due to missing icon.

## Steps to reproduce

Have a lesson with H5P in it. Go to reports > lessons > that lesson > that H5P content. I used "Mark the Words" and "Find the Words".

### PR DESCRIPTION
**Pull request by jredrejo**
## Summary

h5p activities have not a defined icon to be shown. This PR solves it assigning a html5 icon to this content kind

The real fix should be done in kolibri-design-system to assing an icon to h5p at https://github.com/learningequality/kolibri-design-system/blob/main/lib/KIcon/iconDefinitions.js#L95

This PR also solves a problem in the Learn plugin to ensure the right icon is shown.

## References
Closes: #8882 

## Reviewer guidance
Browse the content library , and select an h5p resource, an icon should be shown 
image
image
Go to the Coach reports in a lesson with h5p content, the icon should be the same as with html5:
image
image

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
This is already implemented in the backend here: https://github.com/learningequality/kolibri/pull/8794

We should remove the frontend mapping for this, as it is redundant.

Note that the issue referenced is for the coach app, not in learn.

**Comment by jredrejo** [comment]
> This is already implemented in the backend here: #8794
> 
> We should remove the frontend mapping for this, as it is redundant.
> 

mmm, but it does not work,
image



> Note that the issue referenced is for the coach app, not in learn.

ahhh , yes I didn't see that, I saw the issue in learn and didn't notice the coach problem. I'll fix it

**Comment by rtibbles** [comment]
Have you run `kolibri.core.content.upgrade.metadata_annotation_update` since that PR was merged?

**Comment by rtibbles** [comment]
(the issue with only fixing this in the frontend, is that it means that search would not pick up H5P resources as 'explore')

**Comment by jredrejo** [comment]
> Have you run `kolibri.core.content.upgrade.metadata_annotation_update` since that PR was merged?

I hadn't because I didn't know that was needed, but  after doing this in a shell:

```
In [1]: from kolibri.core.content.upgrade import metadata_annotation_update

In [2]: metadata_annotation_update()

```
nothing changed, the icon is not visible in the learn page in the 0.15.x branch
Is there anything else to be done?

**Comment by rtibbles** [comment]
We worked out that the issue was that the frontend was not looking at the `learning_activities` attribute of the content node, so now everything makes sense!

**Comment by jredrejo** [comment]
@rtibbles everything should be fine now, both on learn and coach

**Review by rtibbles — APPROVED** [review]
Everything works as expected. Super.

**Pull request merged**
