### PR TITLE
migrate woff file from binary to LFS pointer

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

Hopefully this fixes https://github.com/learningequality/kolibri/issues/6312

I believe that somehow this `.woff` file was added as a binary instead of an LFS pointer:
https://github.com/learningequality/kolibri/blob/develop/kolibri/core/content/static/assets/h5p-standalone-dist/fonts/h5p-core-23.woff

Based on the references below, I ran the following commands:

```
> find . | grep h5p-core-23.woff
./kolibri/core/content/static/assets/h5p-standalone-dist/fonts/h5p-core-23.woff
> git lfs migrate import --no-rewrite -m "fix up git LFS issue" ./kolibri/core/content/static/assets/h5p-standalone-dist/fonts/h5p-core-23.woff
migrate: checkout: ..., done
```

Note that using `--no-rewrite` here is important because the guidance given in other threads would have rewritten history on our shared release branch.

### Reviewer guidance

does this address the issue?

### References

* https://github.com/git-lfs/git-lfs/issues/1939
* https://github.com/git-lfs/git-lfs/issues/2910
* https://github.com/git-lfs/git-lfs/pull/3029

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by nucleogenesis — APPROVED** [review]
Aside from the Travis failure this is good. Thanks Devon! Can't wait to rebase my existing work once this is merged.

**Comment by indirectlylit** [comment]
hm neither the build or the test failures seem related to my edit. Will try rebuilding

**Comment by benjaoming** [comment]
This looks like it's working! I think you just need to merge the latest `release-v0.13.x` here and it should work.

```
➜  kolibri git:(cli-help) ✗ gst
On branch cli-help
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    kolibri/core/content/static/assets/h5p-standalone-dist/fonts/h5p-core-23.woff

no changes added to commit (use "git add" and/or "git commit -a")
➜  kolibri git:(cli-help) ✗ git merge indirectlylit/woff
Merge made by the 'recursive' strategy.
 .buildkite/setup_and_upload_artifact.sh                                       |   2 +-
 build_tools/i18n/crowdin.py                                                   |   4 +---
 kolibri/core/assets/src/views/LogoutSideNavEntry.vue                          |   1 -
 kolibri/core/assets/src/views/PaginatedListContainer.vue                      |  47 ++++++++++++++++++++++++++++++++---------------
 kolibri/core/content/static/assets/h5p-standalone-dist/fonts/h5p-core-23.woff | Bin 9096 -> 129 bytes
 kolibri/plugins/device/assets/src/views/AvailableChannelsPage/index.vue       |  15 ++++++++++++++-
 kolibri/plugins/device/assets/test/views/AvailableChannelsPage.spec.js        |   8 ++++----
 kolibri/plugins/facility/assets/src/modules/classAssignMembers/handlers.js    |   4 ++--
 kolibri/plugins/facility/assets/src/views/UserCreatePage.vue                  |   3 +--
 kolibri/plugins/facility/assets/src/views/UserEditPage.vue                    |   3 +--
 kolibri/plugins/user/assets/src/views/LoginSideNavEntry.vue                   |   2 --
 kolibri/plugins/user/assets/src/views/ProfileEditPage.vue                     |   2 +-
 12 files changed, 57 insertions(+), 34 deletions(-)
➜  kolibri git:(cli-help) gst
On branch cli-help
nothing to commit, working tree clean
```

**Comment by indirectlylit** [comment]
rebased. let's see if it works...

**Pull request merged**
