### PR TITLE
Fix exercise rendering

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
More cleanup from #6969 

* Properly handle cancelling requests when disconnected
* Maintain full support for old client API
* Add deprecation warnings

### Reviewer guidance
To test the cancelling:
* set your Network status to 'offline' so that your browser is not connected to Kolibri.
* In the developer console type execute: `kolibriCoreAppGlobal.client.default({url: "http://127.0.0.1:8000/bleg"})`
* It shoudl fail because there is no network connection and the disconnection snackbar appears
* Again execute `kolibriCoreAppGlobal.client.default({url: "http://127.0.0.1:8000/bleg"})`
* The returned promise should be immediately rejected and shown as cancelled.

To test exercises:
* Load an exercise
* Make sure it renders
* See the console for deprecation warnings

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [x] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by ivanistheone** [comment]
@rtibbles I'll be sure to try this out tmrw

Since you're looking into client.js, do you think you could look into making it `KOLIBRI_URL_PATH_PREFIX`-aware to fix  https://github.com/learningequality/kolibri-exercise-perseus-plugin/issues/213#issuecomment-604748222  ?

It might not be simple since mathjax does its own loading of additional resources, but flagging in case it's simple fix.

**Comment by ivanistheone** [comment]
Tested using .pex asset and I can confirm exercises are working fine again.

1. WHEN offline, AND console `kolibriCoreAppGlobal.client.default({url: "http://127.0.0.1:8000/bleg"})` fails as expected:
Screen Shot 2020-06-12 at 6 39 14 AM


2. Again execute `kolibriCoreAppGlobal.client.default({url: "http://127.0.0.1:8000/bleg"})` is immediately rejected as expected
Screen Shot 2020-06-12 at 6 39 34 AM


3. Basic exercise testing + fancy exercise with a perseus graph widget tested and they work great, and console shows deprecation warnings "[WARN: kolibri/core/assets/src/core-app/client.js] entity is deprecated for accessing response data, please use the data key instead"
  Screen Shot 2020-06-12 at 6 51 33 AM

**Review by ivanistheone — APPROVED** [review]
Have not looked at js code, but functionality OK.

**Comment by radinamatic** [comment]
Tested asset on Windows 10, working as expected! :+1: 

Same warning 3. as Ivan observed.

**Review by radinamatic — APPROVED** [review]
Looking good again!

**Comment by rtibbles** [comment]
Have filed a follow up issue for perseus renderer to remove the deprecated calls: https://github.com/learningequality/kolibri-exercise-perseus-plugin/issues/218

But at least this means the updated Axios client is fully API compatible with the old one, so it shouldn't break external plugins.

**Pull request merged**
