### PR TITLE
attempting to merge app-support into develop

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

conflicts:

- kolibri/plugins/user/kolibri_plugin.py
- kolibri/plugins/user/assets/src/views/SignInPage/UsersList.vue added in remotes/le/app-support inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to kolibri/plugins/user/assets/src/views/UsersList.vue
- kolibri/plugins/user/assets/src/views/SignInPage.vue
- kolibri/plugins/learn/assets/src/views/LearnIndex.vue
- kolibri/plugins/device/assets/src/views/DeviceSettingsPage/index.vue
- kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/index.vue
- kolibri/deployment/default/dev_urls.py
- kolibri/core/device/models.py
- kolibri/core/auth/api.py
- kolibri/core/assets/src/views/userAccounts/PasswordTextbox.vue

### Reviewer guidance

everything check out and work?

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by nucleogenesis** [comment]
```
DeviceNotProvisioned at /en/user/
No exception message supplied
```

After starting the server with a new `KOLIBRI_HOME` I refreshed at `/en/user` and it did not redirect me to Setup Wizard as expected.

**Comment by nucleogenesis** [comment]
Not sure if it is intentional but `/app/api/initialize` no longer works even when logged in I get a 403.

**Comment by nucleogenesis** [comment]
**Bug** (Fixed)

On a multiple-facility device:

- Login as superadmin
- Facility -> [select a facility that isn't the first one on your device] -> Users
- Create a few users
- After one or two users, you'll see that you created a user for the wrong facility now after the first one or two were in the facility that you had selected.

**Review by jonboiser — APPROVED** [review]

**Comment by jredrejo** [comment]
> Not sure if it is intentional but `/app/api/initialize` no longer works even when logged in I get a 403.

@nucleogenesis 

` /app/api/initialize` has never worked, the right url is `  /app/api/initialize/<token>` 
Example:
http://localhost:8000/app/api/initialize/01f5bcbe590b45e987ae0471c002ec47

To get the token, from a kolibri shell:
```
from kolibri.core.device.models import DeviceAppKey
DeviceAppKey.get_app_key()
```

**Pull request merged**
