### PR TITLE
Get available disk space for symlinked directory

### LINKED ISSUE #4227: Free Space Report Is Wrong When Content is Symbolically Linked
### Observed behavior

> $ ls -l /opt/kolibri/
total 219344
lrwxrwxrwx  1 root    root           44 Sep  7 21:19 content -> /media/esata/MEDIA_DISK/KOLIBRI_DATA/content
-rw-r--r--  1 kolibri kolibri 220577792 Sep  9 10:15 db.sqlite3
-rw-r--r--  1 kolibri kolibri     32768 Sep  9 10:41 db.sqlite3-shm
-rw-r--r--  1 kolibri kolibri     78312 Sep  9 10:41 db.sqlite3-wal
-rw-r--r--  1 kolibri kolibri         0 Sep  7 19:06 debug.log
-rw-r--r--  1 kolibri kolibri      4096 Sep  7 19:06 job_storage.sqlite3
-rw-r--r--  1 kolibri kolibri     32768 Sep  9 10:15 job_storage.sqlite3-shm
-rw-r--r--  1 kolibri kolibri   3761592 Sep  8 12:42 job_storage.sqlite3-wal
-rw-r--r--  1 kolibri kolibri     66774 Sep  9 10:15 kolibri.log
-rw-r--r--  1 kolibri kolibri       479 Sep  7 19:06 kolibri_settings.json
drwxr-xr-x  5 kolibri kolibri      4096 Sep  7 19:06 kolibri-venv
-rw-r--r--  1 kolibri kolibri      6538 Sep  9 10:41 server.log
-rw-r--r--  1 kolibri kolibri        10 Sep  9 10:15 server.pid
drwxr-xr-x  2 kolibri kolibri      4096 Sep  9 11:01 sessions
drwxr-xr-x 25 kolibri kolibri      4096 Sep  7 19:06 static

[me@tower Raccoon]$ df -h / /media/esata/MEDIA_DISK
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3        39G   34G  2.4G  94% /
/dev/sdb2       1.8T  1.6T  140G  92% /media/esata/MEDIA_DISK

Note the symlinked location has 140G available but Kolibri front end reports "Your remaining space: 2 GB" 
…

### Expected behavior
Correct free space should be reported.

…

### User-facing consequences
Cannot install content.

…

### Errors and logs

Vivaldi browser 

1.15.1147.42 (Stable channel) (64-bit)
--

Kolibri version | 0.10.2
-- | --
http://192.168.1.100:8087/
/opt/kolibri/db.sqlite3
tower
Linux-4.14.65-1-MANJARO-x86_64-with-arch-Manjaro-Linux
2 GB

[kolibri.log.txt](https://github.com/learningequality/kolibri/files/2363937/kolibri.log.txt)
[server.log.txt](https://github.com/learningequality/kolibri/files/2363938/server.log.txt)

### PR DESCRIPTION
**Pull request by lyw07**
### Summary

This PR is to fix #4227 as the user requested, in the case that the content directory is symbolically linked to another location.

### Reviewer guidance

1. Plug in a USB
2. create a folder `content` inside the USB folder
3. Run kolibri 0.11-beta1 (or other versions, as long as it's not installers from this PR), and then stop the server (this is to get the kolibri home directory created. If ~/.kolibri has existed, please skip this step)
4. run `ln -s <usb_directory>/content ~/.kolibri`. After that, run `ls -l ~/.kolibri/content` to see if a symbolic link is created correctly. The result of the command should look something like this:
```
lingyiwang$ ls -l ~/.kolibri/content
lrwxr-xr-x  1 lingyiwang  staff  30 Oct 16 16:45 /Users/lingyiwang/.kolibri/content -> /Volumes/NO NAME/KOLIBRI_DATA/
```
5. Run kolibri 0.11-beta1 again. Go to channel import page to see the available disk space. 
It should look like this:
image
After getting the value of the available disk space, stop the kolibri server.
6. Run kolibri installer from this PR. Go to channel import page to see the available disk space.
The available disk space should be changed. Instead of showing the available disk space of your device, it should show the available space of the USB.
For example:
image

### References

#4227 

----

### Contributor Checklist

- [X] Contributor has fully tested the PR manually
- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by lyw07** [comment]
@mrpau-dev If you have some available time, could you also test this PR? It's similar to https://github.com/learningequality/kolibri/pull/4332. Sorry I should have included the code in the previous PR, but I didn't realize until now. Thank you so much!

**Comment by mrpau-richard** [comment]
@lyw07 I tested this on Ubuntu 16.04 the `content` symlink to external drive worked correctly.
This is my device drive space with the `kolibri-0.11.0` version.
screen shot 2018-10-17 at 7 06 03 pm
After I installed the `.deb` installer from this PR, My `Drive space` became 76GB available.
screen shot 2018-10-17 at 7 07 39 pm


One thing that I noticed that the given `Drive space` is not the same as in the directory folder details.
screen shot 2018-10-17 at 7 23 01 pm

**Comment by mrpau-julius** [comment]
I tested this PR in Xubuntu 17.04 32 bit. It is working. 👍

**Comment by lyw07** [comment]
thank you so much for testing!! @mrpau-richard @mrpau-julius I really appreciate your help.

For the difference of free space that Richard mentioned, I think it might be related to how we convert bytes to gigabytes.

**Comment by indirectlylit** [comment]
> I think it might be related to how we convert bytes to gigabytes.

Any chance we're using base 2 instead of base 10? (see #4272)

**Comment by benjaoming** [comment]
Hurray @lyw07 ! :tada: 

Would you mind doing a codebase scan for something like `os.path` just to see if you can identify other areas where issues might occur from not resolving the "real path" of a filesystem resource?

`ag --py os.path` could be your friend :)

**Comment by lyw07** [comment]
Hi @benjaoming 

thanks! I feel that this could worth a separate issue so I created #4462 for it (through the cool github feature you mentioned on slack 🎉)

**Review by benjaoming — APPROVED** [review]
:+1: This is the correct place to resolve the path (at the point where it's critical to have the real device for measuring disk space). I have no comments - great work and thanks for testing @mrpau-julius !

**Pull request merged**
