### PR TITLE
Refactor coach reports corebase

### LINKED ISSUE #9231: Remove CoreBase from Coach reports
The `kolibri/plugins/coach/assets/src/views/reports` section of the Coach plugin has many pages in it. This shouldn't require too extensive of work to do.

Coach does not make use of the `immersivePageProps` pattern employed previously in other parts of the app, so each of the `*Page` components, ideally, can implement `AppBarCorePage` or `ImmersivePage` directly or by creating a wrapper component for either of them where necessary.

This will only focus on the Report pages, another issue will deal with the rest of coach.

### PR DESCRIPTION
**Pull request by akolson**
## Summary

This pr refactors Coach plugin reports, removing all usages of `CoreBase`

## References

Closes #9231  

## Reviewer guidance

- Navigate through the coach module reporting, ensuring that pages function as before
----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by nucleogenesis — APPROVED** [review]
Generally code review looks good to me. Whenever #9863 passes QA and is merged you can rebase this PR on develop and then we can get some QA on the reports side of things.

**Comment by akolson** [comment]
Based on @nucleogenesis's comment, tagging @radinamatic @pcenov to take a look at this as well.

**Comment by pcenov** [comment]
@radinamatic No issues observed, the pages in the Coach module are functioning correctly as before.

**Review by radinamatic — APPROVED** [review]
Manual QA by @pcenov passed, good to go! 💯 :shipit:

**Pull request merged**
