### PR TITLE
0.10.x into develop

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
Merge!
Conflicts:
*	kolibri/__init__.py
*	kolibri/core/assets/src/api-resources/contentNode.js
*	kolibri/core/assets/src/api-resources/contentNodeSlim.js
*	kolibri/core/assets/src/api-resources/index.js
*	kolibri/core/assets/src/state/mappers.js
*	kolibri/core/assets/src/views/ContentRenderer/index.vue
*	kolibri/core/content/api.py
*	kolibri/core/content/test/test_channel_import.py
*	kolibri/core/content/test/test_import_export.py
*	kolibri/core/logger/api.py
*	kolibri/core/logger/permissions.py
*	kolibri/core/logger/serializers.py
*	kolibri/core/logger/test/test_api.py
*	kolibri/plugins/coach/assets/src/state/actions/exam.js [DELETED]
*	kolibri/plugins/coach/assets/src/state/store.js [DELETED]
*	kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/TopicRow.vue
*	kolibri/plugins/coach/assets/src/views/exams/CreateExamPage/index.vue
*	kolibri/plugins/learn/assets/src/state/actions/main.js [DELETED]
*	kolibri/plugins/learn/assets/src/state/actions/recommended.js [DELETED]
*	kolibri/plugins/learn/assets/src/state/mutations/index.js [DELETED]
*	kolibri/utils/cli.py
*	requirements/base.txt

### Reviewer guidance
Does it all still work?

----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by rtibbles** [comment]
Poked around the app and didn't see any errors.

**Comment by lyw07** [comment]
It looks like many mocks in the tests need to change from `kolibri.x` to `kolibri.core.x`

**Comment by rtibbles** [comment]
Bah, thought I'd caught them all, will take a look.

**Comment by lyw07** [comment]
Running `kolibri start` causes this error:
```
Traceback (most recent call last):
  File "/Users/lingyiwang/.venvs/kolibritest/bin/kolibri", line 11, in <module>
    sys.exit(main())
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/utils/cli.py", line 660, in main
    start(port, daemon=daemon)
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/utils/cli.py", line 309, in start
    server.start(port=port)
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/utils/server.py", line 91, in start
    run_server(port=port)
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/utils/server.py", line 149, in run_server
    from kolibri.deployment.default.wsgi import application
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/deployment/default/wsgi.py", line 15, in <module>
    application = get_wsgi_application()
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/dist/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/dist/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/dist/django/core/handlers/base.py", line 80, in load_middleware
    middleware = import_string(middleware_path)
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/dist/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/plugins/setup_wizard/middleware.py", line 15, in <module>
    SETUP_WIZARD_URL = reverse("kolibri:setupwizardplugin:setupwizard")
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/dist/django/urls/base.py", line 60, in reverse
    app_list = resolver.app_dict[ns]
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/dist/django/urls/resolvers.py", line 350, in app_dict
    self._populate()
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/dist/django/urls/resolvers.py", line 290, in _populate
    for pattern in reversed(self.url_patterns):
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/dist/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/dist/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/dist/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/dist/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/deployment/default/urls.py", line 76, in <module>
    url(r'^docs/', include_docs_urls(title='Kolibri API', generator_class=Generator))
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/dist/rest_framework/documentation.py", line 68, in include_docs_urls
    permission_classes=permission_classes,
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/dist/rest_framework/documentation.py", line 29, in get_docs_view
    permission_classes=permission_classes,
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/dist/rest_framework/schemas/__init__.py", line 41, in get_schema_view
    urlconf=urlconf, patterns=patterns,
  File "/Users/lingyiwang/.venvs/kolibritest/lib/python2.7/site-packages/kolibri/dist/rest_framework/schemas/generators.py", line 262, in __init__
    assert coreapi, '`coreapi` must be installed for schema support.'
AssertionError: `coreapi` must be installed for schema support.
```

**Review by benjaoming — APPROVED** [review]
I see no issues here - nice merge work Mr Tibbles!

**Comment by rtibbles** [comment]
Hrm, it shouldn't be using the coreapi module unless it's running in debug mode.

**Comment by benjaoming** [comment]
@lyw07 nice catch - wondering if this is actually caused by Github not running tests, because it has the latest commit already flagged.

@rtibbles you could perhaps force a rebuild this way:

```
git commit --amend
git push -f
```

**Comment by lyw07** [comment]
Yes, I'm running with the `--debug` option. Is there anything I need to do to make it work in `debug` mode? Running without `--debug` option looks great.

**Comment by rtibbles** [comment]
So this is an issue with develop, not this PR. Will merge here and fix elsewhere. Can you open an issue for this @lyw07?

**Comment by lyw07** [comment]
sure! I will create an issue for this.

**Pull request merged**
