### PR TITLE
Fix error with null nav items.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Fixes a previously unreported error that would occur when being on the library page while not logged in.

## Reviewer guidance
This stops the error, but I am not completely sure it's the correct fix. Verify that this fixes both the non-logged in and the logged in case.

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by marcellamaki — COMMENTED** [review]
I recently saw this and forgot to open an issue - thanks for fixing it. 

I think the fix makes sense, and it fixes the console error. One thing I noticed is that with the fix, the overflow and bookmarks option pops up, on all screen sizes and even when not logged in.


Screen Shot 2022-12-09 at 11 27 53 AM

I think it's a bit out of scope - probably something else brittle or without the proper checks that I did, that is now popping up due to this check. I can open a follow up issue for that (unless you would like to include it here)

**Comment by rtibbles** [comment]
I'll update this here, yup!

**Comment by rtibbles** [comment]
On mobile, logged in:
image

**Comment by rtibbles** [comment]
On mobile logged out:
image

**Review by marcellamaki — APPROVED** [review]
LGTM! Thanks for the refactor

**Pull request merged**
