### PR TITLE
Adds tooltips to progress icons

### PR DESCRIPTION
**Pull request by christianmemije**
## Summary

* Adds tooltips to progress icons by making use of the `ui-tooltip`
* Addresses #1448 
tooltip

### CODE REVIEW

**Comment by rtibbles** [comment]
How does the KeenUI Tooltip interact with screen readers, btw? Does it have accessibility built in?

**Comment by christianmemije** [comment]
It makes use of [https://github.com/HubSpot/tooltip](https://github.com/HubSpot/tooltip) They [added ARIA attributes](https://github.com/HubSpot/tooltip/pull/51) but I cannot seem to find the attributes within the actual markup.

**Comment by DXCanas** [comment]
@JosephusPaye

**Comment by JosephusPaye** [comment]
Hi,

It seems like `tether-tooltip` doesn't add the ARIA attributes when using an existing element as the tooltip content, so Keen UI currently doesn't have the necessary attributes.

I have just added it here: https://github.com/JosephusPaye/Keen-UI/commit/1cda1c45233daa5e581df1565482aaf746e80464 and it will be part of the next version.

**Pull request merged**
