### PR TITLE
Update windows installer version to 1.5.0

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
Brings up latest changes from Windows installer

## Reviewer guidance
Unblock windows installer. Make sure it works.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
Still the same issue as described in https://github.com/learningequality/kolibri/pull/8895#issuecomment-996405310 😞 

New recordings:

install upgrade | after upgrade | after restart
--- | --- | ---
windows-install-2 | windows-0 15-reports-2 | windows-0 15-reports-after-restart-2

New 
[DB-and-logs.zip](https://github.com/learningequality/kolibri/files/7738302/DB-and-logs.zip)

**Comment by radinamatic** [comment]
My bad, this PR wasn't supposed to fix the resources in reports, but it successfully upgraded Kolibri from 0.14.7! 🎉

**Review by radinamatic — APPROVED** [review]
:shipit: 👏🏽

**Comment by rtibbles** [comment]
@radinamatic confirmed that the `KOLIBRI_INSTALLATION_TYPE` env var is now set from within `kolibri shell` so this seems to be working.

**Pull request merged**
