### PR TITLE
Unnecessary kolibri store in tests

### LINKED ISSUE #11725: Remove unnecessary use of the core Kolibri store in tests
When custom theming was first introduced to Kolibri, the theming state was made reactive by adding it to the core Vuex state.

This necessitated many component oriented frontend tests to inject the store into their tests in order to have the Vuex state available and prevent errors.

Since this happened, the reactive theming state has been extracted from Vuex and now lives independently. Therefore, injecting the store into these component tests is no longer needed.

```[tasklist]
### Acceptance Criteria
- [ ] Find all instances of `kolibri.coreVue.vuex.store` imports in Javascript test files
- [ ] In cases where the store is just injected as is into the component, and nothing in the component relies on any vuex state, remove the import and the injection, and ensure the test still passes.
```

For a starting point, many of the affected spec files were originally edited in this commit: https://github.com/learningequality/kolibri/pull/4587/commits/69856a15e321b0c977b29fc0474703d2521bdb13 but there may be others, or those files may have moved since!

### PR DESCRIPTION
**Pull request by nick2432**
## Summary
This PR addresses issue #11725 by removing unnecessary uses of the core Kolibri store in JavaScript test files. With the introduction of custom theming, the theming state was initially added to the core Vuex state. However, the reactive theming state has been extracted from Vuex and now lives independently. Consequently, injecting the store into component tests is no longer needed.

## References
fixes https://github.com/learningequality/kolibri/issues/11725

### CODE REVIEW

**Comment by rtibbles** [comment]
Excellent - this definitely removes some unnecessary references!

The main question now is just confirming there are no other places that we could do this cleanup. I will take a quick glance through your PR code checked out locally to double check!

**Comment by rtibbles** [comment]
From a quick grep, I suspect there may be more instances we could tidy up here.

I searched for `kolibri.coreVue.vuex.store` in files named `*.spec.js` and looked at the Git blame for the import, and more than one tracked back to https://github.com/learningequality/kolibri/pull/4587 - could you confirm that you have checked all instances here?

**Comment by nick2432** [comment]
@rtibbles i have made some changes

**Review by rtibbles — APPROVED** [review]

**Comment by rtibbles** [comment]
Excellent, this seems to have much wider coverage!

**Pull request merged**
