### PR TITLE
remove build.txt line in docs

### PR DESCRIPTION
**Pull request by zrg228**
## Summary
Fixes the problem in issue #10502 based on the comments there and a similar problem referenced on #10489

### CODE REVIEW

**Review by rtibbles — CHANGES_REQUESTED** [review]
This is the right change, but you seem to have added a binary file to your commit. Could you amend your commit to exclude the python.exe file and force push to remove it from the history?

**Comment by zrg228** [comment]
> This is the right change, but you seem to have added a binary file to your commit. Could you amend your commit to exclude the python.exe file and force push to remove it from the history?

sure my bad let me fix that

**Comment by zrg228** [comment]
Ok, I believe the problem should be fixed now

**Review by rtibbles — APPROVED** [review]

**Comment by rtibbles** [comment]
Thanks @zrg228 - if you haven't already, please feel free to add your name and github username to the AUTHORS.md in a follow-up PR !

**Pull request merged**
