### PR TITLE
Added function handler to delay SaveAnswer function

### LINKED ISSUE #9444: Coach>Reports>Quiz score - Incorrect number of attempts
## Observed behavior
I see an incorrect number of attempts at 'Coach>Reports>Quiz score' whenever there's a numeric value input as the answer to a quiz question.
For example if the answer is '12' I will see one failed attempt for the first entered digit '1' and one successful attempt for '12'

## Steps to reproduce the issue
1. Install Kolibri 0.15.2
2. Import [Khan Academy's](https://www.khanacademy.org/math/cc-third-grade-math/represent-and-interpret-data/imp-picture-graphs/e/reading_pictographs_2) (English - US curriculum) > Math by grade > 3rd grade > Represent and interpret data > Picture graphs 
3. Create a quiz for 'Read picture graphs (multi-step problems)'
4. Complete the quiz and as a Coach go to Coach>Reports>Quiz score

## Expected result
Correctly displayed number of attempts.

## Usage Details
Ubuntu 20 - Chrome, Firefox

### PR DESCRIPTION
**Pull request by LianaHarris360**
## Summary

This PR adds a debounce function handler for the saveAnswer method, which previously saved incomplete inputs and showed multiple inputs on a completed quiz when the user intended to have one single answer.

## References

Fixes #9444 

## Reviewer guidance

Note: *Multiple answers might still be recorded if a user takes more than a second to input the complete answer.*
1. On Kolibri 0.15.2, import Khan Academy's (English - US curriculum) > Math by grade > 3rd grade > Represent and interpret data > Picture graphs
2. Create a quiz for 'Read picture graphs (multi-step problems)'
3. Complete the quiz 
4. As a Coach go to Coach>Reports>Quiz score

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by marcellamaki — APPROVED** [review]
Looks good to me! Working as expected. (If we get further feedback on this, we can adjust the debounce time as needed, but the implementation is great!) Nice work @LianaHarris360 🎉

**Comment by pcenov** [comment]
Hi @LianaHarris360, it seems that the issue with the incorrect number of attempts has been fixed however there is something strange going on as a result of which some of my correct answers are not being marked as correct.
Please have a look at the following video where on question 9 the 0 from my answer gets deleted by itself, and also my answer to question 10 is not counted at all:

https://user-images.githubusercontent.com/79847249/193800516-746c88b8-7dcc-4127-b61a-2e6548fc0394.mp4

Screenshot with the results:


I tried completing this quiz with 3 users always using the correct answers and never got a 100% score. Note that the issue is not limited to the numeric fields only as some of the multi-select questions were also marked as incomplete.

**Comment by LianaHarris360** [comment]
Thank you for letting me know @pcenov! I will look into this and see where the problem is occurring.

**Comment by rtibbles** [comment]
Hrm, this might have been why there was no debounce in the first place - to prevent this from happening.

One possibility @LianaHarris360 is that the new `debouncedSaveAnswer` is never getting flushed at any point, so that might be where we are losing responses.

If you can replicate the issue, but can't resolve it, it's OK to revert the change here instead, and we'll come up with another idea for the multiple attempt issue!

**Comment by LianaHarris360** [comment]
I thought about something like that as well. I will investigate a bit and update you if I cannot resolve it @rtibbles.

**Comment by LianaHarris360** [comment]
I was able to replicate the issue @rtibbles. After typing in an answer, the response is lost when a user clicks the next button before the `saveAnswer` function is called. Setting the leading flag on the debounced function causes the first character to be submitted as attempt 1.

**Comment by rtibbles** [comment]
So, with that in mind, I think making sure we flush our new debounced function when we move to the next question may be needed.

So this line: https://github.com/LianaHarris360/kolibri/blob/ee9f2f2f266b0bf5688c44535d061ff96b34bcb2/kolibri/plugins/learn/assets/src/views/ExamPage/index.vue#L393

Would become something like:
```
const saveAnswerPromise = this.debouncedSaveAnswer.flush() || Promise.resolve();
const promise = saveAnswerPromise.then(() => this.debouncedSetAndSaveCurrentExamAttemptLog.flush() || Promise.resolve());
```

So we make sure to flush the `debouncedSaveAnswer` then flush the `debouncedSetAndSaveCurrentExamAttemptLog`.

**Comment by LianaHarris360** [comment]
Yep, that fixed the problem for me. I will update this pr with those changes!

**Comment by rtibbles** [comment]
Great, glad that there was a solution here that kept the original fix too!

**Pull request merged**
