### PR TITLE
Replace KResponseWindow with useKResponseWindow in User Profile plugin

### LINKED ISSUE #11333: Replace KResponsiveWindow mixin by useKResponsiveWindow composable - User Profile plugin
This is one of the issues whose common goal is to gradually replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable.

First, see https://github.com/learningequality/kolibri/issues/11321 for detailed instructions and acceptance criteria common to all issues.

Then, replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable in all .vue files of **the User Profile plugin (kolibri/plugins/user_profile)**

### PR DESCRIPTION
**Pull request by thesujai**
## Summary

For testing:

1. First Identified where ResponsiveWindow elements are are used
2. Then play with CSS class of components that will be used when `windowBreakpoint` is reached.
3. Then verify that the CSS tweaks is consistent with both `KResponsiveWindow` and `useKResponsiveWindow`
4. Roll back the CSS tweaks made while testing

**Page Affected:**

- en/profile/#/     (Though this page only imported `KResponsiveWindow` and not used)

…

## References

Fixes #11333 

…

## Reviewer guidance

Would it be possible to add a `hacktoberfest-accepted` label in this PR?
Here is the link: https://hacktoberfest.com/participation/#maintainers
Its fine if for some reasons you aren't able to do so:)
…

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by thesujai** [comment]
Hey @akolson @AllanOXDi, i am not sure in which page is the component `user_profile/assets/src/views/ChangeFacility/MergeFacility.vue` is referenced. Please let me know so that I can confirm visual test from my side.

**Review by akolson — APPROVED** [review]
Changes look correct to me! Also, no regressions observed. cc @radinamatic @pcenov

**Comment by radinamatic** [comment]
@akolson Would it be possible to have more detailed reviewer guidance with verification steps for manual QA? Thank you!

**Comment by rtibbles** [comment]
The only page that seems to be affected for manual QA here is checking that the Merge Facility workflow renders correctly (and without errors), especially on a small browser window.

No need to test the full workflow, just pressing the 'join facility button' and ensuring nothing errors, and that it looks OK on a small browser window.

**Comment by akolson** [comment]
Thanks @rtibbles. Yes that should be sufficient.

**Comment by akolson** [comment]
@thesujai to Merge facility, follow the steps below;

1. Set up your device as "On my own"
2. Once set up is complete, create a new `admin` user
3. Logout of the `superuser` account and login with the `admin` user you just created.
4. Go to `http://localhost:8000/en/profile/#/`
5. Click on the `Change` button, and this will take you through the self-guided process to change and a merge facility. Please note that you will need set up another device on your local and add the device during the setup as you unfortunately have no access to Zero tier.

**Comment by MisRob** [comment]
@akolson I think @rtibbles's guidance was meant for QA team rather than @thesujai?

By the way, @thesujai, if you ever needed to set up the other device, there's a guide for it https://kolibri-dev.readthedocs.io/en/develop/howtos/another_kolibri_instance.html. I think that here, it's fine to leave it for our QA or reviewers to test it out.

**Review by pcenov — APPROVED** [review]
No issues observed while manually testing, good to go!

**Comment by thesujai** [comment]
@akolson @MisRob Okay thank you

**Comment by akolson** [comment]
Hi @MisRob. I think @thesujai requested for some visual testing guidance too; I guess he wanted to carry out some visual tests on his end.

> Hey @akolson @AllanOXDi, i am not sure in which page is the component user_profile/assets/src/views/ChangeFacility/MergeFacility.vue is referenced. Please let me know so that I can confirm visual test from my side.

**Comment by MisRob** [comment]
@akolson Ah okay, thank you. I just wanted to clarify that even though it's welcome, it's not a blocker as QA folks will be too jumping in.

**Comment by MisRob** [comment]
There's a problem with tests though

**Comment by rtibbles** [comment]
The issue is the `window.matchMedia is not a function` error, it seems - so rebasing this onto latest develop should resolve the test issue (unless I missed other errors in the tests).

**Pull request merged**
