### PR TITLE
Fix changelog for display on dev docs

### PR DESCRIPTION
**Pull request by radinamatic**
## Summary
Fixes the `CHANGELOG.md` formatting error that was causing [full list of 0.15 PRs to appear in the dev docs table of content](https://github.com/learningequality/kolibri/pull/8976#issuecomment-1010311294).

## References
…

## Reviewer guidance
…

----

## Testing checklist

- [X] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
Most of these changes are just duplicating changes in the release-v0.15.x branch. Can you make any additional edits there, and then we can just merge up to develop to fix the docs?

**Review by nucleogenesis — APPROVED** [review]
Awesome thank you!

**Comment by nucleogenesis** [comment]
Ah - I resolved the conflict in the GH UI before seeing Richard's comment. Perhaps rebasing the PR on release-v0.15.x then pushing again - and merging to 0.15.x  - would be the right way forward?

**Comment by radinamatic** [comment]
Thank you both, but the most recent `0.15-to-develop` merge apparently took care of this, and the dev docs now look OK 🙂 

Closing the PR as not necessary! 💥

**Pull request closed without merging**
