### PR TITLE
Replace "x of y" selected messages with "all/some" selected messages in channel content viewer

### LINKED ISSUE #6218: Route with name 'RESOURCE_USER_SUMMARY' does not exist
### Observed behavior

observed in console

```
[vue-router] Route with name 'RESOURCE_USER_SUMMARY' does not exist
```

### Expected behavior

no errors

### User-facing consequences

not apparent but may be indicative of something broken

### Steps to reproduce

I don't have precise steps yet, but these occurred while adding items to a lesson, clicking 'manage resources', and using browser back/forward.

### Context

0.13.0 beta 3

### LINKED ISSUE #6349: remove resource counts in content import tree view
# Observed behavior

For performance reasons, we cannot calculate precise counts. This leads to inconsistencies, where the counts don't add up to the total reported. For example:

image

### Expected behavior

Rather than reporting precise counts, we should use these more nebulous strings:

https://github.com/learningequality/kolibri/blob/ae47e83cc8f9c2a31d95f5915bb2e8edaed3cd3e/kolibri/plugins/device/assets/src/views/SelectContentPage/treeViewUtils.js#L16-L19

### User-facing consequences

confusion about what's actually selected and on the device

### Steps to reproduce

import content

### Context

0.13.0 beta 7

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

1. Replaces the sometimes inaccurate "x of y selected" and "x of x selected" message from the ContentTreeViewer component with the more general "some resources selected" and "All resources selected"
1. Fixes some bugs in the annotation code that drives the checkboxes on this UI
1. Removes code relating to a non-existent 'RESOURCE_USER_SUMMARY' route fixes #6218

Example when importing more: 

Screen Shot 2019-12-17 at 2 56 47 PM

Example when exporting/deleting

Screen Shot 2019-12-17 at 2 56 22 PM

### Reviewer guidance

1. If you see another edge case with the checkboxes when (un)selecting resources, try to write down the exact sequence so it can be fixed

### References

Fixes #6349 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
After seeing this, I'm realizing that the text on the right becomes redundant with the checkbox indicator. In a future release, maybe we should consider getting rid of it entirely

**Review by indirectlylit — APPROVED** [review]
this works for me

**Comment by lyw07** [comment]
Is this ready to be merged? Thank you!

**Comment by jonboiser** [comment]
Should be good to go!

**Pull request merged**
