### PR TITLE
Consistently use cache key as int (big int in db)

### PR DESCRIPTION
**Pull request by benjaoming**
### Summary

There's an inconsistency between the cache key's data type, being a floating point in the Django cache backend representation but saved as an integer.

I have found no theoretical path that actually leads to a bug. So for now, this is just mere speculation.

### References

N/A

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [x] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
failures related to `makemigrations --check`:

```
Migrations for 'device':
  kolibri/core/device/migrations/0007_auto_20200320_1918.py
    - Alter field key on contentcachekey
Traceback (most recent call last):
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/bin/kolibri", line 11, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/build/learningequality/kolibri/kolibri/utils/cli.py", line 243, in invoke
    return super(KolibriDjangoCommand, self).invoke(ctx)
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/travis/build/learningequality/kolibri/kolibri/utils/cli.py", line 641, in manage
    execute_from_command_line(["kolibri manage"] + ctx.args)
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/django/core/management/commands/makemigrations.py", line 193, in handle
    self.write_migration_files(changes)
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/django/core/management/commands/makemigrations.py", line 231, in write_migration_files
    migration_string = writer.as_string()
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/django/db/migrations/writer.py", line 163, in as_string
    operation_string, operation_imports = OperationWriter(operation).serialize()
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/django/db/migrations/writer.py", line 120, in serialize
    _write(arg_name, arg_value)
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/django/db/migrations/writer.py", line 84, in _write
    arg_string, arg_imports = MigrationWriter.serialize(_arg_value)
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/django/db/migrations/writer.py", line 293, in serialize
    return serializer_factory(value).serialize()
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/django/db/migrations/serializer.py", line 229, in serialize
    return self.serialize_deconstructed(path, args, kwargs)
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/django/db/migrations/serializer.py", line 101, in serialize_deconstructed
    arg_string, arg_imports = serializer_factory(arg).serialize()
  File "/home/travis/build/learningequality/kolibri/.tox/py3.7/lib/python3.7/site-packages/django/db/migrations/serializer.py", line 164, in serialize
    raise ValueError("Cannot serialize function: lambda")
ValueError: Cannot serialize function: lambda
```

**Comment by benjaoming** [comment]
Re-targeted to develop and added missing migration. I would have preferred the lambda expression, but it seems that the migration framework a) does not support lambdas and b) errs out on a function with a `__` prefix, so couldn't call it `__generate_content_cache_key`. :man_shrugging:

**Comment by indirectlylit** [comment]
This is now failing postgres tests.

Recommend closing the PR and just opening a new issue to track the inconsistency so we don't spend more time on it now

**Comment by benjaoming** [comment]
The issue is that a content cache key is already being generated in device migration 0003 -- where it hits an integer overflow in Postgres.

Sure, will close it.

```
.tox/postgres/lib/python3.5/site-packages/django/core/management/commands/migrate.py:204: in handle
    fake_initial=fake_initial,
.tox/postgres/lib/python3.5/site-packages/django/db/migrations/executor.py:115: in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
.tox/postgres/lib/python3.5/site-packages/django/db/migrations/executor.py:145: in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
.tox/postgres/lib/python3.5/site-packages/django/db/migrations/executor.py:244: in apply_migration
    state = migration.apply(state, schema_editor)
.tox/postgres/lib/python3.5/site-packages/django/db/migrations/migration.py:129: in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
.tox/postgres/lib/python3.5/site-packages/django/db/migrations/operations/special.py:193: in database_forwards
    self.code(from_state.apps, schema_editor)
kolibri/core/device/migrations/0003_contentcachekey.py:14: in create_content_cache_key
    ContentCacheKey.update_cache_key()
```

**Pull request closed without merging**
