### PR TITLE
Main-nav :focus styling

### PR DESCRIPTION
**Pull request by whitzhu**
**Chrome**
screen shot 2016-08-08 at 11 16 06 am
screen shot 2016-08-08 at 11 16 10 am

**Firefox**
screen shot 2016-08-08 at 11 18 34 am
screen shot 2016-08-08 at 11 18 40 am

## Summary

*Short description*

MVP: When user focus on button, the background-color changes.

For next iteration(after MVP), we can try to do border-right 4px purple as the new focus styling. 
## TODO

- [ ] Have tests been written for the new code?
- [ ] Has documentation been written/updated?
- [ ] New dependencies (if any) added to requirements file
- [ ] Add an entry to CHANGELOG.rst
- [ ] Add yourself it AUTHORS.rst if you don't appear there

## Reviewer guidance

*If you PR has a significant size, give the reviewer some helpful remarks*

## Issues addressed

List the issues solved or partly solved by the PR

## Documentation

If the PR has documentation, link the file here (either .rst in your repo or if built on Read The Docs)

## Screenshots (if appropriate)

They're nice. :)

### CODE REVIEW

**Comment by radinamatic** [comment]
@whitzhu: Can you post screenshot from both FF & Chrome? Thanks!

**Comment by whitzhu** [comment]
@radinamatic Just added screenshots from firefox as well

**Comment by radinamatic** [comment]
Looking really good, @whitzhu!

Would the same style work on content cards when they are in focus? Card grid items are links, right? @indirectlylit

**Comment by whitzhu** [comment]
@radinamatic The same style should work on content cards and topic cards, I'll work on that in a separate PR

**Pull request merged**
