### PR TITLE
Make pre-commit happier

### PR DESCRIPTION
**Pull request by indirectlylit**
Made these changes based on output from running:

```bash
pre-commit run --all-files
```

Original output:

```bash
Trim Trailing Whitespace..........................................................................Failed
hookid: trailing-whitespace

Files were modified by this hook. Additional output:

Fixing .pre-commit-config.yaml

Flake8............................................................................................Failed
hookid: flake8

setup.py:3:1: F401 'sys' imported but unused
setup.py:6:1: F401 'TestCommand' imported but unused
docs/conf.py:35:1: E402 module level import not at top of file
docs/conf.py:36:1: E402 module level import not at top of file
docs/conf.py:209:1: E122 continuation line missing indentation or outdented
docs/conf.py:210:1: E122 continuation line missing indentation or outdented
docs/conf.py:212:1: E122 continuation line missing indentation or outdented
docs/conf.py:213:1: E122 continuation line missing indentation or outdented
docs/conf.py:215:1: E122 continuation line missing indentation or outdented
docs/conf.py:216:1: E122 continuation line missing indentation or outdented
docs/conf.py:222:3: E121 continuation line under-indented for hanging indent
docs/conf.py:266:3: E121 continuation line under-indented for hanging indent
test/test_cli.py:17:1: E402 module level import not at top of file

Check Yaml........................................................................................Passed
Check for added large files.......................................................................Passed
Debug Statements (Python).........................................................................Passed
Fix End of Files..................................................................................Failed
hookid: end-of-file-fixer

Files were modified by this hook. Additional output:

Fixing requirements/dev.txt

Sort python imports...............................................................................Passed
```

new output:

```bash
Trim Trailing Whitespace..........................................................................Passed
Flake8............................................................................................Passed
Check Yaml........................................................................................Passed
Check for added large files.......................................................................Passed
Debug Statements (Python).........................................................................Passed
Fix End of Files..................................................................................Passed
Sort python imports...............................................................................Passed
```

### CODE REVIEW

**Comment by benjaoming** [comment]
I already have docs/conf.py fixed and functional in mine -- how it broke, I don't know.

**Comment by indirectlylit** [comment]
I didn't fix `conf.py` – just ignored it because it looked auto-generated. Is it actually a file that we maintain?

**Comment by MCGallaspy** [comment]
@indirectlylit it is a file we maintain, although it was auto-generated initially. But yeah, I don't care personally if we exclude it from linting, it's pretty low-stakes.

**Comment by indirectlylit** [comment]
okay if we maintain it, I don't want to exclude it. I'll remove that line

**Comment by indirectlylit** [comment]
okay, updated PR. @benjaoming some whitespace changes to `conf.py` may need to be merged with your branch.

**Pull request merged**
