### PR TITLE
Update windows installer to v1.3.1

### PR DESCRIPTION
**Pull request by cpauya**
### Summary

**NOTE:** Contains important fixes to include Python installers when building the Windows installer via BuildKite.

This is to test features and/or fixes for [milestone v1.3.1](https://github.com/learningequality/kolibri-installer-windows/milestone/7) in the released [`v1.3.1-alpha1`](https://github.com/learningequality/kolibri-installer-windows/releases/tag/v1.3.1-alpha1).

Look-up the BuildKite assets below if there are no errors raised during build. Look for the installer .exe/.msi to use for testing the Kolibri Windows installer.

The `docker/env.list/KOLIBRI_WINDOWS_INSTALLER_VERSION` env var value will eventually be set to the (soon-to-be-released) `v1.3.1` value once testing is verified.

### Reviewer guidance

**Merge only when all of these are checked!**

- [x] Code changes at the released [v1.3.1-alpha2](https://github.com/learningequality/kolibri-installer-windows/releases/tag/v1.3.1-alpha2) are tested
- [x] The `env.list/KOLIBRI_WINDOWS_INSTALLER_VERSION=v1.3.1` is already used and tested

/CC: @mrpau-julius @mrpau-richard @radinamatic 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
thanks - adding 0.12.6 milestone

**Comment by radinamatic** [comment]
Tested thoroughly on both Windows 7 & 10:

- fresh install
- upgrade from 0.9.2
- uninstall [kolibri-uninstall.log](https://github.com/learningequality/kolibri/files/3415667/kolibri-uninstall.log)
- restart after the port change

Let's fix the https://github.com/learningequality/kolibri-installer-windows/issues/119, and this should be good to merge!

**Review by radinamatic — DISMISSED** [review]
Great job, add the fix for https://github.com/learningequality/kolibri-installer-windows/issues/119, and we can merge!

**Review by indirectlylit — APPROVED** [review]
great!

**Pull request merged**
