### PR TITLE
Exercise progress and mastered/next item redesign 

### PR DESCRIPTION
**Pull request by christianmemije**
### Summary

Exercise progress changes
* Always visible, fixed to bottom. 
* More feedback

Mastery changes
* Modal and side in replaced by 2 snackbars that appear in all content types.
* A new content card for next resource appears. 

TODO:
~Include thumbnail url in next_content~
Make the whole snackbar clickable?

localhost_8000_learn_ iphone 5_se

thoughts

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [x] Reviewer has fully tested the PR manually
- [x] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
Code looks good to me - @jtamiace could you weigh in on whether the whole snackbar for 'next item' should be clickable? I agree just the link is a bit small on mobile screens in particular.

**Comment by jtamiace** [comment]
I believe @khangmach was working with Christian on this -- Khang was this the final decision on the points + next item snackbar? (clickable text vs whole card)

**Comment by khangmach** [comment]
@christianmemije and I were debating whether or not to make the whole card clickable. Seems like a wider hitbox can't hurt -- lets make the whole thing clickable! 👍 ?

**Comment by rtibbles** [comment]
Yeah, the only thing to bear in mind would be screen reader support, but that's the only caveat!

**Comment by jtamiace** [comment]
Would it be unreadable by a screen reader for either option? If so, we should probably go with the one that's screen-readable

**Comment by rtibbles** [comment]
Not unreadable, just making sure it was a single link with a clear description (and then sr-hide the description text that displays inside the snackbar).

**Review by indirectlylit — APPROVED** [review]
this looks great. feel free to merge pending snackbar changes

**Pull request merged**
