### PR TITLE
Allowing upload step to continue without pi image

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

Builds are _really_ slow. This change should let me block the pi pipeline without having this build fail. Once this is in, I can re-enable blocked-by-default on the pi pipeline.

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by bjester — APPROVED** [review]
Makes sense to me

**Comment by DXCanas** [comment]
Not necessary right now. Better suited for 13.1, as jose marked in milestone. Rebased to avoid breaking android build.

**Comment by indirectlylit** [comment]
@DXCanas time to revisit this?

**Comment by DXCanas** [comment]
Working on an alternative as we speak

**Pull request closed without merging**
