### PR TITLE
various strings

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

* updates tooltip text to "Unlisted channel"
* stubs out text related to setting changes (https://github.com/learningequality/kolibri/issues/5355, https://github.com/learningequality/kolibri/issues/4927)
* add cross-links between settings pages
* fixes design of language selector label
* adds 'empty state' string for learners in Learn (https://github.com/learningequality/kolibri/issues/4701)
* updates privacy modal strings (https://github.com/learningequality/kolibri/issues/6057)
* release notification strings (https://github.com/learningequality/kolibri/issues/6025)

| before | after |
|--|--|
| image | image|
| image|image|
|image|image|
|image |image|

 

### Reviewer guidance

This is not functional yet but I want to get the strings in for string freeze

### References

* https://www.notion.so/learningequality/new-setting-allow-other-computers-on-this-network-to-import-my-unlisted-channels-6420ebc83df1419f9d3a40fb4f13ffe1

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jtamiace** [comment]
I had trouble parsing the implications of the second checkbox in device settings. I think it might be because at first it wasn't clear _when_ the user would be going to these pages. 

Maybe somehow incorporating the concept of "landing page" or "first thing the user sees" more explicitly? 

I know a single checkbox would be simplest, but here is an alternative. The second option makes the sign-in page as default as implicit (assuming that the user understands through their own usage and experience that the sign in page is the default):

Screen Shot 2019-11-12 at 9 36 52 AM

**Comment by indirectlylit** [comment]
I like the radio button idea a lot - thanks

**Review by nucleogenesis — APPROVED** [review]
Looks good to me. I'm not sure if @indirectlylit wants to make the "landing page" setting a radio button here or in a separate PR so I won't merge.

**Comment by indirectlylit** [comment]
self-merging for string freeze

**Pull request merged**
