### PR TITLE
Made bootstrapping code compatible with py3.

### PR DESCRIPTION
**Pull request by ralphiee22**
## Summary

Fixed some issues with python 3. Decoding bytes to utf-8 and using six library.

## Issues addressed

Code was broken on py3.

### CODE REVIEW

**Comment by radinamatic** [comment]
@indirectlylit 
Fetched the latest develop today, and run into this again... 
@ralphiee22's fix works OK too, any reason (a part from the vacations in the middle :stuck_out_tongue:) this is still not merged?

**Comment by rtibbles** [comment]
Testing on Py2 now to ensure we don't break any eggs to make this omelette.

**Comment by radinamatic** [comment]
Gottit! Certainly wouldn't want a bad Py2 omelette.

**Comment by rtibbles** [comment]
Doesn't seem to cause any issues for Python 2, and fix has been confirmed by @radinamatic. Merging.

**Pull request merged**
