### PR TITLE
Fix HTML5 Apps on iOS 9.3 + Safari

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
* Catch errors encountered on iOS 9.3/Safari where properties could not  be deleted.

### Reviewer guidance
Test using iOS 9.3 and Safari, do these HTML5 Apps work:
* African Storybook
* CK-12 PLIX
* Thoughtful Learning

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by radinamatic** [comment]
Build is kind of lagging, going to pull your branch locally!

**Review by radinamatic — APPROVED** [review]
Very slow getting this result in Browserstack, but the fix seems to be working.

Only reported errors are about missing fonts (@indirectlylit I need to file a separate issue on the **ASB chef repo**, as this is replicated constantly)

**Comment by rtibbles** [comment]
Note that the missing font issues are content related issues.

**Comment by jredrejo** [comment]
Confirmed with Chris Jackson after testing in real iPads 2 that the issues have been fixed.

**Pull request merged**
