### PR TITLE
Display author, license, and license owner info on content page.

### PR DESCRIPTION
**Pull request by christianmemije**
## Summary

* Display author, license, and license owner info on content page.
* Minimal styling.

## TODO

* Styling?

## Screenshot

image

### CODE REVIEW

**Comment by indirectlylit** [comment]
Looks good. quick feedback:

* The spacing between the metadata and the 'download' button looks a little tight?
* Maybe better below 'download' than above? Just trying to think of what's more important - admittedly neither are super critical functionality.

**Comment by christianmemije** [comment]
I was debating if below or above the download button would be best, and I went with above because:

  1. Description and metadata kind of go together.
  2. Upon opening the drop down menu the metadata is hidden.

### Above Download Button

image

### Below Download Button

image

**Comment by indirectlylit** [comment]
fair enough!

**Comment by indirectlylit** [comment]
but yeah, I would expect this spacing to be consistent:

image

**Comment by christianmemije** [comment]
Will address that in the next commit.

**Comment by jamalex** [comment]
1. "License Owner:" should be "Copyright:" or "Copyright holder:"
2. Would it make sense to have download button and this attribution block side-by-side on larger screens, and then responsively flow to above/below on smaller screens?

**Comment by radinamatic** [comment]
Was about to say the same as @jamalex, maybe even consolidate the presentation of metadata and options for downloadable content in a [tab-like-ui-element](https://josephuspaye.github.io/Keen-UI/#/ui-tabs-docs). The first one opened by default could contain the description, with metadata and download options could follow on the left.

**Comment by christianmemije** [comment]
### Updated
image

**Comment by christianmemije** [comment]
@radinamatic Once we integrate a component library that will be easy to accomplish! :pray:

**Comment by jamalex** [comment]
> The first one opened by default could contain the description, with metadata and download options could follow on the left.

Just a note that it may not be prominent enough for the comfort of many copyright holders to have the attribution hidden in a subtab. It doesn't need to be big or obvious, but showing by default is probably safest.

**Comment by radinamatic** [comment]
Never thought of that, shame... 😭

**Pull request merged**
