### PR TITLE
Fix: mark as complete modal/logic moved into content page

### LINKED ISSUE #9795: 'Allow learner to mark as complete' not working in Kolibri
## Observed behavior
Scratch all below, my longer-term memory must be off today... 🤦🏽‍♀️ 

Not sure if it's a Studio or Kolibri issue: marking a resource as available to check as completed by learner is not working in Kolibri (tested on 0.15 and 0.16), with ``Error in v-on handler: "TypeError: this.$store.dispatch`` in the console.

0.15 | 0.16
-- | --
make-completed | LEDev (start)  Running  - Oracle VM VirtualBox_024

~I don't recall what was the reasoning to already include in this release the **Allow learner to mark as complete** feature in the edit modal, when no learner in Kolibri will be able to use it for at least a few months...? I'm assuming here that feature will be included in Kolibri 0.16, and if that is the case, this early inclusion is just generating a (contributing to) cognitive overload for Studio users on the edit modal that is already bursting with features and options~

~We should have though better around the UX implications, and at least include additional information string saying the feature is not yet available in Kolibri. In that case we would again have to remove it once 0.16 Kolibri is released.~

~Last but not least, there's no way we can test the feature at this time, and if I understand correctly, it can have [ramifications and cause conflicts in delicate parts of the code around completion and duration](https://github.com/learningequality/studio/issues/3758).~

## Expected behavior
Learners able to mark resource in Kolibri.

cc @bjester @rtibbles

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Summary

Moves the logic for the Mark As Complete modal so that the modal lives in ContentPage now where the "content session" has been initialized using the `useProgressTracking` module. This seemed like a better alternative to trying to initialize another content session within the context of the modal itself.

Now Learn has a `showCompleteContentModal` state which is set to `false` whenever `ContentPage` is created (just to be sure it doesn't stay open if the user navigates back and to another piece of content). `LearnActivityBar` now just sets that Vuex state to true whenever the "mark as complete" button is clicked.

## References

Fixes #9795 

## Reviewer guidance

You will need two things:

- To run Kolibri with an initialized app plugin; you can use the script in #9803 being sure to set the environment variables as such:
`DJANGO_SETTINGS_MODULE=kolibri.deployment.default.settings.dev KOLIBRI_CENTRAL_CONTENT_BASE_URL=https://hotfixes.studio.learningequality.org python path/to/script.py`
- Then you can use the content @marcellamaki shared with me: `dolok-jajiv` (or one of your own if you have it setup already) 
- Go to a piece of content that has the metadata allowing it to be marked as complete and try to mark it complete. 
- You ought to see a snackbar saying you've completed the resource and the icon should change to the yellow "completed" star.

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by marcellamaki — APPROVED** [review]
Looks great! Code is super easy to follow, thanks for the comments, and works exactly as expected. Good to go once the linting is sorted. Thanks @nucleogenesis 🎉

**Comment by marcellamaki** [comment]
One small thing I noticed this morning, @nucleogenesis -- we might want to disable the mark as complete option once the resource is completed, either because the learner has marked it, or because they completed it based on pages read, view time, etc. If you go to "mark as complete" again, there is a console error and the modal doesn't close. I don't think it's likely that people will keep trying to do this, but preventing it would be nice :D

**Comment by nucleogenesis** [comment]
Thanks @marcellamaki ! I just pushed some code to hide the mark complete button for already completed contents.

Also - the linting issue seems to be related to a configuration error that will be fixed in https://github.com/learningequality/kolibri/pull/9810 so should be [good to merge](https://learningequality.slack.com/archives/CB37UM23A/p1667502024298029?thread_ts=1667494395.249509&cid=CB37UM23A)

**Comment by rtibbles** [comment]
Linting issue has been fixed in the release branch.

**Comment by pcenov** [comment]
Hi @nucleogenesis and @marcellamaki while testing the latest [Kolibri beta](https://buildkite.com/learningequality/kolibri-python-package/builds/6562) build I noticed that once I've marked a resource as completed the icon remains visible and I am able to click it again which is confusing. Also once it does disappear I'm still seeing the ellipsis button instead of directly showing the 'View information' icon to the right of the bookmarks icon. Here are a couple of videos to illustrate that:
1. Not signed in learner:

https://user-images.githubusercontent.com/79847249/200881192-54b03ef0-3ff8-4269-8a07-61a25b618b90.mp4

2. Signed in learner:

https://user-images.githubusercontent.com/79847249/200881338-c0c653c6-3b75-4595-9892-a5355ac96a5f.mp4

**Comment by nucleogenesis** [comment]
Thanks @pcenov I'll see if I can find a way to replicate and submit a new PR this week.

**Pull request merged**
