### PR TITLE
Vue2: More linting fixes.

### PR DESCRIPTION
**Pull request by christianmemije**
## Summary

* More linting fixes.

### CODE REVIEW

**Comment by indirectlylit** [comment]
I'm a little wary of merging this in without testing it - I have a feeling it's going to break some styling. However I realize these changes are necessary for allowing the compiler to run while we work on other things... thoughts?

**Comment by 66eli77** [comment]
I think break is better than alter the behavior cause it's much easier to find out, since this branch is current broken already, seems ok to merge to me.

**Comment by indirectlylit** [comment]
Let's add very loud comments next to all these changes, with a note that they are untested and likely need fixing. Also a note to do that fixing under https://trello.com/c/53ISgSuY/687-vue2-misc-to-dos

then we can merge it in and come back to it once the UI is loading fully

**Comment by indirectlylit** [comment]
re: "this branch is current broken already"

It doesn't compile and load, but so far all the changes that have been merged in are things we're fairly confident about. So it's still fairly 'clean' at the moment.

**Pull request merged**
