### PR TITLE
i18n fixes and updates – includes Mozambican Portuguese

### PR DESCRIPTION
**Pull request by indirectlylit**
## User page issue

Addresses an issue introduced in #8443  where the namespace for some strings changed from `UserIndex` to `UserAuthIndex` post-string-freeze. This was giving rise to errors of the form:

```
Kolibri: Could not find translation for message UserAuthIndex.signUpStep1Title in CSV files
Kolibri: Could not find translation for message UserAuthIndex.signUpStep2Title in CSV files
```

Addresses this by temporarily using `createTranslator` to fake the original namespace. We should remove this post-0.15.

## Context transfer issue

Additionally, addresses an issue where the `transfercontext` utility assumed the context node existed, which broke in some cases and gave an error like this:

```
/home/didivm/LE/kolibri/packages/kolibri-tools/lib/i18n/SyncContext.js:74
      contextProperty.value.type === 'StringLiteral' &&
                      ^

TypeError: Cannot read property 'value' of undefined
    at modifyTranslationObjectNode (/home/didivm/LE/kolibri/packages/kolibri-tools/lib/i18n/SyncContext.js:74:23)
    at pre (/home/didivm/LE/kolibri/packages/kolibri-tools/lib/i18n/SyncContext.js:142:15)
    at visit (/home/didivm/LE/kolibri/node_modules/ast-traverse/ast-traverse.js:16:19)
    at visit (/home/didivm/LE/kolibri/node_modules/ast-traverse/ast-traverse.js:32:21)
    at visit (/home/didivm/LE/kolibri/node_modules/ast-traverse/ast-traverse.js:29:25)
    at visit (/home/didivm/LE/kolibri/node_modules/ast-traverse/ast-traverse.js:32:21)
    at visit (/home/didivm/LE/kolibri/node_modules/ast-traverse/ast-traverse.js:29:25)
    at visit (/home/didivm/LE/kolibri/node_modules/ast-traverse/ast-traverse.js:32:21)
    at traverse (/home/didivm/LE/kolibri/node_modules/ast-traverse/ast-traverse.js:42:5)
    at modifyCreateTranslatorASTNodes (/home/didivm/LE/kolibri/packages/kolibri-tools/lib/i18n/SyncContext.js:128:3)
error Command failed with exit code 1.
```

## String updates

* Pulls latest translations and context
* Adds `pt-mz`, superseding https://github.com/learningequality/kolibri/pull/8572

## Reviewer guidance

For code reviewers, recommend looking at individual commits rather than the full diff.

After pulling this, it's necessary to run: `make i18n-extract-frontend` first in order to update the local CSV files:

```bash
make i18n-extract-frontend
make i18n-download branch=release-v0.15.x
```

If you see an error like this:

```
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path '/Users/d/Projects/le/kolibri/kolibri/locale/bg_BG/LC_MESSAGES/glossary/glossary' already exists
make: *** [i18n-download-translations] Error 1
```

It means that the `locale` folder is in a corrupt state. The easiest thing to do might be to clone Kolibri from scratch, or delete and reset just the `locale` folder. Then run again:

```bash
make i18n-extract-frontend
make i18n-download branch=release-v0.15.x
```

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
Looking good, no missing translation errors before or after running `make i18n-download` 🙂 

Georgian | Khmer
--- | ---
 |

**Review by radinamatic — APPROVED** [review]
LGTM! 💯

**Comment by radinamatic** [comment]
Yey for PT-MZ!!! 🎉 🇲🇿 

1 | 2
--- | ---
 |

**Review by rtibbles — CHANGES_REQUESTED** [review]
Was committing the glossary intentional?

**Comment by radinamatic** [comment]
Ugh, I deleted it from Crowdin, but I guess too late 😞

**Comment by indirectlylit** [comment]
> Was committing the glossary intentional?

No, I've never seen those files before but they seem to have been generated during the process.

Anyone know anything about where they're coming from?

**Comment by radinamatic** [comment]
All me, doing some experiments on Crowdin. I hid the glossary file from translators, but forgot that it would be pulled into the source 🤦🏽

**Comment by radinamatic** [comment]
Anyway, now the file is deleted, would one more run of `make i18n-download` solve the issue?

**Comment by indirectlylit** [comment]
didn't appear to but I made the change manually and force-pushed.

good catch @rtibbles!

**Review by rtibbles — APPROVED** [review]

**Pull request merged**
