### PR TITLE
Revert CSS-based fix for carousel shadows, use inline-styles fixes #4399

### LINKED ISSUE #4399: View more in Recommended page is not working
### Observed behavior
In Learners Recommended page, View more label cannot clicked. 

### Expected behavior
Must be clickable the View more label.

### Steps to reproduce
* Sign in as learner
* Go to Learner > Recommended page
* Click the View more label

### Context
 * Kolibri version : 0.11.0b1
 * Operating system : Windows 7 and 10
 * Browser : Firefox  62.0.3 (64-bit)

### PR DESCRIPTION
**Pull request by jonboiser**
This reverts commit 75f9e86239984611b67aa267850553105811a7cf.

Fixes #4399, since the CSS-based fix using negative margin blocks buttons near the carousel.

Also moves the 'next' / '->' control 25 pixels to the right to make it look more balanced

screen shot 2018-10-12 at 12 09 49 pm

### Summary

…

### Reviewer guidance

…

### References

…

----

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Review by christianmemije — APPROVED** [review]
LGTM

**Comment by DXCanas** [comment]
Please see comments on #4399 before merge

**Comment by rtibbles** [comment]
@DXCanas should something be changed before this is merged?

**Review by DXCanas — APPROVED** [review]
@rtibbles I would rather move the "view more" button so that it's after the cards, preventing the overlap that's happening. This fix shifts the cards in ways that interrupt the grid on the recommended page and the buttons in such a way that the control buttons aren't consistently placed.

...but I'm seeing now that moving the "view more" button is a bigger ask than I thought, as it's been abstracted out to another component. And I don't think my issues with the fix are a big enough deal to block the fix. ~So I'll merge.~

Can't merge. But I approve :+1:

**Pull request merged**
