### PR TITLE
consistent icons and tables

### LINKED ISSUE #4858: fix icons in Coach tables
### Observed behavior

Size, spacing, and alignment in Plan:

> image

> image

> image

> image

Missing entirely in Reports:

> image

### Expected behavior

Consistent spacing and sizing everywhere. See the new `LabeledIcon` as a reference (if not implementation), which renders like:

> image

### User-facing consequences

visual inconsistency and missing icons

### Context

k 0.12.0 alpha 7

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

* Adds new `KLabeledIcon` and `KIcon` components
* Makes table formatting more consistent across all plugins
* Adds missing 'back' link on groups management page

### Reviewer guidance

Please browse around and make sure things don't seem broken

I'd like to get this in before the next beta

### References

fixes #4858 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by jonboiser** [comment]
The styling between Coach > Plan, and Coach > Report tables is still a little bit different.

**Comment by indirectlylit** [comment]
pushed change: all `td` -> `th` in `thead`

**Comment by jonboiser** [comment]
Icons on NotificationCard are not vertically middle aligned
screen shot 2019-02-07 at 10 40 29 am

**Comment by jonboiser** [comment]
In RTL, the icons don't get any margin. Screenshot from Brave (CHromium)
screen shot 2019-02-07 at 12 07 15 pm

**Comment by jonboiser** [comment]
In RTL, some columns aren't text-aligned to the Right (would be left in LTR)

screen shot 2019-02-07 at 12 11 11 pm

**Review by jonboiser — APPROVED** [review]

**Pull request merged**
