### PR TITLE
allowRemoteAccess `undefined` from state - was a getter

### PR DESCRIPTION
**Pull request by nucleogenesis**
### Summary

I couldn't see my channels in Learn despite the settings saying that I should.

I found that one piece of the state in the boolean deciding whether to render the Channels and Recommended tabs was trying to get `allowRemoteAccess` from state but it was a getter.

### Reviewer guidance

Pull regular `app-support` as it is now - try to view channels in Learn as any user.

Check this branch out then see your content appear in Learn.

### References

Me. 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by jamalex — APPROVED** [review]
Looks good to me, if it's working for you!

**Review by indirectlylit — APPROVED** [review]
this is correct - it moved from being state to being a getter.

Any chance there are other instances? (cc @jredrejo)

**Comment by indirectlylit** [comment]
test is failing, but I thought I fixed it in 6c3895d83a01e3622d3a3636185c642a732bdf6b

**Comment by bjester** [comment]
@nucleogenesis This is not fixed for me. I tried the PEX and built fresh from your branch and I still go to the classes view instead of channels.

**Pull request merged**
