### PR TITLE
Clear cache on model creation

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

The resource layer handles a ton of cool cases. Richard's awesome. But we've been running into this invalid cache thing quite often.

Here, the collection cache is cleared because we can't be certain about a new model's inclusion in that cache. This is conservative in the sense that it doesn't clear out the model cache.

### Reviewer guidance

Single line, but could solve a majority of our force fetch issues. 

Creating a read-only prop down the line has been mentioned, and that would solve the problems involved in concurrent edits... but I like this better.

### References

March 22 bug bash
----

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by DXCanas** [comment]
@rtibbles I can do a force fetch on the page in coach that brought this issue up, if need be.

I spent a bit too much time figuring out how to write a custom Resource method that takes `getCollections` where `ids` is the parameter so that those `getCollection` calls never go out to the server. Ended up scrapping it all because the only use case I saw for it was lessons :man_shrugging:

**Comment by rtibbles** [comment]
You should be able to pass ids with a list of ids as a collection parameter, so at least you don't have to fire off multiple requests.

**Comment by rtibbles** [comment]
This method was used in exams to fetch all content data in a single fetch.

**Comment by DXCanas** [comment]
^ yeah, I use that with content nodes too

I meant that I was trying to get the the resource layer pass those array-of-ids getCollection through a sieve so that it doesn't fetched the already-cached models

**Comment by DXCanas** [comment]
This should be ready to merge, though.

**Comment by benjaoming** [comment]
Please revert if you disagree! But I don't see anything here that would cause problems in a release, contrarily :)

**Pull request merged**
