### PR TITLE
Move #5308 to release-v0.12.x

### LINKED ISSUE #3598: Class coaches can access class pages even when they are not assigned to the class
### Observed behavior
~I can access the class groups rename form as coach but I have 403 error after I submit it.~

Class Coaches can access a classroom page even if they are not assigned to the classroom.

### Expected behavior
~The class groups rename form most not accessible in coach.~

Pages from classrooms not assigned to the coach should not be accessible to the coach.
 
It should be redirected in the `auth-message` refer at the screenshot below
screen shot 2018-04-27 at 3 13 57 pm

### Steps to reproduce
- Log in as admin, then navigate at `class groups` page then copy the link.
- Log out as admin then Log in as coach then navigate at the `class groups` page using the link.
- Try to rename a class groups then submit it.

### Context

Tell us about your environment, including:
 * Kolibri 0.10.0.dev1.dev+git-33-g268dd8a
 * macOS 10.13.3
 * Chome Version 65.0.3325.181 (Official Build) (64-bit)

…

### PR DESCRIPTION
**Pull request by MisRob**
### Summary

Move #5308 to `release-v0.12.x` as discussed [here](https://github.com/learningequality/kolibri/issues/3598#issuecomment-481771076).

### References

Fixes #3598

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Review by jonboiser — APPROVED** [review]
Tested it briefly with an admin, class coach, and learner account. Looks good.

**Comment by indirectlylit** [comment]
Was this PR created using `git cherry-pick`? I'm getting some merge conflicts going back to `develop`

**Comment by MisRob** [comment]
Yes, I cherry-picked these commits. What were the conflicts?

**Comment by indirectlylit** [comment]
There weren't any real conflicts; however the changes that were cherry-picked seemed to conflict with themselves.

I've never fully understood how git tracks cherry-picked changes across multiple branches with different commit hashes. Sometimes it seems smart enough to understand that there is no conflict, and other times like this the duplicate changes collide...

no worries! I think we just need to generally avoid going from `develop` -> release branches, and try to go the other direction when possible

**Pull request merged**
