### PR TITLE
Use KRadioButtonGroup in the language switcher modal and on the Device settings page

### PR DESCRIPTION
**Pull request by muditchoudhary**
## Summary

…

## References

- [12243](https://github.com/learningequality/kolibri/pull/12243)
-  [650](https://github.com/learningequality/kolibri-design-system/pull/650)
- [10491](https://github.com/learningequality/kolibri/issues/10491)

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by muditchoudhary** [comment]
Hi @pcenov @radinamatic could you please QA test now? I fixed the tab issue on the change language modal.

cc: @MisRob

**Comment by MisRob** [comment]
Thanks @muditchoudhary!

For QA, test instructions are written here https://github.com/learningequality/kolibri/pull/12243

**Comment by pcenov** [comment]
Thanks a lot @muditchoudhary!
@radinamatic I confirm that tab navigation through the radio buttons in the language modal is working correctly in Firefox:

https://github.com/learningequality/kolibri/assets/79847249/92984660-e0c7-48d0-9f2a-20d35202ec7b

**Comment by muditchoudhary** [comment]
Thank you @pcenov

**Comment by MisRob** [comment]
@radinamatic @pcenov Could you please re-test this PR? I've tried briefly and looked good to me.

**Comment by MisRob** [comment]
Actually we will need one more code adjustment, so let's wait for final version before QA. I will let you know when it's ready @radinamatic @pcenov

**Comment by MisRob** [comment]
Thanks for getting everything ready here @muditchoudhary! @radinamatic @pcenov it's ready for final QA :)

**Comment by pcenov** [comment]
Hi @MisRob - no issues observed while manually testing - good to go!

**Comment by MisRob** [comment]
Thanks! We merged the KDS PR. As soon as the new KDS release is ready, I will install it here and we can merge.

**Review by MisRob — APPROVED** [review]
QA passed and code also looks well to me. I rebased on top of the latest `develop` that contains the KDS release with `KRadioButtonGroup`. Let me preview the latest build as soon as it's ready and then we can merge.

**Comment by MisRob** [comment]
Briefly re-tested on the most recent build, all good

**Comment by MisRob** [comment]
Yey @muditchoudhary, it's live now!

**Comment by muditchoudhary** [comment]
Yayy!! Thank you for telling me @MisRob

**Pull request merged**
