### PR TITLE
Update Category Search Modal keyboard accessibility

### LINKED ISSUE #8698: sub-category chooser does not have hover states or keyboard nav
## Observed behavior

The sub-category chooser has no keyboard navigation or hover states:

In some cases there is a pointer cursor, but the item isn't actually clickable:

## Expected behavior

The UI in here feels fairly different from typical interactive elements in KDS. If possible we should try to use established components, but if the design calls for something special we'll need do a bit more work on ensuring accessibility.

## User-facing consequences

* no keyboard nav
* not totally clear that headers _and_ child elements are clickable categories
* some things that look clickable due to cursor aren't actually

## Context

0.15.0-beta2

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary

Swaps in KButton component to add tab/keyboard nav, focus outline, and hover state. Updates cursor pointer for accuracy.

## References

Fixes #8698

tab-nav-category-modal

## Reviewer guidance
Does this make significant enough improvement? Any further design recommendations @jtamiace?

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by indirectlylit — APPROVED** [review]
Thank you, this is a huge improvement!

Two other more minor questions while we're here – cc @jtamiace 

1. **Icon location:** Curious whether it was intentional to not use a `KLabeledIcon` and instead use a separate row? The layout looks a little odd to my eyes as it is:

| current | labeled icon |
|--|--|
| image |  image |
| image | image |

2. **Hover state:** Still feels very subtle compared to KDS components. In particular the fade from `text` to `primary` is very slow and low-contrast:

**Comment by jtamiace** [comment]
The icons were meant to be a bit bigger - in the [mockup](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=5896%3A84371) they're 40px, but can adjust to the size that seems right. (sorry, I never included this in the main Figma page for searching)

Screen Shot 2021-11-16 at 9 30 35 AM

For the hover state, we could do something like this? Building off some of your suggestions in https://github.com/learningequality/kolibri/issues/8631

Screen Shot 2021-11-16 at 10 29 33 AM

**Review by jtamiace — COMMENTED** [review]
I don't know if hover states would be better in a follow up issue since there are several UIs that could apply to, otherwise I think this is great!

**Review by jtamiace — APPROVED** [review]

**Comment by indirectlylit** [comment]
> I don't know if hover states would be better in a follow up issue since there are several UIs

@marcellamaki – up to you. Feel free to merge and I'll file a follow-up issue if you'd prefer.

**Comment by indirectlylit** [comment]
@jtamiace 

> in the mockup they're 40px

was this also the case for the non-nested selectors?

**Comment by jtamiace** [comment]
> non-nested selectors

What is this referring to?

**Comment by indirectlylit** [comment]
Like this one, where there are only "headers" but no child elements:

image

**Comment by jtamiace** [comment]
Oh, yes, it'd be the same

**Comment by rtibbles** [comment]
Going to merge this, let's file follow up issues (although I'm not sure what the precise issue would be).

**Pull request merged**
