### PR TITLE
Remove svg-icon-inline-loader from dependencies, removes large dep

### LINKED ISSUE #7890: remove material-design-icons dependency from kolibri tools
### Observed behavior

`material-design-icons` is [a dependency of `svg-icon-inline-loader`](https://github.com/learningequality/svg-icon-inline-loader/blob/9f137b273af978eda901c6f92b648be30322a15d/package.json#L35) which is [a dependency of `kolibri-tools`](https://github.com/learningequality/kolibri/blob/5df5f30aac0daf0ab97e5fb79e9a3555a9679618/packages/kolibri-tools/package.json#L74)

### Expected behavior

The design system should have pre-processed icons built-in, negating the need for any `material-design-icons` dependency.

### User-facing consequences

Many unnecessary MB of data downloaded, and occasional inscrutable errors

* https://github.com/learningequality/kolibri/pull/7881
* https://github.com/learningequality/studio/issues/2096
* https://github.com/learningequality/studio/#yarn-and-javascript-dependencies

### Errors and logs

```
There appears to be trouble with your network connection. Retrying...
```

### Context

0.14

### PR DESCRIPTION
**Pull request by nucleogenesis**
### Summary

This is a **Draft** for now - need to be sure this is the right branch and coordinate a Kolibri Design System release with the next 0.14.x release if we merge this PR. Need this merged in KDS: https://github.com/learningequality/kolibri-design-system/pull/204

Our  [SVG Icon Inline Loader](https://github.com/learningequality/svg-icon-inline-loader) package depended on [material-design-icons](https://github.com/learningequality/svg-icon-inline-loader/blob/9f137b273af978eda901c6f92b648be30322a15d/package.json#L35) which was noticed because it caused timeouts during `yarn install` for some people due to the size of that Material Icons package.

KDS already has an optimization in place to avoid needing to include that whole package. KDS precompiles SVG icons from Material (and elsewhere) into Vue components. During packaging, only the icons which are actually used are bundled.

Hence this PR which removes all uses of `mat-svg` and `file-svg`.

Removing the `file-svg` required adding the leaf icons to KDS here: https://github.com/learningequality/kolibri-design-system/pull/204

Also - removes the `Answer.vue` component - it is not used anywhere.

### Reviewer guidance

[yarn link KDS to Kolibri](https://github.com/learningequality/kolibri-design-system#development-in-parallel-with-other-applications) and then check a few places:

Lesson Preview (Lesson -> Manage Resources -> Drill down all the way into a resource to preview it) - note that the icon changed from a black check circle to a green one, using the `onDevice` icon. @jtamiace - I can change this to black, but the green seemed to suit the context better.

|Before|After|
|---|---|
|icons-check-lessonpreview-before|icons-check-lessonpreview-after|

---

Superuser Credentials (during onboarding)

- Set your `KOLIBRI_HOME` env var to some dir that isn't a Kolibri Home dir
- Go through onboarding to the superuser credentials form

@jonboiser - previously, the footer didn't show. I fixed this issue - also now the icon is visible.

---

Leaf icons:

- Profile in AppBar
- Check your profile page
- Go to and complete a resource, see the leaf icon pop-up

---

PDF Controls

icons-pdfcontrols-before

### References

Fixes https://github.com/learningequality/kolibri/issues/7890

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by nucleogenesis** [comment]
Another thing to note before merging - the `kolibri-tools` package in this branch should be published - then the `kolibri/core/package.json` should be updated to that version of `kolibri-tools` to ensure the changes are seen.

**Comment by rtibbles** [comment]
As this is primarily a development/build issue, maybe we should target this to develop, as it's not solving a user issue specifically?

**Comment by nucleogenesis** [comment]
@jonboiser 

The only thing remaining here is that merging this will break Kolibri until it is downloading and using the latest 0.2.x branch of KDS so that this PR is included: https://github.com/learningequality/kolibri-design-system/pull/204

Initially, this was targeted at 0.14.x so I was more hesitant then - but now we're pointing at develop so I suspect that we'll see the issue fixed relatively soon anyway. If you're comfortable w/ that let's merge this, otherwise I can work toward getting a release of KDS out sooner than later and then we can update this PR to point to the new KDS release before merging.

**Comment by jonboiser** [comment]
In webpack.config.base.js, you need to remove this loader config

```
        // Preprocessing rules
        // {
        //   test: /\.(html|vue)$/,
        //   enforce: 'pre',
        //   // handles <mat-svg/>, <ion-svg/>, <iconic-svg/>, and <file-svg/> svg inlining
        //   loader: 'svg-icon-inline-loader',
        //   exclude: /node_modules/,
        // },
        // Transpilation and code loading rules

```

**Comment by nucleogenesis** [comment]
@jonboiser This should be good to go. Good catch on that webpack config - my vim grep didn't find that one.

I've also released a beta of KDS 0.2.2 - https://github.com/learningequality/kolibri-design-system/releases/tag/v0.2.2-beta-1 and updated the package.json here to point there.

**Comment by rtibbles** [comment]
Looks like you need to rebuild 4 snapshot tests to get the test suite passing!

**Review by jonboiser — APPROVED** [review]
Looks good!

**Pull request merged**
