### PR TITLE
Add padding to <th> and <td> elements on device permission page table

### LINKED ISSUE #8948: Edit Permissions - German text issues
## Observed behavior
While testing https://github.com/learningequality/kolibri/pull/8946 I noticed that when viewing the content in German at the Edit Permissions page the name of the learner is getting to close to the label. Note that in IE 11 the labels are not left aligned.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-python-package/builds/4677
2. Switch to German language and go to: Device>Permissions
2. Click on Edit Permissions

## Usage Details
Windows (Internet Explorer 11), Ubuntu (Chrome), Android 7(Samsung S7 )

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary
Adds a small amount of padding to the table cell elements on the device permissions page, so that when there are long strings in separate cells, they do not touch.

| Screen size  |  Before  |  After  |
|---|---|---|
| xs screen  | Screen Shot 2022-02-08 at 4 52 51 PM | Screen Shot 2022-02-08 at 4 48 15 PM |
| sm screen  | Screen Shot 2022-02-08 at 4 52 42 PM  | Screen Shot 2022-02-08 at 4 48 24 PM |

## References
Fixes #8948 

## Reviewer guidance
- With language settings on German and on a mobile size display: Device > Permissions > Edit Permissions 
- This does not take into consideration text wrapping, just the spacing issue. Is that sufficient to consider this done?

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by MisRob — APPROVED** [review]
Thank you @marcellamaki, it looks good to me.

**Comment by MisRob** [comment]
Maybe we could add this to the 0.15.1 milestone?

**Comment by marcellamaki** [comment]
Yes, I will add it!

**Review by radinamatic — APPROVED** [review]
Looking good, no glued-in strings anymore! 💯 :shipit:

**Pull request merged**
