### PR TITLE
Upgrade Python dependencies

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Upgrades all Python dependencies to the latest version that supports Python 3.6
* Note that it does not upgrade the Python redis library as far as it could go, because the django-redis-cache library we are using requires a redis version less than 4

## References
Because we are still supporting EOL Python versions, we have to do these upgrades manually rather than relying on dependabot

## Reviewer guidance
First we check if the tests pass, then a smoke test of the asset is in order, particularly testing Redis caching.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by marcellamaki — COMMENTED** [review]
The code read-through here seems fine, but I think some regression testing from the QA team would be very helpful @pcenov @radinamatic. It seems like smoke testing all of the various assets would be the place to start per Richard's notes. Not sure @rtibbles if you have any user workflows that would help with confirming redis-related things are working as expected?

**Comment by rtibbles** [comment]
The only way to test that would be alongside `kolibri-server` - failing that, when this is tested in KDP.

**Comment by pcenov** [comment]
Hi @rtibbles sorry but I am still not sure how to properly test this one - could you please provide additional testing guidance?

**Comment by rtibbles** [comment]
As @marcellamaki mentioned - I think just smoke testing the various assets here is about all that is needed, so just making sure they all start (bar the Mac installer, which we have a separate issue filed for) - and ensuring that you can access Kolibri.

**Comment by pcenov** [comment]
Hi @rtibbles 

1. The Android app is force closing immediately after being launched:

[android_logs.zip](https://github.com/user-attachments/files/15837956/android_logs.zip)

2. Both the .deb and .exe assets can be installed but it's not possible to import a facility and to preview a lesson resource when creating lessons:

https://github.com/learningequality/kolibri/assets/79847249/5ab5f396-b029-43e4-886f-70aced55769a



[ubuntu_logs.zip](https://github.com/user-attachments/files/15837979/ubuntu_logs.zip)

**Comment by rtibbles** [comment]
Seems like this is less straightforward than I had hoped!

**Comment by rtibbles** [comment]
Hi @pcenov, I have rebased onto the latest develop, which should fix the 500 error you saw in import, and have made a fix for the error I saw in the Android logs!

**Review by pcenov — COMMENTED** [review]
I confirm that now the Android app can be installed however it takes about 2 minutes to get to the first page of the setup wizard during which the user sees only a blank white screen. Here's the logcat log for that:

[logcat.txt](https://github.com/user-attachments/files/16011417/logcat.txt)

No other regressions observed in both the app and the desktop version of Kolibri.

**Comment by rtibbles** [comment]
Hrm, interesting - I'm not seeing anything unusual in the logs, my only hunch is that this has added a lot of additional files, causing the unpacking to take longer.

**Comment by pcenov** [comment]
Yeah, sadly that seems to be the case - it just takes a lot of time for the unpacking to happen...

**Comment by radinamatic** [comment]
I can confirm this as replicable on my devices too. If there's nothing we can do to speed up the _unpacking_ time, can we at least make sure to have the Kolibri loader instead of the blank screen for the duration? That would be better UX...

**Comment by radinamatic** [comment]
Or as we mentioned it with @pcenov, straight-up and explicit ``Loading...`` (we have the string).

**Comment by rtibbles** [comment]
Looking at the assets, it looks like we now have two different packages that provide a complete copy of the timezone database, I think this is the cause of the extra files.

I think we can clean this up and only have one of these packages, but it seems simpler to do this after 0.17.0 is released. Bumping this to the first patch milestone instead.

**Comment by pcenov** [comment]
Hi @rtibbles - I've tested again all the installers without any regressions observed, should be good to go!

**Review by marcellamaki — APPROVED** [review]
Updated changes make sense to me

**Pull request merged**
