### PR TITLE
Add a database_only mode in scanforcontent

### PR DESCRIPTION
**Pull request by dylanmccall**
## Summary

This change adds a `--database-only` argument to the `scanforcontent` management command. It allows us to use the command's existing smarts to conditionally import a new channel database, but skipping the step which sets content visibility based on detected files. It is useful for the content extensions work we are doing in the Kolibri flatpak.

### Reviewer guidance

I am unsure if this is the best place for this functionality - it just happened to be the smallest diff for the task at hand. (I had considered changing `importchannel` to understand when a channel database is already reachable on Kolibri's home dir or set of extra content directories, but `scanforcontent` already does that nicely). Please let me know if this looks sane or if there's a better place for it.

### References

Content import in Kolibri flatpak: learningequality/org.learningequality.Kolibri#7

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
@dylanmccall would you mind re-targeting to the 0.14.x branch?

**Comment by dylanmccall** [comment]
@indirectlylit okay, done!

**Comment by indirectlylit** [comment]
thank you!

**Comment by kollivier** [comment]
@dylanmccall Sorry it has taken time for us to look into this! Could you clarify whether this fix is a performance improvement (since in your case you know the files on disk are available), or did you run into an issue when calling `scanforcontent` without this in your setup?

Also, I might suggest using a flag name like `--skip-annotations` to be more explicit about what happens when you set the flag.

**Comment by dylanmccall** [comment]
Sure, that sounds like a _much_ better name :) I'll change that.

The issue with using `scanforcontent` _without_ this is it ends up going through content files on disk and marks content nodes as available based on that, but for content extensions we already have a metadata file which lists the content nodes we want to show; we don't need to do that step. What we _do_ need `scanforcontent` to do is to discover the channel database. After doing that, we can use `importcontent` with the correct `--node-ids` and `--exclude-node-ids`. So it's a performance optimization, and it also (as importantly) solves a problem where Kolibri would end up showing unexpected content nodes after loading an extension.

**Comment by kollivier** [comment]
@dylanmccall Okay, great, thanks for the detailed explanation! I think this is okay to merge, but it might be good to first add a comment in the code about it being related to content extensions (or maybe put a link to this PR?) so that people who come across it and wonder about it have some way to determine the context.

**Comment by dylanmccall** [comment]
Oh yeah, people might be a little confused by that. I added a comment now. Thank you!

**Review by kollivier — APPROVED** [review]
Great, thanks! I think we're good to go with this!

**Pull request merged**
