### PR TITLE
Fix keyboard focus styling on AppBar and Coach > Class Home Page

### LINKED ISSUE #5845: User menu button has no visual in-focus indicator
### Observed behavior
[Discovered](https://github.com/learningequality/kolibri/pull/5839#issuecomment-517759637) while testing #5839:

> in Firefox there is a slight button color change when the user menu button receives focus, but no border/outline (**issue 1a**), and on the next <kbd>Tab</kbd> press the inner text label receives focus (**issue 1b** - there's no need for the label to be focusable).

> In Chrome the text label does not seem focusable, but the user menu button has no visual focus indicator whatsoever (**issue 1c**).

### Expected behavior
Consistent styling for buttons when in focus.

### User-facing consequences
Not knowing where the current focus is.

### Errors and logs
…

### Steps to reproduce
Use the <kbd>Tab</kbd> key to focus user menu button.

### Context
 * Kolibri version: 0.13.0.dev
 * Operating system: all
 * Browser: Chrome & FF

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

**Remove focus ring and make username un-focusable on Firefox**

Dropdown is in the upper-right corner

| Before | After |
|--------|-------|
| firefox-before     | firefox-after      |

**Give items in Classes home page an outline when focused with keyboard**

After:

focus on blocks

### Reviewer guidance

1. Does the app work the same for you as these screenshots?

### References

Fixes #5845

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
I _was_ wrong, @jonboiser , there seem to be several OS-specific differences... 😒 

After installing and testing the built assets on both Ubuntu 16.04 and Windows 7 VMs, I see no focus outline on the user menu buttons on either of them. In addition, in Firefox on Ubuntu the `View all` button outline is also missing.

**Windows**

focus-windows2


**Ubuntu**

focus-ubuntu

**Comment by jonboiser** [comment]
On MacOS + Firefox, I also don't see the outline around the "View all" button. Changing the display attribute for the underlying anchor tag from `inline-table` to `inline-block` seems to fix it.

I'll see if something similar might be going on with the user menu, but I can't reproduce it on Mac.

**Comment by indirectlylit** [comment]
currently broken by https://github.com/learningequality/kolibri/issues/5884

**Comment by radinamatic** [comment]
Yes, please, eagerly awaiting the fix for this... :pray:

**Review by indirectlylit — APPROVED** [review]

**Comment by indirectlylit** [comment]
also partially addresses https://github.com/learningequality/kolibri/issues/6006

**Pull request merged**
