### PR TITLE
0.5 into 0.6

### PR DESCRIPTION
**Pull request by rtibbles**
# Checklist

- [X] PR has the correct target milestone when it's merged
- [X] Automated test coverage is satisfactory
- [x] PR has been fully tested manually

### CODE REVIEW

**Comment by radinamatic** [comment]
Permissions successfully unstuck @rtibbles! Can be assigned, withdrawn and update with no issues anymore... :+1: 

The only problem I found is the unspecified `Transfer failed...` error while importing form the UI, although only from the second imported channel. 

fullscreen_21_10_17_02_46

The first channel got imported correctly, the second failed through the UI, but had no issues with import from the command line.

**Comment by rtibbles** [comment]
OK, let's hold off on 0.6.0 until Monday to try to get to the bottom of this transfer failed bug.

**Comment by benjaoming** [comment]
not feature parity, but [bug parity](https://github.com/learningequality/ka-lite/issues/5528) :dancing_men:

**Comment by rtibbles** [comment]
There will be more merges yet...

**Pull request merged**
