### PR TITLE
Better handling of validation errors when remote facility does not require passwords

### LINKED ISSUE #11605: Setup Wizard - importing user from facility that doesn't require learner passwords
## Observed behavior
if progressing through the setup wizard: `Group-learning` > `LOD` > `Import one or more existing user accounts...` & the user selects a facility where learners are not required to have a password, the following `Import individual user accounts` page does not display a password field due to its conditional rendering. 

if user enters a username that **does not exist** within the selected facility, currently an error occurs that is not visible to users and keeps them from progressing further in the wizard. the error appears only in the console and doesn't seem to accurately reflect to the scenario that occurred, as the error details are `Password is required`, despite the password field not being available to the user.

## Errors and logs

image
image
image

[code for errors arising in this case was updated recently](https://github.com/learningequality/kolibri/pull/11541/files#diff-ba32c1a203321831f941bab48eb678f5b592af398c724fa48415375da15eacd1R52) in https://github.com/learningequality/kolibri/pull/11541

## Expected behavior

- **surfacing error to user**: currently if the user attempts to enter a non-existent username, a console error occurs but no error surfaced to the user and they remain on the page, inexplicably unable to progress. the user should be made aware of what problems are keeping them from progressing through setup. 

- **raising accurate error**:  currently the error that is raised if user enters a non-existent username, when investigated, has the detail `Password is required` - this message does not seem to accurately represent the scenario that has occurred, which is expected to be the detail that accompanies `error_constants.AUTHENTICATION_FAILED` (`"401 Client Error: Unauthorized for url:..."`)

- **handling legitimate non-learner cases**: if an extant **coach** or **admin** username is entered into the username field on the `Import individual user accounts` page, user should be prompted for that username's password as well - even if a facility does not require learner passwords, it still does require passwords for coach or admin users. in this case, raising the `Password is required` error could be appropriate but users also need guidance/a next step nudging them towards the `Use an admin account` link if the password text field is still not made available on the page.

## User-facing consequences
user gets "stuck" on `Import individual user accounts` page without any indication of what is wrong

## Steps to reproduce
- on/based off of release-v0.16.x branch
- fresh kolibri instance to trigger setup wizard
- `Group-learning` > `LOD` > `Import one or more existing user accounts...`
- connect to a facility in which **learner passwords are _not_ required**
- enter a non-existent username into the provided field & attempt to progress through the wizard
- see console for error details

### PR DESCRIPTION
**Pull request by jredrejo**
## Summary

When importing users in a LOD device, authentication errors were not passed as ValidationErrors to the frontend. Also, when the remote facility allowed authentication without password, if the username didn't exist no known error was being passed to the frontend.
This PR fixes these problems.

## References
Closes: #11605 

## Reviewer guidance
Steps to test this PR are described in the steps to reproduce #11605 

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
These changes make sense to me codewise, and do as described in the PR description. Needs manual QA to verify.

**Comment by pcenov** [comment]
Hi @jredrejo, I confirm that now the message "Incorrect username or password" is being displayed for not existing learner accounts or mistyped username/password.

Here's a list with other issues that I am aware of in terms of validation. Perhaps some of those are in scope for this PR, the rest can be fixed separately:

- there's still no error message displayed if the user attempts to submit an empty form (that's valid both for the learner credentials form and for the admin credentials form)
- when we have only the 'Username' field being displayed and I enter an admin username then I am still seeing the "Incorrect username or password" - I think in that case we should be showing the `Device limitations` modal
- if after seeing the "Incorrect username or password" message I click the `Use an admin account` link then the "Incorrect username or password" message is still displayed above the empty form for the admin credentials
- no distinction for capitals vs small letters in the username - I think this should be fixed as part of https://github.com/learningequality/kolibri/pull/11672
- when we have both the Username and Password fields displayed and I enter the username of a learner who was originally created without a password then it's not accepted as valid credentials and I have to import that learner signed in as an admin. This is probably OK, but just mentioning it here as an edge case in case that could be considered.

**Comment by jredrejo** [comment]
> Hi @jredrejo, I confirm that now the message "Incorrect username or password" is being displayed for not existing learner accounts or mistyped username/password.
> 
> Here's a list with other issues that I am aware of in terms of validation. Perhaps some of those are in scope for this PR, the rest can be fixed separately:
> 
> * there's still no error message displayed if the user attempts to submit an empty form (that's valid both for the learner credentials form and for the admin credentials form)
> * when we have only the 'Username' field being displayed and I enter an admin username then I am still seeing the "Incorrect username or password" - I think in that case we should be showing the `Device limitations` modal
> * if after seeing the "Incorrect username or password" message I click the `Use an admin account` link then the "Incorrect username or password" message is still displayed above the empty form for the admin credentials
> * no distinction for capitals vs small letters in the username - I think this should be fixed as part of [fix: validation #11672](https://github.com/learningequality/kolibri/pull/11672)
> * when we have both the Username and Password fields displayed and I enter the username of a learner who was originally created without a password then it's not accepted as valid credentials and I have to import that learner signed in as an admin. This is probably OK, but just mentioning it here as an edge case in case that could be considered.

hi @pcenov are there open issues for these items? I was not aware of any of these excepting #11540 and want to avoid conflicts with other people work. In case there are not other open issues, please edit #11605 to add this list or create a new one so we can focus and schedule the work because your list is quite overwhelming and means there are quite a lot of problems that can look similar to #11605 but are technically different as most of them are in the frontend not (or not only) in the backend validation.

**Review by pcenov — APPROVED** [review]
Ok, thanks @jredrejo - I have created a follow-up issue as suggested.

**Pull request merged**
