### PR TITLE
Fix issue with "in progress" icon being displayed in guest mode and update icon display logic in ProgressIcon.vue

### LINKED ISSUE #7719: "In progress" (clock) icon should not be shown on the `ContentPage` when viewing content as guest
### Observed behavior

E.g. on https://kolibri-training.learningequality.org/en/learn/#/topics/c/9599f581993e43838f19fe04fdf01af9

(Do not log in, but click the "Explore as guest" link on the Sign In page. Then go to the link again.)

You will see the blue clock icon on the right corner, which is used to indicate that a resource is "in progress" (i.e. started but not finished by the user)

CleanShot 2020-12-08 at 12 44 27@2x

### Expected behavior

This clock icon should not be shown to users who are not logged in and only viewing content as a guest

### Steps to reproduce

1. Use Kolibri as a guest
1. Go to some resource
1. See the clock icon

### Context

Kolibri 0.14.5

### PR DESCRIPTION
**Pull request by alvinhsu-gal220**
### Summary

1. Fix the issue where "in progress" icon will be displayed in guest mode.

**Before**
before_1

**After**
after_1

2. The logic controlling when the icon is displayed in `ProgressIcon` is updated to be the same as the logic in `CardThumbnail`. 

This changes the behavior for signed-in user when a resource is first clicked on. Before this change when a signed-in user views a non-video resource for the first time, the in-progress icon **will be display already**. Now the in-progress icon will be displayed **after second visit**. For video resource, the icon will appear after a few seconds.

### Reviewer guidance

**Test steps for item 1**
1. Use Kolibri as a guest
2. Go to some resource
3. The icon should not be displayed in guest mode 

**Test steps for item 2**
1. Logged on to Kolibri 
2. Go to a non video resource which has not been view before (with no "in progress" icon)
3. The icon should not be displayed. Navigate away from this page.
4. Now navigate back to the same resource. The icon should now be displayed.
5. Go to a video resource which has not been view before (with no "in progress" icon)
6. The icon should not be displayed.
7. Click to play the video. The icon should appear after a few seconds.

### References

#7719 

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jonboiser** [comment]
@alvinhsu-gal220 Could you squash these 4 commits into a single one? This is easy to do on a git GUI or using interactive rebase (slightly harder).

**Comment by alvinhsu-gal220** [comment]
@jonboiser does it help?

**Comment by jonboiser** [comment]
@alvinhsu-gal220 Your commit history is a little messy because of the merge from the previous changes on your `develop` branch (hence the extra merge commit I see). Can you try this?

On your `develop` branch:

1. `git reset --soft d32980e8` to get reset your `develop` branch to the last commit when you forked from us.
2. `git add -A` to stage the changes to the two files
3. `git commit` (then add your commit message)
4. `git push --force` to force update your remote `develop` branch. 

It would make easier for me to check out this branch also if you renamed this branch to something other than `develop` because it clashes with `learningequality/develop`. Usually we name the branches something pertaining to the issue we're fixing like `fix-progress-icon`.

**Comment by alvinhsu-gal220** [comment]
@jonboiser Got it! Sorry for the mess I created here. I just did a clean up and create a branch fix-progress-icon. Is there some way to update this pull request to use the new branch? Or maybe I can just create another pull request with the new branch.

**Comment by jonboiser** [comment]
> @jonboiser Got it! Sorry for the mess I created here. I just did a clean up and create a branch fix-progress-icon. Is there some way to update this pull request to use the new branch? Or maybe I can just create another pull request with the new branch.

You'll have to create a new pull request, unfortunately. If you want, could you simply update `alvinhsu-gal220/develop` with the simplified commit history? I can work around the `develop` branch name conflict for now 😄

**Comment by alvinhsu-gal220** [comment]
@jonboiser I think it should be clean now - thank you for bearing with the mess I created! It's been a while since my last using git - the problem of being spoiled by commercial version control system :p

**Review by jonboiser — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
