### PR TITLE
Add prefer-const linting rule to kolibri-tools

### LINKED ISSUE #9867: Add prefer-const linting rule to kolibri-tools
## Observed behavior
I quite frequently see uses of `let` in cases where the variable will never be reassigned. In this case `const` should be preferred for the variable declaration.

ESLint has a `prefer-const` rule https://eslint.org/docs/latest/rules/prefer-const that has some autofixing capability, so this could be added and any existing usages fixed.

Note it would be best to wait until #9698 has been merged to do this.

### PR DESCRIPTION
**Pull request by akila-i**
## Summary

- New ESLint rule (prefer-const) added
- Errors prompted by prefer-const lint rule are fixed
- performed `npm run lint-frontend`. No errors found.
- PR does not affect the UI

## References

- Issue #9867 
- ESLint documentation : [prefer-const](https://eslint.org/docs/latest/rules/prefer-const)

## Reviewer guidance

- `npm run lint-frontend` to check ESLint rules compliance.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by MisRob — CHANGES_REQUESTED** [review]
Thank you for your contribution, @Akila-I. Code changes are looking good to me.

There's one more step that is needed to fix the codebase and that is running `npm run lint-frontend:format` (automatical fix) and then committing all remaining files (those will be files that didn't need manual fix). I think this should also solve the failing linting check on this pull request.

**Comment by MisRob** [comment]
And just a side note, there's no need to be concerned about the _"Kolibri Build Assets for Pull Request / Build DMG file / build_dmg (pull_request) "_ failing check, it's not related to this PR

**Comment by akila-i** [comment]
Hi @MisRob , changes you requested are made and pushed.

**Comment by MisRob** [comment]
@Akila-I Thank you,I'll have a look soon

**Review by rtibbles — APPROVED** [review]
All changes look correct here!

Please feel free to push another commit here, or add a follow up PR adding yourself to the AUTHORS.md file.

**Comment by akila-i** [comment]
AUTHORS.md updated. sorry had to force push again because I had not have my fork synced with upstream earlier. thanks for the opportunity @rtibbles @MisRob . Looking forward to contribute more to Kolibri.

**Review by MisRob — APPROVED** [review]
Thanks for the updates @Akila-I and for reviewing @rtibbles. I briefly skimmed through the most recent force push and haven't noticed anything suspicious, so I think it's ready for merge. I will wait for @rtibbles to do so because I'm not sure what would be the best timing in regard to one of his linting PRs.

**Comment by akila-i** [comment]
Thanks for the guidance and quick responses @MisRob, If this issue is finished, would love to take part in another contribution. Any suggestions of issues?

**Pull request merged**
