### PR TITLE
[WIP] Pre Class Coaches code cleanup

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

…

### Reviewer guidance

…

### References

…

----

### Contributor Checklist

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] Contributor has fully tested the PR manually
- [ ] Screenshots of any front-end changes are in the PR description
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by indirectlylit** [comment]
@jonboiser @DXCanas  I merged the 0.8 changes into develop, but the PR on this is still too big.

when you guys are done editing I can try to rebase if necessary

**Comment by indirectlylit** [comment]
rebased. please direct future PRs towards develop

**Comment by indirectlylit** [comment]
whoops sorry - didn't realize I was the only one who had commits on this branch

**Comment by DXCanas** [comment]
I think some discussion needs to happen @indirectlylit @jonboiser 
f56a6d4132bafaeb6217465c3d9010a7c9833391
6777d36

**Pull request merged**
