### PR TITLE
Avoid stalling LOD syncs during immediate enqueues and discovery hooks

### LINKED ISSUE #11487: Syncing Android LoDs on 0.16b7
## Observed behavior
Tested syncing with 0.16b7 on Ubuntu 20.04 as a server and 3 Android devices as LoDs ([asset from this build](https://github.com/learningequality/kolibri-installer-android/actions/runs/6724526524)).

1. Set up a server facility, one class with 3 learners, and one lesson ready before proceeding with LoDs setup wizard.
2. Imported the user `a` on the Android 13 phone device, initial sync appeared successful with status on both the learner and coach side reported as _Synced_, however the learner could not see the lesson on the Class home page, not even after the app restart. However after the device reboot and subsequent sync the learner did get to see the lesson on the Class home page, completed the lesson and got it to sync with the server facility. [Android13-user-a-logs.zip](https://github.com/learningequality/kolibri/files/13242887/Android13-user-a-logs.zip)

3. I wanted to confirm if I can replicate the above, so uninstalled and reinstalled the APK on the same Android 13 device, imported the user `b`, and this time the learner did get to see the lesson on the Class home page after the initial sync, and their progress was correctly reported to the Coach. [Android13-user-b-logs.zip](https://github.com/learningequality/kolibri/files/13242947/Android13-user-b-logs.zip)
  
4. On Android 9 device I decided to try the **on-my-own setup**, but got the error 1 below:

1 | 2
-- | --
 | 

I proceeded to clear all data and restarted the setup wizard, this time creating a new Learn-only user `d` on the server facility. All proceeded well, when I assigned the learner to the class, lesson synced on LoD, but the lesson completion by the user was never received on the server facility. Problem here is that apparently the logs are not recorded, as when I connect the device with USB cable, I see the `\android\Android\data\org.learningequality.Kolibri\files` folder empty 😕

Another issue that I noticed is that after syncing the Android 9 device with the user `d`, I was not able to see the successful sync of the Android 13 device with the user `b` anymore.

5. The last device I tested with was the Android 11 tablet. Here I managed to complete the **on-my-own setup** and created the user `e`, then intentionally went to browse remotely the server's library, and completed the two resources that are contained in the server facility's lesson. Afterwards I went on to change and join the server facility. Since the lesson (that had only the two resources that were previously completed by the learner before they joined the facility) was effectively completed, I was not surprised to see it in the reports (pic 2. above, says _3 of 5 completed_), but maybe I expected to see some mention of it in the Class activity panel too...? 🤔 

And again, since the sync with Android 11 tablet began, the previous devices did not manage to complete syncs anymore. I would occasionally see the _Waiting to sync..._ status, but it never manage to complete. I created 2 more quizzes, that successfully synced them with the Android 11 tablet which the user `e` completed and synced back, but neither the Android 13 device with the user `b`, nor the Android 9 device with the user `d` ever got the quizzes, despite several app restarts, devices reboots, and the server restarts on the Ubuntu device.

[Android11-user-e-logs.zip](https://github.com/learningequality/kolibri/files/13243348/Android11-user-e-logs.zip)

[Ubuntu20-server-logs.zip](https://github.com/learningequality/kolibri/files/13243352/Ubuntu20-server-logs.zip)

## Errors and logs

Occasionally I did see this error in the server browser console

```
Error: Could not establish connection. Receiving end does not exist.
```

## Expected behavior
All LoD devices that import/create a user on a facility or join it, should continue to sync with the server when the Kolibri app on them is opened and interacted with.  

## User-facing consequences
Users unable to receive the new assignments and have their progress recorded.

## Steps to reproduce
Try to connect more than one LoD Android device to the server facility and observe if they all continue to sync over time. 

## Context

 * Kolibri version 0.16b7
 * Operating system: Ubuntu 20.04 server, Android 9, 11 and 13 LoDs
 * Browser: Firefox and Chrome

cc @rtibbles @bjester 
@pcenov to try to replicate

### PR DESCRIPTION
**Pull request by bjester**
## Summary

- A python `datetime.timedelta` can be falsy if the time delta is 0, so this ensures we reschedule the LOD syncing tasks when they should be scheduled immediately (in 0 seconds)
- Adds logic to prevent network discovery hooks from interfering with ongoing sync queue scheduling
- Adds tests

## References

Resolves https://github.com/learningequality/kolibri/issues/11487

## Reviewer guidance

1. Have a LOD sync with a server
2. Disconnect the LOD from the network or stop its Kolibri for at least 1 minute
3. Reconnect the LOD and verify it syncs upon connecting

----

## Testing checklist

- [X] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [X] Critical and brittle code paths are covered by unit tests

## PR process

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by jredrejo — APPROVED** [review]
simple and clear, thanks!

**Comment by pcenov** [comment]
Hi @bjester,
Unfortunately twice the build installed on my Android phone got into a state of not syncing which cannot be restarted after both restarting the server and relaunching the app - not sure if these are caused by changes made here or other issues with the app so here are the logs for you to investigate:

[AndroidLogs2.zip](https://github.com/learningequality/kolibri/files/13252275/AndroidLogs2.zip)
[AndroidLogs1.zip](https://github.com/learningequality/kolibri/files/13252276/AndroidLogs1.zip)

Server logs:

[ServerLogs.zip](https://github.com/learningequality/kolibri/files/13252278/ServerLogs.zip)

Logs of a LOD installed on Ubuntu VM that was syncing correctly throughout the entire time:

[UbuntuLearnerLogs.zip](https://github.com/learningequality/kolibri/files/13252284/UbuntuLearnerLogs.zip)

**Comment by rtibbles** [comment]
The last successful run of the sync queue processing job in Android 1 seemed to coincide with the startup of the app:

```
INFO 2023-11-03 09:38:00,313 __main__ Starting Kolibri task worker, for job 50
INFO 2023-11-03 09:38:00,413 kolibri.core.device.soud [user=ff9e4fd916a64b73788dd2e3d782894f] [server=6a40d55608b125e4a9e45fb854476922] SoUD sync ready
INFO 2023-11-03 09:38:00,476 kolibri.core.discovery.utils.network.client Attempting connections to variations of the URL: http://192.168.100.254:8080/
INFO 2023-11-03 09:38:00,478 kolibri.core.discovery.utils.network.client Attempting connection to: http://192.168.100.254:8080/
INFO 2023-11-03 09:38:00,498 kolibri.core.discovery.utils.network.client Success! We connected to: http://192.168.100.254:8080/api/public/info/?v=3
INFO 2023-11-03 09:38:00,982 kolibri.core.auth.management.utils Remotely preparing data
INFO 2023-11-03 09:38:02,779 kolibri.utils.options Option CHERRYPY_THREAD_POOL in section [Server] being overridden by environment variable KOLIBRI_CHERRYPY_THREAD_POOL
INFO 2023-11-03 09:38:02,779 kolibri.utils.options Option DEBUG in section [Server] being overridden by environment variable KOLIBRI_DEBUG
INFO 2023-11-03 09:38:02,780 kolibri.utils.options Option DEBUG_LOG_DATABASE in section [Server] being overridden by environment variable KOLIBRI_DEBUG_LOG_DATABASE
INFO 2023-11-03 09:38:02,780 kolibri.utils.options Option RUN_MODE in section [Deployment] being overridden by environment variable KOLIBRI_RUN_MODE
INFO 2023-11-03 09:38:02,780 kolibri.utils.options Option RESTART_HOOKS in section [Deployment] being overridden by environment variable KOLIBRI_RESTART_HOOKS
INFO 2023-11-03 09:38:02,862 kolibri.core.auth.management.utils No records transferred
INFO 2023-11-03 09:38:03,557 kolibri.core.apps Running Kolibri with the following settings: kolibri_app_settings
INFO 2023-11-03 09:38:04,353 kolibri.core.content.kolibri_plugin Processing content requests for synced dataset: dadee434baef8f7ee819e715c5b9cb9f
INFO 2023-11-03 09:38:04,355 kolibri.core.content.utils.content_request Processing new content assignment requests
INFO 2023-11-03 09:38:04,363 kolibri.core.content.utils.content_request Processing new content removal requests
INFO 2023-11-03 09:38:04,371 kolibri.core.content.kolibri_plugin Completed content requests for synced dataset: dadee434baef8f7ee819e715c5b9cb9f
INFO 2023-11-03 09:38:05,033 kolibri.core.discovery.utils.network.client Unable to connect: http://10.0.2.16/api/public/info/
INFO 2023-11-03 09:38:05,037 kolibri.core.discovery.utils.network.client Attempting connection to: http://10.0.2.16:8008/
INFO 2023-11-03 09:38:05,185 __main__ Starting Kolibri task worker, for job 512a7fb299de43c6bfb4036f150a3ba1
INFO 2023-11-03 09:38:05,278 __main__ Ending Kolibri task worker, for job 512a7fb299de43c6bfb4036f150a3ba1
INFO 2023-11-03 09:38:05,364 kolibri.core.auth.management.utils Locally preparing data to send
INFO 2023-11-03 09:38:07,340 kolibri.core.auth.management.utils No records transferred
INFO 2023-11-03 09:38:07,570 kolibri.utils.server Starting Kolibri 0.16.0b7.dev0+git.2.gfd5b9531
INFO 2023-11-03 09:38:07,684 kolibri.utils.server Bus state: ENTER
INFO 2023-11-03 09:38:07,685 kolibri.utils.server Listening for SIGTERM.
INFO 2023-11-03 09:38:07,686 kolibri.utils.server Listening for SIGHUP.
INFO 2023-11-03 09:38:07,686 kolibri.utils.server Listening for SIGUSR1.
INFO 2023-11-03 09:38:07,686 kolibri.utils.server Listening for SIGINT.
INFO 2023-11-03 09:38:07,687 kolibri.utils.server Bus state: IDLE
INFO 2023-11-03 09:38:07,687 kolibri.utils.server Bus state: START
INFO 2023-11-03 09:38:07,775 kolibri.utils.server Started monitor thread 'ZeroConfPlugin'.
INFO 2023-11-03 09:38:07,775 kolibri.utils.server Started monitor thread 'ProcessControlPlugin'.
INFO 2023-11-03 09:38:07,777 kolibri.utils.server Starting on 0.0.0.0:0
INFO 2023-11-03 09:38:07,878 kolibri.utils.server Waiting for 0.0.0.0:46821
INFO 2023-11-03 09:38:07,880 kolibri.utils.server Serving on 0.0.0.0:46821
INFO 2023-11-03 09:38:07,883 kolibri.utils.server Starting on 0.0.0.0:0
INFO 2023-11-03 09:38:07,984 kolibri.utils.server Waiting for 0.0.0.0:60757
INFO 2023-11-03 09:38:07,994 kolibri.utils.server Serving on 0.0.0.0:60757
INFO 2023-11-03 09:38:08,567 kolibri.utils.server Kolibri running on: http://192.168.100.3:60757/
INFO 2023-11-03 09:38:08,568 kolibri.utils.server Kolibri running on: http://127.0.0.1:60757/
INFO 2023-11-03 09:38:08,568 kolibri.utils.server Kolibri running on: http://10.14.223.72:60757/
INFO 2023-11-03 09:38:08,568 kolibri.utils.server Bus state: RUN
INFO 2023-11-03 09:38:08,825 cherrypy.access 127.0.0.1 - - "GET /app/api/initialize/bac2169d487e448297572e602f79715b" 302 0 "" "Mozilla/5.0 (Linux; Android 13; SM-N770F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.66 Mobile Safari/537.36"
INFO 2023-11-03 09:38:08,837 kolibri.core.discovery.utils.network.broadcast Registering ourselves to zeroconf network with id 'f3d82845104e0b02e36212b0c9e7f7ce' and port '60757'
INFO 2023-11-03 09:38:09,058 cherrypy.access 127.0.0.1 - - "GET /" 302 0 "" "Mozilla/5.0 (Linux; Android 13; SM-N770F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.66 Mobile Safari/537.36"
INFO 2023-11-03 09:38:09,306 __main__ Ending Kolibri task worker, for job 50
```

**Comment by bjester** [comment]
Thanks @pcenov. I've pushed more changes based off what we saw in your Android logs. Could you test again?

**Comment by radinamatic** [comment]
Jumping in for Petar here, it's looking better! 🙂 

1. Lesson1 synced to LoD (Android 13 phone), and progress about completion recorded back on the server side.
2. Lesson2 prepared on server and synced on LoD, but without opening the resources.
3. LoD disconnected from the shared WiFi, Lesson2 completed _offline_ and after 5 minutes LoD reconnected to WiFi. Sync was successful!!! 🎉 

LoD disconnected | LoD reconnected
-- | --
 | 


4. Tried again, (_por si las moscas_, as we say in Spanish), Lesson3 prepared on server and synced on LoD, but without opening the resources.
5. LoD disconnected from the shared WiFi, Lesson3 completed _offline_ and after 5 minutes LoD reconnected to WiFi. Sync was successful again!!! 🎉 

LoD disconnected | LoD reconnected
-- | --
 |

**Comment by radinamatic** [comment]
Attaching the logs, just in case you're curious, but approving asap anyways! [Android13-user-a-logs.zip](https://github.com/learningequality/kolibri/files/13254878/Android13-user-a-logs.zip)

**Review by radinamatic — APPROVED** [review]
LoD restarts the syncing after the disconnecting and connecting again! 🎉 
Merge away! 💯 👏🏽 :shipit:

**Pull request merged**
