### PR TITLE
Re-add search functionality for assigning coaches and enrolling learners

### LINKED ISSUE #9519: Enroll learners/Assign coaches - Missing search bar
## Observed behavior
The search bar at Facility > Classes 'Enroll learners' and 'Assign coaches' has disappeared. It's still there in 0.15.2 so this is a regression caused by a change in 0.15.3. There are no errors in the console. 

## Steps to reproduce the issue
1. Install the official 0.15.3 Kolibri build
2. Go to Facility > Classes
3. Select or create a class 
4. Select 'Enroll learners' or 'Assign coaches'

## Usage Details
Ubuntu 20 - Chrome, Firefox

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary
Re-adds the missing search functionality

## References
Fixes #9519

search-coaches
searching-learner

## Reviewer guidance
Is there anything I missed in the copypasta?

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
Code looks good - let's get manual QA for final sign off.

**Comment by radinamatic** [comment]
While the search field is back and it seems to be working well, something has gone awry with selecting all or just one/few: it's like all are selected by default and no changes can be made 😕 
Happens on both assigning coaches and enrolling learners (CSV I used to import users [51.csv](https://github.com/learningequality/kolibri/files/8952766/51.csv)).

coach

**Comment by radinamatic** [comment]
Ok, selecting is now working again, so I'm going to approve, but I did find one issue (filtered results are not reflected in the pagination) for which at this point I'm not sure if it's regression, so it's probably better if we deal with it in a separate issue/PR... 🤔 

filter-pagination

**Comment by radinamatic** [comment]
Still not seeing the filtering reflected on the pagination numbers 😕 
It's my understanding that in the below case those should change from ``1-30 of 38`` into ``1-10 of 10`` and finally ``0-0 of 0``, with the right arrow being disabled.

Tested in Firefox on Ubuntu 18.04:

pagination

**Comment by radinamatic** [comment]
Oh, yeah, now we are talking (searching, filtering and paginating again)!!! 🎉 

pagination-yes

**Review by radinamatic — APPROVED** [review]
LGTM! 💯 :shipit:

**Pull request merged**
