### PR TITLE
Plugin api final

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
Implements update logic for plugins:
* Tracking external plugin versions
* Running migrations and collectstatic on activation and update
* Running update logic on plugin version change

### Reviewer guidance
Does it work? Does it make sense? What kind of tests do you think it should have?

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by jredrejo — APPROVED** [review]
Tested in different scenarios and they all worked perfectly. I know It's not been an easy path, but this api is robust to allow building external plugins that can add any kind of functionality to Kolibri, with the use of middleware and all the available Django libs and apps. Thanks so much, great work!

**Comment by rtibbles** [comment]
Great, let's merge this, and any other issues that arise can be filed and fixed going forward!

**Comment by benjaoming** [comment]
@rtibbles 

Noticing this and wanted to ask:

1. Should we have documentation consolidated for plugin authors? Should there be an issue open on this?
1. For the changelog, do we want to maybe add this? Entry could be "Plugin API is officially supported. Read the documentation her: ..."

**Comment by rtibbles** [comment]
I don't think we want to officially support it until we hit 1.0 - @jredrego has been doing some good internal dog fooding so far, but I think we probably want to sit down and make sure we are covering sufficient needs at this juncture.

Two things come to mind, the first being that creating a plugin that integrates with the rest of the Kolibri frontend is still a challenge, the second that we haven't had much in the way of external plugin creation in a beta phase.

**Comment by rtibbles** [comment]
We do definitely need documentation though!

**Comment by indirectlylit** [comment]
yeah, "plugin api final" might be a small over-statement :)

**Comment by benjaoming** [comment]
What's a better name for this? Plugin API v. 0.99? Plugin API RFC?

One way to test it would be to start writing the documentation, that makes it easier to test its ability to cope with real world usage :)

**Comment by rtibbles** [comment]
> yeah, "plugin api final" might be a small over-statement :)

THIS WAS THE LAST WORD ON IT!

I think @jredrejo and I can probably cohack on some docs for v0.99 :)

**Comment by jredrejo** [comment]
Who needs documentation having such a good commented code https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/__init__.py#L168 ?  :p

**Comment by benjaoming** [comment]
@jredrejo 

Haven't compiled this docstring code. The `#:` is a notation that works with a Sphinx plugin to add documentation for properties. Since it's not applied to all lines, I'm wondering if it will actually get into Sphinx' apidocs.

Regarding plugin documentation, it definitely needs a tutorial / getting started. I think we should separate out current Plugin documentation and make it a top-level item in our developer docs.

Current docs:

https://kolibri-dev.readthedocs.io/en/develop/backend_architecture/plugins.html#creating-a-plugin

Am thinking we should separate the current single-page work in a way that's aligned with @evildmp's work.

image

So we get a new structure that's friendly towards incremental additions. For instance:

* Kolibri plugins
  * Writing your first plugin
  * How-tos: <= These are just ideas
     * How to adapt Kolibri's navigation
     * How to access content
     * How to change style sheets
     * Add external Python dependencies
     * Dealing with built JS assets
     * Distribute your plugin
  * Background
    * Release plan (LTS)
    * Dependency model
  * Reference
    * Plugin API

**Comment by jredrejo** [comment]
@benjaoming I was joking (while also remarking the code is very well documented). I thought adding the **:p**  at the end of my comment would show it was a joke, but it seems it didn't. Sorry about that.

Of course we need to do a real documentation, with a tutorial if possible. I fully support it. 

For the Python part code documentation almost gives you all the info, but for the JavaScript part it does not and I felt in my skin how hard it could have been if I didn't have a tutor.

**Comment by benjaoming** [comment]
Haha, okay - I didn't see any ill-intentions, but I was a bit unsure if you meant that the code comments were good or bad :)

**Pull request merged**
