### PR TITLE
Navigation issue in Channels

### PR DESCRIPTION
**Pull request by ShivangRawat30**
## Summary

Solved the Navigation issue while importing from an attached drive/local network.

## References

#11187 

## Reviewer guidance

…

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by pcenov — CHANGES_REQUESTED** [review]
Hi @ShivangRawat30, apologies but the expected result mentioned by me in https://github.com/learningequality/kolibri/issues/11187 is incorrect as it states: 'The user should be brought back to Device > Channels'
The actual expected result would be for the user to be brought back to the page they came from. So this should be corrected for all 3 available import options and the scenarios would be:
1. Import from Kolibri Studio (online) > Select resources - clicking the Back arrow should bring the user back to 'Import from Kolibri Studio' modal
2. Import from Local network or internet > Select resources - clicking the Back arrow should bring the user back to 'Import from 'Device' modal
3. Import from Attached drive or memory card > Select resources - clicking the Back arrow should bring the user back to 'Import from 'Drive'' modal

Note that you can actually see the correct navigation flow if you use the browser's Back arrow. Let me know if you have any additional questions and many thanks for your efforts on fixing this!

**Comment by ShivangRawat30** [comment]
Screenshot 2023-09-21 at 3 42 07 PM


@pcenov I think the issue lies in the function `goForwardFromSelectImportSourceModal` because for `LOCAL_DRIVE` and `PEER_KOLIBRI_SERVER` the function should return `availableChannelsPageLink()` with drive link or the address id. Please correct me If I am wrong.

**Comment by radinamatic** [comment]
cc @MisRob ⬆️

**Comment by MisRob** [comment]
@ShivangRawat30 I will have a look at this in the next few days

**Comment by rtibbles** [comment]
@ShivangRawat30 - yes, the function you are referencing should be imported into the component you have already updated, and then passed the drive id or the peer id if available to generate the back route.

It may be a little cumbersome, but to be sure of the correct link, you can make the back computed prop completely explicit, checking against each of the cases - similarly to how the app bar title is generated:

https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/plugins/device/assets/src/views/SelectContentPage/index.vue#L158

If it's Kolibri Studio, you can just call the function with no arguments to get the link, if it's peer import mode, you should pass the `addressId` parameter, if it's in import from drive mode, the `driveId` parameter.

**Comment by ShivangRawat30** [comment]
Hey @rtibbles I am having some trouble getting the `drive_Id` and  `address_id` from the vue store to use as params for the `showAvailableChannelsPage` function, please correct me If I am on the wrong path. 

Screenshot 2023-09-29 at 5 19 49 PM
Screenshot 2023-09-29 at 5 23 17 PM

**Comment by rtibbles** [comment]
That looks right - if you are in peerImport mode the `selectedPeer` should be a non empty object, that should have an id property that you can read from (see here where it is read in the same file: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/plugins/device/assets/src/views/SelectContentPage/index.vue#L262) 

If you are in localImport mode then `selectedDrive` should be a non empty object, that should have an id property. (see here: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/plugins/device/assets/src/views/SelectContentPage/index.vue#L270)

These then need to be passed with the appropriate key to the options object for the `availableChannelsPageLink` function: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/plugins/device/assets/src/views/ManageContentPage/manageContentLinks.js#L19

So, either `addressId` or `driveId`.

**Comment by ShivangRawat30** [comment]
@rtibbles please have a look at the changes. 🙂

**Review by rtibbles — COMMENTED** [review]
This looks like the right change to me! @pcenov could you confirm that the issue is fixed?

@ShivangRawat30 looks like there are two linting errors to take care of, removing the unused import of `ContentWizardPages` and returning something from the `backRoute` computed prop. I would suggest just returning `availableChannelsPageLink()` after the if statements to ensure a value is always returned.

**Review by pcenov — APPROVED** [review]
Manual QA passes! Thank you @ShivangRawat30!

**Review by rtibbles — APPROVED** [review]
Changes make sense, manual QA checks out, we're ready to go! Thanks for the work on this, @ShivangRawat30 !

**Pull request merged**
