### PR TITLE
Bump morango to v0.6.10

### LINKED ISSUE #9139: NotNullViolation when trying to import a learner account
## Observed behavior

When trying to sync a learner account from a Kolibri 0.15.1 server with a Postgres backend, to the learner's app (Android or Windows) 0.15.1, it fails.
Last 2 things I see in the Android app are - 
`Remotely preparing data` followed by `2 of 7: Failed`

No facility imports are working when using this upgraded server as the source. They were working at least prior to upgrade to 0.15.x. I am not sure if they were even working after having upgraded to 0.15.0.

## Errors and logs

This is what's present in kolibri.log -
```
ERROR 2022-02-24 11:35:54,204 morango.sync.controller null value in column "transfer_stage_status" violates not-null constraint
DETAIL:  Failing row contains (0f15bf12-fa38-45e8-ac38-2e87de12c6af, 156205118be9ebea414630547bd83133:user-rw:d777ca55f496ac49861b210..., f, t, null, fe3e0240-e835-4e6e-ad8c-e6f77987aa1b, 2022-02-24 06:05:54.182339+00, {"super": {}, "sub": {}}, 0, {}, 2022-02-24 06:05:54.182318+00, 0, 0, initializing, null).

ERROR 2022-02-24 11:35:54,290 django.request Internal Server Error: /api/morango/v1/transfersessions/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/operations.py", line 776, in handle
    transfer_session = transfer_sessions.get(**data)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
morango.models.core.DoesNotExist: TransferSession matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "transfer_stage_status" violates not-null constraint
DETAIL:  Failing row contains (0f15bf12-fa38-45e8-ac38-2e87de12c6af, 156205118be9ebea414630547bd83133:user-rw:d777ca55f496ac49861b210..., f, t, null, fe3e0240-e835-4e6e-ad8c-e6f77987aa1b, 2022-02-24 06:05:54.182339+00, {"super": {}, "sub": {}}, 0, {}, 2022-02-24 06:05:54.182318+00, 0, 0, initializing, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3/dist-packages/kolibri/dist/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/lib/python3/dist-packages/kolibri/dist/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/api/viewsets.py", line 392, in create
    raise context.error
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/controller.py", line 236, in _invoke_middleware
    result = middleware(context)
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/registry.py", line 227, in __call__
    result = operation(context)
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/operations.py", line 719, in __call__
    result = self.handle(context)
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/operations.py", line 804, in handle
    transfer_session.save()
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/query.py", line 1079, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "transfer_stage_status" violates not-null constraint
DETAIL:  Failing row contains (0f15bf12-fa38-45e8-ac38-2e87de12c6af, 156205118be9ebea414630547bd83133:user-rw:d777ca55f496ac49861b210..., f, t, null, fe3e0240-e835-4e6e-ad8c-e6f77987aa1b, 2022-02-24 06:05:54.182339+00, {"super": {}, "sub": {}}, 0, {}, 2022-02-24 06:05:54.182318+00, 0, 0, initializing, null).

```

[Full kolibri.txt also herein](https://github.com/learningequality/kolibri/files/8130167/kolibri.txt)

## Expected behavior

The import should have worked without any errors.

## User-facing consequences

Unable to use the app.

## Steps to reproduce

Had upgraded this server from 0.14.x to 0.15.0 a few days ago and now to 0.15.1 .
Installed the "early access" Android app from play store and attempted to import.

## Context

kolibri-server 0.4.0
kolibri 0.15.1
Ubuntu 18.04.3
Postgres 12.3
Kolibri Android app or Windows app 0.15.1 
Python 3.6.9
Server  nginx/1.14.0 (Ubuntu)

### PR DESCRIPTION
**Pull request by bjester**
## Summary

- Upgrades morango version to v0.6.10 containing [these fixes](https://github.com/learningequality/morango/pull/154)

## References

- https://github.com/learningequality/morango/pull/154
- Fixes https://github.com/learningequality/kolibri/issues/9139

## Reviewer guidance

1. Set up a Debian/Ubuntu VM
```bash
sudo apt install postgresql python3-psycopg2
wget "https://github.com/learningequality/kolibri/releases/download/v0.15.0/kolibri_0.15.0-0ubuntu1_all.deb"
sudo apt install ./kolibri_0.15.0-0ubuntu1_all.deb
sudo su postgres -c psql
# Run the following SQL
CREATE DATABASE kolibri;
CREATE ROLE kolibri WITH LOGIN PASSWORD 'kolibri';
GRANT CONNECT ON DATABASE kolibri TO kolibri;
\c kolibri
GRANT ALL PRIVILEGES ON SCHEMA public TO kolibri;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA public TO kolibri;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO kolibri;
# end SQL
```
2. Edit `~/.kolibri/options.ini`:
```bash
[Database]
DATABASE_ENGINE = postgres
DATABASE_NAME = kolibri
DATABASE_PASSWORD = kolibri
DATABASE_USER = kolibri
DATABASE_HOST = 127.0.0.1
DATABASE_PORT = 5432
```
3. Restart Kolibri
```bash
sudo systemctl restart kolibri.service
```
4. Open a web browser and proceed through setup wizard (if running a headless VM, you'll probably need to add port forwarding from your host to the VM)
5. On the VM, upgrade Kolibri
```bash
wget "https://github.com/learningequality/kolibri/releases/download/v0.15.1/kolibri_0.15.1-0ubuntu1_all.deb"
sudo apt install ./kolibri_0.15.1-0ubuntu1_all.deb
```
6. Check the transfer table:
```bash
sudo su postgres -c 'psql -c "\d morango_transfersession" kolibri' | grep transfer_stage
```
7. You should see the issue, that the column fields are `not null`
8. Install this change
```bash
wget -O pr.deb "https://buildkite.com/organizations/learningequality/pipelines/kolibri-debian/builds/3904/jobs/1d46cbf9-3319-4a3b-a261-ff6d6bba66e1/artifacts/6df892fe-6cad-490c-a5a9-12a92268b2c8"
sudo apt install ./pr.deb
```
9. Check the transfer table:
```bash
sudo su postgres -c 'psql -c "\d morango_transfersession" kolibri' | grep transfer_stage
```
10. The columns should no longer be `not null`
----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [x] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
Hrm - I don't actually see any replication at step 6, I think because the TransferSession table is empty. Will attempt to put some records in on Monday.

**Comment by bjester** [comment]
@rtibbles The command at step 6 I shared should describe the table's schema so no data should be required.

**Comment by rtibbles** [comment]
Ah, I probably forgot to install latest postgresql, as I took a slight shortcut and tested this outside of a VM.

**Comment by rtibbles** [comment]
On a fresh VM was able to replicate and confirm. For posterity, it required one more restart after the installation of the PR asset.

**Review by rtibbles — APPROVED** [review]

**Pull request merged**
