### PR TITLE
Fix to new badge being shown on channel delete

### LINKED ISSUE #6730: New icon is shown in channel when a resource was deleted.
### Observed behavior
When a resource is deleted, there is a New icon shown in the channel name.

This "New" icon is removed when the `Clear completed` link is clicked.

kolibri-v0 13 2-b1--deleting a resource puts a New icon in a channel

### Expected behaviour
Show a different icon when a resource is deleted in a channel.  The New is more for new (or updated) contents.

### User-facing consequences
The New icon is confusing with the delete action.

### Steps to reproduce
1. Install [Kolibri v0.13.2-beta1](https://github.com/learningequality/kolibri/releases/tag/v0.13.2-beta1) in Ubuntu 16.04.6 VM
1. Use Firefox then import a channel
1. Delete a resource within the topic tree of the channel.  Follow this [Gherkin scenario](https://github.com/learningequality/kolibri/blob/release-v0.13.x/integration_testing/features/super-admin/super-admin-delete-channel.feature#L45) for an example.
1. After the resource is deleted, DO NOT click the `Clear` or `Clear completed` buttons.
1. Click the `X` button to leave the task manager immersive modal.
1. Notice the "New" icon in the channel name.

### Fix Acceptance Criteria (added by @nucleogenesis )

- [ ] Add "Updated" label and string
- [ ] Ensure that the label is not hidden when the task is cleared

### Context
 
* Kolibri version: [Kolibri v0.13.2-beta1](https://github.com/learningequality/kolibri/releases/tag/v0.13.2-beta1)
* Operating system: Ubuntu 16.04.6 VM (2GB RAM, 2CPUs, 64GB disk)
* Browser: Firefox v74.0

### PR DESCRIPTION
**Pull request by thesujai**
## Summary

The cause of the bug is well addressed in https://github.com/learningequality/kolibri/issues/6730#issuecomment-1870973735

For handling that we will show `new` badge based on the latest task which will be the task with highest scheduled_datetime(among the tasks with same channel_id)
**Screencast**
Here I delete resource initially(shows no `new` badge)
Then install more resource(shows `new` badge as it should)
Then remove a resource(shows no `new` badge, as it shouldn't)
[Screencast from 28-12-23 04:11:18 PM IST.webm](https://github.com/learningequality/kolibri/assets/120925871/717af862-dcde-4d15-a3b9-935450f90a0c)

…

## References

Fixes #6730 
…

## Reviewer guidance

…

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by rtibbles — COMMENTED** [review]
Code changes look fine - @pcenov could you verify the fix? It seems that the key to replication is to have imported some resources, and then to have deleted a resource without having cleared the import task.

**Comment by rtibbles** [comment]
@thesujai this is great, could you retarget to release-v0.16.x and rebase to that branch too? We can release this in a patch release to 0.16.

**Comment by thesujai** [comment]
Hey @rtibbles 👋🏽 
🚀 Changes are now targeted for release-v0.16.x and rebased onto it. Ready to roll for a patch release to 0.16!
Check it out and let me know if tweaks are needed.

**Comment by pcenov** [comment]
@rtibbles I confirm that this is implemented as specified, passes manual QA. Thank you @thesujai!

**Comment by rtibbles** [comment]
Thanks @thesujai - looks like this is ready to go. We'll hold off merging until 0.16.0 has been released, but no more work needs to be done here!

**Review by rtibbles — APPROVED** [review]
Actually, we changed our minds, and this is safe enough to merge for 0.16.0, thank you for your contribution!

**Pull request merged**
