### PR TITLE
Develop -> Style guide

### PR DESCRIPTION
**Pull request by christianmemije**
## Summary

* Develop -> Style guide

### CODE REVIEW

**Comment by rtibbles** [comment]
Linting error: `./kolibri/core/assets/src/router.js did not conform to prettier standards`

**Comment by indirectlylit** [comment]
much merge.

testing now

**Comment by rtibbles** [comment]
It was Travis wot saw it! 

Possible that you are having the same issue that @jonboiser reported, where the glob expansion works differently on Mac.

**Comment by indirectlylit** [comment]
[glob expansion](http://i.imgur.com/aODZSj5.gifv), eh?

**Comment by rtibbles** [comment]
Something like that, Mac OS is expanding some globs prematurely, and missing some paths in the process. There is a fix, will try to get it propagated soon!

**Pull request merged**
