### PR TITLE
Improved strings formatting in modals.

### PR DESCRIPTION
**Pull request by radinamatic**
### Summary
At first I was filing an issue, but then decided to plunge in myself... 😝 

### Reviewer guidance
Should be painless, some formatting for consistency and improved wording.

#### Before
selection_278

#### After
selection_279

#### Before
selection_276

#### After
selection_277

#### Before
selection_280

#### After
selection_282

### Contributor Checklist

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] Contributor has fully tested the PR manually
- [x] Screenshots of any front-end changes are in the PR description
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

cc @indirectlylit @christianmemije @jonboiser

### CODE REVIEW

**Comment by indirectlylit** [comment]
Unfortunately, we can't do this because use of the `v-html` directive is a [security risk](https://vuejs.org/v2/guide/syntax.html#Raw-HTML): any html or javascript gets inserted without sanitation.

 Instead, we've been using single quotes to delimit names of objects created by users. 

Recommend updating these to, e.g.:

> Are you sure you want to delete 'aygarrett'?

**Comment by radinamatic** [comment]
Ok, I understand the security concerns, does that mean that we have to remove all the instances of `v-html` in these modals? Class names are also "user provided content"...

**Comment by indirectlylit** [comment]
>  does that mean that we have to remove all the instances of v-html in these modals?

Yes, unfortunately that will be necessary.

You're welcome to take a swing at it, or if you'd like to pass it off I'm happy to take care of it.

**Comment by radinamatic** [comment]
Oh, I definitely want to take a swing at it, just making sure... 😛 

So it's just single quotes instead of bold formatting everywhere there is user-provided content?

**Comment by indirectlylit** [comment]
Right. The more general rule is that we can't (currently) do any kind of text formatting _inside_ of a translated string.

**Comment by indirectlylit** [comment]
Also, just a heads-up that there are some conflicts on this branch. You may find it easier to start from scratch.

**Comment by radinamatic** [comment]
Thanks, will try to resolve first, and start from scratch if necessary! 🙂

**Comment by radinamatic** [comment]
@indirectlylit [This](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/views/groups-page/delete-group-modal.vue#L8), for example, does not involve `v-html`. Does it carry any other security risk or can potentially be used instead of it?

**Comment by indirectlylit** [comment]
> can potentially be used instead

Nope, that construction violates the rule that all translation strings must be meaningful, self-contained phrases: we can't "construct" phrases in HTML because it imposes a certain ordering of the words.

In this case we need to turn the `learnersWillBecome` and `ungrouped` strings into a single `learnersWillBecomeUngrouped` string.

**Comment by radinamatic** [comment]
> all translation strings must be meaningful, self-contained phrases

Makes total sense, my stubbornness got better of me... 😒 

Let's close this as the new changes are coming into #3066.

**Pull request closed without merging**
