### PR TITLE
Coach group and lessons fixes

### LINKED ISSUE #4944: TypeError: _addMultipleUsersToGroup
### Observed behavior

Still seeing [this issue](https://github.com/learningequality/kolibri/pull/4934#issuecomment-460874204) when assigning learners to group, **but only in Firefox**, in Chrome it works OK... 😕 

Enrolling learners into the newly created group throws an error, but if I use the back arrow button, the group is listed correctly with the chosen learners.

### Expected behavior

No error, ability to see the added learners without using the back button

### User-facing consequences

Confusion.

### Errors and logs

```
TypeError: _addMultipleUsersToGroup(...).catch(...).finally is not a function[Learn More] actions.js:136
```

### Steps to reproduce

1. Create a class & enroll learners
2. Create group and try to enroll learners

### Context

 * Kolibri version: `release-v0.12.x` dev branch
 * Operating system: Ubuntu 18.04
 * Browser: Firefox 65

cc @rtibbles @indirectlylit

### LINKED ISSUE #4945: Pressing *Finish* button does not close the *Manage resources in...* when editing lesson
### Observed behavior

Following up on [this issue](https://github.com/learningequality/kolibri/pull/4934#issuecomment-460874204) navigation isn't blocked as before, but once the resources are added, pressing *Finish* does nothing. When the page is closed with the *X* in the upper left corner, lesson seems OK, and added resources display correctly. **Happens both in Firefox and Chrome**.

### Expected behavior

Ability to finish managing resources and see the lesson page again.

### User-facing consequences

Apparent block and confusion.

### Errors and logs

Nothing notable in the console or the terminal that I can see...

### Steps to reproduce

Create lesson, add some resources and press **Finish**.

### Context

 * Kolibri version: `release-v0.12.x` dev branch
 * Operating system: Ubuntu 18.04
 * Browser: Firefox 65, Chrome 70.0.3538.77

cc @rtibbles @indirectlylit

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
The Promise finally polyfill did not fix an issue with enrolling users (either because it wasn't being applied, or because something strange is happening with our conditional promises in firefox).
Either way, it was simpler to just not use finally, as it is just syntactic sugar.

The recent fix to make search escaping in #4929 caused a regression which prevented the `Finish` button on lesson resource selection from exiting from the selection screen. This fixes that by adding an additional condition to the route handling.

### Reviewer guidance
Check that you can enroll users in groups in Firefox without errors showing.
Check that you can add resources to a lesson and then click 'Finish' to return to the lesson detail page.

### References
Fixes #4944.
Fixes #4945.

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Review by jonboiser — APPROVED** [review]

**Comment by jonboiser** [comment]
There are still some uses of finally in heartbeat.spec.js.

**Comment by rtibbles** [comment]
Yeah, that was intentional, it's convenient for testing code, and is not an issue in the JSDOM environment.

**Comment by radinamatic** [comment]
Fix works fine on Firefox! 👍 

One thing I noticed is that the snackbar now appear twice when adding the resources to the lesson: first when added (as supposed), and then again after the *Finish* button is pressed (not necessary)... 😕

**Comment by indirectlylit** [comment]
> One thing I noticed is that the snackbar now appear twice when adding the resources to the lesson: first when added (as supposed), and then again after the _Finish_ button is pressed (not necessary)...

@radinamatic would you mind opening an issue for this

**Pull request merged**
