### PR TITLE
Changed KContentRenderer to ContentRenderer.

### PR DESCRIPTION
**Pull request by ShivangRawat30**
## Summary

This PR Renames the `KContentRenderer` to `ContentRenderer`.

## References

#11282 

## Reviewer guidance

…

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by AllanOXDi — APPROVED** [review]
LGTM!

**Comment by rtibbles** [comment]
Retargeting to develop to avoid last minute changes in release.

**Review by rtibbles — CHANGES_REQUESTED** [review]
This has not updated the name of the KContentRenderer component file:
https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/assets/src/views/ContentRenderer/KContentRenderer.js
Ideally this file would be renamed to `index.js`

Updates are also needed to references to it here: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/assets/src/core-app/index.js#L16

With the above rename, the import can be changed to:

```
import ContentRenderer from '../views/ContentRenderer';
```

**Comment by ShivangRawat30** [comment]
@rtibbles I have made the requested Changes, kindly review them.

**Review by rtibbles — APPROVED** [review]

**Pull request merged**
