### PR TITLE
Allow untranslated headers in csv + correct serialization into json

### LINKED ISSUE #9032: Importing users in facility using a csv file doesn't work if there are errors
## Observed behavior
In Facility -> Data -> Import users, when the csv file is correct, everything works fine. However, if the csv file has errors, the errors notification is completely broken after the changes in the task system done in 0.15. 
This problems have been seen when the kolibri/core/auth/management/commands/bulkimportusers.py command is used:
- `self.job.extra_metadata["overall_error"] = self.overall_error` does not work if the error is not serializable
- `raise CommandError` does not produce a right termination of the command

## Errors and logs

```
....
  File "/datos/le/mio/kolibri/kolibri/core/auth/management/commands/bulkimportusers.py", line 852, in handle_async
    self.exit_if_error()
  File "/datos/le/mio/kolibri/kolibri/core/auth/management/commands/bulkimportusers.py", line 769, in exit_if_error
    self.job.save_meta()
  File "/datos/le/mio/kolibri/kolibri/core/tasks/job.py", line 244, in save_meta
    self.storage.save_job_meta(self)
  File "/datos/le/mio/kolibri/kolibri/core/tasks/storage.py", line 287, in save_job_meta
    self._update_job(job.job_id, extra_metadata=job.extra_metadata)
  File "/datos/le/mio/kolibri/kolibri/core/tasks/storage.py", line 300, in _update_job
    orm_job.saved_job = job.to_json()
  File "/datos/le/mio/kolibri/kolibri/core/tasks/job.py", line 178, in to_json
    raise TypeError(
TypeError: Job objects need to be JSON-serializable: Object of type __proxy__ is not JSON serializable
```

```
....
  File "/datos/le/mio/kolibri/kolibri/core/auth/management/commands/bulkimportusers.py", line 852, in handle_async
    self.exit_if_error()
  File "/datos/le/mio/kolibri/kolibri/core/auth/management/commands/bulkimportusers.py", line 770, in exit_if_error
    raise CommandError("File errors: {}".format(str(self.overall_error)))
django.core.management.base.CommandError: File errors: ['Incorrect header label found in the first row']


```

## Expected behavior
Transfer of data from the task to the front end should be ok

## User-facing consequences
The user can not know why importing is failing

## Steps to reproduce
This file can be  used to import, as it's incorrect:
[bec-list-test.csv](https://github.com/learningequality/kolibri/files/7927096/bec-list-test.csv)
In 0.14.x the browser will show the problems found. In 0.15 nothing is shown, the spinning wheel never stops

## Context
kolibri 0.15

### PR DESCRIPTION
**Pull request by jredrejo**
## Summary
This PR fixes three different problems found when importing users using a csv file from kolibri:

1. Changes in 0.15.x required json for the job serialization and some error messages from the importer where not json serializable
2. The importer always requires () in the header field names. This was done to allow translation of columns but didn't make sense if the language of the user is English
3. Force the use of utf-8 when opening the csv to count the lines to avoid charset problems in Windows

## References
Fixes: #9032 , #9034, #9060 

## Reviewer guidance
* In Facility->Data import a csv with errors, the errors list should be correctly visible in the browser
* Import a valid csv file without parenthesis in the colums, as this one, and it should be correctly imported:
[bec-list-test.csv](https://github.com/learningequality/kolibri/files/7935807/bec-list-test.csv)
* Import a valid csv with some columns translated as this one, and it should be correctly imported:
[bec2.csv](https://github.com/learningequality/kolibri/files/7935818/bec2.csv)

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
@pcenov Could you do the manual QA for this tomorrow? Thank you!

**Comment by pcenov** [comment]
Hi @jredrejo importing the above mentioned bec-list-test.csv and bec2.csv files is working correctly. Exporting a CSV file and importing it is also functional.
However when I changed the UI language to Greek, exported a CSV file, added a valid new line with the data for a new user and attempted to import it I get the Loading... screen and the import never finishes. There's no indication what is the problem and no error in the console. Restarting Kolibri doesn't solve the issue and it keeps saying Loading.... 
I'm able to consistently replicate the issue for example by switching to Bulgarian language, generating a CSV, downloading it and directly attempting to import it without making any changes to the file.
Note that the same scenarios work correctly with the default English UI or the language changed to Spanish, so my guess is that there is an issue with non-Latin languages.
Here are the csv files:
[greek.csv](https://github.com/learningequality/kolibri/files/7951324/greek.csv)
[bul.csv](https://github.com/learningequality/kolibri/files/7951424/bul.csv)
The entire .kolibri folder:
[kolibri.zip](https://github.com/learningequality/kolibri/files/7951430/kolibri.zip)
Update: Attempting to import the greek csv file while viewing Kolibri in English does produce an error page which is:

**Comment by jredrejo** [comment]
hi @pcenov  I'm not sure if this is the same issue this PR is trying to fix.
Actually I'm not sure this is a kolibri issue, it looks like it's a problem with windows charsets that I'm not sure how to reproduce (did  you have the server and the browser in the same machine? if you did what are the versions for the  OS and the browser)

I have tried the files you attached and this is what I see (I use Linux). For the `bul.csv`:
image


For the `greek.csv`:
image

and clicking on `Import`:
image

The behaviour and the error messages are correct, and kolibri imports what it can import.

Please, if you are consistently having these issues I think creating a different issue with all the information to try to reproduce it would be better, as it does not seem to be related with this PR (I bet you have the same results on any previous kolibri version)

**Comment by pcenov** [comment]
Hi @jredrejo, after further investigation I confirm that this is a Windows only problem so I will report it as a separate issue.

**Comment by jredrejo** [comment]
> Hi @jredrejo, after further investigation I confirm that this is a Windows only problem so I will report it as a separate issue.

Thanks @pcenov , so @rtibbles  or @marcellamaki this PR is on you to review the code so this fix can enter into 0.15.1

**Comment by jredrejo** [comment]
Added fix for #9060  here so we have all the csv importing fixes merged at once

**Comment by pcenov** [comment]
Retested with the latest build assets on Windows 10, Win 7 and Ubuntu and this time all is working correctly and as expected. Tested also various combinations of OS interface language and Kolibri UI in latin and non-latin languages and also no issues this time around - both csv export and import are functioning correctly.

**Review by radinamatic — APPROVED** [review]
Manual QA passed, let's get the code reviewed, and this is good to go! 👏🏽 💯

**Review by marcellamaki — APPROVED** [review]

**Comment by marcellamaki** [comment]
Not sure about the python test issue -- maybe this is one that is an underlying problem? Otherwise looks fine to me

**Comment by jredrejo** [comment]
@marcellamaki yep, test errors are due to our CI changes that are not working correctly with GH (yet)

**Pull request merged**
