### PR TITLE
Fix height calculation of `FullScreenSidePanel`

### LINKED ISSUE #9271: `FullScreenSidePanel` Error calculating the container height
## Observed behavior

When I want to preview the information of a resource in `FullScreenSidePanel`, if the content in the panel is higher than the viewport, a part of the content is hidden.

HiddenContent

## Errors and logs

None

## Expected behavior

The FullScreenSidePanel shows all the content with some padding below.

## User-facing consequences

Users might not see some related resources that might be of interest to them. In addition, users will see that the information is cut and without any padding, which affects the UX.

## Steps to reproduce

1. Log in.
2. Go to Learn section.
3. Click on "View information" of any resource whose information on the side panel is higher than the viewport (e.g. Ciensación channel > Física > Respirando Agua).

## Context
* Kolibri version: 0.16.0a4.dev0
* Operating system: Ubuntu 20.04
* Browser: OperaGX.

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Summary

The height of FullScreenSidePanel was being miscalculated since when `fixedHeaderHeight` was set, it already included the "px" units, but when inserting it into the inline styles to calculate the height of FSSP, it was putting the units again. 

This PR fix that removing the repeated units, and setting the initial value of `fixedHeaderHeight` with the units to avoid having inconsistent values like `calc(100vh - 0)`.

### Before:

HiddenContent

### After:

HiddenContent_solved

## References

Fixes #9271 

## Reviewer guidance

1. Log in.
2. Go to Learn section.
3. Click on "View information" of any resource whose information on the side panel is higher than the viewport (e.g. Ciensación channel > Física > Respirando Agua).

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by MisRob** [comment]
Thank you for your contribution @AlexVelezLl :) I will assign myself and make a review later today.

**Comment by AlexVelezLl** [comment]
Thanks @MisRob ! :). Sorry that I didn't add a Tag, this is my first PR and the button to manage tags didn't appear.

**Comment by MisRob** [comment]
@AlexVelezLl Ah, it will be something with permissions. No worries, I will do that.

**Comment by MisRob** [comment]
Thank you @AlexVelezLl. Everything is looking good to me and I can confirm that the sidebar works as expected now.

We've noticed that this bug is present on our release branch as well, so I will soon open a PR targeting our release branch with this commit cherry-picked so your fix can be released in the upcoming patch ;)

**Review by MisRob — APPROVED** [review]

**Pull request merged**
