### PR TITLE
Add user interface for customizing the Kolibri device name

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary
1. Adds field and modal at Device > Info page device name
1. Adds code to synchronize the zeroconf cache with the `DynamicNetworkLocation` table when new device info comes from peers.

Screen Shot 2020-04-02 at 3 25 36 PM

### Reviewer guidance

1. Verify that the UI matches the design and has the correct behavior for happy and sad paths.
1. Bonus: test out the name changing with another computer to verify name changes are propagated to peers in real-time.

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by lyw07** [comment]
everything looks good! I tested, and the static addresses issue has been fixed!  🎉
just one small question after I went over the technical design in the notion doc:
> peers will immediately see that new name when opening import/export or other p2p-related menus.

in the PR, we don't get to see the new name immediately after peers open the import/export modal. Instead, peers have to wait for several seconds to let the server connect to the `public/info` api to access the new name. just would like to double-check if we would be okay with this. Thank you!

**Comment by jonboiser** [comment]
Yeah, seeing the name update after a _small_ delay is acceptable as long as it does change eventually!

**Comment by lyw07** [comment]
sounds good! thank you for the confirmation!

**Review by lyw07 — APPROVED** [review]
LGTM!

**Pull request merged**
