### PR TITLE
Username validation

### LINKED ISSUE #11540: Setup Wizard > LOD > Import user - Missing validation for uppercase in the usernames and passwords
## Observed behavior

Initially I thought that the import of a learner from the server to the LOD is not functioning anymore after the latest changes in https://github.com/learningequality/kolibri/pull/11525. In reality both the username and the password of the learner I was trying to import were in uppercase while I was inputting them in lowercase. Therefore the issue is about the proper validation for uppercase.

https://github.com/learningequality/kolibri/assets/79847249/65406d93-2b36-48bf-8162-98d213bb6d5a

## Expected behavior

The user should see validation for incorrect username and password. This should be fixed for both the learner credentials form and the admin credentials form.

## Steps to reproduce the issue
1. Install the [latest Beta 8 build asset](https://github.com/learningequality/kolibri/pull/11525).
2. Setup a server device with learners and assigned lessons.
3. On a separate device start the setup wizard and attempt to import an individual learner through the learn-only device user flow by inputting either the password or the username in incorrect letter case.

## Logs

https://drive.google.com/drive/folders/1OImtokSocwqMa84Yv4acDRn8e8uylv91

## Usage Details
Ubuntu 22  - Chrome, Android 13

### PR DESCRIPTION
**Pull request by nick2432**
## Summary

- Modified the `FacilitySearchUsernameViewSet` to use `username__iexact` for case-insensitive username search.
- Updated the SET_FIRST_LOD action in the handleSubmit method to use the username from the task.extra_metadata instead of the component's this.username. This change ensures that the correct username is set when initializing the firstImportedLodUser in the wizard context

…

## References

Fixes https://github.com/learningequality/kolibri/issues/11540

## Screenshots
I created a user "cincO" and logged in with the username "cinco," and it worked
Uploading 2024-01-19 16-33-50.mp4…

…

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by jredrejo — CHANGES_REQUESTED** [review]
Hello @nick2432 I don't think that `DeviceProvisionSerializer` is the proper place to do this.  In the related issue this PR tries to fix there's a comment from @rtibbles 
suggesting to do it in the public api that responds with the data of the username if it exists  https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/public/api.py#L360 
That's a safer place in the code (it does not create anything) and covers a more general case than the device provisioning (more users could be synced in the future not being superusers so you would not find them)

**Review by jredrejo — CHANGES_REQUESTED** [review]
Hello @nick2432 
I'm afraid this is not working properly because the frontend is not using the username info this api provides, but the username the user typed in the text input. For this reason, the last post the frontend does to the server is not using the right capitalization but the wrong the user typed.

This is the last endpoint the setup uses:
/api/device/deviceprovision/

in my tests, the username was `cincO` and with your api changes, it's correctly returned, but you can see the payload of the endpoint POST has not it corrected:  
`  {"facility_id":"440eb55977625f4e82f1e9eef75769db","superuser":{"username":"cinco","password":"NOT_SPECIFIED"},"settings":{"on_my_own_setup":false},"preset":"nonformal","language_id":"en","device_name":"ddd","allow_guest_access":false,"is_provisioned":true,"is_soud":true}`
So this is is the response to the browser:
`  {"detail":"`username`, `password`, or `full_name` are missing in `superuser`"}`

I understand this is the reason why you modified the provisioning serializer first, but, as previously mentioned, that didn't solve a general case. I'm afraid this issue requires both backend and frontend work to be finished. Please let us know if you need help with the frontend or you can achieve it.
Thanks!

**Comment by nick2432** [comment]
@jredrejo ,
I will try it.

**Comment by nick2432** [comment]
Hey, @jredrejo , please check out my latest changes.

**Review by jredrejo — APPROVED** [review]
Great work @nick2432

**Comment by pcenov** [comment]
Hi @nick2432 and @jredrejo I just tried this and I am still getting an error when trying to import a learner with the incorrect letter case in the username. My question is - since this was merged without requiring any QA verification - is this a partial fix of the issue described in https://github.com/learningequality/kolibri/issues/11540?

https://github.com/learningequality/kolibri/assets/79847249/47ab98c0-0ba0-4a40-a69e-520817f1b865

**Comment by jredrejo** [comment]
> Hi @nick2432 and @jredrejo I just tried this and I am still getting an error when trying to import a learner with the incorrect letter case in the username. My question is - since this was merged without requiring any QA verification - is this a partial fix of the issue described in #11540?
> 
>  2024-01-23_15-46-57.mp4

 @pcenov do you mean you want the password to be accepted when capitalization does not match? that's not possible. This PR fixes username validation when capitalization does not match.
In this  new screencast I see other error messages that are not the described in #11540.  If there are other validation issues that are not included in the validation follow up issue #11711 , please add them there, so everything can be done at once.

**Comment by nick2432** [comment]
> Hi @nick2432 and @jredrejo I just tried this and I am still getting an error when trying to import a learner with the incorrect letter case in the username. My question is - since this was merged without requiring any QA verification - is this a partial fix of the issue described in #11540?
> 
>  2024-01-23_15-46-57.mp4

Hey @pcenov , I believe it's not a case issue. It's not working with both capital and lowercase letters; every username is encountering an error.

https://github.com/learningequality/kolibri/assets/77477551/b6498e63-0cf3-4d92-960f-16ffcf042ac4

**Pull request merged**
