### PR TITLE
Styleguide fixes and clean-up

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

Continuation of #5319. Includes updates based on feedback from @jonboiser 

This PR contains layout and styling updates to the styleguide, but _no changes to the content_.

Specifically:

* Removes the live code editor. My sense is that it caused more issues than it was worth:
  * examples used a second vue instance, and caused the examples to differ from our actual code-base in terms of import statements and `kebab-case` vs `CamelCase`
  * interacted poorly with new dynamic styling
  * related issues: #2416,  #1685, #1686
* updated examples so that they now are real, accurate reflections of components used as used in Kolibri
* switched to a Prism-based code example viewer (https://prismjs.com/) which seemed lighter-weight and more reliable than codemirror, which is [currently being rewritten](https://codemirror.net/6/).
* made code examples a bit more responsive (still not fully though)
* updated side-nav to use material-spec styling, but _not_ necessarily look like Kolibri
* updated component API tables to use our core table styling
* simplified API headers
* general styling updates, including globally bumping line height by a bit
* improved layout
* new color scheme
* mechanism for auto-generating and handling page anchor links
* switches URL to `/design`

### Reviewer guidance

…

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
I'd like to get this in so that subsequent PRs can be content- rather than layout-focused

**Comment by jonboiser** [comment]
Remove the extra h1 tags on the "Checkboxes", "Horizontal navbar", "Tooltips", and "Topic tree breadcrumbs" page, since they appear in the fixed header as well.

**Comment by jonboiser** [comment]
It would be nice if the page title appeared in the browser tab, as well. It just says "Kolibri" for every page.

**Comment by jonboiser** [comment]
Have external links open in a separate tab, like to the core values page, and material design page.

**Comment by jonboiser** [comment]
There's some extra stuff in the "Buttons and links" page

Screen Shot 2019-07-11 at 11 58 47 AM

**Comment by indirectlylit** [comment]
thanks for the feedback! yup I was aware that a lot of the headers were borked. I'll go ahead and fix those

**Comment by indirectlylit** [comment]
@jonboiser I addressed your feedback and pushed changes.

note that I've temporarily commented out a large number of "unfinished" pages. I'll get them into a working state and uncomment them in future PRs.

I've become convinced that – similar to user and developer docs – it doesn't make any sense to retain "in progress" or "to do" items - it only adds noise.

**Review by jonboiser — APPROVED** [review]

**Pull request merged**
