### PR TITLE
Reduce gutter size for content blocks on mobile and small screens

### LINKED ISSUE #10530: Reduce gutter size for content blocks on mobile
## Observed behavior
Noted by @bjester in the alpha12 bug bash: 

The gutter size could be reduced on mobile, which would make better use of the space. Any suggestions @jtamiace @tomiwaoLE ?

gutter

## Context
0.16.0-alpha12

### PR DESCRIPTION
**Pull request by akolson**
## Summary

This pr reduce gutter size for content blocks on mobile and small screens
**Before:**
image

**After:**
Screenshot 2023-05-02 at 17 52 58
Screenshot 2023-05-02 at 17 51 59

## References

Resolves https://github.com/learningequality/kolibri/issues/10530

## Reviewer guidance

Login to kolibri

- Resizes your browser to mobile view or
- Run Kolibri in [app mode](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#running-in-app-mode)

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by thanksameeelian** [comment]
i've been looking at this in the mobile view in chrome & it looks like it's performing as intended & matching the "after" expectations!

the way the top padding renders caught my eye because it felt a bit big compared to the total screen size - is that what's desired? it doesn't feel very consequential in the case of shorter cards (like "classes" for me, though the difference in padding on the top vs sides is noticeable) but in the case of a card with a lot of content it felt like it might be nice to see more of that content rather than a good amount of top padding. i'm not sure if this impression fits with the rest of the team's sentiments though - it could easily just be me or a specific quirk of running mobile view in browser in both of our screenshots 😄

image
image

**Comment by bjester** [comment]
@thanksameeelian That's an excellent catch. Seems the top padding is probably designed to be somewhat proportional to the gutter size. We should followup with @jtamiace (Jessica) on this.

**Comment by jtamiace** [comment]
The margin looks pretty decent reduced to 32px on both desktop and mobile. 24px on mobile looks slightly better but less so on desktop. If there's an easy way to implement that 8px difference that'd be awesome, but either one would work.

Screenshot 2023-05-02 at 5 02 02 PM

**Comment by pcenov** [comment]
LGTM @akolson and @radinamatic - no issues observed while manually testing this in an actual mobile device and regression testing in desktop browsers.

**Review by radinamatic — APPROVED** [review]
Manual QA passed, good to go! 👍🏽 :shipit:

**Review by thanksameeelian — CHANGES_REQUESTED** [review]
just leaving a little block here so it doesn't get accidentally merged too soon, since it seems like there's agreement that a change in the top padding would be preferable (but by no means required 🙂)

**Comment by akolson** [comment]
Hi @thanksameeelian / reviewer, the changes have been made as suggested by Jessica. happy to hear any additional feedback regarding this issue. Thanks

**Review by thanksameeelian — APPROVED** [review]
this looks great to me, @akolson! thank you for being so flexible and receptive to feedback!!

**Pull request merged**
