### PR TITLE
Vue component: Side menu style search-widget

### PR DESCRIPTION
**Pull request by 66eli77**
ready for review.
hint: you need to run `npm install` to install vue focus
*screenshoot
screen shot 2016-07-09 at 8 59 10 pm

### CODE REVIEW

**Comment by rtibbles** [comment]
Will review and resolve the merge conflict here also.

**Comment by rtibbles** [comment]
@66eli77 I have merged the PR to master - but not with the last three commits, as they weren't there when I pulled.

Please rebase these onto current master.

**Comment by 66eli77** [comment]
@rtibbles  it looked quite different after the merge. What changes cause the conflicts?

**Comment by rtibbles** [comment]
@indirectlylit's routing pr heavily refactored the state management, so that caused a lot of conflicts.

I cleaned it up and also removed some of the duplication in the pr (with the content icons and the search card code).

**Comment by 66eli77** [comment]
use content/topic card inside search card did solve the svg duplication problem. but the search card lost control of the styling, and the styles are quite different between these cards

**Comment by rtibbles** [comment]
The other alternative is to include the icons from the same directory, rather than copying them.

Another option is to unscope the styling of the search card. Whatever the solution, we should avoid duplicating code and files in both search and content/topic cards.

**Comment by 66eli77** [comment]
I also observed that when click a topic search card in search, the search results are lost and show a blank search side-menu. It would be convenient if the search results are kept showing, so user can click through the result quickly to find what they want

**Comment by rtibbles** [comment]
Weird - the search state should be preserved, @66eli77. Looking at it now.

**Comment by indirectlylit** [comment]
Looks like most of these changes are merged in. Mind linking to the commit or PR and closing this?

**Comment by rtibbles** [comment]
This was the PR - but because some changes got added to it after merging, I think github got confused.

**Pull request closed without merging**
