### PR TITLE
Re-activate IndividualSelector, fix select-all disabled/checked states

### LINKED ISSUE #6260: "Individual learners" looks like it's one of the group names
### Observed behavior

We don't distinguish between group names and the category of individual learners

image

### Expected behavior

should be more clear what the categories are

### User-facing consequences

possible confusion

### Steps to reproduce

create and assign to groups and individuals

### Context

0.13.0

### LINKED ISSUE #6330: disable 'select all' checkbox if all learners' checkboxes are also disabled
### Observed behavior

reported by @jtamiace regarding learner selection in assignment of quizzes and lessons:

image

### Expected behavior

> Should disable select all checkbox in individual selection of learners if all learners are disabled

### User-facing consequences

UI element that doesn't do anything

### Steps to reproduce

* put all learners in a group
* assign to the group
* also assign to individual learners

### Context

0.13.0

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

1. Turns off the flag that hides the `IndividualLearnerSelector`
1. Fixes the checked/disabled states for the "Select All" checkbox in that Component. Fixes #6330 
1. Some style changes: lightens the `:hover` background for core table, so it doesn't hide greyed items. Adds a "People" icon next to  the "Select individuals" icon so it stands out more. Fixes #6260
1. Adds fix for #6335

Example:

Screen Shot 2020-01-07 at 4 32 49 PM

### Reviewer guidance

1. Try out the individual selector under more complicated cases, like having multiple pages of users, lots of groups, etc.

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
I think we need to target 0.14.0 for this (slated for early March) because it will involve a round of translation.

**Comment by indirectlylit** [comment]
> I think we need to target 0.14.0 for this (slated for early March) because it will involve a round of translation.

actually this might no longer be true. Will investigate with Carine

**Comment by indirectlylit** [comment]
Note: targeting to 0.13.2. Let's wait to merge until after releasing 0.13.1

**Comment by indirectlylit** [comment]
> Adds a "People" icon next to the "Select individuals" icon so it stands out more.

@jonboiser this is a smart idea. Could we do the same thing for "Entire class" and the groups?

| class | group | individuals |
|--|--|--|
|image|image|image|

**Comment by indirectlylit** [comment]
FYI - pushed changes to merge in latest and fix LFS issue

**Comment by indirectlylit** [comment]
After discussion with @carinediaz, we do not have bandwidth to translate this for an early 0.13.2 release after all. Let's retarget to 0.14, which is aimed for mid-march. That means we can merge it into `develop` immediately, and we'll stick with the convention of not adding new strings in patch releases.

**Comment by indirectlylit** [comment]
@jonboiser would you mind rebasing this against `develop`?

**Review by nucleogenesis — APPROVED** [review]
Everything looks good! Excited for this to be included in the next major release :+1:

**Pull request merged**
