### PR TITLE
Squash all that we can without getting circular dependency errors.

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
Do as much migration squashing as possible. Unfortunately, the main motivation for squashing (not creating then deleting the DeviceOwner) is not possible due to the way that Django handles dependencies for squashed migrations (even if there are no circular dependencies for the squashed migrations, it still finds them in the migrations that the squashed migrations are replacing).

@ralphiee22 and I spent a bit of time seeing if we could work around it, but found nothing.

### Reviewer guidance
Check that the app migrates properly!

### References
May or may not want to merge this, I don't think it really helps much, so might not be worth the risk.

#3408

----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [x] Automated test coverage is satisfactory
- [x] Reviewer has fully tested the PR manually
- [x] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [x] External dependencies files were updated (`yarn` and `pip`)
- [x] Documentation is updated
- [x] Link to diff of internal dependency change is included
- [x] CHANGELOG.rst is updated for high-level changes
- [x] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by rtibbles** [comment]
Just a note that I don't think this is worth merging, due to the potential risk and the very small number of operations that are squashed.

**Comment by benjaoming** [comment]
> Unfortunately, the main motivation for squashing (not creating then deleting the DeviceOwner) is not possible due to the way that Django handles dependencies for squashed migrations 

Isn't this severe?

In which migrations does it take place?

**Comment by indirectlylit** [comment]
Since this PR is requiring additional discussion/changes, recommend moving to 0.10.0

**Comment by benjaoming** [comment]
@indirectlylit yup, we ended up deciding it's not worth the effort before we resolve the problems with `DeviceOwner`.

**Comment by indirectlylit** [comment]
thanks for the update

**Pull request closed without merging**
