### PR TITLE
Update Time Spent & Last Activity columns from notifications in Coach Lesson Reports

### PR DESCRIPTION
**Pull request by nucleogenesis**
### Summary

Makes 'Time Spent' column update automatically on a Coach Lesson Report Detail page - issue reported: https://github.com/learningequality/kolibri/issues/5496

This PR makes use of work that I did in https://github.com/learningequality/kolibri/pull/5595 implementing the `NotificationEventType.Answered` to send a `ResourceAnswered` notification. 

This allows the `end_timestamp` time to be the timestamp for the Resource - so it will update live now.

One change that I did in the last commit is that I basically nullified my work on https://github.com/learningequality/kolibri/pull/5936/files where I filtered out `QuizAnswered` notifications in the getter.

Instead, I've now updated the `ActivityBlock` to filter out any notification where `event.type === "Answered"`. Handling this on the component feels better to me - the data we get from the backend is now accurately reflected in the Vuex state, but the components consuming that state decide what they want to do with it - which is to not show "Answered" events.

### Reviewer guidance

1. Have a Lesson created with an exercise added.
2. Login to two browsers (one anonymous). In one browser, be a coach viewing the lesson details page under reports. In the other, be a learner who can work through that lesson.
3. As the learner, answer questions. Expect to see the status change from "Not Started" -> "Started" and the "Time Spent" and "Last Activity" columns update as questions are answered.
4. Ensure also that the "Status" changes properly - to "Completed" when you finish, or to "Needs Help" when you answer 3 wrongly.

### References

https://github.com/learningequality/kolibri/issues/5496
https://github.com/learningequality/kolibri/pull/5595
https://github.com/learningequality/kolibri/pull/5936/files

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [x] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
Tested the dev branch on Ubuntu 18.0:, **Time spent** and **Last activity** are updated in real time! :+1: 

**Progress** column on the lesson resource report gets updated with the *Started* and *Completed* state, but not with *Needs help* state, even though learner gives all the incorrect answers. State is correctly reported on Class home though...

no-needs-help-on-lesson-report

Another issue I bumped into is that the **View all** page is empty on first load, and the most recent activity appears only after the **Show more** button is pressed twice :confused: 

no-activity

**Comment by nucleogenesis** [comment]
@radinamatic 

I've rebased the PR and I'm not having the same issues with the "Needs Help" - but perhaps I'm not taking the same approach?

- As Coach, view the Lesson Reports Details page for a Lesson.
- As a Learner, go answer 3 wrong questions on a Resource in that Lesson.
- As a Coach, see the "Progress" column update automatically with a "# Needs Help" icon underneath the "# of # started" and "# completed" items.

Let me know if you have issues resolving this.

I'm also not able to replicate the issue you note here:

> Another issue I bumped into is that the View all page is empty on first load, and the most recent activity appears only after the Show more button is pressed twice confused

I'm curious if the rebase fixes this as well?

**Comment by radinamatic** [comment]
@nucleogenesis Sure thing, will pull your latest and redo the walk-through!

**Comment by radinamatic** [comment]
@nucleogenesis :confused: Still not being able to see the *Needs help* status anywhere but inside the *Class activity* block on Class home. I rebased and have your branch as follows:

```
(kolibri) didivm@didivm-VirtualBox:~/LE/kolibri$ git status
HEAD detached at nucleogenesis/time-spent-column-coach-report
nothing to commit, working tree clean
(kolibri) didivm@didivm-VirtualBox:~/LE/kolibri$ git reset --hard nucleogenesis/time-spent-column-coach-report 
HEAD is now at e6f4818ee Ensure a "started" event isn't counted as "answered"
(kolibri) didivm@didivm-VirtualBox:~/LE/kolibri$ 
```

As you can see in the recording, **Time spent** and **Last activity** are being constantly updated while the learner **archiem** is giving (all incorrect) answers in the window on the right side, but the 
**Progress** column on the lesson resource report is stuck with *Started* status and does not change to *Needs help* - wasn't that the purpose of the PR? Or am I looking at the wrong place...?

no-needs-help-on-lesson-report2

Again, not seeing the *# need(s) help* status in any of the lessons inside the Lessons block on Class home, and at least `Lección 4-E` and ` Test diffque` should have it. When I click the **Show all** button inside the *Class activity* block on Class home, it still requires ONE click on the **Show more** button to display the most recent activity.

no-activity2

**Comment by radinamatic** [comment]
@nucleogenesis As we suspected, when I installed the DEB asset from this PR on a fresh Ubuntu 16.04 VM, the issue(s) have resolved... :woman_shrugging: 

What's the best way for you to investigate how my dev env setup could be still reproducing the problem? My `.kolibri` folder is huge because of all the content, but the DB is manageable (300Mb uncompressed). Would it help if I passed it to you for further inspection?

**Comment by radinamatic** [comment]
I think we're finally there: working still off your branch I created a completely new class, downloaded some new content which was not present before, created a brand new lesson, and low and behold I can finally see the `Needs help` status correctly :tada: 

needs-help-finally

**Review by radinamatic — APPROVED** [review]
Doubt still persists if after upgrading any of the users would bump into the similar set of circumstances, but since I've now confirmed the fix on both the installed asset and the dev env with fresh content & class, I think we can take this for approved ;)

**Review by jonboiser — APPROVED** [review]

**Pull request merged**
