### PR TITLE
0.8.1-alpha - to be merged after 0.8.0 is tagged

### PR DESCRIPTION
**Pull request by indirectlylit**
### Summary

merge after #3351

### Reviewer guidance

…

### References

…

----

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by indirectlylit** [comment]
ready for merging this @benjaoming

**Comment by indirectlylit** [comment]
@benjaoming could you please review and merge this

**Comment by benjaoming** [comment]
Right by the book <3

image

**Comment by benjaoming** [comment]
Not sure why this contains setting the version number to final + release notes... seems that Github keeps this state, even though they are already merged.

**Pull request merged**
