### PR TITLE
Enable production environment for cherrypy.

### PR DESCRIPTION
**Pull request by jamalex**
For efficiency, and to avoid having tracebacks show up in production, we turn on cherrypy's production mode setting.

### CODE REVIEW

**Comment by rtibbles** [comment]
@jamalex is there a plan to release this on 0.3.x, or would it be better to target this to 0.4.x or develop?

**Comment by jamalex** [comment]
It was based on the VF security review, so I think getting it into 0.3 and
merging back from there would be ideal.

**Comment by rtibbles** [comment]
Right - just wondering if there were plans to actually release the update in the 0.3.x line.

Also - tests are failing!

**Comment by jamalex** [comment]
I think we can hold off for any other bug fix requests from VF, and include
this in a release at that point. But having it in the branch would be good.

Failing tests seems to be due to issues fixed separately but not backported
to 0.3.

On Jun 14, 2017 1:02 AM, "Richard Tibbles" <notifications@github.com> wrote:

Right - just wondering if there were plans to actually release the update
in the 0.3.x line.

Also - tests are failing!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/learningequality/kolibri/pull/1628#issuecomment-308281908>,
or mute the thread

**Comment by benjaoming** [comment]
#1699 shows no issues in tests.

The test issue here is general to 0.3.x:

```
    FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/learningequality/kolibri/kolibri/VERSION'
```

**Pull request merged**
