### PR TITLE
Language switcher

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Implements a language switcher following design of @khangmach - moves language switcher out of the app bar, and implements it as an option in the used drop down.

In addition, it adds a footer to the login and sign up pages (where no app bar is present) showing six languages, and a more languages button to prompt the same modal.

## Screenshots

Mobile footer:

image

Desktop footer:

image

Drop down:

image

Modal:

image

### CODE REVIEW

**Comment by indirectlylit** [comment]
I'm getting:

```
OperationalError at /learn/
no such column: content_contentnode.lang_id
```

Tried:

```
$ kolibri manage migrate
Operations to perform:
  Apply all migrations: sessions, admin, kolibriauth, morango, auth, content, contenttypes, exams, logger
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

```
$ kolibri manage makemigrations
Migrations for 'content':
  0005_auto_20170809_1819.py:
    - Alter field extension on file
    - Alter field preset on file
Migrations for 'kolibriauth':
  0004_auto_20170809_1819.py:
    - Alter field username on deviceowner
    - Alter field username on facilityuser
Migrations for 'morango':
  0007_auto_20170809_1819.py:
    - Change managers on certificate
```

The error persists.

**Comment by indirectlylit** [comment]
workaround was removing all my content databases

**Comment by indirectlylit** [comment]
Very cool!

There some issues though, I think:

## Layout & responsiveness of login page

alignment:

image

button not visible:

image

bottom not visible and page not scrollable:

image

whitespace:

image

## Text wrapping

Should we try to avoid letting languages wrap to new lines? This looks confusing as it stands:

image

## Modal switcher

The link-to-plain-text switcher is a bit awkward because when you switch language, the text weights changes so the line lengths shift.

image

For this modal I think using standard radio buttons would be more appropriate.

**Comment by indirectlylit** [comment]
One other minor note: when browsing Learn anonymously, it's a bit harder to switch language since there's no user dropdown. On the other hand, I guess it's hard regardless because the text "Change language" might be in the wrong language... oh well

**Comment by rtibbles** [comment]
There should be a user dropdown now for anonymous users, I changed it as per the design here:
language select

See the design here ^ for the reason for some of the choices (I think inspired by Facebook's selector - might be worth revisting whether we want a click on a language to select, or set a language?)

**Comment by indirectlylit** [comment]
Yeah - the links work fine on the login screen. It's just in the modal that they should probably be radio buttons since it's a pretty standard selection + confirmation flow.

**Comment by indirectlylit** [comment]
> There should be a user dropdown now for anonymous users

interesting, I didn't see that. will check again tomorrow

**Comment by khangmach** [comment]
- I'm okay with radio buttons for the languages within modal.
- Browsing as guest, user dropdown should exist with options "change language" and "sign in".
- I'm okay with eliminating that extra whitespace and aligning the "more languages" button on desktop so it is inline with the language options 
-On mobile breakpoint since wrapping language options will look bad especially when we have more languages, I'm okay with taking out the language options and just showing current language + more languages button or 2 language options max + more languages button

**Comment by rtibbles** [comment]
Yeah, similarly to Duolingo, Facebook lists quite a few languages, and then has a small (non-linguistic) more button.

image

I think erring on showing more, but allowing a scroll is probably preferable.

**Comment by rtibbles** [comment]
@khangmach I have made changes in line with the suggestions above.

Have removed the non-language text and the 'more button' from the footer, and made everything scroll correctly.

Have removed the 'language prompt' in the footer, in a reflection of the Facebook design, and because I don't think it is meaningful for anyone planning to switch languages.

Have fixed the dropdown issue not showing for anonymous users that @indirectlylit reported.

Modal now:
image

Footer:
image

Footer (mobile):
image

**Pull request merged**
