### PR TITLE
Import export

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

1. Add an 'import more from channel' workflow
1. Give Select Content + Available Channels Pages URLs
1. Refactor - unwrap Select Content Page and Available Channels Page from immersive-full-screen
1. Refactor - replace `pk` with `id` in all consumers of ContentNode(Granular) APIs
1. Refactor - Remove `transitionWizardPage` state machine since transitions are handled by router
1. Refactor - Combine Select Source and Select Drive modals into a single modal
1. Refactor - consolidate Vuex store fixtures for all tests
1. Refactor - poll for Tasks at all `/content/*` pages since we aren't using modals for the wizard any more.

### Reviewer guidance

Test the import/export workflow with all combinations of these conditions

* External drive present/absent
* Content Metadata DB present/absent (and needs to be downloaded from source)
* Content already installed/ no content installed
* Importing from Kolibri Studio or local drive
* Importing a channel that has been upgraded
* Importing from a drive/Kolibri STudio vs. importing _more_ from a specific channel
* Accessing a workflow using buttons/modals vs. accessing it directly via URL

Check for details

* Correct text at all stages, depending on whether it's import/export workflow
* Correct text on Channels Cards at Available Channels Page
* Correct text in all areas of Select Content Page depending on import/export workflow

### References

…

----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [x] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by mrpau-richard** [comment]
@jonboiser I tested the import/export workflow you listed above, so far I didn't encounter any issue during my testing.

I have only one comment with the `Try adding a token` link button moved at the top of all the channels listed. At the `develop branch` it was at the bottom of all the channels.
screen shot 2018-05-30 at 3 45 11 pm

**Comment by radinamatic** [comment]
@mrpau-richard It was a requested feature enhancement, not a bug :wink:  (see #3654 & #3030)

**Comment by mrpau-richard** [comment]
Oh sorry, I didn't notice it. I thought it was an import/export enhancement.

**Comment by indirectlylit** [comment]
This looks excellent - nice job. I'm going to merge in for string freeze. Filed one issue, referenced just above.

Let's continue to hammer this and look for edge cases

**Review by indirectlylit — APPROVED** [review]

**Comment by indirectlylit** [comment]
fixes #3511

**Pull request merged**
