### PR TITLE
Non binary content schema

### LINKED ISSUE #7004: Kolibri is unable to start using python 3.8
### Observed behavior

I upgraded the python to version 3.8.3 and installed it. When I run there's an dialog message "Kolibri is unable to start: You can find additional information in your Kolibri home folder:" and the logs was empty.

I tried to run it using command prompt and it can't run because of an attribute error ` 'time' has no attribute 'clock' `

python38-error

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version 0.13.3
 * Operating system Windows 10
 * Browser n/a

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
Changes the way we store our SQLAlchemy content schema to python modules, rather than binary files containing the pickles of the Python objects.
Upgrades SQLAlchemy (which we previously couldn't do beyond patch versions because the pickled Python objects depended on the internal APIs not changing).

### Reviewer guidance
Does channel import work?

We should hold off merging this until #6873 is merged, so that this can be rebased, and the generation of a new content schema properly tested.

This should hopefully also fix #7004 due to the SQLAlchemy version upgrade.

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
Is this something we want to target to 0.14?

**Comment by rtibbles** [comment]
The only reason we would *need* to is if we wanted to update SQLAlchemy in this release. We can leave this on develop though.

**Comment by rtibbles** [comment]
OK, looks like for Python 3.8 support we would need to merge this PR, so I think we should prioritize it.

**Review by indirectlylit — APPROVED** [review]
tested import and it works fine

**Pull request merged**
