### PR TITLE
Only count LocalFiles once when estimating total download file size

### PR DESCRIPTION
**Pull request by jamalex**
Quick fix.

### CODE REVIEW

**Comment by rtibbles** [comment]
at the risk of slowing down your fix, could you make a similar change here? https://github.com/learningequality/kolibri/blob/release-v0.6.x/kolibri/content/serializers.py#L19

**Comment by jamalex** [comment]
I don't think it applies in that context (at least, it wouldn't be as simple as adding `distinct()`).

**Comment by jamalex** [comment]
Oooh, looks like there's a different syntax: https://stackoverflow.com/a/8680537

**Comment by rtibbles** [comment]
Seems like that is only on `Count` though? https://docs.djangoproject.com/en/dev/topics/db/aggregation/#combining-multiple-aggregations

**Pull request merged**
