### PR TITLE
Kolibri Installation Guides

### PR DESCRIPTION
**Pull request by radinamatic**
## Summary

This is **Work in Progress**, probably won't be merged soon.
The intention is to improve the structure of the sections so each OS gets a separate doc page with the appropriate page title.  
## TODO
- [ ] Finish reviewing the sections that document the existing features.
- [ ] Comment out the sections that do not need to be visible yet, but have them ready for the future. 
- [ ] Review structure.

### CODE REVIEW

**Comment by radinamatic** [comment]
No idea if GH automatically attaches the `needs review` label, but since this is still a WIP, once I consider it is ready for review, I'll put back the label and assign somebody else.

**Comment by benjaoming** [comment]
@radinamatic I believe that @rtibbles has now changed how Device Owners works in #1983 and #1998 so re-visiting 0604b18 is probably a good idea.

**Comment by rtibbles** [comment]
Yeah, DeviceOwners are dead.

**Comment by radinamatic** [comment]
This is a very old draft for the installation doc. So much has changed, and we've adopted the review and editing process on FLE Shared docs, so I'm closing this PR and will open a new one once the editing is done.

**Pull request closed without merging**
