### PR TITLE
[DO NOT MERGE, FOR QA ONLY] Test KDropdownMenu Keyboard Navigation

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Summary
https://github.com/learningequality/kolibri-design-system/pull/818 Introduces some fixes regarding Keyboard Navigation in KDropdownMenu.  This PR introduces these changes in Kolibri for QA to test that this is the expected behaviour.

## Reviewer guidance

Look for dropdown menus, and test its behaviour using Keyboard Navigation.

### CODE REVIEW

**Comment by AlexVelezLl** [comment]
@radinamatic could you please take a look and confirm if this is the expected behaviour while keyboard navigating dropdown menus? :)

**Comment by radinamatic** [comment]
@AlexVelezLl 
While testing the keyboard navigation **ONLY** I did not find any issues, and the dropdown element **Options** in Device > Channels, and **New quiz** in Coach > Plan > Quizzes behaved as expected and required.

However, after I tried to confirm the results with the screenreader, my NVDA was not giving the expected output 😕 

What we call _dropdown_ is essentially the **Menu button** pattern from [ARIA Authoring Practices Guide (APG)](https:/www.w3.org/WAI/ARIA/apg/patterns/menu-button/). Looking at the page source after I installed the asset on Windows 10, while the proper **roles** ``menu`` and ``menu-item`` seem to be applied, the required [aria-haspopup](https://w3c.github.io/aria/#aria-haspopup) **property**, and the [aria-expanded](https://w3c.github.io/aria/#aria-expanded) **state** are not.

Could we fix these [property & states](https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/#wai-ariaroles,states,andproperties) issues before merging the PR?

**Comment by AlexVelezLl** [comment]
Hi @radinamatic, I foresee that including these property & states will need more changes and considerations. And as for now the [issue](https://github.com/learningequality/kolibri-design-system/issues/588) was about fixing the "keyboard navigation", this is a little bit out of scope (and also because this is an existing behaviour rather than a regression introduced in the PR). I will open a follow up issue to make sure we include this too :). Is it okay? :open_hands:

**Comment by AlexVelezLl** [comment]
Follow up issue for this: https://github.com/learningequality/kolibri-design-system/issues/832

**Pull request closed without merging**
