### PR TITLE
Upgrade Windows installer to v1.3.6

### LINKED ISSUE #6700: upgrade windows installer to 1.3.6
ref: https://github.com/learningequality/kolibri-installer-windows/milestone/12

cc @cpauya  @mrpau-richard  @lyw07  @jonboiser

### PR DESCRIPTION
**Pull request by mrpau-richard**
### Summary
Upgrade Windows installer to 1.3.6 release

### Reviewer guidance

…

### References
This fixes #6700 

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by cpauya** [comment]
Thanks for initiating this @mrpau-richard!  The [Windows build failed](https://buildkite.com/learningequality/kolibri-python-package/builds/158#94e3be58-ce44-4338-868c-f30c14f915ff) however:

```
Error on line 463 in Z:\kolibri-installer-windows\src\installer-source\KolibriSetupScript.iss: Column 7:
--
  | Unknown identifier 'HandlePythonSetup'
  | Compile aborted.
```

**Comment by mrpau-richard** [comment]
I finished fixing the error @cpauya

**Comment by radinamatic** [comment]
@mrpau-richard Does something specific need to be tested here, or it's just the version number update?

**Comment by mrpau-richard** [comment]
@radinamatic here's the [1.3.6 milestone](https://github.com/learningequality/kolibri-installer-windows/issues?q=is%3Aissue+milestone%3A1.3.6+is%3Aclosed) for this PR updates.

**Review by cpauya — APPROVED** [review]
I tested the generated installer on both Win10 and Win7 VMs and they work.  
1. Install Kolibri v0.13.1
1. When the browser is launched with the Kolibri setup page shown, Quit Kolibri 
1. Delete `C:\Python34\Scripts\pip*.exe`
1. Install the installer in this PR
1. Notice that Kolibri successfully started and that there are new `C:\Python34\Scripts\pip*.exe` files.

Good one @mrpau-richard!

**Pull request merged**
