### PR TITLE
Fix language switcher modal placement

### LINKED ISSUE #4739: Language switcher vertical alignment
### Observed behavior

Language switcher modal is half hidden under the top edge of the browser window.
Switcher modal is correctly aligned on the sign-in page.

ubuntu 16 04 3 start running - oracle vm virtualbox_374

### Expected behavior

Language switcher should be fully visible.

### User-facing consequences

Inability to change to any language that is not visible in the modal.

### Errors and logs
- nothing visible

### Steps to reproduce

1. Sign in or start browsing as a guest.
2. Try changing the language.

### Context

 * Kolibri version: 0.12.0.alpha3
 * Operating system: Ubuntu 16.04
 * Browser: FF 64 & Chrome 71

### PR DESCRIPTION
**Pull request by rtibbles**
### Summary
* Removes GPU acceleration to prevent interference with modal placement.

### Reviewer guidance
Does the language switcher pop up in the right position?
Does the scrolling header ease acceptably?

### References
Fixes #4739

Before:
image

After:
image

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Gherkin stories have been updated
- [ ] Unit tests have been updated

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by jonboiser** [comment]
I was able to fix this in coach-data with a CSS rule. 2c812914069a2a538bd751f03597cd662fdecf87

Might be just as effective.

**Comment by radinamatic** [comment]
Fetching your branch as the build is taking too long...

**Comment by rtibbles** [comment]
We shouldn't be using `vh` as it is unsupported in the Android native browser below 4.4 (although it's possible that the hard requirement for below 4.4 may be lifting). I see we are also using it in the CoreMenu component, so that must have slipped through somehow.

**Comment by radinamatic** [comment]
Looking good! :+1: 

ledev18 start running - oracle vm virtualbox_389

**Review by radinamatic — APPROVED** [review]
LGTM, merge away! :+1:

**Comment by indirectlylit** [comment]
Hmm both solutions seem a little problematic to be honest. This one looks less so.

I'll merge in but I'd like to follow up.

**Comment by indirectlylit** [comment]
ref #4757

**Pull request merged**
