### PR TITLE
bump perseus plugin version

### PR DESCRIPTION
**Pull request by benjaoming**
### Summary

Scheduled before release of 0.9.0

### Reviewer guidance

No reviews, but do we need tests?

### References

None

----

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by radinamatic** [comment]
> No reviews, but do we need tests?

I'll gladly grab the exe or pex to test once the build is ready, unless it's better to do it otherwise...?

**Comment by benjaoming** [comment]
@radinamatic please do test - translations are missing, but will add and bump once again. But I would think that it's valuable to get a thumbs up on whether this part works!

**Comment by benjaoming** [comment]
Going to add a version bump for perseus w/ translations in this PR as well.

**Comment by benjaoming** [comment]
@radinamatic All the translations will be contained in the upcoming build...

**Comment by radinamatic** [comment]
Installed `kolibri-buildkite-build-3434-5895-KolibriSetup-0.9.0b3.dev0+git.15.gedebe10.exe`, but getting 500 server error 😞 

virtualbox_winps_28_03_2018_12_38_06

When run from command prompt:
virtualbox_winps_28_03_2018_12_41_49

**Comment by radinamatic** [comment]
@benjaoming @indirectlylit ^^

**Comment by radinamatic** [comment]
Same result on Ubuntu 16.10:

virtualbox_ubuntu16 10_28_03_2018_13_18_11

**Comment by indirectlylit** [comment]
seeing this error in dev mode...

```
    WARNING in ../perseus-plugin/kolibri_exercise_perseus_plugin/assets/src/views/index.vue
    
    /Users/d/Projects/learning_equality/repos/perseus-plugin/kolibri_exercise_perseus_plugin/assets/src/views/index.vue
      84:36  error  Unable to resolve path to module 'kolibri.coreVue.mixins.contentRenderer'  import/no-unresolved
    
    ✖ 1 problem (1 error, 0 warnings)
```

**Comment by indirectlylit** [comment]
perseus 0.9.0 did not seem to have static assets built in, so closing this version bump. we'll go to perseus 0.9.1

**Pull request closed without merging**
