### PR TITLE
Ensure session and summary log outputs are consistent between channel and displayed node

### LINKED ISSUE #12791: Session and Summary export logs do not prioritize the content node with the selected channel id
## Observed behavior
This can lead to peculiar data mismatches, especially once https://github.com/learningequality/kolibri/pull/12782 is merged, whereby the topics do not match to the channel.

## Expected behavior
We should look up the node by the content_id and the channel_id - and only fallback to the content_id only if that look up fails.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Ensures the specific node in a channel is returned, not just any with the matching content_id.
* Uses node_id from the session log context in extra_fields when available.

## References
Fixes #12791

## Reviewer guidance
Engage with resources that are in multiple channels (e.g. some KA exercises for different languages, and those that have been copied into the Kolibri QA channel).

Export the session and summary logs.

Make sure that the topic tree hierarchy and the channel name match up to each other in the logs.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
Hi @rtibbles - I noticed the following issues while manually testing:

1. In both logs there's always an empty 'Topic level N' column before the 'Content id' column:

empty level

2. In the summary logs I can see the following issue, where the entries from topic level 4 to 9 are incorrect for a resource imported from KA Chinese:

summary logs

Test channel token which you can use to replicate the issue: `milas-tarol`
Logs and DB in google drive: https://drive.google.com/drive/u/0/folders/17KajXswJjetgPzTTv0bdHrWNGPyg-5N5

**Comment by rtibbles** [comment]
Thanks @pcenov - I have fixed the first issue - I had originally left the second as intended behaviour because of the subtly different way we track data for summary logs vs session logs, but I am inspecting the session logs to get the data we need to ensure consistent behaviour between the two now.

**Review by pcenov — APPROVED** [review]
Thanks @rtibbles - I confirm that the above mentioned issues are fixed now!

**Review by ozer550 — APPROVED** [review]
Code changes make sense! I have tested the PR locally and logs are consistent!

**Pull request merged**
