### PR TITLE
make conditional test script more verbose

### PR DESCRIPTION
**Pull request by benjaoming**
## Summary

Investigating why the conditional tests are being run.
## TODO
- [x] Have tests been written for the new code?
- [x] Has documentation been written/updated?
- [x] New dependencies (if any) added to requirements file
- [x] Add an entry to CHANGELOG.rst
- [x] Add yourself it AUTHORS.rst if you don't appear there
## 
## Issues addressed
#477

### CODE REVIEW

**Comment by rtibbles** [comment]
@benjaoming While you are doing this, would you also be able to only run the build on the Python test environments? Doesn't seem like we need to do it in the docs, node, postgresql ones.

**Comment by benjaoming** [comment]
@rtibbles could you clarify that a bit, not sure I understand?

**Comment by rtibbles** [comment]
From what I can tell, the `make dist` is invoked in every test environment defined in `.travis.yml`.

This means it gets invoked in the following Travis build environments:
```
    - python: "2.7"
      env:
        - TOX_ENV=node0.12.x
        - TRAVIS_NODE_VERSION="0.12"
    - python: "2.7"
      env:
        - TOX_ENV=node4.x
        - TRAVIS_NODE_VERSION="4"
    - python: "2.7"
      env:
        - TOX_ENV=node5.x
        - TRAVIS_NODE_VERSION="5"
    - python: "2.7"
      env:
        - TOX_ENV=postgres
        - TRAVIS_NODE_VERSION="0.12"
```
Where I assume we don't really need to test the `make dist`? I assume we only want to do that across different Python envs, right?

**Comment by benjaoming** [comment]
Ah yes, that's right, no need to test it more than that, and actually `make dist` is "our own" command, so we don't really need to test it with different Python envs, neither.

**Comment by rtibbles** [comment]
Maybe just having a separate env for build testing then?

**Comment by benjaoming** [comment]
Still investigating the cause of why `git_changeset` is matching the '^setup\.py' trigger. It seems that Travis must have changed something in the way the repo is fetched.

**Comment by indirectlylit** [comment]
@benjaoming  switching label to WIP until you say it's ready for review again

**Comment by indirectlylit** [comment]
@benjaoming @rtibbles - I'm closing this PR due to inactivity. Feel free to re-open if desired.

**Comment by rtibbles** [comment]
I think some of the major concerns had been addressed by another PR, which reduced our build times by approximately half.

**Pull request closed without merging**
