### PR TITLE
Fix for progress ranges in CSV export + general data validation

### LINKED ISSUE #3120: 'Progress' shows values outside of 0-1 range in csv export of database
### Observed behavior

From the analytics generated and exported from Kolibri, 'progress' is measured on a scale of 0 to 1. The csv export shows records that are above 1. It's never shown as more than 1 in the frontend of Kolibri.

image 2

### Expected behavior

The expectation is to have a min value of 0 and max value of 1.  

### User-facing consequences

Values above 1 will confuse administrators and others analyzing progress of students.  

### Context

Windows OS, Kolibri version 0.5

### PR DESCRIPTION
**Pull request by benjaoming**
### Summary

Sort of fixes #3120 by correcting data and then blowing up in case content summary progress above 1.01 is saved.

### Reviewer guidance

@jamalex should models be marked as dirty during data migration?

### References

#3120

----

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If there are any front-end changes, before/after screenshots are included
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by ralphiee22** [comment]
Since no one has synced, the dirty bit flag has not been reset, then models do not need to be marked dirty during data migration.

**Comment by benjaoming** [comment]
@ralphiee22 
> Since no one has synced, the dirty bit flag has not been reset, then models do not need to be marked dirty during data migration.

Ah okay, so I can roll back 86130d5 ? Wasn't aware that sync'ing wasn't active.

**Comment by ralphiee22** [comment]
Yes you should be able to roll it back. The management command is in there since 0.7, but it was never made public.

**Comment by benjaoming** [comment]
I've rolled it back!

**Pull request merged**
