### PR TITLE
Add coach-mode props to disable all tracking in content-renderer

### PR DESCRIPTION
**Pull request by 66eli77**

### CODE REVIEW

**Comment by rtibbles** [comment]
@66eli77 I would rather do this by extracting the content tracking behaviour into the learn content page, rather than adding a big conditional flag to the content-renderer itself. I have done this similarly for all the assessment related behaviour, where all the events like `answerGiven` etc. are propagated out of the content renderer and not handled by it itself.

So, basically, you would add methods to handle the `startTracking`, `stopTracking`, and `updateProgress` events that are currently being handled either by actions or by methods that call actions.

Instead they should propagate these events upwards so that the learn content page can listen to them, and we move the two actions and the method that calls an action to there.

See here for an example: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/content-renderer/index.vue#L137

**Comment by 66eli77** [comment]
@rtibbles Yeah, I was wondering why those tracking is directly attached to the content-renderer component. If you take a look at assessment-wrapper, we attach the tracking on this wrapper instead of the content-renderer itself. In fact, should we reuse assessment-wrapper to attach these track events?
On another note, I think Devon wants us to avoid emitting events. @indirectlylit let me know if I misunderstood.

**Comment by rtibbles** [comment]
The assessment wrapper is essentially a special part of the learn page and
is handling assessment specific events coming from the renderer. All other
events (start tracking, stop tracking, update progress) should be handled
by the content page as these are fired for all content types and it is the
common wrapper between assessments and other content.

I disagree with @indirectlylit on this front. We need to emit events in
order to keep our components agnostic to the context in which they are
being used (the alternative is to directly call actions, but these assume a
lot of things about the vuex state and reduces cross contextual usability).

**Comment by rtibbles** [comment]
I was implementing my own fix for this, and now am wondering if stopping tracking of coaches is a good idea after all. I think it might be helpful to have this kind of content interaction data to see how coaches are using it. What might be more interesting is the context in which they are engaging with it to give us extra info.

I think I would like to plan this out a bit before we implement.

**Comment by indirectlylit** [comment]
> On another note, I think Devon wants us to avoid emitting events. @indirectlylit let me know if I misunderstood.

I didn't mean to imply that event-based communication is always bad - it's often the best way of communicating with a parent component, particularly for broadcasting about user interactions and other events.

I believe that in the case I complained about, the emitter was a modal, and it was emitting an event like `closeModal` which was a _command_ to the parent. This seemed more appropriate as an action because of the command-like nature. Typically the contract of event-driven behavior can not make assumptions about who is listening - it could be one, many, or no listeners.

**Comment by indirectlylit** [comment]
It does seem in this case too, the events are at least named as commands (e.g. `stopTracking`)

Perhaps there might be a way to rename the event interface to be less imperative and more descriptive - e.g.

```
@trackingStarted="wrappedStartTracking"
@trackingStopped="stopTracking"
@progress="updateProgress"
```

**Comment by indirectlylit** [comment]
> I was implementing my own fix for this, and now am wondering if stopping tracking of coaches is a good idea after all. I think it might be helpful to have this kind of content interaction data to see how coaches are using it. What might be more interesting is the context in which they are engaging with it to give us extra info.

that makes sense to me

**Pull request closed without merging**
