### PR TITLE
kolibri studio cards ui error resolved

### LINKED ISSUE #10931: Remote browsing - Several UX issues
## Observed behavior
Noticed several UX issues while comparing the current implementation to what we have in [Figma](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?type=design&node-id=194-2922&mode=design).

## Expected behavior
Should be further discussed /changes made.

## Steps to reproduce the issue
1. Install the latest develop build
2. Navigate to Library > Explore libraries

## More information

| Issue| Screenshot |
:-------------------------:|:-------------------------:
| RESOLVED in https://github.com/learningequality/kolibri/pull/11090 ~Library > Other libraries - Design differences~ | 
| (WIP in https://github.com/learningequality/kolibri/pull/11097) Library > Other libraries - Design differences | |
| RESOLVED in https://github.com/learningequality/kolibri/pull/11100 ~Library > View all libraries - Missing number of available channels~ |   |
| RESOLVED in https://github.com/learningequality/kolibri/pull/10974 ~Library > Explore libraries - Missing Search pane, Language filter displayed to the right and ‘All libraries’ link to go back~ |  |

## Usage Details
Kolibri 0.16alfa17
Windows 10, Ubuntu - Chrome

### PR DESCRIPTION
**Pull request by GarvitSinghal47**
#10931

## Summary
Changed kolibri studio crad to stack in only two rows and 3 in each in large screen instead of 2.

Before:

[kolibristdiocardsbefore.webm](https://github.com/learningequality/kolibri/assets/82756460/9359708e-52cd-4e91-8a84-e666aeb78d7d)

After:

[kolibristdiocardsafter.webm](https://github.com/learningequality/kolibri/assets/82756460/ed5fbd4c-b982-45b0-9398-7f9d4d9210ee)

…

## References

…

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by marcellamaki — CHANGES_REQUESTED** [review]
Hi @GarvitSinghal47 - thanks for your work on this! The code changes look like they are handling the issue as described. 

I am placing a "request changes" just for now as a block from merging, because I want to confirm with our design team that there is not an underlying UI problem (which is something that was not described in the issue) that we need to fix. Once I check with them, we will follow up here with code review and any clarifications. Thank you again for your contributions to Kolibri!

**Review by pcenov — CHANGES_REQUESTED** [review]
Hi @marcellamaki I was expecting to see this fix applied also for the scenario where there are 2 cards displayed per line. Currently in that case I am still seeing 3 rows (regardless of whether there are any imported channels in 'My library' or not):

https://github.com/learningequality/kolibri/assets/79847249/ba8df7bf-d2b8-42cf-af1c-e488d21cee18

**Comment by GarvitSinghal47** [comment]
@pcenov i got it , currently this is only showing 3 cards while there is size decrement to certain extent .
required will be that  either it will show  1 card or directly then it would show three cards no two cards i between any two size.

I will resolve it as soon as possible .

**Comment by GarvitSinghal47** [comment]
Hi @MisRob ,

while working on the issue regarding the display of 3 cards in small window sizes. I've found that the issue is present for breakpoints 2 and 3, and that the class pure-12-24 is applied to the cards in these breakpoints, which is setting the width to 50%. Instead, we need to apply the class pure-8-24 to the cards in order to display three cards with width 33 %.

The issue I'm facing is that the CSS is coming from the kolibri-design-system repo and is applied to the whole page. I need assistance in how to override this CSS in the current file  for the kolibri library.

I've tried different ways to override the CSS, but I haven't been able to successfully change it for the kolibri library.

Would you be able to help me with this?

**Comment by MisRob** [comment]
@GarvitSinghal47 This is looking like a limitation of our current KDS (Kolibri Design System). Unless absolutely necessary, we try not to override KDS styles from Kolibri but rather update KDS so they document and satisfy our needs. In regards to grids, there is some planning in progress for a new KDS card grid component. This will be built around completely new designs for grids.

We can definitely consider making further changes before the new grid if it's important. In that case, I'd suggest we open a follow-up issue with a bit more clearer expectations in regards to all breakpoints as after seeing this conversation, it's still not completely clear to me. In that issue, we could also decide whether it's something that can wait until the new card grid, and if no, examine technical aspect more closely and decide on whether to address it in KDS or Kolibri.

So taking all this into account, and the fact that this PR improves cards display under certain conditions, I don't see anything blocking here. Is that okay with you @marcellamaki and @pcenov or do you feel something else needs to be addressed at this point?

**Review by pcenov — APPROVED** [review]
Hi @MisRob I agree with you and I don't see anything blocking as well.

**Review by marcellamaki — APPROVED** [review]

**Comment by marcellamaki** [comment]
Approved! Thank you @GarvitSinghal47, @MisRob, and @pcenov !

**Pull request merged**
