### PR TITLE
0.11 String Audit

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

Updating strings based on a comprehensive sweep of copy we want to change in the app.

### Reviewer guidance

- [List of changes required](https://docs.google.com/document/d/1jFpDV1QmT9u3H3ULqib-Pmx4e1f1FUcGrnZXZssnsPc/edit)

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by indirectlylit** [comment]
looking good, thanks!

I don't think screencaps are totally necessary. What would be more useful is a link to the master list you're working off of so I can cross-reference with that

**Comment by radinamatic** [comment]
Even though on occasion I would like someone to share the screen-capping joys of the docs writer :smiling_imp:, I agree that the master list should be sufficient to review! Is this the [doc](https://docs.google.com/document/d/1jFpDV1QmT9u3H3ULqib-Pmx4e1f1FUcGrnZXZssnsPc/edit) you are working off...?

**Comment by jtamiace** [comment]
screen shot 2018-09-19 at 10 18 34 am

Sorry there is one string I think we overlooked. In the post-device-setup modal, for this string:

`The first thing you should do is import content from the Content tab`

`Content` should be changed to `Channel`

and `The admin account you created...` maybe changed to `The super admin account you created...`

**Comment by DXCanas** [comment]
@indirectlylit Here's the doc:
https://docs.google.com/document/d/1jFpDV1QmT9u3H3ULqib-Pmx4e1f1FUcGrnZXZssnsPc/edit

I'm double checking it and fixing some conflicts, will be monitoring the PR for change requests :)

**Comment by DXCanas** [comment]
Heads up that there have been some other updates:
https://github.com/learningequality/kolibri/commit/96fef6bd25e5f4da2c76c7ebfa85bc5d5a6d9c3d

**Comment by radinamatic** [comment]
@DXCanas A bit too eager with `Full name`? :slightly_smiling_face: 

win10 start running - oracle vm virtualbox_203

**Comment by DXCanas** [comment]
> @DXCanas A bit too eager with `Full name`? 

@radinamatic I hope that was all. I went item by item on the list, so hopefully I didn't miss a Name->Full name somewhere else

**Comment by radinamatic** [comment]
@DXCanas it seems impossible to delete classes...? :confused: 

win10 start running - oracle vm virtualbox_205

**Comment by radinamatic** [comment]
Installed on Windows 10 and went through the doc with master list. Two blockers commented above, and there are a few more comments in the doc.

**Comment by DXCanas** [comment]
Blockers listed above should be resolved @radinamatic

**Comment by radinamatic** [comment]
Awesome, could you & @indirectlylit go through the comments in the doc before I re-test?

**Review by radinamatic — APPROVED** [review]
@indirectlylit If we are good with not having the user counter on `Manage > Users` page, this looks good to me! :100:

**Comment by indirectlylit** [comment]
@DXCanas thanks for this and @radinamatic thanks for doing such a thorough review - much appreciated!

**Pull request merged**
