### PR TITLE
Fix caching issues for remote content API calls

### LINKED ISSUE #11457: [Remote content browsing] Accessing previously failed remote resources returns 410s
## Observed behavior

It seems that, because of some caching, if you clicked a resource without a connection, turned on the connection and tried accessing it again,  it would return the previously failed result. Also, the console fires a 410.

https://github.com/learningequality/kolibri/assets/5203639/60ce04cf-3c11-4023-9f39-4b9f95c3e27c

## Errors and logs

```
Request URL: http://localhost:8000/api/content/contentnode_tree/d6e3b856125f5e6aa5fb40c8b112d5e9/?include_coach_content=true&baseurl=https%3A%2F%2Fstudio.learningequality.org
Request Method: GET
Status Code: 410 Gone (from disk cache)
Remote Address: 127.0.0.1:8000
Referrer Policy: strict-origin-when-cross-origin
```

## Expected behavior

Resources should be able to load correctly when the network connection is back on and stable

## User-facing consequences

Affected resources will not be viewable when the connection is back up.

## Steps to reproduce

1. Go to `http://localhost:8000/en/learn/#/library`. Remote libraries will be loaded.
2. Explore the **Kolibri Library** by clicking `Explore`
3. Once the **Explore Libraries** page has loaded, turn off your wifi connection.
4. Click any resource; you might want to click any in the first two rows (Take note of the resource clicked)
5. You will be redirected back to `http://localhost:8000/en/learn/#/library`(as there is no active connection)
6. Turn on your wifi connection again. Remote libraries will be loaded including the **Kolibri Library**
7. Re-click the resource in 4. above
8. Inpect the console logs for any errors.

## Context

-  Kolibri version: 0.16.x
-  Operating system: Mac OS 14.0 
-  Browser: Chrome (118.0.5993.88 (Official Build) (arm64))

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Fixes issue whereby non-200 responses would get cached
* Fixes content API caching to bypass Django caching middleware, as bespoke caching mechanisms are being used instead
* Fixes public content API endpoints to use matching cache headers to the same endpoints on Studio
* Fixes Etag checking on access to remote libraries by keeping a cache of Etags by baseurl to allow quick 304 responses without having to go to the remote

## References
Fixes https://github.com/learningequality/kolibri/issues/11457

## Reviewer guidance
Load e.g. http://127.0.0.1:8000/api/public/v2/contentnode_tree/d6e3b856125f5e6aa5fb40c8b112d5e9/?format=json and check that refreshes result in a 304 immediately

Likewise for access to remote URLs, such as http://localhost:8000/api/content/contentnode_tree/d6e3b856125f5e6aa5fb40c8b112d5e9/?include_coach_content=true&baseurl=https%3A%2F%2Fstudio.learningequality.org&format=json

Also follow the steps outlined in the issue to ensure that 410s are not being cached.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by akolson** [comment]
It looks like I am still able to replicate the 410s by following https://github.com/learningequality/kolibri/issues/11457 replication steps. Maybe rebasing to include https://github.com/learningequality/kolibri/pull/11459#pullrequestreview-1700355099 changes could prove beneficial?

https://github.com/learningequality/kolibri/assets/5203639/65408e19-6c6a-440e-aaa3-961901ca5f56

**Comment by rtibbles** [comment]
Ugh - no, this seems to be that in spite of refusing to use disk cache for other requests, browsers are very happy to use the disk cache for the 410 response! I'll patch the response headers in this case to prevent caching.

**Comment by rtibbles** [comment]
@akolson I've made one more update to ensure that we add never cache headers to non-200 responses as well, so that browsers are never tempted to cache them!

**Review by akolson — COMMENTED** [review]
Changes look correct and also seem to fix the issue reported. Tagging @radinamatic @pcenov for more manual QA. Thanks @rtibbles

**Review by pcenov — APPROVED** [review]
LGTM as well, no caching issues observed while manually testing.

**Pull request merged**
