### PR TITLE
Command to recover the database: dbrecover

### PR DESCRIPTION
**Pull request by benjaoming**
### Summary

New command `dbrecover` uses external `sqlite3` command to recover the current database. By dumping it and then loading it back in.

Usage:

```
kolibri manage dbrecover  
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
Only use this command to recover a corrupt database. It would (if successful) recover data without any loss. Your old database will be backed up in /home/benjamin/.kolibri/backups. Continue? [y/N)] y
Backed up database to: True
INFO     Beginning database restore
INFO     Searching latest backup in /home/kolibri/.kolibri/backups...
INFO     Using backup file: /home/kolibri/.kolibri/backups/db-v0.9.0.dev+git-20180309174016_2018-03-09_18-45-52.dump
Restored database from: /home/kolibri/.kolibri/backups/db-v0.9.0.dev+git-20180309174016_2018-03-09_18-45-52.dump
```

Works fine except with a corrupt database :)

The reason is that Morango is connecting to the database very early on:  https://github.com/learningequality/morango/issues/48

### Reviewer guidance

Tests are missing currently, will fix that.

### References

#3228 

----

### Contributor Checklist

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] Contributor has fully tested the PR manually
- [x] Screenshots of any front-end changes are in the PR description
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by indirectlylit** [comment]
Hey - did you want this in the 0.8 branch?

**Comment by indirectlylit** [comment]
ah nevermind - I see your comments in the other threads. thanks!

**Comment by aronasorman** [comment]
Is this ready to merge? Looks like it's not doing its intended purpose, which is to recover corrupt DBs (based on your description)

**Comment by benjaoming** [comment]
@aronasorman no, wasn't ready really - 

> Works fine except with a corrupt database :)
> 
> The reason is that Morango is connecting to the database very early on: learningequality/morango#48

(...)

> Tests are missing currently, will fix that.

@indirectlylit what's the reason for this?

>  indirectlylit removed PR: needs review PR: needs updates labels 9 days ago

**Comment by indirectlylit** [comment]
Usually I expect a PR to either "need review" or "need updates"

since it had both labels, I assumed neither was quite correct. In fact, it's probable "work in progress"?

**Comment by benjaoming** [comment]
This won't be ready for 0.9, waiting for Morango changes, and there might be more early-access database obstacles lurking.

**Comment by indirectlylit** [comment]
recommend targeting to develop 0.10.0

**Comment by benjaoming** [comment]
Morango changes decide when this becomes relevant again.

**Comment by indirectlylit** [comment]
> Morango changes decide when this becomes relevant again.

Do you mean that we should clear the milestone until then? Are we waiting until https://github.com/learningequality/morango/issues/48 is resolved?

**Comment by benjaoming** [comment]
The changes to Morango which this PR was waiting for have landed, so can resume work on this...

**Comment by benjaoming** [comment]
Sorry, this has been taking quite a while.

On Ubuntu 18.04, I'm not able to restore the malformed db anymore, using `sqlite3 corrupt.sqlite3 ".dump" > test_restore.sqlite3`

```
sqlite> .dbinfo
unable to read database header
```

In SQLite Manager, the output is just as discouraging:

```
SQLiteManager: Error in opening file test_restore.sqlite3 - either the file is encrypted or corrupt
Exception Name: NS_ERROR_FILE_CORRUPTED
Exception Message: Component returned failure code: 0x8052000b (NS_ERROR_FILE_CORRUPTED) [mozIStorageService.openUnsharedDatabase]
```

**Comment by benjaoming** [comment]
I'm not crazy, the exact same file can be restored with `.dump` on Ubuntu 16.04:

```
test@test-VirtualBox:~$ sqlite3 corrupt.sqlite3 ".dump" > test.sqlite3
test@test-VirtualBox:~$ sqlite3 test.sqlite3 
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> .dbinfo
database page size:  25977
write format:        115
read format:         61
reserved bytes:      79
file change counter: 172115271
database page count: 1229856852
freelist page count: 1094931529
schema cookie:       1330526986
schema format:       1129465153
default cache size:  1413816404
autovacuum top root: 1094863941
incremental vacuum:  1601005927
text encoding:       539124842
user version:        1634625391
application id:      1918989417
software version:    1431063584
number of tables:    0
number of indexes:   0
number of triggers:  0
number of views:     0
schema size:         0
sqlite> 
```

**Comment by benjaoming** [comment]
But I will conclude this venture: It's not feasible to create a management procedure automating a process with so many pitfalls.

It's worth noting that if people in the community forums approach us, the procedure is this:

```
# 1. install sqlite3 client
sudo apt install sqlite3

# 2. backup your corrupt db file
cp ~/.kolibri/db.sqlite3 backup_corrupted_db.sqlite3

# 3. Overwrite it with the .dump command
sqlite3 ~/.kolibri/db.sqlite3 ".dump" > ~/.kolibri/fixed.sqlite3
mv ~/.kolibri/fixed.sqlite3 ~/.kolibri/db.sqlite3
```

**Pull request closed without merging**
