### PR TITLE
html attribute double-quotes

### PR DESCRIPTION
**Pull request by indirectlylit**
Almost all developers (myself being the main exception) have tended to use double-quotes for HTML attributes.

This PR migrates all single-quotes to double-quotes, and adds a linting rule to enforce that convention.

This also addresses @66eli77's concern about embedded javascript strings, allowing us to use the conventional single quotes for inline js strings, e.g.:

```html
   <a :href="'http://' + domain">link</a>
```

### CODE REVIEW

**Comment by jamalex** [comment]
Tyranny of the majority!

I'm wondering whether it might make sense to target mmvp with this, as otherwise we're more likely to have merge conflicts whenever we merge mmvp -> master, since it touches many files. Seems low risk enough?

**Comment by indirectlylit** [comment]
Merging this into mmvp makes me a little uncomfortable just because it touches so many files. I'd prefer holding off with this PR for a week or two until mmvp has truly stabilized?

**Comment by jamalex** [comment]
Sure thing, as you prefer. May need to re-do some quotation-swaps at that point, then, I guess, if anything new is added to the mmvp branch. But if the bug fixes on that branch are truly very minimal, then we probably won't have issues. :+1:

**Comment by jamalex** [comment]
Shall we merge this into master now, then? Looks good to me.

**Comment by indirectlylit** [comment]
let's wait until next week - I'll keep it synced with master in the meantime

**Comment by indirectlylit** [comment]
also, have some failing tests I need to figure out :)

**Comment by indirectlylit** [comment]
closing this PR until after the MVP

**Pull request closed without merging**
