### PR TITLE
Removes CoreBase.vue, Cleans up code, and updates code documentation

### LINKED ISSUE #9235: Remove CoreBase from Kolibri Tools package and then remove CoreBase from Kolibri altogether
There is a TestComponent used for some of the i18n testing in Kolibri Tools that should be removed and replaced with something like AppBarCorePage... or perhaps even a div honestly it's just there to be converted into an AST and tested against and CoreBase has nothing to do with the testing.

Then - remove CoreBase altogether from Kolibri.

:boom:

### PR DESCRIPTION
**Pull request by akolson**
## Summary

This pr removes the CoreBase.vue file, cleans up project of any CoreBase related dependencies and updates the code documentation accordingly.

## References

Closes #9235 

## Reviewer guidance

- Navigate through Coach, Device, Learn, Facility and User Auth plugins to ensure that Kolibri functions as before

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by pcenov** [comment]
@radinamatic no issues caused specifically by these changes were observed during my round of manual testing and all functionalities that are not broken in general in 0.16 (such as Import facility, Generate log files and user CSV, Import users, Filtering by categories) are functioning correctly as before.

**Review by radinamatic — APPROVED** [review]
Manual QA passed, good to go! 💯 :shipit:

**Review by nucleogenesis — APPROVED** [review]
All LGTM! RIP CoreBase

**Comment by indirectlylit** [comment]
nice! happy new year :)

**Pull request merged**
