### PR TITLE
Binary mode for dbbackup/restore (Windows issues)

### PR DESCRIPTION
**Pull request by benjaoming**
### Summary

Supersedes #2952

Bummer, should have opened the file in binary mode to avoid the system's encoding (or lack of) to interfere...

### Reviewer guidance

Could you test on Windows 10, @indirectlylit ?

### References

#2875

----

### Contributor Checklist

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] Contributor has fully tested the PR manually
- [x] Screenshots of any front-end changes are in the PR description
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

### CODE REVIEW

**Comment by benjaoming** [comment]
Before it only worked on Python 2.7 -- now it only fails in Python 2.7

(っ ºДº)っ ︵ ⌨

**Comment by benjaoming** [comment]
It's interesting: If the restore of the database (which is a filesystem level operation) isn't consistent, then the rest of the tests will fail, firstly because the rollback supposed to happen just after the restore fails:

```
self = <django.test.testcases.TestCase testMethod=__init__>
    def _post_teardown(self):
        """Performs any post-test things. This includes:
    
            * Flushing the contents of the database, to leave a clean slate. If
              the class has an 'available_apps' attribute, post_migrate isn't fired.
            * Force-closing the connection, so the next test gets a clean cursor.
            """
        try:
>           self._fixture_teardown()
```

After that, because tables etc. don't exist when they're expected to. Errors like this:

```
    def execute(self, query, params=None):
        if params is None:
            return Database.Cursor.execute(self, query)
        query = self.convert_query(query)
>       return Database.Cursor.execute(self, query, params)
E       OperationalError: Problem installing fixture '/home/travis/build/learningequality/kolibri/kolibri/content/fixtures/content_test.json': Could not load content.ContentTag(pk=1d21d6cf40554b68977366f8218248ae): no such table: content_contenttag
```

**Comment by benjaoming** [comment]
@alanchenz would you be able to test one of these builds on the database that was failing before?

If you are testing this on a system with data that you cherish, I would suggest to make a manual copy of everything called `*.sqlite3` in your `.kolibri/` directory before installing... since the nature of this issue is about not being able to use `dbbackup/restore`. The below is a development release so could potentially contain other issues from our latest updates to the 0.7.x release branch that would make you want to revert. But I have no specific concerns, likely you can just continue using it instead of 0.7.0.

https://storage.googleapis.com/le-downloads/kolibri%2Frelease%2F4607%2Freport.html

**Comment by radinamatic** [comment]
Don't know about @alanchenz, but the reporter from the [community forums](https://community.learningequality.org/t/kolibri-the-server-is-starting-please-wait-kolibri-exe/412/6) did not manage to solve the problem with this build... 😕

**Comment by benjaoming** [comment]
@radinamatic the report in the community forum is about the other issue solved in #3070

**Comment by benjaoming** [comment]
I recommend merging this, since it's confirmed that the specific issue disappeared and was proceeded by an entirely different, but similar issue :)

**Comment by benjaoming** [comment]
@indirectlylit

**Comment by benjaoming** [comment]
Merging now so 0.7.1 can be ready for final testing

**Pull request merged**
