### PR TITLE
Guard against updateTime being called after unmount

### LINKED ISSUE #1276: MP3 interrupted playback: 'currentTime' of undefined
## Summary

Error occurs **in the console** if you navigate away from the player **WHILE** playing the audio...
Nothing in the UI, so not urgent!

## System information

 - Version: 0.4.0alpha3
 - Operating system: both Windows 7 and Ubuntu 16.10
 - Browser: FF & Chrome

## Traceback or relevant snippet from server.log or browser console
Chrome
```
Uncaught TypeError: Cannot read property 'currentTime' of undefined
```
Firefox
```
TypeError: this.$refs.audio is undefined
```

## Screenshots
virtualbox_ubuntu 16 10_21_04_2017_15_11_08

virtualbox_windows 7_21_04_2017_15_15_28

### PR DESCRIPTION
**Pull request by jonboiser**
Fixes #1276 

The error is caused by the `audio` element firing off an event that is handled after the `<audio>` is destroyed. Tried pausing `audio` at `beforeDestroy`, but that didn't seem to work.

So the simplest solution seemed to be to just put a guard inside `updateTime`.

I tried to write a test for this, but got this error trying to run it:
```
TypeError: undefined is not an object (evaluating 'window.navigator.userAgent')
  at webpack:///kolibri/plugins/audio_mp3_render/~/html5media/dist/api/1.1.8/html5media.js:213:0
```
`window.navigator.userAgent` is fine, so I wonder if it has something to do with how webpack config is working in test environment.

### CODE REVIEW

**Comment by indirectlylit** [comment]
That same error came up recently for the MP3 plugin here: https://github.com/learningequality/kolibri/issues/1057

The fix related to the way that webpack imports `html5media`. Maybe a clue for getting the test to work?

**Comment by jonboiser** [comment]
@indirectlylit Yeah, the webpack config for this mp3 plugin wasn't absorbed into the base config, which karma uses. I added a similar line in the base config, and the problem seems to have gone away.

**Comment by jonboiser** [comment]
1. Added the config for html5 media to base/karma webpack config
1. Autofixed lints in karma.conf
1. Added regression test

**Comment by indirectlylit** [comment]
> I added a similar line in the base config, and the problem seems to have gone away.

Sounds like our test environment doesn't handle per-plugin webpack configs, which is something we'll need to fix eventually. Longer-term we probably don't want this in the base config because `html5media` is not a dependency in the base _package.json_.

I added a comment indicating that we want to get rid of it eventually

**Comment by jonboiser** [comment]
I moved the html5media-specific config to karma.conf.js. If plugins are truly independent, it might make sense to give each their own test suite/config. Or one can merge the various webpack configs into a monolithic one for karma, although you never know if they might contradict each other.

**Comment by rtibbles** [comment]
We definitely need a per-plugin testing strategy, to enable testing for external plugins like the kolibri-perseus-exercise-renderer, which is currently untested. This fix will do for now, but that is definitely the long term plan.

**Pull request merged**
