### PR TITLE
Tests uKResponsiveWindow composable and Updates KDS Package to latest develop

### PR DESCRIPTION
**Pull request by akolson**
## Summary

This pr implements the `useKResponsiveWindow` composable in areas where its mixin equivalent(`KResponsiveWindowMixin`) is used particularly in `kolibri/plugins/learn/assets/src/views/LibraryPage/SidePanel.vue` and `kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue` as a test.

Please note that my KDS fork has been referenced for testing purposes. This will be reverted once KDS PR https://github.com/learningequality/kolibri-design-system/pull/377 gets merged

## References

https://github.com/learningequality/kolibri-design-system/pull/377

## Reviewer guidance

1. Navigate to  `http://localhost:8000/en/learn/#/library`
2. Test the window for responsiveness. It should behave as before when using the mixin

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [x] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by radinamatic** [comment]
Tested by running from the source with Firefox on Ubuntu, no regressions on the Learn/Library page when resizing the window, neither manually nor with the Responsive Design Mode.

@pcenov Could you grab the Windows asset and test with Chrome? Thank you!

**Comment by pcenov** [comment]
Hi @akolson and @radinamatic the main regression I see is that the Library page cannot be opened any more in Internet Explorer:



I couldn't find any other issues in the rest of the supported browsers, but I do have plenty reported here: https://github.com/learningequality/kolibri/issues/9726

**Comment by radinamatic** [comment]
> Library page cannot be opened any more in Internet Explorer

Oouch, thank you for fishing that out, I tend to forget IE11 (wishful thinking, I know 😒)

**Comment by akolson** [comment]
Great catch @pcenov. Fixing this. Thanks

**Comment by akolson** [comment]
@radinamatic @pcenov. The issue with IE should be resolved now!

**Comment by pcenov** [comment]
@akolson I confirm that now the Library page can be opened in IE however the responsiveness is not functioning correctly. For example if I shrink the window while at the Library page the filters section never goes in mobile view, while if I go in mobile view and then expand the window the filters section doesn't go back to desktop mode:

https://user-images.githubusercontent.com/79847249/195538853-ac91a8c9-186b-4ccb-8fc1-3520eec69bab.mp4

**Comment by akolson** [comment]
Hi @pcenov, Thanks for the feedback. I have fixed the issues with responsiveness on IE so we should be good now!

**Comment by pcenov** [comment]
Awesome @akolson - everything looks fine now in all supported browsers! :)

**Review by radinamatic — APPROVED** [review]
Manual QA passes, good to go! 💯 :shipit:

**Comment by akolson** [comment]
PR has been updated to the latest KDS commit

**Pull request merged**
