### PR TITLE
Disable arrows on Paginated Lists if there are no results in the table

### LINKED ISSUE #6335: User counts label are not in the same position
### Observed behavior
The user counts label are not in the same position in two different browsers

### Expected behavior
User counts label should be in the same position

### User-facing consequences

…

### Errors and logs
Screen Shot 2019-12-16 at 12 34 08 PM

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: 0.13.0b7
 * Operating system: Windows 7
 * Browser: Firefox and IE11

### LINKED ISSUE #6454: Disabled arrows button can click on Microsoft edge browser
### Observed behavior

In Facility > users page, I tried to click the disabled arrow button and its goes to next.
arrow_button2
 

### Expected behavior

The disabled arrow button must be not click.
### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

1. Sign as super admin or admin facility
2. Go to Facility > Users page
3. Click the disabled arrow button

### Context

Tell us about your environment, including:
  Kolibri version : 0.13.0
  Operating system: Windows 10 Pro 2015
  Browser: Microsoft Edge 20.10240.16384.0

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

1. Disables the forward arrow button in PaginatedListContainer if there are no results (e.g. when the filter does not match anything)
1. Some code style changes to match new ESLint rules
1. Change CSS rule for `nav` fixes #6335
1. Clamps the page range to fix unusual behavior in old versions of MS Edge. Fixes #6454 

This is what it should look like. Before, the right button would not be disabled.

Screen Shot 2020-01-13 at 2 08 19 PM
…

### Reviewer guidance

@mrpau-julius , can you see if this fixes the bug you saw in #6454 using Edge 20?

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by mrpau-julius** [comment]
@jonboiser I download the installation in build kite and test on it. But still have a bug on Edge version 20.
image
 I made an OVA file at this link. https://drive.google.com/drive/u/0/folders/10TfBkMFKNYSSqmbEMsJX4lk5GPJiA0So
In case you need it. 

Kolibri account:
Username: admin
Password: pass

**Comment by jonboiser** [comment]
@mrpau-julius Thanks for checking this on Edge 20. The OVA is a little too big for me to download, so I added some new code that I think might fix the issue on Edge. Could you try it again with the latest MS Installer?

**Comment by mrpau-julius** [comment]
@jonboiser I done testing the new installer built in buildkite, it fixed the disable forward button if theirs few data user. When I import more user data using `kolibri manage import many-users. csv` on terminal and refresh the browser and check the activity of the button I discover it's still disable even if it have a 186 users. I tried to click on and it goes next. I open the Firefox browser to check, but it's still disable and not clickable. I think it might be not disable if theirs a lot of created users. 

new_issues_on_forward_button

**Comment by jonboiser** [comment]
@mrpau-julius Thanks for finding that. That was due to a typo. Could you try it again? The "->" button should not be disabled when you're on the first page any more. Edge still acts weird in that it's still allowing disabled buttons to emit a "click" event, but when you get to the first page, "<-" should be disabled and not do anything when you click it. Similar with "->" on the last page.

**Review by mrpau-julius — APPROVED** [review]
@jonboiser I done tested it again. Nice fixed, both arrow button are now back to normal behavior.

**Review by nucleogenesis — APPROVED** [review]
Code looks good - works in testing :+1:

**Pull request merged**
