### PR TITLE
Fix python black issues in develop

### PR DESCRIPTION
**Pull request by bjester**
### Summary

A new version of `black` was released yesterday. This makes fixes for incorrectly formatted code for the new version.
https://github.com/psf/black/releases/tag/19.10b0

### Reviewer guidance

- Review the changes
- Does the `pythonblack` suite complete successfully?

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
Weird - did our version of black update?

**Comment by bjester** [comment]
@rtibbles They released a new version yesterday so I believe so. The changes seem to make sense to me. How about to you?

**Review by rtibbles — APPROVED** [review]

**Comment by rtibbles** [comment]
Yeah - it looks like they chose 'even more lines' as the new default option.

**Comment by indirectlylit** [comment]
Shouldn't our `black` version have been pinned? This could be problematic for people who run black locally, e.g. https://github.com/learningequality/black-fmt

Luckily this is a small change, but we should alert people to upgrade locally and fix `black-fmt` now

**Comment by bjester** [comment]
@indirectlylit Ooh, good catch. Although, I just ran `npx black-fmt` locally on the latest `develop` with these updates and it didn't want to revert them.

**Comment by indirectlylit** [comment]
>  it didn't want to revert them

Okay, that's great

**Comment by bjester** [comment]
@indirectlylit Looks like it was using your `black-fmt` but was changed, and is using unpinned black
https://github.com/learningequality/kolibri/blob/develop/tox.ini#L123
https://github.com/learningequality/kolibri/pull/5795

**Comment by bjester** [comment]
@indirectlylit I could create a PR to update `black-fmt` to the same version?

**Comment by indirectlylit** [comment]
Darn, looks like I missed that change during code review. @benjaoming I don't understand your motivation for un-pinning. Can you elaborate?

> I could create a PR to update black-fmt to the same version?

Could do. It's sort of a hassle because we need to build the binaries on [old versions](https://github.com/learningequality/black-fmt#development) of both linux and mac.

**Comment by benjaoming** [comment]
> Darn, looks like I missed that change during code review. @benjaoming I don't understand your motivation for un-pinning. Can you elaborate?

I don't understand where the black requirement is specified! Where'd I unpin it?

**Comment by indirectlylit** [comment]
> Where'd I unpin it?

see https://github.com/learningequality/kolibri/pull/5795/commits/b7828f777278ddbbda52fadfb9edb18f8eb0e590

(the `black-fmt` package contains pinned (compiled binaries) of `black`)

However, we still run into a problem with people who choose to use their own system installations of `black`, in which case we still need to document the "correct" version to install...

These sorts of issues are inevitable since we've chosen to use it in it's beta state: https://github.com/psf/black#note-this-is-a-beta-product

**Comment by benjaoming** [comment]
Ah, I looked in 0.12.x branch by mistake. Yes, I recall this comment:

```
# black is unpinned because they have no useful version semantics,
# so better to break immediately and decide from there
```

This is the CI run code.

IIRC, pre-commit addresses these issues of linting tool versions by pinning versions in git repositories and automatically changing/bumping.

A concern that I'd have in any case is how we ensure that changes to old branches don't prompt a bunch of code formatting.

**Comment by indirectlylit** [comment]
FYI, we also intentionally started moving away from `pre-commit` because it was messing with some developers' workflows: https://github.com/learningequality/kolibri/issues/5409

**Pull request merged**
