### PR TITLE
Automatic Mac Builds

### PR DESCRIPTION
**Pull request by DXCanas**
### Summary

Pulled this out of some of my pipeline refactor work to get it in on time. Some hacks (one pipeline uploading to another) was necessary to get the artifacts to go to the appropriate places and show up on the right page. That's likely to be redone later.

Why WIP? Installer isn't signed yet. Not guaranteed to be in, but working on it until EOD on Friday November 14th, 2019.

### Reviewer guidance

- Monitor buildkite progress
- Check and see if a mac installer shows up on the generated HTML page under details
- Log into buildkite and see if the MacOS pipeline was triggered properly
- Download the macos installer for this PR and test it

### References

- #1 

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by indirectlylit** [comment]
uh oh!

```
Loading .env environment variables…
--
  | Traceback (most recent call last):
  | File "/Users/david/.local/share/virtualenvs/wip-kolibri-macos-flDa6jKx/bin/pew", line 3, in <module>
  | import re
  | File "/Users/david/.local/share/virtualenvs/wip-kolibri-macos-flDa6jKx/lib/python3.6/re.py", line 142, in <module>
  | class RegexFlag(enum.IntFlag):
  | AttributeError: module 'enum' has no attribute 'IntFlag'
  | 🚨 Error: The command exited with status 1
```

**Comment by DXCanas** [comment]
Handles everything I throw at it no problem. Submit a pr and everything falls apart

**Comment by rtibbles** [comment]
Updated milestone to 0.13.0.

**Comment by indirectlylit** [comment]
it built!

However I still don't see any artifacts:

----
image

----

image

**Comment by rtibbles** [comment]
Definitely won't be in our custom artifact listing, but odd that it is missing from buildkite. @DXCanas did you add the buildkite artifact upload step?

**Comment by DXCanas** [comment]
I actually tried adding it to our custom artiact listing @rtibbles - That's precisely the reason it's not showing up in the artifact upload step

It's a bit of a hack, since I'm planning on reworking the custom artifact listing. I'm uploading to a step in the main pipeline from the macos pipeline, to a step whose GUI doesn't support displaying artifacts (a trigger step).

Would you mind taking a look at my modifications to the script to see what I missed?

**Comment by rtibbles** [comment]
Sorry, I think it's because there are two places you have to list the file:
https://github.com/learningequality/kolibri/blob/develop/.buildkite/upload_artifacts.py#L95

Try adding `dmg` to the `file_order` list and that should upload it. Nice work.

Also looking forward to when you refactor the upload_artifacts script :)

**Comment by DXCanas** [comment]
@rtibbles thanks for the tip!! Have some cool ideas in store :)

Seems to be building and uploading @indirectlylit 🎉

**Review by indirectlylit — APPROVED** [review]
nice!

**Pull request merged**
