### PR TITLE
Remove DEBUG=True from the base settings.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

See title.

## Issues addressed

Helps with observation of DEBUG template rendering observed in #537 .

### CODE REVIEW

**Comment by aronasorman** [comment]
@benjaoming I think this person who committed this line, added it while he was testing the PEX executable. He's currently blaming the reviewer though for not catching this :)

**Comment by indirectlylit** [comment]
I believe this PR broke master?

Now running `kolibri manage devserver -- --webpack` results in client errors:

```
GET http://localhost:8000/static/default_frontend/default_frontend-a7cc8b2009a908aa23dd.js 
(index):51 Uncaught ReferenceError: kolibriGlobal is not defined(anonymous function) @ (index):51
(index):75 Uncaught ReferenceError: kolibriGlobal is not defined(anonymous function) @ (index):75
(index):85 Uncaught ReferenceError: kolibriGlobal is not defined(anonymous function) @ (index):85
(index):86 Uncaught ReferenceError: kolibriGlobal is not defined(anonymous function) @ (index):86
(index):87 Uncaught ReferenceError: kolibriGlobal is not defined(anonymous function) @ (index):87
(index):88 GET http://localhost:8000/static/learn_module/learn_module-871aaf80c25eb497118e.js 
loading-spinner.gif:1 GET http://localhost:8000/static/images/loading-spinner.gif 404 (Not Found)
```

(Running `kolibri start` still seems to work)

**Comment by aronasorman** [comment]
@indirectlylit I think you'll need to add another option now: `--settings=kolibri.project.default.settings.dev`. 

But it looks like there's no dev setting bundled in. Can add that in another PR.

**Comment by rtibbles** [comment]
Note, @indirectlylit you should be running with the `--debug` flag as stated in the docs: http://kolibri.readthedocs.io/en/latest/dev/getting_started.html#run-the-server perhaps this got elided in your command history since August 12th when this DEBUG setting snuck in?

**Comment by indirectlylit** [comment]
ah, perhaps. I've never used that flag and never had this issue before, but I'll start using it now.

**Comment by indirectlylit** [comment]
correction - looks like `--debug` is in my command history so I did use it at some point.

**Pull request merged**
