### PR TITLE
Simple database backup and restore, automatic at upgrade

### PR DESCRIPTION
**Pull request by rtibbles**
# Checklist

- [X] PR has the correct target milestone when it's merged
- [ ] Automated test coverage is satisfactory
- [x] PR has been fully tested manually
- [X] CHANGELOG.rst is updated for high-level changes

# Details

Opening after some initial testing of #2428 and hopefully some fixes on 0.6 that will make this work how we want!

### CODE REVIEW

**Comment by rtibbles** [comment]
Can confirm that this now works as intended.

**Comment by radinamatic** [comment]
[`pex` asset from here](https://storage.googleapis.com/le-downloads/kolibri%2Frelease%2F3132%2Freport.html), seems to behaving well: created db backup is named after the `pex`, and only after expressly running the the command `kolibri manage dbbackup`, not after every start:

fullscreen_20_10_17_06_55

Will try `exe` next!

**Comment by radinamatic** [comment]
Backup & Restore working correctly on Windows too! 

fullscreen_20_10_17_07_53


```
C:\Python27\Scripts>kolibri manage dbrestore --latest
[37mINFO     Beginning database restore[0m
[37mINFO     Searching latest backup in C:\Users\IEUser\.kolibri\backups...[0m
[37mINFO     Using backup file: C:\Users\IEUser\.kolibri\backups\db-v0.6.dev020171020002556-git_2017-10-20_07-42-52.dump[0m
Restored database from: C:\Users\IEUser\.kolibri\backups\db-v0.6.dev020171020002556-git_2017-10-20_07-42-52.dump
```
Haven't tried the full revert to 0.5, will see if I can try that later.

**Comment by indirectlylit** [comment]
thanks all

**Pull request merged**
