### PR TITLE
Don't display LOD sync or cleanup sync tasks on the Facility Tasks page

### LINKED ISSUE #11543: Facilites task manager not displaying task details
## Observed behavior
Task data is not displayed, just the green checkmark 🙂 

Facility with a lot of tasks | Facility with less tasks
-- | --
 | Selection_226

The first image is from the facility that had a lot of syncing with LoDs, while the second is from another device where I imported the first facility in full.
 
## Errors and logs
None that I could see in the console

## Expected behavior
Proper detail about the past tasks should be available to the user.

## User-facing consequences
Inability to check the history of the facilities syncing tasks. UI seems broken.

## Steps to reproduce
Wait for some syncing tasks to be completed and check the Facilities task manager page.

## Context

 * Kolibri version: EXE asset from #11525 
 * Operating system: Windows 10
 * Browser: Firefox & Chrome

### PR DESCRIPTION
**Pull request by marcellamaki**
## Summary
Adds a condition so that LOD sync tasks and related cleanup sync tasks are not displayed on the facility task management page. Display all of these tasks here would potentially overwhelm the user and provide information that is not useful to facility syncs specifically

## References
Fixes https://github.com/learningequality/kolibri/issues/11543

| Before | After  |
|---|---|
| Screenshot 2023-11-21 at 2 38 46 PM | Screenshot 2023-11-21 at 2 38 26 PM |

## Reviewer guidance
In a LOD scenario, navigate to the facility task page. Perform different tasks such as importing a facility, as well as some LOD syncing. With this update, the facility import task should display, for example, but "blank" tasks related to LOD or cleanup syncs should not display. 

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by bjester — APPROVED** [review]
This seems like an acceptable change. I've now realized the reason for the `cleanupsync` task appearing is because it's in the [`facility_task_queue`](https://github.com/learningequality/kolibri/blob/cc8d5bda16321d42def450f095b993c90257ef0f/kolibri/core/auth/tasks.py#L651). So alternatively, we could remove it from that queue and it shouldn't appear anymore. Although, as the queue is used to group tasks, it does make sense to exist in that queue. :shrug: 

So that said, LGTM

**Review by bjester — CHANGES_REQUESTED** [review]
On second thought (shared more on Slack), I think we should remove the [queue](https://github.com/learningequality/kolibri/blob/cc8d5bda16321d42def450f095b993c90257ef0f/kolibri/core/auth/tasks.py#L651) from the task instead. That will stop the `cleanupsync` task from being returned by the API, and prevent the API response from being bloated by these hidden tasks. The LOD tasks are already in a different queue. My bad for forgetting how the queue was utilized for this in the first place!

**Comment by radinamatic** [comment]
LoD syncs may have been removed correctly from the task list , but they still appear in the counter on the Device - Facilities page:


https://github.com/learningequality/kolibri/assets/1457929/7aceba18-dfe4-4f42-9cb1-a1ed5f035eb7

**Comment by bjester** [comment]
> LoD syncs may have been removed correctly from the task list , but they still appear in the counter on the Device - Facilities page:

Removing the queue will also resolve this.

**Review by bjester — APPROVED** [review]
I guess I approve these changes :smile:

**Comment by marcellamaki** [comment]
I also approve it 😄

**Pull request merged**
