### PR TITLE
add 2 fields to ContentMetadata that are required by content curation

### PR DESCRIPTION
**Pull request by 66eli77**
## Summary

sort_order and license_owner fields are added to ContentMetadata.

## TODO

- [x] Has documentation been written/updated?

## Reviewer guidance
please run 'kolibri manage makemigrations' and 'kolibri manage migrate' after pull this new fields

### CODE REVIEW

**Comment by rtibbles** [comment]
Test failures? Do the fixtures need updating?

**Comment by 66eli77** [comment]
both fields have "blank=True, null=True", they are not in the fixture if no value assigned to these fields. I dumped the data, and checked. If there's test failure, shouldn't be fixture.

**Comment by rtibbles** [comment]
So what is the test failure here?

**Comment by 66eli77** [comment]
seems the failure comes from plugin.py

**Comment by 66eli77** [comment]
@rtibbles test passed, please merge

**Pull request merged**
