### PR TITLE
Remove direct dependency on ifcfg and use zeroconf.get_all_addresses

### PR DESCRIPTION
**Pull request by jamalex**
As discussed on Slack.

### CODE REVIEW

**Review by kollivier — APPROVED** [review]
💯

**Comment by benjaoming** [comment]
@jamalex @kollivier For 0.14, we could add a patch for ifcfg for Android support and release it through ifcfg (we co-maintain that project).

**Comment by indirectlylit** [comment]
> As discussed on Slack.

ref: https://learningequality.slack.com/archives/C5XMC1EAV/p1586039733091800

**Comment by benjaoming** [comment]
Slack discussion doesn't note why Android support couldn't be added to ifcfg.

**Pull request merged**
