### PR TITLE
feat: dynamically add title on shaved text

### LINKED ISSUE #7557: `TextTruncator` component does not provide a way to read the hidden text
### Observed behavior

I noticed this on the Channel cards and breadcrumbs, but it's probably a pretty widespread issue.

Basically, if a long piece of text is truncated, I don't think there's a way for me to _read_ the full-text without navigating somewhere else.

Screenshots of places in the app. Sighted users cannot read the text hidden by "..." without navigating elsewhere. 

(The first one's not a good example because we're _in_ the topic and you see the header below, but imagine if you go a level deeper, then the breadcrumb would be truncated)

image

image

image

### Expected behavior

I'm not sure how to handle this universally, but a general pattern is to give link-like things a `title` attribute so the full-text will be shown on most browsers when you hover over the link long enough.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

### PR DESCRIPTION
**Pull request by Kalovelo**
### Summary
resolves #7557 

When a user hovers over a shaved text, the whole text is shown via the browser's tooltip. The title attribute is set only on shaved texts. If the user changes the resolution to a bigger screen and the text is no longer shaved, the title's attribute is removed.

Before Hovering:
image

After Hovering over title:
image

### Reviewer guidance
1. Hover over a truncated text
2. Change the resolution in order to test the responsiveness

### References
resolves #7557 

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by jonboiser** [comment]
@radinamatic Can you take a look at this? I think using the `title` attribute is a good basic strategy. 

This combined with #7914 should resolve a large class of readability issues on the Content Cards

**Review by jonboiser — APPROVED** [review]
Looks good, thanks!

**Comment by jonboiser** [comment]
@radinamatic I think I will also retarget #7914 for 0.14.7, since this will be a nice addition to the fixes we made to KM UI messages. So with all of these patches, the reading experience in KM for both content like Khan Academy (km) and UI will be greatly improved.

**Comment by radinamatic** [comment]
Excellent, thank you @Kalovelo! 💯 

> So with all of these patches, the reading experience in KM for both content like Khan Academy (km) and UI will be greatly improved.

Great news @jonboiser, much beauty indeed... ❤️ 🤩

**Pull request merged**
