### PR TITLE
Fixed file reading error- Windows not replacing slashes correctly before

### PR DESCRIPTION
**Pull request by jayoshih**
## Summary
Fixed plugin path reading

## TODO
- [N] Have tests been written for the new code?
- [N] Has documentation been written/updated?
- [N] New dependencies (if any) added to requirements file
- [N] Add an entry to CHANGELOG.rst
- [N] Add yourself it AUTHORS.rst if you don't appear there

## Issues addressed
Windows webpack not replacing slashes correctly, causing IO error.

### CODE REVIEW

**Comment by rtibbles** [comment]
We can't write automated tests for this, as we don't test on Windows. Wah-wah.

**Comment by MCGallaspy** [comment]
> don't test on Windows

Says who? I do it routinely.

**Comment by rtibbles** [comment]
As in, Travis doesn't run tests in a Windows environment for us.

**Comment by benjaoming** [comment]
```
if sys.system == 'nt`:
    os.system("format C:")

**Pull request merged**
