### PR TITLE
Use studio.leq as the canonical download source

### PR DESCRIPTION
**Pull request by aronasorman**
has caching, and works with our branding.

### CODE REVIEW

**Comment by indirectlylit** [comment]
do you want this in 0.6 or develop?

**Comment by aronasorman** [comment]
0.6 for now, to give it more time for testing. Once regular devs are using it, then I think it should be good for mainline kolibri.

**Comment by indirectlylit** [comment]
not sure what you mean by mainline kolibri... is that `master` or `develop`?

> 0.6 for now

okay I'll change the target

**Comment by indirectlylit** [comment]
after changing the target, looks this was based off a different branch: https://github.com/learningequality/kolibri/pull/2228/commits

**Comment by aronasorman** [comment]
Oh sorry, I meant develop, to give it more time to simmer and for testing :)

**Comment by aronasorman** [comment]
Changed it back to develop again.

**Pull request merged**
